Added "ggplotgui" code
africanmathsinitiative/R-Instat pull request #5164
Opened 2019-02-07 12:07 UTC by Ogik99

fixes #5146 
@africanmathsinitiative/developers this is ready for review.

2019-02-07 12:24 UTC, maxwellfundi commented on instat/dlgGraphsGUI.vb
> +Imports instat
This line can be removed. Its not needed!

2019-02-07 12:25 UTC, maxwellfundi commented on instat/dlgGraphsGUI.vb
> +
This empty sub can also be removed @Ogik99

2019-02-07 12:36 UTC, Ogik99 commented
@maxwellfundi I have made the recommended changes. Kindly review.

2019-02-08 06:15 UTC, dannyparsons commented
@Ogik99 @Ivanluv thanks for working on this. The dialog set up is ok but the R connection has some issues of crashing while the app is running. We'll have to keep looking into this and hopefully have it working for the next released version.

2019-02-26 12:58 UTC, maxwellfundi commented
@dannyparsons A quick reminder to have a look on this.

2019-02-27 12:59 UTC, dannyparsons commented
Yes I couldn't see an easy way to solve the crashing issue. It might be to be in touch with rdotnet developers.

2019-03-01 06:37 UTC, Patowhiz commented on instat/dlgGraphsGUI.vb
> +
Though trivial, you could have the entire if statement as 1 line  `ucrBase.OKEnabled(Not ucrReceiverGraphs.IsEmpty)`

2019-03-01 06:39 UTC, Patowhiz commented
@dannyparsons  So are we still going to add it to the menu and have it accessible?

2019-03-01 08:04 UTC, dannyparsons commented
Not yet as its currently unstable, but yes once we resolve this.

2020-05-18 10:48 UTC, shadrackkibet commented
@Ogik99 what is the state of this? Anything remaining?

2020-07-10 10:28 UTC, lloyddewit commented
@Patowhiz Please could you try and complete this PR? @rdstern suggested this.

2020-07-12 11:04 UTC, Patowhiz commented
@lloyddewit thank you.  Will take it up

2020-07-27 08:58 UTC, lloyddewit commented
@Patowhiz Did you get a chance to look at this? thanks

2020-08-15 15:22 UTC, Patowhiz commented
Yes. I'm doing this in a separate branch which I will push once my questions are answered in issue #5146. Its clear to me that this dialog needs a package that is dependent on other major packages, which they are currently not shipped with R-Instat.

2020-11-04 18:31 UTC, rdstern requested changes
It would be great if this could be added.  It is from Feb 2019 from @dannyparsons so could he re-allocate this?

2020-11-05 08:36 UTC, lloyddewit commented
@rdstern @dannyparsons @Patowhiz 
I suggest that @patowhiz:
- tests that installing packages `devtools` and `ggpoltgui` do not cause any issues for R-Instat
- if ok, create new issue `Packages for next version` similar to issue #5976
- links this issue to this PR
- completes this PR

If I misunderstood anything or you have other comments then please let me know, thanks

2020-11-05 18:34 UTC, dannyparsons commented
`devtools` is already a package included in R-Instat so that's not an issue. I think the issue is whether we can launch a shiny app from within R-Instat.

If it doesn't work, there might not be much we can do as it may be an issue with rdotnet. To test this I would suggest making a test VB repo with a single form that uses rdotnet to launch the shiny app and see if it works. e.g.

Imports RDotNet

```vb
Public Class Form1

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim engine As REngine

        REngine.SetEnvironmentVariables()
        engine = REngine.GetInstance()
        engine.Initialize()

        engine.AutoPrint = True

        engine.Evaluate("some_r_code")
    End Sub
End Class
```

If it works then we should be able to get it working in R-Instat too. If not, then we could report to the rdotnet repo but probably can't do anything ourselves.

2022-01-17 09:46 UTC, lloyddewit commented
No work was done on this PR for nearly three years so I closed this PR. It is still available for reference if needed (this PR is referenced in issue #5146).

2022-01-17 09:46 UTC, closed without merging