Detect list of Datasets
africanmathsinitiative/R-Instat pull request #5836
Opened 2020-06-13 04:50 UTC by Patowhiz

Fixes #5649 
@africanmathsinitiative/developers this is ready for review.
Some of the R commands may need to be changed. Open to more correct commands for coercing the matrix object types to data frame. See my comments in issue.

2020-06-29 12:43 UTC, lloyddewit commented
@shadrackkibet, @Ivanluv reading this PR and the related PR #5649, I understand that this is ready for your test/review. Please could one of you do this? thanks

2020-06-29 12:57 UTC, shadrackkibet commented
@Ivanluv you have worked on this dialog before. I think you are best suited to review otherwise, I am happy to review.

2020-06-29 14:22 UTC, Patowhiz commented
@lloyddewit the issue raised is generally very straightforward to solve and I have solved it. However upon looking into the datasets further, I realised to solve even future issues (feature requests) that relate to this in away, more needs to be done. I have asked for some inputs and feedback from @shadrackkibet and @rdstern in the best way to fully solve these possible future feature requests.  @lloyddewit your thoughts on my inquiries on the issue ( #5649 ) will help too.

2020-06-30 06:44 UTC, lloyddewit commented
@Patowhiz Thank you for the response. I suggest that we review and close this PR based on the specific issue it was designed to solve. 
Please could you make a new issue that describes the future issues (feature requests) that you describe above?
If there are related issues then please could you ensure that they're correctly cross-referenced? Or you could consider combining them into a single, clearly explained issue (you're good at explaining things!). Thanks

2020-07-01 00:01 UTC, Patowhiz commented
@lloyddewit thanks. I'll separate the issues and have further discussions on them with @rdstern

2020-08-07 14:31 UTC, Patowhiz commented
@lloyddewit this is ready for your review. It fixes the original issue raised by @rdstern . As discussed above, the extra issues will be addressed in another PR as soon as I get more feedback from @rdstern on them.

2020-08-08 08:22 UTC, lloyddewit commented
@Ivanluv Please could you peer review? thanks

2020-08-17 10:09 UTC, lloyddewit commented
@Ivanluv Please could you peer review? thanks

2020-08-18 08:41 UTC, Ivanluv commented
Am doing this now

2020-08-19 06:30 UTC, lloyddewit commented
@Ivanluv Thank you for your review (as discussed via Skype).

@rdstern Please could you test? thanks

2020-08-19 07:38 UTC, rdstern approved these changes
I tried @Patowhiz changes pretty extensively including all the examples in agricolae, and hydroTSM and also the matrix in xts.  It all seems to work now!

2020-08-19 09:02 UTC, lloyddewit requested changes
@Patowhiz I found the code structured and readable. I especially liked your use of comments. There's just a couple of small suggestions, we can then merge. Thank you!

2020-08-26 15:22 UTC, Patowhiz commented on instat/dlgFromLibrary.vb
> +            ElseIf strRClass = "matrix" Then
@lloyddewit yes. However notice my comment below the if statement that follows. I separated the block in anticipation of future changes. I've also pointed out the reason in the issue quoted in the comment. 

```
'this has been done in it's own block in anticipation of a correct way of coercing matrix to data frame
'currently this command loses data(some columns) of the matrix once it's coerced. See issue #5649
```
I'm still happy to combine the blocks to 1 case block and have 2 comments into the block, though I think it may be confusing in future to someone else as to why they are in the same block. The class types are different and the intention is to demonstrate that their coercion implementation will be different.

2020-08-26 15:34 UTC, Patowhiz commented on instat/dlgFromLibrary.vb
> +            If strRClass = "zoo" Then
I agree

2020-08-26 15:38 UTC, Patowhiz commented
@rdstern yes the import works. Doing this task made me realise on the numerous R class types there are when it comes to datasets in general, and different packages tend to support coercion into data.frame type but with loss of data. To nail the import well we may have to work on the R code used as the R link importing datasets and dataframes in general. Will proceed with this discussions in the issue. Thank you.

2020-08-27 05:58 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +            ElseIf strRClass = "matrix" Then
@Patowhiz thank you for the explantion, I agree with you, please ignore my comment.

2020-08-27 05:59 UTC, lloyddewit approved these changes

2020-08-27 05:59 UTC, lloyddewit commented
@rdstern Please could you reapprove? thanks

2020-08-27 14:33 UTC, rdstern approved these changes
It still looks fine

2020-08-30 07:10 UTC, merged