Adding memory of directory and filename to export & save dialogs
africanmathsinitiative/R-Instat pull request #5873
Opened 2020-06-29 23:55 UTC by Patowhiz

Fixes #5606

This PR affects 4 dialogs `dlgExportDataset`, `dlgExportGraphAsImage` , `dlgExportRObjects` , `dlgExportRWorkspace` , `dlgSaveAs` 

@africanmathsinitiative/developers this is ready for review

2020-07-06 07:36 UTC, lloyddewit commented
@Ivanluv Please could you review this PR? thanks

2020-07-09 22:45 UTC, Patowhiz commented
@lloyddewit @dannyparsons upon looking this code much further, I realised that the consistent code repetition has reached my threshold of warranting a custom control. In this case, I'm thinking of a custom control that has a `ucrInput` and a _browse_ `button`. This control can be implemented in a way that it handles the click events (for both `ucrInput `and the _browse_ `button`),  processing of file paths, _memory_ functionality, in a more generic way. With this kind of implementation then we can reduce the lines written in these dialogs (and other similar dialogs) by a huge factor (almost down to 1 line of code).

So @lloyddewit as you go through the code please check if my thoughts resonate with yours in regards to this, if they do, I can create an issue about this and have further discussions with the team.

2020-07-09 22:55 UTC, Patowhiz commented
On a separate note, I noticed that there are design changes that will conflict with @lilyclements changes in PR #5880, So this PR should not be merged until that PR is merged. I will sort out the conflicts.

2020-07-11 09:08 UTC, lloyddewit commented
@Patowhiz PR #5880 is now merged. I understand that this allows you to prepare this PR for peer review? thanks

2020-08-07 12:24 UTC, Patowhiz commented
@lloyddewit thanks for the notification. Yes I have resolved the conflicts. This is ready for your review. Please also take a look at my comment. Thank you

> @lloyddewit @dannyparsons upon looking this code much further, I realised that the consistent code repetition has reached my threshold of warranting a custom control. In this case, I'm thinking of a custom control that has a `ucrInput` and a _browse_ `button`. This control can be implemented in a way that it handles the click events (for both `ucrInput `and the _browse_ `button`), processing of file paths, _memory_ functionality, in a more generic way. With this kind of implementation then we can reduce the lines written in these dialogs (and other similar dialogs) by a huge factor (almost down to 1 line of code).
> 
> So @lloyddewit as you go through the code please check if my thoughts resonate with yours in regards to this, if they do, I can create an issue about this and have further discussions with the team.

2020-08-08 08:09 UTC, lloyddewit commented
@Patowhiz yes, good suggestion. There is a lot of repeated code across the 5 dialog boxes. I agree that the best solution would be to create a new custom control (repetition could be handled in other ways but a new ucr would be the most consistent with R-Instat's current approach). 
The question is do we make the new ucr as part of this PR or do we raise a new issue for it? If you think that you could complete this PR within 2 weeks with a new ucr (and it doesn't impact your other work too much), then it would make this PR more readable and robust. So this would be my preference. If you prefer to spin off the ucr to a new issue then that's also fine.
What's do you recommend?

2020-08-10 07:58 UTC, Patowhiz commented
@lloyddewit will complete the new control by end of today. I've created a new PR #5924 with an empty control which should be merged immediately to avoid conflicts cause by solution changes, I'm adding the functionality code in this PR and will have it ready for review by end of today.

2020-08-10 14:57 UTC, Patowhiz commented
@lloyddewit @rdstern this is now ready.
It has the changes that demonstrate how the `ucrInputFile` control can be used. You can review it once PR #5924 is merged.

2020-08-11 07:56 UTC, lloyddewit commented
@Ivanluv This PR is now ready for your review.

@Patowhiz Thank you for completing this so promptly. I noticed that this PR still contains changes to the `.vbproj` file. Are these changes still needed now that PR #5924 is merged?

2020-08-11 08:59 UTC, Patowhiz commented
@lloyddewit I'm not seeing any change to the '.vbproj' file. Maybe it was cause I had not synchronised the changes from the master. From my end only 17 files are shown to be changed. All of which relate to this dialogs changed by this PR.

2020-08-11 09:12 UTC, lloyddewit commented
@Patowhiz The `.vbproj` file is now removed from the list. I think it was fixed by the synchronization with master a few minutes ago, thanks

2020-08-17 10:12 UTC, lloyddewit commented
@Ivanluv Please could you review this PR? thanks

2020-08-18 08:40 UTC, Ivanluv commented
@lloyddewit  am okay with these changes

2020-08-19 07:03 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2020-08-19 13:35 UTC, rdstern requested changes
It seems to work.  One small additional item for @Patowhiz is in the export dialogue.  It does remember the directory, but not the type of data.  So the default is a csv file.  I saved as excel, but each time I return it is back to csv.  Could it please also remember the last type of file.
The save seems fine.

2020-08-26 15:06 UTC, Patowhiz commented
@rdstern thanks for the observation. I have now added that feature.

2020-08-30 10:42 UTC, lloyddewit requested changes
@Patowhiz This looks excellent. I especially liked the clarity/consistency between the different dialogs, the `Using` statement and the XML comments.
I only have some small suggestions and questions. If you can accept/reject these then I can approve.
Thanks

2020-08-30 10:42 UTC, lloyddewit commented on instat/dlgExportGraphAsImage.vb
> +        ucrFilePath.ResetPathControl()
Should `DefaultSuggestionName` be set here?
The same question applies to the other dialogs below.

2020-08-30 10:42 UTC, lloyddewit commented on instat/ucrFilePath.vb
> +''' Optional. Set a default suggestive name
```suggestion
''' Optional. Set a default suggested name
```

2020-08-30 10:42 UTC, lloyddewit commented on instat/dlgExportDataset.vb
> +        ucrFilePath.DefaultFileSuggestionName = ucrAvailableSheets.strCurrDataFrame 'set suggestive name from selected data frame
```suggestion
        ucrFilePath.DefaultFileSuggestionName = ucrAvailableSheets.strCurrDataFrame 'set default suggested name from selected data frame

```

2020-08-30 10:42 UTC, lloyddewit commented on instat/dlgExportGraphAsImage.vb
> +        'give a suggestive name from the receiver
```suggestion
        'give a default suggested name from the receiver
```

2020-08-30 10:42 UTC, lloyddewit commented on instat/dlgExportRObjects.vb
> +        'ucrReceiverObjects is a multireceiver. So give a suggestive name if it has 1 item only
```suggestion
        'ucrReceiverObjects is a multireceiver. So give a default suggested name if it has 1 item only
```

2020-08-30 10:42 UTC, lloyddewit commented on instat/dlgExportRWorkspace.vb
> +        'ucrReceiverMultiple is a multireceiver. So give a suggestive name if it has 1 item only
```suggestion
        'ucrReceiverMultiple is a multireceiver. So give a default suggested name if it has 1 item only
```

2020-08-30 10:42 UTC, lloyddewit commented on instat/ucrFilePath.vb
> +    ''' used to set the suggestive name if no file name was set before
```suggestion
    ''' used to set the suggested name if no file name was set before
```

2020-08-30 10:42 UTC, lloyddewit commented on instat/ucrFilePath.vb
> +    ''' Used by the SaveFileDiaolog prompt to 'remember' last selected file name and directory
```suggestion
    ''' gets or sets the input file path used by the SaveFileDiaolog prompt to 'remember' the 
    ''' last selected file name and directory
```

2020-08-30 10:42 UTC, lloyddewit commented on instat/ucrFilePath.vb
> +    Public Function GetPathControl() As ucrInputTextBox
Make a `ReadOnly` `PathControl` property instead?

2020-08-31 10:38 UTC, Patowhiz commented on instat/dlgExportGraphAsImage.vb
> +        ucrFilePath.ResetPathControl()
@lloyddewit  `dlgExportDataSet` doesn't have a receiver, so on `Reset`, the default name can only be changed here, currently the data frame selector doesn't raise `ControlValueChanged` (which could be used override the default name) if the data frame is just one. In the other dialogs, `Reset` raises `ControlContentsChanged` event in their receivers which automatically clears the default name, thus we don't need to do it in `SetDefaults()` subroutine.

2020-08-31 10:47 UTC, Patowhiz commented on instat/ucrFilePath.vb
> +    Public Function GetPathControl() As ucrInputTextBox
@lloyddewit yes, thank you.

2020-08-31 13:52 UTC, lloyddewit commented on instat/dlgExportGraphAsImage.vb
> +        ucrFilePath.ResetPathControl()
@Patowhiz Understood. Thanks for the explanation.

2020-08-31 13:54 UTC, lloyddewit approved these changes

2020-08-31 13:54 UTC, lloyddewit commented
@rdstern Please could you approve? thanks

2020-08-31 15:41 UTC, rdstern approved these changes
Still looks fine

2020-09-05 19:19 UTC, Patowhiz commented
@rdstern @lloyddewit I've now expounded this PR to also fix issue #5602 and #5590. They both required changes to dialogs changed in this PR. Code can be reviewed by @lloyddewit once he is back. Code changes are only in `dlgEportRObjects.vb` and `dlgExportDataset.vb`

2020-09-11 09:02 UTC, lloyddewit commented
@Patowhiz Thank you for the extra changes. These changes are significant since @rdstern and I last reviewed. Is this PR now ready for final review and merge? thanks

2020-09-28 08:29 UTC, Patowhiz commented
@lloyddewit @rdstern  yes this is now ready for final review

2020-10-07 07:34 UTC, lloyddewit commented
@rdstern Please could you re-test? thanks

2020-10-12 22:26 UTC, rdstern requested changes
@Patowhiz this looks so much better as an export dialogue.
The one oddity was the multiline display of the file.  The [...] means that the single line display isn't able to show the extreme right of the file-name - usually the extension.  And the multi-line display doesn't have word-wrap, so it is all on the top line.  Could you add word-wrap to the display, of omit the multiline option.  

On the positive side I tried exporting 4 data frames to Excel and it worked fine.  This is a major enhancement for our sort of audience.

2020-10-13 07:39 UTC, rdstern commented
I had not realised that I can export multiple data frames (as multiple files) in any format.  Great.  Then it uses the data frame name as the file-name and you therefore choose a directory.  I tried and felt I had a problem making a new directory.  But I couldn't verify that, because of the more major problem below.  I then repeated having made a new directory outside R-Instat, but then found it had made a new one with a single letter, namely T.  I will investigate further when the problem below has been investigated.

I did notice that word-wrap has been installed.

Anyway it did then save fine and I returned to the dialogue and exported again to Excel.  Then it froze and I had to break out after about 10 minutes.  When I broke out it was at the following line number 1301:

    `evtWaitHandleWaitDisplayDone.WaitOne()`.

Here is the data file I used:
[Niger4dly_extremes.zip](https://github.com/africanmathsinitiative/R-Instat/files/5369711/Niger4dly_extremes.zip)

2020-10-13 08:56 UTC, rdstern reviewed
I have tried again and can't get it to freeze up now.  It generally seems to be working well.

The one potential issue (that @Patowhiz may have mentioned) is the overwriting of files with the multiple save as csv, etc.  Then you choose a directory, rather than a filename.  It does know the names it will save, but there is no check that you may overwrite existing files.  In all other situations you are saving a single file, so that save dialogue gives the warning.  In this situation there is no warning.  I assume that isn't possible, but it is risky!

2020-10-14 09:14 UTC, Patowhiz commented
@rdstern in the case of exporting data frames as separate multiple files, we can have a label that warns the user that files with similar names will be overwritten if they exist. This could be shown just below the file path control. This will require no checking and will blend easily with user expectations before they click okay. Will that be cautious enough for you?

Please note, this dialog is very dependent on R and in particular rio package. If the data exported is huge of course we will have thread timeout errors (unless better handling of long threads is built).

2020-10-14 09:45 UTC, rdstern commented
@Patowhiz yes, that sounds fine and is enough.  And this is a major improvement, so I am very keen for this to be merged and be in the next version.
(If you want to be more cautious, then the user can save one at a time.)

2020-10-14 17:54 UTC, Patowhiz commented
@rdstern I have added include text that warns user that files will be overwritten if they already exist. The warning text can be changed if what I have is not good enough.

Below is a screenshot that demonstrates this.

<img width="338" alt="export_files" src="https://user-images.githubusercontent.com/21179007/96026568-55da8b80-0e5f-11eb-9dde-4fcfb2d38609.PNG">

2020-10-14 18:59 UTC, rdstern commented
Yes, just "Files with the same names will be overwritten"

2020-10-14 19:31 UTC, Patowhiz commented
Changed the confirmation text to the text suggested by @rdstern

2020-10-27 08:05 UTC, lloyddewit requested changes

2020-10-27 09:27 UTC, Patowhiz commented on instat/ucrFilePath.vb
> +    Public Sub SetPathControlRcode(clsNewCodeStructure As RCodeStructure, Optional bReset As Boolean = False)
`SetPathControlParameter(rParameter As RParameter)` can be made to a property, it has only 1 parameter. 
But `SetPathControlRcode(clsNewCodeStructure As RCodeStructure, Optional bReset As Boolean = False)` has 2 parameters, I'm not sure how that can be converted to a property in VB.NET. Properties generally allow 1 parameter in their `Set` options.

So for consistency I opted to have the 2 `Set` subroutines.

2020-10-27 09:47 UTC, Patowhiz commented on instat/ucrFilePath.vb
> +            Using dlgFolderBrowse As New FolderBrowserDialog
@lloyddewit the `FolderBrowserDialog` is a component that uses managed resources(file streams, security permissions etc) in its implementation. `Using` block guarantees disposal of the resources(it's similar to `Try Finally`). Instantiating the `FolderBrowserDialog` inside the Using block guarantees that all the managed resources will immediately be disposed or released for reuse no matter how you exit the block.

The same applies to `SaveFileDialog`.

We can still use `Dim` but then we risk memory exceptions incase the managed garbage collection doesn't dispose the resources held in such components. To further reduce this risk of this happening, we could have the component declared globally as a variable in the class, but then I think this would not be ideal in terms of simplicity.

2020-10-27 09:55 UTC, Patowhiz commented on instat/ucrFilePath.vb
> +                    End If
@lloyddewit the default value for `dlgSaveFile.FileName` is empty(""). Yes I agree, I have edited the comment to express the intention.

2020-10-27 13:07 UTC, Patowhiz commented on instat/ucrFilePath.vb
> +    Public Property FolderBrowse As Boolean = False
Probably just a syntax advantage in the manner in which it could be used now and  in future. For instance extending the property to have extra `set` functionality would not need any renaming.

2020-10-28 10:07 UTC, lloyddewit commented on instat/ucrFilePath.vb
> +    Public Sub SetPathControlRcode(clsNewCodeStructure As RCodeStructure, Optional bReset As Boolean = False)
yes, you're correct, a `set` should have only 1 parameter

2020-10-28 10:14 UTC, lloyddewit commented on instat/ucrFilePath.vb
> +            Using dlgFolderBrowse As New FolderBrowserDialog
Thanks for the explanation. I knew that `Using` was related to correct closure of external resources, but I didn't think of the dialog in that way. But of course it's a `FolderBowserDialog`.

2020-10-28 10:15 UTC, lloyddewit submitted a review, later dismissed

2020-10-28 10:16 UTC, lloyddewit commented
@rdstern please can you approve? thanks

2020-11-03 20:52 UTC, Patowhiz commented
@rdstern this is now waiting for your approval.

2020-11-15 10:25 UTC, lloyddewit commented
@rdstern please could you approve? thanks

2020-11-17 18:54 UTC, rdstern approved these changes
ok by me

2020-11-18 09:39 UTC, lloyddewit commented
@Patowhiz Please could you resolve the code conflict so that we can merge? thanks

2020-12-02 08:48 UTC, Patowhiz commented
@lloyddewit I have resolved the conflicts. It's now ready.

2020-12-02 08:58 UTC, lloyddewit submitted a review, later dismissed

2020-12-02 09:01 UTC, lloyddewit commented
@dannyparsons please could you review (you asked to review this before it was merged)? thanks

2021-01-04 12:35 UTC, rdstern approved these changes

2021-01-18 13:19 UTC, Patowhiz commented
@rdstern as discussed with @volloholic below is the screenshot of the changes made to the export dialog. The file type is now enforced through the combobox, which is now always visible.
@Wycklife you may use these changes for the video production in regards to exporting the multiple data frames imported from climsoft.
@lloyddewit @rdstern this is now ready for review.

Single file selected
<img width="344" alt="screenshot 1" src="https://user-images.githubusercontent.com/21179007/104920081-53308a80-59a8-11eb-817a-faf6ecde0e97.PNG">

Multiple files Selected
<img width="342" alt="export multiple files" src="https://user-images.githubusercontent.com/21179007/104920107-5deb1f80-59a8-11eb-92ed-31776069c02a.PNG">

2021-01-19 09:44 UTC, lloyddewit commented
@volloholic @dannyparsons Do these new changes resolve your outstanding comments? Would you still like to review, or may @rdstern and I approve and merge?
thanks for clarifying

2021-02-16 15:46 UTC, Patowhiz commented
@rdstern did you manage to test the new design changes proposed by @volloholic 
@lloyddewit the new changes address design changes requested by @volloholic after he had discussions with @dannyparsons. These new design changes affect the export dialog only.

2021-02-22 23:35 UTC, rdstern requested changes
@Patowhiz this is looking good and is an important improvement for the next update.  Two trivial suggestions.  
a) Can the file types field be wider, so most of the types are shown completely.
b) Then, when I was exporting multiple files (e.g. csv) it didn't let me choose the names.  I could only choose the directory.  I suggest we should say that.  So, when there are multiple files and the full set of export options is provided, then the label changes to Export Directory:  Perhaps the Export moves to the line above, so the directory name field stays the same size?

2021-02-23 20:07 UTC, Patowhiz commented
@rdstern I have addressed item (a).
In regards to item (b) I think it's a standard way in most software packages when it comes to exporting multiple files, users by default expect to select a directory into which they files will be placed into, and also expectation naming the files. I have no strong reservations from making the change other than it is an extra set of functionality that I think is not really necessary(since its normal in regards to user expectations). If others feel that this change is important, I can add it.

<img width="341" alt="Capture" src="https://user-images.githubusercontent.com/21179007/108901397-df7b4080-762b-11eb-92ed-8eac7145384e.PNG">

2021-02-23 20:29 UTC, rdstern approved these changes
@Patowhiz I am happy now and would really like to see this feature merged.  Over to @lloyddewit

2021-03-01 11:39 UTC, lloyddewit approved these changes
I reviewed the commits since my last approval

2021-03-01 11:40 UTC, merged