Replacing the old save control in the calculator with a new save control
africanmathsinitiative/R-Instat pull request #5916
Opened 2020-08-03 14:44 UTC by Wycklife

@africanmathsinitiative/developers This is work in progress
I have added the new control to the calculator. It adds a new column to the data frame. The part remaining is positioning of the new column.

2020-08-03 17:33 UTC, Wycklife commented
@africanmathsinitiative/developers This is now ready for review. I tried looking at the dialogs which uses the save control, I keep on getting the bug below whenever I reopen the dialog after positioning the new column. @lloyddewit What could be the cause of this bug?

![image](https://user-images.githubusercontent.com/33898404/89210272-8339cc00-d5c8-11ea-89db-6aa6157b4c9e.png)

2020-08-04 14:08 UTC, lloyddewit commented
@Wycklife I assume the error is because the data name is not provided (it's an empty string). However, I couldn't recreate the error. I tested the PR and it seems to do the column positioning correctly :). See screen dump below.
There are still some issues related to updating the prefix.
If you have specific steps that trigger the error then let me know and I'll try and recreate.
![image](https://user-images.githubusercontent.com/57253949/89303513-99996380-d66c-11ea-8d37-fb06370e5bdc.png)

2020-08-04 16:34 UTC, Wycklife commented
@lloyddewit Can the error be caused by machine? I also tested the same using Ivan's laptop and it never produced the error. Let me look into it a gain. I'm also fixing the prefix

2020-08-05 06:46 UTC, lloyddewit commented
@Wycklife Interesting. The error is most likely caused by slightly different steps being taken on the 2 laptops. Or it could be a difference in the environment such as OS, dotnet version, Visual Studio etc.. Or it could be problems initialising the memory location used to store/update the data name (especially if >1 variables reference the same location), but this is a more common problem with older languages and VB dotnet has memory management features to prevent this type of issue.

2020-08-07 06:56 UTC, Patowhiz commented
> @africanmathsinitiative/developers This is now ready for review. I tried looking at the dialogs which uses the save control, I keep on getting the bug below whenever I reopen the dialog after positioning the new column. @lloyddewit What could be the cause of this bug?
> 
> ![image](https://user-images.githubusercontent.com/33898404/89210272-8339cc00-d5c8-11ea-89db-6aa6157b4c9e.png)

@Wycklife from you comment above. From the error message box it is quite clear that the data name is not being found. It's indicated as empty "". Thus the data object is not also found. I think this could be caused by how your code is set up on reopening the dialog. 

I'm happy to review this and get more insights on the code.

2020-08-07 07:01 UTC, rdstern commented
@Patowhiz your review would be good.  @Wycklife is currently main preparing for his MSc exams, so I am not sure when he will look at the review, but it would be good to do antyway.

2020-08-08 06:42 UTC, Wycklife commented
@Patowhiz This error occurs even on the count in factor dialog not only on the calculator, I thought perhaps it's caused by my machine, of which I agree with @lloyddewit  comment above. I tried testing these dialogs using Ivan's laptop but I couldn't find the error, using the same procedure I used on with my laptop. @lloyddewit  tested too and never found the error.

2020-08-13 09:18 UTC, Wycklife commented
@Patowhiz Did you try to test this?

2020-08-15 13:17 UTC, Patowhiz commented on instat/dlgCalculator.vb
>              ucrBase.OKEnabled(False)
@Wycklife  The whole code statement inside TestOkEnabled() subroutine could be replaced with 

` ucrBase.OKEnabled(Not ucrCalc.ucrReceiverForCalculation.IsEmpty AndAlso ucrCalc.ucrSaveResultInto.IsComplete)`

2020-08-15 13:19 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub chkSaveResultInto_CheckedChanged(sender As Object, e As EventArgs)
@Wycklife  Do we still need this subroutine? I think this was meant to be an event handler for  control `chkSaveResultInto` which has been removed

2020-08-15 13:22 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_NameChanged()
@Wycklife I couldn't find where `ucrSaveResultInto_NameChanged()` is used. Even event `SaveNameChanged()` is no longer being raised.

2020-08-15 13:23 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_NameChanged()
It shows up as unused when I looked it up in visual studio

2020-08-15 13:43 UTC, Patowhiz commented
@wycliffe I also noted that there is a big space between the base buttons and `ucrSave` control.

<img width="392" alt="calculator" src="https://user-images.githubusercontent.com/21179007/90313604-7dbc7a00-df16-11ea-8686-11122bc36f98.PNG">

2020-08-20 08:42 UTC, Wycklife commented
> @Wycklife in addition to the queries I have raised I could not build this PR without commenting out the usage of `ucrCalculator` in `sdgCalculationsSummary`. You may want to check the changes required before this is merged.
> 
> Below is the `sdgCalculationsSummary` that I had to comment out.
> <img alt="sdgCalc" width="434" src="https://user-images.githubusercontent.com/21179007/90313446-68931b80-df15-11ea-8aef-83c8815ff4d5.PNG">

@Patowhiz This should be fixed on a separate branch, it's a different sub dialog using the same old save control. What do you think? Should I remove it on this same branch

2020-08-20 08:43 UTC, Wycklife commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_NameChanged()
> @Wycklife I couldn't find where `ucrSaveResultInto_NameChanged()` is used. Even event `SaveNameChanged()` is no longer being raised.

@Patowhiz Could you check a gain please?

2020-08-20 08:44 UTC, Wycklife commented
@Patowhiz Could you review this a gain. I have fixed the above comments.

2020-08-24 08:36 UTC, Wycklife commented
@lloyddewit I have made improvements to this pull request and it seems okay from my end.

2020-08-24 08:39 UTC, Wycklife commented
@lloyddewit The question I have is whether to remove that line of code from sdgCalucaltionSummary which produces an error when building. If yes then should I do it on this branch?

2020-08-24 09:53 UTC, lloyddewit commented
@Wycklife yes, you should delete the line and include the change in this PR.
If you submit a PR then that PR should be buildable and testable. In this PR, you deleted `chkSaveResultInto`. Therefore you also need to remove any `chkSaveResultInto` references in other files. Otherwise the software will not build. All changed files should be included in the PR. I don't understand how you were able to build and test this PR without removing this line. Were you using an older version of `sdgCalculationSummary`?

2020-08-24 10:02 UTC, Wycklife commented
> @Wycklife yes, you should delete the line and include the change in this PR.
> If you submit a PR then that PR should be buildable and testable. In this PR, you deleted `chkSaveResultInto`. Therefore you also need to remove any `chkSaveResultInto` references in other files. Otherwise the software will not build. All changed files should be included in the PR. I don't understand how you were able to build and test this PR without removing this line. Were you using an older version of `sdgCalculationSummary`?

@lloyddewit Thanks for your comment. I think whenever I build, then this error keeps on popping up, so I had to comment the error out. Let me remove that part.

2020-08-24 10:45 UTC, Wycklife commented
@lloyddewit I have removed the error.

2020-08-24 10:51 UTC, lloyddewit commented
@Patowhiz Please could you confirm that your comments are resolved? thanks

2020-08-26 14:30 UTC, Patowhiz commented
@Wycklife the code looks good to me.
There are just 2 lines of code that define variables which are no longer being used. Code line 21 and  22
```
 Dim strCalcHistory As List(Of String)
 Dim dataset As DataFrame
```
I think the 2 lines can be deleted, they add no functionality to the dialog.

On the design, I can still see a huge gap between the save control and the base buttons, I wonder if this is happening on my screen only? I checked and didn't see any hidden control occupying that space.

<img width="395" alt="space dlgenter" src="https://user-images.githubusercontent.com/21179007/91316576-a15aac80-e7c1-11ea-9d53-62b62ec0d29e.PNG">

2020-08-26 17:07 UTC, Wycklife commented
@Patowhiz Some of the keyboards are large in size i.e Wakefield keyboard, that's why that space  was left. It has been there even before.

2020-08-26 17:38 UTC, rdstern commented
@Wycklife you have a point, but here is the dialogue with Wakefield.

2020-08-26 17:40 UTC, rdstern commented
@Wycklife you have a point.  But here is the calculator with the Wakefield keyboard.  So I still think that, as @Patowhiz suggests, the gap doesn't need to be so large?

![image](https://user-images.githubusercontent.com/11226469/91337556-71180b80-e7cb-11ea-8c78-72e6914b07c8.png)

2020-08-27 07:21 UTC, Wycklife commented
@rdstern I have reduced the space, I just want to commit the changes.

2020-08-27 09:18 UTC, rdstern commented
@Wycklife that's great.  It was a good suggestion from @Patowhiz .  Once you reduced the space I assume (and hope) that you checked with the big keyboards - especially Wakefield.  If you remember we found earlier that with Wakefield the dialogue looked odd when you returned to the dialogue a second time.

2020-08-27 10:29 UTC, Wycklife commented
@Patowhiz , @rdstern I suggest we leave that space the way it is. I have tried reducing the size but it's affecting the wakefield keyboard when you reopen the dialog. I.e Some of the keys are hidden.

2020-08-27 10:49 UTC, Patowhiz commented
@Wycklife can you please share the screenshot.

2020-08-27 11:13 UTC, Patowhiz commented
@Wycklife  If it's retaining the width then I think it should retain the height too on reopening. Generally VB.NET handles the forms and controls size measurements by handling the 2 in it's events. we can have a quick skype about it

2020-08-27 11:17 UTC, rdstern commented
Aha, @Wycklife am I right that when you reduce the space it is ok when you first go into the calculator and then use Wakefield?  But then, when you return to the calculator again it isn't ok?

Or is it a problem anyway?

2020-08-27 11:51 UTC, Wycklife commented
> Aha, @Wycklife am I right that when you reduce the space it is ok when you first go into the calculator and then use Wakefield? But then, when you return to the calculator again it isn't ok?
> 
> Or is it a problem anyway?

Yes, you're right. I am now setting the height of the dialog in relation with the keyboard selected. Just as the width of the dialog enlarges or reduces depending on the size of the keyboard selected. I think this will work out.

2020-09-01 10:12 UTC, Wycklife commented
@rdstern This is now working well on my side. The location of the ucrBase and the height of the dialog changes depending on the keyboard option selected. @Patowhiz Could you please review if this is okay? @rdstern You can review as well. Thank you.

2020-09-02 08:51 UTC, rdstern requested changes
@Wycklife the save part now seems to work.  But on the layout:
a) The Comment field, in particular, has now moved very close to the left-hand side.  I was happy where it was before.
b) With the Wakefield keyboard I don't see why the left hand side needs to change.  There seems to be a lot of space with the left side just remaining where it is.  Are there any other keyboards that change the layout?  Do they need to?

2020-09-28 10:50 UTC, Patowhiz commented
@Wycklife I have made changes to the code that calculates the required height to your branch in PR [204](https://github.com/Wycklife/R-Instat/pull/204). You can merge to your branch. I cloned my branch from this PR branch.

Below is a screenshot of the new design with and without the wakefield calculator visible.

Without wakefield calculator
<img width="390" alt="basic calculator" src="https://user-images.githubusercontent.com/21179007/94423131-d11a1d00-0190-11eb-803a-5dbed7f66efe.PNG">

With wakefield calculator
<img width="665" alt="wakefield calc" src="https://user-images.githubusercontent.com/21179007/94423167-df683900-0190-11eb-89d6-b90396a8b0f2.PNG">

2020-09-29 06:52 UTC, lloyddewit commented
@Wycklife is this PR now ready for review/test or do you still expect more commits? thanks for clarifying

2020-10-13 07:26 UTC, Wycklife commented
@rdstern The following are the changes that @Patowhiz  made.
1. Maitined the height of the dialog and the location of the base control.
2. Changes the width of the dialog to accommodate the calculator size.
@lloyddewit This now looks okay. @africanmathsinitiative/developers Someone to review the changes.

2020-10-13 09:41 UTC, Wycklife commented
@rdstern The following are the changes that @Patowhiz  made.
1. Maitined the height of the dialog and the location of the base control.
2. Changes the width of the dialog to accommodate the calculator size.
@lloyddewit This now looks okay. @africanmathsinitiative/developers Someone to review the changes.

2020-10-13 09:44 UTC, Wycklife commented
@africanmathsinitiative/developers This branch has got conflict, am fixing them now

2020-10-13 14:13 UTC, Wycklife commented
@rdstern I realised some of the keyboard options were hidden and I have made some improvements to them. I have also resolve the conflicts for this pr. Could you please review this once more? I might not be able to continue working on the date keyboard till this pr is merged to avoid conflicts. Thank you.

2020-10-13 14:14 UTC, Wycklife commented
@lloyddewit This PR is now ready for review. Thank you.

2020-10-13 15:39 UTC, rdstern commented
Thanks @Wycklife and could you specify which keyboards etc you changed.  There is a lot in this dialogue and I would like to be sure I am checking exactly the bits you changed.

2020-10-14 08:05 UTC, Wycklife commented
> Thanks @Wycklife and could you specify which keyboards etc you changed. There is a lot in this dialogue and I would like to be sure I am checking exactly the bits you changed.

These are the keyboards I made improvements:
Summary Keyboard
Strings (Character Columns)
Wakefield
Transform

2020-10-14 19:42 UTC, Patowhiz commented on instat/dlgCalculator.vb
> +    Private Sub CalculationsOptions()
Probably a brief comment that explains what `CalculationsOptions()` does.

2020-10-14 19:42 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_NameChanged()
Still shows up as unused

2020-10-14 19:42 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub chkSaveResultInto_CheckedChanged(sender As Object, e As EventArgs)
Same here. Unused subroutine

2020-10-19 08:03 UTC, rdstern commented
As you are on this dialogue, please can I add a (hopefully trivial) addition.  It is one that could affect many dialogues and good that we take the opportunity to correct, when we are changing a dialogue.

There is a tidyverse style guide.  It says:
"Variable and function names should use **_only lowercase letters, numbers, and __**. Use underscores (_) (so called snake case) to separate words within a name.


# Good
day_one
day_1

# Bad
DayOne
dayone"

In the calculate dialogue we suggest a new variable is Calc1, i.e. with upper case C.  Please change to calc1.  Thanks.

2020-10-19 08:32 UTC, Patowhiz commented
Functionality and code looks good from my end.

2020-10-21 17:00 UTC, rdstern submitted a review, later dismissed
Happy to approve.  Over to @lloyddewit .  If ok, good to include in the next release

2020-10-22 09:06 UTC, lloyddewit requested changes

2020-10-22 09:06 UTC, lloyddewit commented on instat/dlgCalculator.vb
> +    Private Sub ucrBase_ClickOk(sender As Object, e As EventArgs) Handles ucrBase.ClickOk
```suggestion

    Private Sub ucrBase_ClickOk(sender As Object, e As EventArgs) Handles ucrBase.ClickOk
```

2020-10-22 09:06 UTC, lloyddewit commented on instat/dlgCalculator.vb
> +    Private Sub CalculationsOptions()
```suggestion
```

2020-10-22 09:09 UTC, lloyddewit approved these changes
@Wycklife Thank you, this looks good. I just made a couple of small cosmetic changes.

2020-10-22 09:10 UTC, lloyddewit commented
@rdstern Please could you re-approve (functionality has not changed)? thanks

2020-10-22 10:03 UTC, rdstern approved these changes

2020-10-22 13:12 UTC, merged