Dispaly additions#5903
africanmathsinitiative/R-Instat pull request #5918
Opened 2020-08-06 13:18 UTC by Ivanluv

fixes ##5903

2020-08-14 06:38 UTC, lloyddewit commented
@shadrackkibet please could you peer review? thanks

2020-08-14 07:02 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +    Private Sub ucrSelectorDisplayDailyClimaticData_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrSelectorDisplayDailyClimaticData.ControlValueChanged, ucrReceiverStations.ControlCo
Should this be the same events?

2020-08-14 07:02 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +        'End If
Should this be removed?

2020-08-17 07:31 UTC, Ivanluv commented
@shadrackkibet  could you look at this again

2020-08-17 13:44 UTC, shadrackkibet commented
We agreed to add a control to change Rug plot colour. Check the discussion in the issue. An editable Combobox is enough for that purpose.
@rdstern I think there should be a control to save the graph.

2020-08-17 14:52 UTC, rdstern commented
I support both of those suggestions.

2020-08-17 16:40 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +            clsFacetFunction.AddParameter("labeller", "label_wrap_gen(multi_line=FALSE)", iPosition:=3)
`abel_wrap_gen(multi_line=FALSE)` this should be an RFunction

2020-08-17 16:42 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +        clsStationElemFacetOperator.ClearParameters()
Why do you clear parameters here?

2020-08-17 16:45 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +        clsGgplotAesFunction.AddParameter("x", ucrReceiverDate.GetVariableNames(False), iPosition:=0)
Any reason why this is not done through setRcodeForControls?

2020-08-17 16:49 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +    Private Sub ucrReceiverDate_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrReceiverDate.ControlContentsChanged, ucrReceiverYear.ControlContentsChanged, ucrReceiverStations.Contro
Everything here should be `.ControlContentsChanged` event.

2020-08-17 16:51 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +    Private Sub ucrReceiverMultipleElements_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrReceiverMultipleElements.ControlContentsChanged, ucrReceiverStations.ControlValueChanged
I see a mixture of events here.

2020-08-18 11:11 UTC, Ivanluv commented on instat/dlgDisplayDailyData.vb
> +        clsGgplotAesFunction.AddParameter("x", ucrReceiverDate.GetVariableNames(False), iPosition:=0)
parameter value requires a value without qoutes  while other functions in the  setRcode that use `ucrReceiverDate` use the value with quotes

2020-08-18 11:15 UTC, rdstern commented
@Ivanluv one other small improvement as I use the dialogue is to include (by default) all the elements for the sheet that have been defined in the Define Climatic dialogue.

2020-08-18 12:17 UTC, Ivanluv commented on instat/dlgDisplayDailyData.vb
> +        clsStationElemFacetOperator.ClearParameters()
`station` and `variables` parameters are being added to the existing parameters rather than replacing  them.So clearing them makes them update correctly

2020-08-20 08:52 UTC, Ivanluv commented
@shadrackkibet  could you have a look again

2020-08-30 08:04 UTC, lloyddewit commented
@Ivanluv There are still some open peer review comments above. Please could you clarify whether you'd like to accept/reject these comments? thanks

2020-09-01 06:50 UTC, Ivanluv commented
@shadrackkibet  could you look at this again

2020-09-07 12:48 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +        ucrInputGRugColur.SetItems(dctGRugColour)
@Ivanluv I can't see where this change is done.

2020-09-07 12:57 UTC, shadrackkibet requested changes

2020-09-07 12:57 UTC, shadrackkibet commented on instat/dlgDisplayDailyData.vb
> +        dctGRugColour.Add("Red", Chr(34) & "red" & Chr(34))
Since Red is the default. Let's have it as the first in the dropdown.

2020-09-07 13:00 UTC, shadrackkibet commented
Remove the label below. That is the same label you have for the checkbox. You can add colon(:) at the end of the checkbox then put the NUD after the colon. See below.
![image](https://user-images.githubusercontent.com/26301973/92390265-34310a80-f123-11ea-94ff-f072487d15f6.png)

2020-09-24 07:30 UTC, rdstern commented
![image](https://user-images.githubusercontent.com/11226469/94112240-0f37d980-fe3d-11ea-921e-fc046df4f2c6.png)

This is now looking really good and useful.
I am now using it on a challenging data set, and - so far so good!
But:

a) In the colours for the rug-plot you now default to red - same as the data.  But you don't include black, which I prefer!  I found I could type Black into the rug-plot control and it works!  However it gives a developer error as it doesn't recognise the colour when returning to the dialogue.  I suggest making the list of colours more complete, and then perhaps not allowing typing anything else?
b) In the Facets you allow Free Y, Free X or Free.  We also need the 4th - especially in the example above, when we are plotting a single element.  Is it called "Fixed"?
c) By the way I didn't think the Free-x would be particularly useful, but it is used above and I love it!

Here is another example.  It looks good.

![image](https://user-images.githubusercontent.com/11226469/94113944-8ff7d500-fe3f-11ea-8e6c-5115ab9bc990.png)

d) This is more a question perhaps for @dannyparsons initially.  There is more that I would like to do with this graph, e.g. change y-axis title, add a footnote, change x-axis limits, change theme.  I think Danny is of the view that we should permit access to the "usual" plotting sub-dialogues, which would be a major advance.  Perhaps some tabs would be disabled, e.g. facets?  Let's see what he says.  This would apply to quite a lot of our graphics dialogues.

2020-09-24 08:36 UTC, shadrackkibet commented
> a) In the colours for the rug-plot you now default to red - same as the data. But you don't include black, which I prefer! I found I could type Black into the rug-plot control and it works! However, it gives a developer error as it doesn't recognise the colour when returning to the dialogue. I suggest making the list of colours more complete, and then perhaps not allowing typing anything else?

@Ivanluv to avoid the developer error when a color not in the dictionary is typed just include `ucrInputGRugColur.bAllowNonConditionValues = True` .

2020-09-25 15:11 UTC, rdstern commented
That's good.  And, if you prefer red, then I am happy it is the default.  But it is then the same color as the data.  I still prefer black and am happy I can type it.  But I hope it (and perhaps a few more colors are also included in the drop down

2020-09-26 05:25 UTC, rdstern submitted a review, later dismissed
The small changes are welcome.  This is still one of many dialogues where I hope we can soon add the usual plot options sub-dialogue.  But that is for the future!
I am happy for this improved version to be merged.

2020-09-28 07:48 UTC, lloyddewit requested changes
@shadrackkibet thank you for the review.
@Ivanluv this looks good, I just had a couple of small comments.

2020-09-28 07:48 UTC, lloyddewit commented on instat/dlgDisplayDailyData.vb
> +    ''' text is set to  "No Facets"
```suggestion
    ''' Sets the facet combobox text:
    ''' <list type="bullet">
    '''     <item><description>
    '''             If the station receiver is not empty and the multiple element receiver has more 
    '''             one element then sets the facet combobox text to "Station-Element " and 
    '''             "Element - station"
    '''     </description></item><item><description>
    '''             If the station receiver is not empty and the multiple element receiver has 
    '''             less than 2 elements then sets the facet combobox text to "Station"
    '''     </description></item><item><description>
    '''             If the station receiver is empty and the multiple element receiver has 2 or 
    '''             more elements then sets the facet combobox text to "Element"
    '''     </description></item><item><description>
    '''             If the station receiver is empty and the multiple element receiver has no 
    '''             elements then sets the facet combobox text to "No Facets"
    '''     </description></item>
    ''' </list>    
```

2020-09-28 07:48 UTC, lloyddewit commented on instat/dlgDisplayDailyData.vb
> +        Select Case ucrInputFacetBy.GetText()
if `ucrInputFacetBy.GetText()` returns a value not covered below (e.g. `"No Facets"`, then `clsStationElemFacetOperator` will have no parmeters. Is this legal? should there be a default case?

2020-09-28 08:00 UTC, lloyddewit requested changes
@Ivanluv one extra comment

2020-09-28 08:00 UTC, lloyddewit commented on instat/dlgDisplayDailyData.vb
> +            ucrSaveGraph.SetPrefix("Graph")
@Ivanluv I couldn't see any obvious changes related to this comment. Is it resolved?

2020-09-28 09:08 UTC, Ivanluv commented on instat/dlgDisplayDailyData.vb
> +        Select Case ucrInputFacetBy.GetText()
`clsStationElemFacetOperator` having no parameters is the default case.

2020-09-28 09:13 UTC, Ivanluv commented on instat/dlgDisplayDailyData.vb
> +            ucrSaveGraph.SetPrefix("Graph")
` ucrSaveGraph.Reset()` resolved this

2020-09-28 22:34 UTC, Patowhiz commented
@Ivanluv  In addition to the suggestions mentioned above, I would like to also suggest addition of  comments

2020-09-29 07:16 UTC, Ivanluv commented
@Patowhiz what are you suggestions?

2020-09-29 16:51 UTC, Patowhiz commented
Code comments to the new addition s done in the PR.

2020-10-07 07:52 UTC, lloyddewit commented
@rdstern you approved on 26 Sep. Since then, just the comments have been changed, please could you re-approve? thanks

@Ivanluv There's a suggestion above from @Patowhiz about commenting. I reviewed the level of commenting. The main changed function has an updated comment. There are some small private handlers added without comment blocks. This is roughly inline with other dialogs and I think its OK. Therefore I assumed you weren't planning to change the comments further.

2020-10-07 09:11 UTC, Ivanluv commented
@lloyddewit  yes,I wasn't planning to change the comments further

2020-10-07 10:33 UTC, rdstern approved these changes
Still looks fine

2020-10-07 10:52 UTC, lloyddewit approved these changes

2020-10-07 10:52 UTC, merged