Changes for the extremes Dialogue
africanmathsinitiative/R-Instat pull request #5933
Opened 2020-08-17 12:40 UTC by Ivanluv

@africanmathsinitiative/developers  this fixes #5887 and it from PR #5900

2020-08-17 12:40 UTC, Ivanluv commented
@shadrackkibet  you can now review this

2020-08-17 17:06 UTC, shadrackkibet commented on instat/sdgExtremesDisplayOptions.vb
> +            clsFevdPlotFunction.RemoveParameterByName("type")
This function should not run when this radio button is selected. Therefore no need to remove this parameter.

2020-08-17 17:07 UTC, shadrackkibet commented on instat/sdgExtremesDisplayOptions.vb
> +Public Class sdgExtremesDisplayOptions
The licence text is needed here.

2020-08-17 17:07 UTC, shadrackkibet commented on instat/sdgExtremesMethod.vb
>  ﻿Public Class sdgExtremesMethod
Licence text needed here

2020-08-17 17:09 UTC, shadrackkibet commented on instat/sdgExtremesMethod.vb
> +        ucrPanelExtreme.SetParameter(New RParameter("method"))
Parameter position?

2020-08-17 17:10 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +Imports instat
This is not needed.

2020-08-17 17:12 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +    Private bResettingDialogue As Boolean = False
Why is this needed?

2020-08-17 17:15 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        ucrSaveExtremes.SetCheckBoxText("Save Model")
```suggestion
        ucrSaveExtremes.SetCheckBoxText("Save Model:")

```

2020-08-17 17:16 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        ucrInputThresholdforLocation.SetText("0")
This is not needed.

2020-08-17 17:17 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        ucrReceiverExpressionExplanatoryModelForLocParam.Selector = ucrSelectorExtremes
This should be done on `InitialiseControls()`

2020-08-17 17:18 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        clsLocationScaleResetOperator.SetOperation("")
Why do you need an empty operation?

2020-08-17 17:21 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        clsLocationParamOperator.AddParameter(strParameterValue:="", iPosition:=0, bIncludeArgumentName:=False)
why is this needed?

2020-08-17 17:23 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        clsDetach.AddParameter("unload", "TRUE")
positions?

2020-08-17 17:28 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        bResetDisplayOptions = False
This should be done after `dgExtremesDisplayOptions.ShowDialog()`

2020-08-17 17:28 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        bResetFittingOptions = False
also here

2020-08-17 17:30 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +
single space

2020-08-17 17:33 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        ucrTryModelling.ucrInputTryMessage.txtInput.Controls.Clear()
We should have methods in `ucrTry` class to do this.

2020-08-17 17:38 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        HideAndShowKeyboard()
This is only used here, can you inline code here.

2020-08-17 17:38 UTC, shadrackkibet commented on instat/sdgExtremesDisplayOptions.vb
> +        ucrSavePlots.SetCheckBoxText("Save Graph")
```suggestion
        ucrSavePlots.SetCheckBoxText("Save Graph:")
```

2020-08-17 17:44 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +    End Sub
space here

2020-08-20 09:12 UTC, Ivanluv commented on instat/sdgExtremesDisplayOptions.vb
> +            clsFevdPlotFunction.RemoveParameterByName("type")
This helps in setting the conditions

2020-08-30 08:10 UTC, lloyddewit commented
@Ivanluv There are still some open peer review comments above. Please could you clarify whether they're already resolved, or if you still plan to accept/reject them? thanks

2020-09-01 06:33 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +        clsLocationScaleResetOperator.SetOperation("")
Used in Setting  the RCode for the explanatory model check box

2020-09-01 06:37 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +        clsLocationParamOperator.AddParameter(strParameterValue:="", iPosition:=0, bIncludeArgumentName:=False)
the operator required is, ~"value" ,the operation has no parameter on the left

2020-09-01 06:46 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +        HideAndShowKeyboard()
The parameter is added by the explanatory check box and the checkbox is unchecked by default

2020-09-01 06:46 UTC, Ivanluv commented
@shadrackkibet could you review this again

2020-09-07 15:33 UTC, shadrackkibet commented
- Looks better. Can you try to improve the design, alignments, naming etc? Otherwise, @lilyclements might find some time to help. See below.
![image](https://user-images.githubusercontent.com/26301973/92402107-af042080-f137-11ea-9162-028763918fec.png)
![image](https://user-images.githubusercontent.com/26301973/92402266-ec68ae00-f137-11ea-85f4-a7396194933a.png)
![image](https://user-images.githubusercontent.com/26301973/92402401-276ae180-f138-11ea-80de-157c83b9e130.png)

2020-09-07 15:45 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        clsConvertVector.SetRCommand("as.vector")
Why do you need this function?

2020-09-07 15:46 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        clsFevdPlotsFunction.SetRCommand("plot.fevd")
Just `plot` is enough

2020-09-28 17:52 UTC, Patowhiz reviewed
@Ivanluv would also be helpful if comments you could add comments explaining certain parts of code that are not clear in first glance.

2020-09-28 17:52 UTC, Patowhiz commented on instat/dlgExtremes.vb
> +    Private Sub HideAndShowKeyboard()
@Ivanluv though trivial and probably not necessary subroutine  `HideAndShowKeyboard()` could be simplified to;

```
Private Sub HideAndShowKeyboard()	
	With ucrChkExplanatoryModelForLocationParameter
	     grpFirstCalc.Visible = .Checked
             grpSecondCalc.Visible = .Checked
	End With
 End Sub
```

2020-09-28 17:52 UTC, Patowhiz commented on instat/dlgExtremes.vb
> +        TestOkEnabled()
@Ivanluv `TestOkEnabled()` will by default be called when `SetRCodeForControls(True)` is called(because `ControlContentsChanged` will be raised). This makes calling `TestOkEnabled()` here to be called twice. I noticed this when I put breakpoints in during runtime

2020-09-28 17:52 UTC, Patowhiz commented on instat/dlgExtremes.vb
> +        grpSecondCalc.Visible = False
@Ivanluv I think the 2 lines
```
 grpFirstCalc.Visible = False
 grpSecondCalc.Visible = False
```

could be moved to the designer(set via visual studio properties palette) since they are called once during form load, meaning they are part of the first default state of the form. Also its clear that they are only set in subroutine `HideAndShowKeyboard()`, which is certainly called when contents of the controls concerned are changed.

2020-09-28 17:52 UTC, Patowhiz commented on instat/dlgExtremes.vb
> +    Private clsLocationParamOperator As New ROperator
@Ivanluv though trivial. I think `clsFevdFunction`, `clsNaExclude`, `clsPlotsFunction`, `clsLocationScaleResetOperator`, and `clsLocationParamOperator `don't need to be initialised here. This is done in `SetDefaults()` and the subroutine is always called before they are used.

I also noticed `clsAttach `and `clsDetach` are not initialised in `SetDefaults()`

2020-09-29 09:34 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +            If (ucrInputExtremes.GetText() = "GP" OrElse ucrInputExtremes.GetText() = "PP" OrElse ucrInputExtremes.GetText() = "Exponential") Then
Thanks for this suggestion

2020-09-29 09:43 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +        TestOkEnabled()
True.Am making changes right away

2020-10-07 07:55 UTC, lloyddewit commented
@Ivanluv does the commit above resolve all the peer review comments above, or are you still working on this? thanks for clarifying

2020-10-07 09:09 UTC, Ivanluv commented
@lloyddewit  this resolves all the peer reviews

2020-10-07 10:40 UTC, lloyddewit commented on instat/dlgExtremes.vb
> +        HideAndShowKeyboard()
@Ivanluv Sorry, I didn't understand your comment above. Could this sub be inlined?
```suggestion
        With ucrChkExplanatoryModelForLocationParameter
            grpFirstCalc.Visible = .Checked
            grpSecondCalc.Visible = .Checked
        End With
```

2020-10-07 10:50 UTC, lloyddewit commented
@Ivanluv I went through the previous peer review comments. Most of them seemed to be resolved, so I marked them as resolved. However, some still seem to be open. Please could you review all the comments above that are not marked as resolved?
If you reply to each comment (either accepting suggestion or giving reason for rejecting) then that would be very helpful, thanks

2020-10-07 11:09 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +    Private clsLocationParamOperator As New ROperator
True.I have made this change

2020-10-07 11:09 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +        grpSecondCalc.Visible = False
Done

2020-10-07 11:10 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +    Private Sub HideAndShowKeyboard()
Done

2020-10-07 11:12 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +    End Sub
Done

2020-10-07 11:13 UTC, Ivanluv commented on instat/sdgExtremesDisplayOptions.vb
> +        ucrSavePlots.SetCheckBoxText("Save Graph")
I've made the change

2020-10-07 12:00 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +        ucrInputThresholdforLocation.SetText("0")
` ucrInputThresholdforLocation` is not setting Rcode  so `ucrInputThresholdforLocation.SetText("0")` resets the text to zero on reseting .`ucrReceiverVariable.SetMeAsReceiver()` is also required on resetting since we have two receivers

2020-10-07 12:03 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +        clsConvertVector.SetRCommand("as.vector")
I have removed this since its not required

2020-10-07 12:03 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +        clsFevdPlotsFunction.SetRCommand("plot.fevd")
Done

2020-10-07 12:04 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +            If (ucrInputExtremes.GetText() = "GP" OrElse ucrInputExtremes.GetText() = "PP" OrElse ucrInputExtremes.GetText() = "Exponential") Then
Done

2020-10-07 12:04 UTC, Ivanluv commented
@lloyddewit  could you look at this again

2020-10-08 07:38 UTC, lloyddewit commented on instat/dlgExtremes.vb
> +        HideAndShowKeyboard()
@Ivanluv Please could you resolve the comment above? thanks

2020-10-08 07:45 UTC, lloyddewit commented on instat/dlgExtremes.vb
> +    Private clsLocationParamOperator As New ROperator
@Ivanluv I can't see the change in the code, please could you clarify? thanks

2020-10-08 07:46 UTC, lloyddewit commented
@Ivanluv I think there is one comment in `instat/dlgExtremes.vb` that is still open (see above). Please can you clarify? thanks

2020-10-08 10:37 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +    Private clsLocationParamOperator As New ROperator
Initialisation of `clsAttach` and `clsDetach` is done by ` clsAttach = New RFunction` and  `clsDetach = New RFunction` on lines 102 and 103.As for the whether the initialisation of the `clsFevdFunction`, `clsNaExclude`, `clsPlotsFunction`, `clsLocationScaleResetOperator` functions needs not to be done there am not sure

2020-10-11 10:11 UTC, lloyddewit commented on instat/dlgExtremes.vb
> +    Private clsLocationParamOperator As New ROperator
@Ivanluv Thank you for the clarification about `clsAttach` and `clsDetach`.  Regarding lines 22 to 25 I agree with @Patowhiz that `New` is not needed here. But I don't want to delay because of this so I'm happy to approve.

2020-10-11 10:11 UTC, lloyddewit approved these changes

2020-10-11 10:12 UTC, lloyddewit commented
@rdstern Please could you test/approve? thanks

2020-10-12 21:48 UTC, rdstern commented
There are some important aspects that may need an @dannyparsons discussion.

This is the file I tried with:

[Niger4dly_extremes.zip](https://github.com/africanmathsinitiative/R-Instat/files/5367302/Niger4dly_extremes.zip)

a) In the summary data frame in these data, the y data (in variable max) has missing values.  This works if there is no model, but gives an error if a model is fitted.  The command tries to exclude the missing values, but doesn't work as given, perhaps because the y and x are then inconsistent.  If I filter to the non-missing values in max, then I can fit a model, say station or year, etc.

If that is what is needed, then I am happy for this to continue in that way.  But then perhaps don't do anything in the R code to the dependent variable, but include the default na.action=na.fail, so the error message is clearer.

b) I can have a graph and the default is a nice combined graph.  By default this appears in the output window.  The graph can (sort of) be saved in the dialogue, but it is a graph in the base graphics, so I don't think it does save anything - at least not that is recognised by R-Instat.

I still wonder if ggplotify can be used, so it becomes a ggplot instead.  Then all should work.

As it isn't saved, then I can't display the graph in the R viewer.  I have discussed this aspect in general with @Patowhiz .  However, in the current code I changed the plotting to the following:
```
plot(x=data_book$get_models(data_name="Data_by_year_station", model_name="extreme9"), type="primary")
last_graph <-recordPlot()
```
Can we use this in general and could this also enable the base graphs in general to be saved in objects and then plotted again in the future?

2020-10-22 07:50 UTC, Ivanluv commented
Am ready to complete to once  @dannyparsons  has responded

2020-11-01 11:38 UTC, lloyddewit commented
@dannyparsons is there anything you can do from your side to unblock this PR? thanks

2020-11-29 10:11 UTC, shadrackkibet commented
> a) In the summary data frame in these data, the y data (in variable max) has missing values. This works if there is no model, but gives an error if a model is fitted. The command tries to exclude the missing values, but doesn't work as given, perhaps because the y and x are then inconsistent. If I filter to the non-missing values in max, then I can fit a model, say station or year, etc.

@rdstern please give more details about this error. I am unable to replicate it. Perhaps post the error message as well.

2020-12-11 08:34 UTC, rdstern requested changes
@shadrackkibet sorry for the delay in trying to answer this.  Now it needs updating I think.  It currently says that the version of R is incorrect.

2021-01-04 12:26 UTC, rdstern commented
@Ivanluv this needs updating I think.  It says it needs the new  version of R?

2021-01-04 12:43 UTC, Ivanluv commented
@rdstern I have updated the branch

2021-01-04 17:07 UTC, rdstern requested changes
Here is the code for one example now:
extRemes::fevd(x = stats::na.exclude(object = max), location.fun = ~station + 
    year, type = "GEV", method = "MLE")
I'm not sure this is a good way to try to cope with the missing values, so perhaps that should be undone.  It still gives the same odd message when there are missing values in the data.  I notice now that it also can't cope with missing values in the x'variables.  We might just have to accept that for now.
A minor problem is that when the code, as in the example above, is on 2 lines, then it over-types in the title of the plot - at least for a combined plot.
Perhaps a quick look by @shadrackkibet could help.  Then we merge and improve later.

2021-01-05 12:19 UTC, Ivanluv commented
@Shadrack how can I solve  the over typing problem

2021-01-09 16:57 UTC, shadrackkibet commented
- The function `fevd` has the parameter `na.action` which is meant to deal with missing values. I think to avoid the error we need to exclude missing. Therefore you need to set `na.action = na.omit` or `na.action = na.exclude` . For example
`extRemes::fevd(x = max, na.action = na.exclude, location.fun = ~station +
year, type = "GEV", method = "MLE")` 
- I can't find an easy way to deal with the over-typing issue.

2021-01-27 07:21 UTC, shadrackkibet commented
@Ivanluv can we try to get this merged? anything remaining?

2021-01-27 07:46 UTC, Ivanluv commented
@shadrackkibet  everything is done except for the over-typing issue

2021-01-27 08:09 UTC, rdstern commented
The overtyping in the figure isn't important.  It could be merged now, or the problems with missing values could be investigated further.  Perhaps merge and have this as an issue?

2021-01-27 08:49 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +        ucrInputThresholdforLocation.SetText("0")
Also, reset the save control here.

2021-01-27 09:00 UTC, shadrackkibet commented
Only a few comments and then this should be ready. Since this is an initial implementation it will be good to get it in. Further improvements can be done after further testing.

- When I check the checkbox (Explanatory model for location or scale) and then reopen the dialog the controls below disappear.
- The save control doesn't reset.
- Rename the receiver "**Response Variable:**" which is consistent with **"Model>Fit Model>General"**.

![image](https://user-images.githubusercontent.com/26301973/105967001-67eedb80-6096-11eb-9424-312d724f957c.png)

2021-01-27 11:40 UTC, Ivanluv commented
@shadrackkibet  I have resolved the issues you raised. Could you look at this again

2021-01-27 12:08 UTC, shadrackkibet commented
Looks better now. Over to @lloyddewit for the next steps.

2021-01-28 12:05 UTC, lloyddewit requested changes
@Ivanluv this looks good, just some small comments, thanks

2021-01-29 06:13 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +    Private Sub ucrReceiverVariable_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrReceiverVariable.ControlValueChanged
Done

2021-01-29 07:01 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +    Private Sub cmdPlus_Click(sender As Object, e As EventArgs) Handles cmdPlus.Click
Any suggestions on how to this?

2021-01-29 07:06 UTC, Ivanluv commented on instat/dlgExtremes.vb
>          End If
Done

2021-01-29 07:37 UTC, Ivanluv commented on instat/dlgExtremes.vb
> +    Private bResettingDialogue As Boolean = False
`bResettingDialogue  `prevents the addition of the `scaleLocation `parameter to the `clsLocationScaleResetOperator `operator on resetting

2021-02-01 11:42 UTC, lloyddewit commented on instat/dlgExtremes.vb
> +    Private bResettingDialogue As Boolean = False
Thank you, I took another look and I understand now (`ParameterControl` is called indirectly when `SetRCodeForControls` changes the value of the controls).

2021-02-01 11:43 UTC, lloyddewit commented on instat/dlgExtremes.vb
> +        bResettingDialogue = True
I understand now, please see my other comment below related to `bResettingDialogue `

2021-02-01 12:05 UTC, lloyddewit commented on instat/dlgExtremes.vb
> +    Private Sub cmdPlus_Click(sender As Object, e As EventArgs) Handles cmdPlus.Click
Would something like this work?
```
    Private Sub cmdButton_Click(sender As Object, e As EventArgs) Handles cmdColon.Click, cmdMultiply.Click
        Select Case DirectCast(sender, Button).Name
            Case "cmdColon"
                ucrReceiverExpressionExplanatoryModelForLocParam.AddToReceiverAtCursorPosition(":")
            Case "cmdMultiply"
                ucrReceiverExpressionExplanatoryModelForLocParam.AddToReceiverAtCursorPosition("*")
        End Select
    End Sub
```

2021-02-01 12:06 UTC, lloyddewit commented
@Ivanluv Thanks for all the changes, there is just one comment still open

2021-02-01 12:41 UTC, shadrackkibet commented on instat/dlgExtremes.vb
> +    Private Sub cmdPlus_Click(sender As Object, e As EventArgs) Handles cmdPlus.Click
@lloyddewit I think it is dangerous to use the name of the control among the cases here. If a developer changes the name of the control then this will definitely not work and it might not be easy to know exactly where names are used.

2021-02-02 11:22 UTC, lloyddewit commented on instat/dlgExtremes.vb
> +    Private Sub cmdPlus_Click(sender As Object, e As EventArgs) Handles cmdPlus.Click
> 
> 
> @lloyddewit I think it is dangerous to use the name of the control among the cases here. If a developer changes the name of the control then this will definitely not work and it might not be easy to know exactly where names are used.

@shadrackkibet thank you for the comment. The button event handlers all do roughly the same thing so I tried to think of a way to reduce the duplication. The `sender` parameter contains the type and current state of the calling object so I tried to use this information to identify which button was clicked. I agree that if, in future, a developer changes the control name then the suggested code would also need to be updated. I agree this reduces the code adaptability. I can't think of any better `sender` property we could use. I think vbdotnet expects you to derive a new `EventArgs` class and pass extra information about the event in the `e` parameter. However I think this is too complex for this situation.
In summary, I agree with you, and I can't think of a better solution for now. So I will resolve this comment and approve the PR.
Thanks again for the insightful comment.

2021-02-02 11:23 UTC, lloyddewit approved these changes

2021-02-02 11:24 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2021-02-03 13:45 UTC, rdstern approved these changes
Long-term my only confusion is with missing values.  But I see the comment for the fevd function is as follows:  "function to be called to handle missing values. Generally, this should remain at he default (na.fail), and the user should take care to impute missing values in
an appropriate manner as it may have serious consequences on the results."

So I suggest it be merged and we continue to test.

2021-02-04 08:15 UTC, merged