Infilling climatic element using multiple elements from different sources and Missing value plots from imputeTS package
africanmathsinitiative/R-Instat pull request #5938
Opened 2020-08-21 10:00 UTC by shadrackkibet

@rdstern this is ready for you to test. It is the implementation of the function from **chillR** package for infilling missing values using auxiliary data sources.

2020-08-24 05:23 UTC, rdstern commented
@shadrack ok.  Will do.

2020-08-24 06:22 UTC, rdstern requested changes
1. I am happy that the control about whether to include output has been omitted.  Not important, but (at some stage) it would be good to reposition the other 2 controls.
2. Very good to have the saving variable in the dialogue.  But odd that it isn't the same control as there is, when a single variable is involved.  Then there is the control that includes the position button.
3.  I am not sure why it needs the date variable to be unique?  I first tried with a data frame having multiple stations and it gives an unclear error message.  When I made a new data frame with a single station, then it worked fine.  It is only comparing the 2 (or more) variables, so I am unclear why the date needs to be unique?
4. I need to check, but assume it won't work when a filter (say to a single station) is in operation.  This is a more general issue, and may need to be attacked at some stage - but not yet just for this dialogue.

2020-08-24 16:16 UTC, shadrackkibet commented
> Very good to have the saving variable in the dialogue. But odd that it isn't the same control as there is, when a single variable is involved. Then there is the control that includes the position button.

This is like what we have in start of rains, end of rains etc

2020-08-24 19:58 UTC, rdstern commented
@shadrackkibet but start and end of the rains writes to a new summary data frame, while here we are adding to the existing one.  And the method should be consistent between how we add when we use just the one variable, and whn there are others.

2020-09-06 11:23 UTC, shadrackkibet commented
Fixes  #5944. @rdstern this now includes missing value plots from `imputeTS` package. This is ready for you to test.

2020-09-06 16:50 UTC, rdstern requested changes
@shadrackkibet this is great.  
a) It needs a check of the code when the Station is not filled, or when there is a single station, i.e. the wrapper isn't then needed.  Currently it doesn't then give a graph.  One example I used was the dodoma data which doesn't have a Station variable.
b) It doesn't transfer the graph into the R window.  I can understand that the combined graph doesn't work with Plotly, but it should transfer as an R graph, either from the toolbar or from the dialogue.  @Patowhiz is also looking at this feature in general.
c) In the 4th button there needs to be a 3rd single receiver, perhaps with the label True (Optional): or True Values (Optional):.  
d) The graphs are looking good enough that it will be worth trying to add further options (largely through the sub-dialogue) and also to have more flexibility to display (or not) the titles, so more of the screen can be for the graphs.

2020-09-06 17:01 UTC, shadrackkibet commented
@rdstern I had identified some of these issues. a) and b) should now work and at least you should be able to use plotly when you have one station eg Dodoma.

2020-09-06 17:05 UTC, shadrackkibet commented
Another improvement that is now working is for the **Fit multiple** i.e chillR should now work when you have multiple stations at a time. The station receiver is now enabled and should be working as expected.

2020-09-06 20:38 UTC, rdstern commented
With one station it is great that plotly works.  I hope, eventually, that the R graph display will become available for any graph.  Currently the toolbar icon and the dialogue don't seem to work.  It is available as can be seen by opting in the Tools > Options dialogue to plot there.  Here is an example:
![image](https://user-images.githubusercontent.com/11226469/92334318-97b82b00-f084-11ea-9177-fa1d557906f6.png)

I hope @Patowhiz is examining this in general.
Currently, if Station is selected, then it is a multiple graph, even if the data is filtered to a single station, which is something that could be a useful feature.  I wonder if this can be detected?

In the dialogue there is a lot of space at the top.  The top radio buttons and the controls could move up.  That's partly because there is another control that would be useful - and quite nice not to change the size for this.

So, this could be for the intervals option which can show Percents or Counts.  Maybe just a checkbox (default checked) Show Percents?

2020-09-08 11:42 UTC, shadrackkibet commented
> So, this could be for the intervals option which can show Percents or Counts. Maybe just a checkbox (default checked) Show Percents?

@rdstern I suggest a Combobox with the two options **Percent** and **Counts**. What do you think about that?

2020-09-08 13:49 UTC, shadrackkibet commented
> Currently, if Station is selected, then it is a multiple graph, even if the data is filtered to a single station, which is something that could be a useful feature. I wonder if this can be detected?

Do you mean it always gives you a combined plot with all stations?

2020-09-08 14:02 UTC, rdstern commented
RDS: Currently, if Station is selected, then it is a multiple graph, even if the data is filtered to a single station, which is something that could be a useful feature. I wonder if this can be detected?

SK: Do you mean it always gives you a combined plot with all stations?

RDS: No. It correctly applies the filter.  But it seems to go through your code for a combined graph, so the current system for plotly or R plot don't work.

2020-09-08 14:37 UTC, shadrackkibet commented
Aha! understood now. I can add a check to fix that.

2020-09-10 08:12 UTC, shadrackkibet commented
@rdstern ?

2020-09-14 12:40 UTC, shadrackkibet commented
@rdstern I have now found a way to fix the issue with R graph display for multiple plots. **View last graph** button should now work with the combined plot. `patchwork` package, an extension package to `ggplot2` provides an alternative to `gridExtra` function which work well with `gg` objects. Unfortunately, it doesn't work well with `plotly`, the author of the package is aware of it, according to him this is beyond the scope of the package as reported [here](https://github.com/thomasp85/patchwork/issues/70). I think we can find a workaround using `plotly::subplot()` which works with combining plots.

2020-09-14 14:19 UTC, rdstern commented
That's great.  I am less concerned with plotly with multiple plots than fixing the R display.  We usually want plotly to look into the details of a plot, so will often want to start with a single station.

2020-09-21 06:56 UTC, shadrackkibet commented
@rdstern are you happy with this?

2020-09-29 07:19 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2020-09-30 09:37 UTC, Ivanluv commented
@lloyddewit  the vb code looks fine from my end. I will need help looking at the R script

2020-10-07 09:20 UTC, lloyddewit requested changes
@shadrackkibet This looks good, I only had minor comments. 
@dannyparsons I reviewed the R code with my limited knowledge of R. You are also very welcome to review if you wish

2020-10-07 09:20 UTC, lloyddewit commented on instat/dlgInfillMissingValues.vb
> +            Select Case ucrInputComboFunction.GetValue()
If there is only 2 cases then `If-Then-Else` is normally better

2020-10-07 09:20 UTC, lloyddewit commented on instat/dlgInfillMissingValues.vb
> +                End Select
should we have a `Case Else` to raise a developer error if `GetText` returns something unexpected?

2020-10-07 09:20 UTC, lloyddewit commented on instat/dlgInfillMissingValues.vb
> +        End If
```suggestion
        ucrNudFacetColumns.Visible = (rdoDisplay.Checked OrElse rdoShow.Checked) AndAlso Not ucrReceiverDispMultShowStation.IsEmpty
        lblFacetColumns.Visible = ucrNudFacetColumns.Visible
```

2020-10-12 14:41 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +    patchwork::wrap_plots(plt_list, ncol = ncol)
It's not necessary and fractional less efficient apparently but I prefer to include an explicit `return` statement for clarity.

2020-10-18 11:21 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +  curr_data <- self$get_data_frame(use_current_filter = FALSE)
`date_col` is also used in line 3636.

2020-10-18 11:55 UTC, shadrackkibet commented
@lloyddewit I have addressed points from your review above. This is ready for you to review again. Thanks

2020-10-19 07:30 UTC, lloyddewit submitted a review, later dismissed

2020-10-19 07:31 UTC, lloyddewit commented
@rdstern please could you approve? thanks

2020-10-20 16:45 UTC, shadrackkibet commented
@rdstern this is a reminder for you to approve?

2020-10-20 23:27 UTC, rdstern commented
@shadrackkibet this is looking very good.  I am testing with a new data set namely the 4 stations from Niger.
[niger4day.zip](https://github.com/africanmathsinitiative/R-Instat/files/5412147/niger4day.zip)

a) When going into the dialogue for the first time it gave the error below.  I press OK and it continues fine.
![image](https://user-images.githubusercontent.com/11226469/96653926-1960d100-1332-11eb-9533-aa82785a9d8b.png)

b) I then used the first option for a graph (for minimum temperatures) and it was fine.  When I returned to the dialogue it lost the label for the facets control.

c) I then went to Multiple and used tmax with tmin as the other variable:  This gave the error:
![image](https://user-images.githubusercontent.com/11226469/96654382-187c6f00-1333-11eb-945f-75a6a8a24682.png)

d) I unstacked the data by station to give minimum temperatures for each of the four stations.  I carried all the date variables.  Then I tried with Birni N'Konni with infilling from Niamey.  This gave:

![image](https://user-images.githubusercontent.com/11226469/96654831-0f3fd200-1334-11eb-91cc-72bc6d74417a.png)

2020-10-25 17:39 UTC, shadrackkibet commented
@rdstern I investigated the source of the bug reported in c) above. I think I understand why that happens. This is because some dates are missing in the data you provided above. I used infill missing dates which showed that 30 and 31 days are missing for **Niamey Aero** and **Birni N'Konni** respectively. After infilling it works well. I thought of adding this as a check and infill where necessary. 

d) For this I assume is a non-issue because this dialog is designed for stacked data i.e station in a single column, so unstacking is not needed.

2020-10-28 08:37 UTC, rdstern commented
@shadrackkibet you are quite right with the gaps in the data.  When I corrected that, then it worked.
The next thing I tried was to unstack the data from the 4 stations.  I unstacked tmin by station and carried all the date variables.  Then I sorted by date, so the data are in date order.

When I tried infilling for Agades, using just one station, Niamey, I get:

![image](https://user-images.githubusercontent.com/11226469/97411798-a7235a00-18f8-11eb-992e-ec8b201fd415.png)

Perhaps this is because of the missing values at the start for Agades?

I have a feeling you are close here!

2020-10-28 08:41 UTC, shadrackkibet commented
@rdstern after infilling dates you don't have to unstack the data.

2020-10-28 08:45 UTC, shadrackkibet commented
So something like this should work.
![image](https://user-images.githubusercontent.com/26301973/97412679-ed85b280-1912-11eb-84f7-aa14a60b2446.png)

2020-10-28 10:27 UTC, rdstern commented
@shadrackkibet I realise that I could have done as you suggested.  But I **_also_** wanted to see if an element could be filled-in using the same element from the other stations.  That should also be possible - no?  So infilling Agades tmin, using the values for the same element from Niamey, etc should also work I reckon?

2020-10-28 11:35 UTC, shadrackkibet commented
> @shadrackkibet you are quite right with the gaps in the data. When I corrected that, then it worked.
> The next thing I tried was to unstack the data from the 4 stations. I unstacked tmin by station and carried all the date variables. Then I sorted by date, so the data are in date order.
> 
> When I tried infilling for Agades, using just one station, Niamey, I get:
> 
> ![image](https://user-images.githubusercontent.com/11226469/97411798-a7235a00-18f8-11eb-992e-ec8b201fd415.png)
> 
> Perhaps this is because of the missing values at the start for Agades?
> 
> I have a feeling you are close here!

Aha! I now understand what you were trying to do. That should actually work! I tried unstacking **tmin** and carried date variables as you did. The only other thing I did is to check if there are missing dates in between. So I used our usual dialog "Fill date gaps" I found out that 30 rows for date gaps are missing. Once that is done it works.

2020-10-28 12:23 UTC, shadrackkibet commented
@rdstern I have three options to guide the user accordingly when there are missing dates. What do you think? 

1) Add a check for missing dates which will notify the user through the output window if there are missing dates. In that case, the user will then have to infill missing dates.
2) Have this as an option on the dialog as a checkbox - Fill missing dates.  When checked it infills missing dates. If unchecked a message is printed into the output window.
3) Infill missing dates internally and notify the user that missing dates has been infilled.

2020-10-28 23:49 UTC, rdstern commented
@shadrackkibet this now seems to work well.  I am a bit disappointed in myself that I didn't realise that the missing dates were causing the problem, particularly after you had told me exactly the same reason for the original data.

Anyway I would be happy with your first option, namely to detect and report, and then leave the user to infill the missing gaps.  That's usually done before the data are specified as climatic.  So, if - as I did - this is missed, then the user is reminded.

2020-10-29 08:31 UTC, shadrackkibet commented
@rdstern I have now added a check for the missing dates. Please have a look.

2020-10-29 14:23 UTC, rdstern approved these changes
@shadrack.  This is sensible now and I would be happy to see it merged and then used.  So I am approving.

It is an example that traps an error and now gives a good message.  We have a few other climatic dialogues that try to do similar checks and I wonder about putting the message in the output window instead of in the error message.  I like the fact if gives some details about the infilling when it works, so this would be a shorter message when it doesn't?  What do others including @dannyparsons think?

However I would like to also get the 2nd approval, by @lloyddewit soon so it can be merged

2020-10-29 15:15 UTC, Patowhiz commented
@rdstern I second your idea. 

If it's agreed that having such messages in the output window is the way to go.  Then I suggest such messages to be in a different colour.  To show the difference between normal output and user feedback.

2020-10-30 13:04 UTC, shadrackkibet commented
@rdstern I have now modified this to allow printing of the message into the output window. I also changed the output message when it works.

2020-10-31 19:48 UTC, rdstern approved these changes
@shadrackkibet I like the change and am approving the work at this stage.  It is now a dialogue that will benefit from being used and discussed in the next version.
The Niger data is odd in a variety of ways.  This time I infilled the data in the long form.  The command worked nicely.  I then unstacked tmax for the 4  stations and it first gave an error.  I found that was because the data were not in date order.  When put into date order it now said that there was a gap of -31 days.  Interesting that this was because there were duplicate days.  It could be good to check for duplicates explicitly at some stage, but I also wonder how that happened to the data.

2020-11-01 09:45 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +  curr_data <- self$get_data_frame(use_current_filter = FALSE)
agreed, sorry I missed that

2020-11-01 10:14 UTC, lloyddewit requested changes
@shadrackkibet this looks good, a couple of very minor comments. Also, there's a problem with one of the diffs, thanks

2020-11-01 10:14 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +  self$add_columns_to_data(col_name = column_name, col_data = col)
indent?

2020-11-01 10:14 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +    if (gaps != 0) {
use `else if (gaps != 0) {`?

2020-11-01 10:14 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
> -DataBook <- R6::R6Class("DataBook",
I can't review because something is wrong with the diff, please could you redo your changes so that they are visible in the diff? thanks

2020-11-01 11:01 UTC, lloyddewit approved these changes
@shadrackkibet thanks for the quick changes - all good!

2020-11-01 11:02 UTC, lloyddewit commented
@rdstern there are no functional changes since your last approval, please could you re-approve? thanks

2020-11-03 09:47 UTC, shadrackkibet commented
@rdstern ?

2020-11-03 11:17 UTC, rdstern approved these changes

2020-11-03 11:34 UTC, merged