Setting Autofill property for multiple receiver elements in Climatic>Check Data>Inventory plot
africanmathsinitiative/R-Instat pull request #5951
Opened 2020-08-28 13:42 UTC by Wycklife

Fixes #5929

@africanmathsinitiative/developers This is ready for review

2020-08-30 07:27 UTC, lloyddewit commented
@Ivanluv Please could you review? thanks

2020-08-31 10:03 UTC, Ivanluv commented
@lloyddewit  this looks fine from my end

2020-09-10 07:50 UTC, rdstern requested changes
@wycklife, the change is evident as the dialogue now has autofilled with the defined elements.  That's good.
But was the change checked?  The dialogue no longer works - which is an elementary check to do!  When I look at the R-code, the first line is now absent and hence the variables. are not recognised.

2020-09-10 08:15 UTC, dannyparsons commented
Could this be due to the changes to `ucrReceiver.vb` and `ucrReceiverMultiple.vb`? Any changes here need to be checked extremely carefully as they potentially affect all dialogs.

2020-09-10 13:58 UTC, Wycklife commented
@dannyparsons The error occurs because the bWithQuotes property was set to false and therefore the column names could not be recognized. Otherwise I agree the changes should be checked well by the reviewer.

2020-09-10 14:30 UTC, Wycklife commented
@rdstern Is this dodoma <- data_book$get_data_frame(data_name="dodoma") the line you're referring to? Do we really need it, otherwise it was not there before. The dialog is now working. Could you please check.

2020-09-12 12:22 UTC, rdstern approved these changes
This now seems to work fine.  It is a good improvement.

2020-09-14 08:08 UTC, lloyddewit requested changes

2020-09-14 08:08 UTC, lloyddewit commented on instat/ucrReceiver.vb
> +                    Next
Old functionality (pseudo code):
```
  'If there is only 1 column name 
    'For each selector item
      'If selector item = column name
        'Add selector item to receiver and exit loop
```
New functionality (pseudo code):
```
  'for each selector item
    'for each column name
      'if selector item = column name
        'Add selector item to receiver and exit column name loop
```
Will this impact other dialog boxes that relied on the old functionality?

2020-10-21 16:38 UTC, rdstern submitted a review, later dismissed
This is a small, but useful change by @Wycklife .  I hope it does not cause complications on merging, because the bigger changes have been made in this dialogue.  I believe those have already been merged.
Over to @lloyddewit for a final check

2020-10-22 09:06 UTC, dannyparsons commented on instat/ucrReceiver.vb
> +                        clsIncludeList.AddParameter(kvpInclude.Key, GetListAsRString(kvpInclude.Value.ToList()))
The only difference between `If` and `Else` seems to be whether quotes are used. I don't see why that depends on the number of variables?

2020-10-22 09:09 UTC, dannyparsons commented on instat/ucrReceiver.vb
> +                    Next
I think this makes sense as the extra for loop caters for the when there could be multiple columns to add. @lloyddewit do you agree that the functionality is the same as the old code when `chrColumns.Count = 1`?

2020-10-22 09:54 UTC, lloyddewit requested changes
@Wycklife Please could you respond to the 2 outstanding comments? thanks

2020-10-22 09:54 UTC, lloyddewit commented on instat/ucrReceiver.vb
> +                        clsIncludeList.AddParameter(kvpInclude.Key, GetListAsRString(kvpInclude.Value.ToList()))
@Wycklife Please could you respond to @dannyparsons question above? thanks

2020-10-22 09:54 UTC, lloyddewit commented on instat/ucrReceiver.vb
> +                    Next
@dannyparsons Yes, I agree that the functionality is the same as the old code when `chrColumns.Count <= 1`.

@wycklife Please could you confirm that new functionality pseudo code above is the intended functionality for the case when `chrColumns.Count > 1`? thanks

2020-10-22 11:13 UTC, Wycklife commented
@lloyddewit @dannyparsons  I agree with that statement. The functionality is the same.

2020-10-22 13:05 UTC, lloyddewit commented on instat/ucrReceiver.vb
> +                    Next
> 
> 
> @dannyparsons Yes, I agree that the functionality is the same as the old code when `chrColumns.Count <= 1`.
> 
> @Wycklife Please could you confirm that new functionality pseudo code above is the intended functionality for the case when `chrColumns.Count > 1`? thanks

@Wycklife I saw you marked this comment as resolved so I'll assume that you are confirming the above. Next time, if you can confirm explicitly then it's clearer, thanks

2020-10-22 13:07 UTC, lloyddewit commented
> 
> 
> @lloyddewit @dannyparsons I agree with that statement. The functionality is the same.

@Wycklife sorry, I'm still not clear. I understand what the code is doing but I don't understand why. Please could you quickly explain? thanks

2020-10-22 14:30 UTC, Wycklife commented on instat/ucrReceiver.vb
> +                        clsIncludeList.AddParameter(kvpInclude.Key, GetListAsRString(kvpInclude.Value.ToList()))
This is because I added another method `setClimaticType`(as an overload) in line 527 which takes a list of strings without qoutes while the existing method in line 521 takes only a string which is easy to add quotes at the start and at the end. This means here I needed to have two cases otherwise `GetListAsRString` will add add quotes when it is not needed.

2020-10-23 05:54 UTC, Wycklife commented
@lloyddewit This is because I added another method setClimaticType(as an overload) in line 527 which takes a list of strings without qoutes while the existing method in line 521 takes only a string which is easy to add quotes at the start and at the end. This means here I needed to have two cases otherwise GetListAsRString will add add quotes when it is not needed.

2020-10-23 11:07 UTC, lloyddewit commented on instat/ucrReceiver.vb
> +                        clsIncludeList.AddParameter(kvpInclude.Key, GetListAsRString(kvpInclude.Value.ToList()))
@Wycklife Thank you for the explanation, I think I understand. You are saying that there are now 2 `SetClimaticType` functions. The first takes a single string as parameter, the second takes a list of strings as a parameter. You added the second function in this PR.
```
    Public Sub SetClimaticType(strTemp As String)
        Dim dctTemp As New Dictionary(Of String, String())
        dctTemp.Add("Climatic_Type", {Chr(34) & strTemp & Chr(34)})
        SetIncludedAutoFillProperties(dctTemp)
    End Sub

    Public Sub SetClimaticType(lstStrTemp As String())
        Dim dctTemp As New Dictionary(Of String, String())
        dctTemp.Add("Climatic_Type", lstStrTemp)
        SetIncludedAutoFillProperties(dctTemp)
    End Sub
```
The first function encloses the string in quotes before it adds it to the dictionary, the second function adds each string without quotes. This is not documented in the code. 

Would it be better to change `SetClimaticType(lstStrTemp As String())` so that it also puts quotes around the added strings? Can you see why this could be a better design?

2020-10-23 12:34 UTC, Wycklife commented on instat/ucrReceiver.vb
> +                        clsIncludeList.AddParameter(kvpInclude.Key, GetListAsRString(kvpInclude.Value.ToList()))
@lloyddewit Yeah, Let me try out out this to see if it will work.

2020-10-23 14:09 UTC, Patowhiz commented on instat/ucrReceiver.vb
> +                        clsIncludeList.AddParameter(kvpInclude.Key, GetListAsRString(kvpInclude.Value.ToList()))
@Wycklife  while you are it. You could also change `lstStrTemp` to `arrStrTemp`. It's an array and conforms to the hungarian notation used here.

Another alternative change, trivial and very optional, 
My understanding is, you will have to write a loop for this, so you could make the parameter `lstStrTemp As String()` to be `enumerableStrTemp As IEnumerable(Of String)`. Arrays, Lists and other Collections implement `IEnumerable`. So this makes the overload be more flexible when used externally. And still retains the same functionality.

2020-10-26 11:21 UTC, lloyddewit commented on instat/ucrReceiver.vb
> +                        clsIncludeList.AddParameter(kvpInclude.Key, GetListAsRString(kvpInclude.Value.ToList()))
@Wycklife Another option you could consider is changing the `SetClimaticType(strTemp As String)` function so that it does **not** enclose the string in quotes. This would keep both functions above simple, and also avoid the need for an `If` statement on line 628. Of course, you would need to check all the places where this list is referenced in the code.

The above is independent from @Patowhiz 's comments (they would still apply).

2020-10-29 14:14 UTC, Wycklife commented on instat/ucrReceiver.vb
> +                        clsIncludeList.AddParameter(kvpInclude.Key, GetListAsRString(kvpInclude.Value.ToList()))
@lloyddewit I have used Patrick's second method above.

2020-10-29 16:24 UTC, Wycklife commented
@lloyddewit I have added a loop which converts normal vb.net string values to R-Instat recognized script strings. Kindly check whether this is now okay.

2020-10-30 11:18 UTC, Wycklife commented
@lloyddewit I'm still making some changes on this, once am done I'll alert you.

2020-10-30 12:02 UTC, Wycklife commented
@lloyddewit This is now ready for you to check. Thank you

2020-11-01 11:20 UTC, lloyddewit approved these changes
@Wycklife Thanks for the changes, looks good!

2020-11-01 11:21 UTC, lloyddewit commented
@rdstern Please could you re-test? thanks

2020-11-15 10:40 UTC, lloyddewit commented
@rdstern Please could you re-test? thanks

2020-11-17 09:02 UTC, rdstern approved these changes
ok

2020-11-17 14:43 UTC, lloyddewit commented
@dannyparsons Please could you review before this is merged? thanks

2020-11-17 21:24 UTC, dannyparsons requested changes

2020-12-07 07:42 UTC, Wycklife commented on instat/ucrReceiver.vb
> +    Public Sub SetClimaticType(enumerableStrTemp As IEnumerable(Of String))
Okay

2020-12-07 11:18 UTC, lloyddewit commented
@Wycklife You marked the comments above (from @dannyparsons) as resolved. However, I couldn't see any commits so I assume that the changes still need to be made.
You should only resolve a comment when any necessary changes have been committed.
If I misunderstood anything then please let me know, thanks

2020-12-07 14:16 UTC, Wycklife commented
@lloyddewit Ooh! I'm sorry I have just confirmed the changes I made didn't come through because of internet connection, let me try a gain.

2021-02-22 16:24 UTC, dannyparsons commented
This is now replaced by #6233 (not branched so closing this)

2021-02-22 16:24 UTC, closed without merging