Download gridded data from IRI as Netcdf format
africanmathsinitiative/R-Instat pull request #5958
Opened 2020-09-02 18:49 UTC by shadrackkibet

Fixes #3995. @dannyparsons @rdstern I am putting up this for you to have a look. Danny, I am getting below bugs especially with **CHIRPS** when downloading data. Sometimes it works, when I change the time range. Perhaps it is an internet issue? I tried copying the link from VS output window into the browser, sometimes it downloads the file but then when I try to open the file using Netcdf dialog I get an error as shown below. I am not sure why. 

**Download from IRI**
![image](https://user-images.githubusercontent.com/26301973/92022660-46e2c280-ed64-11ea-983b-1aed3c3b13df.png)

**Import Netcdf**
![image](https://user-images.githubusercontent.com/26301973/92023598-a7263400-ed65-11ea-96e3-8d097d490f60.png)

2020-09-02 19:58 UTC, rdstern commented
One option did work at your defaults.  But I then got similar error messages to the above, i.e.
![image](https://user-images.githubusercontent.com/11226469/92030182-97572180-ed5e-11ea-8258-046248b7743d.png)

Then I re-tried the same options as worked before and got something like the above error again.

I am keen on being able to import the different sources of rainfall data.  But I assume other elements are also available.  At this stage I would not object to a long list as it seems to be an excellent source of data.

2020-09-03 11:45 UTC, dannyparsons commented
I would try testing in RStudio so that you figure out which parts of the R code are giving the error. And also check that the URL is being constructed correctly each time by printing it and trying to use the URL directly.
That may be linked to the second issue of opening the file.

2020-09-03 15:58 UTC, dannyparsons commented
I'm struggling to get any NetCDF files to download from the IRI site directly. Can you try this as well? I tried CHIRPS and TAMSAT it just gives files of size 0.

2020-09-04 16:05 UTC, shadrackkibet commented
@rdstern @dannyparsons this is now working better. I found out that fixing the `method = "libcurl" or "curl"` in `download.file()` works better rather than `auto`.

2020-09-07 08:04 UTC, rdstern commented
I tried with roughly the defaults and TAMSAT data.  After quite a long time - 5 minutes it said:
![image](https://user-images.githubusercontent.com/11226469/92361942-1cd42c00-f0e7-11ea-9149-44d68c5cc051.png)

In addition:

a) There is the option to save the file.  Is this instead (or as well) as putting into the data frame?  Would that be an rds file or an nc file? It could be that we wish to download a large file (say for an area) and then only open the subset that corresponds to the stations?  Then we might want to save it, but not put it in R-Instat.  If not, then maybe that could be added and called called Transfer and be additional to save?
b) I am given no prior information on the size of the file I am downloading.  Is this possible.  I think it is worked out incorrectly by IRI?  It would be like a Try feature?
c) We have the problem in R-Instat that this operation might take a long time and we can't interrupt a command.  Could a transfer be "in the background" so we could continue with other work?

2020-09-07 10:21 UTC, dannyparsons commented
> @rdstern @dannyparsons this is now working better. I found out that fixing the method = "libcurl" or "curl" in download.file() works better rather than auto.

I preferred the "auto" method because it gives a pop up download box. If it doesn't work then no problem, but could you check it definitely doesn't work this way? There was an issue with the IRI site so it might work now.

2020-09-07 10:29 UTC, dannyparsons commented
> a) There is the option to save the file. Is this instead (or as well) as putting into the data frame? Would that be an rds file or an nc file? It could be that we wish to download a large file (say for an area) and then only open the subset that corresponds to the stations? Then we might want to save it, but not put it in R-Instat. If not, then maybe that could be added and called called Transfer and be additional to save?

The saved file is the downloaded NetCDF file. This could be clarified on the dialog if it's not clear. The dialog should give the option to download without importing exactly for the reason you mention. Importing would import everything.

> b) I am given no prior information on the size of the file I am downloading. Is this possible. I think it is worked out incorrectly by IRI? It would be like a Try feature?

If we list the spatial and temporal resolution of each data source hard coded in the dialog code then we can estimate quite accurately the number of rows to be imported. We could then try to estimate how this relates to file size by comparing sizes with number of observations, but this is really not simple. It may be different for different data sources and will also depend on each dimension e.g. a long time series for one point may be bigger/smaller than the same number of observations for a single time point. We would really be guessing as this can only be known from IRI and it doesn't seem to provide it for subsets well.

> c) We have the problem in R-Instat that this operation might take a long time and we can't interrupt a command. Could a transfer be "in the background" so we could continue with other work?

It could be but I don't think I would recommend this as it needs a lot of processing power to run two versions of R in separate threads. It would need a lot of testing and checking to see how stable this is and I guess it's not important enough for that. I hope we can have the download progress bar as that is very useful.

2020-09-10 11:13 UTC, dannyparsons commented
- It allows me to have the min date after the max date. I think we can prevent this on the dialog.

2020-09-14 13:49 UTC, shadrackkibet commented
@dannyparsons can you have a look into this again? I have now made the changes you requested above.

2020-09-14 14:43 UTC, dannyparsons commented on instat/ucrDateTimePicker.vb
> +    Public Function CurrentDate(Optional bWithQuotes As Boolean = True) As String
Could you rename this to `ValueAsString` to be consistent with `ValueAsRDate` and also add a parameter for the separator which can be `"/"` by default?

2020-09-14 14:44 UTC, dannyparsons commented on instat/ucrDateTimePicker.vb
> +    Public Function CurrentDate(Optional bWithQuotes As Boolean = True) As String
Actually, you shouldn't need this function because the control can return a Date function automatically.

2020-09-14 14:45 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +        clsDefaultEndDate.AddParameter("x", ucrDtpMaxDate.CurrentDate())
The date picker control is set up to return an `as.Date()` function you can pass in directly so you don't need create these R functions in the dialog.

2020-09-14 15:03 UTC, dannyparsons commented
The min date is correctly limited to the minimum date of the data, but the max date doesn't have the same lower limit. Can you add that too?

Also, the pop up about the max date being higher than the min date comes up a lot of times as you're changing the dates. Could you set this so that it only appears once and then doesn't appear again until the dialog is reset?

2020-09-14 19:07 UTC, dannyparsons commented
Thanks, that seems to address those issues. I'm making a comment on the issue for design changes.

2020-09-15 09:27 UTC, lloyddewit commented
@shadrackkibet thank you for the changes. Is this PR now ready for review or do you still expect more commits? thanks

2020-09-15 09:32 UTC, shadrackkibet commented
I still have more TODO before this is ready for re-review. Thanks

2020-09-15 19:00 UTC, shadrackkibet commented
@dannyparsons I have now incorporated the changes as outlined in the issue, please have a look. I left out CMORPH from the dialog but the code is there, we will enable once we agree on which options to include. 

I am unable to download TAMSAT v3 data, even directly from the browser using URLs. e.g [http://iridl.ldeo.columbia.edu/SOURCES/.Reading/.Meteorology/.TAMSAT/.TARCAT/.v3p1/.daily/.rfe/X/%2810E%29/%2810.5E%29/RANGEEDGES/Y/%2810N%29/%2810.5N%29/RANGEEDGES/data.nc](http://iridl.ldeo.columbia.edu/SOURCES/.Reading/.Meteorology/.TAMSAT/.TARCAT/.v3p1/.daily/.rfe/X/%2810E%29/%2810.5E%29/RANGEEDGES/Y/%2810N%29/%2810.5N%29/RANGEEDGES/data.nc). It is taking long to load with no success. Could you also try? Not sure if this is an issue from IRI servers. There seem to be issues accessing data from time to time from IRI servers. Yesterday I was unable to download CMORPH data, on enquiry via email they said it was an issue from their end which seems to have been fixed now.

2020-09-16 08:26 UTC, dannyparsons commented
Great thanks I'll check.

The TAMSAT data also didn't download for me. I also tried restricting it to a few days and it still doesn't work. Text seems to work ok but not NetCDF. Can you send them another query about this? It's generally been stable for me in the past so I hope this is just a temporary instability.

2020-09-16 14:50 UTC, dannyparsons reviewed
The design looks much better and it's working well. A few comments below, and two other points:

- the new data frame name is quite long. Can this instead be just the source name (in lower case)? And if easy in R we add a label attribute to the data frame which gives full details e.g. "TAMSAT v3.1 Daily Rainfall 31/10/2000 - 1/11/2000 Point: (34,58, 0)"
- If I check "Don't import after downloading" then the data frame name box should disappear

2020-09-16 14:50 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
>    }else if(source=="NOAA_RFE2") {prexyaddress <- paste0(init_URL, ".NOAA/.NCEP/.CPC/.FEWS/.Africa")
The sources should now match the dialog so this should just be "NOAA" and it should just add the NOAA part of the URL, then the rest is specific to the choice so it should go in the data part.
The same applies to the other sources.

2020-09-16 14:50 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +      if(data == "daily_estimated_prcp"){extension <- ".DAILY/.RFEv2/.est_prcp"}#(days since 2000-10-31 12:00:00) ordered (31 Oct 2000) to (12 Sep 2020)
The data names should also be updated to include the data set e.g. `data == "rfe2_daily_estimated_prcp"`

2020-09-16 14:50 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +        rdoEntireRange.Checked = True
This should be easy to have conditions based on whether the data parameters are present? The default is the whole range so the date parameters should not be included by default.

2020-09-16 14:50 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +        clsDownloadFromIRIFunction.AddParameter("path", (Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) & "\Downloads").Replace("\", "/"), iPosition:=2)
```suggestion
        clsDownloadFromIRIFunction.AddParameter("path", Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments).Replace("\", "/"), iPosition:=2)
```

I see that Downloads isn't part of Special Folders so in case of any issues on some machines with this workaround let's use Documents instead which shouldn't ever cause problems.

2020-09-16 14:50 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +        clsDownloadFromIRIFunction.AddParameter("max_lat", 10.5, iPosition:=6)
The default for these doesn't really matter as long as it's somewhere in Africa that is in most of the sources, but we though a nice default would be the Maseno station: lon = 34.58, lat = 0. Then add 0.5 to each for max.

2020-09-16 14:50 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +        clsDownloadFromIRIFunction.AddParameter("max_lat", 10.5, iPosition:=6)
And if it's easy, can we have a single point as the default?

2020-09-16 14:50 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +    else stop("Data file does not exist for TAMSAT data")
I got an error here with this code: 
`data_book$download_from_IRI(source="TAMSAT", data="daily_recovered_rainfall_estimate", path="C:/Users/Danny/Documents", min_lon=34.58, min_lat=0, min_date=as.Date(x="2000/10/31"), max_date=as.Date(x="2000/11/1"), name="TAMSAT_v3.1 Daily Rainfall Complete (Filled)_31_10_2000_01_11_2000", download_type="point")`

I think it's missing this data option from the list.

2020-09-21 08:14 UTC, shadrackkibet commented on instat/dlgImportGriddedData.vb
> +        rdoEntireRange.Checked = True
@dannyparsons I tried removing `min_date` and `max_date` from the default with conditions set as shown below

```
ucrPnlDateRange.AddParameterPresentCondition(rdoCustomRange, {"min_date", "max_date"})
ucrPnlDateRange.AddParameterPresentCondition(rdoArea, {"min_date", "max_date"}, False)
```
On testing, no radio button is checked. What could be the problem?

I also tried adding `min_date` by default with the following conditions

```
ucrPnlDateRange.AddParameterPresentCondition(rdoCustomRange, "min_date")
ucrPnlDateRange.AddParameterPresentCondition(rdoArea, "min_date", False)
```
this worked as expected i.e `rdoCustomRange` is checked by default.

2020-09-21 08:38 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +        rdoEntireRange.Checked = True
Not sure why that should be if they are both added by default. Still, the condition on `min_date` is still valid.

2020-09-21 10:25 UTC, shadrackkibet commented on instat/dlgImportGriddedData.vb
> +        rdoEntireRange.Checked = True
Fixed now. Thanks

2020-09-21 10:32 UTC, shadrackkibet commented
@dannyparsons could you have a look into this again?

2020-10-05 08:27 UTC, shadrackkibet commented
@dannyparsons I am trying to add TAMSAT v3.0 but seems restricting of values and ranges doesn't wok for v3.0. How did you get this to work? For example, what could be the problem with this link? [https://iridl.ldeo.columbia.edu/SOURCES/.Reading/.Meteorology/.TAMSAT/.TARCAT/.v3p0/.daily/.rfe/X/(34.58E)/VALUES/Y/(0N)/VALUES/](https://iridl.ldeo.columbia.edu/SOURCES/.Reading/.Meteorology/.TAMSAT/.TARCAT/.v3p0/.daily/.rfe/X/(34.58E)/VALUES/Y/(0N)/VALUES/)

2020-10-05 13:14 UTC, dannyparsons commented
If you go to the data source https://iridl.ldeo.columbia.edu/SOURCES/.Reading/.Meteorology/.TAMSAT/.TARCAT/.v3p0/.daily/.rfe and then use the website to restrict the range you see that it uses lon and lat instead of X and Y e.g. https://iridl.ldeo.columbia.edu/SOURCES/.Reading/.Meteorology/.TAMSAT/.TARCAT/.v3p0/.daily/.rfe/lon/%2819.0125W%29%2840E%29RANGEEDGES/lat/%284S%29%2835.9625S%29RANGEEDGES/
So we need to be able to have different dimension names when restricting the range. I wasn't actually aware it wasn't always X and Y.

2020-10-05 13:16 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +    prexyaddress <- paste0(init_URL, ".NOAA/.NCEP/.CPC/.FEWS/.Africa/.DAILY/.ARC2")
Can you change this so that the source is just "NOAA". And then include "ARC2" in the data part? We may have other NOAA products to add in future so the base URL will be different.

2020-10-05 13:19 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +  } else if (source == "NOAA") {
So this combines with "NOAA_ARC2" above with "NOAA" as the source and ARC2 Daily, RFE2 daily etc. being data options for that source.

2020-10-08 13:56 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +                dctFiles.Add("Daily Precipitation 0.25 degree", Chr(34) & "daily_improved_global_0p25_prcp" & Chr(34))
Can you move this one to the bottom of the list? I think it will be least common to want the low resolution version.

2020-10-13 08:44 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +                dctFiles.Add("Daily estimated Precipitation", Chr(34) & "daily_est_prcp" & Chr(34))
```suggestion
                dctFiles.Add("ARC2 Daily Precipitation", Chr(34) & "daily_est_prcp" & Chr(34))

```

2020-10-13 08:44 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +                dctFiles.Add("Monthly estimated Precipitation", Chr(34) & "monthly_est_prcp" & Chr(34))
```suggestion
                dctFiles.Add("ARC2 Monthly Precipitation", Chr(34) & "monthly_est_prcp" & Chr(34))

```

2020-10-13 09:32 UTC, dannyparsons reviewed
This looks good now, just the TAMSAT v3.0 options need to be added and the dimension names issue to be resolved. I have commented below on how to approach these.

2020-10-13 09:32 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +add_xy_area_range <- function(path, min_lon, max_lon, min_lat, max_lat) {
Add two parameters here, `dim_x = "X"` and `dim_y = "Y"` so that we can change the dimension names to "lon" and "lat" for TAMSAT case.

2020-10-13 09:32 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +add_xy_point_range <- function(path, min_lon, min_lat) {
Same here as above.

2020-10-13 09:32 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +  init_URL <- "https://iridl.ldeo.columbia.edu/SOURCES/"
Define `dim_x = "X"` and `dim_y = "Y"` as variables here. Then in the TAMSAT section set `dim_x = "lon"`, `dim_y = "lat"` so that correct names are used.

2020-10-13 09:32 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +    URL <- add_xy_point_range(path = prexyaddress, min_lon = min_lon, min_lat = min_lat)
add the new `dim_x` and `dim_y` defined parameters here to ensure correct url.

2020-10-13 09:32 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +                dctFiles.Add("v3.1 Daily Rainfall", Chr(34) & "daily_rfe" & Chr(34))
Can you add v3.0 options here as well? Put them at the top for now since there is an issue with v3.1.

2020-10-18 11:13 UTC, shadrackkibet commented
@dannyparsons TAMSAT v3.0 is now added. Please check.

2020-10-20 16:44 UTC, shadrackkibet commented
@dannyparsons @rdstern this is a reminder for you to check.

2020-10-20 22:17 UTC, rdstern reviewed
@shadrack this is impressive.
a) The only minor issue I could find was with the ARC2 data, where the minimum date should be 1/1/1983, and it is currently the same are the (correct) RFE data at October 2000.
b) At the top there is correctly) the name of the dialogue.  Should (internet connection needed) be added?

These are just comments:
c) I don't have a good way to do this, but I has to wait about 25 minutes for a single point to be copied - for the whole time period.  
d) The place it is saved reminds me that I wonder if we should soon have an issue to be able to set a working directory?  This might even be an item that would be on the file menu and also perhaps on our new front menu.

2020-10-21 08:08 UTC, shadrackkibet commented
@rdstern a) and b) done!

2020-10-21 08:56 UTC, dannyparsons requested changes
Just one minor change.

2020-10-21 08:56 UTC, dannyparsons commented on instat/dlgImportGriddedData.vb
> +        dctDownloadPairs.Add("UCSB_CHIRPS", Chr(34) & "UCSB_CHIRPS" & Chr(34))
Can you remove the `_`  from the display name? That will make them more readable.

2020-10-21 09:05 UTC, shadrackkibet commented on instat/dlgImportGriddedData.vb
> +        dctDownloadPairs.Add("UCSB_CHIRPS", Chr(34) & "UCSB_CHIRPS" & Chr(34))
Done!

2020-10-21 09:19 UTC, dannyparsons submitted a review, later dismissed
Great.

2020-10-21 10:22 UTC, lloyddewit commented
@rdstern I understand from the comments above that your concerns have all been addressed. Please could you re-approve?

@dannyparsons If I see that you have already approved a PR then I will assume that my final review/approval is no longer needed. If I misunderstood then please let me know, thanks

2020-10-21 15:27 UTC, rdstern approved these changes
@shadrackkibet this is great.  I assume @lloyddewit to give the final review, unless already done

2020-10-21 16:05 UTC, dannyparsons approved these changes
I take it from Stephen's comment that I can approve and merge.

2020-10-21 16:05 UTC, merged