Adding the GEV and GP extreme distributions to Show model and generate random Samples Dialogues
africanmathsinitiative/R-Instat pull request #5961
Opened 2020-09-03 12:56 UTC by Ivanluv

2020-09-18 14:40 UTC, rdstern approved these changes
These changes seem fine

2020-09-20 07:41 UTC, lloyddewit commented
@shadrackkibet please could you review? thanks

2020-09-29 07:26 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  #if (min(p, na.rm = TRUE) <= 0 || max(p, na.rm = TRUE) >= 1) stop("qevd: invalid p argument.  Must have 0 < p < 1.")
We need to understand why this line of code is causing issues.

2020-10-01 11:19 UTC, rdstern requested changes
I have found a small problem.  This dialogue can be used without a data frame being present, i.e. with "no data loaded".  This gives an error, but then works and produces the graph.  Unless it is trivial to fix, I suggest we don't allow OK to be enabled in this dialogue unless there is a data frame.  

Once merged, there remain a lot of further changes to the probabilities dialogue.

2020-11-01 11:40 UTC, lloyddewit commented
@Ivanluv are you able to implement the change @rdstern requested?

2021-01-04 12:28 UTC, rdstern requested changes
This also needs an update because of the version of R

2021-01-05 11:59 UTC, rdstern requested changes
@Ivanluv this needs the update for the version of R.

2021-01-05 12:07 UTC, Ivanluv commented
@rdstern it already has conflicts .I am to work on the issue again and close this PR

2021-01-27 07:23 UTC, shadrackkibet commented
@Ivanluv any progress here?

2021-01-27 07:32 UTC, Ivanluv commented
@shadrackkibet currently none .I don't understand the R changes to be implemented for this to work. I therefore asked @rdstern to have this assigned to someone else

2021-01-27 08:12 UTC, rdstern commented
I thought that was ok, i.e. show model and random samples.  What remains is adding these distributions to the Fit > One Variable dialogue.  That may be implicit here or a different issue.

In the one variable fit, this was waiting until the test and estimate were merged - which has now happened.

2021-01-27 10:05 UTC, lloyddewit commented
@Ivanluv I'm not sure how to interpret the comments above. Are you able to progress this (potentially with support) or should we try and find someone else to take over?
thanks for clarifying

2021-01-27 10:25 UTC, rdstern commented
I was assuming this would be done by @shadrackkibet

2021-01-27 10:34 UTC, shadrackkibet commented
Happy to take over. Thanks.

2021-01-27 10:46 UTC, Ivanluv commented
@shadrackkibet take over

2021-01-27 11:03 UTC, shadrackkibet commented on instat/My Project/Resources.resx
> +  </data>
@Ivanluv  are you able to remove changes from these files? This will ensure a smooth takeover.

2021-01-27 11:22 UTC, Ivanluv commented on instat/My Project/Resources.resx
> +  </data>
Let me do so

2021-01-27 11:50 UTC, Ivanluv commented on instat/My Project/Resources.resx
> +  </data>
Done

2021-01-27 12:10 UTC, shadrackkibet commented on instat/My Project/Resources.Designer.vb
> +    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
What about this?

2021-01-28 09:11 UTC, shadrackkibet commented on instat/My Project/Resources.Designer.vb
> +     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
I still see some changes in this file.

2021-05-25 15:52 UTC, lloyddewit commented
This PR is replaced by PR #6214

2021-05-25 15:52 UTC, closed without merging