Adding the summary R function in dlgInventory
africanmathsinitiative/R-Instat pull request #5962
Opened 2020-09-03 15:26 UTC by N-thony

I have added the summary R function in the dlgInventory form of the issue #5385. 
So, I'm waiting for this PR to be review.

2020-09-05 18:43 UTC, rdstern requested changes
@N-thony and @lilyclements this is great so far.
First comments on the design.
a) Sorry, but I think the graph should come first.  It is an inventory of both what is present and what is absent.  So instead of Summary I propose the second button (now) be called Missing.
b) The 2 graph sub-dialogue buttons remain present for the Summary/Missing option.  They don't need to be visible.  Then the controls can be moved up.
c) Currently when you return to the dialogue, the Summary controls are not visible.  (You get them back by going Graph and then back to Summary.)
d) Add a (checkbox) with the label Save Details: Then a name for the new data frame that will be saved.  
e) In the function, with the details, add a 6th variable with the name Level and Value either Year, Month, Day, etc
f) In the function for the summary perhaps use % instead of Percentage. Then the width of the output may be less and go on one line in the default output window.
g) I like the fact that a tibble (or multiple Tibbles) are produced, but not the additional output.  Can it be neater.
h) How should the saving be done?  I think the summary can always go in the output window.  It is just the details that are saved.  Are they part of the function or in the R code in addition to the function?  And they are in a single data frame, for all the levels that were chosen.
i) When results are in the output window the default shows just a few lines.  Can this limit be higher.  Perhaps it is usefully an argument in the dialogue?

2020-09-08 07:47 UTC, lilyclements commented
Another small point - under "Details", the "Hour", "Minute", "Second" option should be disabled as the code isn't written for this yet

2020-09-08 07:54 UTC, lilyclements commented
Also, I noticed this function has been added to the `stand_alone_functions.R` file and is called `climatic.summary`.
Tidyverse functions tend to use an underscore between words rather than a dot (as well as the other functions written in this file for R-Instat) so for consistency this should be changed to `climatic_summary` (or perhaps `climatic_missing` since @rdstern is suggesting we change the radio button for this option from "Summary" to "Missing")

2020-09-08 15:47 UTC, N-thony commented
> 
> 
> @N-thony and @lilyclements this is great so far.
> First comments on the design.
> a) Sorry, but I think the graph should come first. It is an inventory of both what is present and what is absent. So instead of Summary I propose the second button (now) be called Missing.
> b) The 2 graph sub-dialogue buttons remain present for the Summary/Missing option. They don't need to be visible. Then the controls can be moved up.
> c) Currently when you return to the dialogue, the Summary controls are not visible. (You get them back by going Graph and then back to Summary.)
> d) Add a (checkbox) with the label Save Details: Then a name for the new data frame that will be saved.
> e) In the function, with the details, add a 6th variable with the name Level and Value either Year, Month, Day, etc
> f) In the function for the summary perhaps use % instead of Percentage. Then the width of the output may be less and go on one line in the default output window.
> g) I like the fact that a tibble (or multiple Tibbles) are produced, but not the additional output. Can it be neater.
> h) How should the saving be done? I think the summary can always go in the output window. It is just the details that are saved. Are they part of the function or in the R code in addition to the function? And they are in a single data frame, for all the levels that were chosen.
> i) When results are in the output window the default shows just a few lines. Can this limit be higher. Perhaps it is usefully an argument in the dialogue?

1) I don't understand well the comment g), could you be more precise about the additional output.
2) I'm confused about the comments d) and h)
3) I also don't understand well the comment i) about the default when the results are in the outputs window.
Could you clarify that with screenshots?
I have already made some changes regarding others' comments apart e) and f) I think they are for @lilyclements.

2020-09-09 07:06 UTC, shadrackkibet requested changes

2020-09-09 07:06 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  if (summary == TRUE){
No need to be explicit when using booleans in R e.g `summary == TRUE`. Just `summary` is enough. I see several other places where this is done.

2020-09-09 07:06 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +        group_by({{ stations }}, Element ) %>%
Always add the package e.g `dplyr::group_by()`.

2020-09-09 07:26 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    #print(summary.data)
should be removed?

2020-09-09 07:40 UTC, N-thony commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    #print(summary.data)
Yes

2020-09-09 07:40 UTC, N-thony commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  if (summary == TRUE){
Okay.

2020-09-10 06:46 UTC, N-thony commented
I have made changes according to the comments. I'm waiting for @lilyclements to update the R function with **save details** and the remaining parameters Hour, Minute, and Second.

2020-09-11 11:19 UTC, lilyclements commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    data %>% mutate(stations = 1)
Apologies for not writing this into the function when I sent it, but any place where the following functions are given, can you add `dplyr::` in front?

* `mutate`
* `group_by`
* `arrange`
* `filter`
* `summarise`

2020-09-11 11:20 UTC, lilyclements commented
@rdstern thank you for your points. You have listed some changes to make to the R-function. Are these the sorts of changes you were referring to the other day to give to someone else to take over, or should I make the changes?

2020-09-11 15:33 UTC, rdstern commented
@N-thony I washoping you would be able to make the changes to the R function?  @lilyclements can provide advice where needed.  Otherwise Lily is prepared to make the changes.  What do you think?

2020-09-11 16:17 UTC, N-thony commented
> 
> 
> @N-thony I was hoping you would be able to make the changes to the R function? @lilyclements can provide advice where needed. Otherwise Lily is prepared to make the changes. What do you think?

The first option is better, I will try to make all the remaining change and contact @lilyclements if I find any problem.

2020-09-16 12:55 UTC, N-thony commented
I have made all  the changes according the first comments from @rdstern. So this PR is ready to be review.

2020-09-16 13:54 UTC, lloyddewit commented
@africanmathsinitiative/admin please could you peer review? thanks

2020-09-21 14:02 UTC, Ivanluv commented
@lloyddewit  the code for the Inventory dialogue looks fine from my end.@Shadrack can help me look at the R script

2020-09-22 08:13 UTC, shadrackkibet reviewed
A question, why do we need two functions here? can't this be one method with `details` as an option? 

I understand there might be a difficulty in printing output and saving data frame at the same time. I think this method need to be moved into `instat_object_R6/instat_data_object` which will need to be readapted to fit into the structures.

2020-09-22 08:24 UTC, lilyclements commented
@N-thony out of interest where have the parameters under the "Graph" option been moved to?

[On current]
![image](https://user-images.githubusercontent.com/21180424/93770863-aff78080-fc14-11ea-86fd-ece4f35e4169.png)

[On this branch]
![image](https://user-images.githubusercontent.com/21180424/93770475-22b42c00-fc14-11ea-90d9-493ae07cfc19.png)

2020-09-22 08:41 UTC, shadrackkibet reviewed
A couple of other issues;

- The top radio button doesn't retain the selected state.
- Align controls 
- ucrsave doesn't reset.
- Check details checkbox doesn't retain the selected state, check also other controls linked to it.

Posssibly Rcode problems below

- There might be an issue with `year, month, day` checkboxes how should that work? I always got a column with labels `day` when all are checked.
- I got odd results when I have data from multiple stations see below screenshot, the first column always indicate station?
![image](https://user-images.githubusercontent.com/26301973/93860061-26ed5180-fcc7-11ea-9f29-ae21cb5d87e3.png)

2020-09-22 08:41 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +            ucrChkDetails.Checked = False
`ucrChkDetails.Checked = False`
Checking and unchecking should not be done manually. Set conditions and that will be done through Rcode. Let me know if you need some help.

2020-09-22 08:41 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +            pnlDetails.Location = New Point(pnlDetails.Location.X, iPnlDetailsY / 1.08)
Why do you need a windows form panel? We only use add radio buttons into our custom `ucrPanel`. Other controls are normally added to a group box.

2020-09-22 08:51 UTC, shadrackkibet commented
That is all for now! I feel like there is still more to report. Please sort out those ones then I can look into it again.

2020-09-22 09:49 UTC, N-thony commented on instat/dlgInventoryPlot.vb
> +            ucrChkDetails.Checked = False
I think it may be the data, because in mine with dodoma. If there is no month or year and only day in what you are printing, you will only get day in the column level.

2020-09-22 09:57 UTC, lilyclements commented
> Posssibly Rcode problems below
> 
> * There might be an issue with `year, month, day` checkboxes how should that work? I always got a column with labels `day` when all are checked.
> * I got odd results when I have data from multiple stations see below screenshot, the first column always indicate station?

@shadrackkibet to the first point, did you check all three checkboxes? The R code in your image implies only `day` was checked so I'm wondering if this is an issue with the dialog code.

2020-09-22 11:15 UTC, shadrackkibet commented
> @shadrackkibet to the first point, did you check all three checkboxes for day, month, and year? The R code in your image implies only day was checked so I'm wondering if this is an issue with the dialog code.

@lilyclements yes, I checked `day, month` and `year` as shown below

![image](https://user-images.githubusercontent.com/26301973/93875275-5eff8f00-fcdd-11ea-970d-26651e1df117.png)

Here is the code
```
# Code generated by the dialog, Inventory
ghana <- data_book$get_data_frame(data_name="ghana")
date <- data_book$get_columns_from_data(data_name="ghana", col_names="date")
climatic_missing(data=ghana, date=date, stations="station", elements="rainfall")

   Element X.station.       From         To Missing Percentage "station"
1 rainfall    station 1944-01-01 2016-12-31      66     0.1245   station
  Complete.Years
1             67

date <- data_book$get_columns_from_data(data_name="ghana", col_names="date")
climatic_details1 <- climatic_details(month=TRUE, year=TRUE, data=ghana, date=date, stations="station", elements="rainfall")
data_book$import_data(data_tables=list(climatic_details1=climatic_details1))


rm(list=c("ghana", "date", "climatic_details1", "date"))
```
The output below

![image](https://user-images.githubusercontent.com/26301973/93875496-c289bc80-fcdd-11ea-871d-6406a654bd7a.png)

2020-09-22 11:28 UTC, lilyclements commented
> date <- data_book$get_columns_from_data(data_name="ghana", col_names="date")
> climatic_details1 <- climatic_details(month=TRUE, year=TRUE, data=ghana, date=date, stations="station", elements="rainfall")
> data_book$import_data(data_tables=list(climatic_details1=climatic_details1))

@shadrackkibet if I move this code into R and run `stations = station` (i.e., not as a string) then it is no longer a problem. So `.SetParameterIsRFunction()` should sort this out too.
Note that there is no output for `year` since the most consecutive missing days in this data set is 31 days.

```
# station run as a string means that the month/year options are not given
climatic_details(month=TRUE, year=TRUE, data=ghana, date=date, stations="station", elements="rainfall")

# station not run as a string fixes this
climatic_details(month=TRUE, year=TRUE, data=ghana, date=date, stations=station, elements="rainfall")
```

2020-09-27 21:31 UTC, N-thony commented
I have made the change regarding the first review of dlgInventory. So this PR is ready for the second review.

2020-09-28 10:14 UTC, lilyclements requested changes
Additionally, under the Missing radio button:
* The `ucrSaveDetails` does not reset properly - it stayed checked/unchecked despite the reset (and removes the name in the save if I reset with it unchecked)
* If I uncheck `Summary` and click OK, then reopen the dialog, the `summary` checkbox is checked again.
* Similarly, if I uncheck both `Summary` and `Details` and press OK, `climatic_missing` still runs

Under the Graph radio button, there is a bug if the "Year-DOY plot" is selected. I checked and this is a bug on the main version (I think in the R-Code) so I can explore this one a bit.

2020-09-28 10:14 UTC, lilyclements commented on instat/dlgInventoryPlot.vb
> +        If (Not ucrReceiverDate.IsEmpty AndAlso Not ucrReceiverElements.IsEmpty) Then
This needs to be amended:
* OK should not be enabled if the ucrSaveGraph is not complete when the graph radio button is selected.
* OK should not be enabled if the ucrSaveDetails is not complete when the rdoMissing and ucrChkDetails are selected. 
* OK should not be enabled if the rdoMissing is selected and neither of ucrChkDetails or ucrChkSummary are checked, since no code can run.
* OK should not be enabled if rdoMissing and ucrChkDetails is selected, but none of the Year/Month/Day/Hour/Minute/Second checkboxes are checked.

2020-09-28 10:46 UTC, N-thony commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                                                  Percentage = sum(is.na(value))/n()*100))
Sorry for this one.

2020-09-30 14:24 UTC, shadrackkibet requested changes

2020-09-30 14:24 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    summary.data <- data.frame(data.stack %>%
The output here is a data frame. Therefore `data.frame` is not needed. This will then allow the use of `%`.

2020-10-01 07:10 UTC, N-thony commented
I made the change regarding the second review of this branch and fixing some bugs in code. This PR is ready for a review.

2020-10-01 08:40 UTC, lilyclements reviewed
Looks good, I have two minor comments with (hopefully) fixes.

Design-wise, under "Graph" the checkboxes should all be aligned. Currently they're not aligned with the checkbox in the ucrBase.

2020-10-01 08:40 UTC, lilyclements commented on instat/dlgInventoryPlot.vb
> +    Private Sub AllControls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrSaveGraph.ControlContentsChanged, ucrReceiverElements.ControlContentsChanged, ucrReceiverDate.ControlConten
You need to add `ucrSaveDetails` to this list as well

2020-10-01 08:40 UTC, lilyclements commented on instat/dlgInventoryPlot.vb
> +        clsClimaticDetails.SetAssignTo("last_details", strTempDataframe:=ucrInventoryPlotSelector.ucrAvailableDataFrames.cboAvailableDataFrames.Text, strTempTable:="last_details")
I'm getting an error with the `ucrSaveDetails` after clicking Reset:
Run the dialog as normal, and click OK
Reopen the dialog and click "Reset"
Then click Missing > Details > Save Details and change the name of the new data frame which contains the details table, an error pops up

> .temp_val <- capture.output(data_book$add_table(table_name="last_details", table=test, data_name="test")

This error is calling a table not a data frame. While it is a summary table, the table is saved as a data frame.

I think this problem is due to this line because you're running `strTempTable` here, but the object being saved is a data frame. I think this should instead read `strDataFrameNames`

2020-10-01 11:43 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +    Private Sub AllControls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrSaveGraph.ControlContentsChanged, ucrReceiverElements.ControlContentsChanged, ucrReceiverDate.ControlConten
Also change `ucrPnlOptions.ControlValueChanged` to `ucrPnlOptions.ControlContentsChanged`

2020-10-04 08:23 UTC, lloyddewit commented
@N-thony there are 2 comments from @lilyclements above. I saw that you marked them both as resolved. However the comments ask for changes and I don't see any new commits. Please could you clarify? thanks

2020-10-04 12:37 UTC, N-thony commented
> 
> 
> @N-thony there are 2 comments from @lilyclements above. I saw that you marked them both as resolved. However the comments ask for changes and I don't see any new commits. Please could you clarify? thanks

Yeah it's true. I have already resolved these comments. Before making a commit I was checking the dialog again and I found that under missing if you close the dialog and reopen when ucrChkSummary and ucrChkDetails are unchecked I have a message in the image below.
![Uploading image.png…]()

2020-10-05 07:17 UTC, N-thony commented
Currently under Missing if you close the dialog and reopen when ucrChkSummary and ucrChkDetails are unchecked there is a message before the dialog to reopen. I'm trying to fix it

2020-10-06 09:46 UTC, N-thony commented
To avoid the developer message under missing if the dialog is closed and you want to reopen the dialog when ucrChkMissing and ucrChkDetails are unchecked, I have set ucrBase to run 'climatic_missing' RCode when the dialog is reopened so ucrChkSummary will be checked only under Missing when both ucrChkSummary and ucrChkDetails are unchecked when the dialog is closed.

2020-10-06 15:07 UTC, lilyclements commented on instat/dlgInventoryPlot.vb
> +            If (Not ucrReceiverDate.IsEmpty AndAlso Not ucrReceiverElements.IsEmpty AndAlso (ucrChkSummary.Checked OrElse (ucrChkDetails.Checked AndAlso ucrSaveDetails.IsComplete AndAlso (ucrChkYear.
This should instead read 
`If (Not ucrReceiverDate.IsEmpty AndAlso Not ucrReceiverElements.IsEmpty AndAlso (ucrChkDetails.Checked AndAlso ucrSaveDetails.IsComplete AndAlso (ucrChkYear.Checked OrElse ucrChkMonth.Checked OrElse ucrChkDay.Checked OrElse ucrChkHour.Checked OrElse ucrChkMinute.Checked OrElse ucrChkSecond.Checked)))) AndAlso (ucrChkSummary.Checked OrElse ucrChkDetails.Checked) Then`

That is, remove the first `ucrChkSummary.Checked OrElse (...`since at the moment you can have the `ucrSaveDetails` incomplete (or none of the year/month/day boxes checked) if both `ucrChkDetails` and `ucrChkSummary` are selected

2020-10-07 06:41 UTC, N-thony commented
@lilyclements I solved the issue you raised on 6 October. Please could you confirm that your comment is resolved? thanks.

2020-10-07 15:02 UTC, lilyclements commented on instat/dlgInventoryPlot.vb
> +                    Exit Sub
Out of interest, what does `Exit Sub` do?

2020-10-07 16:14 UTC, N-thony commented
@lilyclements I solved the issue you raised 1 hour ago. Please could you confirm that your comment is resolved? thanks.

2020-10-07 16:24 UTC, N-thony commented
@lilyclements I solved the issue you raised 1 hour ago. Please could you confirm that your comment is resolved? thanks.

2020-10-07 16:49 UTC, lilyclements commented
@N-thony this resolves my comment, thanks

2020-10-08 07:25 UTC, lloyddewit commented
> 
> 
> That is all for now! I feel like there is still more to report. Please sort out those ones then I can look into it again.

@shadrackkibet Thank you for the review you did earlier on this PR. Please could you do a second review (or let me know if its not needed)? thanks

2020-10-18 08:52 UTC, shadrackkibet commented
This PR has conflicts. Please resolve so that I can review it.

2020-10-18 13:59 UTC, N-thony commented
@shadrackkibet I have resolved the conflicts in this PR. Could you please review it. Thanks.

2020-10-18 15:04 UTC, shadrackkibet requested changes

2020-10-18 15:04 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +        If rdoMissing.Checked AndAlso Not ucrChkSummary.Checked AndAlso Not ucrChkDetails.Checked Then
Should this be ` If rdoMissing.Checked AndAlso Not (ucrChkSummary.Checked OrElse ucrChkDetails.Checked Then)`?

2020-10-18 15:04 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  }
Was this resolved?

2020-10-19 08:05 UTC, N-thony commented
@shadrackkibet I solved the issues you raised on 18 October. Please could you confirm that your comments are resolved? thanks.

2020-10-19 08:34 UTC, shadrackkibet commented
Looks better now. @rdstern, please test.

2020-10-19 10:20 UTC, rdstern requested changes
@N-thony this is now working fine.  I am sure there will be further suggestions for improvements.  But I would like to get it merged very soon, so users can try it.
2 very minor suggestions are as follows:  If not trivial, the leave for now.
a) In the summary the % missing is given with many decimals.  Could it easily be fixed to be just one decimal, e.g. 3.6, 17.4.
b) The label for the Complete.Years is long and that variable is sometimes on new lines.  Change the heading to Full_Years.
I hope, in parallel that @lloyddewit could check the code, so it can be approved and merged soon.

2020-10-19 12:40 UTC, N-thony commented
@rdstern  I solved the issues you raised few hours ago. Please could you confirm that your comments are resolved? thanks

2020-10-19 13:01 UTC, N-thony commented
@rdstern  I solved the issues you raised a few hours ago. Please could you confirm that your comments are resolved? Thanks.

2020-10-19 16:08 UTC, rdstern submitted a review, later dismissed
@N-thony great.
I can always think of improvements, but would like this now to be merged and then we can test it further.  Over to @lloyddewit to check finally on the code

2020-10-20 06:13 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> -    'End Sub
why is this removed?

2020-10-20 06:25 UTC, N-thony commented on instat/dlgInventoryPlot.vb
> -    'End Sub
I have just set it to be automatic. In SetRCode... I have added for ucrReceiverStation an AddAdditionalCodeParameterPair.

2020-10-20 06:35 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> -    'End Sub
okay

2020-10-20 06:39 UTC, shadrackkibet commented
The dialog design is messed up as shown below when I do the following

- Click on Missing radio button
- Check details checkbox
- Check to save details checkbox
- Click Graph radio button

![image](https://user-images.githubusercontent.com/26301973/96549429-23de8480-12b8-11eb-9f3b-a44866cdb747.png)

2020-10-20 06:41 UTC, N-thony commented
> 
> 
> The dialog design is messed up as shown below when I do the following
> 
>     * Click on Missing radio button
> 
>     * Check details checkbox
> 
>     * Check save details checkbox
> 
>     * Click Graph radio button
> 
> 
> ![image](https://user-images.githubusercontent.com/26301973/96549429-23de8480-12b8-11eb-9f3b-a44866cdb747.png)

Okay, I see.

2020-10-20 07:11 UTC, N-thony commented
@shadrackkibet I have solved the tissue your raised a few minutes ago. Could you please confirm that your comment is resolved? Thanks.

2020-10-20 09:01 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +        End If
This should also run when closing the dialog (red X). `me.Closing`. Otherwise you still get the developer error when "X" is used to close the dialog.

2020-10-20 09:10 UTC, shadrackkibet requested changes

2020-10-20 09:10 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +        clsInventoryPlot.AddParameter("facet_by", "NULL")
Add parameter positions

2020-10-20 09:10 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +        ucrChkDetails.AddToLinkedControls({ucrChkDay, ucrSaveDetails}, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True)
Remove `ucrSaveDetails` here. It is not necessary.

2020-10-20 09:10 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +        ucrChkSummary.SetLinkedDisplayControl(ucrPnlOrder)
This is not needed.

2020-10-20 09:10 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +        ucrPnlOrder.SetLinkedDisplayControl(rdoElementOrder)
Remove these two redundant lines 172 and 173.

2020-10-20 10:53 UTC, N-thony commented
@shadrackkibet I have solved the tissues your raised a few minutes ago. Could you please confirm that your comments are resolved? Thanks.

2020-10-20 11:24 UTC, shadrackkibet commented
Looks good!

2020-10-20 15:17 UTC, lloyddewit commented
@rdstern please could you retest and approve? thanks

2020-10-20 15:37 UTC, rdstern commented
I can approve as it stands.  But I have been using the dialogue and found a small item that could perhaps be done now.
@N-thony when the inventory is saved it carries over the station as a factor variable, but the element and levels are character.  Could you make them also into factors?

I really would like this to be merged in the Thursday version, so will approve if you don't have the time for this.

2020-10-20 15:41 UTC, shadrackkibet commented
Do we have a release on Thursday? I wasn't aware of that!

2020-10-20 15:48 UTC, rdstern commented
@shadrackkibet you are right to question this!  I wrote the message a week ago to explain this.  It would have been a bit better if I had also remembered to send it!

2020-10-20 15:52 UTC, N-thony commented
> I can approve as it stands. But I have been using the dialogue and found a small item that could perhaps be done now.
> @N-thony when the inventory is saved it carries over the station as a factor variable, but the element and levels are character. Could you make them also into factors?
> 
> I really would like this to be merged in the Thursday version, so will approve if you don't have the time for this.

I'm doing it now.

2020-10-20 16:28 UTC, N-thony commented
@rdstern I have made the change on elements and levels to be factors. Could you please confirm that it fine now? thanks.

2020-10-20 19:08 UTC, rdstern approved these changes
@N-thony great.  Thanks

2020-10-21 10:48 UTC, lloyddewit approved these changes
@N-thony good work, well done!

2020-10-21 10:48 UTC, merged