Bar And Pie Chart Dialog Bug
africanmathsinitiative/R-Instat pull request #5967
Opened 2020-09-05 03:02 UTC by Patowhiz

Fixes #5950
@africanmathsinitiative/developers this is ready for review.

2020-09-09 08:35 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2020-09-09 13:27 UTC, Ivanluv commented
@lloyddewit  looking at this now

2020-09-10 07:52 UTC, Ivanluv commented
@Patowhiz  could we just have the argument name in ,`clsRCoordPolarParam.SetArgumentName("coord_polar")` ,  from `coord_polar `   to   `coordPolar`?

2020-09-10 08:30 UTC, Patowhiz commented
@Ivanluv thanks for the suggestion. May I ask, why `coordPolar`? As I mentioned in this [comment](https://github.com/africanmathsinitiative/R-Instat/issues/5950#issuecomment-682086458), the `coord_polar` which is a ggplot  function can exist when when bar chart or pie chart is produced. Is `coordPolar` unique to the bar chart or the pie chart, assuming its a ggplot function?

2020-09-10 09:19 UTC, Ivanluv commented
As I understand it,the condition is using the the  functions argument name and not the functions  command name.So when we change the name to `coordPolar`(to be used by the Pie charts radio button for its `coord_polar` function) it will differentiate it from `coord_polar` name (which is in the subdialogue)

2020-09-10 10:27 UTC, Patowhiz commented
> As I understand it,the condition is using the the functions argument name and not the functions command name.So when we change the name to `coordPolar`(to be used by the Pie charts radio button for its `coord_polar` function) it will differentiate it from `coord_polar` name (which is in the subdialogue)

@Ivanluv thank you for the suggestion. Now I understand. This should definitely work.

2020-09-10 10:39 UTC, Patowhiz commented
@Ivanluv I added your much appreciated suggestion. This is now ready for your review

2020-09-10 11:16 UTC, Ivanluv commented
@lloyddewit  This looks okay from my end

2020-09-11 08:29 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2020-09-22 20:15 UTC, rdstern approved these changes
This seems fine now.  Over to @lloyddewit for the second approval

2020-09-23 08:02 UTC, lloyddewit requested changes
@Patowhiz I only have a couple of very small suggestions. However there's something else I'm a bit confused by. Your final commit reversed all your previous changes (including the lines you previously commented out). Did @Ivanluv 's suggestion to change the parameter name solve the bug and make the previous changes superfluous?

2020-10-07 09:25 UTC, lloyddewit commented
@Patowhiz Please could you clarify the status of this PR? thanks

2020-10-13 06:27 UTC, Patowhiz commented on instat/dlgBarAndPieChart.vb
> +        ucrPnlOptions.AddParameterPresentCondition(rdoBarChart, "coordpolar", False)
@lloyddewit my choosing of using small case was influenced by how it's been done in other dialogs. 
`dlgInsertColumns.vb`, `dlgRatingScales.vb`, `dlgReplaceValues.vb` and many others .

Most dialogs are using small case in naming parameter arguments. In regards to this case, the parameter argument name was coord_polar but that was unique enough and resulted  in a bug cause there is already an operator with such name. So I removed the hyphen and concatenated the word retaining the case to what was already there and also used in other dialogs.

In regards to the hungarian notation in R-Instat, I think this has been adopted mainly in the VB.NET side. The scripts generated are not strict in this.

I'm happy to use either if you strongly think otherwise.

2020-10-13 06:33 UTC, Patowhiz commented
@lloyddewit I have responded to your review. Other than the naming this PR is ready

2020-10-13 06:56 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +        ucrPnlOptions.AddParameterPresentCondition(rdoBarChart, "coordpolar", False)
Thank you for the explanation. I assume you mean 'the parameter argument name was coord_polar but that was * **not** * unique enough and resulted in a bug'. I'm happy with all lower case names if that's consistent with other dialogs.

2020-10-13 06:56 UTC, lloyddewit approved these changes

2020-10-13 06:57 UTC, merged

2020-10-14 06:05 UTC, Patowhiz commented on instat/dlgBarAndPieChart.vb
> +        ucrPnlOptions.AddParameterPresentCondition(rdoBarChart, "coordpolar", False)
Yes, I meant **not**

2020-10-14 06:08 UTC, Patowhiz commented
> @Patowhiz I only have a couple of very small suggestions. However there's something else I'm a bit confused by. Your final commit reversed all your previous changes (including the lines you previously commented out). Did @Ivanluv 's suggestion to change the parameter name solve the bug and make the previous changes superfluous?

Yes. I only needed to make the parameter argument name to be unique. The subdialog already had a parameter argument name called `coord_polar` which when added to the base function resulted in the bug.