Added menu items under Structured>Circular
africanmathsinitiative/R-Instat pull request #5970
Opened 2020-09-08 11:36 UTC by HawardKetoyoMsatsi

Fixes #5964

@africanmathsinitiative/developers This is ready for review.

2020-09-09 06:35 UTC, shadrackkibet commented
I think we can continue further with this work by adding new empty forms  for the proposed dialogs into this PR.  With help from others, we can support @HawardKetoyoMsatsi to implement these dialogs.

2020-09-11 10:09 UTC, HawardKetoyoMsatsi commented
@Wycklife and I have added empty dialogs for the Rose plots and others mentioned on #5974 . @africanmathsinitiative/developers  Someone to review these changes and the merging should be quick so that we can begin work on these dialogs. Thank you.

2020-09-11 10:11 UTC, HawardKetoyoMsatsi commented
@rdstern  we have decided to have all the six additional Rose plots in one dialog named Other Rose Plots, is this okay?

2020-09-11 10:55 UTC, lloyddewit commented
@africanmathsinitiative/developers For speed, I think we can bypass your review for this PR. If @rdstern approves, then I can review/approve/merge.

2020-09-11 16:06 UTC, HawardKetoyoMsatsi commented
@dannyparsons @Wycklife have added a time series dialog and a sub dialog with controls. Kindly get the changes from this branch. @africanmathsinitiative/developers This also fixes #5973 .

2020-09-11 16:18 UTC, dannyparsons commented
There are probably too many changes here for one pull request, but I am ok with the time series dialog added here for speed of getting that done.

@HawardKetoyoMsatsi there are two small changes in `dlgCalculator.vb` and `sdgSummaries.vb` which seem unrelated to the issue. If these are intentional could you explain them?

2020-09-12 07:56 UTC, HawardKetoyoMsatsi commented
> There are probably too many changes here for one pull request, but I am ok with the time series dialog added here for speed of getting that done.
> 
> @HawardKetoyoMsatsi there are two small changes in `dlgCalculator.vb` and `sdgSummaries.vb` which seem unrelated to the issue. If these are intentional could you explain them?

@dannyparsons These changes are related to this issue. 
The Structured>Circular>Calculator menu opens dlgCalculator with which the default calculator should be Circular Calculator. The Structured>Circular>Summaries>Summaries opens sdgSummaries  which needs open with the default being Circular in order to give column statistics for circular data...

2020-09-14 06:57 UTC, lloyddewit commented
@HawardKetoyoMsatsi Thenak you for the recent changes. Do you plan any more commits to this PR or can we go ahead with review and merge? thanks

2020-09-14 07:08 UTC, HawardKetoyoMsatsi commented
@lloyddewit I don't have any changes. You can go ahead with review and merge. 
Thanks

2020-09-14 08:31 UTC, lloyddewit requested changes
@HawardKetoyoMsatsi Thank you for the changes, I just had a couple of comments, thanks

2020-09-14 08:31 UTC, lloyddewit commented on instat/sdgSummaries.vb
> +    Public iIndex As Integer
Give this a default value of zero?

2020-09-14 08:31 UTC, lloyddewit commented on instat/frmMain.vb
> +        sdgSummaries.iIndex = 0
Not needed if iIndex has default value of zero?
This comment applies to all the similar cases below

2020-09-14 09:58 UTC, dannyparsons reviewed
Sorry I have made what seems to be trivial changes more complicated but there are some important software development principles that we want to stick to even for small changes. I have tried to explain the ideas in the comments below but get back to me if anything's not clear.

2020-09-14 09:58 UTC, dannyparsons commented on instat/frmMain.vb
> +        sdgSummaries.iIndex = 0
I think if the dialog was opened previously then it may now not be 0 so would need to be reset. However, I don't think this is the best way to implement this. I will explain in the general comment.

2020-09-14 09:58 UTC, dannyparsons commented on instat/dlgCalculator.vb
> +    Public strDefaultItem As String
I like this approach to add a variable to control which tab to show by default. 
However, good practice would be to make this `Private` and then add a method to set this such as `SetDefaultItem()` which can be called to set this variable.
The reason for this is that a method will allow us to make checks on what this variable is set as. For example, what happens if someone sets this to something that doesn't exist? The method allows us to have a consistent way of setting the variables and ensure errors and trapped. The method can be simple for now with just a line to set the variable and the checks can be added later.
Check with @shadrackkibet if any of this is not clear or get back to me.

2020-09-14 09:58 UTC, dannyparsons commented on instat/sdgSummaries.vb
> +    Public iIndex As Integer
Can you change this to be a character instead of an integer? The reason is that it will be easy to make a mistake and set the wrong number whereas a character is clearer, and also when we add new tabs we potentially change the order of the tabs which would mean the tab numbers will be wrong whereas we can associate the names to a tab number and change them in one place if needed.

Can you do a similar thing to the suggestion for the calculator dialog? i.e. make this `Private` and have a method to set? You need to be careful about when this is then applied. It is not only when resetting, it could be that the tab needs to be changed after the first time it's opened because it's opened from another place. I suggest we use `""` to indicate not to change the tab (unless it's being reset then it goes back to first time). There are a few different cases here so think them out carefully.

2020-09-14 09:58 UTC, dannyparsons commented on instat/frmMain.vb
> +        dlgCalculator.strDefaultItem = "Basic"
So my comment above means this line will be replaced by a call to a method e.g. `dlgCalculator.SetDefaultItem("Basic")`

2020-09-14 09:58 UTC, dannyparsons commented on instat/frmMain.vb
> +        sdgSummaries.iIndex = 0
We can avoid having to set this back to the default in every other place by setting the variable back to the default in the sub dialog after it's been applied.

2020-09-14 09:58 UTC, dannyparsons commented on instat/sdgSummaries.vb
> +    Public iIndex As Integer
Also, I think there should be an equivalent variable in `dlgColumnSummaries` to be able to set this. We should not be setting something on the sub dialog directly without going through the main dialog, because the main dialog may also have functionality which conflicts. For example, if we had a method in the main dialog to also set the default tab, then it would overwrite an external change.

The right place to be setting a default for the sub dialog is when the main dialog sets up the sub dialog. So we should add a way of setting this through the main dialog.

2020-09-14 15:00 UTC, dannyparsons commented
@HawardKetoyoMsatsi now that you have the new Seasonality plot dialog to do would you like me to finish off the changes I suggested to this above if you haven't already done this? Then you can concentrate on the new dialog.

2020-09-14 17:21 UTC, HawardKetoyoMsatsi commented
Sure, you finish off the changes let me continue with the Seasonality plot dialog.

2020-09-15 09:57 UTC, dannyparsons commented
Ok I'll work on this now. We need to be careful about conflicts, because the seasonality dialog is added in this pull request. So you need to wait for this to be merged before making a new pull request for the seasonality dialog, but you could start work on the dialog and copy over changes once this is merged. Check with @shadrackkibet about that.

2020-09-15 12:24 UTC, HawardKetoyoMsatsi commented
I am working on it on a new branch, once the merging is done I will copy my work to update the seasonality dialog accordingly.

2020-09-16 09:08 UTC, dannyparsons commented on instat/dlgCalculator.vb
> +    Public strDefaultItem As String
@HawardKetoyoMsatsi if you're interested in how I implemented this see the changes here https://github.com/africanmathsinitiative/R-Instat/pull/5983/commits/caef5d6ef573440da9b6a1a23dda393c81cd0688

2020-09-16 10:21 UTC, lloyddewit commented
@HawardKetoyoMsatsi I understand that PR #5983 includes all your updates (with some adjustments from Danny). So I think it's OK to close this PR. Please let me know if I misunderstood, thanks

2020-09-16 12:05 UTC, dannyparsons commented
That's fine to close but because my new PR is branched from here it would automatically close when the new PR is merged. The advantage of leaving this to be done automatically is that any linked issues will get closed at the correct time when the new PR is merged.

2020-09-16 12:23 UTC, lloyddewit commented
@dannyparsons yes, I forgot that GitHub would detect that the commits are merged and close this PR automatically, that's a better way of doing it.

2020-09-16 14:06 UTC, merged