Changes to General Graphics dialogue
africanmathsinitiative/R-Instat pull request #5971
Opened 2020-09-09 13:22 UTC by Ivanluv

@africanmathsinitiative/developers this fixes #5552.Its still in progress

2020-09-29 08:33 UTC, Ivanluv commented on instat/ucrGeom.vb
> +                    'For Each clsParam In lstAllGeoms(iCurrentGeomIndex).clsLayerParameters
@Patowhiz  I am looking at issue #5552 and I think the code I have commented causes the issue raised ie 

> I then Edit and make the width of the jitter 0.2 and the alpha into 0.1.
Then I Edit the boxplot and make the outlier colour into blue
Then edit the jitter again and you see that the width of the jitter is still 0.2, but the alpha argument has become unset.
Interesting!

I  however don't understanding why and how  the code  is of use.  Could you kindly take a look at this and help me understand

2020-11-01 11:43 UTC, lloyddewit commented
@Ivanluv please could you clarify the status of this PR? do you still need help from @Patowhiz ? thanks

2020-11-02 07:17 UTC, Ivanluv commented
@lloyddewit I got help but am still working on this

2021-01-04 10:20 UTC, Ivanluv commented
@africanmathsinitiative/developers this is ready for review

2021-01-05 08:38 UTC, lloyddewit commented
@shadrackkibet Please could you review? thanks

2021-03-16 10:50 UTC, lloyddewit requested changes

2021-03-16 10:50 UTC, lloyddewit commented on instat/ucrAdditionalLayers.vb
> +        End If
The selected items will always be a subset of the total items. Therefore, do we need this extra check?
If we do need the extra check then would it be more readable to make this function:
```
    Private Sub SetEditDeleteEnabled()
        If lstLayers.Items.Count > 0 AndAlso lstLayers.SelectedItems.Count = 1 Then
            cmdDelete.Enabled = True
            cmdEdit.Enabled = True
        Else
            cmdDelete.Enabled = False
            cmdEdit.Enabled = False
        End If
    End Sub
```

2021-03-16 10:50 UTC, lloyddewit commented on instat/ucrGeom.vb
> +                    bResetGlobal = bReset
`ucrInputGeoms.SetName` does not seem to use `bResetGlobal `, and it is set to false 2 lines later. Do we need this line?

2021-03-16 10:50 UTC, lloyddewit commented on instat/ucrGeom.vb
> +                    'Why do we have to remove the parameters here?
```suggestion
                    'TODO Why do we have to remove the parameters here?
```

2021-03-16 12:05 UTC, Ivanluv commented on instat/ucrGeom.vb
> +                    bResetGlobal = bReset
its used by the event `ucrInputGeoms.ControlValueChanged` thats called during `ucrInputGeoms.SetName`

2021-03-16 13:33 UTC, lloyddewit commented on instat/ucrGeom.vb
> +                    bResetGlobal = bReset
OK, thanks for the explanation

2021-03-16 13:34 UTC, lloyddewit approved these changes

2021-03-16 13:38 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2021-03-16 15:00 UTC, lloyddewit commented
@Ivanluv As suggested by @dannyparsons, this PR affects all graphics dialogs, so @dannyparsons or @volloholic will also review before we merge.

2021-03-24 12:05 UTC, dannyparsons commented
Thanks I'll discuss with @volloholic about reviewing.

2021-03-26 16:32 UTC, rdstern approved these changes

2021-03-31 08:16 UTC, merged