Improvements to the Enter Dialog
africanmathsinitiative/R-Instat pull request #5972
Opened 2020-09-09 14:40 UTC by Wycklife

Fixes the last two parts of #5596

1. Swapping the calculator basic keyboard and the enter basic keyboard
2. Added keys and improvements to the existing enter keyboard
3. Added examples and tool tips to the list view linked  with the example button.
4. Replaced the old save control with the new control and set the positioning of the variables

@africanmathsinitiative/developers This is ready for review

2020-09-09 14:41 UTC, Wycklife commented
@lilyclements This is ready for you to look at the design first.  Thanks.

2020-09-12 10:57 UTC, lilyclements commented
@Wycklife can you update this branch with the master? Then I can make some design changes and push them into your branch (if you're happy with them)

2020-09-12 11:36 UTC, Wycklife commented
@lilyclements Okay I am doing that.

2020-09-12 12:46 UTC, Wycklife commented
@lilyclements The branch has been updated

2020-09-13 08:40 UTC, rdstern commented
@Wycklife this has made good progress.  I mention what has been done well and also what remains - I should say that some of what remains is because of errors I made in the instructions.

a) The new examples have been added together with the tooltips.  Please now detete the original examples, they are the top 4 ones, down to month.abb.
b) The new save control with the position added, is included.  Great.
c) There is an oddity to try to fix.  The first examples now are 4.5 and 'Nairobi'.  @Wycklife I wonder if you tested them?  If so, you might have noticed that the Try control doesn't work.  It says they are an error - but they are not, in the sense that they do give an acceptable variable.  Can you fix the try control?  This is something that @Patowhiz has examined for another dialogue, so he may be able to help if you get stuck.
d) The main changes are to the second keyboard.  I need to add tooltips and there should also be changes in the keyboard.
1) the keyboard should move down a bit, so the keys are alighted with the main keyboard.
2) The keys should become narrower, so the dialogue, as a whole is not so wide.
3) Sorry, I do need to change some of the keys and also the layout.  Your putting them into alphabetical order is sensible, but I propose below a new set and order.
4. It remains as 16 keys and I list them in the next message going across:

2020-09-13 12:05 UTC, rdstern commented
Row 1:
a) Change : to `[ :]` with the cursor before the colon.  Tooltip A subset, e.g. letters[1:4] gives a, b, c, d.
b) The second is `letters` as now. Tooltip: The letters, e.g. letters[1:4] gives a, b, c, d. Type LETTERS[1:4] for A, B, C, D.
c) factor, to now give `forcats::as_factor( )`. Tooltip: e.g. forcats::as_factor("B","C","A") to make the contents into a factor variable with the levels in the order as entered, so here B is the lowest level.

(This reminds me.  Can you change the second factor example to forcats::as_factor(rep(LETTERS[4:1],c(4,3,1,1))) with tooltip changed to Gives D,D,D,D,C,C,C,B,A as a fa ctor.)
d) rnorm as before, giving rnorm( ) as now, but also adding the parameters when that is ticked. Tooltip: Random sample from a normal distribution, e.g. rnorm(36, 100, 15) gives 36 observations from a distribution with mean 100 and s.d. 15; rnorm(36) is from a standard normal distribution.
More to come.

2020-10-12 09:37 UTC, Wycklife commented
@rdstern I have fixed items 1 to 4 above. On the try conrol, I have gone through the control and realized that the control only accept commands not single elements. I'm not sure on how to add this an additional property to the control for it to accept these elements. Though when I convert them to vectors i.e c(4.5) and c('Nairobi') the control seems to work. Should I pass these items as vectors?

2020-10-12 09:38 UTC, Wycklife commented
![image](https://user-images.githubusercontent.com/33898404/95731123-c7f87800-0c87-11eb-828f-c5b257a3a4a3.png)

This is the new layout of the keyboard and the dialog.

2020-10-12 09:46 UTC, rdstern commented
@Wycklife this layout looks neat and I look forward to testing it.
On your solution for the Try with a single element, I see it works on the command, perhaps because the number, or string is put into an object and then used.  
In a similar situation (File > New Data Frame) @Patowhiz was able to improve the Try facility, which had similar limitations.  Perhaps he can suggest a simple method?

2020-10-14 15:42 UTC, Patowhiz commented
> @Wycklife this layout looks neat and I look forward to testing it.
> On your solution for the Try with a single element, I see it works on the command, perhaps because the number, or string is put into an object and then used.
> In a similar situation (File > New Data Frame) @Patowhiz was able to improve the Try facility, which had similar limitations. Perhaps he can suggest a simple method?

@rdstern we discussed with @Wycklife in regards to this. I have looked into the problem and explained it in issue #6018. This dialog can have the original expressions or the modified expressions(if need be). Then we can solve the actual problem in a separate PR.

2020-10-19 07:10 UTC, Wycklife commented
@rdstern @dannyparsons Now that there is a new issue on the Try control, Should this now be merged? If it's okay?

2020-10-21 20:49 UTC, rdstern commented
@Wycklife this looks good.  I have some trivial corrections to 3 of the examples.  If they could be done tomorrow, then we might be able to get it included in the release.
I have numbered the examples 1 to 10, in their order.
6. begins factor.  Change the final 2 to 3 and add another NA to the end of the tooltip.
8. Begins c( .  Add ,15 at the end.  In the tooltip add 0 at the start and another 15 at the end  - so 0,1,3,5,10,11,12,15,15
10. Change 1940 to 1937.  The tooltip stays as before.

2020-10-22 06:43 UTC, Wycklife commented
@rdstern I have fixed the changes above.

2020-10-22 07:19 UTC, rdstern submitted a review, later dismissed
I am approving, because it all now works.  There are 2 tiny cosmetic points that could be included if done immediately, plus one slightly larger point  that could be done, or left as an issue.
1) In the 8th tooltip there isn't yet a comma before the 10.
2) In the key [ , ] the focus is after the comma and should be before.
Now the bigger point and this has been an error, so far on my part.  We are getting close to being able to suggest using R-Instat to support teaching of R.  Now there is a tidyverse style guide which we should follow.  There are 2 points to note here, the first is in the examples.
After a comma it is good to have a space - as in writing English.
Usually have a space round an operator.
So, in the 3rd example change (2,3,4)*1.5E02 to (2, 3, 4) * 1.5E02.  
Do the same comma rule for the other examples.

Also ready for second approval by @lloyddewit 
I will check any of the minor cosmetic changes above if they are done in time.

2020-10-22 09:48 UTC, rdstern requested changes
@Wycklife this is good.  Just a space after the first argument in the last one, i.e. before the as.Date.

And a new one that I hope is trivial too.  We save as Enter1, etc.  The good practice guide says keep to lower case, so change to enter1.
Thanks

2020-10-22 10:46 UTC, Wycklife commented
@rdstern Done.

2020-10-22 10:56 UTC, rdstern approved these changes
Great.  Ready for @lloyddewit

2020-10-22 12:32 UTC, dannyparsons requested changes
Please check for consistency in the R code (following the tidyverse style guide https://style.tidyverse.org/syntax.html). I commented on some below but please check throughout.
Also, please check on grammar and consistency in tooltips. I think tooltips should be sentences so start with a capital letter and end with a full stop.

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        lstView.Items.Item(1).ToolTipText = "a single text repeated for the data frame" 'todo. Sensible tooltip here.
```suggestion
        lstView.Items.Item(1).ToolTipText = "A single text repeated for the data frame" 'todo. Sensible tooltip here.

```

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        lstView.Items.Item(2).ToolTipText = "gives 300, 450, 600 then repeated for the data frame" 'todo. Sensible tooltip here
```suggestion
        lstView.Items.Item(2).ToolTipText = "Gives 300, 450, 600 then repeated for the data frame" 'todo. Sensible tooltip here

```

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        lstView.Items.Item(3).ToolTipText = "values 1 to 3 with the variable made into a factor" 'todo. Sensible tooltip here
```suggestion
        lstView.Items.Item(3).ToolTipText = "Values 1 to 3 with the variable made into a factor" 'todo. Sensible tooltip here

```

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +            ucrReceiverForEnterCalculation.AddToReceiverAtCursorPosition("seq(from= ,to= ,by= ,length =  )", 22)
Please follow the [tidyverse style guide](https://style.tidyverse.org/syntax.html), specifically 2.2.1 on commas: always put a space after a comma, and 2.2.4: always put spaces around `=`

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({" forcats::as_factor(rep(LETTERS[4:1], c(4, 3, 1, 1)))"}))
```suggestion
        lstView.Items.Add(New ListViewItem({"forcats::as_factor(rep(LETTERS[4:1], c(4, 3, 1, 1)))"}))
```
extra space was included at the start

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({"factor(c(1, 2, 3))"}))
Shouldn't this be `forcats::as_factor` if we're now using this?

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        ucrReceiverForEnterCalculation.AddToReceiverAtCursorPosition(" rnorm( )", 2)
```suggestion
        ucrReceiverForEnterCalculation.AddToReceiverAtCursorPosition("rnorm( )", 2)
```
extra space

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        ucrReceiverForEnterCalculation.AddToReceiverAtCursorPosition(" runif( )", 2)
```suggestion
        ucrReceiverForEnterCalculation.AddToReceiverAtCursorPosition("runif( )", 2)
```
extra space

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        ttEnter.SetToolTip(cmdPi, "The number pi = 3.14.")
`Pi` is not equal to 3.14! At least use `3.14...` to make it accurate.

2020-10-22 12:32 UTC, dannyparsons commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({"'Nairobi'"}))
Here you've got single quotes whereas in other places you have double quotes. Is that deliberate?

2020-10-22 13:18 UTC, Wycklife commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({"'Nairobi'"}))
@dannyparsons This what Roger suggested. Do you want it changed?

2020-10-22 13:19 UTC, Wycklife commented
@dannyparsons Could you check if your changes are properly fixed? Thank you

2020-10-22 14:15 UTC, rdstern commented
I am always confused on the use of single and double quotes.  But we should try to be consistent one way or the other!

2020-10-22 14:32 UTC, Wycklife commented
> I am always confused on the use of single and double quotes. But we should try to be consistent one way or the other!

Meaning I should I should change items with single quotes to have double quotes?

2020-10-22 14:36 UTC, rdstern commented
Meaning that on items of programming and consistency, if @dannyparsons and I differ, then usually follow danny!  Does that make it clear?  If so, then let me know the decision!

2020-10-23 10:36 UTC, lloyddewit commented
@Wycklife There are a number of open comments above. Please could you respond to each comment stating which action you took. If you changed code in response to the comment then please state what you changed (preferably with line number). Currently I have to do detective work to link the updated code to the comment to the supdated code. This is time-consuming and error-prone. 
If you do the above then I can do the final review, thanks

2020-10-23 11:54 UTC, Wycklife commented on instat/dlgEnter.vb
> +        lstView.Items.Item(2).ToolTipText = "gives 300, 450, 600 then repeated for the data frame" 'todo. Sensible tooltip here
@dannyparsons This has been fixed

2020-10-23 11:56 UTC, Wycklife commented on instat/dlgEnter.vb
> +            ucrReceiverForEnterCalculation.AddToReceiverAtCursorPosition("seq(from= ,to= ,by= ,length =  )", 22)
@dannyparsons I have done the spacing

2020-10-23 11:57 UTC, Wycklife commented on instat/dlgEnter.vb
> +        ucrReceiverForEnterCalculation.AddToReceiverAtCursorPosition(" rnorm( )", 2)
@dannyparsons Spaces removed.

2020-10-23 11:57 UTC, Wycklife commented on instat/dlgEnter.vb
> +        ttEnter.SetToolTip(cmdPi, "The number pi = 3.14.")
@dannyparsons I have changed this.

2020-10-23 11:59 UTC, Wycklife commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({"'Nairobi'"}))
@dannyparsons I have added double quotes.

2020-10-23 11:59 UTC, Wycklife commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({" forcats::as_factor(rep(LETTERS[4:1], c(4, 3, 1, 1)))"}))
@dannyparsons This extra space has been removed

2020-10-23 12:00 UTC, Wycklife commented on instat/dlgEnter.vb
> +        ucrReceiverForEnterCalculation.AddToReceiverAtCursorPosition(" runif( )", 2)
@dannyparsons The extra space has been removed.

2020-10-23 12:01 UTC, Wycklife commented on instat/dlgEnter.vb
> +        lstView.Items.Item(3).ToolTipText = "values 1 to 3 with the variable made into a factor" 'todo. Sensible tooltip here
@dannyparsons I have resolved this

2020-10-23 12:23 UTC, Wycklife commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({"factor(c(1, 2, 3))"}))
@rdstern Should I add forcats::as_factor instead of factor for consistency?

2020-10-27 05:56 UTC, Wycklife commented
@lloyddewit I have resolved the comments, please could it now be merged?

2020-10-27 08:19 UTC, lloyddewit commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({"factor(c(1, 2, 3))"}))
@Wycklife I don't see a response from @rdstern. Was this comment resolved in an external conversation (if so, please could you document here)? Or is this comment still open?

2020-10-27 08:22 UTC, lloyddewit commented
@Wycklife Thank you for clarifying the resolved comments. There is still one comment above that may still be unresolved, please can you clarify? thanks

2020-10-28 08:00 UTC, Wycklife commented on instat/dlgEnter.vb
> +        lstView.Items.Add(New ListViewItem({"factor(c(1, 2, 3))"}))
@lloyddewit I have discussed this with Roger and he has agreed that the change should be made. I have done that and pushed the minor change.

2020-10-28 08:03 UTC, Wycklife commented
@lloyddewit I have made that small change. The change is about replacing factor() with forcats::as_factor() in line 253. Thank you. The comments have been resolved.

2020-10-28 08:15 UTC, lloyddewit approved these changes

2020-10-28 08:44 UTC, lloyddewit commented
@Wycklife Thanks for the final change, looks good.

@rdstern there are 2 changes since your last approval (replaced single quotes with double quotes and replaced `factor()` with `forcats::as_factor()`. Please could you approve? thanks

2020-10-28 10:50 UTC, rdstern approved these changes
Good.  Approved.

2020-10-30 12:00 UTC, merged