Reordering of Multiple Items in ucrReorder Control
africanmathsinitiative/R-Instat pull request #5989
Opened 2020-09-18 21:00 UTC by Patowhiz

Fixes #3589

2020-09-22 07:38 UTC, rdstern approved these changes
Great, this now seems to work.  Over to @lloyddewit to be able to merge

2020-09-22 09:23 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2020-09-22 11:35 UTC, Ivanluv commented
@lloyddewit  this looks okay

2020-09-23 09:20 UTC, rdstern submitted a review, later dismissed
I have checked again, because I needed to use this facility.  It works fine still from my point of view.  Back to @lloyddewit

2020-09-23 09:25 UTC, lloyddewit requested changes
@Patowhiz this looks clear and elegant, I especially appreciated the excellent commenting. 
I just had a couple of observations

2020-09-23 09:25 UTC, lloyddewit commented on instat/ucrReorder.vb
> +                For Each kvpItem As KeyValuePair(Of Integer, ListViewItem) In dctSelectedItems
Move the `For` and `Next` lines outside the `Select` statement (makes code 6 lines shorter)?

2020-09-23 09:25 UTC, lloyddewit commented on instat/ucrReorder.vb
> +                    iStartindex = iStartindex + 1
is this line needed?

2020-09-23 09:37 UTC, Patowhiz commented on instat/ucrReorder.vb
> +                For Each kvpItem As KeyValuePair(Of Integer, ListViewItem) In dctSelectedItems
@lloyddewit aha. That was the catch 22. Make the lines shorter or make the code faster. Putting the Select statement outside means the same checking will be done several times in the same loop. Putting the for loop inside the select statement means the check happens once.

They will both produce the same output and they both look simpler and direct to me. 

So the questions I had were; Shorter lines? or Faster code?
What do you recommend, I'm happy with either, since in this case, optimised code may never have any noticeable effect, and the lines shortened are just 6.

2020-09-23 09:39 UTC, Patowhiz commented on instat/ucrReorder.vb
> +                    iStartindex = iStartindex + 1
Thanks. This is not needed

2020-09-23 09:51 UTC, lloyddewit commented on instat/ucrReorder.vb
> +                For Each kvpItem As KeyValuePair(Of Integer, ListViewItem) In dctSelectedItems
You probably know my view ;)
In this case (and in the vast majority of cases) readability is more important than performance. If we are reordering millions of lines then having the extra 6 duplicate lines may have a measurable performance improvement but I'm not convinced.
Accept or reject as you wish :)

2020-09-23 12:31 UTC, Patowhiz commented on instat/ucrReorder.vb
> +    ''' opted to use string parameter because the sub is used inside this class only and by 4 events
Agreed.

2020-09-23 12:34 UTC, Patowhiz commented on instat/ucrReorder.vb
> +                For Each kvpItem As KeyValuePair(Of Integer, ListViewItem) In dctSelectedItems
Shortened the lines

2020-09-23 12:47 UTC, Patowhiz commented
Made the requested changes

2020-09-24 09:17 UTC, lloyddewit approved these changes

2020-09-24 09:17 UTC, lloyddewit commented
@rdstern please could you re-approve? thanks

2020-10-01 07:18 UTC, rdstern approved these changes

2020-10-04 08:43 UTC, merged