One variable dialogue improvements
africanmathsinitiative/R-Instat pull request #6004
Opened 2020-10-01 08:36 UTC by Ivanluv

@africanmathsinitiative/developers  This is from PR #5861

2020-10-04 08:35 UTC, lloyddewit commented
@Ivanluv Thank you for taking over PR #5861. I understand that:
- This PR completely replaces PR #5861 and includes all of its commits. Therefore when this PR is merged, PR #5861will also merge automatically.
- Your work on this PR is ongoing and is not yet ready for review


Please let me know if I misunderstood anything, thanks

2020-10-05 07:10 UTC, Ivanluv commented
@lloyddewit  both  points are correct

2020-10-30 06:15 UTC, Ivanluv commented
@rdstern  could you look at this again

2020-11-04 18:05 UTC, rdstern requested changes
That's looking good with the extra control.
a) It doesn't "remember" the level used previously.
b)When it isn't a factor variable the control isn't there.    Could the selector have anything except character.  Then when it is factor you can opt to make it numeric.  Could you also, when it is not a factor, and you are using binomial or proportion, it would have the equivalent control "Convert to Factor", and it would then do an as.factor.  
c) The selector does not allow character variables

2020-11-17 18:01 UTC, rdstern requested changes
This is now getting there.  There are 2 packages to add, namely DEscTools and MKinfer.
The other minor point is on the Z test, where Ok should be disabled if the sd field is empty.
Then I need @dannyparsons to help me on how to cope with variables that are not numeric.  I wonder what can (should) be coped with.

2021-01-05 11:53 UTC, rdstern approved these changes
@Ivanluv , please check that the new packages are included in the list to be added.

2021-01-05 12:12 UTC, Ivanluv commented
@rdstern  I have added the package to that list

2021-01-07 11:57 UTC, lloyddewit requested changes
@Ivanluv Looks good! I just have some relatively trivial comments

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +    Private clsGetFactorLevel As New RFunction
Cahange all names to end in `Function` (e.g. rename `clsRConvertVector` to `clsRConvertVectorFunction`).
Also, some names need the capitalisation fixed (e.g. rename `clsRfitdist` to `clsRFitDistFunction`).

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +                ucrBase.OKEnabled(False)
```suggestion
            ucrBase.OKEnabled(False)
```

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +        End If
add `else` that raises developer error?

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +                        tttests.SetToolTip(ucrInputComboTests.cboInput, "Sen 's slope for linear rate of change")
```suggestion
                        tttests.SetToolTip(ucrInputComboTests.cboInput, "Sen's slope for linear rate of change")
```

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +
```suggestion
```

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +                Select Case ucrInputComboTests.GetText()
Should all of these cases have tool tips? or just some?

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +        End If
add `else` with developer error?

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +
```suggestion
```

2021-01-07 11:57 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +            If Not ucrReceiverVariable.IsEmpty AndAlso rdoTest.Checked AndAlso (ucrReceiverVariable.strCurrDataType.ToLower = "logical" Or ucrReceiverVariable.strCurrDataType.ToLower = "factor") AndA
Convert this condition to multiple lines so that no single line > col 100

2021-01-08 07:29 UTC, Ivanluv commented on instat/dlgOneVarFitModel.vb
> +    Private clsGetFactorLevel As New RFunction
Done

2021-01-08 07:29 UTC, Ivanluv commented on instat/dlgOneVarFitModel.vb
> +        End If
How can I do that?

2021-01-08 07:30 UTC, Ivanluv commented on instat/dlgOneVarFitModel.vb
> +                Select Case ucrInputComboTests.GetText()
Some

2021-01-08 07:34 UTC, Ivanluv commented on instat/dlgOneVarFitModel.vb
> +        End If
Any suggestion on how to do that

2021-01-08 09:14 UTC, closed without merging

2021-01-08 11:24 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +        End If
I moved this comment to PR #6150

2021-01-08 11:25 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +                Select Case ucrInputComboTests.GetText()
ok

2021-01-08 11:26 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +        End If
I added this comment to PR #6150