Seasonality Plots dialog (branched from HawardKetoyoMsatsi:seasonalityplots)
africanmathsinitiative/R-Instat pull request #6006
Opened 2020-10-06 16:24 UTC by dannyparsons

Branched from #5984 

- Changed estimates summary options after discussion with @rdstern. Estimates' summary now fixed to the same as Reference Values' but thresholds can be different.
- Set mean as the default summary
- Fixed R code setting for controls where this was not set up
- Corrected variables from receivers to be as strings not RFunctions

@africanmathsinitiative/developers this is ready for review

2020-10-06 16:43 UTC, dannyparsons reviewed
@HawardKetoyoMsatsi @shadrackkibet I've added comments here to explain the changes I've made from #5984. You can see the full comparison here https://github.com/HawardKetoyoMsatsi/R-Instat/compare/seasonalityplots...dannyparsons:HawardKetoyoMsatsi-seasonalityplots

The dialog was producing the correct output with all different options, but some of the things mentioned below are ways I corrected the R code that was being produced, or corrected the VB code to follow our normal conventions, particularly ensuring all controls are reading their value from the R code.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        ucrReceiverReference.bWithQuotes = False
This was set as `.SetParameterIsRFunction()` for all receivers whereas it should be strings without quotes. For `dplyr` and `ggplot2` functions we only need the variable names, not to extract the columns. Before, there was lots of extra lines getting the columns from the data frames before doing the plot which were unnecessary.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        ucrReceiverReference.strSelectorHeading = "Numerics"
Data types were not set for any receivers.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        ucrInputEstimatesSummary.IsReadOnly = True
Changed the functionality of this after discussing with Roger. This now displays the same summary as for Reference Values and can't be changed.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +    Private clsFormulaRCode As RCodeStructure
To be able to set the R code for `ucrInputSmoothing` I created this "dummy" `RCodeStructure` which is set when the smoothing option is changed and allows the R code to be set. See below for where it's used.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        If ucrReceiverStation.IsEmpty AndAlso clsFacetWrapTildeOperator.clsParameters.Count = 0 Then
This is needed in case we later add the Plot Options subdialog and allow facets to be added from there also.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +    End Sub
I separated out these different parts of the code so that they are only run when the controls they depend on change.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +                clsMutateFunction.AddParameter("estimates", ucrReceiverEstimates.GetVariableNames(False), iPosition:=1)
For all options, these need to be `.GetVariableNames(False)` so that we just get the names of the column. `False` means do not add quotes to the column name.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +    Private Sub ReferenceSummarySetRCode(bReset As Boolean)
It's not possible to automatically set the R code for `ucrInputReferenceSummary` because it depends on multiple parts of the code, however, we still need the value to be read from the code so that's what this function does.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        clsFacetWrapTildeOperator.bForceIncludeOperation = True
Instead of adding a blank parameter use `.bForceIncludeOperation = True` to force the operator to appear even when there is only one parameter in the operator.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        clsMeanFunction.AddParameter("x", "value", iPosition:=0)
In `mean`, `sd` functions etc. you had a different parameter name and had `bIncludeArgumentName:=False`. These should be used just like any other function with correct parameter names.

2020-10-06 16:43 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        SetRCodeForControls(bReset)
This is run every time the dialog opens, not just on reset.

2020-10-07 07:26 UTC, lloyddewit commented
@rdstern Please could you test? thanks

@dannyparsons I understand that:

- this PR is ready for test
- this PR supercedes PR  #5984, no more work is expected on PR #5984 
- PR #5984 will merge automatically when this PR merges

If I misundersood anything then please let me know, thanks

2020-10-07 09:53 UTC, rdstern requested changes
I was going to  approve, because it could usefully be merged now.  But I have a variety of suggestions, either for now, or for later, once it has been merged.  No I would like point a) to be considered first.
a) The data are labelled as reference and estimated.  And these are given in the legend, in the opposite order to the dialogue.  But the main change is to give the actual name of the variable, rather than the standard name.

From here, these could be suggestions for a new issue, after merging.
b) Could the Missing checkbox be moved down, so it is at the bottom, rather than the top of the controls on the left?  That is more consistent with the missing option on the summary dialogue.  It also leaves a space for...
c) There are a lot more minor changes that may become useful, if it is practical to add the Plot Options, which should go just below the data selector.  Perhaps it could go there now, even though disabled?  (Among these are position of the legend, having dates in the year for the x-axis.
d) Could a default graph caption give details of what is being done in this dialogue?

2020-10-07 10:03 UTC, dannyparsons commented
@lloyddewit yes that's right exactly

2020-10-08 08:54 UTC, dannyparsons commented
@rdstern a) and b) have now been addressed. In particular, I found the `names_ptypes` parameter of `pivot_longer` which can define the factor column to be produced from stacking to ensure the labels are always in the same order (instead of being in alphabetical order)

I agree with making c) and d) a separate issue for further improvement after this.

2020-10-11 09:59 UTC, lloyddewit requested changes
@dannyparsons just some small comments

2020-10-11 09:59 UTC, lloyddewit commented on instat/dlgSeasonalPlot.vb
> +    ''' Sets the R Code for ucrInputReferenceSummary. This is done manually by this Sub instead of through conditions because of the complex checks on multiple functions required.
```suggestion
    ''' Sets the R Code for ucrInputReferenceSummary. This is done manually by this sub instead of 
    ''' through conditions because of the complex checks on multiple functions required.
```

2020-10-11 09:59 UTC, lloyddewit commented on instat/dlgSeasonalPlot.vb
> +    ''' <summary> Dummy ROperator set to either clsRefGreaterOperator or clsRefLessOperator depending on summary option. This is used in SetRCode for ucrInputReferenceSummary. </summary>
```suggestion
    ''' <summary> 
    ''' Dummy ROperator set to either clsRefGreaterOperator or clsRefLessOperator depending on 
    ''' summary option. This is used in SetRCode for ucrInputReferenceSummary. 
    ''' </summary>
```

2020-10-11 09:59 UTC, lloyddewit commented on instat/dlgSeasonalPlot.vb
> +        strEstimatesName = ucrReceiverEstimates.GetVariableNames(False)
```suggestion
        Dim strReferenceName As String = ucrReceiverReference.GetVariableNames(False)
        Dim strEstimatesName As String = ucrReceiverEstimates.GetVariableNames(False)
```

2020-10-11 09:59 UTC, lloyddewit commented on instat/dlgSeasonalPlot.vb
> +        End If
```suggestion
        ' By default estimates has the same threshold as reference values, unless the user has 
        ' already typed in ucrInputEstimatesThreshold to make them different.
        If Not ucrInputEstimatesThreshold.UserTyped Then
            ucrInputEstimatesThreshold.SetName(ucrInputReferenceThreshold.GetText())
        End If
```

2020-10-11 09:59 UTC, lloyddewit commented on instat/dlgSeasonalPlot.vb
> +        ' The check for clsFacetWrapTildeOperator.clsParameters.Count = 0 ensures that facets added on a subdialog are not removed when ucrReceiverStation is empty.
```suggestion
        ' Facets are handled manually since they could also be managed on a sub dialog.
        ' The check for clsFacetWrapTildeOperator.clsParameters.Count = 0 ensures that facets added 
        ' on a subdialog are not removed when ucrReceiverStation is empty.
```

2020-10-13 08:55 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        strEstimatesName = ucrReceiverEstimates.GetVariableNames(False)
We have been using a convention of defining variables separately to assigning them a value. I am not sure if this is the correct convention to use but that's why I did it like this. I will remove `= ""` as these are unnecessary.
I can't see any mention of what the convention should be for this in the VB coding conventions document. I did find this document https://en.wikibooks.org/wiki/Visual_Basic/Coding_Standards which doesn't mention this convention but in the "Function Return Values" section the example code separates defining the variable from assigning a value.

2020-10-13 08:59 UTC, dannyparsons commented
@lloyddewit thanks for the review and feedback. I've accepted all those changes apart from one where I've commented. Let me know if you think that's ok.

2020-10-13 13:23 UTC, lloyddewit commented on instat/dlgSeasonalPlot.vb
> +        strEstimatesName = ucrReceiverEstimates.GetVariableNames(False)
@dannyparsons If that is the normal convention in R-Instat then that's OK for me. I personally find 2 lines more readable here than 4 lines but that's subjective. Consistency is also important.
Thank you for the wikibooks link, I wasn't aware of this. There's also the Microsoft VB coding guidelines (https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/coding-conventions). These aren't so extensive as the wikibooks link. They briefly mention declarations. They don't have the exact example above but show the following as good practice. The Visual Studio 'quick actions' (the lightbulb symbol preceeding a code line) also recommends combining declaration and initailisation. So it's subjective!

![image](https://user-images.githubusercontent.com/57253949/95866198-e897ff00-0d67-11eb-8702-4117f6497d12.png)

2020-10-13 13:23 UTC, lloyddewit approved these changes

2020-10-13 14:21 UTC, dannyparsons commented on instat/dlgSeasonalPlot.vb
> +        strEstimatesName = ucrReceiverEstimates.GetVariableNames(False)
Thanks. Yes I think either would be acceptable as long as we're consistent. Whatever we decide we should be documenting our coding conventions or stating which ones we're following. I think developers have mostly picked them up from the existing code but we should be explicit about it too. We probably want a separate issue on documenting coding conventions.

2020-10-15 17:45 UTC, dannyparsons commented
I can replicate this problem is `x` is a factor or if d.f. is < 3. When `x` is a factor none of the curves work. Do you get it in any other case? If it was very important for this to work with `x` as a factor we could probably do this or we restrict `x` to be numeric.
I think we should also restrict d.f. to be >= 3 for splines. It doesn't produce anything otherwise and can't see why < 3 would be especially needed.

2020-10-15 18:05 UTC, rdstern commented
hbere is the problem with doy1 numeric and d.f. = 6
![image](https://user-images.githubusercontent.com/11226469/96168766-28521880-0f19-11eb-8145-e6078e925e51.png)

Here are the results:
![image](https://user-images.githubusercontent.com/11226469/96168889-50da1280-0f19-11eb-8583-9c9d3301d0d6.png)

2020-10-16 08:51 UTC, dannyparsons commented
It's not really designed for the case of data summarised to the doy level but it should work still. I tried it with Dodoma and it worked producing the same R code that you showed. Could you send me the data you're using privately so that I can test?

2020-10-16 11:21 UTC, rdstern approved these changes
Found the last problem was because a new package needed to be installed.

I note that at some stage a logit transform may be needed.

2020-10-16 12:45 UTC, dannyparsons commented
This is now ready. We agreed on not needing any further changes at this point.

2020-10-18 07:58 UTC, merged