Documenting ucrSaveGraph
africanmathsinitiative/R-Instat pull request #6009
Opened 2020-10-07 09:55 UTC by N-thony

@lloyddewit I wrote the documentation for ucrSaveGraph. Please could you peer review this PR? Thanks.

2020-10-18 09:33 UTC, lloyddewit requested changes
@N-thony This looks great, I just had a couple of small suggestions

2020-10-18 09:33 UTC, lloyddewit commented on instat/ucrSaveGraph.vb
> +    ''' <summary> Save the graph when the check box save graph is checked. </summary>
```suggestion
   ''' <summary> Returns the state of the save graph check box. </summary>
```

2020-10-19 08:19 UTC, N-thony commented
@lloyddewit  I solved the issues you raised on 18 October. Please could you confirm that your comments are resolved? thanks.

2020-10-19 10:28 UTC, lloyddewit approved these changes

2020-10-19 10:28 UTC, lloyddewit commented
@rdstern please could you approve (functionality not affected, just changes to code comments)? thanks

2020-10-19 10:33 UTC, rdstern approved these changes

2020-10-20 09:11 UTC, merged