Time series plot dialog: added names_ptypes parameter to ensure labels are in correct order
africanmathsinitiative/R-Instat pull request #6010
Opened 2020-10-08 10:00 UTC by dannyparsons

@africanmathsinitiative/developers this is ready for review.

One minor change: `names_ptypes` added to `pivot_longer` to ensure that the reference and estimates columns always appear in the correct order in the labels of the graph.

2020-10-11 10:00 UTC, lloyddewit commented
@shadrackkibet Please could you review? thanks

2020-10-18 09:23 UTC, shadrackkibet requested changes

2020-10-18 09:23 UTC, shadrackkibet commented on instat/dlgTimeSeriesPlot.vb
> +    Private clsPivotFactorLevelsCFunction As New RFunction
Should this be `Private clsPivotFactorLevelsCFunction As RFunction` ?

2020-10-18 17:22 UTC, dannyparsons commented on instat/dlgTimeSeriesPlot.vb
> +    Private clsPivotFactorLevelsCFunction As New RFunction
Thanks, done.

2020-10-19 05:43 UTC, shadrackkibet commented
Looks good, over to @lloyddewit and @rdstern

2020-10-19 07:43 UTC, lloyddewit approved these changes

2020-10-19 16:37 UTC, rdstern approved these changes
Great - another one

2020-10-20 09:00 UTC, merged