Separating missing value options on summary dialogs
africanmathsinitiative/R-Instat pull request #6014
Opened 2020-10-12 19:20 UTC by shadrackkibet

Fixes #6012. This is still a work in progress.

2020-10-19 14:40 UTC, shadrackkibet commented
@africanmathsinitiative/developers this PR fixes two issues as referenced above. This is ready for review.

2020-10-20 08:59 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2020-10-20 16:47 UTC, shadrackkibet commented
@rdstern, please test. I would like to get this done as soon as possible.

2020-10-20 22:51 UTC, rdstern submitted a review, later dismissed
@shadrackkibet this is great and it all seems fine.  This was @dannyparsons suggestion and is one that was blindingly obvious - in hindsight of course.

I am happy to approve so these can be merged.  However there are (at least) 2 more dialogues.  They do need to be changed soon, but this could be a separate issue if you prefer.

They are Describe > One Variable > Summarise and also 2 Variable > Summarise.  Both these dialogues call the same sub-dialogue and the missing options are now absent.  I assume they are simple to add here too.  I have never used the missing options in these dialogues, so it can be left to later if needed.

2020-10-21 07:07 UTC, shadrackkibet commented
> They are Describe > One Variable > Summarise and also 2 Variable > Summarise. Both these dialogues call the same sub-dialogue and the missing options are now absent. I assume they are simple to add here too. I have never used the missing options in these dialogues, so it can be left to later if needed.

Let's have it as a separate issue. Thanks

2020-10-21 09:17 UTC, dannyparsons requested changes
Looks good, a couple of changes needed.

2020-10-21 09:17 UTC, dannyparsons commented on instat/sdgMissingOptions.vb
> +        ucrNudNumber.SetParameter(New RParameter("na_max_n", 11))
This currently has a max of 100. Need to set min/max to fix this.

2020-10-21 09:17 UTC, dannyparsons commented on instat/dlgColumnStats.vb
> +        If Not ucrChkOmitMissing.Checked AndAlso clsDefaultFunction.ContainsParameter("na_type") Then
```suggestion
        If Not ucrChkOmitMissing.Checked Then
```
You don't want that second condition because it would mean that the parameter could get added if the checkbox was unchecked but the parameter was not included at that point i.e. it could go into `Else` when you don't want it to. There's no issue with trying to remove a parameter that doesn't exist anyway too.

2020-10-21 09:17 UTC, dannyparsons commented on instat/dlgClimaticSummary.vb
> +        If Not ucrChkOmitMissing.Checked AndAlso clsDefaultFunction.ContainsParameter("na_type") Then
```suggestion
        If Not ucrChkOmitMissing.Checked Then
```
Same here as explained for the other dialog.

2020-10-21 09:24 UTC, Ivanluv commented
@lloyddewit  the vb code looks okay by me

2020-10-21 09:41 UTC, shadrackkibet commented on instat/sdgMissingOptions.vb
> +        ucrNudNumber.SetParameter(New RParameter("na_max_n", 11))
Done!

2020-10-21 09:50 UTC, dannyparsons approved these changes

2020-10-21 10:07 UTC, lloyddewit approved these changes

2020-10-21 10:14 UTC, lloyddewit commented
@rdstern please could you retest? The only functional change since your last approval was changing the max possible value of 'na_max_n' from 100 to maxint.

2020-10-21 12:19 UTC, dannyparsons commented
I've tested that point and it's working so happy for it to be merged.

2020-10-21 15:14 UTC, merged