Data View Window Startup helpful Information
africanmathsinitiative/R-Instat pull request #6019
Opened 2020-10-15 10:54 UTC by Patowhiz

Fixes #5632.
@africanmathsinitiative/developers this is ready for review.

2020-10-15 15:24 UTC, rdstern commented
This looks really good.  
a) In the top section add the ... after New Data Frame
b) Make the space much wider to show the filenames as much as possible in the middle section
c) The More doesn't work.  I suspect there are only 5 files.  If that takes a long time to implement, then delete the option for now.
d) In the Help the first item could be the `Introduction`, so it goes to the top of the Help, i.e. as in Help > Introduction.  The second item could be `R-packages in R-Instat`.  This links to Help > R Packages and Commands.  The third item could be R-Instat website and link to `http://r-instat.org/ `(Why isn't it https?).  The 4th item could be `Instructional videos (to come)` and is not live.  The fifth could then be `(more to come)` and is also not live.

2020-10-16 19:41 UTC, rdstern requested changes
I showed it to Rachel who was very happy with the new screen.
a) It still needs to be much wider for the Recent file names.
b) The More as you showed it with the other software, then opened another scrollable window.  Yours just adds the file names below.  I liked the idea of the other window, but (for now) I suggest you delete the More, unless that can be done quickly.  Or keep it, but disable.

2020-10-19 07:08 UTC, Patowhiz commented
@rdstern I've made the changes requested in your above comment. File names and file paths are now fully viewable.
Will the videos be online? Do we have page template already online, I could link to it. I have the videos link disabled for now.

![Uploading full_paths.PNG…]()

@africanmathsinitiative/developers this is now ready for review.
@lloyddewit this PR has changes to frmMain.vb.

2020-10-19 07:37 UTC, lloyddewit commented
@Ivanluv please could you peer review? thanks

2020-10-19 07:44 UTC, rdstern submitted a review, later dismissed
@Patowhiz I am now very happy with this improvement to the start of R-Instat.  I note that it was not what Danny and I suggested, but, after discussion and suggestions from Patrick,  it is considerably better!
Last time I asked for changes in the More button and really like what there is now.  I had not realised that there would be scroll bars.

2020-10-21 07:39 UTC, Ivanluv commented
@lloyddewit  this looks okay from my end

2020-10-21 09:54 UTC, lloyddewit requested changes
@Patowhiz  This looks very good. I really liked your commenting approach. I just have a couple of small comments. Please could you check them asap so we can merge this today and include in the new release?

2020-10-21 12:29 UTC, Patowhiz commented on instat/clsRecentFiles.vb
> +    Private ucrDataViewWindow As ucrDataView
@lloyddewit A property will expose this control to other classes that may use this this class in future. I'm not sure if that is desired?When I went through this class, it seemed like a utility class to me. I'm happy to make this a property if you strongly feel there is a merit to this.

2020-10-21 15:13 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +    Private ucrDataViewWindow As ucrDataView
@Patowhiz Thank you for the explanation. I'm happy to leave the code as it is. I was just curious if you had a special reason for doing it this way.
I understand your concerns about this class needing to know about the user control. I think having a private data member with a public `SetDataViewWindow` function is similar to a public property in terms of write access, it's mainly the synatx that differs.

2020-10-21 15:13 UTC, lloyddewit approved these changes

2020-10-21 15:14 UTC, lloyddewit commented
@rdstern Please could you re-approve (no functional changes since your last approval)? thanks

2020-10-21 16:04 UTC, rdstern approved these changes

2020-10-22 08:43 UTC, merged

2020-10-22 08:56 UTC, dannyparsons commented on instat/ucrDataView.Designer.vb
> +        Me.linkHelpMoreToCome.Text = "More to come"
Can we hide this or remove this? I don't think this is useful if it doesn't do anything.

2020-10-22 08:58 UTC, dannyparsons commented on instat/ucrDataView.Designer.vb
> +        Me.linkHelpInstructionVideos.Text = "Instructional videos"
Also hide this until there is a link

2020-10-22 08:58 UTC, dannyparsons commented on instat/ucrDataView.Designer.vb
> +        Me.linkHelpRpackages.Text = "R-packages in R-Instat"
R packages instead of R-packages

2020-10-22 09:55 UTC, Patowhiz commented on instat/ucrDataView.Designer.vb
> +        Me.linkHelpRpackages.Text = "R-packages in R-Instat"
Done this in PR #6036

2020-10-22 09:56 UTC, Patowhiz commented on instat/ucrDataView.Designer.vb
> +        Me.linkHelpInstructionVideos.Text = "Instructional videos"
Done this in PR #6036

2020-10-22 09:59 UTC, Patowhiz commented on instat/ucrDataView.Designer.vb
> +        Me.linkHelpMoreToCome.Text = "More to come"
Done this in PR #6036

2020-10-22 10:02 UTC, Patowhiz commented
I've made the changes in #6036