Added controls and their functionality to visdat dialogue
africanmathsinitiative/R-Instat pull request #6021
Opened 2020-10-16 10:51 UTC by Wycklife

Fixes part (a to d) of #6008
@africanmathsinitiative/developers This is ready for review

2020-10-16 10:53 UTC, Wycklife commented
@rdstern Could you please check this?

2020-10-16 11:47 UTC, rdstern submitted a review, later dismissed
@from my side this is working, If @lilyclements or @dannyparsons could quickly advise on the sampling fraction, then perhaps that could be added.  Meantime I am approving and hope @lloyddewit will find the code changes to be ok.

2020-10-16 12:32 UTC, lilyclements commented
> @from my side this is working, If @lilyclements or @dannyparsons could quickly advise on the sampling fraction, then perhaps that could be added. Meantime I am approving and hope @lloyddewit will find the code changes to be ok.

I have now advised on issue #6008

2020-10-16 15:36 UTC, lilyclements commented on instat/dlgVisualizeData.vb
> +        ucrInputComboboxPalette.SetParameter(New RParameter("palette", 2))
You should have just one ucrInput for the `palette` option which is visible for both `vis_dat` and `vis_guess`. This would reduce the code/controls on the dialog and ensure that the value in the input is not "lost" when switching between radio buttons. Also currently the controls "blink" (as in, leave for a split second before coming back) when switching between radio buttons. This would fix that problem.

By using just the one `palette` control, you instead should run something in the `SetRCode` sub like:
`ucrInputComboboxPalette.AddAdditionalCodeParameterPair(clsVisGuessFunction, New RParameter("palette", 2), iAdditionalPairNo:=1)`
before running
`ucrInputComboboxPalette.SetRCode(clsVisDatFunction, bReset)`

Similarly this is true for the `ucrChkSortVariables` and `ucrNudMaximum` where these controls are only needed once each (and for the sampling fraction option, when it is set up).

2020-10-16 15:39 UTC, lilyclements commented on instat/dlgVisualizeData.vb
>      Private Sub TestOkEnabled()
This sub should be updated now that there are new controls: OK should not be enabled if the ucrNud is visible and empty (this will be true for the sampling fraction ucrNud too once it is set up).

2020-10-19 09:31 UTC, Wycklife commented on instat/dlgVisualizeData.vb
> +        ucrInputComboboxPalette.SetParameter(New RParameter("palette", 2))
@lilyclements This is possible, I link one combobox to the two radio buttons, but the problem with this is that changing the value of the parameter(items within the combo box) from one button affect the other button. See the screen shots below;
1. I have changed the value from "default" to "qual" this is fine as show below.

![image](https://user-images.githubusercontent.com/33898404/96426363-d0abf980-1205-11eb-958c-68d984092b23.png)

2. I have not change the value but went straight to visGuess button, the value still remains to be "qual" which I think should not be the case. See below. This is why I decided to have different controls for them so that what is don on on doesn't change the other one.

![image](https://user-images.githubusercontent.com/33898404/96426971-a4dd4380-1206-11eb-877a-f966768c437f.png)

2020-10-19 10:03 UTC, lilyclements commented on instat/dlgVisualizeData.vb
> +        ucrInputComboboxPalette.SetParameter(New RParameter("palette", 2))
Elsewhere in the software the options on the controls do not "reset" when switching between radio buttons along the top of the dialog (e.g. dlgBoxplot). This is in case the user sets up the dialog options, and then decides/realises they wish to use a different radio button along the top. I am not sure why this dialog should be different to other dialogs with buttons along the top?

2020-10-20 08:06 UTC, Wycklife commented
@lilyclements I have resolved your comments above. Please could you check.

2020-10-22 07:28 UTC, rdstern submitted a review, later dismissed
There is one point being worked on and should now become a separate issue.
The other changes are working and are important, so it would be great if they can be included in this release.  Over to @lloyddewit

2020-10-22 09:40 UTC, rdstern requested changes
I would really like to get this merged today.  But I have just found that the sort isn't working and @Wycklife is fixing this.  Then I'll test again

2020-10-22 09:50 UTC, lilyclements commented
@Wycklife did you still want me to review?

2020-10-22 10:08 UTC, rdstern approved these changes
@Wycklife great.  Well done

2020-10-22 10:09 UTC, rdstern approved these changes
Great @Wycklife well done
Over to @lloyddewit for the second check and hopefully to be merged.

2020-10-22 12:47 UTC, lloyddewit approved these changes
@Wycklife Looks good to me. Thanks for adding an XML header to your new function

2020-10-22 12:47 UTC, merged