Cluster
africanmathsinitiative/R-Instat pull request #6022
Opened 2020-10-16 11:34 UTC by HawardKetoyoMsatsi

Fixes #5966 

@africanmathsinitiative/developers. This is ready for review.

2020-10-18 08:15 UTC, lloyddewit commented
@shadrackkibet please could you review? thanks

2020-10-18 17:10 UTC, shadrackkibet requested changes

2020-10-18 17:10 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +            SetRcodeForControls(bReset)
This should done outside the if statement. Always run when the dialog is loaded.

2020-10-18 17:10 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +    End Sub
Always have a single space after each sub.

2020-10-18 17:10 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        ucrInputColor.SetParameter(New RParameter("cols", 12))
why is the parameter position 12?

2020-10-18 17:10 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        dctColor.Add(“Set3”, Chr(34) & "Set3" & Chr(34))
Looks like the quotes i.e `“Accent”/"Accent"` are different here. Did you copy and paste from somewhere?

2020-10-18 17:10 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        ucrNudNoOfClusters.SetMinMax(1,)
Why is the parameter position 14? and same for two parameters?

2020-10-18 17:10 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +    End Sub
space

2020-10-18 17:10 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +    Private Sub SetRcodeForControls(bReset As Boolean)
```suggestion
    Private Sub SetRCodeForControls(bReset As Boolean)
```

2020-10-18 17:10 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        End If
```suggestion
            ucrBase.OKEnabled(ucrReceiverPollutant.IsEmpty)
```

2020-10-18 17:12 UTC, shadrackkibet requested changes

2020-10-18 17:12 UTC, shadrackkibet commented on instat/frmMain.resx
> +    <value>3</value>
Any changes on `frmMain` should be done on a separate PR and merged as soon as possible!

2020-10-18 17:14 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        ucrNudNoOfClusters.SetMinMax(1,)
Is this correct? ` ucrNudNoOfClusters.SetMinMax(1,)`

2020-10-18 17:17 UTC, shadrackkibet requested changes

2020-10-18 17:17 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        clsPolarClusterFunction.AddParameter("angle", "45", iPosition:=14)
check your parameter positions.

2020-10-27 13:27 UTC, HawardKetoyoMsatsi commented
I am closing this pull request because there are conflicting frmmain resource files.

2020-10-27 15:01 UTC, closed without merging