Added the second circular plot from openair package #5966
africanmathsinitiative/R-Instat pull request #6023
Opened 2020-10-16 12:07 UTC by HawardKetoyoMsatsi

Fixes #5966 

@africanmathsinitiative/developers. This is ready for review.

2020-10-18 08:18 UTC, lloyddewit commented
@shadrackkibet Please could you review this PR also? thanks

2020-10-18 17:40 UTC, shadrackkibet requested changes

2020-10-18 17:40 UTC, shadrackkibet commented on instat/dlgPolarFrequency.vb
> +            SetRcodeForControls(bReset)
This should be done outside the if statement.

2020-10-18 17:40 UTC, shadrackkibet commented on instat/dlgPolarFrequency.vb
> +    End Sub
space

2020-10-18 17:40 UTC, shadrackkibet commented on instat/dlgPolarFrequency.vb
> +    Private Sub SetRcodeForControls(bReset As Boolean)
```suggestion
    Private Sub SetRCodeForControls(bReset As Boolean)
```

2020-10-18 17:40 UTC, shadrackkibet commented on instat/dlgPolarFrequency.vb
> +        End If
```suggestion
            ucrBase.OKEnabled(ucrReceiverPollutant.IsEmpty)
```

2020-10-18 17:40 UTC, shadrackkibet commented on instat/dlgPolarFrequency.vb
> +    'End Sub
remove?

2020-10-18 17:40 UTC, shadrackkibet commented on instat/frmMain.resx
> +  <data name="mnuStructuredProcurement.Size" type="System.Drawing.Size, System.Drawing">
Do `frmMain` changes on a separate PR.

2020-10-18 21:34 UTC, rdstern requested changes
@HawardKetoyoMsatsi this is looking good, but there are some important changes that are needed.
In particular the dialogue assumes (and uses) both a wind speed variable, called ws, and wind direction, called wd.  We may not have those names, and it is not R-Instat style to insist on that.  So there should be the (usual) single receivers for Wind Speed and Wind Direction.  Then there is your Pollutant receiver with (Optional), because it can be empty.
The code may have to rename these variables.  It may be a good time now to discuss how that is done in general, because it is similar in the wind rose/pollution dialogue.
The Type control needs to become more general and to permit any function as well as the pre-defined ones.  Look at the controls for the wind/pollution rose, and also note that a second variable can also be given.
The legend control needs a small change.  It looks as though when you untick, you may not get a legend.  I like the fact you can change the position, but don't have the checkbox unless that results in no legend at all.  I assume one is usually needed.

2020-10-21 07:27 UTC, lloyddewit commented
@HawardKetoyoMsatsi Is this ready for review/test or do you still plan further changes? thanks

Also, the title of this PR is confusingly similar to PR #6022, are they both the 'second circular plot'?

2020-10-22 06:39 UTC, HawardKetoyoMsatsi commented
It is not yet ready for review there are a few fixes pending

2020-10-22 06:39 UTC, HawardKetoyoMsatsi commented
It is not yet ready for review, there are a few fixes pending.

2020-10-27 13:28 UTC, HawardKetoyoMsatsi commented
I am closing this pull request because there are conflicting frmmain resource files.

2020-10-27 14:59 UTC, closed without merging