Tidy climatic data dialog improvements
africanmathsinitiative/R-Instat pull request #6032
Opened 2020-10-20 19:12 UTC by dannyparsons

fixes #5383 

@africanmathsinitiative/developers this is ready for review. Please test all 3 cases as the R code has changed substantially.

- allow 62 columns to be given for day option for flags
- added tooltips on radio buttons and receiver label to explain cases
- added label to show number of columns in multiple receiver
- set selector to remove columns added in a receiver to make selection clearer
- allowed month and year columns to be non-numeric
- added an "unstack elements" option for multiple elements
- stop and give output if unstacking and values are not unique

Also included here is a bug fix in `ucrReceiverMultiple`. The additional line added ensures that the selector refreshes when using the "Clear" option in the receiver. This is only important if the columns are removed from the selector when added which is why this has gone unnoticed for a long time.

2020-10-21 07:39 UTC, lloyddewit commented
@rdstern Please could you test? thanks

@shadrackkibet Please could you peer review? It would be great if the peer review could be done this morning so we can include in tomorrow's build, thanks

2020-10-21 12:45 UTC, rdstern commented
Tough test to start with!  The Niger data for 10 stations as it arrived.
[dlyNiger.zip](https://github.com/africanmathsinitiative/R-Instat/files/5415882/dlyNiger.zip)
These are the data.  I separated V5 into year and month, made V2 and V3 into factors.
Then also got rid of one row when V5 was NA.
Then 62 variables and didn't unstack.  The error was:
![image](https://user-images.githubusercontent.com/11226469/96721096-91b3aa80-13a3-11eb-9a22-fc2019653593.png)

2020-10-21 13:25 UTC, dannyparsons commented
This worked for me. I think you have an older version of the `tidyselect` package. Hopefully if you update the package it will now work. The up to date version of the package will be included in the next release. Sorry I didn't realise an update was needed to run this.

2020-10-21 13:39 UTC, dannyparsons commented
@shadrackkibet are you also able to test this to confirm?

2020-10-21 14:10 UTC, shadrackkibet commented
Works for me. Only that on reopening the multiple receiver label (red) resets to (0).

2020-10-21 14:18 UTC, shadrackkibet commented
See below
![image](https://user-images.githubusercontent.com/26301973/96732704-4f996180-13c1-11eb-9344-e2d279609906.png)

2020-10-21 14:40 UTC, dannyparsons commented
Thanks, I think I've fixed that by removing the label from the designer as this was being reset when the dialog reopened and the translation was being done.

2020-10-21 22:31 UTC, rdstern approved these changes

2020-10-21 22:33 UTC, rdstern commented
@dannyparsons it now seems to work nicely on the 64 bit version.  Happy to approve at this stage from my point of view.  It has produced variables in an "interesting" order, called value_906, value_914, value_32... There are 41 of them, followed by the flag_906, etc.  

This is my first experience in climatic, or a data frame with so many elements/variables and hence adding a bit of urgency to improvements on tools to be able to organise the names, etc.

I am really pleased with the changes - not just the flag fields, but also being able to cope with year and month variables that are character as well as numeric.  I have not tried, but hope it is still ok with jan, Feb, etc?

2020-10-22 08:41 UTC, lloyddewit requested changes
@dannyparsons this looks good, I just had some small questions about the R code

2020-10-22 08:41 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
> +    if(continue) {
Replace with `if(!continue) stop` (or `return`)?

2020-10-22 08:41 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
> +      else id_cols <- c(id_cols, "element")
will this be overwritten by line 2114?

2020-10-22 11:35 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
>    if(continue) {
This is a hack around the issue that we can't display output to the output window in R-Instat if the R function returns an error. So that's why I don't use `stop` although that would be the best R practice. The inline comment tries to explain this. It's our issue in VB and use of the RLink so once we resolve this the function can be corrected.

2020-10-22 11:37 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +      else id_cols <- c(id_cols, "element")
Both lines are extending `id_cols`: 
`id_cols <- c(id_cols, "element")` and then `id_cols <- c(id_cols, "date")` so the later line doesn't overwrite the changes from the previous.

2020-10-22 12:08 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +      # ".value" is a special sentinel used in names_to ensure names of value columns come from the names of cols. See ?pivot_longer values_to section for details.
done

2020-10-22 12:08 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +      y$day <- substr(y$day, 4, 5)
done

2020-10-22 12:10 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +    if(!all(sapply(x[, stack_cols], function(col) is.numeric(col) || (is.logical(col) && all(is.na(col)))))) stop("All stack_cols must be numeric\nThe following stack_cols are not numeric: ", paste(s
I agree but not sure how general it should be so added a comment to say this needs to be done.

2020-10-22 12:10 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +    if(continue) {
done

2020-10-22 12:10 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +    if(length(stack_cols) != 31 && length(stack_cols) != 62) stop("You have specified: ", length(stack_cols), " stack columns\nThere must be exactly 31 or 62 stack columns when format == 'days'")
done

2020-10-22 12:12 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +    y$month <- substr(y$month, 6, 8)
done

2020-10-22 12:13 UTC, dannyparsons commented
Thanks I've addressed or commented on those points.

2020-10-22 12:35 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
>    if(continue) {
Sorry, I didn't express my comment very well. I understand that `stop` won't work here. My comment was about inverting the `if` statement to avoid indenting the normal path. If `stop` is not correct here then could `if(!continue)` return be used?
I'll approve any way because this is not so important.

2020-10-22 12:36 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
> +      else id_cols <- c(id_cols, "element")
Thanks for the explanation, I should really learn R

2020-10-22 12:37 UTC, lloyddewit approved these changes

2020-10-22 12:38 UTC, lloyddewit commented
@rdstern please could you reapprove (functionality should not have changed)? thanks

2020-10-22 12:48 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
>    if(continue) {
Ah I see, I didn't understand the full comment. Yes I've done this now with `return()`

2020-10-22 13:10 UTC, lloyddewit approved these changes

2020-10-22 14:08 UTC, rdstern approved these changes
Great improvements

2020-10-22 14:29 UTC, merged