Adding ucrSave control to dlgFindNonnumericValues
africanmathsinitiative/R-Instat pull request #6043
Opened 2020-10-25 22:07 UTC by Patowhiz

Fixes #6002
Extended the adding of columns functionality.
Removed bug in the calculation script.
Made the dialog use `ucrSave` control.

2020-10-26 11:06 UTC, lloyddewit commented
@Patowhiz ready for review/test? thanks

2020-10-26 15:23 UTC, Patowhiz commented
@lloyddewit @africanmathsinitiative/developers this is now ready for review.

Please note, I had to extend the adding of columns functionality to support this and future dialogs which save columns in separate scripts. This seemed to be the best alternative rather than quickly extending the `calculations.R` scripts.

The current implementation of adding and at the same time positioning columns can be adapted to the older script code(which technically limited this function to columns that didn't exist). So currently there is a duplication of checks, I will add a comment in regards to this once this new implementation is generally agreed.

2020-10-26 15:32 UTC, rdstern commented
@Patowhiz I am trying to check your new code.  It says I need to update my version of R - which I have done.  I am using 4.0.3.  So I wonder if the problem is that your version wasn't updated?

2020-10-26 16:43 UTC, Patowhiz commented
@rdstern Oh! yes. This PR didn't have the latest changes from master. I've now updated. But let me test if bug mentioned in issue #6042 will now affect this PR.

2020-10-27 07:40 UTC, Patowhiz commented
@rdstern now you can test this PR. This dialog will not have the bug described in issue #6042. The functionality extended is designed differently. Please note, it's only dialog `dlgFindNonnumericValues`, because of how the dialog script produces the new logical column.

2020-10-27 17:30 UTC, lilyclements reviewed
It seems that this PR means that the new column is often at the end of the data frame.

1. I think the new generated column is supposed to be next to character column in the receiver for this dialog (I may be wrong, however, this is going off the issue).
2. If I use the right-click on the main data frame to "Convert" a column, e.g. "Convert to Character", then the column moves to the end of the data frame, rather than stay in the position where it initially was. (I assume this happens elsewhere, for example, "Prepare > Data Frame > Convert Columns").
3. This does not occur everywhere, however. E.g., Prepare > Calculate > Duplicate Column we want the new column to be placed next to a current column (i.e., not necessarily at the end of the data frame) and this does as such.

This seems to cause a bug if I create a new column (where the new column is not placed at the end of the data frame) and open a dialog. Using the "diamonds" data set in the `ggplot2` library:
a) Go to Prepare > Calculate > Duplicate Column and put in "cut" as the column to duplicate. Press OK
b) Open the "Non-Numeric Cases" dialog

The following error comes up:

![image](https://user-images.githubusercontent.com/21180424/97338810-b6af8e00-1879-11eb-934f-13b66f2020cc.png)

For me, this bug also occurred for other data sets I tried out, and for any dialog I tried to open in (b), however, I'm being specific here in case you try a data set/dialog which it happens to not occur with.

2020-10-28 10:05 UTC, Patowhiz commented
@lilyclements thank you for testing this.

I have solved your item (1). I had not linked the new save control to the receiver.
I have also solved item (2). 

@rdstern @dannyparsons  to solve the item (2) raised by @lilyclements  above. I had to fix issue #6042 also. So @rdstern this PR doesn't have the bug. You can now also test this.

2020-10-28 11:27 UTC, rdstern approved these changes
Great.  Please can @lloyddewit and perhaps also @dannyparsons check the code.  This could have solved the serious bug in 0.6.3

2020-10-30 11:46 UTC, lloyddewit requested changes
@Patowhiz thanks, looks good, just a couple of small questions

2020-10-30 11:46 UTC, lloyddewit commented on instat/ucrSave.vb
>      '''             this control changes. </para><para>
```suggestion
    '''             This subroutine is called automatically when the receiver (specifying a column name) linked to 
    '''             clsColPosFunction changes. </para><para>
```

2020-10-30 11:46 UTC, lloyddewit commented on instat/clsRCodeStructure.vb
> -                    End If
I understand that:
- old code: add `before` parameter unless (`strAdjacentColumn` specified AND `before` false AND don't include default params)
- new code: always add `before` parameter

Therfore the only difference is related to including default parameters (visually different but functionally the same). Please could you clarify the purpose of this change?

2020-10-30 14:42 UTC, Patowhiz commented on instat/clsRCodeStructure.vb
> -                    End If
It's actually also functionally different at the R backend level. 

Basically, by not defining the before parameter, at the backend level, the function responsible for for adding or replacing columns will not be able to know where to position the new or replaced column. So it will just add it but not position it.

Before my new changes, replaced columns could not be repositioned. To extend this functionality but at the same time not affect other backend R functions that use the add column R function, I had to change how this parameter is being used in the add column R function block.

2020-11-01 09:28 UTC, lloyddewit commented on instat/clsRCodeStructure.vb
> -                    End If
In the R backend, the `before` and `adjacent_column` parameters are used in the `add_columns_to_data` function. In this function, the `before` parameter is `FALSE` by default (see definition below from `data_object_R6.R` line 496). The change above explicitly forces the `before` parameter to be set even when it is `FALSE` (but it's anyway `FALSE` by default). Therefore I still don't see the purpose of the change above. Am I missing something?
Could you test with and without the above change to clarify if it makes any difference? thanks
```
function(col_name = "", col_data, use_col_name_as_prefix = FALSE, hidden = FALSE, before = FALSE, adjacent_column, num_cols, require_correct_length = TRUE)
```

2020-11-02 10:15 UTC, Patowhiz commented on instat/clsRCodeStructure.vb
> -                    End If
@lloyddewit I have changed `add_columns_to_data` function in this PR. It is now as shown below;
`function(col_name = "", col_data, use_col_name_as_prefix = FALSE, hidden = FALSE, before, adjacent_column, num_cols, require_correct_length = TRUE) `

Check line 496 in file `data_object_R6.R` in this PR. Look at the green line. Below is also a screenshot.

<img width="924" alt="code_difference" src="https://user-images.githubusercontent.com/21179007/97856539-7e8ecc00-1d0d-11eb-89a2-2bc7ace65bad.PNG">

2020-11-03 09:25 UTC, lloyddewit commented on instat/clsRCodeStructure.vb
> -                    End If
Yes, you're correct, I didn't notice the change on line 496, sorry for that. I'll approve.
Out of interest, what was the reason for removing the default parameter? is it to force the developer to be specific?

2020-11-03 09:26 UTC, lloyddewit approved these changes

2020-11-03 09:26 UTC, lloyddewit commented
@rdstern  since your last approval, only a comment changed. Please could you re-approve? thanks

2020-11-03 09:45 UTC, rdstern approved these changes

2020-11-03 11:12 UTC, merged

2020-11-03 19:48 UTC, Patowhiz commented on instat/clsRCodeStructure.vb
> -                    End If
@lloydewit 
Yes, if the developer doesn't specify any value the function assumes no positioning is required. Which technically is a good assumption.  
Before the change, there was no way of knowing whether positioning of the column added or replaced is needed(which is understandable, replaced columnscould not be repositioned). The alternative to solving this would have been adding another parameter for this,  which I think would have been redundant.

2020-11-03 19:57 UTC, Patowhiz commented on instat/dlgFindNonnumericValues.vb
> +        ucrSaveColumn.setLinkedReceiver(ucrReceiverColumn)
@rdstern  below is my response in regards to the comment you made about making dialogs automatically create new columns after selected variable
@lilyclements for dialogs that already have the ucrSave control, a code line like this is the only change required to make the new column created by the dialog be automatically position after the selected column/variable. See the comment above the code.
ucrReceiverColumn.strSelectorHeading = "characters"

'makes the ucrSave control to position new column after selected column
ucrSaveColumn.setLinkedReceiver(ucrReceiverColumn).