Adding controls to dlgPolarCluster
africanmathsinitiative/R-Instat pull request #6050
Opened 2020-10-29 06:34 UTC by HawardKetoyoMsatsi

Fixes #5966
Added controls to dlgPolarCluster and implemented R code.

@africanmathsinitiative/developers , @shadrackkibet , this is ready for review.

2020-11-12 08:24 UTC, rdstern reviewed
I can't test this until #6048 is merged.

2020-11-12 09:14 UTC, shadrackkibet reviewed
Looks good. Then think about data at multiple levels, will this function still cope with that?

2020-11-12 09:14 UTC, shadrackkibet commented on instat/instat.vbproj.user
> +</Project>
Did you intend to have these changes here?

2020-11-12 09:14 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        End If
Just to check, what if the numeric up-downs are empty? doesn't this bug?

2020-11-12 09:14 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        ucrInputColor.SetItems(dctColor)
set the R Default here

2020-11-12 09:18 UTC, shadrackkibet commented
I think you also want to save the graph so add the save control into these dialogs.

2020-11-12 12:29 UTC, HawardKetoyoMsatsi commented on instat/dlgPolarCluster.vb
> +        End If
It doesnt bug however the code appears as follows.

last_graph <- openair::polarCluster(mydata=mydata, pollutant="nox", wd="wd", x="ws", cols="Accent", angle=, n.clusters=)

should we leave the OK button disabled until these fields are filled?

2020-11-12 12:34 UTC, HawardKetoyoMsatsi commented on instat/dlgPolarCluster.vb
> +        ucrInputColor.SetItems(dctColor)
@shadrackkibet the default is already set to "Accent".

2020-11-12 12:46 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        ucrInputColor.SetItems(dctColor)
But that is not the R Default

2020-11-12 12:48 UTC, shadrackkibet commented on instat/dlgPolarCluster.vb
> +        End If
So long as it doesn't bug and the graph produced is sensible then happy to leave it that way.

2020-11-12 12:50 UTC, lloyddewit commented
@rdstern PR #6048 is now merged so this PR is ready for testing (but you may wish to wait for @HawardKetoyoMsatsi to resolve @shadrackkibet 's suggestions first)

2020-11-12 13:01 UTC, HawardKetoyoMsatsi commented on instat/instat.vbproj.user
> +</Project>
@shadrackkibet No, I didn't intent to have them. 
@lloyddewit I am not able to resolve the changes made in the file **instat/instat.vbproj.user** I didn't intend to have them is there anything that can be done about it?

2020-11-13 10:36 UTC, lloyddewit commented on instat/instat.vbproj.user
> +</Project>
@HawardKetoyoMsatsi I think you can just reverse the changes to `instat.vbproj.user` and push the file again (i.e. copy-paste the original contents of the file into your version of the file and push it again). Git will recognise that the file is identical and remove it automatically from the PR (I think!)

2020-11-27 11:16 UTC, lloyddewit commented
@HawardKetoyoMsatsi are the comments from @shadrackkibet now resolved? thanks

2020-11-27 16:05 UTC, HawardKetoyoMsatsi commented
@lloyddewit in the last 7 commits I made in this PR I addressed comments made by @shadrackkibet.

2020-11-28 08:40 UTC, lloyddewit commented
@rdstern please could you test? thanks

2020-12-08 11:50 UTC, lloyddewit commented
@rdstern please could you test? thanks

2020-12-11 17:50 UTC, rdstern requested changes
@HawardKetoyoMsatsi  well done this all seems to work.

I am not sure what it does, so it will be good to get it merged soon.  I have a few questions:
a) The first is called pollutant.  That's odd to me that it isn't a default of wind speed?
b) There is an odd order of the controls with the Date between the other two.
c) You have to include a third variable.  I found that I could put windspeed as the pollutant and also the third variable.  So I am still not quite sure what is happening here.
d) This probably applies generally to this set of controls.  None of them seem to fill by default.  If the data were defined as climatic with these variables, then perhaps they could be?

2021-03-16 06:43 UTC, HawardKetoyoMsatsi commented
I am closing this so that I can reimplement and open it in another PR

2021-03-16 06:43 UTC, closed without merging