R-Instat startup window modification
africanmathsinitiative/R-Instat pull request #6052
Opened 2020-10-29 11:52 UTC by Patowhiz

Fixes #6045.
@africanmathsinitiative/developers this is ready for review.

2020-10-29 19:24 UTC, rdstern approved these changes
This is better and happy to accept - so approving.
I hope the changes can be assessed by @lloyddewit and merged into the forthcoming version.
I would like to question (perhaps in parallel) a couple of points.
a) I like the More option.  But the screen is very clean without the results of that.  It is also a one-way option.  I would like @dannyparsons and @lloyddewit view on moving the Help section down a bit, and then having a Less option to return to the initial setting?
b) The More option is only available from this front screen.  It could be messy adding it to the bottom of the file menu, but could it also be an option on the Toolbar.  They currently show the same 5 recent files.  If this is desirable, but not so easy, then could it be an addition issue.

2020-11-01 11:10 UTC, lloyddewit commented
@Ivanluv Please could you review? thanks

2020-11-02 09:35 UTC, Patowhiz commented
@rdstern we could discuss item (c) on separate issue or PR. This PR has changes on `frmMain.vb` which may need to changed in another PR by another developer.

2020-11-02 13:12 UTC, Ivanluv commented
@lloyddewit  this looks okay from my end

2020-11-03 11:10 UTC, lloyddewit requested changes
This looks excellent (fault-tolerant, readable and well commented), just a couple of small questions

2020-11-03 11:10 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +        'the add and displays menu items (_in reverse order) for dialogs
```suggestion
        'then add and display menu items (in reverse order) for dialogs
```

2020-11-03 20:19 UTC, Patowhiz commented on instat/clsRecentFiles.vb
> +    Public Sub addToMenu(formOrFilePathObj As Object)
@lloyddewit yes. I also thought so. The 2 functions will be functionally different which reinforces the idea.
But then I realised the change will force me to change other files in this PR. Some of those files have been changed in my current open PR's. So I opted to comment and just improve it's internal implementation. 

I can quickly do that in this PR and resolve other PRs if you think it's important for it to be done. Alternatively I can do it after those PRs are merged and put in a reference to your above comment in the new PR that will address it. I prefer the second option.

2020-11-04 08:42 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +    Public Sub addToMenu(formOrFilePathObj As Object)
@patowhiz I don't think that other files need to be changed. They will automatically call the correct sub based on the type of parameter they pass. Only `clsRecentFiles.vb` needs to be changed. The following should work:
```
   ''' <summary>
    ''' adds the form to menu items
    ''' </summary>
    ''' <param name="frmDialog">form to add to menu items</param>
    Public Sub addToMenu(frmDialog As Form)
        'Checks for existance, else add it to the beginning
        If lstRecentDialogs.Contains(frmDialog) Then lstRecentDialogs.Remove(frmDialog)
        'adds to the list
        lstRecentDialogs.Add(frmDialog)
        'checks that only 10 items are allowed
        If lstRecentDialogs.Count > 10 Then
            lstRecentDialogs.RemoveAt(0)
        End If
        'update recent dialogs menu items
        UpdateRecentDialogsMenuItems()
    End Sub

    ''' <summary>
    ''' adds the file path to menu items
    ''' </summary>
    ''' <param name="strFilePath">file path to add to menu items</param>
    Public Sub addToMenu(strFilePath As String)
        'remove file if it exists(helps with making sure displayed file names are rearranged)
        lstRecentOpenedFiles.Remove(strFilePath)
        'add to recent opened files list..
        lstRecentOpenedFiles.Add(strFilePath)
        'make sure there are only ever 30 items...
        'todo. add this to the general options on the number of recently files to show
        While lstRecentOpenedFiles.Count > 30
            lstRecentOpenedFiles.RemoveAt(0)
        End While
        'update recent files menu items
        UpdateRecentFilesMenuItems()
    End Sub
```

2020-11-04 10:06 UTC, Patowhiz commented on instat/clsRecentFiles.vb
> +    Public Sub addToMenu(formOrFilePathObj As Object)
@lloyddewit yep. Was thinking about the naming convention also. Capital "A" instead of small "a" in the subroutine name `addToMenu`, will cause changes to other files after refactoring. Or should we just ignore that for now?

2020-11-04 10:11 UTC, Patowhiz commented on instat/clsRecentFiles.vb
> +    Public Sub addToMenu(formOrFilePathObj As Object)
@lloyddewit I have changed the function as suggested. Thank you.

2020-11-05 09:00 UTC, rdstern approved these changes
All looks good.  I must admit I wasn't quite sure what has changed - but it is working fine for me.

2020-11-05 09:26 UTC, Patowhiz commented
@rdstern in addition to the items raised in the issue, below are the major changes added.

> @rdstern I've made the recent header and files to be displayed when R-Instat is fully "initialised" (and almost the same time the output window displays the initial command). I realised doing so is much safer (`R` has to be initialised first before any opening of file operations) and won't deviate from current loading events much.
> 
> I've also optimised the code to prevent unnecessary calls of refreshing the displayed lists of recent file.
> 
> The recent files section should now "feel" more natural from the end user perspective.

2020-11-05 11:14 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +    Public Sub addToMenu(formOrFilePathObj As Object)
yes, I also noticed that the naming convention wasn't followed, I agree with you that this doesn't need to be done in this PR. This all looks good now :)

2020-11-05 11:14 UTC, lloyddewit approved these changes

2020-11-05 11:15 UTC, merged