Dlg factor convert
africanmathsinitiative/R-Instat pull request #6076
Opened 2020-11-09 12:28 UTC by lilyclements

Fixes #6005 

This is still in progress.

2020-11-10 17:55 UTC, dannyparsons requested changes

2020-11-10 17:55 UTC, dannyparsons commented on instat/ucrColumnMetadata.vb
> +        clsConvertOrderedFactor.AddParameter("col_names", GetSelectedVariableNames(), iPosition:=2)
I think you've switched them the wrong way round here?

2020-11-10 17:55 UTC, dannyparsons commented on instat/ucrDataView.vb
> +        clsConvertTo.AddParameter("col_names", SelectedColumns(), iPosition:=1)
It looks like you've left these in the other order just to see if anyone noticed ;) It looks like the only one where they are added in a different order, doesn't make any difference but now I can't unsee the inconsistency :)

2020-11-10 18:18 UTC, lilyclements commented on instat/ucrDataView.vb
> +        clsConvertTo.AddParameter("col_names", SelectedColumns(), iPosition:=1)
Yes, all a big test - congrats! I can't unsee it either, have sorted it now.

2020-11-11 09:20 UTC, dannyparsons approved these changes
@lloyddewit happy with this. There is no functionality change to R code being run from these changes.

2020-11-11 11:38 UTC, lloyddewit commented
@rdstern please could you test? thanks

2020-11-11 11:55 UTC, rdstern approved these changes
Happy to approve this change to the code.  And so I do.  But while changing the code I note there remains an issue of ordered factors.  I don't know if @lilyclements or @dannyparsons feels it is a good time to also change that.
If I have numeric I can make it either a factor, or an ordered factor.  But once it is a factor I am then not able to make it (instead) into an ordered factor.  I have tired clicking on ordered factor.  I have also tried making it numeric again and then an ordered factor.  It stubbornly remains labelled as (f), rather than (o.f).

2020-11-12 12:53 UTC, lloyddewit approved these changes

2020-11-12 12:54 UTC, merged

2020-11-12 12:58 UTC, dannyparsons commented
This should be mentioned on the issue about defining factors, but yes it is related.