Adding the station radio button to Climatic summaries dialogue
africanmathsinitiative/R-Instat pull request #6091
Opened 2020-11-16 10:12 UTC by Ivanluv

@africanmathsinitiative/developers  this is ready for review
fixes #6068

2020-11-16 15:36 UTC, dannyparsons requested changes

2020-11-16 15:36 UTC, dannyparsons commented on instat/dlgClimaticSummary.vb
> +        ucrPnlAnnualWithin.AddParameterPresentCondition(rdoAnnual, "stations", False)
That's not a correct condition for Annual. Annual will be by stations if there are stations.

2020-11-16 15:36 UTC, dannyparsons commented on instat/dlgClimaticSummary.vb
> +        ucrPnlAnnualWithin.AddParameterPresentCondition(rdoStation, "stations", True)
The conditions for station should also have not year and not within year.

2020-11-16 15:36 UTC, dannyparsons commented on instat/dlgClimaticSummary.vb
> +                clsDefaultFactors.RemoveParameterByName("stations")
Why are you removing this here? Stations should always be included for each option if there is a station column, as you have done on line 373.

2020-11-17 06:19 UTC, Ivanluv commented on instat/dlgClimaticSummary.vb
> +        ucrPnlAnnualWithin.AddParameterPresentCondition(rdoAnnual, "stations", False)
`stations` is a different parameter from `station`. I made it to simplify assigning of conditions

2020-11-17 14:18 UTC, dannyparsons commented on instat/dlgClimaticSummary.vb
> +        ucrPnlAnnualWithin.AddParameterPresentCondition(rdoAnnual, "stations", False)
Ok I think I've seen what you've done with the two parameters. But this is quite confusing when reading the code (and for someone editing this in future to easily make a mistake), and I don't think necessary. If the only reason is to shorten the number of conditions then I don't think it is an advantage over having clearer and more logical code, even if it's longer. It would be much clearer to have a single parameter for stations, and have four conditions for the station radio button. That also simplifies the code below when setting the parameters.

2020-11-17 16:09 UTC, rdstern requested changes
@Ivanluv this is great.  It works well.  The one problem needs perhaps a comment from @dannyparsons .  If you don't have a Station factor, then Ok is still enabled.  But the summary doesn't work without a factor.  You can have a factor with a single level - that's fine.  But otherwise you just get a single number in the summary, rather than a single row.
I suggest, for this option, you don't have Ok enabled unless the Station factor is present.  Note that you don't need a station factor for any of the other 3 radio-button options, because then you have a year etc factor.  The problem is just when there is no factor.

2020-11-17 21:49 UTC, dannyparsons commented
I agree, if there are no station variables then ok is disabled.

2020-11-19 13:02 UTC, Ivanluv commented
@rdstern  could you look at this again. @dannyparsons  I have made some changes to the conditions but am not sure if its the correct way to do it

2020-11-19 14:23 UTC, dannyparsons commented on instat/dlgClimaticSummary.vb
> +        ucrPnlAnnualWithin.AddParameterPresentCondition(rdoStation, "station", True)
This is technically correct, but I think you will have an issue when no factors are given, because then none of the conditions will be matched and you'll get a developer error. So if you remove this condition then when no factors are filled in, the station radio button will be selected, and there's no chance of errors.

2020-11-19 14:25 UTC, dannyparsons commented on instat/dlgClimaticSummary.vb
> +        clsDefaultFactors.AddParameter("year", "")
I think by removing the line mentioned above this won't be needed anymore and can be removed.
@rdstern are you happy that the station option is the default when opening the dialog?

2020-11-19 15:47 UTC, rdstern commented
Yes indeed

2020-11-27 09:43 UTC, lloyddewit commented
@Ivanluv did you resolve all the comments from @dannyparsons and is it ready for another review? thanks

2020-11-27 09:46 UTC, Ivanluv commented
@lloyddewit this is ready for review

2020-11-27 10:01 UTC, lloyddewit commented
@dannyparsons please could you confirm that your comments are all resolved? thanks

2021-01-04 11:49 UTC, rdstern approved these changes
It is time this was merged.

2021-01-05 08:27 UTC, lloyddewit commented
@Ivanluv Please could you clarify if/how @dannyparsons 's comments were resolved? thanks

2021-01-05 09:06 UTC, Ivanluv commented
@lloyddewit  have resolved the comment from @dannyparsons  by having the station radio button as the default and removing the unnecessary code

2021-01-05 10:13 UTC, lloyddewit commented on instat/dlgClimaticSummary.vb
> +        ucrPnlAnnualWithin.AddParameterPresentCondition(rdoAnnual, "stations", False)
confirmed resolved

2021-01-05 10:15 UTC, lloyddewit commented on instat/dlgClimaticSummary.vb
> +        ucrPnlAnnualWithin.AddParameterPresentCondition(rdoStation, "station", True)
confirmed resolved

2021-01-05 10:15 UTC, lloyddewit commented on instat/dlgClimaticSummary.vb
> +        clsDefaultFactors.AddParameter("year", "")
confirm resolved

2021-01-05 10:16 UTC, lloyddewit approved these changes

2021-01-05 10:18 UTC, merged