Inventory sub dialog graph
africanmathsinitiative/R-Instat pull request #6092
Opened 2020-11-17 11:14 UTC by N-thony

@rdstern I made improvements to the inventory graph. Can you confirm that the points you raised about issue #6029 have been made? Thank you.

2020-11-19 16:02 UTC, rdstern commented
@N-thony this is a good start.

1. On the sub-dialogue you have, I note that the x-axis "Year" is there initially.  Then it is absent after using the sub-dialogue.
2. On the initial titles sub-dialogue the font-sizes are all zero.  If you look at the Climatic > PICSA  > Rainfall graph sub-dialogue, they start at 20, 15, 8.
3. Again, on the PICSA sub-dialogue, there is a useful tooltip in the footnote about `\n` giving a newline.  That would be good to add.
4. What you have in the y-axis and x-axis tabs could be added, instead, into the Titles tab.  Again, as it is in the PICSA > Rainfall sub-dialogue.
5. Then the x-axis tab is mainly for the spacing of the years as they are labelled there.  See below.
![image](https://user-images.githubusercontent.com/11226469/99690521-27fcee00-2a80-11eb-8f35-f6511449d0eb.png)

For example if I would like those labels to be every 5 years, instead of every 20 years, I would do it there.
6. The y-axis may be more complicated and you will need help and advice from @shadrackkibet and @dannyparsons but the example above shows that it isn't great currently.  In this example, I can't read the information on either the right or the left of the y-axis.

Thanks.

Roger

2020-11-27 07:23 UTC, N-thony commented
@rdstern I solved the issues you raised days ago. Could you please confirm the issues are resolved? Thanks.

2020-11-27 07:52 UTC, rdstern commented
Thanks.  Will do.

2020-11-27 11:50 UTC, shadrackkibet requested changes

2020-11-27 11:50 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +  if(!is.null(labelYAxis)){g <- g + ggplot2::ylab(labelYAxis)}else{g <- g + ggplot2::ylab("")}
Always use `missing()` to check if an argument is specified. `is.null`  is a check for the reserved word "NULL" which means "empty". Then use ` ggplot2::xlab(NULL)` and `ggplot2::ylab(NULL)` which gives more space on the axis.

2020-11-30 07:07 UTC, N-thony commented on instat/static/InstatObject/R/data_object_R6.R
> +  if(!is.null(labelYAxis)){g <- g + ggplot2::ylab(labelYAxis)}else{g <- g + ggplot2::ylab("")}
Thanks

2020-11-30 07:08 UTC, N-thony commented
@shadrackkibet I solved the issue you raised days ago. Could you please confirm the issue is resolved? Thanks.

2020-12-01 09:56 UTC, shadrackkibet requested changes

2020-12-01 09:56 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +     if(scale_ydate && !is.null(date_ybreaks) && !is.null(date_ylabels)){ g <- g + ggplot2::scale_y_date(date_breaks = paste0(step," ",date_ybreaks), date_labels = date_ylabels) }
What about this? Check other places as well.

2020-12-01 10:27 UTC, N-thony commented
@shadrackkibet I solved the issue you raised minutes ago. Could you please confirm the issue is resolved? Thanks.

2020-12-03 09:30 UTC, lloyddewit commented
@rdstern are the issues you raised above now resolved? thanks

2020-12-18 07:04 UTC, rdstern commented
@N-thony I tried to check the sub-dialogues, but they are still disabled.  I can't check until they are enabled.  Thanks

2020-12-18 09:19 UTC, N-thony commented
> @N-thony I tried to check the sub-dialogues, but they are still disabled. I can't check until they are enabled. Thanks

@rdstern what do you mean by they are still disabled? The Sub-dialog or something else?

2020-12-18 10:23 UTC, rdstern commented
@N-thony sorry, I can get the Inventory sub-dialogue.

I still can't sort out the x-axis or y-axis scales as I would like to.  On x-axis it is usually like the PICSA sub-dialogue.  There I can do this

![image](https://user-images.githubusercontent.com/11226469/102603088-422afa00-411a-11eb-870f-f53612d3bc0b.png)

So, I am not sure you need None and Date.  It is usually (I haven't tried all options, just numeric, so the same as PICSA should work.  See the year x-axis in the picture above.

You have allowed for dates so I tried them.  I am not sure it is needed for this, but might be for the y-axis.  When I tried with date, because that was my only option to get more labels so:
![image](https://user-images.githubusercontent.com/11226469/102603525-d7c68980-411a-11eb-9ae1-a79773ac39f2.png)

Gave:
![image](https://user-images.githubusercontent.com/11226469/102603622-f9277580-411a-11eb-8c5a-ff744849a1b5.png)

As I say - I am not sure you need the date option for the x.

2020-12-18 10:30 UTC, rdstern commented
Here is an example for a possible date change on the y-axis
![image](https://user-images.githubusercontent.com/11226469/102604139-a4d0c580-411b-11eb-87f5-b15d66cb434d.png)
Possibly that might not give much flexibility, but could allow anything from one month to 6 months, and also allow the font to change.  Also just possibly have none?  What do you think?

2020-12-18 10:36 UTC, shadrackkibet commented on instat/instat.vbproj
> +    </EmbeddedResource>
You don't have to create a new sub dialog. There is already an existing form (sub dialog) `sdgInventoryGraph.vb`. So I don't expect changes in `.vbproj `

2020-12-18 10:38 UTC, shadrackkibet commented on instat/dlgInventoryPlot.vb
> +        sdgInventoryPlot.ShowDialog()
You don't have to create a new sub dialog. There is already an existing form (sub dialog) `sdgInventoryGraph.vb`. So I don't expect changes in `.vbproj`

2020-12-18 16:14 UTC, rdstern commented
![image](https://user-images.githubusercontent.com/11226469/102618836-60e9ba80-4133-11eb-8ca0-afdc1974731d.png)

This is great, just what I was hoping for in flexibility.

![image](https://user-images.githubusercontent.com/11226469/102632664-491c3180-4147-11eb-8ab9-dc6e420d0453.png)
or
![image](https://user-images.githubusercontent.com/11226469/102633847-e7f55d80-4148-11eb-94c0-35b88dc6e8a2.png)
or
![image](https://user-images.githubusercontent.com/11226469/102634757-33f4d200-414a-11eb-945a-945645a25d7b.png)

a) In the y-axis tab the breaks up-down can go down to zero.  It gives an error if it is zero.  Make 1 the minimum.
b) In the Size, the up-down is inactive.  It is still usable, as you can type in (which I like), but the up-down should work.
 
c) A curiosity, that perhaps @dannyparsons can help to explain is the Jan appearing twice?  And the numbers in the y-axis are slightly confusing in starting (for example above) from 23 Dec and going to 17 Jan?
d) On the facets tab the first option is size.  Could there be two controls here for Station and Element.  In the example above I would like quite large, or default for the stations (only 2 stations), but quite small for the elements.  I assume this is possible?

To me a big improvement is the x-axis options and that is working well.  Great.

2020-12-21 12:18 UTC, N-thony commented
@rdstern I solved the issues you raised last Friday. Could you please confirm that the issues are resolved? Thanks

2020-12-21 14:39 UTC, rdstern commented
Looks good:
![image](https://user-images.githubusercontent.com/11226469/102788069-fab2a100-4399-11eb-8758-a9999986ce20.png)

On the labelling I notice that the axis labels are (I think) "above" the date.  I wonder if they can be centred instead? (Or their position could become an option?  @N-thony how is your R or this or do you want to check with @shadrackkibet

2020-12-21 15:44 UTC, N-thony commented
@rdstern I solved the issue you raised minutes ago. Could you please confirm that the issue is resolved? Thanks

2020-12-22 14:47 UTC, rdstern submitted a review, later dismissed
I am happy to approve this now, because it is a considerable improvement by @N-thony to this important dialogue.  He has added considerable flexibility to the dialogue.  The original is available and this is an improvement.
I hope @lloyddewit could check the text, but would also like either @shadrackkibet or @lilyclements to check on a remaining problem and also look at the design of the sub-dialogue tabs to see if they can suggest further options, and/or label and layout improvements.

![image](https://user-images.githubusercontent.com/11226469/102899274-93acef00-4462-11eb-943a-4875e57e3e22.png)

Here is the remaining problem (or problems).  When looking by year it seems to have 13 categories, ostensibly going from January to January.  I think the data may be ok and this is just ggplot being a bit clever on the labelling in a way we don't want here.  This is a general issue on this option.
2. A special problem is when the rain days are displayed.  We don't need to keep this option in the dialogue.  But it occasionally seems to give a problem.  Here it looks as though December 2000 was all rainy.  

Here are the data I was using:  
[ghana_2_stations.zip](https://github.com/africanmathsinitiative/R-Instat/files/5730463/ghana_2_stations.zip)

2020-12-23 10:12 UTC, lloyddewit requested changes
@shadrackkibet Thank you for your peer review
@N-thony This is good work! I just have a few small suggestions

2020-12-23 10:12 UTC, lloyddewit commented on instat/sdgInventoryPlot.vb
> +    Public strAxisType As String
Is this needed?

2020-12-23 10:12 UTC, lloyddewit commented on instat/sdgInventoryPlot.vb
> +    Private Sub UcrNud1_Load(sender As Object, e As EventArgs) Handles ucrNudFacetYSize.Load
Is this function needed?

2020-12-23 11:51 UTC, N-thony commented
@lloyddewit I solved the issues you raised hours ago. Could you confirm that the issues are resolved? Thanks.

2020-12-24 08:28 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +DataSheet$set("public","make_inventory_plot", function(date_col, station_col = NULL, year_col = NULL, doy_col = NULL, element_cols = NULL, add_to_data = FALSE, year_doy_plot = FALSE, coord_flip = FAL
Thanks for updating this line. There are other examples of very long lines in this function but they are throughout the R code. So it's OK to leave them as is for now.

2020-12-24 08:58 UTC, lloyddewit commented
@N-thony thanks, all my comments above are resolved.
I am ready to approve but there is still an issue with `instat.vbproj`. I resolved all the conflicts and the file in this PR is now identical to the file on the `master` branch (I double-checked this with an external diff tool). However, GitHub is confused and thinks that every line has changed. I cannot correct this myself because I don't seem to have push privileges to this PR.
It would be best if `instat.vbproj` disapeared totally from this PR. Please could you try one more time to copy the file from `master` and push it to this PR? There are a couple of ways of doing this, we can discuss if it helps.

2020-12-24 09:37 UTC, lloyddewit commented
@dannyparsons I am ready to approve this PR but there is an issue with 'instat.vbproj'. This was updated in this PR but the changes were not needed so we tried to reverse them. As far as I can see, the file in this PR is now identical to the file on the master branch (I checked this with an external diff tool). However, GitHub shows nearly every line as changed. 
We could go ahead and merge but it would be better if 'instat.vbproj' disapeared completely from this PR.
I could research how to achieve this but it may be time-consuming. 
Have you come across this type of situation before? Do you have any advice?
thanks

2020-12-28 08:04 UTC, lloyddewit commented
@N-thony I think the easiest solution to the `instat.vbproj` issue is to close this PR and make a new one.
Please could you:
- Make a new branch from the current master branch
- Copy the changes from this PR to the new branch (all files except `instat.vbproj`)
- Submit a new PR (which references this PR)
- Close this PR
Please let me know if you have any questions, thanks

2020-12-28 11:25 UTC, closed without merging