Extremes calculation dialog improvements
africanmathsinitiative/R-Instat pull request #6107
Opened 2020-11-26 14:18 UTC by shadrackkibet

Fixes #4760 and Fixes #5881.  @rdstern I am putting up this for some quick testing just to check that this is what is needed although it is still work in progress. Mean Residual Life Plot is already working however the following still remain. 

- Add more options eg min and max thresholds, rug, line colour, fill etc... Some of these might go into a subdialog.
- Implement the following;
  - Tc plot
  - Declustering

FYI here current look of the dialog.
![image](https://user-images.githubusercontent.com/26301973/100361391-2c3e8380-300b-11eb-9f6f-dec568899a1a.png)

2020-11-27 11:10 UTC, rdstern commented
Yes - seems to work:
![image](https://user-images.githubusercontent.com/11226469/100443065-f3e98480-30a0-11eb-829a-3f75735ec1e2.png)

I note it also automatically adds the filter.  This plot would usually be prior to that.  The plots look good.  I assume that options for scaling the facets, etc will come.

2020-11-27 11:28 UTC, shadrackkibet commented
I actually thought of modifying the filter so that it gives the values within an interval say, PRECIP>= 10mm &PRECIP<=20mm. This will be concurrent with what is displayed on the graph.

2020-11-29 07:21 UTC, shadrackkibet commented
@rdstern this is ready for you to review. This PR implements Mean residual life plot. I would like to get this merged first before I proceed with the other components i.e Tc plot and declustering. 

- On your point above, the filter is still added when Mrl plot checkbox is checked. If that is not sensible then we can find a mechanism to avoid adding a filter. This can be by making Mrl plot explicit on top or hide the **value**  controls when Mrl plot checkbox is checked.

2020-11-29 10:09 UTC, rdstern commented
![image](https://user-images.githubusercontent.com/11226469/100538700-45248000-3229-11eb-98f7-c93bd3343c9b.png)

This is looking great.  I am happy to approve in its current form and do so.  Perhaps @dannyparsons can check and see if it is ready, or can soon be merged.

Being critical, the above default has the word excesses that overtypes the numbers below, particularly when the graph is smaller.  And the facets have the same scale above, so can we have them as proper facets, with the x part only at the bottom.  That will become more critical with more stations.


![image](https://user-images.githubusercontent.com/11226469/100538900-7fdae800-322a-11eb-9a3b-76d028278480.png)

Here is the image "the other way".  Now I can't read the excesses, because of their size. Can this be changed?  And I wonder about having an option this way round, to have the same y axis for each graph - and hence save a lot of space again as well as compare the stations more easily.

Are there becoming too many options and we need a sub-dialogue button?

2020-11-29 10:09 UTC, rdstern approved these changes

2020-12-08 11:38 UTC, lloyddewit requested changes
looks good, just a couple of small comments

2020-12-08 11:38 UTC, lloyddewit commented on instat/dlgExtremesClimatic.vb
> +        clsPlotMrlFunction = New RFunction
move this down to line 378?

2020-12-08 11:38 UTC, lloyddewit commented on instat/dlgExtremesClimatic.vb
> +        clsPlotMrlFunction.AddParameter("element_name", ucrReceiverElement.GetVariableNames, iPosition:=2)
Once added, this parameter is never removed. Is that correct?

2020-12-08 17:26 UTC, shadrackkibet commented on instat/dlgExtremesClimatic.vb
> +        clsPlotMrlFunction = New RFunction
Keeping this here is consistent with what is done in other places. Clearing i.e `RFunction.Clear()` and setting of `New` instances of RFunction are normally done at the start of `setDefaults()` subroutine before adding parameters and setting other properties.

2020-12-09 08:27 UTC, lloyddewit commented on instat/dlgExtremesClimatic.vb
> +        clsPlotMrlFunction = New RFunction
understood, thanks

2020-12-11 11:23 UTC, shadrackkibet commented on instat/dlgExtremesClimatic.vb
> +        clsPlotMrlFunction.AddParameter("element_name", ucrReceiverElement.GetVariableNames, iPosition:=2)
Done!

2020-12-12 08:53 UTC, lloyddewit approved these changes

2020-12-12 08:55 UTC, lloyddewit commented
@rdstern the only change since your previous approval is that the `element_name` parameter should now be removed when the receiver is empty. Please could you test/approve? thanks

2020-12-18 06:58 UTC, rdstern approved these changes
Happy to approve and this is an exciting addition.  An early next step is to separate the new graphs from the process of making a new data frame.
And I think there is another section to come?

2020-12-20 09:27 UTC, lloyddewit approved these changes

2020-12-20 09:27 UTC, merged