Adding Export to World Weather Record dialog
africanmathsinitiative/R-Instat pull request #6114
Opened 2020-12-07 16:00 UTC by HawardKetoyoMsatsi

Added two blank forms dlgExportToWWR and sdgExportToWWR. This solves issue #6110
@africanmathsinitiative/developers and @rdstern this is ready for review. 
It contains frmmain changes therefore it should be merged as soon as possible.

2020-12-07 16:22 UTC, dannyparsons commented
Thanks for this. Are the menu items hidden? It's fine to add them to frmMain but they should be hidden until the dialogs are implemented. Alternatively, you could have created the dialog but not added the menu items yet. Either is ok.

Also, it's good to reference the issue, but you don't want this pull request to close the issue, because that will be when you actually do the dialog. In your next PR when you implement the dialog, you can use "fixes #xxx" to reference the issue and close it when merged.

2020-12-08 06:38 UTC, HawardKetoyoMsatsi commented
Well noted, I have disabled the menu.

2020-12-08 09:11 UTC, lloyddewit requested changes

2020-12-08 09:11 UTC, lloyddewit commented on instat/frmMain.resx
> +    <value>False</value>
Should both the `Enabled` **and** `Visible` properties be set to false? (we don't want the user to see a greyed-out menu item, we prefer the user not to see the menu item at all)

2020-12-08 09:11 UTC, lloyddewit commented on instat/frmMain.resx
> +  <data name="ExportToWWRToolStripMenuItem.Size" type="System.Drawing.Size, System.Drawing">
I'm not familiar with the `resx` naming convention but should this new menu item be called `mnuExportToWWRToolStrip`?
Please could you check with one of the other developers? thanks

2020-12-08 09:11 UTC, lloyddewit commented on instat/frmMain.resx
> +    <value>168, 22</value>
Do you know why these Rose plot values changed (I assume they aren't connected to this PR)?

2020-12-08 09:26 UTC, dannyparsons commented on instat/frmMain.resx
> +  <data name="ExportToWWRToolStripMenuItem.Size" type="System.Drawing.Size, System.Drawing">
Yes `mnuExportToWWRToolStrip` would be a sensible name.

2020-12-08 09:31 UTC, dannyparsons commented on instat/frmMain.resx
> +    <value>168, 22</value>
It does happen automatically sometimes, I am not really sure why. If it doesn't look any different in the design then it should be ok.

2020-12-08 11:34 UTC, dannyparsons commented
@HawardKetoyoMsatsi while you are here, could you also change the label for Climatic > Prepare > SPI to "SPI/SPEI" if Roger agrees. I will update the dialog itself.

2020-12-08 11:39 UTC, rdstern commented
Agreed.  Good idea to include SPEI.  I assume we can include our own evapotranspiration.  I did check with the package people if we could use their routine, but it seems to be limited to monthly data.

2020-12-08 20:09 UTC, HawardKetoyoMsatsi commented on instat/frmMain.resx
> +  <data name="ExportToWWRToolStripMenuItem.Size" type="System.Drawing.Size, System.Drawing">
I have fixed naming of the menu item mnuExportToWWRToolStripMenuItem .

2020-12-08 20:09 UTC, HawardKetoyoMsatsi commented
Since Roger agreed I have left the dialog for @dannyparsons to update the last suggestion raised concerning this dialog.

2020-12-08 20:31 UTC, HawardKetoyoMsatsi commented on instat/frmMain.resx
> +    <value>False</value>
I have set both enabled and visible properties to false

2020-12-09 08:21 UTC, lloyddewit approved these changes

2020-12-09 08:23 UTC, lloyddewit commented
@rdstern I approved from my side but it still requires an update from @dannyparsons

2020-12-09 10:16 UTC, dannyparsons approved these changes

2020-12-09 10:16 UTC, merged