Climdex dialog updated for multiple stations
africanmathsinitiative/R-Instat pull request #6118
Opened 2020-12-10 13:15 UTC by dannyparsons

- added wrapper climdex R functions for multiple stations
- updated dialog to new functions

@africanmathsinitiative/developers this is ready for review

**Please test:**
- Annual and Monthly options
- With and without multiple stations
- That it works with different kinds of month column e.g. number or names
- Running multiple times to see if summaries go in the same sheet (if the same station/year/month columns are used)
- Doing other summaries at the same level before and/or after using the dialog to see if they go in the sheet e.g. Climatic Summaries followed by Climdex

2020-12-11 11:54 UTC, lloyddewit requested changes
Just some small comments on the R code

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
> +          else if (setequal(mns, month.name.english)) climdex_output[[month]] <- month.abb.english[climdex_output[[month]]]
The if condition is the same as the line below. Should we check against `month.abb.english` instead?

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
> +                                "August", "September", "October", "November", "December")
Do we need to consider case sensititivity?

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
> +          else if (setequal(mns, month.name.english)) climdex_output[[month]] <- month.abb.english[climdex_output[[month]]]
The if condition is the same as the line below. Should we check against `month.abb.english` instead?

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                   "tr" = climdex.pcic::climdex.id(ci),
is this correct?

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                   "rx5day" = climdex.pcic::climdex.rx1day(ci, freq = freq),
is this correct?

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      } else if(freq == "monthly") {
```suggestion
      } else {
```
If we do check for `"monthly"` then for consistency should we also add a `else {stop ...`?

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  # All indices can only be calculated annually. Only some have monthly versions as well.
```suggestion
  # All indices can be calculated annually. Only some have monthly versions as well.
```

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  year_only_indices <- c("fd", "su", "id", "tr", "wsdi", "csdi", "gsl", "sdii", "r10mm",
These literal strings are duplicated. The compiler won't notice typos. Use constants?

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  else if (is.character(data[[year]])) df_out[[year]] <- as.character(df_out[[year]])
This type of logic seems to reoccur in the previous R file. Place this logic in a shared function?

2020-12-11 11:54 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                              "August", "September", "October", "November", "December")
duplicated literals, make constants?

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +          else if (setequal(mns, month.name.english)) climdex_output[[month]] <- month.abb.english[climdex_output[[month]]]
Yes, thanks.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +                                "August", "September", "October", "November", "December")
This is how they would be created from R automatically, but they could be in other forms. I've added checks for all upper case or all lower case as well.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/instat_object_R6.R
> +          else if (setequal(mns, month.name.english)) climdex_output[[month]] <- month.abb.english[climdex_output[[month]]]
Yes thanks.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                   "tr" = climdex.pcic::climdex.id(ci),
Fixed thanks.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                   "rx5day" = climdex.pcic::climdex.rx1day(ci, freq = freq),
Fixed thanks.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      } else if(freq == "monthly") {
Agreed, there is a check and stop above to make sure it is one of the two values so `else` is fine.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  # All indices can only be calculated annually. Only some have monthly versions as well.
Done.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  year_only_indices <- c("fd", "su", "id", "tr", "wsdi", "csdi", "gsl", "sdii", "r10mm",
This is what we should do when we make an R package with these functions. It's not so standard to make constants otherwise.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  else if (is.character(data[[year]])) df_out[[year]] <- as.character(df_out[[year]])
Yes, you're right. I've put it as a TODO comment for now.

2020-12-11 13:49 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                              "August", "September", "October", "November", "December")
Done.

2020-12-11 13:51 UTC, dannyparsons commented
@lloyddewit thanks for picking up those detailed mistakes. I've addressed your comments, could you check the latest changes?

@rdstern could review functionality in parallel.

2020-12-11 14:52 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  year_only_indices <- c("fd", "su", "id", "tr", "wsdi", "csdi", "gsl", "sdii", "r10mm",
OK, understood

2020-12-11 14:53 UTC, lloyddewit approved these changes

2020-12-12 07:42 UTC, rdstern requested changes
@dannyparsons this is great.  I have been trying it on the Niger (awkward) data and so far just about so good.
1) On the settings tab it used to say 1961 to 1990 as the base.  Now it said 1900 to 1900.  Perhaps that was to do with my data?
2) More serious is the settings for the maximum number of missing values.  The minimums of the up-down are both set to 1 and I suggest should be zero?  Second I don't think they are changing when I changed the settings down as far as I could go.  I failed to check the command though.

2020-12-12 15:10 UTC, dannyparsons commented
Thanks @rdstern those were both bugs, now fixed.

2020-12-12 15:11 UTC, merged

2020-12-14 11:21 UTC, lloyddewit reviewed
@dannyparsons FYI, I reviewed but have no comments