Speidlg
africanmathsinitiative/R-Instat pull request #6120
Opened 2020-12-11 14:35 UTC by lilyclements

Replaces #6116 

Fixes #6117 

@africanmathsinitiative/developers this is ready for review.

This PR fixes a few bugs and has some design alterations. Additionally, changes from #6116 :

> * dialog now allows multiple stations
> * wrapper R functions added to organise input and output data
> 
> **To test**
> 
> * Dialog is for monthly data only
> * Data must be in date order (within stations)
> * Data can't have any gaps i.e. missing months
> The dialog should get sensible errors if any of these are not met.

2020-12-12 09:46 UTC, lloyddewit commented
@shadrackkibet Please could you review? thanks
Sorry that I'm currently asking you to do most of the reviews. Your review observations increase the code quality. and you are the best qualified developer to do the reviews at the moment. The number of reviews needed may decrease in the next weeks but if the review requests get too much then let me know.

2020-12-12 14:36 UTC, shadrackkibet requested changes

2020-12-12 14:36 UTC, shadrackkibet commented on instat/dlgSPI.vb
>          ucrBase.clsRsyntax.iCallType = 2
Nothing is printed in the output window. Remove?

2020-12-12 14:36 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    ts_data[id_cols] <- NULL
```suggestion
  ts_data <- tidyr::pivot_wider(data,
  id_cols = tidyselect::all_of(c(year, month)),
  names_from = tidyselect::all_of(station), values_from = tidyselect::all_of(element),
  values_fill = NA) %>%
  dplyr::arrange(!!!rlang::syms(c(year, month))) %>%
  dplyr::select(!c(year, month))
```

2020-12-12 14:39 UTC, shadrackkibet commented
> @shadrackkibet Please could you review? thanks
> Sorry that I'm currently asking you to do most of the reviews. Your review observations increase the code quality. and you are the best qualified developer to do the reviews at the moment. The number of reviews needed may decrease in the next weeks but if the review requests get too much then let me know.

@lloyddewit I am happy to review. No worries!

2020-12-12 14:53 UTC, dannyparsons commented
Thanks @shadrackkibet I've addressed these comments here https://github.com/africanmathsinitiative/R-Instat/pull/6123

2020-12-12 14:53 UTC, merged

2020-12-14 11:45 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    ts_data[id_cols] <- NULL
@dannyparsons You implemented @shadrackkibet 's comment above with the exception of the `%>% dplyr::select(!c(year, month))` part.
I was expecting to see a line similar to:
```
ts_data <- ts_data %>% dplyr::select(!c(year, month))
```
Was this omitted deliberately?

2020-12-14 12:00 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    ts_data[id_cols] <- NULL
Yes, that didn't quite work because the column names are string variables, which needs a different syntax in `dplyr` but I couldn't quite figure out how to do this. In any case, it gives the same functionality.