Implemented code for Export to World Weather Record dialog
africanmathsinitiative/R-Instat pull request #6122
Opened 2020-12-11 17:52 UTC by HawardKetoyoMsatsi

Added controls to dlgExportToWWR and sdgExportToWWR and implemented code for these controls.
This fixes issue 6110
@africanmathsinitiative/developers @rdstern @dannyparsons This is ready for Review.

@dannyparsons The R function you created could be improved to output on the screen a message saying it is done running and saved the filed to ones PC.

2020-12-12 06:48 UTC, shadrackkibet requested changes

2020-12-12 06:48 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      summarise(mean = sprintf("%6s", round(mean(.data[[mean_temp]], na.rm = TRUE), 1)))
add package names. Please check other places as well.

2020-12-12 06:48 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                      pull(mean))
Also here and other places

2020-12-12 06:48 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      summarise(mean = sprintf("%6s", round(mean(.data[[mean_sea_level_pressure]], na.rm = TRUE), 1)))
@dannyparsons should we use `summary_mean()` instead of base `mean()`? which returns `NaN` when all months are missing. I am not sure if `NaN\NA` is consistent with WWR output format. Otherwise, we might want to remove empty years.

2020-12-12 11:22 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      summarise(mean = sprintf("%6s", round(mean(.data[[mean_sea_level_pressure]], na.rm = TRUE), 1)))
Yep, good idea, `NA`s will be coded as `""` in the output file, but I'm not sure if that will do the same for `NaN` so better to make sure it's always `NA`.
@HawardKetoyoMsatsi can you update the R code as Shadrack suggests?

2020-12-14 06:40 UTC, HawardKetoyoMsatsi commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      summarise(mean = sprintf("%6s", round(mean(.data[[mean_sea_level_pressure]], na.rm = TRUE), 1)))
Sure, I am going to update the R code shortly.

2020-12-14 08:24 UTC, HawardKetoyoMsatsi commented
@dannyparsons @shadrackkibet am done adding the above package names and implementing the summary_mean() function, entries with missing values are now coded as "NA"

2020-12-14 08:25 UTC, HawardKetoyoMsatsi commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      summarise(mean = sprintf("%6s", round(mean(.data[[mean_temp]], na.rm = TRUE), 1)))
Done.

2020-12-14 08:25 UTC, HawardKetoyoMsatsi commented on instat/static/InstatObject/R/stand_alone_functions.R
> +                      pull(mean))
Done.

2020-12-14 08:26 UTC, HawardKetoyoMsatsi commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      summarise(mean = sprintf("%6s", round(mean(.data[[mean_sea_level_pressure]], na.rm = TRUE), 1)))
Done.

2020-12-14 10:33 UTC, dannyparsons commented
Great, looks good. @shadrackkibet are you happy with this now? If so, I'll do a final review.

2020-12-17 05:32 UTC, shadrackkibet requested changes

2020-12-17 05:32 UTC, shadrackkibet commented on instat/dlgExportToWWR.vb
> +    Private Sub btnStationMetadata_Click(sender As Object, e As EventArgs) Handles btnStationMetadata.Click
The naming convention we use for buttons is `cmd...` good to maintain that for consistency.

2020-12-17 05:32 UTC, shadrackkibet commented on instat/sdgExportToWWR.vb
> +        ucrReceiverLongitude.SetParameter(New RParameter("longitude", 5))
Continue parameter positions from the main dialog since all are added into the base function. Good to maintain the order in the R function.

2020-12-17 05:32 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      dplyr::summarise(fq = as.function(fun)(na.omit(wt))) %>% arrange(-fq)
`dplyr::arrange(-fq)`?

2020-12-17 05:32 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
>    else dat <- dat %>% count(x, sort = TRUE, name = "fq")
also for `dplyr::count()`?

2020-12-17 05:32 UTC, shadrackkibet commented
Please sort out conflicts so that I can test.

2020-12-17 07:02 UTC, HawardKetoyoMsatsi commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      dplyr::summarise(fq = as.function(fun)(na.omit(wt))) %>% arrange(-fq)
Done.

2020-12-17 07:02 UTC, HawardKetoyoMsatsi commented on instat/sdgExportToWWR.vb
> +        ucrReceiverLongitude.SetParameter(New RParameter("longitude", 5))
Done.

2020-12-17 07:04 UTC, HawardKetoyoMsatsi commented on instat/dlgExportToWWR.vb
> +    Private Sub btnStationMetadata_Click(sender As Object, e As EventArgs) Handles btnStationMetadata.Click
Done.

2020-12-17 07:23 UTC, HawardKetoyoMsatsi commented
@shadrackkibet I m done resolving the conflict in this PR and fixing all the raised issues, kindly have a look.

2020-12-17 08:33 UTC, lloyddewit commented
@HawardKetoyoMsatsi @shadrackkibet Thanks for the good work and review
@dannyparsons You said above that you'll do a final review of this PR?

2020-12-17 08:39 UTC, shadrackkibet commented
I am still unable to test this. I think the sorting of conflicts caused issues in the  `stand_alone_functions.R` file. @HawardKetoyoMsatsi please sort this out and make sure you test it first on your machine.

![image](https://user-images.githubusercontent.com/26301973/102463530-4a246480-405c-11eb-8083-f06d588082f9.png)

2020-12-17 09:05 UTC, shadrackkibet requested changes

2020-12-17 09:05 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  else dat <- dat %>% plyr::count(x, sort = TRUE, name = "fq")
This is not the correct R package. This should be `dplyr::count()`

2020-12-17 14:51 UTC, HawardKetoyoMsatsi commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  else dat <- dat %>% plyr::count(x, sort = TRUE, name = "fq")
The original R function given to me had plyr::count() that's why I chose toupdate the missing package to dplyr::count().
I have now changed all cases to dplyr::count() changed

2020-12-17 14:55 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  else dat <- dat %>% plyr::count(x, sort = TRUE, name = "fq")
Notice that this function is not linked to WWR function.

2020-12-17 15:12 UTC, HawardKetoyoMsatsi commented
@shadrackkibet I have fixed the two issues above kindly take a look. The code is now running perfectly from my end.

2020-12-17 15:41 UTC, HawardKetoyoMsatsi commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  else dat <- dat %>% plyr::count(x, sort = TRUE, name = "fq")
Noted, I have fixed it accordingly.

2020-12-17 16:05 UTC, shadrackkibet commented
Few comments on the sub dialog design. @dannyparsons you can now proceed with your review.

![image](https://user-images.githubusercontent.com/26301973/102511482-e3be3700-4099-11eb-93b7-ec4219300665.png)

- The bottom receiver is missing colons (:)  
-  The labels for the last two receivers should be **Station Height:** and **Barometer Height:**
- Receivers are to well-aligned with labels.
- Receivers spacing should be even.

Use VS tools shown below to align and space controls.
![image](https://user-images.githubusercontent.com/26301973/102511937-7232b880-409a-11eb-9229-289512a2aadc.png)

2020-12-17 16:21 UTC, shadrackkibet commented
> @dannyparsons The R function you created could be improved to output on the screen a message saying it is done running and saved the filed to ones PC.

@dannyparsons what do you think? I think this is a good enhancement to consider.

2020-12-17 16:28 UTC, dannyparsons commented
Yes, good idea. Something like "File created at: path/to/file"

2020-12-17 17:24 UTC, shadrackkibet commented
> Yes, good idea. Something like "File created at: path/to/file"

@HawardKetoyoMsatsi can you make this change?

2020-12-18 08:01 UTC, HawardKetoyoMsatsi commented
@shadrackkibet @dannyparsons screen a message giving path to saved output has been added, please take a look.

2020-12-18 08:19 UTC, shadrackkibet commented
Looks better now. @dannyparsons please proceed with your review.

2020-12-26 16:36 UTC, Patowhiz commented
Could you please share the main dialog design. Would like to see if it uses or needs to use the custom file input control. Thanks

2020-12-29 18:07 UTC, dannyparsons commented
@HawardKetoyoMsatsi well done, this was really great. The code looks good and it's working well. 

I made some minor changes to your PR as a new PR here #6141. The reason for this is that there is an updated documentation on the WWR format which I was only made aware of recently, so the dialog and R code needed some minor changes. I also made a minor change to the design of the main dialog to add a group box for the elements, but other than your code looks good and I didn't have any other changes to make.

2021-01-19 16:56 UTC, merged