Implementing the Conditional Quantile Option
africanmathsinitiative/R-Instat pull request #6144
Opened 2021-01-01 12:09 UTC by N-thony

@rdstern I have implemented the Conditional Quantile dialog of issue #5974. Could you please check this dialog if it works well? Thanks

2021-01-01 12:28 UTC, rdstern commented
@N-thony that's great.  I'll check.

2021-01-04 09:16 UTC, rdstern commented
This is great and it is working already!  Well done.
a) Could you change the control currently called Data Split Methods, Type into Facet By (Optional):  And put it on the right-hand side below the other 2 controls.  It can take up to 2 factors, so perhaps make it into a multiple receiver.  
b) Move up the Plot Options button, so it is in the same position as in the other plotting dialogues - so just below the data selector.  Until it is active it should be disabled.
c) I tried bins.  Can you make the default into 31, which I think is the default in the function.  I am not sure what min.bin is doing, but make the default 10 for now.
d) It will be good to implement the alternative key positions and number of lines.  I leave to you whether rthis needs the sub-dialogue or can be added to the main dialogue.
e) Now a computing problem for you.  It (by default) saves a lattice graph.  It is saved in lasg_graph is you don't give it a separate name.  But it can be huge!  So for the dodoma data in the R-Instat library I used tmax and tmin and did the fraph by month.  Then the file (with this one graph added to the R-Instat data book) becomes 219 mbytes.  It is less than 2 mbytes otherwise.  I wonder what can be done about this.  It is slowing my machine down and I have a pretty fast machine!

2021-01-05 19:21 UTC, N-thony commented
@rdstern I solved the issues you raised yesterday.  Could you confirm that the issues are resolved?
For instance, I have added key positions to the main dialog. I may add the sub dialog if you request more flexibility in the graph.

2021-01-10 07:39 UTC, shadrackkibet requested changes

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrReceiverObservations.bAutoFill = True
I think you do not need to autofill here.

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrReceiverObservations.SetParameter(New RParameter("obs", 0))
Check your parameter positions here, these two can't have the same position.

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        'ucrReceiverType.SetClimaticType("station")
Remove it? Otherwise, comment on why this is still needed.

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetParameter(New RParameter("bins", 3))
Two controls with the same parameter?

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ' ucrChkBin.SetRDefault("TRUE")
Remove?

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudMinBin.SetParameter(New RParameter("min.bin", 4))
Also here.

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ' ucrChkMinBin.SetRDefault("TRUE")
Remove?

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudKeyColumns.SetParameter(New RParameter("key.columns", 5))
Also here.

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ' dctLegendPosition.Add("None", Chr(34) & "none" & Chr(34))
Remove?

2021-01-10 07:39 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +
You need to set the assignment to `last_graph` here so that the save control resets properly i.e it is unchecked when the dialog is reset.

2021-01-10 07:46 UTC, shadrackkibet commented on instat/static/InstatObject/R/Rsetup.R
> +  packs_to_load <- c("plyr", "dplyr", "ggplot2", "ggthemes", "svglite", "ggfortify", "PCICt", "sp", "ggmosaic", "wakefield", "circular", "latticeExtra")
Add a comment above explaining why `latticeExtra` need to be loaded.

2021-01-10 08:04 UTC, shadrackkibet commented
> b) Move up the Plot Options button, so it is in the same position as in the other plotting dialogues - so just below the data selector. Until it is active it should be disabled.

Make sure this button is disabled now since it is not yet working!

> c) I tried bins. Can you make the default into 31, which I think is the default in the function. I am not sure what min.bin is doing, but make the default 10 for now.

This can be a vector e.g `c(10,20)` therefore this should be an input textbox so that it allows the user to type in a vector. Perhaps you need to add a tooltip to explain this and also give an example to guide the user.

2021-01-10 08:22 UTC, shadrackkibet commented
Comment on design and TestOk.

![image](https://user-images.githubusercontent.com/26301973/104117639-dceeb100-5333-11eb-9a08-7e6eada59c8c.png)

- Align labels properly with corresponding receivers.
- Rename checkboxes to **Key Position** and **Key Column(s)** .
- When `bins, min.bin` and `key columns` are empty as shown in the figure below, Ok is enabled. On click Ok it doesn't give an error but the output code is as shown below.
```
# Code generated by the dialog, Conditional Quantile Plot
Dagoretti_JKIA <- data_book$get_data_frame(data_name="Dagoretti_JKIA")
conditionalquantile2 <- openair::conditionalQuantile(obs="TMPMAX", mod="tmax_MERRA2", type="station", mydata=Dagoretti_JKIA, bins=, min.bin=, key.columns=, key.position="bottom")
data_book$add_graph(graph_name="conditionalquantile2", graph=conditionalquantile2, data_name="Dagoretti_JKIA")
```
![image](https://user-images.githubusercontent.com/26301973/104117896-d9f4c000-5335-11eb-9a3a-62d117398d03.png)

To sort out these you need to set Rdefaults.

2021-01-10 15:55 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetParameter(New RParameter("bins", 3))
Yes, I need to set the same parameter to the ucrChk because it controls if the parameter is added or removed

2021-01-10 16:09 UTC, N-thony commented
@shadrackkibet I solved the issues you raised a couple of hours ago. Could you confirm that the issues are resolved? Thanks.

2021-01-10 16:21 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetParameter(New RParameter("bins", 3))
The NUD should pass the parameter while the checkbox is only used to hide/unhide the NUD via linking controls.

2021-01-10 16:29 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
Did you set the R defaults?

2021-01-10 16:31 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
I have added conditions in TestOk to avoid that.

2021-01-10 16:33 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetParameter(New RParameter("bins", 3))
Okay, but this will not allow that when the dialog is closed and ucrChk  is checked and open, ucrChk becomes unchecked.
I would like to see the code where this is done so I can understand how it works.

2021-01-10 16:33 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
You need to set R defaults as well.

2021-01-10 16:47 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetParameter(New RParameter("bins", 3))
You need to set conditions to ensure that checkboxes retain state on reopening. In this case you should use `.AddParameterPresentCondition`. for example

```
    ucrChkBin.AddParameterPresentCondition(True, "bins")
    ucrChkBin.AddParameterPresentCondition(False, "bins", False)
```

2021-01-10 16:51 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetParameter(New RParameter("bins", 3))
Okay

2021-01-10 17:44 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        If Not ucrReceiverObservations.IsEmpty() AndAlso Not ucrReceiverPredictions.IsEmpty() AndAlso ucrSavePlot.IsComplete AndAlso ucrNudBin.GetText <> "" AndAlso ucrNudKeyColumns.GetText <> "" And
The corresponding checkboxes should be included in TestOk. Otherwise, if these Nuds and input are empty and the checkboxes are not checked OK will not be enabled which might be confusing to the user.

2021-01-10 17:56 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        If Not ucrReceiverObservations.IsEmpty() AndAlso Not ucrReceiverPredictions.IsEmpty() AndAlso ucrSavePlot.IsComplete AndAlso ucrNudBin.GetText <> "" AndAlso ucrNudKeyColumns.GetText <> "" And
Correct! Thanks

2021-01-10 18:29 UTC, N-thony commented
@shadrackkibet I solved the issues you raised a couple of hours ago. Could you confirm that the issues are resolved? Thanks.

2021-01-11 06:26 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +            clsConditionalQuantileFunction.AddParameter("min.bin", "c(" & ucrInputMinBin.GetText() & ")")
- This parameter is passed automatically by setting Rcode and manually here which contradicts the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle. Could you ensure this done only once? If not I suggest you add a comment here.
- What does the else to this do? should you remove the parameter? should it be a developer error? 
- Always add parameter positions!

2021-01-11 06:26 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
I still can't see where this is done. If you decided otherwise then you should explain why!

2021-01-11 06:42 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +            clsConditionalQuantileFunction.AddParameter("min.bin", "c(" & ucrInputMinBin.GetText() & ")")
min.bin is already added automatically, so I have set the condition if in case the user enters min.bin of the length of two e.g min.bin = c(10,20).

2021-01-11 07:08 UTC, N-thony commented
@shadrackkibet I solved the issues you raised a couple of minutes ago. Could you confirm that the issues are resolved? Thanks.

2021-01-11 07:42 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
`ucrNudBin.SetRDefault(31)`

2021-01-11 08:12 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
Setting the Rdefault to to Nud doesn't allow the ucrChk to keep the state if you close and open the dialog when they are checked. Remember that I have set the condition to the ucrChk as follow:
    ucrChkBin.AddParameterPresentCondition(True, "bins")
    ucrChkBin.AddParameterPresentCondition(False, "bins", False)

2021-01-11 12:59 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +            clsConditionalQuantileFunction.AddParameter("min.bin", ucrInputMinBin.GetText(), iPosition:=5) 'this is min.bin is length of two e.g min.bin = c(10,20)
Why the same comment twice?

2021-01-11 13:00 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +            clsConditionalQuantileFunction.AddParameter("min.bin", ucrInputMinBin.GetText(), iPosition:=5) 'this is min.bin is length of two e.g min.bin = c(10,20)
Oh, sorry. It was cc.

2021-01-11 13:02 UTC, shadrackkibet commented
When you reopen the dialog `min.bin` checkbox is always checked. The dialog should always retain its state on reopening.

2021-01-11 13:09 UTC, N-thony commented
> When you reopen the dialog `min.bin` checkbox is always checked. The dialog should always retain its state on reopening.

I don't know but mine works well. closing.opening min.bin checkbox keeps the state.

2021-01-11 13:14 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
That is right. Setting R default ensures that the parameter is hidden when its value is the set R default. This is useful because it is not necessary to pass parameters when defaults are defined internally in the R function. For example to following lines of code give the same output. 

```
openair::conditionalQuantile(mydata=Dagoretti_JKIA, obs="prcp_CHIRPS", mod="est_prcp_CHIRPSv2", type="station")
```

```
openair::conditionalQuantile(mydata=Dagoretti_JKIA, obs="prcp_CHIRPS", mod="est_prcp_CHIRPSv2", type="station", bins=31, min.bin=c(10,20), key.columns=2, key.position="bottom")
```

This means it is not necessary to pass `bins, min.bin, key.columns, key.position` with default values. I hope this makes sense.

2021-01-11 13:19 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
Exact!

2021-01-11 13:20 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputMinBin.SetParameter(New RParameter("min.bin", 5))
This parameter is added into the R function manually elsewhere. Why is this needed?

2021-01-11 13:22 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
Do you now understand why you need to set R defaults?

2021-01-11 13:25 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputMinBin.SetParameter(New RParameter("min.bin", 5))
Oh yes, this correct!

2021-01-11 13:35 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputMinBin.bAllowNonConditionValues = True
Why are these two lines of code needed?

2021-01-11 13:40 UTC, shadrackkibet commented
As a principle please make sure that you are always able to explain what the code does and why each line of code you write is needed. If anything doesn't make sense to you always ask!

2021-01-11 14:54 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrNudBin.SetMinMax(1, Integer.MaxValue)
Yap

2021-01-11 17:26 UTC, N-thony commented
@shadrackkibet I solved the issues you raised a couple of hours ago. Could you confirm that the issues are resolved? Thanks.

2021-01-11 17:57 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputLegendPosition.SetRDefault("bottom")
chr(34)?

2021-01-11 18:19 UTC, N-thony commented
@shadrackkibet I solved the issues you raised a couple of minutes ago. Could you confirm that the issues are resolved? Thanks.

2021-01-13 06:12 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputLegendPosition.bAllowNonConditionValues = True
Can you explain why should non-conditioned values be allowed here?

2021-01-13 06:24 UTC, shadrackkibet commented
I also think the disabled **Plot options** should be called **Conditional Quantile Options** because this will be a special sub dialog with options only used in this dialog.

2021-01-13 06:25 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputLegendPosition.bAllowNonConditionValues = True
To allow the control value to be set to a value that is not one of the valid values predefined in the dictionary.

2021-01-13 06:28 UTC, N-thony commented
> I also think the disabled **Plot options** should be called **Conditional Quantile Options** because this will be a special sub dialog with options only used in this dialog.

Yes, you are right!

2021-01-13 06:34 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputLegendPosition.bAllowNonConditionValues = True
But only options specified in the dictionary are allowed here. Isn't that the reason why this input Combobox is non-editable?

2021-01-13 07:06 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputLegendPosition.bAllowNonConditionValues = True
> But only options specified in the dictionary are allowed here. Isn't that the reason why this input Combobox is non-editable?

Yes, I see your point.

2021-01-13 07:15 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputLegendPosition.bAllowNonConditionValues = True
Therefore this should be removed.

2021-01-13 07:35 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrInputLegendPosition.bAllowNonConditionValues = True
Done, thanks!

2021-01-13 07:47 UTC, shadrackkibet commented
Looks better now. @lloyddewit, please proceed with the necessary steps.

2021-01-13 08:00 UTC, lloyddewit commented
@shadrackkibet thank you for the review
@rdstern Please could you test that your comments from 04 Jan above are now resolved? thanks

2021-01-13 09:37 UTC, rdstern commented
@N-thony and @shadrackkibet well done as this seems to be working well now.
I have tried most of the options in the dialogue and don't seem to be able to break it.
Importantly I also note that the graph icon on the toolbar is working, so we can (I assume) now display Lattice graphs as well as ggplot graphs in the R-viewer through the toolbar icon.
So the changes that I suggest are purely cosmetic.  
To me the dialogue breaks (slightly) with an important principle in our proposed use of R-Instat.  R-Instat is designed to promote good statistical practice - even for inexperienced users.  One aspect of the good practice is that you are tempted to concentrate on important points when using a dialogue.  This includes using facets etc.
Now currently, when I use this dialogue I am drawn to the options on the left-hand side.  So, I am likely to ask "How many bins should I use, and what does this minimum number mean and what on earth is c(10,20) here.  

They are not important and so should not distract the user.  

I need some help here, because I am not sure what the "Minimum number of points" does?  Assuming we keep that option on the main dialogue, then do we really need to be able to alter both options?  If so, then it could become 2 up-down controls.  

I therefore checked back to the guide and there seems to be an important new (I assume new - or perhaps I missed it before) function called conditionalEval that extends the use of the conditional quantiles function.  So, let's think short-term and longer-term.  In the longer term I note that the chapter in the book is still called conditional quantiles, so our menu remains fine.  Then I suggest we will soon have 2 radio buttons at the top with a label `Conditional`, and then the first button is `Quantiles` and the second is `Evaluation`.

This is for a new issue and very interesting, but not urgent.

For now it would be good to get the current version merged as soon as possible.  So I suggest minimal changes as follows:

a) Change `Bins` to `Histogram Bins`  
b) Make the Minimum number control invisible for now.
c) Possibly add the buttons at the top, as described above, to show our intentions to add the Evaluation function later - with the Evaluation button visible, but disabled.
d) Write a new issue to add the Conditional Evaluation function once @N-thony has time.

Then let's merge it.

2021-01-13 20:53 UTC, N-thony commented
@rdstern I solved the comments about the small changes in the design. Could you please check it? Thanks

2021-01-13 21:00 UTC, N-thony commented
@rdstern I solved the comments about the small changes in the design. Could you please check it? Thanks

2021-02-03 12:40 UTC, N-thony commented
@rdstern In addition of the conditionalQuantile function, I have implemented the conditionalEval function. Could you please review? Thanks.

2021-02-03 13:54 UTC, rdstern reviewed
@N-thony The controls on the left were empty - I am not sure what they should have contained?  And I was unable to see what happens, because Ok wasn't enabled.
Could you also tell me what data you are using to test?

2021-02-03 13:59 UTC, N-thony commented
> @N-thony The controls on the left were empty - I am not sure what they should have contained? And I was unable to see what happens, because Ok wasn't enabled.
> Could you also tell me what data you are using to test?

Oh sorry, I set the condition also to the Statistic Receiver. I think you need to fill this Receiver too.

2021-03-16 14:21 UTC, N-thony commented
@rdstern thanks for your comment above and the quick chat. This is now ready. Please could you test?

2021-03-22 06:47 UTC, maxwellfundi commented
@shadrackkibet @rdstern  Kindly this is ready for your re-review.

2021-03-22 07:15 UTC, rdstern requested changes
@N-thony this is potentially looking very good indeed.  But I couldn't test it properly, because of an issue that needs to be fixed before you proceed.
It isn't just your problem, but this dialogue has brought it to a head.
I found elsewhere that a lattice graph (at least one generated through openair) can be very large.  A simple graph changed the file size in R-Instat from 2mbytes to 200 mbytes.  The graphs here are complicated to the extent that the automatic backup doesn't work, and I can't save the file, because of the inclusion of the graph.  
I don't know what's happening here - is it trying to save a bitmap for example.
This is a bit peripheral, but needs a serious investigation before we can move on.
You may wish to investigate quickly, but don't spend more than (say) 15 minutes, before asking others - perhaps @volloholic ?
@shadrackkibet is also testing, but needs to be aware of this issue first.

2021-03-23 09:28 UTC, rdstern commented
I start with the quantiles
a) It is looking very good
b) In the minimum number of points could you make it an up-down control.  Perhaps minimum 5 and no maximum.  Default 10.
c) Please also check that the value is registered in the command if it isn't the default?  I don't know what the default is?
d) Please change the label Key Position to Legend Position.  
e) Move Key Columns control to the same row as the Legend Position.  Call it just Columns.  Also if the Legend Position is set to None, then it is made not visible.

I still need to check the Eval in more detail.  It have me the following error when I tried a simple default with just the 2 variables and nothing in either multiple receiver.
![image](https://user-images.githubusercontent.com/11226469/112124018-ce393b80-8bb9-11eb-9c04-8458bc529a32.png)

I need also to check with @maxwellfundi about @shadrackkibet taking over completion of this and the Taylor diagram.  @N-thony has done well getting this far, but now has too many other priorities.

2021-03-27 08:36 UTC, N-thony commented
@rdstern this is ready. Could you test? Thanks

2021-03-27 09:04 UTC, rdstern requested changes
@N-thony thanks

The one item remaining is the Facet multiple receiver.  Can you change it so it also permits factors.

2021-03-27 09:46 UTC, N-thony commented
@rdstern thanks for your comment. I think it's resolved. Could you re-test now?

2021-03-27 10:04 UTC, rdstern submitted a review, later dismissed
@N-thony great, thanks.
@dannyparsons and @lloyddewit This dialogue has tow parts, with different functions, each from openair.
We have now disabled the Eval, so the plotting can be merged.  Then I hope we can proceed quickly to check and add the Eval part later.

2021-03-29 08:52 UTC, lloyddewit requested changes

2021-03-29 08:52 UTC, lloyddewit commented on instat/dlgConditionalQuantilePlot.vb
> +    Private iBaseMaxY
```suggestion
    Private iBaseMaxY As Integer
```

2021-03-29 08:52 UTC, lloyddewit approved these changes

2021-03-29 08:54 UTC, lloyddewit commented
@rdstern I made one tiny change that should not affect the functionality. Please could you approve again? thanks

2021-03-29 09:06 UTC, rdstern approved these changes
I am approving, because what I found is trivial and I don't want to slow the process now.
I used the default, which has legend as None.  But it then does the default, which is legend = Bottom.
That can be changes within the next issue - which is mainly for the Evaluation part

2021-03-29 09:40 UTC, lloyddewit commented
@shadrackkibet Thank you for all the reviewing you did for this PR. You requested changes so you also need to approve. Please could you approve and merge? thanks

2021-03-29 11:09 UTC, shadrackkibet approved these changes

2021-03-29 11:10 UTC, merged