Adding pull down control and Fixing bugs
africanmathsinitiative/R-Instat pull request #6149
Opened 2021-01-06 16:30 UTC by N-thony

2021-01-06 17:28 UTC, dannyparsons commented
@N-thony I have edited the title of the PR so that's its more specific and descriptive. We try to use the PR titles in the release notes so please make them descriptive by mentioning the dialog name and the changes in a few words.

2021-01-06 17:29 UTC, N-thony commented
> @N-thony I have edited the title of the PR so that's its more specific and descriptive. We try to use the PR titles in the release notes so please make them descriptive by mentioning the dialog name and the changes in a few words.

Thanks

2021-01-07 07:21 UTC, N-thony commented
Added pull-down control for facet options and bug fixes. This solves issue #6106
@africanmathsinitiative/developers and @rdstern this is ready for review. Thanks.

2021-01-07 08:23 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2021-01-07 09:42 UTC, Ivanluv commented
reviewing this now

2021-01-07 13:42 UTC, Ivanluv commented on instat/dlgPICSARainfall.vb
> +                clsFacetOperator.AddParameter("wrap", iPosition:=0)
This  parameter  does not to have a parameter value

2021-01-07 14:25 UTC, N-thony commented
@Ivanluv I solved the issue you raised minutes ago. Could you confirm that the issue is resolved? Thanks.

2021-01-08 06:55 UTC, Ivanluv commented on instat/dlgPICSARainfall.vb
>      Private Sub XAxisDataTypeCheck()
This function is also not being referenced anywhere in you code. Do you still need it?

2021-01-08 06:55 UTC, Ivanluv commented on instat/dlgPICSARainfall.vb
> +                clsGroupByFunction.AddParameter("variable", bIncludeArgumentName:=False, iPosition:=0)
this parameter does not have a parameter values

2021-01-08 06:55 UTC, Ivanluv commented on instat/dlgPICSARainfall.vb
>      Private Sub ucrReceiverX_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrReceiverX.ControlValueChanged
could you remove this sub since its no longer being used

2021-01-08 07:14 UTC, N-thony commented
@Ivanluv I solved the issues you raised minutes ago. Could you confirm that the issues are resolved? Thanks.

2021-03-16 11:27 UTC, Ivanluv commented
@lloyddewit the code looks okay from my end

2021-03-16 13:31 UTC, lloyddewit commented
@rdstern please could you test? thanks

2021-03-16 19:43 UTC, rdstern approved these changes
Great.  Both the enhancement and the addition of mean lines seems to work fine!

2021-03-17 09:30 UTC, maxwellfundi commented on instat/dlgPICSARainfall.vb
> +                clsGroupByFunction.AddParameter("variable", bIncludeArgumentName:=False, iPosition:=0)
I am concerned about this parameter that has no value, if its not needed can it be removed? 
While @rdstern  has tested this and approved it, when should this parameter be added @N-thony ?

2021-03-17 09:45 UTC, rdstern commented
@maxwellfundi I just comment on our scheme, because you are doing a perfect job here!  I only test the functionality and not the code.  From my point of view it seemed to work ok.

Then @lloyddewit or shadrack or you, or Danny  check the code.  That may be before me or after me.  If you find problems then the pull request changes and my approval becomes null.  I then look again after your suggestions are satisfied.

2021-03-17 10:06 UTC, N-thony commented on instat/dlgPICSARainfall.vb
> +                clsGroupByFunction.AddParameter("variable", bIncludeArgumentName:=False, iPosition:=0)
@maxwellfundi the bug was due the duplication of this parameter variable in the group_by function when you have more than 1 station

2021-03-17 11:49 UTC, lloyddewit requested changes

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +    Private strNone As String = "None"
Make all these strings `ReadOnly`?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        Dim strChangedText As String = ""
```suggestion
```

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        If bUpdateComboOptions Then
Follow the 'happy path stays left` principle (https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88). So more readable if we write:
```
        If Not bUpdateComboOptions Then
            Exit Sub
        End If
```

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        Dim strTemp As String = ""
```suggestion
```

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        If Not bUpdatingParameters Then
Invert condition so that 'happy path stays left'

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +    Private dctComboReceiver As New Dictionary(Of ucrInputComboBox, ucrReceiverSingle)
This `Dictionary` only contains a single value. Could we remove this data member and just reference to `ucrReceiverFacetBy` instead?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +
Remove this line?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +                For Each ucrInputTemp As ucrInputComboBox In dctComboReceiver.Keys
The dictionary only has one entry. Remove this loop?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        For Each ucrInputTemp As ucrInputComboBox In dctComboReceiver.Keys
The dictionary only has one entry. Remove this loop?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +            For Each kvpTemp As KeyValuePair(Of ucrInputComboBox, ucrReceiverSingle) In dctComboReceiver
The dictionary only has one entry. Remove this loop?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +                    If Not strChangedText = strFacetCol AndAlso Not strChangedText = strFacetRow AndAlso Not ucrInputTemp.Equals(ucrChangedControl) AndAlso ucrInputTemp.GetText() = strChangedText The
make more readable by adding new lines between conditions

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +                    If strChangedText = strFacetWrap AndAlso ucrInputTemp.GetText = strFacetRow OrElse strChangedText = strFacetRow AndAlso ucrInputTemp.GetText = strFacetWrap OrElse strChangedText =
make more readable by adding new lines between conditions.
Also, the mix between `AndAlso` and `OrElse` is confusing. Add brackets to clarify the precedence?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        For Each ucrInputTemp As ucrInputComboBox In dctComboReceiver.Keys
The dictionary only has one entry. Remove this loop?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +            If strTemp = strXAxis Then
Replace this 'ElseIf` structure with `Select`

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        Dim strText As String
delete?

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +                    End If
replace with select

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +                If strText = strFacetWrap OrElse strText = strFacetCol OrElse strText = strFacetRow AndAlso Not kvpTemp.Value.IsEmpty Then
remove first 3 conditions

2021-03-17 11:49 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +                clsGroupByFunction.AddParameter("variable", bIncludeArgumentName:=False, iPosition:=0)
@N-thony Sorry, I still don't understand why this parameter does not have a value, please could you explain? or we can quickly discuss verbally) thanks

2021-03-17 13:18 UTC, N-thony commented
@maxwellfundi @lloyddewit thanks for your comments above. I think to have resolved them.

2021-03-17 14:09 UTC, lloyddewit commented
@N-thony thank you for the changes. However, I still see a number of unresolved comments. Please resolve and let me know when you are done.
If my comments are not clear then let me know and we can discuss.
Thanks

2021-03-17 14:28 UTC, N-thony commented on instat/dlgPICSARainfall.vb
> +        Dim strText As String
@lloyddewit we can discuss.

2021-03-22 05:10 UTC, N-thony commented
@lloyddewit thanks for your comments. I think have resolved them.

2021-03-22 05:40 UTC, N-thony commented
@lloyddewit thanks for your comments. I think have resolved them.

2021-03-23 11:16 UTC, lloyddewit requested changes

2021-03-23 11:16 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        Next
Does this replacement code work and allow you to remove `dctComboReceiver`?
```suggestion
        ucrReceiverFacetBy.SetRCode(Nothing)
        Select Case ucrInputStation.GetText()
            Case strXAxis
                ucrReceiverFacetBy.ChangeParameterName("x")
                ucrReceiverFacetBy.SetParameterIncludeArgumentName(False)
                ucrReceiverFacetBy.SetRCode(clsAsFactorFunction)
                clsRaesFunction.AddParameter("x", clsRFunctionParameter:=clsAsFactorFunction)
            Case strColour
                ucrReceiverFacetBy.ChangeParameterName("color")
                ucrReceiverFacetBy.SetParameterIncludeArgumentName(True)
                ucrReceiverFacetBy.SetRCode(clsRaesFunction)
            Case strFacetWrap
                ucrReceiverFacetBy.ChangeParameterName("wrap" & ucrInputStation.Name)
                ucrReceiverFacetBy.SetRCode(clsFacetOperator)
            Case strFacetCol
                ucrReceiverFacetBy.ChangeParameterName("col" & ucrInputStation.Name)
                ucrReceiverFacetBy.SetRCode(clsFacetColOp)
            Case strFacetRow
                ucrReceiverFacetBy.ChangeParameterName("row" & ucrInputStation.Name)
                ucrReceiverFacetBy.SetRCode(clsFacetRowOp)
        End Select
```

2021-03-23 11:16 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +    Private dctComboReceiver As New Dictionary(Of ucrInputComboBox, ucrReceiverSingle)
Please see comment on line 688

2021-03-23 11:16 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +
Please see comment on line 688

2021-03-23 11:58 UTC, N-thony commented
@lloyddewit thanks for your comment. I removed the dictionary and it works.

2021-03-23 13:28 UTC, lloyddewit submitted a review, later dismissed

2021-03-23 13:30 UTC, lloyddewit commented
@rdstern There have been quite a few code changes since your last test, please could you test again? thanks

2021-03-23 16:18 UTC, rdstern requested changes
@N-thony the main issue of the bug seems to have gone.  Great.
1. In the options for the station to be a facet I think you can delete x-axis and probably also colour axis.
2. Try - with the sample data set mentioned - to change the option for the trpe of facet.  I made it Wrap.  Then it also deleted the year from the x-axis.  They should not be connected in this way.

2021-03-24 14:44 UTC, maxwellfundi commented
@N-thony there requested changes here, could you make these a priority?

2021-03-24 14:49 UTC, N-thony commented
> @N-thony there requested changes here, could you make these a priority?

Okay @maxwellfundi. I need to check this first with @rdstern.

2021-03-25 06:51 UTC, N-thony commented
@rdstern thanks for your comment above. I think have resolved it. Could you test the change?

2021-03-25 07:57 UTC, rdstern approved these changes
@lloyddewit the problems I had are now fixed.

2021-03-25 10:33 UTC, lloyddewit approved these changes

2021-03-25 10:33 UTC, merged