Improvements to the one variable
africanmathsinitiative/R-Instat pull request #6150
Opened 2021-01-08 09:04 UTC by Ivanluv

This is from PR #6004

2021-01-08 11:29 UTC, lloyddewit reviewed
@Ivanluv thanks for the updates, there's just a couple of open questions about developer errors

2021-01-08 11:29 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +        End If
Add an `Else` with a developer error?
There's an example in `dlgCalculator.vb`:

`MsgBox("Developer error: there is no Calculator keyboard called" & Chr(34) & strNewDefaultKeyboard & Chr(34) & vbNewLine & "Default keyboard will be selected.")`

2021-01-08 11:29 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +            End Select
Add `Else` with developer error?

2021-01-10 08:36 UTC, lloyddewit approved these changes

2021-01-10 08:41 UTC, lloyddewit commented
@rdstern you already tested this new functionality under PR #6004. There are relatively small changes since then. Please could you retest and approve? thanks

2021-01-10 10:15 UTC, rdstern commented
@Ivanluv sorry - this is a complicated dialogue.  I am hoping to get it merged, though we will continue to find combinations that don't work.  But this one could usefully be fixed now.

I used the standard survey data set and the default test - which is binomial and variety - which is a factor.  It then gives the levels of the factor.  But this command also works for numeric variables.  So the levels control should remain open and the successive values become the levels.  You don't need to, but may wish to do an as-factor behind the scenes - perhaps Shadrack can help.  Currently it doesn't work well as you see here.

When I changed to fert from the variety it still kept the success="NEW" from the variety - so had zero.
When I tried again it allowed and correctly had zero - lowest level - which is great.  But I can't change the "level".

```
# Code generated by the dialog, One Variable Fit Model
fert <- data_book$get_columns_from_data(data_name="survey", col_names="fert")
last_model <- mosaic::binom.test(x=fert, p=0.5, conf.level=0.95, ci.method="Clopper-Pearson", success="NEW")
data_book$add_model(model_name="last_model", model=last_model, data_name="survey")
data_book$get_models(data_name="survey", model_name="last_model")

data:  fert  [with success = NEW]
number of successes = 0, number of trials = 36, p-value = 3e-11
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.00000 0.09739
sample estimates:
probability of success 
                     0 

rm(list=c("last_model", "fert"))

# Code generated by the dialog, One Variable Fit Model
fert <- data_book$get_columns_from_data(data_name="survey", col_names="fert")
last_model <- mosaic::binom.test(x=fert, p=0.5, conf.level=0.95, ci.method="Clopper-Pearson")
data_book$add_model(model_name="last_model", model=last_model, data_name="survey")
data_book$get_models(data_name="survey", model_name="last_model")

data:  fert  [with success = 0]
number of successes = 9, number of trials = 36, p-value = 0.004
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.1212 0.4220
sample estimates:
probability of success 
                  0.25 
```

2021-01-11 14:20 UTC, Ivanluv commented
Am still working on having the levels for numeric columns

2021-01-12 13:43 UTC, Ivanluv commented
@rdstern could you look at this again

2021-01-14 07:45 UTC, rdstern submitted a review, later dismissed
@Ivanluv I am approving this, now because it works fine - at least the bit I checked, with binomial.
However, it does have a small problem to me in that the fert - that is a variable that could be either numeric or a factor is silently converted into a factor for the binomial - and then it remains as a factor afterwards.  I assume you need to make it a factor for your code?  I tried with fertgrp as character and it leaves it as character.  
I then tried to analyse fert with a t-test and it gives an error, because fert is now a factor.  
So, unless you need it to become a factor, then it should be left as numeric.  If it does need, for your code to become a factor, then ideally you return it to its previous type later, or you make a comment in the output window that the variable is now converted to factor.

2021-01-14 14:13 UTC, rdstern submitted a review, later dismissed
@lloyddewit this is now working as far as I can see.  Great if it can be accepted

2021-01-20 12:00 UTC, lloyddewit requested changes
@Ivanluv Thanks, this looks good. I only had a few small suggestions

2021-01-20 12:17 UTC, Ivanluv commented on instat/dlgOneVarFitModel.vb
> +        ucrInputSuccess.SetText(lstFactor(0))
I have added a developer error, Stating there are no factor levels to be displayed

2021-01-20 12:21 UTC, Ivanluv commented on instat/dlgOneVarFitModel.vb
> +        If ucrInputComboTests.GetText = "---------------------" Then
this was to be used as a separator for tests within the Test combo box. I don't know is a constant will do the same

2021-01-22 08:30 UTC, lloyddewit commented on instat/dlgOneVarFitModel.vb
> +        If ucrInputComboTests.GetText = "---------------------" Then
Could you declare a constant (e.g. `Private ReadOnly strSeparator As String = "---------------------"`) and then use this constant here, and on line 95?

2021-01-22 09:37 UTC, Ivanluv commented on instat/dlgOneVarFitModel.vb
> +        If ucrInputComboTests.GetText = "---------------------" Then
Done

2021-01-22 09:43 UTC, lloyddewit approved these changes

2021-01-22 09:45 UTC, lloyddewit commented
@rdstern there are small code changes since your last approval. These should not have changed the functionality (in theory!). You may still want to do a small sanity check before approving again :) thanks

2021-01-24 09:46 UTC, shadrackkibet commented
@lloyddewit I see this PR has two approvals already. Is there something else needed? or you just forget to merge?

2021-01-26 08:35 UTC, merged