Cimulative/Exceedance Graph: Added points option
africanmathsinitiative/R-Instat pull request #6151
Opened 2021-01-08 13:41 UTC by N-thony

Added points option. This solves issue #6111
@africanmathsinitiative/developers and @rdstern this is ready for review. Thanks.

2021-01-10 08:28 UTC, lloyddewit commented
@shadrackkibet please could you review? thanks

2021-01-10 08:58 UTC, shadrackkibet requested changes

2021-01-10 08:58 UTC, shadrackkibet commented on instat/dlgCumulativeDistribution.vb
> +        ' ucrChkIncludePoints.SetParameter(New RParameter(""))
Remove?

2021-01-10 08:58 UTC, shadrackkibet commented on instat/dlgCumulativeDistribution.vb
> +        clsBaseOperator.AddParameter("labs", clsRFunctionParameter:=clsLabsFunction)
Parameter position?

2021-01-10 09:02 UTC, shadrackkibet commented
The output graph is okay. However, ` ggplot2::stat_ecdf(pad=FALSE) ` is added twice when Include points is not checked.

```
last_graph <- ggplot2::ggplot(data=Dagoretti_JKIA, mapping=ggplot2::aes(x=PRECIP, colour=station)) + ggplot2::stat_ecdf(pad=FALSE) + ggplot2::stat_ecdf(pad=FALSE) + theme_grey() + labs(y=NULL) + ggplot2::scale_y_continuous(breaks=seq(from=0, to=1, by=0.25))
```

2021-01-10 16:52 UTC, N-thony commented
@shadrackkibet I solved the issues you raised a couple of hours ago. Could you confirm that the issues are resolved? Thanks.

2021-01-10 17:22 UTC, shadrackkibet commented
Looks good. Thanks.

2021-01-10 17:23 UTC, shadrackkibet commented on instat/dlgCumulativeDistribution.vb
> +        clsBaseOperator.AddParameter("labs", clsRFunctionParameter:=clsLabsFunction)
I can't see this change.

2021-01-10 17:25 UTC, N-thony commented on instat/dlgCumulativeDistribution.vb
> +        clsBaseOperator.AddParameter("labs", clsRFunctionParameter:=clsLabsFunction)
Oh okay, thanks, doing it.

2021-01-10 18:35 UTC, N-thony commented
@shadrackkibet I solved the issues you raised a couple of hours ago. Could you confirm that the issues are resolved? Thanks.

2021-01-11 08:31 UTC, lloyddewit approved these changes

2021-01-11 08:33 UTC, lloyddewit commented
@shadrackkibet thank you for the fast review :). As far as I could see, all your comments were resolved. If I misunderstood, then please let me know
@rdstern I think this is now ready for your testing

2021-01-15 19:34 UTC, rdstern approved these changes
Great

2021-01-19 09:49 UTC, merged