Improving Taylor Diagram Dialog
africanmathsinitiative/R-Instat pull request #6157
Opened 2021-01-13 07:41 UTC by N-thony

Improved the design of the Taylor Diagram dialog and small changes in the code. This fixes the comments in issues #5885 
@africanmathsinitiative/developers this is ready to review. Thanks.

2021-01-13 08:08 UTC, lloyddewit commented
@shadrackkibet please could you review? thanks

2021-01-13 09:11 UTC, shadrackkibet commented on instat/dlgTaylorDiagram.Designer.vb
> +        Me.lblEstimated.Name = "lblEstimated"
This label seems to have disappeared.

2021-01-14 06:40 UTC, shadrackkibet commented on instat/dlgTaylorDiagram.Designer.vb
> +        Me.lblEstimated.Name = "lblEstimated"
This is what I get.

![image](https://user-images.githubusercontent.com/26301973/104553822-5b0cc980-564c-11eb-9118-47bbdae0e6aa.png)

2021-01-14 06:44 UTC, shadrackkibet commented
Please change the current receiver to be the observed receiver. This is because the station receiver is auto-filled.

2021-01-14 06:50 UTC, N-thony commented on instat/dlgTaylorDiagram.Designer.vb
> +        Me.lblEstimated.Name = "lblEstimated"
This is different from what I have but let me push again.

2021-01-14 07:02 UTC, N-thony commented
@shadrackkibet I have pushed my branch with small changes about the design requested in issue #5885

2021-01-14 07:14 UTC, shadrackkibet commented
What about the button to the sub dialog?

2021-01-14 08:14 UTC, N-thony commented
> What about the button to the sub dialog?

I have added the button and changed the current receiver to be the observed receiver.

2021-01-14 08:19 UTC, shadrackkibet requested changes

2021-01-14 08:19 UTC, shadrackkibet commented on instat/dlgTaylorDiagram.vb
> +        ucrReceiverSingleEstimated.SetIncludedDataTypes({"numeric"})
Change selector header here i.e ` ucrReceiverSingleEstimated.strSelectorHeading = "Numerics"`. Also do the same for other receivers where variables are restricted.

2021-01-14 08:19 UTC, shadrackkibet commented on instat/dlgTaylorDiagram.vb
>          ucrReceiverSingleObserved.SetIncludedDataTypes({"numeric"})
Also here `ucrReceiverSingleObserved.strSelectorHeading = "Numerics"`

2021-01-14 08:19 UTC, shadrackkibet commented on instat/dlgTaylorDiagram.vb
>          ucrReceiverMultipleGroup.bExcludeFromSelector = True
Also here `  ucrReceiverMultipleGroup.strSelectorHeading = "Factors & Characters"`

2021-01-14 08:30 UTC, shadrackkibet commented
That is all for now. Once this is done @lloyddewit please proceed with the next steps.

2021-01-14 11:05 UTC, N-thony commented
@lloyddewit I solved the comments above about the small change in the code. This is now ready for the next steps. Thanks.

2021-01-20 09:59 UTC, lloyddewit commented
@rdstern please could you test? thanks

2021-03-24 13:32 UTC, shadrackkibet approved these changes
Looks good. Over to you @rdstern @dannyparsons @lloyddewit

2021-03-25 08:23 UTC, shadrackkibet commented
I am now taking over this PR.

2021-03-25 10:08 UTC, lloyddewit commented
> 
> 
> I am now taking over this PR.

@shadrackkibet Thanks, I assume that you intend to make additional changes. Should we ait for these changes before we test/review?

2021-03-25 10:16 UTC, shadrackkibet commented
I now have a new PR (#6339) branched from this one, with additional changes and it is ready for review.

2021-03-25 10:24 UTC, lloyddewit commented
> 
> 
> I now have a new PR (#6339) branched from this one, with additional changes and it is ready for review.

Thank you for the explanation. Sorry, I should have looked at PR #6339 before I commented.

I'm not sure what to do next for this PR, it depends on your intention for PR #6339.
Should we:
- merge this PR now?
- close after PR #6339 merged?
- wait for this PR to merge automatically when PR #6339 merged?

Thanks for your advice

2021-03-25 12:16 UTC, shadrackkibet commented
Wait for this PR to merge automatically when PR #6339 is merged.

2021-03-26 16:11 UTC, merged