Declustering of extremes
africanmathsinitiative/R-Instat pull request #6164
Opened 2021-01-18 13:18 UTC by shadrackkibet

Fixes #4760  @rdstern this is ready for testing. 

NB: I am still investigating how we can obtain declustered data and save as desired.

2021-01-18 16:19 UTC, rdstern requested changes
@shadrackkibet this is looking very nice.  You have 10 as the default.  I wonder about making it higher, say 40?
More seriously, with the Ghana data, that I can attach it crashes with 10mm and an overflow exception.  I assume this is because it is processing too many observations.  It produces the summary, but gives the overflow when I stipulate the graph.

2021-01-19 13:35 UTC, shadrackkibet commented
@rdstern please check if the overflow exception problem is now fixed. I also changed the default threshold to 40 which appears to be high for temperature data therefore sometimes the user will get a bug when this threshold is higher than the data maximum.

2021-01-19 20:34 UTC, rdstern approved these changes
@shadrackkibet I am approving now, so this can be merged.  If you would like to make a small change now first then add a tooltip to the threshold value "Choose the threshold value within the data range at each station".

2021-01-20 09:40 UTC, lloyddewit commented
@Ivanluv Please could you peer review, thanks

2021-01-20 11:27 UTC, Ivanluv commented
@lloyddewit  am currently looking at this

2021-01-20 11:58 UTC, Ivanluv commented
@lloyddewit  this is okay

2021-01-22 09:34 UTC, lloyddewit approved these changes
@shadrackkibet Thanks, this looks good and I'm happy to approve. I had one question (doesn't affect approval)

2021-01-22 09:34 UTC, lloyddewit commented on instat/clsRLink.vb
> +                                                      End Sub, maxStackSize:=25000000)
@shadrackkibet I was curious where the 25MB figure comes from. Is this a recommendation from somewhere or a practical figure you derived by testing on your machine? I couldn't find much information about this online.

2021-01-22 09:34 UTC, merged

2021-01-22 09:59 UTC, shadrackkibet commented on instat/clsRLink.vb
> +                                                      End Sub, maxStackSize:=25000000)
This purely subjective. I had to test this using various datasets in R-Instat and this limit was never reached (at least on my machine). The change in `maxStackSize` was motivated by a solution [here](https://stackoverflow.com/questions/49623768/an-unhandled-exception-of-type-system-stackoverflowexception-occurred-in-rdotn). From this link they use 2.5MB but that didn't work with `ghana` dataset so I just added a `0` and that was never reached even using other datasets. The "ideal" value I thought it will work is `integer.MaxValue` but that crashed the software. 

I thought this change will impact the software negatively. I did test other dialogs after this change but I didn't find anything suspicious.

So this value is some sort of a practical figure derived by testing on my machine.

2021-01-26 08:30 UTC, lloyddewit commented on instat/clsRLink.vb
> +                                                      End Sub, maxStackSize:=25000000)
@shadrackkibet very interesting, thanks for explaining