Bug fix: calculation of dry months on rainfall quality control
africanmathsinitiative/R-Instat pull request #6179
Opened 2021-01-25 13:22 UTC by shadrackkibet

Fixes part of #6115 and #5017. @rdstern this fixes the problem with the calculation of dry months on rainfall quality control.

Notes

2021-01-26 07:10 UTC, shadrackkibet commented
@africanmathsinitiative/developers this is ready for review.

2021-01-26 08:24 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2021-01-26 08:31 UTC, Ivanluv commented
@lloyddewit  am looking at this now

2021-01-26 11:04 UTC, Ivanluv commented
@lloyddewit  the code looks okay from my end

2021-01-26 11:25 UTC, lloyddewit commented
@rdstern please could you test? thanks

2021-01-26 23:18 UTC, rdstern submitted a review, later dismissed
Excellent that this seems resolved.

2021-01-27 09:59 UTC, lloyddewit requested changes
@shadrack looks good, just a couple of small comments

2021-01-27 09:59 UTC, lloyddewit commented on instat/dlgClimaticCheckDataRain.vb
> +        If ucrReceiverElement.IsEmpty OrElse ((ucrChkLarge.Checked AndAlso ucrNudLarge.IsEmpty) OrElse (ucrChkSame.Checked AndAlso (ucrNudSame.IsEmpty OrElse ucrInputSameValue.IsEmpty)) OrElse (ucrCh
More readable if lines don't exceed 100 columns (but this issue is not caused by your change)
```suggestion
        If ucrReceiverElement.IsEmpty OrElse 
                ((ucrChkLarge.Checked AndAlso ucrNudLarge.IsEmpty) OrElse 
                (ucrChkSame.Checked AndAlso (ucrNudSame.IsEmpty OrElse ucrInputSameValue.IsEmpty)) OrElse 
                (ucrChkWetDays.Checked AndAlso ucrNudWetDays.IsEmpty) OrElse 
                (ucrChkOutlier.Checked AndAlso (ucrNudSkewnessWeight.IsEmpty OrElse ucrNudCoeff.IsEmpty)) OrElse
                (ucrChkDryMonth.Checked AndAlso (ucrInputThreshold.IsEmpty OrElse ucrReceiverMonth.IsEmpty))) OrElse
                ucrChkOutlier.Checked AndAlso (ucrChkOmitZero.Checked AndAlso ucrInputThresholdValue.IsEmpty) Then
```

2021-01-27 09:59 UTC, lloyddewit commented on instat/ucrNud.vb
> +        Return nudUpDown.Text = ""
is this safer?
```suggestion
        Return string.IsNullOrEmpty(nudUpDown.Text)
```

2021-01-27 10:31 UTC, shadrackkibet commented
No functionality change. Happy with these changes.

2021-01-28 08:41 UTC, lloyddewit approved these changes

2021-01-28 08:42 UTC, lloyddewit commented
@rdstern Small changes since your last approval (functionality not affected). Please could you approve again? thanks

2021-01-29 08:34 UTC, shadrackkibet commented
@rdstern ?

2021-01-29 09:40 UTC, rdstern approved these changes

2021-02-01 11:12 UTC, merged