Improving the inventory graph
africanmathsinitiative/R-Instat pull request #6187
Opened 2021-01-26 13:19 UTC by N-thony

@rdstern thanks for your comments in issue #6029. I think I resolved them, please could you review them?

2021-01-27 08:23 UTC, lloyddewit commented
@shadrackkibet please could you review? thanks

2021-01-27 10:03 UTC, shadrackkibet requested changes

2021-01-27 10:03 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +               g <- ggplot2::ggplot(data = curr_data, ggplot2::aes_(x = as.name(date_col), y = 1, fill = as.name(key_name))) + ggplot2::geom_raster() + ggplot2::scale_fill_manual(values = key) + ggpl
Make this a variable since it is repeated here 4 times? 
```
ggplot2::ggplot(data = curr_data, ggplot2::aes_(x = as.name(date_col), y = 1, fill = as.name(key_name))) + ggplot2::geom_raster() + ggplot2::scale_fill_manual(values = key) + ggplot2::scale_x_date(date_minor_breaks = "1 year")
```

2021-01-27 10:03 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +	      }else {g <- g + ggplot2::facet_grid(facets = as.formula(paste(station_col, "+ .~variable")))}
Out of interest why this change?

2021-01-27 10:03 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +	      }else {g <- g + ggplot2::facet_grid(facets = as.formula(paste(station_col, "+ .~variable")))}
Out of interest why this change?

2021-01-27 13:07 UTC, N-thony commented
@shadrackkibet  thanks for your comments above. I think I resolved them, please could you review them?

2021-01-27 14:14 UTC, shadrackkibet commented
- Size label missing?
![image](https://user-images.githubusercontent.com/26301973/106000664-23783580-60c0-11eb-8a19-76e6297cbf32.png)
- Specifying x-axis breaks doesn't work for me. Using Dodoma data I use the following
![image](https://user-images.githubusercontent.com/26301973/106001269-cc269500-60c0-11eb-9608-4dc383f34eff.png)
Notice that the x-axis doesn't change in the following plot. I expected to have tick marks every 5 years.
![image](https://user-images.githubusercontent.com/26301973/106001548-245d9700-60c1-11eb-8d05-88e44b3cefb3.png)
- When I specify breaks and the inputs(from, to and in step of) are left empty as shown below then go back and click Ok I get below bug. This doesn't happen in PICSA dialog.
![image](https://user-images.githubusercontent.com/26301973/106002134-d006e700-60c1-11eb-92f4-650f33fe0546.png)
![image](https://user-images.githubusercontent.com/26301973/106002382-1f4d1780-60c2-11eb-8d54-d0f4b783da06.png)
- The sub dialog design doesn't look great. Labels are far from corresponding controls, no proper alignments of controls, inconsistencies, lots of empty spaces around etc. Can this be improved now? perhaps @lilyclements has some time to help with sorting out the design.

2021-01-27 14:25 UTC, shadrackkibet requested changes

2021-01-27 14:25 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +               g <- g + ggplot2::facet_grid(facets = as.formula(paste("variable +", station_col, "~."))) + blank_y_axis + ggplot2::scale_y_continuous(breaks = NULL) + ggplot2::labs(y = "")
```suggestion
               g <- g + ggplot2::facet_grid(facets = as.formula(paste("variable +", station_col, "~."))) + blank_y_axis + ggplot2::scale_y_continuous(breaks = NULL) + ggplot2::labs(y = NULL)

```

2021-01-27 14:25 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +              g <- g + ggplot2::facet_wrap(facets = as.formula(paste(".~",station_col, "+ variable")), nrow = nrow, ncol = ncol, scales = scale, dir = dir) + blank_y_axis + ggplot2::scale_y_continuou
```suggestion
              g <- g + ggplot2::facet_wrap(facets = as.formula(paste(".~",station_col, "+ variable")), nrow = nrow, ncol = ncol, scales = scale, dir = dir) + blank_y_axis + ggplot2::scale_y_continuous(breaks = NULL) + ggplot2::labs(y = NULL)

```

2021-01-27 14:25 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +               g <- g + ggplot2::facet_grid(facets = as.formula(paste(station_col, "~variable"))) + blank_y_axis + ggplot2::scale_y_continuous(breaks = NULL) + ggplot2::labs(y = "")
```suggestion
               g <- g + ggplot2::facet_grid(facets = as.formula(paste(station_col, "~variable"))) + blank_y_axis + ggplot2::scale_y_continuous(breaks = NULL) + ggplot2::labs(y = NULL)

```

2021-01-27 14:25 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +               g <- g +  ggplot2::facet_wrap(facets = as.formula(paste(".~variable +",station_col)), nrow = nrow, ncol = ncol, scales = scale, dir = dir) + blank_y_axis + ggplot2::scale_y_continuous(
```suggestion
               g <- g +  ggplot2::facet_wrap(facets = as.formula(paste(".~variable +",station_col)), nrow = nrow, ncol = ncol, scales = scale, dir = dir) + blank_y_axis + ggplot2::scale_y_continuous(breaks = NULL) + ggplot2::labs(y = NULL)

```

2021-01-27 14:25 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +               g <- g + ggplot2::facet_grid(facets = as.formula(paste("variable~", station_col))) + blank_y_axis + ggplot2::scale_y_continuous(breaks = NULL) + ggplot2::labs(y = "")
```suggestion
               g <- g + ggplot2::facet_grid(facets = as.formula(paste("variable~", station_col))) + blank_y_axis + ggplot2::scale_y_continuous(breaks = NULL) + ggplot2::labs(y = NULL)

```

2021-01-27 16:50 UTC, rdstern commented
The options on the main page seem roughly to be working.  But the sub-dialogue seems only to add in an nrow and ncol  value and they don't (seem to) do anything.

Also I can have both activated and I wonder what should then be done.  I used an example with 4 stations and 5 elements.  I set the number of rows to 2 and also columns to 2!  Of course only 1 of these is needed, because I have a total of 20 facets.

When I specify the number of rows (or columns) I do want also to allow them to be in either element or station order.  I still wonder whether a single checkbox on the main dialogue might be better?  Say for columns.  Then there is a setting of the pull-down and also the number of columns.

The data I am using is this:
[niger4day.zip](https://github.com/africanmathsinitiative/R-Instat/files/5881715/niger4day.zip)





```
# Code generated by the dialog, Inventory
last_graph <- data_book$make_inventory_plot(data_name="Data", date_col="date", element_cols=c("tmax","tmin","rain","hmax","hmin"), station_col="Name", facet_by="stations-elements", graph_title="Inventory Plot", graph_subtitle="", graph_caption="", labelXAxis="", toXAxis=, fromXAxis=, byXaxis=, labelYAxis="", nrow=2, ncol=2)
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="Data")
data_book$get_graphs(data_name="Data", graph_name="last_graph")

```

Here is a typical graph:

2021-01-28 11:44 UTC, N-thony commented
> The options on the main page seem roughly to be working. But the sub-dialogue seems only to add in an nrow and ncol value and they don't (seem to) do anything.
> 
> Also I can have both activated and I wonder what should then be done. I used an example with 4 stations and 5 elements. I set the number of rows to 2 and also columns to 2! Of course only 1 of these is needed, because I have a total of 20 facets.
> 
> When I specify the number of rows (or columns) I do want also to allow them to be in either element or station order. I still wonder whether a single checkbox on the main dialogue might be better? Say for columns. Then there is a setting of the pull-down and also the number of columns.
> 
> The data I am using is this:
> [niger4day.zip](https://github.com/africanmathsinitiative/R-Instat/files/5881715/niger4day.zip)
> 
> ```
> # Code generated by the dialog, Inventory
> last_graph <- data_book$make_inventory_plot(data_name="Data", date_col="date", element_cols=c("tmax","tmin","rain","hmax","hmin"), station_col="Name", facet_by="stations-elements", graph_title="Inventory Plot", graph_subtitle="", graph_caption="", labelXAxis="", toXAxis=, fromXAxis=, byXaxis=, labelYAxis="", nrow=2, ncol=2)
> data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="Data")
> data_book$get_graphs(data_name="Data", graph_name="last_graph")
> ```
> 
> Here is a typical graph:

I cannot see the graph here.

2021-01-28 11:55 UTC, N-thony commented
@shadrackkibet thanks for your comments above. I think I resolved them, please could you review them?

2021-01-29 07:18 UTC, rdstern commented
Sorry @N-thony - graph now added above

2021-01-29 08:38 UTC, N-thony commented
> The options on the main page seem roughly to be working. But the sub-dialogue seems only to add in an nrow and ncol value and they don't (seem to) do anything.
> 
> Also I can have both activated and I wonder what should then be done. I used an example with 4 stations and 5 elements. I set the number of rows to 2 and also columns to 2! Of course only 1 of these is needed, because I have a total of 20 facets.
> 
> When I specify the number of rows (or columns) I do want also to allow them to be in either element or station order. I still wonder whether a single checkbox on the main dialogue might be better? Say for columns. Then there is a setting of the pull-down and also the number of columns.
> 
> The data I am using is this:
> [niger4day.zip](https://github.com/africanmathsinitiative/R-Instat/files/5881715/niger4day.zip)
> 
> ```
> # Code generated by the dialog, Inventory
> last_graph <- data_book$make_inventory_plot(data_name="Data", date_col="date", element_cols=c("tmax","tmin","rain","hmax","hmin"), station_col="Name", facet_by="stations-elements", graph_title="Inventory Plot", graph_subtitle="", graph_caption="", labelXAxis="", toXAxis=, fromXAxis=, byXaxis=, labelYAxis="", nrow=2, ncol=2)
> data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="Data")
> data_book$get_graphs(data_name="Data", graph_name="last_graph")
> ```
> 
> Here is a typical graph:
> ![image](https://user-images.githubusercontent.com/11226469/106243909-0ea3bb00-6202-11eb-9a62-90f8c8e49dc7.png)

I suggest moving the pull-down control on the main form to the sub dialog. What do you think?

2021-01-29 08:49 UTC, N-thony commented
@rdstern  thanks for your comments above. I think I resolved them, please could you review them?
I'm still wondering the optimal place for the pull-down control only to set ncol/nrow for elements/stations

2021-01-29 11:00 UTC, N-thony commented
@rdstern thanks for your comments above. I think I resolved them, please could you review them?

2021-02-03 08:46 UTC, rdstern approved these changes

2021-02-03 10:23 UTC, lloyddewit approved these changes

2021-02-03 10:25 UTC, merged