Adding a right-click to the Column metadata
africanmathsinitiative/R-Instat pull request #6203
Opened 2021-02-03 09:36 UTC by shadrackkibet

Fixes #5250 and Fixes # @africanmathsinitiative/developers this is ready for review.

Notes
- Deleted extra separator, disabled freeze and unfreeze menu items
- Added and implemented facilities for tab context menu strip
- Enabled hide sheet when sheets > 1
- Removed some commented out code

2021-02-03 09:53 UTC, shadrackkibet commented
I think in the long term we need to make these right-click as user controls. Maintaining consistency across windows is difficult.

2021-02-03 10:28 UTC, lloyddewit commented
@Ivanluv Please could you review? thanks

2021-02-03 11:28 UTC, shadrackkibet commented
**Note:** Right-click is now also added into row click in data frame metadata.

2021-02-04 12:30 UTC, shadrackkibet commented
@rdstern what do you think about these additions?

2021-02-04 12:50 UTC, rdstern submitted a review, later dismissed
@shadrack this looks fine to me.

2021-02-09 08:46 UTC, shadrackkibet commented
@lloyddewit this is ready for review.

2021-02-12 10:52 UTC, lloyddewit requested changes
@shadrackkibet this looks good, I just had a couple of comments.

2021-02-12 10:52 UTC, lloyddewit commented on instat/ucrDataFrameMetadata.vb
> +        Dim lstSelectedVars As New List(Of String)
We know the size of the array (derived from `grdMetaData.CurrentWorksheet.SelectionRange.Row`). Therefore we can make a fixed size array and allocate to it directly in the loop. Is this simpler and more efficient than creating an empty variable length list and then expanding the list on each iteration?
Declare array something like:
```
Dim arrSelectedVars(grdMetaData.CurrentWorksheet.SelectionRange.Row) As String
```

2021-02-12 10:52 UTC, lloyddewit commented on instat/ucrDataFrameMetadata.vb
> +            lstSelectedVars.Add(grdMetaData.CurrentWorksheet(i, 0))
replace with array? e.g.
```
arrSelectedVars(i - grdMetaData.CurrentWorksheet.SelectionRange.Row) = grdMetaData.CurrentWorksheet(i, 0)
```

2021-02-12 10:52 UTC, lloyddewit commented on instat/ucrDataFrameMetadata.vb
> +    Private Function GetSelectedVariableNamesAsArray() As String()
This function returns an array of strings. However all the calling functions only use the first string in the array. Would it be better just to return the first string?

2021-02-12 11:03 UTC, lloyddewit commented
@shadrackkibet as you know, GitHub will now generate the release notes automatically. I tried to change the name of this PR so that it provides a descriptive sentence for the release notes. Please could you check/update? thanks

2021-02-12 11:59 UTC, shadrackkibet commented on instat/ucrDataFrameMetadata.vb
> +    Private Function GetSelectedVariableNamesAsArray() As String()
Yes, that would work now. However, I think one reason we want to leave it as an array is that some functionalities like deleting multiple columns at the same time will require this to return an array.

2021-02-12 12:31 UTC, shadrackkibet commented on instat/ucrDataFrameMetadata.vb
> +        Dim lstSelectedVars As New List(Of String)
Agreed.

2021-02-12 12:31 UTC, shadrackkibet commented on instat/ucrDataFrameMetadata.vb
> +            lstSelectedVars.Add(grdMetaData.CurrentWorksheet(i, 0))
Agreed.

2021-02-12 12:40 UTC, shadrackkibet commented
> @shadrackkibet as you know, GitHub will now generate the release notes automatically. I tried to change the name of this PR so that it provides a descriptive sentence for the release notes. Please could you check/update? thanks

@lloyddewit there are no changes in the Data view here. Only Column metadata (bottom right-click) and Dataframe metadata (row right-click).

2021-02-17 09:32 UTC, lloyddewit commented on instat/ucrDataFrameMetadata.vb
> +    Private Function GetSelectedVariableNamesAsArray() As String()
OK, thanks
I think it's important to have an extendable architecture but I prefer only to implement functionality as/when its needed. Your preference may be different.
In this case, the implementation is done so I agree it's not worth changing (and I agree it may help another developer in the future).

2021-02-17 10:07 UTC, lloyddewit approved these changes

2021-02-17 10:08 UTC, lloyddewit commented
@rdstern There are some small implementation changes. The functionality should be identical to before. Please could you retest? thanks

2021-02-17 15:33 UTC, rdstern approved these changes
Looks fine still

2021-02-18 08:38 UTC, merged