Adding quintiles, terciles and deciles to summary statistics
africanmathsinitiative/R-Instat pull request #6205
Opened 2021-02-04 08:06 UTC by shadrackkibet

Fixes #6194 @africanmathsinitiative/developers this is ready for review.

Notes.
- Designer modifications i.e added more checkboxes under summaries tab.
- Added and implemented more summary functions (terciles, deciles and quintiles) and changed function names.
- Code refactor i.e changed the assignment of labels from `=` to `<-` and tidyverse styling.

2021-02-04 08:40 UTC, rdstern requested changes
@shadrackkibet this already works fine.  The only change I would like is to reverse the order of the derived variables.
So the tercile/quartile summaries come in the new data frame before the deciles, and in ascending, rather than descending order.  And they come after the summaries that are from the blocks above - like the count, sum, etc

2021-02-04 08:49 UTC, lloyddewit commented
@dannyparsons This PR contains significant R changes. Would you like to peer review?

2021-02-04 11:57 UTC, shadrackkibet commented
@rdstern I think the order of the resulting columns is now fixed. Please check.

2021-02-04 12:28 UTC, rdstern approved these changes
@shadrackkibet great.

2021-02-08 18:28 UTC, dannyparsons submitted a review, later dismissed

2021-02-08 18:28 UTC, dannyparsons commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +}
To avoid this repetition for each quantile this could use `summary_quantile` above i.e.

```
p10 <- function(x, na.rm = FALSE, na_type = "", weights = NULL, ...) {
   summary_quantile(x = x, na.rm = na.rm, na_type = na_type, weights = weights, probs = 0.1)
}

p20 <- function(x, na.rm = FALSE, na_type = "", weights = NULL, ...) {
   summary_quantile(x = x, na.rm = na.rm, na_type = na_type, weights = weights, probs = 0.2)
}

```

2021-02-09 07:46 UTC, shadrackkibet commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +}
Sure, this makes the code a bit cleaner. Thanks

2021-02-09 09:29 UTC, rdstern approved these changes
Looks good still

2021-02-12 10:12 UTC, lloyddewit approved these changes

2021-02-12 10:30 UTC, shadrackkibet commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +p20 <- function(x, na.rm = FALSE, na_type = "", weights = NULL, ...) {
The reason we need all these functions is because we want the user to be able to obtain all these summaries (p10, p20 etc) on one click Ok otherwise the user will have to use the dialog multiple times. Your suggestions above would not work because the current setup in the main summary function `calculate_summary` would not produce multiple columns at the same time using one `summary_function` e.g `summary_quantile` with different `probs`. I am not sure if this makes sense to you. Perhaps explanation via a call will be better.

2021-02-12 12:00 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +p20 <- function(x, na.rm = FALSE, na_type = "", weights = NULL, ...) {
@shadrackkibet thanks for the explanation. I understand that if we want multiple summaries from a single call to the summary function (`calculate_summary`?), then we can only pass in a list of functions. We cannot pass in a single function with a list of different parameters. Did I understand correct? If not, please may I have a quick verbal call? thanks

2021-02-12 12:02 UTC, merged

2021-02-12 12:10 UTC, shadrackkibet commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +p20 <- function(x, na.rm = FALSE, na_type = "", weights = NULL, ...) {
Correct. But if we want I think we can refactor `calculate_summary` to allow passing in a function with a list of different parameters.