Swapping metadata and data window
africanmathsinitiative/R-Instat pull request #6212
Opened 2021-02-05 15:34 UTC by N-thony

Swapping Metadata and Data windows. I suggest that when the options about Data View and Column data are checked in the view menu, the option Swap metadata and data window will appear in the View menu so that if you check, the swapping will occur. This solves issue #6208 
@rdstern this is ready for review. Thanks.

2021-02-07 08:09 UTC, rdstern requested changes
@N-thony It seems to be working quite well, but not exactly as I was hoping.  I am happy with what is there though.
I was hoping for the "Swap Data and Metadata" entry to be available when I start.  If you click on it (at the start, it would replace the data (i.e. close that) by the metadata, i.e. open the metadata in its place.
Currently I can swap when I have 3 windows open.  I like that, but would also like the option with just the 2 windows.

2021-02-07 08:15 UTC, rdstern requested changes
Aha, I can do what I want with your current system, but it takes multiple steps.
I opened the Column Metadata - and now the swap appears.  Now I swap.  Now I close the data.  
I would like those 3 steps from the start, by haing the Swap menu item visible all the time.  I just click on that and it swaps them over.

2021-02-07 17:38 UTC, N-thony commented
@rdstern  Thanks for your comment above. I think I resolved it. Please could you review?

2021-02-09 08:26 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2021-02-09 18:10 UTC, N-thony commented
@lloyddewit sorry, before @Ivanluv to review this, following the chat with @rdstern there is a small change I made in the code that I would like @rdstern to test first then @Ivanluv will proceed with the review. @rdstern please could you test the small change I made? Thanks

2021-02-09 20:10 UTC, N-thony commented
@lloyddewit sorry, before @Ivanluv to review this, following the chat with @rdstern there is a small change I made in the code that I would like @rdstern to test first then @Ivanluv will proceed with the review. @rdstern please could you test the small change I made? Thanks

2021-02-10 16:26 UTC, N-thony commented
@rdstern I have added some combinations for the swapping system. Please could you test the change? Thanks

2021-02-10 19:51 UTC, rdstern approved these changes
@N-thony this is now ok from my point of view

2021-02-12 11:07 UTC, lloyddewit commented
@Ivanluv this PR is ready again for your review, thanks

2021-02-12 12:00 UTC, Ivanluv commented
@lloyddewit  am looking at this now

2021-02-15 07:21 UTC, Ivanluv commented
@lloyddewit  this looks okay

2021-02-15 08:07 UTC, shadrackkibet commented
I tested this and seems to work - no code review. However, I have one comment.  I did the following.

- Loaded data
- Swap Data and Metadata
- Open Data view via **View>Data View**
- Close Data view via **View>Data View**

I thought because **Swap data and metadata** is checked the layout should remain swapped i.e Column Metadata side by side with Output window.

2021-02-19 08:54 UTC, lloyddewit requested changes

2021-02-19 08:54 UTC, lloyddewit commented on instat/frmMain.vb
> +            End If
restructure to remove duplication?
```suggestion
            If mnuViewSwapDataAndMetadata.Checked AndAlso mnuViewDataView.Checked Then
                splDataOutput.Panel1.Controls.Add(ucrColumnMeta)
                splMetadata.Panel1.Controls.Add(ucrDataViewer)
                If Not mnuViewColumnMetadata.Checked Then
                    mnuViewColumnMetadata.Checked = True
                    mnuViewDataView.Checked = False
                End If
            Else
                splDataOutput.Panel1.Controls.Add(ucrDataViewer)
                splMetadata.Panel1.Controls.Add(ucrColumnMeta)
            End If
```

2021-02-20 18:54 UTC, N-thony commented
@lloyddewit thanks for the comment above. I resolved it.

2021-02-25 08:49 UTC, lloyddewit submitted a review, later dismissed

2021-02-25 08:55 UTC, lloyddewit commented
@rdstern You approved on 10 Feb. Since then, there was a small code change that should not affect the functionality. Please could you approve again? thanks

2021-02-25 11:30 UTC, rdstern approved these changes

2021-03-02 08:18 UTC, lloyddewit commented
@N-thony Please can you resolve the merge conflicts? We can then merge, thanks

2021-03-03 08:34 UTC, lloyddewit approved these changes

2021-03-03 08:40 UTC, lloyddewit commented
@rdstern The only change since your last approval were changes to fix merge conflcts in frmMain. Please could you approve again? thanks

2021-03-03 08:42 UTC, shadrackkibet commented
> I tested this and seems to work - no code review. However, I have one comment. I did the following.
> 
> * Loaded data
> * Swap Data and Metadata
> * Open Data view via **View>Data View**
> * Close Data view via **View>Data View**
> 
> I thought because **Swap data and metadata** is checked the layout should remain swapped i.e Column Metadata side by side with Output window.

Just before this is approved and merged. I would like to check if this was considered.

2021-03-03 09:19 UTC, rdstern commented
@shadrack you are quite right and I hadn't tested that combination.  It is a useful one and I agree with you.
But @N-thony this is ok and has been going on a long time.  So, if easy to fix, then please do.  Otherwise I can approve and this can be a further small issue.

Just to clarify what Shadrack found.  
a) View > Swap data and metadata - looks fine but you don't see the data - just the metadata.  And View > data View is correctly not ticked.
b) View > Data View

Now you see the data and usefully in a wide Window right across.  That's quite a useful layout with the 3 windows

c) Now View > Data View, because you have finished looking at the data and want to continue as before, i.e. with the meat-data alongside the Output.  But it isn't like that.

2021-03-14 09:38 UTC, rdstern reviewed
@N-thony the recent problem still seems to be there.  I hope it can be fixed soon.

2021-03-23 14:40 UTC, lloyddewit commented
> 
> 
> @shadrack you are quite right and I hadn't tested that combination. It is a useful one and I agree with you.
> But @N-thony this is ok and has been going on a long time. So, if easy to fix, then please do. Otherwise I can approve and this can be a further small issue.

@rdstern - @N-thony wasn't sure how to fix this and he asked my view.
To solve this, I think we would have to update `frmMain.UpdateLayout()` and possibly also look at the event handlers for `mnuViewDataView`, `mnuViewColumnMetaData` and `mnuViewSwapDataAndMetadata`.  This is significant work (>1 person-day including extra testing?). I assume this is not a priority for the sprint. I suggest that we make a small issue instead.

2021-03-23 15:02 UTC, rdstern submitted a review, later dismissed
This is not worth that amount of work.  The changers are excellent, and this is a very slight inconvenience, i.e. you have to press another couple of buttons to get what is needed.
So I have no hesitation in considering this a "feature" and therefore am happy to approve.

2021-03-23 15:22 UTC, lloyddewit commented
@N-thony Please could you 
- make an issue for this last unresolved 'feature'
- resolve the merge conflicts

thanks

2021-03-23 15:43 UTC, N-thony commented
> @N-thony Please could you
> 
> * make an issue for this last unresolved 'feature'
> * resolve the merge conflicts
> 
> thanks

@lloyddewit thanks, I resolved the conflicts. I will write an issue for the last unresolved 'feature'.

2021-03-23 16:19 UTC, lloyddewit approved these changes

2021-03-23 16:22 UTC, lloyddewit commented
@N-thony Another PR completed, thank you :)

@rdstern @maxwellfundi @shadrackkibet I did a quick regression test and it looks OK. Please could one of you approve so we can merge? 
Thanks

2021-03-23 16:27 UTC, rdstern approved these changes
Great

2021-03-23 18:49 UTC, merged