Adding extreme value, generalized pareto and gumbel distributions
africanmathsinitiative/R-Instat pull request #6214
Opened 2021-02-07 09:51 UTC by shadrackkibet

Fixes #5886 and replaces PR #5961 by @Ivanluv. @rdstern this should at least work for **Show model** and **Random Samples**, therefore, I am putting this up for some initial testing. It will also be good for @jkmusyoka to test it. 

@rdstern `texmex` package includes  **_Generalized logistic distribution_**. I thought of adding it, what do you think?

I don't expect this to work perfectly, I will actually be surprised if there are no bug reports!

**Notes** 
- Loaded texmex package by default
- Added generalized pareto and gumbel resources
- Added evd, generalized pareto and gumbel into the list of distributions
- Some designer fixes
- Code refactor e.g adding setter methods and removing redundant code and calls

2021-02-07 14:45 UTC, rdstern requested changes
@shadrack this all seems to work in the random samples and also in the probability distributions.
In the gev I think the problem is that these distributions require initial values - and they need to be given using the names of the parameters - which I don't know.  I think that may need to be solved in R initially to see what needs to be added in R-Instat?
It is possible that the method using fitdistrplus won't work easily.  In that case we may have to change plans slightly.

2021-02-07 15:07 UTC, shadrackkibet commented
@rdstern thanks for testing this. My priority at the moment is to ensure at least it works well for probability distributions. I agree that fixing it in one variable will need a different approach and it might also need us to contact **fitdistrplus** authors. Therefore I consider this a separate task.

2021-02-07 15:14 UTC, rdstern commented
@shadrackkibet your comment overlapped with mine to you in relation to the probability distributions dialogue.  Here is what I said:
In addition to discussing the modelling, it would be good to have a quick discussion on the extreme value distributions.  In particular I suggest we could identify considerable improvements in the Probability dialogue.  I don't want you then to have to do them, but you could maybe supervise Ivan, or Haward, or Antoine (or perhaps even Caleb) on that.  
I am less sure on exactly what needs to be done on the fitting.  So good to discuss that also.

There is quite a lot to improve on that dialogue.  It should be a separate issue, which then becomes important in the teaching of extremes - and other probability stuff.

2021-02-09 08:34 UTC, lloyddewit commented
@shadrackkibet I understand that this PR is still ongoing, let us know when you think this is stable enough for a peer review, thanks

2021-04-12 14:00 UTC, shadrackkibet commented on instat/static/InstatObject/R/Rsetup.R
> +=======
```suggestion
```

2021-04-13 15:14 UTC, rdstern commented
@shadrackkibet this is now working much better:
a) Small oddity with the extreme value distribution with the default 0.5 - it doesn't do it.  Works for Gumbel and Pareto, and for the extreme value with other limits.  Am I missing something here?
b) Good to have the options button.  Should it be called Graphics Options rather than Distributions Options.  The button  could move up just a bit.
c) I still don't get anything to save into a variable.  Should the saving be an option, and the output be made cleaner in the results window?

Say as soon as you want to hane the completion of this dialogue on.

I didn't check its use in the One Variable fit.  Correct that this is not implemented yet?  I was assuming Caleb might want to look at that?

2021-04-13 15:56 UTC, shadrackkibet commented
> c) I still don't get anything to save into a variable. Should the saving be an option, and the output be made cleaner in the results window?

- You have to use a column for that just uncheck the checkbox **Enter value(s)** then it will give a receiver and the save column control.

- One variable is not yet working. I consider it a separate task.

2021-04-14 06:29 UTC, rdstern commented
@shadrackkibet I continue with:
_c) I still don't get anything to save into a variable. Should the saving be an option, and the output be made cleaner in the results window?_
To which you said:
_You have to use a column for that just uncheck the checkbox Enter value(s) then it will give a receiver and the save column control._

Here is the dialogue - I think I am doing as you said:
![image](https://user-images.githubusercontent.com/11226469/114663565-75f5e500-9cf2-11eb-957e-a056dae1f5c6.png)

I was excited.  Here are the data and the results:

![image](https://user-images.githubusercontent.com/11226469/114663765-b8b7bd00-9cf2-11eb-822d-29f729679392.png)

The command is as follows:

```
# Code generated by the dialog, Show Model
prob1 <- data_book$get_columns_from_data(data_name="data", col_names="prob1")
mosaic::qdist(p=prob1, plot=FALSE, return="values", dist="gev", xi=0, sigma=1, mu=3)
```
So, a) I am happy with the option to put the results in the output window - with a layout giving the quantiles and the values.
b) The results don't save in a variable

Thanks

2021-04-14 08:41 UTC, rdstern reviewed
@shadrackkibet this now works.  There remains a lot to do with this dialogue, most of which is cosmetic.  
a) It would be good to be able to display the numerical results in the output window instead of saving.
b) Lots of minor changes in the layout and options in the dialogue e.g. label Graph Options, change position of it slightly.  add option to display more of the distribution (i think the default is 0.99.95?) change the default for the Position button.  Make the graph, values into a box with a label, e.g. Display:  
You are good on details.  Do you want to merge now, or soon, and then continue, or hand over, or..

2021-05-08 16:12 UTC, rdstern submitted a review, later dismissed
@shadrackkibet I am approving as this is so much better than we have currently.
I then hope @Cal-Insta may be able to improve further

2021-05-09 17:35 UTC, shadrackkibet commented
@rdstern I agree with you. Someone can review then we can merge.

2021-05-09 18:25 UTC, rdstern approved these changes

2021-05-14 08:11 UTC, lloyddewit requested changes
This looks good, just a few minor comments

2021-05-14 08:11 UTC, lloyddewit commented on instat/dlgShowModel.vb
> +            For Each clstempparam In ucrDistributionAndParameters.clsCurrRFunction.clsParameters
Rename to `clsTempParam`?

2021-05-14 08:11 UTC, lloyddewit commented on instat/dlgShowModel.vb
> +            For Each clstempparam In ucrDistributionAndParameters.clsCurrRFunction.clsParameters
Rename to `clsTempParam`?

2021-05-25 04:31 UTC, rdstern submitted a review, later dismissed
@shadrackkibet I would really like to see your improvements merged.  Are there still changes to make or should this be examined by @lloyddewit now?
There is still a lot that can be improved, but I would like @Cal-Insta to start from where you have got to?

2021-05-25 12:43 UTC, shadrackkibet commented on instat/dlgRandomSample.vb
> +        SetRCodeForControls(bReset)
Yes, I changed the file. f to F here

2021-05-25 12:46 UTC, shadrackkibet commented on instat/clsDistribution.vb
> +    Public Sub SetRName(strTemp As String)
Yes, doing this is better and cleaner. This will be more work. Therefore I will a TODO comment in code. Thanks

2021-05-25 13:00 UTC, shadrackkibet commented on instat/clsDistribution.vb
> +        strPackagName = strTemp
I agree with your suggestion. However, changing it will result in changing another three additional files where this is used. I also notice similar naming in `clsRFunction.vb` file which has over 99+ references.

2021-05-25 13:07 UTC, shadrackkibet commented on instat/dlgRandomSample.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
I have now made a minor designer change so that the designer file is included.

2021-05-25 13:10 UTC, shadrackkibet commented
@lloyddewit I have addressed your comments above. Please check. @rdstern could you please test and re-approve if you are happy? Thanks

2021-05-25 13:14 UTC, lloyddewit approved these changes

2021-05-25 15:19 UTC, merged