Oddity when importing excel file
africanmathsinitiative/R-Instat pull request #6222
Opened 2021-02-15 17:44 UTC by N-thony

Fixing the issue when setting the missing value code in importing excel file. This solve issue #6192
@africanmathsinitiative/developers and @rdstern this is ready for review. Thanks.

2021-02-22 09:38 UTC, Patowhiz commented on instat/dlgImportDataset.vb
> +            clsImportExcel.AddParameter("na", "c(" & GetMissingValueRString(ucrInputMissingValueStringExcel.GetText()) & "," & Chr(34) & "" & Chr(34) & ")")
@N-thony the value returned by function `GetMissingValueRString()` could make this fail. It also return an R string vector if it detects the missing values input are more than one. Please have a look at its implementation.

I looked at Lily's comment. I think it's best to implement what you have correctly done here at `GetMissingValueRString()` level.

This could be done in this PR or just edited in PR #6065 that affects the same dialog to avoid future conflicts.

2021-02-22 17:31 UTC, N-thony commented
@Patowhiz thanksfor your comment. I think to have resolve it. Could you please test?

2021-03-01 10:25 UTC, lloyddewit requested changes

2021-03-01 10:25 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +        strRmissingValueString = "c(" & strRmissingValueString & "," & Chr(34) & "" & Chr(34) & ")"
Can we simplify?
```suggestion
        strRmissingValueString = "c(" & strRmissingValueString & "," & Chr(34) & Chr(34) & ")"
```

2021-03-01 10:25 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +        'End If
If these lines are no longer needed, then they should be deleted (rather than commented out)

2021-03-01 10:28 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +            clsImportExcel.AddParameter("na", "c(" & GetMissingValueRString(ucrInputMissingValueStringExcel.GetText()) & "," & Chr(34) & "" & Chr(34) & ")")
@N-thony `GetMissingValueRString` is referenced in 5 places. If you move the changes to 'GetMissingValueRString' then you will affect all 5 references (rather than just the 2 above). Please could you test all 5 references? thanks

2021-03-01 10:36 UTC, lloyddewit requested changes
> @N-thony the value returned by function `GetMissingValueRString()` could make this fail. It also return an R string vector if it detects the missing values input are more than one. Please have a look at its implementation.

@N-thony I don't think you addressed @Patowhiz 's comment above. What is returned by `GetMissingValueRString("a,b")`? is this correct?

2021-03-01 10:43 UTC, N-thony commented
> > @N-thony the value returned by function `GetMissingValueRString()` could make this fail. It also return an R string vector if it detects the missing values input are more than one. Please have a look at its implementation.
> 
> @N-thony I don't think you addressed @Patowhiz 's comment above. What is returned by `GetMissingValueRString("a,b")`? is this correct?

I think in @Patowhiz's comment, he suggested me to apply the change in GetMissingValueRString() level.

2021-03-01 11:38 UTC, N-thony commented
@lloyddewit  thanks for your comment above. I think to have resolved it. Could you please test?

2021-03-01 13:43 UTC, Patowhiz commented
> > > @N-thony the value returned by function `GetMissingValueRString()` could make this fail. It also return an R string vector if it detects the missing values input are more than one. Please have a look at its implementation.
> > 
> > 
> > @N-thony I don't think you addressed @Patowhiz 's comment above. What is returned by `GetMissingValueRString("a,b")`? is this correct?
> 
> I think in @Patowhiz's comment, he suggested me to apply the change in GetMissingValueRString() level.

@N-thony yes that was my suggestion. And also as @lloyddewit mentioned above, try testing it even for other files if the new implementation will work. I think it should work since the new implementation just adds an empty string as one of the missing values placeholders which is probably always the case.

@rdstern my only worry is if there is any situation where a user may not want this default implementation `e.g na = c("-99", "")`. Because the only way they will be able to change it is by going to the script window. The added `""` is never shown in the input control.

2021-03-03 10:00 UTC, lloyddewit commented
@N-thony thank you for the short chat. As discussed, we need to ensure that your solution works with a list of missing values (as opposed to a single specified missing value).
Please create a test Excel file that contains missing values represented by "-1", "-99" and "". Then try and import the Excel file and ensure that all the missing values are replaced by "NA" and the columns remain numeric.
Thanks

2021-03-04 10:12 UTC, N-thony commented
> @N-thony thank you for the short chat. As discussed, we need to ensure that your solution works with a list of missing values (as opposed to a single specified missing value).
> Please create a test Excel file that contains missing values represented by "-1", "-99" and "". Then try and import the Excel file and ensure that all the missing values are replaced by "NA" and the columns remain numeric.
> Thanks

2021-03-04 10:19 UTC, N-thony commented
> > @N-thony thank you for the short chat. As discussed, we need to ensure that your solution works with a list of missing values (as opposed to a single specified missing value).
> > Please create a test Excel file that contains missing values represented by "-1", "-99" and "". Then try and import the Excel file and ensure that all the missing values are replaced by "NA" and the columns remain numeric.
> > Thanks

@lloyddewit  using this file [MPAT.Kenya.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/6082698/MPAT.Kenya.xlsx) shared by @rdstern, I used Household_data. I have tested this solution with column Q56 that contains "-1", "-2", and "-3" and it works well.

2021-03-04 10:22 UTC, lloyddewit approved these changes

2021-03-04 10:24 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2021-03-16 08:41 UTC, Patowhiz commented
> > > > @N-thony the value returned by function `GetMissingValueRString()` could make this fail. It also return an R string vector if it detects the missing values input are more than one. Please have a look at its implementation.
> > > 
> > > 
> > > @N-thony I don't think you addressed @Patowhiz 's comment above. What is returned by `GetMissingValueRString("a,b")`? is this correct?
> > 
> > 
> > I think in @Patowhiz's comment, he suggested me to apply the change in GetMissingValueRString() level.
> 
> @N-thony yes that was my suggestion. And also as @lloyddewit mentioned above, try testing it even for other files if the new implementation will work. I think it should work since the new implementation just adds an empty string as one of the missing values placeholders which is probably always the case.
> 
> @rdstern my only worry is if there is any situation where a user may not want this default implementation `e.g na = c("-99", "")`. Because the only way they will be able to change it is by going to the script window. The added `""` is never shown in the input control.

@rdstern could you please answer my above question.

2021-03-16 08:44 UTC, Patowhiz commented on instat/dlgImportDataset.vb
> +        strRmissingValueString = "c(" & strRmissingValueString & "," & Chr(34) & Chr(34) & ")"
@maxwellfundi @lloyddewit  This now looks good from my end

2021-03-16 09:01 UTC, rdstern commented
@Patowhiz I am not quite sure what you mean by not wanting the default?  On input I think we will never want to have the variables made into character, because of those missing values.  

But I do still want to be able to include multiple missing values.  For data from Zambia now I am using -99.0,-99, because R recognises them as different.  I assume I can still have this?  If not, then perhaps we might just allow a single string/value, but have a second field for another.  It is rare that we need more than 2 - so perhaps the script window can then be used.

2021-03-16 09:32 UTC, Patowhiz commented
@N-thony my question has been answered. @lloyddewit  this is ready for you.

2021-03-16 09:35 UTC, lloyddewit commented
@rdstern Please could you test/approve? thanks

2021-03-24 14:41 UTC, maxwellfundi commented
@rdstern this is ready for your re-review.

2021-03-25 09:14 UTC, rdstern approved these changes
Great

2021-03-25 09:27 UTC, merged