Save Control in dlgCalculator
africanmathsinitiative/R-Instat pull request #6230
Opened 2021-02-22 08:16 UTC by Patowhiz

Fixes #6080
@africanmathsinitiative/developers this is ready for review.

2021-02-22 08:26 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_SaveResultChanged(ucrChangedControl As ucrCore) Handles ucrSaveResultInto.ControlValueChanged, ucrSaveResultInto.ControlContentsChanged
@lloyddewit this made me wonder if we should add raising of `ControlContentsChanged` in the `ucrCheck` custom control. At the moment, it only raises `ControlValueChanged` when checked or unchecked, and the `ucrSave` control only raises its `ControlValueChanged`. 

In this case, we want the calculator to detect  any changes in its `ucrSave` control; checked status and other controls contents changed.

So I implemented it this way cause I'm not sure what it will conceptually mean to also raise contents changed when the checkbox status is changed in the `ucrSave` control and whether that will change its conceptualisation without affecting other dialogs negatively.

However, I strongly think that `ucrCheck` control should also raise `ControlContentsChanged`. If you agree then the extra event defined here may not be necessary.

2021-02-22 09:42 UTC, rdstern requested changes
@Patowhiz great to have this working again:
a) It says Save Result Into.  Either delete the Into or move the control over to the right, so it doesn't overwrite.
b) I suggest the default is to produce another variable.  So the initial state is with the Save control checked.
c) When you write to the output window, just give the data.  Now you get each part of the object.
d) Not to do - just a relief.  I like the way you can use the drop-down in the save control, to save back into an existing variable.  Delighted that is now returned.

2021-02-22 10:20 UTC, Patowhiz commented
@rdstern I have now made the above changes

2021-02-22 13:08 UTC, rdstern approved these changes
Looks ok now

2021-03-01 08:25 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_SaveResultChanged(ucrChangedControl As ucrCore) Handles ucrSaveResultInto.ControlValueChanged, ucrSaveResultInto.ControlContentsChanged
@Patowhiz Thank you for the interesting question.

My personal preference would be for controls to raise standard events whenever possible. If these events have a non-standard effect then I would prefer this non-standard behaviour to be implemented in the event handler. I think doing it this way makes it easier for other developers to understand the behaviour.

Another point: Currently the `ucrSaveResultInto.ControlContentsChanged` is handled in two subs. This could be confusing for other developers reading the code. The order in which the subs will be called is also indeterminate. 
Is it possible to handle the `ucrSaveResultInto.ControlContentsChanged` event in a single sub?

2021-03-01 13:29 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_SaveResultChanged(ucrChangedControl As ucrCore) Handles ucrSaveResultInto.ControlValueChanged, ucrSaveResultInto.ControlContentsChanged
> My personal preference would be for controls to raise standard events whenever possible.

@lloyddewit great. Let me implement the event in the `ucrCheck`. Then we won't need `ucrSaveResultInto.ControlContentsChanged` to be handle in 2 subs

2021-03-02 14:30 UTC, Patowhiz commented
@lloyddewit I have made the necessary changes needed in the `ucrCalculator`. I wasn't sure on the best event to raise  `OnControlContentsChanged()` in `ucrCheck` (I have used `CheckedChanged`, it's already being used for  `OnControlValueChanged()`).

2021-03-02 15:03 UTC, Patowhiz commented
This is ready for review.

2021-03-03 10:27 UTC, lloyddewit commented
@Ivanluv Please could you review? thanks

2021-03-03 13:05 UTC, Ivanluv commented
@lloyddewit   the code looks okay from my end

2021-03-04 06:55 UTC, rdstern approved these changes

2021-03-04 08:47 UTC, lloyddewit requested changes

2021-03-04 08:47 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_SaveNameChanged(ucrChangedControl As ucrCore) Handles ucrSaveResultInto.ControlContentsChanged
The `ucrSaveResultInto.ControlContentsChanged` event is already handled below.
Also, where is the `SaveNameChanged` event handled?
Could we delete this sub (or combine it with the sub below)?

2021-03-04 08:47 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    ''' this will be raised the input name is changed and even when the ucrSave checkbox checked status is changed
```suggestion
    ''' this will be raised when the input name is changed and even when the ucrSave checkbox checked status is changed
```

2021-03-08 12:03 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_SaveNameChanged(ucrChangedControl As ucrCore) Handles ucrSaveResultInto.ControlContentsChanged
@lloyddewit it was being handled in the `dlgCalculator`. I added the extra `SaveResultChanged` event because of how `ucrCheck` was previously implemented. I have now removed it. `SaveNameChanged` as previously implemented will be enough.

2021-03-08 12:03 UTC, Patowhiz commented on instat/ucrCalculator.vb
> +    Private Sub ucrSaveResultInto_SaveNameChanged(ucrChangedControl As ucrCore) Handles ucrSaveResultInto.ControlContentsChanged
This is now ready for review.

2021-03-09 16:29 UTC, Patowhiz commented
@rdstern @lloyddewit this is ready for review.

2021-03-09 17:24 UTC, rdstern approved these changes

2021-03-10 11:52 UTC, lloyddewit approved these changes

2021-03-10 11:53 UTC, merged

2021-03-10 14:55 UTC, shadrackkibet commented on instat/ucrSave.vb
> +        btnColumnPosition.Visible = ucrChkSave.Checked
This change has caused a bug in all dialogs that use save control. The position button is not always visible when the checkbox is checked. See all graphic dialogs for example **Describe>Specific>**
![image](https://user-images.githubusercontent.com/26301973/110648325-a9ac8f00-81c9-11eb-826b-9d2f16506046.png)

2021-03-10 19:58 UTC, Patowhiz commented on instat/ucrSave.vb
> +        btnColumnPosition.Visible = ucrChkSave.Checked
@shadrackkibet thank you for spotitng this. I have corrected it in PR #6255