Inventory Plot dialog autofills defined elements, autofill implemented for multiple receivers, Is_Element property created for climatic dataframes
africanmathsinitiative/R-Instat pull request #6233
Opened 2021-02-22 16:21 UTC by dannyparsons

fixes #5929
This replaces #5951 (not branched)

- Autofill enabled for multiple receivers - all valid columns will autofill (unlike for single receivers where autofill only happens if there is exactly one valid column)
- `Is_Element` metadata property added for climatic data frames. Receivers can be set to autofill all climatic elements with `Receiver.SetClimaticType("element")`
- Implemented for the elements receiver on Inventory Plot dialog

@africanmathsinitiative/developers This is ready for review.

2021-02-22 16:23 UTC, dannyparsons commented on instat/ucrReceiver.vb
> +            SetIncludedAutoFillProperties(dctTemp)
This allows developers to set this property in the same way i.e. `ucrReceiverElements.SetClimaticType("element")` although it's a different metadata property to specific elements.

2021-02-22 16:23 UTC, dannyparsons commented on instat/ucrReceiverSingle.vb
> -    End Sub
Moved to base class as multiple receiver now does the same.

2021-02-22 16:23 UTC, dannyparsons commented on instat/ucrReceiverSingle.vb
> -    End Sub
Moved to base class as multiple receiver now does the same.

2021-02-22 17:05 UTC, dannyparsons commented
Note that this will not work with existing `DataBook` files which are already defined as climatic, without defining as climatic again, since the `Is_Element` property won't be in the metadata for those files.

2021-02-23 18:30 UTC, rdstern requested changes
@dannyparsons I think this dialogue may be working, but it has re-uncovered another bug.

I tried with 6 stations from Zambia, defined as climatic (can check with the metadata) and it doesn't autofill in this dialogue.  I pressed reset and still nothing.

I returned to the define climatic which filled automatically and then returned to the dialogue.  Now it works - at least when I press reset.

I think Rachel found this issue when preparing the videos., i.e. that the information on the climatic definition doesn't completely survive saving.  It does in the metadata, but not completely.  I hope this message is clear.

2021-02-25 11:44 UTC, dannyparsons commented
Ok, yes that sounds like a general issue with the climatic metadata. I suggest not addressing that in this PR.

If there's not an issue for this already can we make one for it?

2021-03-02 11:22 UTC, lloyddewit approved these changes

2021-03-02 15:20 UTC, shadrackkibet approved these changes

2021-03-03 10:16 UTC, lloyddewit commented
@rdstern Please could you approve? thanks

2021-03-03 10:30 UTC, rdstern approved these changes

2021-03-03 11:05 UTC, merged