Fixing bug in the File > Open from File dialogue
africanmathsinitiative/R-Instat pull request #6242
Opened 2021-02-25 11:06 UTC by N-thony

fixes #6229 
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks

2021-03-02 11:01 UTC, lloyddewit requested changes

2021-03-02 11:01 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +                End If
Replace with a select/case statement?

2021-03-02 13:16 UTC, N-thony commented
@lloyddewit  thanks for the comment above. I think have resolved it.

2021-03-02 14:26 UTC, lloyddewit submitted a review, later dismissed

2021-03-02 14:26 UTC, lloyddewit commented
@rdstern please could you test? thanks

2021-03-07 11:14 UTC, rdstern approved these changes

2021-03-07 12:25 UTC, shadrackkibet commented
I tested and found some minor design issues that should be easy to fix here instead of another PR. See the below screenshot.

- There is a control that overlaps with preview when loading the `.dly` file
- Remove unnecessary space between the label and input in the save control

![image](https://user-images.githubusercontent.com/26301973/110239594-dc038580-7f58-11eb-8cfa-e350b4725553.png)

2021-03-07 13:58 UTC, rdstern commented
@shadrackkibet sounds good

2021-03-07 20:02 UTC, N-thony commented
@shadrackkibet thanks for your comments. I think have resolved them? could you test?

2021-03-08 06:44 UTC, shadrackkibet commented
@N-thony can you edit this PR title so that it contains the details of the bug fixed and the changes made? Check the message below from Danny sent to your mailbox.

>1. Pull Request Titles
The PR title will be used in the release notes. Please make sure the title of your PR is descriptive of the change you are making (but not too long). Also, try to make it less technical as possible. These will be read by users, so imagine a user without programming knowledge reading your PR title. Will they understand what this actually changes in the software? Sometimes it's unavoidable that the title will be technical, but for most dialog changes, we should be able to make them clear to users. In general, include the dialog name in the title if the PR is on a specific dialog.

>Examples
Good: Corrected consecutive wet days calculation on rainfall quality control
Good: Cumulative/Exceedance Graph: Added points option
Good: Small bug fixes on NetCDF dialog
Bad: issue #8888
Bad: Bug fix
Bad: dlgMakeDate

>The PR title can be edited after its created so you can improve it if you think of a more appropriate title. Reviewers should also review the PR title and check it's a sensible description.

2021-03-08 07:54 UTC, shadrackkibet commented
Another problem is that the new data frame name is not retained on reopen. It is always reset to the default name.

2021-03-08 12:51 UTC, N-thony commented
> Another problem is that the new data frame name is not retained on reopen. It is always reset to the default name.

@shadrackkibet thanks for your comment, would you come again. I have tried this and the new data frame name is retained on reopening.

2021-03-08 13:10 UTC, shadrackkibet commented
> > Another problem is that the new data frame name is not retained on reopen. It is always reset to the default name.
> 
> @shadrackkibet thanks for your comment, would you come again. I have tried this and the new data frame name is retained on reopening.

- Open a file say `.csv` from your directory
- Change the **New Data frame name** in the dialog to say "myData"
- Click Ok / Close the dialog 
- Now reopen the dialog

Notice that the name ("myData") is lost.

2021-03-08 15:14 UTC, N-thony commented
> > > Another problem is that the new data frame name is not retained on reopen. It is always reset to the default name.
> > 
> > 
> > @shadrackkibet thanks for your comment, would you come again. I have tried this and the new data frame name is retained on reopening.
> 
> * Open a file say `.csv` from your directory
> * Change the **New Data frame name** in the dialog to say "myData"
> * Click Ok / Close the dialog
> * Now reopen the dialog
> 
> Notice that the name ("myData") is lost.

@shadrackkibet I think it is fine since the New Data frame name always by default will be the file name. If you click on a file, it sets the name of the file.

2021-03-10 10:38 UTC, lloyddewit commented
> 
> @shadrackkibet I think it is fine since the New Data frame name always by default will be the file name. If you click on a file, it sets the name of the file.

@N-thony As a general principle, if the user closes a dialog, and then reopens it later, the dialog should return to the state it was in when it was closed. Therefore I think @shadrackkibet 's comment from 08 March is still open. Is it difficult to fix?

2021-03-10 13:06 UTC, N-thony commented
@lloyddewit thanks for your comment. I think have resolved it.

2021-03-12 11:31 UTC, lloyddewit commented
> 
> 
> > @shadrackkibet I think it is fine since the New Data frame name always by default will be the file name. If you click on a file, it sets the name of the file.
> 
> @N-thony As a general principle, if the user closes a dialog, and then reopens it later, the dialog should return to the state it was in when it was closed. Therefore I think @shadrackkibet 's comment from 08 March is still open. Is it difficult to fix?

@N-thony I tested and this now seems to be resolved - thanks

2021-03-12 11:32 UTC, lloyddewit approved these changes

2021-03-12 11:33 UTC, lloyddewit commented
@rdstern please could you retest? thanks

2021-03-12 21:54 UTC, rdstern requested changes
The problem is changed but partly still remains.
I opened an Excel file from the library as described before - it worked fine.
Then I tried to open a new file and it gave me the provisional name of the previous one.  This is an occasion when the name freom before should be updated, rather than just remembered.

2021-03-13 09:33 UTC, N-thony commented
@rdstern thanks for your comment above. I think have resolved it. Please could you test?

2021-03-13 10:15 UTC, rdstern approved these changes

2021-03-15 09:50 UTC, lloyddewit approved these changes

2021-03-15 09:51 UTC, merged