Opening from script feature
africanmathsinitiative/R-Instat pull request #6247
Opened 2021-03-03 11:37 UTC by Ivanluv

This currently implements the opening of the split dialogue from script ,though not fully functional

Among the things not functioning as required are:

- Incorrect updating of controls that use `AddAdditionalCodeParameterPair()`

2021-03-04 12:05 UTC, lloyddewit requested changes
@Ivanluv This is just a partial review. I did not look at `clsRLink.vb` and `dlgSplitText.vb` yet.

2021-03-05 08:46 UTC, lloyddewit requested changes

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +    Private lstRCodeStructure As List(Of RCodeStructure)
We could make this a public property.
The `Set` could also set `bReset = True`.

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +            SetDefaults(lstRCodeStructure)
This parameter is not needed

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +    Private Sub SetDefaults(Optional lstOfRCodeStructure As List(Of RCodeStructure) = Nothing)
Parameter is not needed

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +            lstRCodeStructure = Nothing
Move to outside of `if` statement?
Comment also needs fixing

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +            lstRCodeStructure = Nothing
Move to outside of `if` statement?

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +                MsgBox("Developer error:The Script must be an RFunction")
If this line is reached then, after the message box, the dialog will be in an incomplete state. Better to restructure the `If` conditions above?

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +            If Not IsNothing(TryCast(lstOfRCodeStructure(0), RFunction)) Then
Move all the `lstRCodeStructure` validity checks to the start of this function. If any of the checks fail then display a message box, reset `lstRCodeStructure` to `Nothing` and then continue.

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +                        Else
Move all the `lstRCodeStructure` validity checks to the start of this function.

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +                            If Rfunction Is clsTextComponentsFixed Then
Replace this `If ElseIf` structure with `Select Case`

2021-03-05 08:46 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +                For Each Rfunction In {clsTextComponentsFixed, clsTextComponentsMaximum, clsBinaryColumns}
Rename `Rfunction` e.g. to `clsFunction`?

2021-03-08 14:51 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +                                ucrBase.clsRsyntax.SetBaseRFunction(clsBinaryColumns)
Bug here?
```suggestion
                                ucrBase.clsRsyntax.SetBaseRFunction(clsTextComponentsMaximum)
```

2021-03-09 07:44 UTC, Ivanluv commented on instat/instat.vbproj
> +      <HintPath>..\..\..\..\Pictures\RScript.dll</HintPath>
I would prefer adding in in the  ..\Source\Repos\R-Instat\packages

2021-03-09 11:16 UTC, Ivanluv commented on instat/ucrInputComboBox.vb
> +    Public Sub SetItems(dctItemParameterValuePairs As Dictionary(Of String, String), Optional bClearExisting As Boolean = True, Optional bSetCondtions As Boolean = True, Optional bNewHasRParamFunctio
I have fixed this in a new PR #6252

2021-03-09 11:17 UTC, Ivanluv commented on instat/ucrInputComboBox.vb
> +                End If
this is now in PR #6252

2021-03-09 12:02 UTC, Ivanluv commented on instat/dlgSplitText.vb
> +    Private lstRCodeStructure As List(Of RCodeStructure)
Done

2021-03-09 12:02 UTC, Ivanluv commented on instat/dlgSplitText.vb
> +    End Sub
Done

2021-03-09 12:07 UTC, Ivanluv commented on instat/dlgSplitText.vb
> +    Private Sub SetDefaults(Optional lstOfRCodeStructure As List(Of RCodeStructure) = Nothing)
Done

2021-03-09 12:24 UTC, Ivanluv commented on instat/dlgSplitText.vb
> +            lstRCodeStructure = Nothing
Done

2021-03-09 12:56 UTC, Ivanluv commented on instat/dlgSplitText.vb
> +                            If Rfunction Is clsTextComponentsFixed Then
Done

2021-03-09 12:58 UTC, Ivanluv commented on instat/dlgSplitText.vb
> +                For Each Rfunction In {clsTextComponentsFixed, clsTextComponentsMaximum, clsBinaryColumns}
I have reimplemented that function

2021-03-09 12:58 UTC, Ivanluv commented on instat/dlgSplitText.vb
> +                                ucrBase.clsRsyntax.SetBaseRFunction(clsBinaryColumns)
Thanks.I have changed this

2021-03-09 16:10 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +                MsgBox("Developer error:The Script must be an RFunction")
Done, thanks

2021-03-09 16:14 UTC, lloyddewit requested changes

2021-03-15 15:04 UTC, lloyddewit commented
@maxwellfundi This is a long-term, ongoing PR. @Ivanluv and I agreed that we will put this PR on hold during the sprint, and we will continue after 26 March 2021. I'll be happy to review this PR again after the sprint.

2021-03-16 07:05 UTC, maxwellfundi commented
@lloyddewit  that sound okay, I will now change its milestone

2021-04-12 08:34 UTC, closed without merging