implemente functionality of  circular plots dialog
africanmathsinitiative/R-Instat pull request #6262
Opened 2021-03-12 13:13 UTC by HawardKetoyoMsatsi

Fixes #6060
@africanmathsinitiative/developers @rdstern @lloyddewit this is ready for review.
Implemented code for dlgCircularDensity plot. The dialog implements the Circular Density plot, Rose plot, and Scatter plot.

2021-03-16 09:04 UTC, Wycklife reviewed
I have done some basic tests on this and the following are my comments:
1. Clicked on the first option(Rose Plot) and select the units combobox. You have radinas instead of radians.

![WhatsApp Image 2021-03-16 at 10 50 01](https://user-images.githubusercontent.com/33898404/111282876-85303700-864f-11eb-8c44-a0bbecf06e67.jpeg)

2.  When I select hours as the unit with the first option, the output still has pi. See below.
![WhatsApp Image 2021-03-16 at 10 53 52](https://user-images.githubusercontent.com/33898404/111282486-1b179200-864f-11eb-8d22-e6a3e250ec91.jpeg)

2021-03-16 09:14 UTC, HawardKetoyoMsatsi commented
```
# Code generated by the dialog, Circular Plots

myws <- data_book$get_columns_from_data(data_name="notmydata", col_names="myws")
plot(circular::density.circular(x=myws, bw=25, kernel="vonmises", na.rm=TRUE), main=" ", xlab=" ", ylab=" ", shrink=1.3, units="degrees")
last_graph <- grDevices::recordPlot()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="notmydata")
data_book$get_graphs(data_name="notmydata", graph_name="last_graph")
rm(list=c("last_graph", "myws"))
```

@rdstern @dannyparsons we have modified the R-Instat script code to enable the above code produced by the dialog to display and save the graph. And our investigations show that the function recordPlot can also work for ggplots.

We now need to discuss with @dannyparsons on how this can be generally supported for other dialogs that use non ggplot package.

2021-03-16 13:34 UTC, rdstern commented
@HawardKetoyoMsatsi this is looking good.  There is a lot that can be added - with many options available, but I would like to merge this quickly and then make a separate issue for refinements.
a) There are the changes noted by @Wycklife above
b) You have Kernel visible for each type of plot, but I think it only applies to the density.
c) Keeping the overall size the same could you have `Circular: ` in front of the 3 buttons at the top.  Then the first one says Histogram (Rose Plot), the second says Density Plot and the third says Scatter Plot as now.

2021-03-16 14:20 UTC, dannyparsons commented
I think it's ok for enhancements to be left as a separate PR later, but bugs or errors should be addressed before merging.
e.g. I think these should be fixed before merging:
> You have radinas instead of radians.

> b) You have Kernel visible for each type of plot, but I think it only applies to the density.

2021-03-17 09:18 UTC, HawardKetoyoMsatsi commented
@Wycklife @rdstern The above issues have been fixed, kindly have a look.

@Wycklife When one selects hours as the unit with the first option, the output still has pi since conversion is done from Hour Angles to degrees which appear in terms of Pi, so it is just a conversion from one scale to another but they don't calibrate in the hour-scale.

2021-03-18 06:49 UTC, HawardKetoyoMsatsi commented
@dannyparsons @rdstern @Patowhiz suggestions that arose from the discussion among @Patowhiz and @dannyparsons and I have been implemented herein. kindly have a close look at it.

2021-03-18 07:13 UTC, maxwellfundi commented
@Wycklife  please re-review this PR

2021-03-18 07:34 UTC, Wycklife commented
> @Wycklife please re-review this PR

Okay

2021-03-18 09:33 UTC, Wycklife commented
I have tested this and it seems to work well from my end.

2021-03-18 10:14 UTC, maxwellfundi commented
@rdstern This now is ready for your review.

2021-03-18 10:15 UTC, Wycklife approved these changes

2021-03-18 10:34 UTC, dannyparsons requested changes
- Some small formatting suggestions
- I tested with the three different graph display options: output window, R viewer and separate viewer and all worked
- However, when I click display last graph on the toolbox the  window pops up but it's blank. Can you check this?

2021-03-18 10:34 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +  if(any(c("ggplot", "gg", "gtable", "grob", "ggmultiplot", "ggsurv", "ggsurvplot", "openair","recordedplot") %in% class(object))) {
```suggestion
  if(any(c("ggplot", "gg", "gtable", "grob", "ggmultiplot", "ggsurv", "ggsurvplot", "openair", "recordedplot") %in% class(object))) {

```

2021-03-18 10:34 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +    else if(type == graph_label) out = names(private$objects)[sapply(private$objects, function(x) any(c("ggplot", "gg", "gtable", "grob", "ggmultiplot", "ggsurv", "ggsurvplot", "openair","recordedplo
```suggestion
    else if(type == graph_label) out = names(private$objects)[sapply(private$objects, function(x) any(c("ggplot", "gg", "gtable", "grob", "ggmultiplot", "ggsurv", "ggsurvplot", "openair", "recordedplot") %in% class(x)))]

```

2021-03-18 10:34 UTC, dannyparsons commented on instat/static/InstatObject/R/stand_alone_functions.R
> +return(grDevices::recordPlot())
Please use the correct indentation in a function. If you edit in RStudio this should be done automatically.

2021-03-18 12:45 UTC, rdstern requested changes
This is looking good now.
a) The kernel is no longer in the dialogue for non-density graphs, but it is still in the R code you generate.  It doesn't cause trouble, but should only be in the command for a density plot.
b) You have shrink=2 as your default.  The default in the package is 1, so I suggest you change it to 1.  
c) If you wish you could start the process of adding arguments to the dialogue by including Shrink as a label and then an up-down.  It could go from perhaps 0.5 to 3 in steps of 0.1.  It applies to all 3 buttons.

2021-03-19 06:37 UTC, HawardKetoyoMsatsi commented
@dannyparsons @rdstern the above issues have been fixed, kindly take a look.

2021-03-19 09:19 UTC, dannyparsons requested changes
R code formatting looks good now. Couple of small comments below.

I checked the View Last Graph button again and it still shows a blank window. Did you check this?

2021-03-19 09:19 UTC, dannyparsons commented on instat/dlgCircularDensityPlot.vb
> +    End Sub
Empty sub?

2021-03-19 09:19 UTC, dannyparsons commented on instat/dlgCircularDensityPlot.vb
> +        clsScatterPlotFunction.AddParameter("sep", 0.0003, bIncludeArgumentName:=True, iPosition:=5)
bIncludeArgumentName:=True is the default so you don't need to include that. You can remove this parameter and it will function the same.

2021-03-23 09:40 UTC, HawardKetoyoMsatsi commented
> * Some small formatting suggestions
> * I tested with the three different graph display options: output window, R viewer and separate viewer and all worked
> * However, when I click display last graph on the toolbox the  window pops up but it's blank. Can you check this?

Hi @dannyparsons,  @Patowhiz is investigating your third issue raised herein.

2021-03-24 12:12 UTC, shadrackkibet approved these changes
This is already working therefore we can have it as an initial implementation. I think we can have the issue with the last graph investigated as a separate issue. I therefore approve. Over to you @lloyddewit , @dannyparsons  and @rdstern

2021-03-24 12:42 UTC, dannyparsons commented
I'd like to understand the last graph issue before merging, as this may affect the dialog implementation. It may also have effects on other dialogs.

2021-03-25 20:52 UTC, rdstern submitted a review, later dismissed
@haward great this seems to work now.  I just notice that the plot.circular code still includes the kernel ="von.mises".  which is not needed there.  My understanding is that it is only needed for the density.  I am happy you have taken it out of rose plot.
I am approving as this isn't serious - it is ignored by the function.  But nice (assuming it is very quick) to make this small change.

2021-03-26 07:44 UTC, lloyddewit submitted a review, later dismissed

2021-03-26 07:46 UTC, lloyddewit commented
> 
> 
> @haward great this seems to work now. I just notice that the plot.circular code still includes the kernel ="von.mises". which is not needed there. My understanding is that it is only needed for the density. I am happy you have taken it out of rose plot.
> I am approving as this isn't serious - it is ignored by the function. But nice (assuming it is very quick) to make this small change.

@HawardKetoyoMsatsi Would you like to make the optional change suggested by @rdstern or can we go ahead and merge? 
@dannyparsons You asked to review before this PR was merged. You already reviewed above. Do you wish to do a final review?

Thanks

2021-03-26 08:00 UTC, HawardKetoyoMsatsi commented
> > @haward great this seems to work now. I just notice that the plot.circular code still includes the kernel ="von.mises". which is not needed there. My understanding is that it is only needed for the density. I am happy you have taken it out of rose plot.
> > I am approving as this isn't serious - it is ignored by the function. But nice (assuming it is very quick) to make this small change.
> 
> @HawardKetoyoMsatsi Would you like to make the optional change suggested by @rdstern or can we go ahead and merge?
> @dannyparsons You asked to review before this PR was merged. You already reviewed above. Do you wish to do a final review?
> 
> Thanks

@lloyddewit Yes please let let me make the requested changes before you merge.

2021-03-26 08:52 UTC, HawardKetoyoMsatsi commented
@lloyddewit I have removed the kernel ="von.mises" parameter as requested and it is okay now, back to you and @dannyparsons .

2021-03-26 09:49 UTC, lloyddewit approved these changes

2021-03-26 09:50 UTC, lloyddewit commented
@HawardKetoyoMsatsi Thank you

@rdstern @dannyparsons If you are both happy, then I'll merge, thanks

2021-03-26 10:22 UTC, rdstern approved these changes

2021-03-26 10:39 UTC, dannyparsons requested changes
The issue with view last graph is potentially general and relates to the changes to the Data Book in this PR. So I would like to understand this better before merging.

@Patowhiz I think you're probably busy with other urgent tasks. @lilyclements Could you take a quick look at the displaying of last graph. I guess something might need to be updated in the view last graph R method to account for record_plot. If not I could have a look later.

2021-03-26 16:05 UTC, dannyparsons commented
@HawardKetoyoMsatsi I found the issue which was the recordPlot not saving objects correctly. To save time I opened a new PR with this small change #6346

2021-03-26 16:55 UTC, merged