One Variable Frequency - Graph bug fix
africanmathsinitiative/R-Instat pull request #6270
Opened 2021-03-15 10:37 UTC by lilyclements

Fixes some of #6201 

@africanmathsinitiative/developers this is ready for review. 

Changes made:
* Changed `sjplot` to `plot_frq` since the plot wasn't working otherwise
* Added the `list` function depending if one variable is being plotted, or several variables. This fixes a bug (not outlined in any issue) where there was an error if only one variable was in the receiver for "Graph" or "Both".
* Minor design tidy up

Issue #6201 has three other requests that I haven't looked at in this PR - I'm unsure if these three other fixes are in their own separate issues. If they are, then #6201 can be closed when this is merged.

2021-03-15 11:25 UTC, rdstern requested changes
@lilyclements great.  This now works.  
There is just one item you may quickly be able to examine.  It currently calls plot_frq inside plot_grid.  This currently means it is harder to look at, in the R viewer.  We expect to improve that, but (only if very quick) do we need the plot_grid is only a single variable is plotted?  Could we then just call plot_frq directly?  That would make it a ggplot graph, rather than a grid.

Then I would like to see this merged - because it does now work.  There is a lot more work that is possible, and I suggest worthwhile, to add more options - and also to stop messy graphs.  here is an example:
![image](https://user-images.githubusercontent.com/11226469/111146008-dae9de00-8580-11eb-8587-d13d1f0e6f8e.png)

But that should be investigated initially by others, not by Lily

If the change suggested above takes more than a few minutes, then leave it for later work and we'll merge this.

2021-03-15 12:32 UTC, lilyclements commented
@rdstern It's definitely possible, but I'm not sure how to do it because there are multiple functions. It would be quicker for someone else to do (either now or I can update the issue to add it in)

2021-03-15 13:45 UTC, rdstern approved these changes
Bug fixed so happy to approve.  There is lots more that can be done later, but useful to have this working nicely as the starting point.

I suggest this can close issue 6201.  I will open a new issue on possible further improvements.

2021-03-15 14:15 UTC, lloyddewit approved these changes

2021-03-15 14:27 UTC, merged

2021-03-20 11:23 UTC, shadrackkibet commented on instat/dlgOneWayFrequencies.vb
> +        clsPlotGrid.AddParameter("x", clsRFunctionParameter:=clsSjPlotList)
Position? Also in other places?

2021-03-20 11:26 UTC, shadrackkibet commented
Also to note that **View last graph** doesn't work for this dialog. It is a good example where `ggplotify::as.ggplot()` will work. I do not think the graph will loose its features due to conversion.

2021-03-20 11:35 UTC, lilyclements commented on instat/dlgOneWayFrequencies.vb
> +        clsPlotGrid.AddParameter("x", clsRFunctionParameter:=clsSjPlotList)
Thanks for this. I think someone may be working on this dialog shortly (see issue #6279) so I've added a comment requesting the parameter positions added then (just to avoid conflicts in case I add it in and it's not merged quickly!)

2021-03-20 11:46 UTC, rdstern commented
@HawardKetoyoMsatsi is going to look at #6279, but hasn't started yet.

There are 2 points to fix in this issue, and then I am hoping that @jkmusyoka can suggest further additions to the dialogue.  As @shadrackkibet is clearly back, then I would be delighted if he could take over Haward's role.  It is his sort of job, and I think quick for him, while tricky for Haward?

2021-03-20 11:50 UTC, shadrackkibet commented on instat/dlgOneWayFrequencies.vb
> +        clsPlotGrid.AddParameter("x", clsRFunctionParameter:=clsSjPlotList)
That is fine @lilyclements