Allowing more variable types for (General) modelling
africanmathsinitiative/R-Instat pull request #6276
Opened 2021-03-15 18:25 UTC by lilyclements

Fixes #6197 

Changes
* Added a label in the general modelling dialog which states the variable type (or if the variable type is unsuitable for a model)
* Allowed numeric-type distributions to work for positive integers
* Added a new type for distributions - "two way numeric" - to account for when data is binary (note that for `binomial` or `quasibinomial`, a numeric is accepted only if it is binary, that is, it is 0/1)

2021-03-15 18:31 UTC, lilyclements reviewed
@dannyparsons I have made the changes we discussed earlier to the distributions. I've made a few comments below - would you mind taking a look?

2021-03-15 18:31 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +        type = "two level numeric"
I have kept "two level numeric" and "two level factor" separate for now. I can combine them together, however.
One reason I kept them separate is because I noticed in "Two Variable Fit Model" I think `ucrReceiverExplanatory.strCurrDataType = "two variable numeric"` would need to be added into l. 477 (`DataTypeAccepted` sub). However, do not think "two variable factor" is needed there.

2021-03-15 18:31 UTC, lilyclements commented on instat/static/.old/data_object.R
> +    type = "two level factor"
I just noticed this is the only place we use "2 level factor" not "two level factor" so changed it in case of future bugs.
Should I add in the "two level numeric" type in this R file as well?

2021-03-15 18:43 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +        type = "two level numeric"
Good idea, that sounds very useful to keep them separate!

2021-03-15 18:45 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +        type = "two level numeric"
Can you also change `private$data[[col_name]]` to `curr_col` and then on 1394 change `use_current_filter = TRUE` so that  it's checking on the filtered data.

2021-03-15 18:48 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
>      if(length(levels(curr_col))==2) type = "two level factor"
Can you change this such that it checks the number of non-empty levels? An example is a 3-level factor where we filter down to 2 levels in R-Instat. We would like this to return as `"two level factor"` because when you run the dialog there will be only 2 levels due to the filter.

2021-03-15 18:52 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +      else if(is.integer(private$data[[col_name]])) {
Here we could do `all(a == as.integer(a))` so that it also captures numeric columns which only have integers (as opposed only to integer type columns).

2021-03-16 09:40 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +        type = "two level numeric"
Yes will do. The checks on numerics/integers/positive integers also use `col_name`. Should I change these to `curr_col` too?

2021-03-16 10:21 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +        type = "two level numeric"
Yes, all the checks should be on `curr_col`

2021-03-16 12:38 UTC, lilyclements commented
@dannyparsons this is ready for re-review

2021-03-17 12:04 UTC, dannyparsons requested changes
A few issues found:

- When I opened the dialog for the first time the checkbox for convert to numeric was visible but the receive is empty, so I think just needs to be checked on first opening
- When I changed response variable from numeric to factor it doesn't update the response variable type. Could the R function return "factor" so it can be displayed? The same happened for a logical column and also a 0-1 numeric column. Maybe the label is not updating correctly?
- Also it didn't let me choose a distribution when the response variable was logical
- When I had stuff filled in and clicked reset I got this message: "Developer error: Cannot set value of ucrFamily because cannot find a distribution matching the function and parameter given"

2021-03-18 12:54 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +    if(nlevels(curr_col)==2 | nlevels(factor(curr_col))==2) type = "two level factor"
Thanks! When should a `||` be used instead of a `|`?

2021-03-18 13:53 UTC, lilyclements commented
@dannyparsons thank you for the review - I've addressed the changes, can you have another look?

2021-03-18 16:34 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +    if(nlevels(curr_col)==2 | nlevels(factor(curr_col))==2) type = "two level factor"
Good question. `||` always returns a single logical value whereas `|` is vectorised. It doesn't matter in this case, because both give the same but `If` gives a warning if more than one logical value is provided, so this forces it as one.

Try this to see the difference:
```r
1:10 > 5 | (1:10 %% 2) == 0
1:10 > 5 || (1:10 %% 2) == 0
```
Here is quite a nice explanation https://stackoverflow.com/a/22251971/6424231

2021-03-18 16:50 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +    if(nlevels(curr_col)==2 | nlevels(factor(curr_col))==2) type = "two level factor"
Ah interesting! Thank you!

2021-03-18 18:02 UTC, dannyparsons commented on instat/dlgFitModel.vb
> +            ucrChkConvertToVariate.Visible = False
Instead of this, can you run `ResponseConvert()` as the last line of `SetRCodeForControls()`? That way the settings for the checkbox is done consistently in a single place.

2021-03-18 18:15 UTC, dannyparsons reviewed
Looks good. From my last list of issues, only the developer error remains. I identified when it happens. It seems to only be when the response variable is an "unsuitable type". Then click Reset then you get the dev error. I think this is coming from `ucrDistribution`.

Also, when the response variable is character, convert to numeric checkbox makes everything `NA` so the model gives an error. I think we only want convert to numeric for factor? Check with @rdstern 

These are small issues so may not be that important.

2021-03-19 14:50 UTC, lilyclements commented
Thanks for identifying this - I'm unsure how to fix it. Would you mind taking a quick look?

I've sorted the issue with the visibility of the ucrChk

2021-03-22 12:37 UTC, Ivanluv commented
@lilyclements  everything including the code looks good by me .For the issue on the developer error by the distribution control ,I think that requires more work within the distribution control

2021-03-26 09:10 UTC, lilyclements commented
@africanmathsinitiative/developers this is ready to review

2021-03-26 09:35 UTC, dannyparsons approved these changes
Since the developer error was an existing issue, and not a major one, I suggest this is approved due to other more urgent tasks.

2021-03-26 09:36 UTC, dannyparsons commented
@rdstern Could you also test?

@lilyclements Could you open a separate issue for the developer error?

2021-03-26 10:00 UTC, lilyclements commented
Have now reported the error in #6345 - thanks.

2021-03-26 10:37 UTC, rdstern approved these changes
@lilyclements great.

I would like a discussion now on what you consider to be the next steps in this "system".  For example I notice it correctly detected an integer variable in the survey data and suggested a Poisson model.  When I had a similar variable but with zeros, it said it wasn't a category.

However this is a big step forwards.  Next we avoid the developer bug by always having some possible distributions!

2021-03-26 11:01 UTC, merged

2021-03-26 11:02 UTC, lloyddewit commented
@lilyclements Thank you for this PR. Please could you check that the new title for this PR is correct (and change if not)? thanks