Separating the sub-dialog for Merge into two sub-dialogs
africanmathsinitiative/R-Instat pull request #6281
Opened 2021-03-16 15:27 UTC by lilyclements

Replaces #6277
Fixes #6265

This PR separates the two tabs in the original sub-dialog into two separate sub dialogs (as described in #6265).

@dannyparsons this is ready for review. From what I can tell, the dialogs still automatically add in columns you merge by, even if you try to remove those columns in the "Columns to Include" tab. Is this okay?

2021-03-17 10:10 UTC, dannyparsons commented on instat/sdgMerge.vb
>      Private bEnableColumnSelection As Boolean = True
Can you remove this and also remove from the Setup method? This is only needed in the other subdialog now.

2021-03-17 10:32 UTC, dannyparsons requested changes
Looks good. Some suggestions:
- Change "Merging by" label to "Joining by" for consistency
- Change "Column Options" button to "Column Selection"
- Can you make the multiline textbox to be longer like it was before? I think it was 3 or 4 lines deep before.
- Can you add something to highlight the "Joining Options" button when the no joining columns message is displayed? Something like changing the `BackColour` property to "LemonChiffon"? Then it goes back to normal colour when there some joining columns.

Also, I just noticed that `dlgMergeAdditionalData` will also need to be updated as well. It only need the "Joining Options" subdialog. Could you also update this dialog?

2021-03-18 11:40 UTC, lilyclements commented
@dannyparsons I have now implemented the changes you suggested. Can you re-review?

2021-03-18 11:53 UTC, dannyparsons commented on instat/dlgMerge.vb
> +                cmdJoinOptions.BackColor = SystemColors.ControlLight
I think that should just be `Control`?
```suggestion
                cmdJoinOptions.BackColor = SystemColors.Control
```

2021-03-18 12:06 UTC, dannyparsons commented on instat/sdgMergeColumnsToInclude.vb
> +                If Not ucrReceiverFirstSelected.GetVariableNamesAsList.Contains(clsTmpParam.strArgumentValue.Trim(Chr(34))) Then
This should be the second selector. Possibly an existing bug!
```suggestion
                If Not ucrReceiverSecondSelected.GetVariableNamesAsList.Contains(clsTmpParam.strArgumentValue.Trim(Chr(34))) Then
```

2021-03-18 12:13 UTC, dannyparsons requested changes
Looks good, couple of small comments.

Also, can you remove `Optional bNewEnableColumnSelection As Boolean = True` from the SetUp function in `sdgMerge` as it's not needed now?

2021-03-18 12:19 UTC, dannyparsons commented on instat/dlgMerge.vb
> +                cmdJoinOptions.BackColor = SystemColors.ControlLight
Actually, I found an answer here to do it https://stackoverflow.com/a/25419219/6424231

VB is over complicated some times!

```vb
cmdJoinOptions.BackColor = SystemColors.ButtonFace
cmdJoinOptions.UseVisualStyleBackColor = True

```

2021-03-18 12:35 UTC, lilyclements commented on instat/dlgMerge.vb
> +                cmdJoinOptions.BackColor = SystemColors.ControlLight
Yeah control was giving a shade lighter for some reason! I'll try this - thanks!

2021-03-18 12:47 UTC, lilyclements commented
@dannyparsons thank you for the comments - I've made the changes now.

2021-03-18 14:14 UTC, dannyparsons approved these changes
Great, looking good. I've reviewed both code and functionality so either of @lloyddewit or @rdstern or another developer doing a second review will be sufficient.

2021-03-18 15:28 UTC, rdstern approved these changes
@lilyclements that's great and I am adding my approval.

But is there a good reason for the new button to be under the Options button.  I was a bit looking forward to it being on the right, rather than below?

2021-03-18 16:55 UTC, rdstern commented
I'm happy with the position of the Join Options button.  I wondered about Column Sewlection moving to be on the same "row" as the join options and its partner on the right of the dialogue, rather than below.

2021-03-18 18:43 UTC, dannyparsons commented
Yep good idea.

2021-03-18 18:49 UTC, dannyparsons approved these changes

2021-03-18 18:55 UTC, lilyclements commented
Sorry for the confusion - do you mean like this (which is the current PR)

![image](https://user-images.githubusercontent.com/21180424/111681705-78f8d500-881b-11eb-8786-90f6adc95965.png)

Or like this?
![image](https://user-images.githubusercontent.com/21180424/111681338-08ea4f00-881b-11eb-86d6-c019d9086d98.png)

Or like something else. Sorry!

2021-03-18 19:05 UTC, dannyparsons commented
The second!

2021-03-18 22:09 UTC, rdstern commented
I would like the third!  That's like the second, but with Column SElection moved to the right, so it is lined on the right with the end of the field above.  Possibly consider moving the Join Options button so it aligned on the left with the left of the field above and also the left of the Join button above.

2021-03-19 08:24 UTC, dannyparsons commented
Yes happy with that suggestion too.

2021-03-19 11:42 UTC, lilyclements commented
Great - I've moved it like this in the most recent commit:

![image](https://user-images.githubusercontent.com/21180424/111774926-02ee7f80-88a8-11eb-930a-9fe9ed72aa2e.png)

2021-03-19 11:48 UTC, dannyparsons commented
Sorry for another change, could you make them smaller so there's more space between them in the middle?

2021-03-19 12:25 UTC, lilyclements commented
Sure - this is the most recent commit 
![image](https://user-images.githubusercontent.com/21180424/111779508-2288a680-88ae-11eb-9165-8dd847d67baf.png)

2021-03-19 18:31 UTC, dannyparsons approved these changes

2021-03-19 18:31 UTC, merged

2021-03-20 10:10 UTC, shadrackkibet commented on instat/sdgMergeColumnsToInclude.vb
> +            clsMerge.AddParameter("x", clsRFunctionParameter:=ucrSelectorColumnsToIncludeFirst.ucrAvailableDataFrames.clsCurrDataFrame)
Parameter positions?

2021-03-20 10:10 UTC, shadrackkibet commented on instat/sdgMergeColumnsToInclude.vb
> +            clsMerge.AddParameter("y", clsRFunctionParameter:=ucrSelectorColumnsToIncludeSecond.ucrAvailableDataFrames.clsCurrDataFrame)
Also here

2021-03-20 10:16 UTC, shadrackkibet commented
@dannyparsons any reason why this PR is missing a label? I will add a feature label. Please remove if not needed.

2021-03-20 11:51 UTC, lilyclements commented on instat/sdgMergeColumnsToInclude.vb
> +            clsMerge.AddParameter("y", clsRFunctionParameter:=ucrSelectorColumnsToIncludeSecond.ucrAvailableDataFrames.clsCurrDataFrame)
Good point - made a PR in #6304 which adds these parameter positions

2021-03-20 13:41 UTC, dannyparsons commented
@shadrackkibet Thanks for the label, I had forgot.