Fixing when OK is enabled in the Start of Rains dialog
africanmathsinitiative/R-Instat pull request #6282
Opened 2021-03-16 17:08 UTC by lilyclements

Fixes #5925 

@africanmathsinitiative/developers this is ready to review

In this PR, the TestOK is changed after a minor bug was spotted.

2021-03-16 19:49 UTC, Wycklife submitted a review, later dismissed
This is working fine.

2021-03-16 20:03 UTC, Karakacha commented
I have also tested this and its working.

2021-03-17 05:34 UTC, Karakacha approved these changes
I tested it and it worked

2021-03-17 09:51 UTC, lloyddewit requested changes

2021-03-17 09:51 UTC, lloyddewit commented on instat/dlgStartofRains.vb
> +        If Not ucrReceiverRainfall.IsEmpty AndAlso Not ucrReceiverDate.IsEmpty AndAlso Not ucrReceiverDOY.IsEmpty AndAlso Not ucrReceiverYear.IsEmpty AndAlso ucrNudThreshold.GetText <> "" AndAlso ((u
I find one long line unreadable. A simple improvement would be to split it onto multiple lines (see below).
It would be even better to refactor this sub and simplify the logic. Could we set `bOKEnabled` to false on line 765, and then just pick out the conditions where `bOkEnabled` is true?
```suggestion
        If Not ucrReceiverRainfall.IsEmpty AndAlso
                Not ucrReceiverDate.IsEmpty AndAlso
                Not ucrReceiverDOY.IsEmpty AndAlso
                Not ucrReceiverYear.IsEmpty AndAlso
                ucrNudThreshold.GetText <> "" AndAlso
                (
                    (ucrChkNumberOfRainyDays.Checked AndAlso ucrNudRDMinimumDays.GetText <> "" AndAlso ucrNudRDOutOfDays.GetText <> "") OrElse
                    Not ucrChkNumberOfRainyDays.Checked) AndAlso
                (
                    (
                        (ucrChkTotalRainfall.Checked AndAlso ucrNudTROverDays.GetText <> "") AndAlso
                        ((rdoTRAmount.Checked AndAlso ucrNudTRAmount.GetText <> "") OrElse (rdoTRPercentile.Checked AndAlso ucrNudTRPercentile.GetText <> ""))) OrElse
                    Not ucrChkTotalRainfall.Checked) AndAlso
                (
                    (ucrChkDrySpell.Checked AndAlso ucrNudDSMaximumDays.GetText <> "" AndAlso ucrNudDSLengthOfTime.GetText <> "") OrElse
                    Not ucrChkDrySpell.Checked) AndAlso
                (
                    (ucrChkDryPeriod.Checked AndAlso ucrNudDPMaxRain.GetText <> "" AndAlso ucrNudDPRainPeriod.GetText <> "" AndAlso ucrNudDPOverallInterval.GetText <> "") OrElse
                    Not ucrChkDryPeriod.Checked) Then
```

2021-03-17 09:51 UTC, lloyddewit commented on instat/dlgStartofRains.vb
> +        If (ucrChkAsDoy.Checked AndAlso ucrInputNewDoyColumnName.IsEmpty) OrElse (ucrChkAsDate.Checked AndAlso ucrInputNewDateColumnName.IsEmpty) OrElse (ucrChkStatus.Checked AndAlso ucrInputNewStatu
Make more readable?
```suggestion
        If (ucrChkAsDoy.Checked AndAlso ucrInputNewDoyColumnName.IsEmpty) OrElse
                (ucrChkAsDate.Checked AndAlso ucrInputNewDateColumnName.IsEmpty) OrElse
                (ucrChkStatus.Checked AndAlso ucrInputNewStatusColumnName.IsEmpty) Then
            bOkEnabled = False
        End If
```

2021-03-17 11:16 UTC, lilyclements commented on instat/dlgStartofRains.vb
> +        If Not ucrReceiverRainfall.IsEmpty AndAlso Not ucrReceiverDate.IsEmpty AndAlso Not ucrReceiverDOY.IsEmpty AndAlso Not ucrReceiverYear.IsEmpty AndAlso ucrNudThreshold.GetText <> "" AndAlso ((u
I don't think I follow the final suggestion - picking out conditions where `bOkEnabled` is true is what is being run here, with additional false conditions given below?
I'm happy to commit these changes if you think that's easiest.

2021-03-17 14:28 UTC, lloyddewit approved these changes

2021-03-17 14:29 UTC, lloyddewit commented on instat/dlgStartofRains.vb
> +        If Not ucrReceiverRainfall.IsEmpty AndAlso Not ucrReceiverDate.IsEmpty AndAlso Not ucrReceiverDOY.IsEmpty AndAlso Not ucrReceiverYear.IsEmpty AndAlso ucrNudThreshold.GetText <> "" AndAlso ((u
@lilyclements I don't blame you :) Your suggestion sounds reasonable and I committed the suggested changes.

2021-03-17 14:30 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2021-03-22 04:42 UTC, shadrackkibet requested changes

2021-03-22 04:42 UTC, shadrackkibet commented on instat/dlgStartofRains.vb
>          End If
Syntax error with this `if` statement.

2021-03-22 09:04 UTC, lilyclements commented on instat/dlgStartofRains.vb
>          End If
Good point - have sorted it now, thanks.

2021-03-22 16:59 UTC, shadrackkibet approved these changes

2021-03-22 17:00 UTC, shadrackkibet commented
@lloyddewit please re-approve and merge.

2021-03-23 08:29 UTC, lloyddewit commented
@rdstern This PR is a releatively small change which has been tested by others. However, there have been some changes since the last test, and this PR hasn't been tested yet by you. 
Please could you test/approve? thanks

2021-03-23 08:29 UTC, lloyddewit approved these changes

2021-03-23 08:30 UTC, lloyddewit commented
@rdstern please can we wait for @rdstern 's approval before we merge? thanks

2021-03-23 16:51 UTC, rdstern approved these changes

2021-03-23 18:45 UTC, merged