Edits to ucrSave and Position subdialog
africanmathsinitiative/R-Instat pull request #6285
Opened 2021-03-17 07:53 UTC by Patowhiz

2021-03-17 11:11 UTC, maxwellfundi commented
@Patowhiz  please let remember to get this to ready for review when its done.

2021-03-20 12:28 UTC, shadrackkibet commented
@Patowhiz I was about to do this on a separate PR but noticed you are working on Non-numeric cases dialog. 

- Remove the unnecessary spacing between the label and input in the save control.
- Removed colons (:) on the label

![image](https://user-images.githubusercontent.com/26301973/111869272-9fd81800-898f-11eb-9ca9-11b9bb867c47.png)

2021-03-24 10:33 UTC, dannyparsons commented
Sometimes the extra spacing for the label is there because the French translation is longer. I'm not sure if that's the case here or not. Just something to be aware of.

2021-03-24 11:39 UTC, Patowhiz commented
@rdstern I have fixed the bugs you found. This is now ready for review.

2021-03-24 11:48 UTC, rdstern approved these changes
@Patowhiz great.  Fixed.

2021-03-24 12:06 UTC, dannyparsons commented on instat/static/InstatObject/R/Backend_Components/calculations.R
> +						               adjacent_column = ""
The alignment seems to be off here.

2021-03-24 14:08 UTC, maxwellfundi commented on instat/static/InstatObject/R/Backend_Components/calculations.R
> +						               adjacent_column = ""
@Patowhiz  these should be easy to fix, could you open this file in R-Studio to correct the alignement.

2021-03-24 14:09 UTC, maxwellfundi commented on instat/static/InstatObject/R/Backend_Components/calculations.R
> +						               adjacent_column = ""
@Patowhiz  it will be good to have this done as #6319 depend on this.

2021-03-25 16:24 UTC, dannyparsons reviewed
Just one comment for now from checking `ucrSave`. Will go through the other changes now.

2021-03-25 16:25 UTC, dannyparsons commented on instat/dlgFindNonnumericValues.vb
> +        'clsNonNumericFilterFunc.SetAssignTo("non_numerics_filter")
These commented lines could be removed now.

2021-03-25 16:26 UTC, dannyparsons commented on instat/dlgFindNonnumericValues.vb
> +        'clsNonNumericFilterFunc.SetAssignTo("non_numerics_filter")
Actually, this one for the filter should stay. Only `clsNonNumericCalcFunc` is linked to `ucrSave`.

2021-03-25 16:28 UTC, dannyparsons commented on instat/dlgFindNonnumericValues.vb
> +        'ucrSaveColumn.AddAdditionalRCode(clsNonNumericFilterFunc, iAdditionalPairNo:=1)
This line can be removed. `clsNonNumericFilterFunc` just has a fixed assign to, not related to the save control.

2021-03-25 16:58 UTC, dannyparsons requested changes
I think the change of defaults will fix the error I got. A few other small comments and a change I discussed with Patrick separately. Then I think it's ready.

2021-03-25 16:58 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +DataSheet$set("public", "add_columns_to_data", function(col_name = "", col_data, use_col_name_as_prefix = FALSE, hidden = FALSE, before, adjacent_column = "", num_cols, require_correct_length = TRUE,
You also need to set the default for `adjacent_column` in the same DataBook method.
I just got this error from the Combine Text dialog due to this I think.

![image](https://user-images.githubusercontent.com/11214914/112512375-39863780-8d8b-11eb-9788-29b45bcbfde2.png)

2021-03-25 17:47 UTC, Patowhiz commented on instat/static/InstatObject/R/Backend_Components/calculations.R
> +						               adjacent_column = ""
@dannyparsons this is because I changed this part with R Studio which auto formats the lines

2021-03-25 18:35 UTC, Patowhiz commented on instat/ucrSave.vb
> +                strControlValue = clsMainRCode.GetParameter(strReadNameFromParameterName).strArgumentValue
@dannyparsons done thanks.

2021-03-25 18:37 UTC, Patowhiz commented on instat/static/InstatObject/R/data_object_R6.R
> +DataSheet$set("public", "add_columns_to_data", function(col_name = "", col_data, use_col_name_as_prefix = FALSE, hidden = FALSE, before, adjacent_column = "", num_cols, require_correct_length = TRUE,
@dannyparsons done thanks.

2021-03-25 18:40 UTC, Patowhiz commented
@dannyparsons this is now ready for your review.

2021-03-26 10:29 UTC, dannyparsons approved these changes
Code looks good. @rdstern Could you do a quick final test to confirm it's still working as well as when you tested before the recent changes?

2021-03-29 10:56 UTC, rdstern approved these changes
@dannyparsons and @Patowhiz I am not quite sure what I am checking here:
1) I tried the calculator and it works.
2) I tried nonum and it works - except I would like, as a default, that when the new variable is a function of an existing one - as in nonum - then the default is after the columns used.  I guess that is another issue to raise.
3) I checked with Prepare > Column: Calculate > Enter and the Position isn't there.  I think it is, in the Master.  I'll check later.
4) I checked the Climatic > Prepare > Transform which isn't there yet.  I guess that is to rais in a different issue?
So, where it had a chance, it still seems to work.

2021-03-29 14:21 UTC, maxwellfundi commented
@dannyparsons  @rdstern  thank you for your reviews. I am merging this now.

2021-03-29 14:21 UTC, merged