Implemented dialog for Polar plot from Openair package
africanmathsinitiative/R-Instat pull request #6290
Opened 2021-03-17 12:32 UTC by HawardKetoyoMsatsi

5 different polar plots from the openair package are implemented here.
This PR replaces PRs. #6059 #6053 #6050 #6023 #6022

2021-03-25 16:18 UTC, HawardKetoyoMsatsi commented
@shadrackkibet @maxwellfundi @rdstern @lloyddewit Kindly review the current state of the dialog. I have removed the Facet options after a discussion with @shadrackkibet I am going to open an issue over the same.

2021-03-26 06:20 UTC, rdstern requested changes
@HawardKetoyoMsatsi and @shadrackkibet I very much like the structure that you have now. I am afraid it is still a long way from being finished, simply because there are so many refinements that are possible with these plots. 
The examples I tried did work.  Two suggestions, then I hope we could merge and sort out the rest in a further issue.  The big plus point, from the usage point of view is that we can try adding features with the script window first.
a) Please look at the other circular dialogues.  I have a feeling they have wind speed before wind direction?  I quite like wind direction first.  But let's be consistent.  This might mean another issue to change the other circular dialogues.
b) The facets are absent.  I think Haward has greatly complicated his life by starting with the nice features in openair, and then trying to add the way we work in R-Instat.  For simplicity, let's add the facets the R-Instat way and then consider whether we can take advantage of the extra facilities in openair.  So add 2 single receivers, called Facet (Optional) and Facet2 (Optional) which call openair's Type argument, and assume the facets are from variables in the data frame - not from his special method from the date variable.  
Then let's merge and proceed.

We can't use the lattice package and not have lattices (facets!)

2021-03-30 11:21 UTC, HawardKetoyoMsatsi commented
@rdstern Kindly take a look, I have implemented the faceting options and placed with speed before wind direction for consistency with other dialogs. This however brought Plot against: label before wind direction (Kindly comment on whether we can leave it there or look for a space for it).

2021-03-30 12:49 UTC, rdstern commented
I comment as I go through these in turn.  It would be really good to get this merged in this version:
a) In the third option, i,.e. Polar Plot change Plot against to Windspeed  - as in most of the others.  It says that's the default, so let's say that too! 
b) Same for 5th option Polar cluster
c) In Polar cluster move the Cluster label to the left, so it is not under the next control.
d) Is there anything different in your code for the polar cluster plot, compared to the others?  The others all transfer to the R viewer.  This one doesn't. 

Overall, great - and clearly a lot of work.  The dialogues look neat.  Well done.


**_Polar Frequency_**

Seems ok to me:

![image](https://user-images.githubusercontent.com/11226469/112987832-0c56d200-915b-11eb-854a-600e87b7a671.png)

Giving:
![image](https://user-images.githubusercontent.com/11226469/112987888-1d074800-915b-11eb-9beb-ca0374a45fca.png)

(I don't know what the Transform checkbox is doing, and later we should add a tooltip to explain.

**_Percentile Rose_**

![image](https://user-images.githubusercontent.com/11226469/112988211-7ec7b200-915b-11eb-8c2a-dd2d5ec387df.png)


Giving:

![image](https://user-images.githubusercontent.com/11226469/112988433-bdf60300-915b-11eb-94dd-5d49be4e3b36.png)


**_Polar Plot_**
![image](https://user-images.githubusercontent.com/11226469/112989229-981d2e00-915c-11eb-8ede-337f5fd02434.png)


Giving:
![image](https://user-images.githubusercontent.com/11226469/112989116-79b73280-915c-11eb-8b0b-95b6d99b7bef.png)



**_Polar Annulus_**

This gave an error of not enough data in certain circumstances.  For example it needed to Date-Time Variable, and I couldn't facet by time of day.  I could by another pollutant:

So this needs investigation, but I suggest we can merge first and then discover more.
But this works:
![image](https://user-images.githubusercontent.com/11226469/112989918-5c369880-915d-11eb-90ed-1bf85182f39f.png)


Giving:

![image](https://user-images.githubusercontent.com/11226469/112989821-3dd09d00-915d-11eb-9a6b-0ad2549a16c4.png)

**_Polar cluster_**

![image](https://user-images.githubusercontent.com/11226469/112990384-e979ed00-915d-11eb-9421-7f21b4b98001.png)

Giving:

![image](https://user-images.githubusercontent.com/11226469/112990717-44abdf80-915e-11eb-8d34-98673f9eafc7.png)

2021-03-30 15:03 UTC, HawardKetoyoMsatsi commented
@rdstern I have made the required changes kindly take a look. I am not able to tell what is happening with the polar cluster, they all use the same function.

2021-03-30 20:11 UTC, rdstern submitted a review, later dismissed
Great @HawardKetoyoMsatsi quite a tour de force!

2021-03-31 08:00 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  type = "default"
```suggestion
  type <- "default"
```

2021-03-31 08:08 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  }
```suggestion
  if (!missing(type1_col_name) && !missing(type2_col_name)) {
    type <- c(type1_col_name, type2_col_name)
  }
  if (missing(type1_col_name) && !missing(type2_col_name)) {
    type <- type2_col_name
  }
  if (!missing(type1_col_name) && missing(type2_col_name)) {
    type <- type1_col_name
  }
```

2021-03-31 08:50 UTC, HawardKetoyoMsatsi commented on instat/static/InstatObject/R/stand_alone_functions.R
> +other_rose_plots <- function(data, type1_col_name, type2_col_name, date_col_name, wd_col_name, ws_col_name, main_method, single_pollutant, multiple_pollutant, ...) {
Two controls are passing the same parameter name that's why I chose to have different names for each control

2021-03-31 08:51 UTC, HawardKetoyoMsatsi commented on instat/dlgOtherRosePlots.vb
> +                Else
Done

2021-03-31 10:14 UTC, shadrackkibet submitted a review, later dismissed

2021-03-31 11:21 UTC, lloyddewit commented on instat/dlgOtherRosePlots.vb
> +        ElseIf rdoPolarCluster.Checked OrElse rdoPercentileRose.Checked Then
I would expect this sub to either add or remove the `statistic` parameter but in its current implementation it may do neither.
Should this `If` statement have an `Else` at the end that removes the parameter?

2021-03-31 11:40 UTC, rdstern requested changes
@HawardKetoyoMsatsi a very small point.  I put wind speed into the first dialogue.  That is cleared in the 3rd and 5th, where you used to have other variable.  It is remembered by the other cases.
I could accept that if you don't have time

2021-03-31 14:44 UTC, HawardKetoyoMsatsi commented on instat/dlgOtherRosePlots.vb
> +        ElseIf rdoPolarCluster.Checked OrElse rdoPercentileRose.Checked Then
Yea for the last ElseIf an Else would have been better

2021-03-31 18:08 UTC, shadrackkibet approved these changes

2021-03-31 18:10 UTC, merged

2021-04-01 06:11 UTC, HawardKetoyoMsatsi commented
@rdstern I think it will be okay to accept if the two plots with cleared inputs as they are then we can discuss on how to either restrict it to wind Speed. Some plots take wind speed as a parameter name "`wd`" while the two take wind speed as parameter name "`x`"