Fixing bug when clicking reset in the Duplicates dialog
africanmathsinitiative/R-Instat pull request #6303
Opened 2021-03-20 11:27 UTC by lilyclements

@africanmathsinitiative/developers this is ready for review

Fixes a bug highlighted by @shadrackkibet in #6287

Now when "reset" is clicked, there is not an error message from the `data_name` parameter not being added in.

To check:
* Load the data
* Click reset
* Then click Ok

2021-03-21 09:05 UTC, lloyddewit commented
@Ivanluv Please could you peer review? thanks

2021-03-21 09:08 UTC, lloyddewit approved these changes

2021-03-21 09:09 UTC, lloyddewit commented
@rdstern please could you test? thanks

2021-03-24 09:43 UTC, rdstern approved these changes

2021-03-24 11:56 UTC, dannyparsons requested changes

2021-03-24 11:56 UTC, dannyparsons commented on instat/dlgDuplicates.vb
> +        clsGetColumnsFunction.AddParameter(strParameterName:="data_name", strParameterValue:=Chr(34) & ucrSelectorDuplicateswithVariables.ucrAvailableDataFrames.cboAvailableDataFrames.SelectedItem &
There shouldn't be a need to add this in `SetDefaults()`. The data frame is variable, so it isn't a default. Instead, your code under event `ucrSelectorDuplicateswithVariables.ControlValueChanged` could be extracted to a `Sub` and then called there and also called at the end of `SetRCodeForControls()` so that when resetting it's added in.

2021-03-24 14:16 UTC, maxwellfundi commented
@lilyclements  is this ready for re-review?

2021-03-24 14:34 UTC, dannyparsons approved these changes
Looks great.

2021-03-24 14:35 UTC, merged