New data frame example
africanmathsinitiative/R-Instat pull request #6335
Opened 2021-03-24 15:46 UTC by Patowhiz

Fixes this [comment](https://github.com/africanmathsinitiative/R-Instat/issues/6250#issuecomment-805924953) in issue #6250.

@africanmathsinitiative/developers this is ready for review.

2021-03-24 16:43 UTC, dannyparsons commented on instat/dlgNewDataFrame.vb
> +            lstView.Items.Add(New ListViewItem({"data.frame(date = seq(as.Date(""2019-1-1""), as.Date(""2020-12-31""), ""month""), rain = as.numeric(NA), tmin = as.numeric(NA), tmax = as.numeric(NA))
Slightly simplified the element columns. It achieves the same result.
```suggestion
            lstView.Items.Add(New ListViewItem({"data.frame(date = seq(as.Date(""2019-1-1""), as.Date(""2020-12-31""), ""month""), rain = NA_real_, tmin = NA_real_, tmax = NA_real_)"}))

```

2021-03-25 12:14 UTC, rdstern requested changes
Both of the new bits work.
a) Include Danny's change to the code for the second example.  It changes from the as.numeric that I suggested.  Keep the as.numeric in the first example - it is quite nice to have the two alternative ways in the 2 examples.
b) Add tooltip:  Two variables with daily dates and rainfall, ready for climatic data entry.  
c) Second tooltip Four variables including monthly dates.  Or use Prepare > Column: Date > Generate Dates to include a date variable.

2021-03-25 19:09 UTC, Patowhiz commented
@rdstern @dannyparsons I have made the suggested changes. This is now ready for your review.

2021-03-25 19:21 UTC, rdstern approved these changes
Good

2021-03-26 11:23 UTC, lloyddewit approved these changes

2021-03-26 11:25 UTC, merged