Graphs no longer saved in data_book by default to reduce file size when saving/auto-saving
africanmathsinitiative/R-Instat pull request #6344
Opened 2021-03-25 15:12 UTC by dannyparsons

fixes #6158

Implements the workaround outlined here: https://github.com/africanmathsinitiative/R-Instat/issues/6158#issuecomment-806906835

2021-03-25 15:43 UTC, rdstern requested changes
@dannyparsons releif that that problem is solved.
But I don't have a graph saved at all. 
I did a Taylor plot, and then gave the graph a name.  Then a correlation with a graph.  So one ggplot2 and one lattice graph.
When I look at the objects I have last_model, but not last_graph, nor the graph I saved.  I thought I would have access to them for the session?

2021-03-25 17:56 UTC, dannyparsons commented
Thanks. They were there but weren't being displayed. Should be fixed now.

I tested saving a file. Closing R-Instat and opening. When reopening, graphs are gone but models stayed.

2021-03-25 18:04 UTC, dannyparsons commented
In case you're looking again already, there was a small bug, I've just fixed with latest commit.

2021-03-25 18:58 UTC, rdstern submitted a review, later dismissed
@dannyparsons this is great, and I hope it can be merged.
It has uncovered some (minor) problems in the Prepare > R Object dialogues.  There are 4 dialogues and graphs are not recognised as Objects in View object or Reorder Objects.  In rename objects and Delete objects it is different, because of Shadrack's work on the filters.  That has Objects and one category is Model.  A model appears twice.  Graphs appear there, but not under the general Object category.  I wonder if we need that, and perhaps should just have the categories.

Then Describe > View graph now includes the lattice graphs, even though it says it is just ggplot only.  Of course it can't display in the interactive viewer!
These are nothing to do with this issue, that I hope can be merged quickly.

2021-03-26 10:41 UTC, dannyparsons commented
@lloyddewit This may conflict with others PRs on the same R files. Since this is a small change I don't mind waiting for those to be merged first and then resolving any conflicts.

2021-03-26 10:45 UTC, lloyddewit approved these changes
I reviewed the R code as best I could.
I just have one small comment (feel free to ignore this comment)

2021-03-26 10:45 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
>          if(!(object_name %in% names(curr_objects))) stop(object_name, "not found.")
```suggestion
        if(!(object_name %in% names(curr_objects))) stop(object_name, " not found.")
```

2021-03-26 11:26 UTC, dannyparsons commented
Thanks, updated.

2021-03-26 11:29 UTC, lloyddewit approved these changes

2021-03-26 16:08 UTC, dannyparsons commented
@lloyddewit I'll wait till #6346 is merged before merging this in case of any conflicts.

2021-03-26 21:04 UTC, closed without merging