Bug fix: use of multiple factors on fill date gaps
africanmathsinitiative/R-Instat pull request #6381
Opened 2021-04-04 09:18 UTC by shadrackkibet

fixes #6380

@africanmathsinitiative/developers this is ready for review.

2021-04-06 04:12 UTC, rdstern reviewed
@shadrackkibet great.  It works.
However, it now works too well in fact.  
I tried also with a Month factor that I generated with the Use Date dialogue.  It still worked, but added many other rows than I wanted.  Can we restrict it to only work for additional station-type variables.  I assume as a factor they need to have the same number of levels and really be in 1-to 1 correspondence?

I have now checked on one possibility.  I took the 2 factors, each with 4 levels and used interaction as follows,i.e. with drop unused levels = TRUE:

`Interact <- interaction(x=data_book$get_columns_from_data(data_name="Append", col_names=c("station","station_id"), use_current_filter=FALSE), drop=TRUE)
`
The resulting interaction only had 4 levels, i.e. the same number as the first station variable.  Unless that is the case, we don't allow additional variables?

2021-04-06 07:27 UTC, shadrackkibet commented
@rdstern I added a check for the factor levels please test again.

2021-04-06 12:49 UTC, rdstern requested changes
@shadrackkibet I think the check could be a bit cleverer than just the number of levels of each factor.  That's why I suggested we use the combine idea and get rid of unused levels.  Then the combined number of levels will be the same as the station factor.

2021-06-11 09:02 UTC, lloyddewit commented
@shadrackkibet Please could you clarify the status of this PR? thanks

2021-06-11 10:37 UTC, shadrackkibet commented
No advances on this yet. I am not sure how to do this kind of check.

2021-06-11 11:04 UTC, shadrackkibet commented
I also think the current design of the dialog is a limitation in doing this check. @rdstern if you agree we have the station factor separately then I think it is possible to implement your idea i.e add a station receiver.

2021-06-11 19:28 UTC, rdstern commented
I think it is easy to do a check with the current structure.  I use the example of the Kenya data from the library, for all elements where there are 6 stations.  There are 2 variables for the station as shown here:

![image](https://user-images.githubusercontent.com/11226469/121738365-0afa3c00-caf2-11eb-99cb-1ef09048f94a.png)

Now these two variables need to be essentially the same.  I got an interaction variable for the 2 variables.  Here is the r-code from the interaction dialogue:

```
# Code generated by the dialog, Combine Factors
Interact <- interaction(x=data_book$get_columns_from_data(data_name="w_kenya_allelements", col_names=c("station","stationID"), use_current_filter=FALSE), drop=TRUE, sep="Période."):

```

This produces an interaction variable.  (If there are 3 variables, then all 3 could be included.  Then we simply check if the number of levels of this interaction is the same as the number of levels of the first variable in the control.  If ok we proceed.  If not we stop and say something like:  **_The multiple Station Variables are not in synch_** 

It would be clearer if we changed the label from `By Factors` to` Station Variable(s):`

2021-06-12 17:38 UTC, shadrackkibet commented
- I don't like the fact that we have to depend on the first variable in the multiple selector. What if the order of items in the receiver changes? 
-  This dialog is available under **Prepare>Column Dates**. Therefore it can be used generally although its main use is on climatic data. Changing **By Factors:** to **Station Variable(s):** will look like it is just climatic?

2021-06-12 20:14 UTC, rdstern commented
On your first comment, it only works if all variables are essentially identical - so any variable will do.
I take your second point.  I hadn't thought of that.  perhaps leave the label as it is.

2021-06-16 09:31 UTC, shadrackkibet commented
@rdstern I implemented the desired check. Please check.

2021-06-16 09:34 UTC, rdstern commented
@shadrackkibet many thanks - will do

2021-06-17 07:28 UTC, rdstern submitted a review, later dismissed
@shadrackkibet this seems to work well, so I am approving.  @lloyddewit to do the second check now?
@shadrackkibet when there is an error it is raised in the same way as errors in our code - that we haven't planned for.  This is a general point.  When we have something like this, I have no problem reporting it, in this way.  But I wonder if we could also give a neater version of the message in the output window?  We don't need to repeat the command there, because that's (usually) already displayed?

2021-06-17 07:38 UTC, lloyddewit commented
@N-thony Please could you review? thanks

2021-06-19 06:11 UTC, N-thony reviewed
@lloyddewit all is good from my end. Thanks

2021-06-22 13:30 UTC, lloyddewit commented on instat/dlgInfill.vb
> +        End If
Can we simplify this sub?
```suggestion
        clsDefaultFunction.RemoveParameterByName("start_date")
        clsDefaultFunction.RemoveParameterByName("end_date")
        Select Case ucrInputLimitOptions.GetText
            Case "Fixed Limits", "Fixed Start Limit"
                clsDefaultFunction.AddParameter("start_date", clsRFunctionParameter:=ucrDtpStartDate.ValueAsRDate, iPosition:=3)
            Case "Fixed Limits", "Fixed End Limit"
                clsDefaultFunction.AddParameter("end_date", clsRFunctionParameter:=ucrDtpEndDate.ValueAsRDate, iPosition:=4)
        End Select
```

2021-06-22 13:40 UTC, shadrackkibet commented on instat/dlgInfill.vb
> +        End If
Committed the suggestion. Thanks for the simplification @lloyddewit

2021-06-22 15:10 UTC, lloyddewit approved these changes

2021-06-22 15:11 UTC, lloyddewit commented
@rdstern One small change since your last approval (functionality should not be affected), please could you approve again? thanks

2021-06-23 07:51 UTC, rdstern approved these changes

2021-06-23 07:52 UTC, merged