Created JSON file containing English text from all dialogs
africanmathsinitiative/R-Instat pull request #6382
Opened 2021-04-04 18:27 UTC by lloyddewit

Related to (but does not fix) issue #3721 . 

@africanmathsinitiative/developers There is nothing you can review or test in this PR. This PR is just a new English source file for the CrowdIn translations.

@dannyparsons This new English JSON file should include the text from `frmMain` and all the dialogs. This is the vast majority of the English text in R-Instat. However it is still missing some non-standard elements:

- the `frmMain` menus (this text is in `r_instat_menus.json`)
- right mouse button menus in the `frmMain` windows (e.g. script window)
- tool bar pull down menus
- `ucrCheck` and `ucrInput` controls (these controls use dynamic text, for later implementation)
- text in message boxes
- any other dynamic text

I will probably find more exceptions as I test. 
The code I used to generate the file will be included in a future PR.

Please could the CrowdIn translations of this JSON file into French be done in parallel to my work on the translation mechanism?
Please may I add extra English text to this file in a future PR (for the missing cases above)?
Thanks if this is possible.

2021-04-20 19:48 UTC, lloyddewit commented
@dannyparsons I added new English JSON files. As discussed, `r_instat_menus.json` contains all the text associated with `frmMain`, and `r_instat_not_menus.json` contains all the other text.

I tried to include all the static and dynamic text in the controls. Some text is not included:

- text in message boxes
- text containing carriage returns or line feeds (causes problems for the csv files that I use to populate the database)
- composite text (e.g. built up of different elements such as text including path names, row numbers, counts etc.)

2021-05-02 13:53 UTC, shadrackkibet requested changes
@lloyddewit since there is nothing to test, I only checked the spelling mistakes in the file.

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Dispaly Daily Options": "Dispaly Daily Options",
I can see some typo here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Fliter Preview:": "Fliter Preview:",
Also here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Latitute:": "Latitute:",
also here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Maximum Logitude": "Maximum Logitude",
also here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Packages Documenation": "Packages Documenation",
also here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Polar Cordinates": "Polar Cordinates",
also here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Postion:": "Postion:",
also here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Satelite Element:": "Satelite Element:",
Should all these be `satellite`?

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_not_menus.json
> +"Specifiy": "Specifiy",
also here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_menus.json
> +"Acknowledgements": "Acknowledgements",
also here? I remember you changed this in the menu recently

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_menus.json
> +"Cummulative Exceedance...": "Cummulative Exceedance...",
`cumulative`?

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_menus.json
> +"Multple Lines...": "Multple Lines...",
also here

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_menus.json
> +"Non Parameteric One Way ANOVA...": "Non Parameteric One Way ANOVA...",
`Parametric` ?

2021-05-02 13:53 UTC, shadrackkibet commented on instat/translations/en/r_instat_menus.json
> +"Timeseries...": "Timeseries...",
Should this be two words?

2021-05-02 18:00 UTC, lloyddewit commented
@shadrackkibet Thank you for spotting the typos.
The JSON file in this PR reflects the text in the `.vb` and `.resx` files. Therefore we need to fix the typos in these `.vb` and `.resx` files, and then generate a new translations database and translation JSON files.
I think we can best do this after version 0.7.1 is released.
I'd prefer to do this in a separate PR. I made issue PR #6438 for this.

2021-05-02 18:49 UTC, dannyparsons commented
Thanks Stephen, I will merge this and start getting the translations done in CrowdIn.

@shadrackkibet thanks for spotting the typos. Can we try to find where these are in forms/dialogs and correct them there? This will then be reflected in the json files as Stephen mentioned.

2021-05-02 18:49 UTC, dannyparsons approved these changes

2021-05-02 18:49 UTC, merged