Enhancement of convert to numeric on right click
africanmathsinitiative/R-Instat pull request #6385
Opened 2021-04-06 14:03 UTC by shadrackkibet

Partially implements #5465.

@africanmathsinitiative/developers this is ready for review.

2021-04-06 16:54 UTC, rdstern requested changes
@shadrackkibet great it works already.  Two small suggestions:
a) Could your non-numeric option be the default.  Currently it is now the second option.
b) Once in the non-numeric dialogue could the variable be selected automatically?
Then it's already ready!

2021-04-06 19:12 UTC, shadrackkibet commented
@rdstern the above changes have been done!

2021-04-07 05:19 UTC, rdstern approved these changes
@shadrackkibet great - approving.  I suggest @dannyparsons could do the second review as this was his work originally

2021-04-07 08:08 UTC, dannyparsons reviewed
Just a couple of suggestions on the text

2021-04-07 08:08 UTC, dannyparsons commented on instat/frmConvertToNumeric.resx
> +    <value>Some Values are non-numeric:
```suggestion
    <value>Some values are non-numeric:
```

2021-04-07 08:08 UTC, dannyparsons commented on instat/frmConvertToNumeric.resx
> +- Choose "Non-numeric" to investigate these values.
Can this button be `Inspect Values`? In general we should use verbs for actions.

2021-04-07 08:21 UTC, lloyddewit submitted a review, later dismissed

2021-04-07 08:21 UTC, lloyddewit commented on instat/frmConvertToNumeric.vb
> +    Public Sub SetDataFrameName(strDataFrame As String)
@shadrackkibet I initially thought that `strDataFrameName` should be a public property but then I realized that you'd have to write a `Get` or make the property `WriteOnly`. So on balance, I think what you've done here is a good solution.

2021-04-07 08:47 UTC, lloyddewit approved these changes

2021-04-07 16:55 UTC, rdstern approved these changes
@shadrack great!

2021-04-07 16:58 UTC, merged