Enhancement of cell right click
africanmathsinitiative/R-Instat pull request #6387
Opened 2021-04-06 15:55 UTC by shadrackkibet

This PR fixes "marked" points in issue #6384

@africanmathsinitiative/developers this is ready for review.

- Moved add comment into the main right-click 
- Enable levels/labels only on the factor column

2021-04-06 17:17 UTC, rdstern approved these changes
@shadrackkibet great.  Changes the position of the Add Comment option and also sorts out a problem on the Levels/Labels
Over to @lloyddewit

2021-04-07 07:47 UTC, lloyddewit requested changes

2021-04-07 07:47 UTC, lloyddewit commented on instat/ucrDataView.vb
> +        Dim strType As String = frmMain.clsRLink.GetColumnType(grdCurrSheet.Name, strColumns(0))
`SelectedColumnsAsArray()` may potentially return an empty array, this will trigger an exception on this line.
Check for empty array?

2021-04-07 08:27 UTC, shadrackkibet commented on instat/ucrDataView.vb
> +        Dim strType As String = frmMain.clsRLink.GetColumnType(grdCurrSheet.Name, strColumns(0))
Thanks, that is right. I have now added a check.

2021-04-07 08:46 UTC, lloyddewit requested changes

2021-04-07 08:46 UTC, lloyddewit commented on instat/ucrDataView.vb
> +        End If
Do we need an `Else` statement?
Also, we should normally declare variables in the scope where they are needed
```
        Dim strColumns() As String = SelectedColumnsAsArray()
        If strColumns IsNot Nothing AndAlso strColumns.Count > 0 Then
            Dim iSelectedCols As Integer = grdData.CurrentWorksheet.SelectionRange.Cols
            Dim strType As String = frmMain.clsRLink.GetColumnType(grdCurrSheet.Name, strColumns(0))
            mnuLebelsLevel.Enabled = (iSelectedCols = 1 AndAlso strType.Contains("factor"))
        Else
            mnuLebelsLevel.Enabled = False
        End If
```

2021-04-07 09:20 UTC, shadrackkibet commented on instat/ucrDataView.vb
> +        End If
I don't think an else will be `mnuLebelsLevel.Enabled = False`. Perhaps a developer error will be more appropriate? 

Another point is that  `mnuLebelsLevel.Enabled = (iSelectedCols = 1 AndAlso strType.Contains("factor"))` is a short-hand which can be `false` so we already have an else in that case.

For the scope, I would define scope differently. I would consider the subroutine as the scope where I declare the variables and make assignments between checks. Therefore I would have the following in the subroutine.

```
        Dim iSelectedCols As Integer
        Dim strColumns() As String
        Dim strType As String

        strColumns = SelectedColumnsAsArray()
        If strColumns IsNot Nothing AndAlso strColumns.Count > 0 Then
            iSelectedCols = grdData.CurrentWorksheet.SelectionRange.Cols
            strType = frmMain.clsRLink.GetColumnType(grdCurrSheet.Name, strColumns(0))
            mnuLebelsLevel.Enabled = (iSelectedCols = 1 AndAlso strType.Contains("factor"))
        Else
            "developer error"
        End If
        mnuRemoveCurrentFilters.Enabled = Not String.Equals(strFilterName, strNoFilter)
``` 

What do you think?

2021-04-07 10:32 UTC, rdstern submitted a review, later dismissed
Still happy with this from my side

2021-04-07 10:51 UTC, lloyddewit commented on instat/ucrDataView.vb
> +        End If
> I don't think an else will be `mnuLebelsLevel.Enabled = False`. Perhaps a developer error will be more appropriate?
> 
For me, a developer error is only when we have a situation that should never occur and indicates a coding error. If you think that an empty `strColumns` array meets this criteria then I agree that a developer error is the best solution.

> For the scope, I would define scope differently. I would consider the subroutine as the scope where I declare the variables and make assignments between checks. Therefore I would have the following in the subroutine.
> 
> ```
>         Dim iSelectedCols As Integer
>         Dim strColumns() As String
>         Dim strType As String
> 
>         strColumns = SelectedColumnsAsArray()
>         If strColumns IsNot Nothing AndAlso strColumns.Count > 0 Then
>             iSelectedCols = grdData.CurrentWorksheet.SelectionRange.Cols
>             strType = frmMain.clsRLink.GetColumnType(grdCurrSheet.Name, strColumns(0))
>             mnuLebelsLevel.Enabled = (iSelectedCols = 1 AndAlso strType.Contains("factor"))
>         Else
>             "developer error"
>         End If
>         mnuRemoveCurrentFilters.Enabled = Not String.Equals(strFilterName, strNoFilter)
> ```
> 
> What do you think?

This is 3 lines longer than my proposal but we have no formal coding standards so I think it comes down to personal taste.
Therefore, I've no problem if you prefer to implement like this, it looks good :)

2021-04-08 12:10 UTC, rdstern submitted a review, later dismissed

2021-04-09 07:38 UTC, lloyddewit requested changes

2021-04-09 07:38 UTC, lloyddewit commented on instat/ucrDataView.vb
> +            'TODO: Add developer error?
Please could you add a developer error here?
Would it also be sensible to set `mnuLebelsLevel.Enabled` to `False` (otherwise it could potentially remain `True` even when the required conditions are not met)?
```suggestion
            MsgBox("Developer error: SelectedColumnsAsArray() expected to return an array with at least one element.")
            mnuLebelsLevel.Enabled =  False
```

2021-04-09 08:01 UTC, lloyddewit commented
@rdstern Please could you approve again? thanks

2021-04-09 09:58 UTC, merged