Enhancement of the Climatic Data Entry Dailog
africanmathsinitiative/R-Instat pull request #6399
Opened 2021-04-08 10:55 UTC by N-thony

@rdstern this solves the following items in issue #6352 and ready for your test:

1. Added the Options sub-dialogue.
2. Remain in the offending cell when an item is flagged and not possible, e.g. a decimal or typing text
3. Added Extra Rows checkbox
4. Summary of the number of observations shown in the main dialog
5. Added a button Comment
6. Added flag field data checkbox
Other items are still under implementation.

2021-04-09 03:34 UTC, Patowhiz commented
Also added item (2) (Patrick).

> The last value does not always seem to register. So if I enter 555 into a field and then hit Return I don't think the 555 is used.

2021-04-16 17:57 UTC, N-thony commented
@shadrackkibet I made the initial steps for the comments to the data entry system described in #6405. This is ready. Could you proceed with the next steps? Thanks.

2021-04-19 07:43 UTC, lloyddewit commented
@shadrackkibet The comment above assumes that you'll peer review this PR. Are you happy to do this or should we ask someone else?

2021-04-19 08:08 UTC, shadrackkibet commented
@lloyddewit my understanding is that the work here is incomplete. I am therefore taking over to complete work on comments. @N-thony please correct me if I misunderstood.

2021-04-19 08:15 UTC, N-thony commented
> @lloyddewit my understanding is that the work here is incomplete. I am therefore taking over to complete work on comments. @N-thony please correct me if I misunderstood.

@shadrackkibet Yes, you are right.

2021-04-19 08:22 UTC, rdstern commented
@Patowhiz is also involved in this.  Perhaps check that his part is finished?

2021-04-19 09:48 UTC, lloyddewit commented
> 
> 
> > @lloyddewit my understanding is that the work here is incomplete. I am therefore taking over to complete work on comments. @N-thony please correct me if I misunderstood.
> 
> @shadrackkibet Yes, you are right.

Ok that's great, thanks for clarifying

2021-04-21 06:47 UTC, N-thony commented
@rdstern could you test? Thanks.

2021-04-21 08:36 UTC, rdstern commented
@N-thony this is looking good now.  
a) The addition of monthly sums by @Patowhiz seems to work fine.  I have queried some additions to that feature with him, and can report later.  But I would be happy to accept this as it is.
b) In the data entry you have "Add Flag Variables Data".  I thought that would go as another option with the default ticked.  It would check that the flag variables exist in the data frame. If not, the option is disabled and there is a tooltip that says "Use the Setup for Data Entry dialogue to define flag Variables."
c) If you define a default value, and then go into the data entry, these are the (new) values.  So they become changed values when you return to the main dialogue.  Currently they are ignored in the label in red.  I am not sure what happens with the writing back to the data frame. 
d) @shadrackkibet is better than me in making suggestions on the layout of the information in the main dialogue.  I would prefer the red information on the number of rows added to be lower in the dialogue?  Perhaps move the Enter Data and Check Date buttona up a bit and put it below the Enter data.  Also have less space above the Comment line.
e) @N-thony is going to implement the option to add extra rows.  (Nice for this release but not vital.)

2021-04-22 04:17 UTC, Patowhiz commented
> e) @N-thony is going to implement the option to add extra rows. (Nice for this release but not vital.)

Yes,and the etra rows options shouldn't apply for "Monthly" entry.  It aready add extra rows. Though if that was to be added, the code wil have to be edited to exclude those extra rows from the monthly totals.

2021-04-22 05:33 UTC, N-thony commented
> > e) @N-thony is going to implement the option to add extra rows. (Nice for this release but not vital.)
> 
> Yes,and the etra rows options shouldn't apply for "Monthly" entry. It aready add extra rows. Though if that was to be added, the code wil have to be edited to exclude those extra rows from the monthly totals.

There will be another check box according to @rdstern to add the extra summary rows for the month option.

2021-04-22 15:45 UTC, rdstern commented
@N-thony the default value needs to be done correctly.  It is usually for rainfall where you may want to have 0 every day of the month.  So the default means that all values have effectively been entered.  So this should be registered and possibly all should be coloured yellow.  Is there perhaps also a lighter yellow to distinguish this default?  Otherwise the full yellow.  And when you return then all should be changed and hence updated if ok is pressed.

2021-04-22 17:58 UTC, shadrackkibet commented
@N-thony looks like you are still working on this? Let me know when it's ready then I can complete work on comments.

2021-04-22 18:19 UTC, N-thony commented
@shadrackkibet over to you now.

2021-04-22 18:20 UTC, shadrackkibet commented
Great.

2021-04-23 21:36 UTC, N-thony commented
@rdstern could you re-test? Thanks

2021-04-23 23:07 UTC, rdstern requested changes
@N-thony and @shadrackkibet and @Patowhiz this is looking very good.
Just 2 points and 2 questions:
a) The rows and comments added should not be present when you return to the dialogue.  They are not there at the very start.  Once the data has been written to the data frame, they are reset to zero and not shown on the entry until you return again from the data entry.
b) The Missing label in the options should be Missing Shown as NA.
c) (Only if really easy!) I stupidly used a data frame without setting the key.  (But that is also the idea of testing!) It let me set up some comments and then gave me an error when I pressed Ok.  Could the lack of the key be checked within the comments sub-dialogue, so perhaps Add Comment is then disabled and a tooltip can explain why?
Now 2 questions, probably for the next versions.
a) Is it easy in the grid to have a sort of underline after the 10th and 20th of the month?
b) When entering by month you come back and then usually want the next month.  What's the simplest way to move on a month at a time?  Perhaps a small button with the label Next.  Only when the Month option is used?

2021-04-24 07:53 UTC, shadrackkibet commented
> a) The rows and comments added should not be present when you return to the dialogue. They are not there at the very start. Once the data has been written to the data frame, they are reset to zero and not shown on the entry until you return again from the data entry.

@rdstern this means that once you click add comments on the sub dialog then we clear controls?

2021-04-24 07:57 UTC, N-thony commented
> > a) The rows and comments added should not be present when you return to the dialogue. They are not there at the very start. Once the data has been written to the data frame, they are reset to zero and not shown on the entry until you return again from the data entry.
> 
> @rdstern this means that once you click add comments on the sub dialog then we clear controls?

@shadrackkibet are you working on ?

2021-04-24 08:00 UTC, N-thony commented
@shadrackkibet sorry.  I had a chat with @rdstern and I was making the change, are you also working on that?

2021-04-24 08:02 UTC, shadrackkibet commented
Please go ahead and make those changes.

2021-04-24 08:10 UTC, rdstern commented
@shadrackkibet , it is once you click Ok on the main dialogue, when it writes the data and comments back to the respective data frames.  Then you return to the dialogue - perhaps to enter the next month.  Currently it still shows the ros and commants from before.  The red lines should be cleared once they are added.

2021-04-24 08:23 UTC, shadrackkibet commented
@rdstern I now understand. This is caused by a change made by @N-thony recently. I will comment on the code on how to fix it.

2021-04-24 08:27 UTC, shadrackkibet requested changes

2021-04-24 08:27 UTC, shadrackkibet commented on instat/sdgCommentForDataEntry.vb
> +    Private iComment As Integer = 0
No need to add another variable you could just use the `i` above.

2021-04-24 08:27 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
> +        'sdgCommentForDataEntry.ClearComments()
It is important to clear comments once added to the data frame here. This is the cause of the bug (a) reported by @rdstern

2021-04-24 08:29 UTC, shadrackkibet commented on instat/sdgCommentForDataEntry.vb
> +    Private iComment As Integer = 0
Give `i` a sensible name as well maybe `iNumComments`?

2021-04-24 08:44 UTC, N-thony commented on instat/dlgClimaticDataEntry.vb
> +        'sdgCommentForDataEntry.ClearComments()
This is giving a bug when the comment is not added. Perhaps it is not a good place to put it. I don't know if I'm wrong

2021-04-24 08:54 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
> +        'sdgCommentForDataEntry.ClearComments()
Which bug?

2021-04-24 09:17 UTC, N-thony commented on instat/dlgClimaticDataEntry.vb
> +        'sdgCommentForDataEntry.ClearComments()
![image](https://user-images.githubusercontent.com/68591383/115953954-9c83ff00-a4ee-11eb-93e3-098fbdc74215.png)

2021-04-24 12:29 UTC, N-thony commented
@rdstern this is ready for you to re-test. Thanks.

2021-04-24 13:34 UTC, N-thony commented
@rdstern this is ready for you to re-test. Thanks.

2021-04-24 13:34 UTC, rdstern commented
1There is still the issue to fix of the number of rows changed being shown after they were written back to the data frame.  See here:

![image](https://user-images.githubusercontent.com/11226469/115960122-71f27000-a507-11eb-92b5-4d450181b6f2.png)

2. When I start the dialogue the focus is on the receiver for the data entry.  If the data file has been defined as climatic, then the station and date fields should fill automatically.  Otherwise the focus should be on the first field - namely the station.

3.  The label still has to be done here.
4. 
![image](https://user-images.githubusercontent.com/11226469/115960266-5340a900-a508-11eb-905f-c8bd07bc45d6.png)

Change `Missing` to `Missing values shown as NA`

2021-04-24 13:50 UTC, N-thony commented
@rdstern could you test again? Thanks.

2021-04-24 14:10 UTC, rdstern approved these changes
@N-thony I am approving.  There is the one small "feature" that the NA as missing isn't activated until you go into thde Options.  But that is so minor I don't want to delay the merging.
I suggest - exceptionally - that @shadrackkibet do the second check so it can be merged as soon as possible.  This isn't risky as there will immediately be another pull request.  Then I'll ask @dannyparsons to merge

2021-04-24 14:41 UTC, N-thony commented
@rdstern I made a small code change for the NA feature.

2021-04-24 16:23 UTC, shadrackkibet requested changes
Just some minor code reviews.

2021-04-24 16:23 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
> +        sdgCommentForDataEntry.Reset()
This is not consistent with how we reset the sub dialogs. You should have a boolean in the main dialog that is passed into the subdialog. Set the boolean by default and immediately you return to the main dialog. Then controls will then be reset through setRcode. Check other dialogs to see how that is done.

2021-04-24 16:23 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
> +        clsGetDataEntry.AddParameter("station_name", Chr(34) & ucrInputSelectStation.GetValue() & Chr(34), iPosition:=6)
Why is this done manually? I would like to understand why this is not done through "seRcode". If not possible then should we remove this somewhere?

2021-04-24 16:23 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
> +    'End Sub
Remove?

2021-04-24 16:23 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +Imports instat
Not needed

2021-04-24 16:23 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +    End Sub
Always have  a space at the end of each sub

2021-04-24 16:23 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +        ucrInputTransform.SetValidationTypeAsNumeric(dcmMin:=0.1) 'temporary`
Why are these temporary? Always try to have clear comments. It will save lots of time for the next maintainer.

2021-04-24 16:23 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +        lblAfter.Visible = False
Always use the linking system to set visibility and state of controls whenever possible.

2021-04-24 16:23 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +
Only a single space

2021-04-24 16:23 UTC, shadrackkibet commented on instat/sdgCommentForDataEntry.vb
> +    End Sub
Always have space between subs

2021-04-24 16:23 UTC, shadrackkibet commented on instat/sdgCommentForDataEntry.vb
> +    End Sub
Why is this done manually? use setRcode?

2021-04-24 16:29 UTC, shadrackkibet requested changes

2021-04-24 16:29 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
>              If bSetup Then
`AndAlso`?

2021-04-24 17:43 UTC, N-thony commented on instat/dlgClimaticDataEntry.vb
>              If bSetup Then
It will not work properly with AndAlso

2021-04-24 17:43 UTC, rdstern approved these changes
@N-thony great.  @shadrackkibet I am approving again

2021-04-24 18:03 UTC, N-thony commented on instat/dlgClimaticDataEntry.vb
> +        clsGetDataEntry.AddParameter("station_name", Chr(34) & ucrInputSelectStation.GetValue() & Chr(34), iPosition:=6)
There is a quotation problem, so I made it like to solve this problem. Do you have any code suggestion?

2021-04-24 18:44 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
>              If bSetup Then
Why?

2021-04-24 18:55 UTC, N-thony commented on instat/dlgClimaticDataEntry.vb
>              If bSetup Then
This statement allows keeping the state of the grid if already filled. If you look all the code, when you try to combien the bShow and bSetup you will go long with th code.

2021-04-24 19:09 UTC, N-thony commented
@shadrackkibet I resolved some of your comments, and I think others require discussion. Since this is still under building I may resolve them in a new PR.
@rdstern sorry, I think you can re-approve if @shadrackkibet is happy with my suggestion.

2021-04-24 19:19 UTC, rdstern approved these changes

2021-04-25 06:14 UTC, shadrackkibet commented
@N-thony could you comment and "resolve conversation" for those points you have resolved? If something isn't clear, please let me know.

2021-04-25 10:42 UTC, N-thony commented
> @N-thony could you comment and "resolve conversation" for those points you have resolved? If something isn't clear, please let me know.

I left comments in the remaining that I'm waiting for your suggestions

2021-04-26 07:47 UTC, N-thony commented
@shadrackkibet I resolved some comments, and I'm still waiting to hear from you for those above not yet marked resolved.

2021-04-26 12:05 UTC, shadrackkibet commented
@rdstern could you test and re-approve? then we can merge then we can proceed with adding other features.

2021-04-26 12:40 UTC, rdstern approved these changes

2021-04-26 12:45 UTC, shadrackkibet approved these changes

2021-04-26 12:50 UTC, shadrackkibet commented
@lloyddewit I am merging this then I will open a new PR to work on adding flags. If you would like to review please go ahead here or wait when I open a new PR. Thanks

2021-04-26 12:50 UTC, merged

2021-04-27 07:28 UTC, lloyddewit commented
> 
> 
> @lloyddewit I am merging this then I will open a new PR soon to work on adding flags. If you would like to review please go ahead here or wait when I open a new PR. Thanks

@shadrackkibet Thank you for reviewing and merging. The majority of the commits were from @N-thony , @rdstern tested/approved and and you peer reviewed. So I think this PR has had adequate quality checks. 
Something we should monitor: If the peer reviewer has also made non-trivial commits to the PR then there should be a second or different peer reviewer. 
If you're involved in the new PR then I can do the final pre-merge peer review.