Implemented code for Wind/Pollution Rose dialogue
africanmathsinitiative/R-Instat pull request #6400
Opened 2021-04-08 11:33 UTC by HawardKetoyoMsatsi

Fixes #5965
@africanmathsinitiative/developers @rdstern this is ready for review.
this replaces PR #6126 which had build errors.

2021-04-08 12:49 UTC, rdstern commented
@haward This is looking very good.  I have suggestions for mainly just cosmetic changes:
a) Move Pollutant up (above the 2nd set of wd and ws.  And say Pollutant (Optional):
b) If just ws and wd are completed then enable Ok and run windrose rather than pollution rose.
c) Have a checkbox below the Pollutant saying "Compare two sets"  Default is unchecked and then the ws2 and wd2 are not visible.  If checked, then they are as you have it now.

2021-04-09 18:26 UTC, rdstern requested changes
@HawardKetoyoMsatsi this was probably still waiting for more changes from you, but I looked anyway.
a) Good change you made in the order of the controls and enabling it to function as an ordinary wind-rose plot.
b) Still good to add (Optional) after Pollutant.
c) Change the tab order, so it goes to pollutant after wind direction.  Then to the facets.
d) Consider a checkbox - as mentioned before for the 2nd ws/wd - unless that is too complicated

2021-04-10 06:43 UTC, HawardKetoyoMsatsi commented
@rdstern I was still working on it when you reviewed it but am now done, please take a look once more.

2021-04-10 07:05 UTC, rdstern approved these changes
@HawardKetoyoMsatsi great - looks good now.  @lloyddewit over to you!

2021-04-12 13:43 UTC, lloyddewit commented
@shadrackkibet please could you review? thanks

2021-04-12 18:22 UTC, shadrackkibet requested changes

2021-04-13 07:48 UTC, HawardKetoyoMsatsi commented
@shadrackkibet Please have a look at the corrections done.

2021-06-15 08:44 UTC, lloyddewit commented
@shadrackkibet Please could you check the changes from @HawardKetoyoMsatsi above, thanks

2021-06-15 09:15 UTC, shadrackkibet commented
Yes, I will, thanks for the reminder @lloyddewit. @HawardKetoyoMsatsi sorry for keeping you on this. I should have checked a long time ago!  Please send reminders when things stay for long.

2021-06-15 09:39 UTC, shadrackkibet requested changes
@HawardKetoyoMsatsi check some additional points here. If you could fix then I will approve. Thanks.

2021-06-15 09:39 UTC, shadrackkibet commented on instat/dlgWindPollutionRose.vb
> +    Private bRcodeSet As Boolean = False
Remove because it's not used anywhere?

2021-06-15 09:39 UTC, shadrackkibet commented on instat/dlgWindPollutionRose.vb
> +        dctStatistic.Add("abs.count", Chr(34) & "abs.count" & Chr(34))
Will it be better to use long names here? e.g Proportion count, Proportion mean, absolute mean?

2021-06-15 09:39 UTC, shadrackkibet commented on instat/dlgWindPollutionRose.vb
> +        ucrSaveGraph.SetPrefix("wind_pollution_rose")
It's dangerous to use the same prefix as the function name. The function will be overridden when you save the plot. I suspect the dialog will be unusable after that.

2021-06-23 07:44 UTC, shadrackkibet commented
@HawardKetoyoMsatsi 8 days ago I reviewed this. Could you give an update on the state of this PR?

2021-06-23 14:40 UTC, HawardKetoyoMsatsi commented
Hi, @shadrackkibet I have made the proposed changes, kindly take a look.

2021-06-23 14:41 UTC, HawardKetoyoMsatsi commented on instat/dlgWindPollutionRose.vb
> +        dctStatistic.Add("abs.count", Chr(34) & "abs.count" & Chr(34))
Yes, you are right, the labels will look better that way.

2021-06-24 07:43 UTC, shadrackkibet requested changes

2021-06-24 07:43 UTC, shadrackkibet commented on instat/dlgWindPollutionRose.vb
> +        bReset = False
I notice the translation class is missing here!

2021-06-24 21:46 UTC, HawardKetoyoMsatsi commented on instat/dlgWindPollutionRose.vb
> +        bReset = False
Done please take a look

2021-06-25 09:00 UTC, shadrackkibet approved these changes
@rdstern @lloyddewit over to you.

2021-06-27 10:13 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  }
Only one of these if statements will ever be true. Would it be more readable to use `Else If` for the 2nd and 3rd if statements. No changes, needed, I'll approve anyway, it's jiust a thought.

2021-06-27 10:13 UTC, lloyddewit approved these changes

2021-06-27 10:15 UTC, lloyddewit commented
@rdstern If you can test/approve again, then we can merge, thanks

2021-07-06 08:29 UTC, rdstern approved these changes

2021-07-06 08:52 UTC, merged