Implemented functionalities to setup data for data entry dialog
africanmathsinitiative/R-Instat pull request #6409
Opened 2021-04-12 13:37 UTC by N-thony

@lloyddewit this PR is still under implementation. Thanks

2021-04-21 06:29 UTC, rdstern commented
@N-thony this is looking good.  Very good.  It is working and could be accepted now.  There are some small cosmetic things it would be nice to include:
a) Can you change the label `Station: `to `Station Variable:`.  
b) The level of Station has the quotes round it.  You (I think) got rid of those in the Data entry dialogue.  We also don't need them here.
c) If a data frame has been defined as climatic, then the Station and Date fields are usually completed automatically.  This is particularly for the Add Flags option.  
d) Now - only if it is easy.  When the key is added in the usual way (through Prepare > Keys and Links > Add Key a summary is put into the output window.  Could this be included here too.

2021-04-21 12:37 UTC, N-thony commented
@rdstern I resolved your comments. Could you test? Thanks.

2021-04-21 13:05 UTC, rdstern approved these changes
@N-thony looks really good now. 
@lloyddewit on to you

2021-04-22 07:39 UTC, lloyddewit commented
@shadrackkibet Are you willing to peer review this PR? If you prefer someone else then let me know, thanks

2021-04-22 18:02 UTC, shadrackkibet commented
@lloyddewit I am always happy to peer review. However, I also worked on this dialog therefore I would suggest we give an opportunity to someone else to peer review.

2021-04-23 07:04 UTC, lloyddewit commented
> 
> 
> @lloyddewit I am always happy to peer review. However, I also worked on this dialog therefore I would suggest we give an opportunity to someone else to peer review.

@Ivanluv Please could you peer review? thanks

2021-04-23 07:08 UTC, Ivanluv commented
@lloyddewit am happy to review

2021-04-26 07:44 UTC, Ivanluv commented on instat/dlgClimaticDataEntry.vb
> +        lblNbRowsChanged1.Visible = False
should this  also be hidden when moving between dataframes?

2021-04-26 07:44 UTC, Ivanluv commented on instat/dlgClimaticDataEntry.vb
> +        'ucrInputSelectStation.SetParameter(New RParameter("station_name", 6))
could the commented section be removed when they are no longer needed

2021-04-26 07:44 UTC, Ivanluv commented on instat/dlgClimaticDataEntry.vb
> +        'ucrInputSelectStation.AddQuotesIfUnrecognised = False
remove this too

2021-04-26 07:44 UTC, Ivanluv commented on instat/dlgClimaticDataEntry.vb
> +        ucrInputSelectStation.bFirstLevelDefault = True
should this be moved in the `InitialiseDialog()` sub?

2021-04-26 07:44 UTC, Ivanluv commented on instat/dlgClimaticDataEntry.vb
> +        'ucrInputSelectStation.SetRCode(clsGetDataEntry, bReset)
remove this

2021-04-26 07:44 UTC, Ivanluv commented on instat/dlgClimaticDataEntry.vb
> +    Private Sub ucrSelectorClimaticDataEntry_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrSelectorClimaticDataEntry.ControlValueChanged, ucrReceiverStation.ControlValueChanged, ucrRec
`ucrReceiverStation.ControlValueChanged` seems to be handled twice. Could it be possible for these to be handled once?

2021-04-26 07:58 UTC, N-thony commented
@Ivanluv thanks for your review. This PR concern just dlgSetupForDataEntry, but I will consider your comments in PR #6399.

2021-04-26 08:36 UTC, Ivanluv commented on instat/dlgSetupForDataEntry.vb
> +        clsGetKey = New RFunction
could we have the `clsAddKey=New RFunction ` included here?

2021-04-26 08:36 UTC, Ivanluv commented on instat/dlgSetupForDataEntry.vb
> +        ucrChkAddKey.SetText("Add Key")
This checkbox does not update correctly on reopening of the dialogue . With the add key unchecked closing the dialogue and reopening comes up with the add key checkbox checked

2021-04-26 08:36 UTC, Ivanluv commented on instat/dlgSetupForDataEntry.vb
> +        ucrChkAddFlagVariables.SetText("Add Flag Variables")
this checkbox is also not resetting correctly when checked

2021-04-26 09:32 UTC, N-thony commented
@Ivanluv thanks for your comments above, I think I have resolved them. Could you test?

2021-04-26 10:31 UTC, Ivanluv commented
@N-thony  testing now

2021-04-26 10:58 UTC, Ivanluv commented
This looks okay from my end

2021-04-27 08:34 UTC, N-thony commented
@rdstern following your comment in #6401, I have fixed the bug. Could you re-test? Thanks

2021-04-27 09:40 UTC, rdstern requested changes
@N-thony it now seems to be partly fixed.  I tried with the same file I sent (which had no key).  If I opt to get a key it now works fine and produces the key with no problem.
If I get it to add the flag field without getting a key then it still gives an error.  

I didn't check whether adding a key is the default - i.e. it is initially ticked.  I even wonder whether the key should be automatic?  So there might even not be a checkbox.  If it finds no key then it simply adds one just as it adds the flag variable.  What do you think?

Perhaps for now if it is easy to fix the bug, i.e. when no key you still produce the flag field without producing an error.

2021-04-27 09:46 UTC, N-thony commented
> @N-thony it now seems to be partly fixed. I tried with the same file I sent (which had no key). If I opt to get a key it now works fine and produces the key with no problem.
> If I get it to add the flag field without getting a key then it still gives an error.
> 
> I didn't check whether adding a key is the default - i.e. it is initially ticked. I even wonder whether the key should be automatic? So there might even not be a checkbox. If it finds no key then it simply adds one just as it adds the flag variable. What do you think?
> 
> Perhaps for now if it is easy to fix the bug, i.e. when no key you still produce the flag field without producing an error.

I think we can the same as the key is added when creating the new data frame but here it will check first if the exists or not

2021-04-27 10:15 UTC, N-thony commented
@rdstern I removed the Add key checkbox. Now If finds no key then it simply adds one just as it adds the flag variable. Could you re-test? Thanks.

2021-04-27 10:59 UTC, shadrackkibet commented
The good option is to check if there is a key internally in the R function and add if necessary. @N-thony can you do this?

2021-04-27 11:05 UTC, N-thony commented
> The good option is to check if there is a key internally in the R function and add if necessary. @N-thony can you do this?

The check is done through the code when adding flag variables, it adds the key if necessary.

2021-04-27 11:17 UTC, shadrackkibet requested changes

2021-04-27 11:17 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +            clsNewDataFrame.AddParameter("precip", "as.numeric(NA)", iPosition:=2)
Instead, use `NA_real_` here and elsewhere?

2021-04-27 11:17 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +    Private Sub ucrInputSpecify1_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrInputSpecify1.ControlValueChanged, ucrChkSpecify1.ControlValueChanged
Again add a space

2021-04-27 11:17 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +        ucrInputSpecify3.Visible = ucrChkSpecify3.Checked
Use `.AddToLinkedControls` todo this?

2021-04-27 11:17 UTC, shadrackkibet commented on instat/frmMain.resx
>    <data name="mnuTidyandExamineClimaticDataEntry.Size" type="System.Drawing.Size, System.Drawing">
Always have `frmmain` changes done separately else we are likely to have a conflict here.

2021-04-27 11:17 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +            AddRemoveParameter()
Put this outside the `if` statement?

2021-04-27 11:17 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +    End Sub
Combine?

2021-04-27 11:43 UTC, shadrackkibet commented
- The following input controls do not reset
- In this dialog, the label for the station receiver is "Station variable:" elsewhere including data entry it is called "Station:"
![image](https://user-images.githubusercontent.com/26301973/116233619-30aacc00-a764-11eb-9073-b07cc50034a4.png)
- Should I be allowed to click Ok when I have this? When I check Add flag variables and click Ok I get the bug below.
![image](https://user-images.githubusercontent.com/26301973/116235498-9d26ca80-a766-11eb-8626-6f666e5e96b4.png)
![image](https://user-images.githubusercontent.com/26301973/116235290-576a0200-a766-11eb-9b59-32221bf30198.png)

- Sort out tab order

2021-04-27 11:52 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +        clsGetKey.AddParameter("key_name", Chr(34) & "key" & Chr(34), iPosition:=0)
Not all keys are called `key` it can be any string. If a user uses a dataset with a different key say "key1" this will not work!

2021-04-27 12:02 UTC, shadrackkibet commented
> > The good option is to check if there is a key internally in the R function and add if necessary. @N-thony can you do this?
> 
> The check is done through the code when adding flag variables, it adds the key if necessary.

Currently, this doesn't work properly.  My proposal above implies that we do the checking in R i.e in the function `add_flag_fields` and add the key where necessary.

2021-04-27 12:32 UTC, rdstern requested changes
@N-thony trying with the same file there is no error, but it also didn't say it had added the key.  And checking it wasn't added.

2021-04-27 12:39 UTC, shadrackkibet commented
@rdstern In this dialog the station is compulsory! is this what we want? What if I have data for one station without the station column do we assume that the users have to create a station column before using the dialog?

2021-04-27 13:05 UTC, rdstern commented
@shadrackkibet yes I was assuming that!

2021-04-28 05:37 UTC, shadrackkibet commented
@rdstern then as far as I know this is the only climatic dialog that makes this assumption. I do not think there is any technical reason why we should make that assumption here. The dialog should work for multiple stations, single station or no station column (where in this case we use the date column as the key column).

2021-04-28 05:39 UTC, shadrackkibet commented
@N-thony comment and resolve points that you have resolved above.

2021-04-28 06:06 UTC, N-thony commented on instat/dlgSetupForDataEntry.vb
> +        clsGetKey.AddParameter("key_name", Chr(34) & "key" & Chr(34), iPosition:=0)
@shadrackkibet you may edit add_flag_fields so that the check will be done directly in R and adds key if necessary.

2021-04-28 07:16 UTC, rdstern commented
@shadrackkibet you are right and could relax that if you like.

My reasining is that I wanted to follow the "code of conduct" from Climsoft as far as I could.  Partly to show our interest in being compatible.

In Climsoft you have to enter the Station details before you enter data.  I rather like that encouragement.  So, to setup the data sntry you don't necessarily need s station file, but you do, at least need to know something about the station.

2021-04-29 12:51 UTC, N-thony commented
@shadrackkibet I found there is an R function called has_key used to check it exits any key in a data frame. I have used that instead of get_key function.

2021-04-30 18:35 UTC, shadrackkibet commented
> @shadrackkibet I found there is an R function called has_key used to check it exits any key in a data frame. I have used that instead of get_key function.

Good spot. Therefore we need to use it inside the `add_flags_fields` R function. I already did it in the linked PR above therefore you could have a look at it.

2021-05-02 07:35 UTC, lloyddewit commented
@N-thony I understand that this PR is replaced by PR#6435 (now merged). Does this mean that we can now close PR #6409?

2021-05-02 08:29 UTC, N-thony commented
> @N-thony I understand that this PR is replaced by PR#6435 (now merged). Does this mean that we can now close PR #6409?

Yes, we can close it.

2021-05-02 08:32 UTC, lloyddewit commented
This PR is replaced by PR#6435.

2021-05-02 08:32 UTC, closed without merging