Added an option to compare by row to the compare columns dialogue
africanmathsinitiative/R-Instat pull request #6414
Opened 2021-04-14 14:35 UTC by HawardKetoyoMsatsi

Fixes #6393
@africanmathsinitiative/developers @rdstern this is ready for review.

2021-04-14 19:52 UTC, rdstern requested changes
@HawardKetoyoMsatsi great, this is basically working.
a) The tolerance doesn't seem to work.  I tried 0.2 and it always seemed to remain on zero.
b) I suggest, like the non-numeric dialogue you always save the resulting logical variable.  The label can be shorter, as in the other dialogue, so Logical Column:.
c) Could there be a suggested name, perhaps just compare.
d) Instead of the table, where there is the x as the output, perhaps also just use the summary command - again as in the non-numeric dialogue

2021-04-15 14:46 UTC, HawardKetoyoMsatsi commented
@rdstern I have made the requested changes, please take a look.

2021-04-15 17:07 UTC, rdstern commented
@HawardKetoyoMsatsi it is looking good now - and the tolerance works.  Just some small things.
a) The save logical column doesn't remember the setting from last time.
b) Could saving be the default, i.e. it is initially checked.
c) Suggest a default variable name, perhaps `compare`, then it would become compare1, etc.  There is a standard function for this.
d) When saved the output window prints Null see below.  Could this not be done?

![image](https://user-images.githubusercontent.com/11226469/114910117-6b803c00-9e15-11eb-8efd-ab5c970688ed.png)

2021-04-16 14:51 UTC, HawardKetoyoMsatsi commented
@rdstern Kindly have a look at the corrections I have made.

@dannyparsons @shadrackkibet I have removed two comments and a piece of code (below) below from the code and set the data frame selector because I find the save control automatically saves to the Dataframe that feeds the second receiver. Please take a look at it, it must have been implemented already.

`'Not setting data frame selector or prefix here because we need save control only linked to data frame of second selector which is not yet implemented`

    ```
Private Sub ucrReceiverSecond_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrReceiverSecond.ControlValueChanged
        ' Needs to be done manually because data frame name should only be the data frame name from the second receiver's varibable.
        ucrSaveLogical.SetGlobalDataName(ucrReceiverSecond.GetDataName())
    End Sub
```

2021-04-16 17:48 UTC, rdstern approved these changes
@HawardKetoyoMsatsi great.
Approving.  I hadn't realised that usually the other option may have variables from different data frames.  I am assuming the same data frame here.

2021-04-19 07:48 UTC, lloyddewit commented
@N-thony Please could you peer review this PR? We can briefly discuss a good approach. I'll contact you on WhatsApp.

2021-04-19 13:22 UTC, N-thony requested changes

2021-04-19 13:22 UTC, N-thony commented on instat/dlgCompareColumns.vb
>      End Sub
Combine?

2021-04-19 13:22 UTC, N-thony commented on instat/dlgCompareColumns.vb
> +    Private Sub Controls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrSaveLogical.ControlContentsChanged
Only ucrSaveLogical?

2021-04-20 08:48 UTC, HawardKetoyoMsatsi commented on instat/dlgCompareColumns.vb
>      End Sub
@N-thony Combining the two checks in one subroutine will not work in this case, the two checks need to work when separate events are called.

2021-04-20 08:56 UTC, HawardKetoyoMsatsi commented on instat/dlgCompareColumns.vb
> +    Private Sub Controls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrSaveLogical.ControlContentsChanged
@N-thony this is now fixed please take a look.

2021-04-20 09:01 UTC, N-thony commented on instat/dlgCompareColumns.vb
> +    Private Sub Controls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrSaveLogical.ControlContentsChanged
Great, this solves my comment.

2021-04-20 09:02 UTC, N-thony commented
@lloyddewit over to you now. Thanks.

2021-04-20 09:49 UTC, lloyddewit approved these changes

2021-04-20 09:52 UTC, lloyddewit commented
@rdstern since your last approval, there is one small change that should not affect the functionality. Please could you reapprove? thanks

2021-04-20 09:55 UTC, rdstern approved these changes
Very useful addition

2021-04-20 10:03 UTC, merged

2021-04-21 07:14 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
>      End Sub
@HawardKetoyoMsatsi I note that you ought to have used `.ControlValueChanged`  event and not `.ValueChanged` here.

2021-04-21 07:24 UTC, shadrackkibet commented
I did have a quick look and had a few designer points to report.

- Could you improve the design of this dialog? The top radio buttons are not well centred. See below
![image](https://user-images.githubusercontent.com/26301973/115513153-6eeb4b80-a28b-11eb-8cba-f29b63ab48db.png)

- Add colons(:)

2021-04-21 07:32 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
>      End Sub
I see also see a potential problem here; the check for the receivers should be done inside `CheckDatatype()` sub. Otherwise, if you run this sub elsewhere the message box is always shown. To check this just move from one radio button at the top when the receivers are empty you will always get the message which can be annoying to the user. Does this make sense to you?

2021-04-21 07:40 UTC, shadrackkibet commented
@HawardKetoyoMsatsi why do you need `ifelse()` here? Perhaps I am missing something?

`ifelse(test=abs(x=Dagoretti_JKIA.PRECIP - Dagoretti_JKIA.TMPMAX) <= 0, yes=TRUE, no=FALSE)`

Isn't this sufficient? because it always returns a logical value?

`abs(x=Dagoretti_JKIA.PRECIP - Dagoretti_JKIA.TMPMAX) <= 0`

2021-04-21 07:53 UTC, lloyddewit commented on instat/dlgCompareColumns.vb
>      End Sub
@shadrackkibet Thanks for the comment. I looked at the code, and indeed `ucrReceiver` objects normally handle the `ControlValueChanged` event rather than the `ValueChanged` event. I see that the `ValueChanged` event is a standard WinForms event, whereas the `ControlValueChanged` event is a `ucrCore` event (see screen shot below). The code above should work, but I understand that it is better to use handle the `ControlValueChanged` event because this is the standard way of handling this type of event from a `ucrCore` derived object. Is that correct?

![image](https://user-images.githubusercontent.com/57253949/115516755-b91dfe00-a286-11eb-804b-2a7a21ee57be.png)

2021-04-21 07:55 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
>      End Sub
@lloyddewit your statement is correct.

2021-04-21 08:44 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
> +        clsSummaryFunction.AddParameter("x", clsRFunctionParameter:=clsIfElseCompareFunction, bIncludeArgumentName:=False, iPosition:=1)
Always use the correct parameter names. Here it should be `object` and then no need to hide the parameter.

2021-04-21 08:44 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
> +        ucrInputTolerance.SetText("0")
This default should be set as a parameter value to the left of the operator and therefore no need to manually set it here.

2021-04-21 08:44 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
> +                Else
Simplify this by using an `OrElse` in the if statement?

2021-04-21 08:44 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
> +                ucrBase.OKEnabled(True)
The `else` here means when the other radio button is checked Ok should be enabled as shown below. Which is not desired? By the way, look at the spacing of the checkboxes do you notice something?

![image](https://user-images.githubusercontent.com/26301973/115523117-6730a480-a295-11eb-86a2-ea52c3b07d7e.png)

2021-04-21 08:44 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
> +            grpComparisions.Visible = True
This shouldn't be done manually here. Set it as a linked display control i.e `SetLinkedDisplayControl`

2021-04-21 08:44 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
> +                ucrInputTolerance.Visible = False
Check if this is the correct `else`.

2021-04-22 07:33 UTC, lloyddewit commented
@shadrackkibet Thank you for your review.
@HawardKetoyoMsatsi This PR is now merged so I assume you'll address @shadrackkibet 's comments in a new PR. Is that correct?

2021-04-22 07:47 UTC, rdstern commented
I would be happy for @HawardKetoyoMsatsi to address these useful, points from @shadrackkibet .

Alternatively there is a task on quite a number of dialogues, concerned with the Save control and I can include it there.  I'll add the buttons at the top at the same time.  There is also quite a lot of space in the save control, between the label and the next field.  I am waiting for the French version, before commenting on that aspect.

2021-04-27 06:47 UTC, HawardKetoyoMsatsi commented
@lloyddewit Sure, I will address the issues in a new PR. I will however wait for @rdstern's comment concerning issues with the Save control in other dialogs I work on all of them at the same time.

2021-04-27 07:03 UTC, rdstern commented
I have included this in #6397 and have now added @HawardKetoyoMsatsi to that issue.  It is waiting for @Patowhiz and I would be happy for Haward to join me in reminding Patrick about this work.  I had hoped it would be ready for Ivan and Haward to take over by now.

2021-04-27 08:43 UTC, shadrackkibet commented
I would suggest that we consider the changes here as separate from issues in the save control. The change in the save control here is specific to this dialog which can just be fixed from the design. Therefore, I would expect the below change to be included with the changes suggested above.

>a) Check Data > Compare Columns: (closed pull request #6414 by Shadrack:) So centre the buttons at the top, add a colon in the position control label, sort out Alignment of the position control button and check that the default is to put the new (logical) variable after the second column. If easy (and only if easy) note the blank space, where Shadrack suggests the size of the dialogue might change with the setting of the top button.

2021-04-27 08:49 UTC, rdstern commented
@shadrackkibet I would be very happy with that.  Let's do it!  Can you check with @HawardKetoyoMsatsi if he or you or @Ivanluv  can do it?

2021-04-27 09:01 UTC, shadrackkibet commented
@rdstern from our quick discussion here we have agreed as follows;

- @HawardKetoyoMsatsi will work on reviews here and do the changes on the save control that are specific to compare dialog.
- @Ivanluv will look into issue #6397 excluding Compare dialog and fix issues reported on the save control from various dialogs.
-  I will support and review their work

2021-04-27 12:06 UTC, HawardKetoyoMsatsi commented on instat/dlgCompareColumns.vb
> +                ucrInputTolerance.Visible = False
The final commit that was merged had this piece of code updated.

2021-04-27 16:22 UTC, shadrackkibet commented on instat/dlgCompareColumns.vb
> +                ucrInputTolerance.Visible = False
That is right, the question here is to check if `ucrInputTolerance.Visible = False` is the correct as the else