Minor correction to the insert column
africanmathsinitiative/R-Instat pull request #6428
Opened 2021-04-26 09:51 UTC by Ivanluv

Fixes #6442
@africanmathsinitiative/developers  this is ready for review.

2021-04-26 10:03 UTC, rdstern approved these changes
Great

2021-04-26 10:04 UTC, rdstern submitted a review, later dismissed
Great

2021-04-26 11:29 UTC, shadrackkibet commented on instat/dlgInsertColumn.vb
> +
Add parameter positions?

2021-04-26 11:30 UTC, shadrackkibet requested changes

2021-04-26 11:30 UTC, shadrackkibet commented on instat/dlgInsertColumn.vb
> +
Add parameter positions?

2021-04-26 12:30 UTC, shadrackkibet requested changes

2021-04-26 12:30 UTC, shadrackkibet commented on instat/dlgInsertColumn.vb
>          clsInsertColumnFunction.AddParameter("use_col_name_as_prefix", "TRUE")
Still missing position here?

2021-04-26 12:33 UTC, shadrackkibet commented
@rdstern do we want the inserted column to be of class Logical by default? I thought we want numeric class by default.

2021-04-26 12:37 UTC, rdstern commented
@shadrackkibet I had noticed that.  But if you type a number into the logical (all NA) variable, then it automatically becomes numeric.  So I thought that was OK?

2021-04-26 12:43 UTC, shadrackkibet commented
In R we have different `NA` types i.e `NA_integer_, NA_real_, NA_complex_, and NA_character`. If we want to have a numeric class by default then we need to use `NA_real_` as the default. Will this be confusing to users?

2021-04-26 12:47 UTC, rdstern commented
I'd be quite happy with that.  @dannyparsons I don't see any downside to having NA_real_ as the default?

2021-05-03 06:51 UTC, rdstern commented
Can I check this?  It would be good to get it merged today if possible.

2021-05-03 07:33 UTC, Ivanluv commented
@rdstern  yes you can check

2021-05-03 08:57 UTC, rdstern requested changes
@Ivanluv this works fine and good to get into the next version.
It is a bit confusing that the default value is given in the dialogue as NA_real.  Could that still be shown as NA?

2021-05-03 10:20 UTC, rdstern reviewed
@Ivanluv that's fine by me, because I wasn't so worried before.  But it now generates a logical column again!  I thought the idea was that you, would make it numeric.
If you would like to be more dramtic, then you could replace the control by a pull-down into which you could optionally type.  If so, then the default is still NA, perhaps but could be NA_num as you had before.  Then there could be NA, which generates logical and possibly also TRUE, FALSE "small" "Mali" as others.

2021-05-03 10:33 UTC, shadrackkibet commented
A workaround would be to use `as.numeric(NA)`. Make `as.numeric()` and Rfunction and then pass it into the insert column function. Then the default shown in control will remain as `NA`.

2021-05-03 11:25 UTC, shadrackkibet requested changes

2021-05-03 11:25 UTC, shadrackkibet commented on instat/dlgInsertColumn.vb
> +        clsAsNumericFunction.AddParameter("col_data", "NA", bIncludeArgumentName:=False, iPosition:=0)
Always use the correct parameter name. In this case, it should be x and also for the control above. Then there is no need to hide it.

2021-05-03 11:48 UTC, shadrackkibet commented
@Ivanluv I notice I might have misled you in this. Now everything that is imputed into the input control will be coarsed to numeric including characters etc. Therefore I suggest we go by Roger's suggestion above. Really sorry for that!

2021-05-03 12:13 UTC, shadrackkibet commented
Then you need to ensure that for characters you add "" and for numeric and logical no "".

2021-05-03 14:34 UTC, shadrackkibet commented on instat/dlgInsertColumn.vb
> +        ucrInputDefaultValue.SetItems({"NA", "NA_real_"}, bAddConditions:=True, bAddQuotes:=False)
I think there is no harm in adding the other types as well i.e `NA_integer_, NA_complex_` and `NA_character` @rdstern to confirm.
@Ivanluv I think `bAddConditions:=True, bAddQuotes:=False` are redundant here because of two lines(79,80) below?

2021-05-03 14:37 UTC, rdstern commented
Yes, I agree.  Once there is the pull-down it would be fun to create variables of different types.

2021-05-13 07:08 UTC, shadrackkibet commented
@rdstern this looks good. If you approve then we can merge.

2021-05-13 07:21 UTC, rdstern approved these changes
Looks good.  Perhaps @shadrackkibet can also approve and merge?

2021-05-13 07:37 UTC, shadrackkibet commented on instat/dlgInsertColumn.vb
> +        ttColumnDefaultValue.SetToolTip(ucrInputDefaultValue.cboInput, "Include the quotes if the default value is a string, e.g. ""small"".Do not include qoutes if its logical, e.g. TRUE")
```suggestion
        ttColumnDefaultValue.SetToolTip(ucrInputDefaultValue.cboInput, "Include the quotes if the default value is a string e.g. "small". Do not include quotes if the default value is logical e.g. TRUE)

```

2021-05-13 07:54 UTC, Ivanluv commented on instat/dlgInsertColumn.vb
> -        ttColumnDefaultValue.SetToolTip(ucrInputDefaultValue.cboInput, "Include the quotes if the default value is a string, e.g. ""small"".Do not include qoutes if its logical, e.g. TRUE")
@shadrackkibet  the double  quotes before and after small  place the string small within the whole string

2021-05-13 07:56 UTC, shadrackkibet commented on instat/dlgInsertColumn.vb
> -        ttColumnDefaultValue.SetToolTip(ucrInputDefaultValue.cboInput, "Include the quotes if the default value is a string, e.g. ""small"".Do not include qoutes if its logical, e.g. TRUE")
@Ivanluv sorry my suggestion was not correct. Please ignore it.

2021-05-13 07:57 UTC, shadrackkibet approved these changes
@rdstern please re-approve then we can merge.

2021-05-13 08:07 UTC, shadrackkibet commented
@rdstern nothing changed since you last approved. I had a minor suggestion that was wrong.

2021-05-13 08:49 UTC, rdstern approved these changes

2021-05-13 08:53 UTC, merged