Bug fixes: Climatic data entry
africanmathsinitiative/R-Instat pull request #6429
Opened 2021-04-26 13:48 UTC by shadrackkibet

2021-04-27 08:26 UTC, shadrackkibet commented
@rdstern could you please test? There shouldn't be any functionality changes in the dialog. This is just tidying code and fixing bugs in the current version. I would like to merge this before I work on adding flags.

@lloyddewit I welcome you to peer review this. 

I noted some bugs and deviation in the way we set up sub dialogs in PR #6399 which I thought will be quick for me to fix. For learning purposes I would encourage @N-thony to look into changes here and ask questions.

Summary of some of the changes made:

- Setting Rfunctions in the main dialog and then passing them into subdialogs
- Proper resetting of subdialogs i.e have a boolean from the main dialog that is passed into `.setRcode` in the subdialog
- Visibility of tooltips i.e setting it into the parent control
- Restricted comments subdialog data frame selector
- Use of linking system to link controls i.e `AddToLinkedControls`
- Corrected `get_keys` function. We don't have to fix the key name

2021-04-27 09:09 UTC, rdstern submitted a review, later dismissed
@shadrackkibet it still looks fine.
@lloyddewit could you confirm and merge if ok.  It will then be opened again immediately for further work

2021-04-27 09:31 UTC, lloyddewit commented
@rdstern @shadrackkibet yes, I'm happy to review

2021-04-27 10:45 UTC, lloyddewit requested changes
@shadrackkibet Thanks, this looks good.
Please could you look at the comment in `sdgCommentForDataEntry.vb`?
My other comments are less important. I understood that this PR was also about showing good practice. So I used the opportunity to ask your opinion on a couple of things.

2021-04-27 10:45 UTC, lloyddewit commented on instat/sdgClimaticDataEntryOptions.vb
> +        ucrInputTransform.SetValidationTypeAsNumeric()
What was the reason for removing the minimum valid number?

2021-04-27 10:45 UTC, lloyddewit commented on instat/sdgClimaticDataEntryOptions.vb
> +            Return ucrInputTransform.GetValue
Would it improve fault tolerance if we did a `TryCast` here to ensure that the `GetValue` object can safely be cast to a double?

2021-04-27 10:45 UTC, lloyddewit commented on instat/sdgCommentForDataEntry.vb
> +    Private clsGetKey As New RFunction
Is the `New` consistent with the other subdialogs?

2021-04-27 10:45 UTC, lloyddewit commented on instat/sdgCommentForDataEntry.vb
> +        clsGetKey = clsNewGetKey
Will this cancel the effect of lines 101 and 103?

2021-04-27 13:23 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
> +    Private clsGetKey As New RFunction
I like adding `*Function` as well. Generally in the software, we have a mixture of the two. In my opinion, I think we should encourage adding `*Function` and `*Operator` at the end. Therefore I will change the naming here.

2021-04-27 13:45 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
> +            SetNumberCommentEnteredText(sdgCommentForDataEntry.GetSetNumberOfCommentsEntered)
The visual basic naming convention encourages capitalization of the first letter when naming elements [here](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/naming-conventions) Generally in the software, we don't follow this. Checking elsewhere for example `ucrInputComboBox.vb` line 164 I find that we have used `GetSet...` therefore, in this case, I choose to remain with this.
![image](https://user-images.githubusercontent.com/26301973/116251532-6c9b5c80-a777-11eb-9614-7f03c7154349.png)

2021-04-27 14:04 UTC, shadrackkibet commented on instat/sdgCommentForDataEntry.vb
> +    Private clsGetKey As New RFunction
This is another place where we are not consistent generally. 

The reason why I added this is because I get an exception in line 129 because this is not declared as a `New` instance. I had chosen this fix but since it is not consistent I will remove `New` here and instead add a check in line129.

2021-04-27 14:30 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +            Return ucrInputTransform.GetValue
I think you meant `TryParse`? If this is correct then I agree with you.

2021-04-27 16:29 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +        ucrInputTransform.SetValidationTypeAsNumeric()
I don't think the minimum transformation values has to be `0.1` a user might want to use any numeric number.

2021-04-27 17:06 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +            Return ucrInputTransform.GetValue
@lloyddewit I thought of changing this into a function as follows;
```
    Public Function TransformValue() As Object
        Dim dTemp As Double
        If Double.TryParse(ucrInputTransform.GetValue, dTemp) Then
            Return ucrInputTransform.GetValue
        Else
            Return CDbl(ucrInputTransform.GetValue)
        End If
    End Function
```
What do you think?

2021-04-27 17:07 UTC, shadrackkibet commented on instat/sdgCommentForDataEntry.vb
> +        clsGetKey = clsNewGetKey
Yes, It should be just above line 101 and 103

2021-04-27 17:19 UTC, shadrackkibet commented on instat/dlgClimaticDataEntry.vb
> +        clsList.Clear()
No reason. Either work in this case. I will change for consistency.

2021-04-27 17:35 UTC, rdstern commented
@shadrackkibet you are right.  If in inches then 0.01 might be used, so smaller numbers shouldn't be excluded.  0.1 is the obviou value if data are in mms or degrees c, where measured to one decimal place.  Then you may want to enter (say) 12 for 1.2mm and not bother with the decimal point

2021-04-27 18:17 UTC, lloyddewit commented on instat/sdgClimaticDataEntryOptions.vb
> +            Return ucrInputTransform.GetValue
Yes, you're right `TryParse` is the correct function' I liked your function. For me, keeping it as a readonly property is also fine. I think if the `TryParse` fails then we should raise a developer error rather than trying `CDbl`. How about something like below?
```
    Public ReadOnly Property GetTransformValue As Double
        Get
            Dim dTemp As Double
            If Not Double.TryParse(ucrInputTransform.GetValue, dTemp) Then 'If TryParse fails then sets dTemp to zero
                MsgBox("Developer error: The ucrInputTransform combo box contains the value '" & ucrInputTransform.GetValue & "'. Cannot convert this to a double.")
            End If
            Return dTemp 
        End Get
    End Property
```

2021-04-27 18:24 UTC, lloyddewit commented
@shadrackkibet Thank you for the responses. All comments are resolved apart from one (please see above), thanks

2021-04-27 18:37 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +            Return ucrInputTransform.GetValue
Agreed

2021-04-27 18:38 UTC, shadrackkibet commented
> @shadrackkibet Thank you for the responses. All comments are resolved apart from one (please see above), thanks

@lloyddewit I resolved it now. Thanks

2021-04-28 06:30 UTC, lloyddewit approved these changes

2021-04-28 06:31 UTC, lloyddewit commented
@shadrackkibet Thanks for the updates, it all looks good.
@rdstern Please could you approve again? thanks

2021-04-28 07:41 UTC, rdstern approved these changes

2021-04-28 07:52 UTC, merged