Updated compare columns dialog
africanmathsinitiative/R-Instat pull request #6433
Opened 2021-04-28 14:10 UTC by HawardKetoyoMsatsi

@shadrackkibet @africanmathsinitiative/developers This is ready for review.

2021-04-29 07:45 UTC, lloyddewit commented
@HawardKetoyoMsatsi Thank you for the PR. When you open a PR, please could you add more details about what has changed. Is this a bug fix or enhancement? Is it related to an specific GitHub issue? 

@N-thony Please could you peer review? 

Thanks

2021-04-29 07:54 UTC, N-thony commented
> @HawardKetoyoMsatsi Thank you for the PR. When you open a PR, please could you add more details about what has changed. Is this a bug fix or enhancement? Is it related to an specific GitHub issue?
> 
> @N-thony Please could you peer review?
> 
> Thanks

@lloyddewit I'm happy to do it.

2021-04-29 07:59 UTC, N-thony commented on instat/dlgCompareColumns.vb
> +    Private clsCompareColumns, clsAbsoluteFunction As New RFunction
Rename clsCompareColumnsFunction? just for consistency.

2021-04-29 08:22 UTC, N-thony requested changes

2021-04-29 08:22 UTC, N-thony commented on instat/dlgCompareColumns.vb
> +        'ucrPnlOptions.AddFunctionNamesCondition(rdoByValue, {"compare_columns"})
Remove or comment if need in the future?

2021-04-29 08:22 UTC, N-thony commented on instat/dlgCompareColumns.vb
> +        ' ucrPnlOptions.SetRCode(, bReset)
Remove or comment if need in the future all commented lines?

2021-04-29 08:22 UTC, N-thony commented on instat/dlgCompareColumns.vb
> +            'grpComparisions.Visible = True
Again

2021-04-30 18:35 UTC, rdstern approved these changes
Looks ok to merge to me!

2021-05-05 09:12 UTC, HawardKetoyoMsatsi commented
@N-thony  I have fixed the issue raised concerning unnecessary comments.
@lloyddewit this PR only addresses issues suggested by @shadrackkibet in PR #6414

2021-05-05 14:58 UTC, Patowhiz commented
@HawardKetoyoMsatsi in this PR does this dialog expand and shrink it's size based on the radio button checked? If do, then the only thing left is linking the receiver to the `ucrSave` control as outlined by @rdstern in issue #6397. For this dialog, I think this should just be 1 line as done in most dialogs in PR #6434, we can discuss about it further.

2021-05-05 15:02 UTC, Patowhiz commented on instat/dlgCompareColumns.vb
> +            Me.Size = New System.Drawing.Size(Me.Width, iDialogHeight)
Why not just use `Me.height`, since only the height is being changed all the time?

2021-05-05 15:04 UTC, Patowhiz commented
@HawardKetoyoMsatsi in regards to my [comment ](https://github.com/africanmathsinitiative/R-Instat/pull/6433#issuecomment-832758004)above, ignore it. After looking at your code the receiver is already linked and working correctly.

2021-05-07 09:12 UTC, HawardKetoyoMsatsi commented on instat/dlgCompareColumns.vb
> +            Me.Size = New System.Drawing.Size(Me.Width, iDialogHeight)
@Patowhiz I actually can't figure out how to use only Me.height that's why I used Me.size, could you please edit the code then I can try and accept your suggestion from my end.

2021-05-07 09:13 UTC, HawardKetoyoMsatsi commented on instat/dlgCompareColumns.vb
> +    Private clsCompareColumns, clsAbsoluteFunction As New RFunction
@N-thony am done renaming

2021-05-07 13:28 UTC, Patowhiz commented on instat/dlgCompareColumns.vb
> +            Me.Size = New System.Drawing.Size(Me.Width, iDialogHeight)
Okay. Will make a PR to your branch.

2021-05-14 14:01 UTC, lloyddewit requested changes
Thanks, this looks good, just a few small suggestions

2021-05-17 20:53 UTC, rdstern approved these changes

2021-05-20 13:57 UTC, HawardKetoyoMsatsi commented on instat/dlgCompareColumns.vb
> +        Else
No, there is no ElseIf in Sub TestOkEnabled()

2021-05-21 07:06 UTC, HawardKetoyoMsatsi commented on instat/dlgCompareColumns.vb
> +                If rdoByRow.Checked Then
I have brought back If rdoByRow.Checked since the condition checking for datatype applies to both rdoByRow and rdoByValue, The check for rdoByRow should thus come inside the check for the datatype. if I run with your suggestion the check doesnt work when rdoByValue is checked

2021-05-24 09:59 UTC, lloyddewit commented on instat/dlgCompareColumns.vb
> +            ucrSaveLogical.Location = New Point(ucrSaveLogical.Location.X, iBaseMaxY / 1.07)
@HawardKetoyoMsatsi You marked this as resolved but the code was not changed. Please could you clarify?

2021-05-24 10:04 UTC, lloyddewit approved these changes
Thanks! There was just one very small comment so I approved

2021-05-24 10:04 UTC, lloyddewit commented
@rdstern please could you retest/approve? thanks

2021-05-24 17:01 UTC, rdstern approved these changes

2021-05-24 18:05 UTC, lloyddewit commented
@shadrackkibet I'm happy to merge, but if you'd like to review first, then please go ahead

2021-05-24 19:46 UTC, shadrackkibet commented
@lloyddewit looks good.

2021-05-24 19:46 UTC, merged

2021-05-26 09:39 UTC, dannyparsons commented
@HawardKetoyoMsatsi A more descriptive title for the PR would be useful in future as these appear in the release notes. "Updated" is a bit too vague.