Adding and setting save controls to dialogs
africanmathsinitiative/R-Instat pull request #6434
Opened 2021-04-29 09:56 UTC by Patowhiz

Fixes some items in issue #6397

Fixes the following items;

> Prepare > Check Data
> 
> Duplicates: Align. Also Default:The new variables always come at the end. For the third option it is simple, because there is a single receiver. The default should be after the variable. For the first option it takes a whole data frame, so the existing is fine. The middle option takes multiple Variables. Ideally the default is after the last variable in the multiple receiver. I hope that will be easy. (That will usually be the last variable in the data frame, but happy with the rule that what is last in the receiver is the basis for the position.
> Compare Columns. Align. also Adjust: Change to Save result for second column: Default to after 2nd column. It is currently at the end.
> Non-Numeric. Adjust: Add colon and here there is too much space after the label.
> Anonymise. Align, Change name from Hash to hash. Default to after variable - currently at end.

> -----------------------------

> Prepare > Column: Calculate
> 
> Regular Sequence. Align. This is another example where there is no variable. Could it also go after the current variable in the grid, if that exists. Otherwise at the end.
> Enter. There is a big gap after the label Enter Result into which should be smaller. There is no position control yet. As with the others, ideally after the current active variable, or at the end.
> Duplicate Align only!
> Row Summaries. Align. After last variable.
> Rank. Align. After variable chosen. (Also change label of variable to Column to Rank, i.e. get rid of the s.
> Poly: Align. Move control over a bit. Then default is after the variable.
> Random Samples. Align. Ok at the end here.
> Permute. Align. After variable being permuted.

> ---------------------------------------------------

> Prepare > Column: Factor
> 
> Recode Numeric. Move saving control over. Add the Position button - default after column.
> Count in Factor. Align. Default new variable name to be count, not Count, i.e. all lower case. (Position has the correct default.)
> Recode Factor: Align. Change default to after factor variable.
> Combine factor: Align. Change default to after last variable in receiver.
> 

@lloyddewit  For some reasons `dlgRecodeNumeric` is implemented differently, for instance the setting of R code is not done in the 'normal' way and parameters are also manually written. So I only focused on adding the save control. However, I think it should be redone in 'normal' way because I see no reason as to why it shouldn't, but that can be done after discussions

2021-04-30 05:29 UTC, rdstern approved these changes
@lloyddewit  this is work by @Patowhiz on many dialogues.  It is a difficult one to check completely.  It clearly is an improvement and the work will continue with more dialogues and perhaps will also add more small improvements to ones that are "finished".  I have not found any problems, so am approving on the grounds it is an improvement.  Once merged we will do another round of these dialogues and others will also take over adding these improvements to further dialogues.
That's subject (of course) to the code cxhanges all being sensible.

2021-04-30 16:49 UTC, lloyddewit requested changes

2021-04-30 16:49 UTC, lloyddewit commented on instat/dlgRecodeNumeric.vb
> +        autoTranslate(Me)
Move to end of this sub (otherwise the text set during initialisation won't be translated)

2021-05-05 07:28 UTC, Patowhiz commented on instat/dlgAnonymiseIDColumn.vb
>          ucrSaveAnonymisedColumn.SetLabelText("Column Name:")
@lloyddewit that's a good idea. @rdstern what's you suggestion on this?

2021-05-05 07:28 UTC, Patowhiz commented on instat/dlgDuplicates.vb
> +        ElseIf rdoSuccessiveValues.Checked Then
We can have an else that triggers a developer error.

2021-05-05 07:40 UTC, Patowhiz commented on instat/dlgDuplicates.vb
> +        ElseIf rdoSuccessiveValues.Checked Then
@lloyddewit though I'm not sure why this will be a developer error. The else could be raised when the ucrPanel initially checks the radio buttons added to it. My understanding is, the else could only be executed during first initialization of the dialog, the ucrPanel always requires at least one radio button to be checked. 
So I think it's much more stable if I just have an else for successive value radio button.

2021-05-05 07:45 UTC, Patowhiz commented on instat/dlgDuplicates.vb
> +        ElseIf rdoSuccessiveValues.Checked Then
@lloyddewit I looked at this again an realized I did the 2 choices explicitly because there is a 3rd radio button which doesn't have a receiver activated.

![duplicates](https://user-images.githubusercontent.com/21179007/117110566-27f55f80-ad3b-11eb-9647-965c18e95b73.PNG)

2021-05-05 07:48 UTC, Patowhiz commented on instat/dlgRecodeNumeric.vb
> +        autoTranslate(Me)
Done.

2021-05-05 08:09 UTC, lloyddewit commented on instat/dlgDuplicates.vb
> +        ElseIf rdoSuccessiveValues.Checked Then
OK, agreed

2021-05-06 03:45 UTC, Patowhiz commented
@rdstern @lloyddewit if this PR looks good then I suggest merging it. It contains changes to 42 files and this could easily result to conflicts that may need me to redo the work.

2021-05-06 03:49 UTC, Patowhiz commented on instat/dlgAnonymiseIDColumn.vb
>          ucrSaveAnonymisedColumn.SetLabelText("Column Name:")
@lloyddewit I'll implement this in a different PR.

2021-05-07 08:08 UTC, rdstern approved these changes
@lloyddewit This has changed many dialogues - I think 42.  I have checked quite a few and am happy with what they do.  I notice the alignment has been sorted out - minor, but important.  And the Position control seems now to have been added systematically.
I still have some questions, some minor e.g. the colon is still missing in the calculator, and many still default to the end, rather than after the column producing the transformation.  But I still propose these changes be merged and we then continue to look again at many of the respective dialogues.

2021-05-12 14:14 UTC, dannyparsons approved these changes

2021-05-12 14:14 UTC, merged

2021-05-16 12:10 UTC, Patowhiz commented
> @lloyddewit For some reasons dlgRecodeNumeric is implemented differently, for instance the setting of R code is not done in the 'normal' way and parameters are also manually written. So I only focused on adding the save control. However, I think it should be redone in 'normal' way because I see no reason as to why it shouldn't, but that can be done after discussions.

@lloyddewit if you get time and have a look at the dialog and end up agreeing with my above comment, please assign someone to refactor the dialog code and make it consistent with how other dialogs have been implemented. This would be helpful to future developers that may want to look at code implementation examples in the dialogs. Thanks

2021-05-17 10:40 UTC, lloyddewit commented
> 
> 
> > @lloyddewit For some reasons dlgRecodeNumeric is implemented differently, for instance the setting of R code is not done in the 'normal' way and parameters are also manually written. So I only focused on adding the save control. However, I think it should be redone in 'normal' way because I see no reason as to why it shouldn't, but that can be done after discussions.
> 
> @lloyddewit if you get time and have a look at the dialog and end up agreeing with my above comment, please assign someone to refactor the dialog code and make it consistent with how other dialogs have been implemented. This would be helpful to future developers that may want to look at code implementation examples in the dialogs. Thanks

@Patowhiz Thanks for the suggestion.
@Ivanluv In PR #6407 you are trying to open different dialogs from the script. In order to estimate the amount of effort to implement the 'open from script' functionality for all R-Instat dialogs, you are interested in finding dialogs that work in sub-standard ways. Would it be interesting for you to look at 'dlgRecodeNumeric' to see if it has any special characteristics that would make 'open from script' difficult?

2021-05-18 12:02 UTC, shadrackkibet commented on instat/ucrSave.vb
> +            RemoveHandler Me.ucrLinkedReceiver.ControlValueChanged, AddressOf LinkedReceiverControlValueChanged
This line causes a warning message as shown below.

![image](https://user-images.githubusercontent.com/26301973/118647172-b6f98180-b7e9-11eb-807d-2f272adbae15.png)

2021-05-22 09:19 UTC, Patowhiz commented on instat/ucrSave.vb
> +            RemoveHandler Me.ucrLinkedReceiver.ControlValueChanged, AddressOf LinkedReceiverControlValueChanged
@shadrackkibet thanks for the review. I have fixed this warning in PR #6480.