Data entry setup implementation
africanmathsinitiative/R-Instat pull request #6435
Opened 2021-04-29 15:32 UTC by shadrackkibet

This PR is a continuation of work in PR #6409. I mainly did bug fixes in this PR therefore we no longer need PR 6409. @rdstern please test.

2021-04-29 15:44 UTC, rdstern requested changes
@shadrackkibet the New button seems to work fine.
I can't seem to get the Ok enabled in the Add key part so I can't check that?  I tried with the fairview data that just has 3 variables - station, date and rain.  It didn't have a key.  I added the key, but that didn't help.

2021-04-29 16:02 UTC, shadrackkibet commented
@rdstern it should work now.Thanks

2021-04-29 16:17 UTC, rdstern submitted a review, later dismissed
@shadrackkibet great, that now seems to work.

@lloyddewit over to you.  This is one of the dialogues we need for the upgrade.

2021-04-30 06:13 UTC, shadrackkibet commented
@lloyddewit I would like to get this done and merged today.

2021-04-30 12:21 UTC, lloyddewit requested changes
@shadrackkibet This looks good. I like that this is a nice clean dialog implementation. Could it be used as an example of good practice for other developers?
The only thing that really puzzled me was line 338, the other comments are less important.

2021-04-30 13:51 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +        End If
I would make the `elseif` the `else` in this case.

2021-04-30 14:13 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +    Private bReset As Boolean = True
Yes, we could but that will mean we change the load `Sub` as follows? 
![image](https://user-images.githubusercontent.com/26301973/116706955-d6fe0800-a9d6-11eb-9733-db77e058e535.png)
Then perhaps `bFirstLoad ` isn't a good name as an  argument for `SetRCodeForControls(bFirstLoad)`?

I, therefore, suggest we keep it.

2021-04-30 14:25 UTC, shadrackkibet commented
@lloyddewit thanks for the reviews. As you might have noticed much of the code here are from PR #6409. I agree with your points above and therefore I have made the changes in this PR.

For record purposes, I think it is important to understand why these code/comments were added initially. Therefore, I would like to invite @N-thony the author of PR #6409 to answer the questions above because they were initially from his PR.

2021-04-30 14:34 UTC, shadrackkibet commented
> @shadrackkibet This looks good. I like that this is a nice clean dialog implementation. Could it be used as an example of good practice for other developers?

@lloyddewit I do not think this is a good example for other developers. Would you like to have some for documentation purposes? If yes then I can suggest a number of dialogs. Happy to discuss further.

2021-04-30 14:41 UTC, N-thony commented on instat/dlgSetupForDataEntry.vb
> +    Private strStation As String = ""
Yes, you are right.

2021-04-30 14:42 UTC, N-thony commented on instat/dlgSetupForDataEntry.vb
> +        ' Storing and then removing strSpecify3 as a parameter ensures dplyr::mutate does not keep old parameters when the selected variable is changed.
this should be strSpecify1 rather than strSpecify3

2021-04-30 14:42 UTC, lloyddewit commented on instat/dlgSetupForDataEntry.vb
> +    Private bReset As Boolean = True
I agree, we can consider your suggestions for a future  dialog

2021-04-30 14:44 UTC, N-thony commented on instat/dlgSetupForDataEntry.vb
> +            clsNewDataFrameFunction.RemoveParameterByName(strDaframeName.Replace("'", ""))
Yes @lloyddewit in kine 344 the else should remove the added parameter, so it should be strStation

2021-04-30 14:46 UTC, lloyddewit commented on instat/dlgSetupForDataEntry.vb
> +        End If
OK

2021-04-30 14:47 UTC, N-thony commented on instat/dlgSetupForDataEntry.vb
> +        ' This ensures clsNewDataFrame has the correct parameters. Unlike in most functions, in our use of dplyr::mutate in this case, the parameter name is the selected variable.
yes

2021-04-30 14:55 UTC, lloyddewit commented on instat/dlgSetupForDataEntry.vb
> +        ' Storing and then removing strSpecify3 as a parameter ensures dplyr::mutate does not keep old parameters when the selected variable is changed.
I saw that you removed the comment from these 3 subs. I thought the comment was useful. Would you consider adding it back again?

2021-04-30 14:58 UTC, lloyddewit requested changes
Thank you for the changes. There are just 4 small open comments left. If these can be resolved then we can approve and merge.

2021-04-30 16:19 UTC, lloyddewit commented on instat/dlgSetupForDataEntry.vb
> +        ' Storing and then removing strSpecify3 as a parameter ensures dplyr::mutate does not keep old parameters when the selected variable is changed.
Just discussed with @shadrackkibet : 'I don't [think] the comments on each of those subs is useful. It is just a copy-paste. I find the code clear and obvious'. 
That's OK, I'll resolve this comment

2021-04-30 16:35 UTC, lloyddewit requested changes

2021-04-30 16:35 UTC, lloyddewit commented on instat/dlgSetupForDataEntry.vb
> +        Dim strSpecify1 As String = ucrInputSpecify1.GetValue()
I don't think `strSpecify1` can be a local `Sub` variable. It's value needs to be persistent between calls to this function. Previously, `strSpecify1` was an object data member. This was needed because we have to remove the old parameter (with a potentially different name) before the new parameter is added.
The same comment applies to the 2 functions below (for `strSpecify2` and `strSpecify3`).

2021-04-30 16:41 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +        Dim strSpecify1 As String = ucrInputSpecify1.GetValue()
But it's only used in this sub. So we should define it within the scope?

2021-04-30 16:53 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +        Dim strSpecify1 As String = ucrInputSpecify1.GetValue()
I understand your point. I am just concerned that it is only used here therefore it should be declared within?

2021-04-30 17:02 UTC, lloyddewit commented on instat/dlgSetupForDataEntry.vb
> +        Dim strSpecify1 As String = ucrInputSpecify1.GetValue()
If we want to limit the scope to this `Sub` then we could declare a local `Static` variable.
The important thing is that the variable's value is persistent between calls to this `Sub`. This is because we need the previous value so that we can remove the old parameter (with the old name) before we call `strSpecify1 = ucrInputSpecify1.GetValue()`.
I hope this makes sense

2021-04-30 17:14 UTC, shadrackkibet commented on instat/dlgSetupForDataEntry.vb
> +        Dim strSpecify1 As String = ucrInputSpecify1.GetValue()
Yes, this makes sense. I did revert back to the previous setup. Thanks

2021-04-30 18:21 UTC, lloyddewit commented
@rdstern After you approved, we made some changes that may have affected the functionality. Please could you test and approve again? 

@N-thony This PR is based on your code in PR #6409, please could you review and check we didn't misundersatnd anything?

Thanks!

2021-04-30 18:44 UTC, rdstern approved these changes
@shadrackkibet and @lloyddewit this is looking good!

2021-04-30 18:55 UTC, N-thony commented
> @rdstern After you approved, we made some changes that may have affected the functionality. Please could you test and approve again?
> 
> @N-thony This PR is based on your code in PR #6409, please could you review and check we didn't misundersatnd anything?
> 
> Thanks!

@lloyddewit it looks good. Thanks.

2021-04-30 18:55 UTC, merged