Adding flag fields on climatic data entry
africanmathsinitiative/R-Instat pull request #6436
Opened 2021-05-01 16:23 UTC by shadrackkibet

@rdstern this is ready for you to test. Thanks

2021-05-01 18:06 UTC, rdstern commented
I have now checked the problem I found more carefully.  I think it is quite small.
[fairview.zip](https://github.com/africanmathsinitiative/R-Instat/files/6410062/fairview.zip)
It is with the fairview data that just contains rainfall.
I add the flag field and then start the data entry.
However there is no rain from July 1 2014 to October 31 2014.  So I change to range and choose those 4 months  - I use Range rather than month.  I also have a default value of zero (0).  
It works fine and updates.  I chose the option to not save the flag fields.  That is all ok.
Then I return and go back into the data again.  It is still the default value - pale yellow.  
a) I now set to save the flag fields.  It does this and correctly calls them data, because they were there before.
b) But, they should not be pale yellow now, nor be entered.  The default value is only inserted as zero when there is NA.  Here there is now zero, so the default is not used.  Hence no new values are entered.  

That's the problem.  I think it should be easy - I hope - to fix.

2021-05-01 18:43 UTC, shadrackkibet commented
@rdstern that is because the default value checkbox is still checked. So you should uncheck the checkbox once the values are infilled. We can uncheck it once the user clicks Ok and therefore they will not appear as pale yellow despite having changed. Would you like that?

2021-05-01 21:26 UTC, rdstern commented
@shadrackkibet but ther default value is supposed to replace the NA by the default (0).  When it chenged NA into 0 it colours it a pale yellow.  Even if you leave it ticked, there are no NA values when you return to the same data.  You detect this, with the value in the flag field and the default should also.  So nothing should be yellow, or marked as changed the second time round.

2021-05-02 08:24 UTC, rdstern reviewed
@shadrackkibet I think your part seems to be working fine.  Great.
I tried with the Dodoma data and including adding and changing.  It seems to work.
The only problem is that it is quite slow now and this is just for a single station?  

But the bad news is that other parts may have regressed!  In particular the default value may not work as well as before.  I will test further and report separately.

2021-05-02 08:26 UTC, shadrackkibet commented
@rdstern I have just fixed the default value. Could you please re-test now?

2021-05-02 08:33 UTC, shadrackkibet commented
@rdstern I expected it to be a bit slow when adding flags. That is because I have a number of loops inside the R function, I will try to optimize it before release and if not I think we will have to consider it as a separate improvement. However, I don't expect it to be slow with the previous functionality i.e without adding flags.

2021-05-02 09:29 UTC, rdstern approved these changes
Now seems to work well!.  Great

2021-05-02 09:41 UTC, shadrackkibet commented
@rdstern I noted a bug in the metadata. The variable names didn't update correctly and therefore the columns were not visible in the filter subdialog where we want to use the flag columns!

Note that I have also optimized adding of flags. It should be substantially fast now. There is a risk of regression on flag fields with this change. Please check that it works as expected. I did check and seems to work!

2021-05-02 13:31 UTC, rdstern commented
@shadrackkibet it is much faster.  So that's great.  
a) One small thing is that you have the add flag fields checkbox in the data entry.  I suggest the default - when there are the flag fields - is for this to be checked.
b) Then I got this bug.  It may have been there before, and not noticed.
![image](https://user-images.githubusercontent.com/11226469/116814714-32083a00-ab52-11eb-9c9d-be87610bf524.png)

I suspect something is not clearing, because at the bottom it mentions November and 10 days.  That's what I updated earlier for Dodoma.  Now I was using the small new dataset to test the default of zero and that's when the error occurred.

The commands generated were as follows:
![image](https://user-images.githubusercontent.com/11226469/116814872-beb2f800-ab52-11eb-8cc9-2000e9d3cca6.png)

I tried the same after pressing Reset.  Then it worked fine with the following code instead:
![image](https://user-images.githubusercontent.com/11226469/116814925-12bddc80-ab53-11eb-893e-073bb3becda5.png)

2021-05-02 19:45 UTC, shadrackkibet commented
@rdstern I have fixed the bug you reported above. 

> a) One small thing is that you have the add flag fields checkbox in the data entry. I suggest the default - when there are the flag fields - is for this to be checked.

We need an R function to be able to implement this or we use column names from the selector.  I also notice that we need to check if the flags fields exist when creating flags using the setup for data entry dialog. When this PR is merged the user can easily override the flag fields using the setup for data entry without noticing (very dangerous!).  Therefore let's open a separate issue with both of these.

b) Bug fixed!

2021-05-02 20:04 UTC, rdstern approved these changes
@shadrackkibet great - it all seems to be working.  Thanks for all that.
@lloyddewit to check now

2021-05-03 19:20 UTC, lloyddewit requested changes

2021-05-03 19:20 UTC, lloyddewit commented on instat/sdgClimaticDataEntryOptions.vb
>              Dim dTemp As Double
This get potentially returns `Nothing`
```suggestion
            Dim dTemp As Double = 0
```

2021-05-03 19:20 UTC, lloyddewit commented on instat/sdgClimaticDataEntryOptions.vb
>              Dim dTemp As Double
This get potentially returns `Nothing`
```suggestion
            Dim dTemp As Double = 0
```

2021-05-03 19:20 UTC, lloyddewit commented on instat/sdgCommentForDataEntry.vb
> +        End If
Should the checkboxes be set to `False` if the conditions are not met?
Can this be made more readable?
```suggestion
        Dim bStrColumnEmpty = String.IsNullOrEmpty(strColumn)
        Dim bStrRowEmpty = String.IsNullOrEmpty(strRow)
        If Not bStrColumnEmpty Then
            ucrReceiverColumn.Add(strColumn, strSelectedDataFrame)
        End If
        rdoCell.Checked = Not bStrColumnEmpty And Not bStrRowEmpty
        rdoColumn.Checked = Not bStrColumnEmpty And bStrRowEmpty
        rdoRow.Checked = bStrColumnEmpty And Not bStrRowEmpty
        rdoDataFrame.Checked = bStrColumnEmpty And bStrRowEmpty
```

2021-05-03 19:20 UTC, lloyddewit commented on instat/sdgCommentForDataEntry.vb
> +            End If
```suggestion
            cmdAddComment.Enabled = expTemp IsNot Nothing AndAlso expTemp.AsCharacter(0) = "TRUE" AndAlso Not ucrInputComment.IsEmpty
```

2021-05-03 20:21 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +    for (i in names(new_data)[-c(1:2)]) {
Why always not the first two columns? I don't think we should rely on this being correct in all cases.

2021-05-03 20:23 UTC, dannyparsons commented
Thanks for the comments Stephen. I've also added some comments/questions. I don't think any of these are significant functional issues hence I suggest merging as the additions are substantial and needed.

@shadrackkibet please still address the comments

2021-05-03 20:24 UTC, merged

2021-05-04 06:45 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +    for (i in names(new_data)[-c(1:2)]) {
Because we don't want to create flags for station and date columns which are always the first and the second columns in the constructed data frame. A better way will be to get elements separately.

2021-05-04 06:52 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +  changed_data <- curr_data
The data frame is changed in line 3871. In line 3876 and 3877 we need to extract a column from the original(curr_data) data frame and the changed data frame(changed_data) to compare and produce the flag field.

2021-05-04 06:56 UTC, shadrackkibet commented on instat/static/InstatObject/R/instat_object_R6.R
> +DataBook$set("public", "save_data_entry_data", function(data_name, new_data, rows_changed, comments_list = list(), add_flags = FALSE, ...) {
It is not used anywhere. I will remove it. Thanks