Replacing the radio buttons for language in the options dialogue with a combbox
africanmathsinitiative/R-Instat pull request #6452
Opened 2021-05-05 09:35 UTC by Ivanluv

fixes #6358
@africanmathsinitiative/developers this is ready for review
@dannyparsons should I just Include the spanish and kiswahili options and have them enabled even though they are not working?

2021-05-10 09:39 UTC, lloyddewit commented
@HawardKetoyoMsatsi As discussed, please could you do the first review, thanks

2021-05-10 12:42 UTC, HawardKetoyoMsatsi commented
@lloyddewit Sure, I am happy to review this.

2021-05-11 11:51 UTC, Ivanluv commented on instat/dlgOptions.vb
thanks for noticing these.I have fixed it

2021-05-11 11:53 UTC, Ivanluv commented on instat/dlgOptions.vb
>      End Sub
I dont think it should be empty

2021-05-13 15:59 UTC, rdstern requested changes
This looks nice and is much better than the old radio buttons.

I also am quite happy that there are additional languages that show our intent.  And we can see they don't work yet, because when you return to the dialogue the pull-down has gone back to English.  

There is one small problem.  If I move the French then that's fine it is in French.  If I move to Swahili from French it stays in French, but the pull-down says English.  I assume it should remain in French.

2021-05-17 20:44 UTC, rdstern submitted a review, later dismissed

2021-05-18 11:00 UTC, lloyddewit commented
@rdstern @Ivanluv As mentioned above, the dropdown shows languages that are not yet implemented, and shows them as enabled. This is inconsistet with our policy on menus. We only enable a menu option **after** the corresponding dialog has been implemented. 

Having enabled, non-existent languages is confusing to the user. It also means that we have to add special code that jumps back to English or French if one of the not-implemented languages is slected. I tested this and does not yet work correctly.

It would be much simpler just to list English and French for now. We should add other languages to the list only when the language is included. This can be done as part of the PR for the new language.

If @rdstern  has no objections, then please could @Ivanluv remove the not-implemented languages. I can then approve and merge.
Thanks

2021-05-20 18:53 UTC, lloyddewit commented
@Ivanluv I discussed with @rdstern . 
If you change the list to just contain English, French and Portugese then I can approve and merge.
Please treat Portugese exactly the same as English and French (i.e. assume that it is implemented in the database). This is because @dannyparsons will create a Portugese machine translation before the next release.
Thanks

2021-05-24 07:39 UTC, lloyddewit requested changes

2021-05-24 07:39 UTC, lloyddewit commented on instat/dlgOptions.vb
> +                ucrInputLanguage.SetText("French")
Please could you add a `Case`:
```
            Case "pt-PT"
                ucrInputLanguage.SetText("Portugese")
```

2021-05-24 07:39 UTC, lloyddewit commented on instat/dlgOptions.vb
> +                strCurrLanguageCulture = "fr-FR"
Please could you add a `Case`:
```
            Case "Portugese"
                strCurrLanguageCulture = "pt-PT"
```

2021-05-24 07:39 UTC, lloyddewit commented on instat/dlgOptions.vb
>      End Sub
I don't think this `Sub` has any purpose, please could you delete it?

2021-05-24 07:40 UTC, lloyddewit commented
@Ivanluv Please could you also resolve the merge conflicts? thanks

2021-05-24 09:15 UTC, lloyddewit approved these changes

2021-05-24 09:16 UTC, lloyddewit commented
@rdstern Please could you retest/approve? thanks

2021-05-24 16:06 UTC, rdstern requested changes
@Ivanluv just a tiny thing - please add the u in Portuguese.

2021-05-24 17:52 UTC, lloyddewit requested changes

2021-05-24 17:52 UTC, lloyddewit commented on instat/dlgOptions.vb
> +        ucrInputLanguage.SetItems({"English", "French", "Portugese"})
```suggestion
        ucrInputLanguage.SetItems({"English", "French", "Portuguese"})
```

2021-05-24 17:52 UTC, lloyddewit commented on instat/dlgOptions.vb
> +                ucrInputLanguage.SetText("Portugese")
```suggestion
                ucrInputLanguage.SetText("Portuguese")
```

2021-05-24 17:52 UTC, lloyddewit commented on instat/dlgOptions.vb
> +            Case "Portugese"
```suggestion
            Case "Portuguese"
```

2021-05-24 17:53 UTC, lloyddewit commented
> 
> 
> @Ivanluv just a tiny thing - please add the u in Portuguese.

@rdstern 
That was my fault - sorry!
I made the corrections, please could you approve? thanks

2021-05-24 17:54 UTC, lloyddewit approved these changes

2021-05-24 18:58 UTC, rdstern approved these changes

2021-05-24 19:43 UTC, merged

2021-05-26 09:53 UTC, dannyparsons commented
@Ivanluv The combo box should be non-editable. Can you please update this?

2021-05-26 11:09 UTC, Ivanluv commented
@dannyparsons  I have fixed this via PR #6498