Small design fixes in Enter dialog
africanmathsinitiative/R-Instat pull request #6457
Opened 2021-05-06 09:56 UTC by N-thony

@rdstern @lloyddewit this partially fixes #6454.

2021-05-07 10:21 UTC, lloyddewit requested changes

2021-05-07 10:21 UTC, lloyddewit commented on instat/dlgClimaticDataEntry.vb
> +    Private bRemoveValueChanged As Boolean = True
Delete? (see comment below)

2021-05-07 10:21 UTC, lloyddewit commented on instat/dlgClimaticDataEntry.vb
> +        End If
Move the `AddHandler` command could to `InitialiseDialog()` and delete this `If` block?
Is the `AddHandler` even needed? Doesn't the `Handles` on line 307 achieve the same thing?

2021-05-09 07:15 UTC, lloyddewit approved these changes

2021-05-09 07:15 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2021-05-09 11:58 UTC, rdstern approved these changes

2021-05-10 07:23 UTC, merged