Checking and comparing station coordinates within station and shapefiles
africanmathsinitiative/R-Instat pull request #6458
Opened 2021-05-06 14:43 UTC by HawardKetoyoMsatsi

Fixes #6373
@rdstern @africanmathsinitiative/developers This is Ready for review
The PR fixes issue #6373 gadm36_KEN_shp and western_kenya_station_info datasets were used for testing however extra columns for Country, County, and Sub_County should be added to the station file for better testing.

2021-05-07 09:40 UTC, lloyddewit commented
@N-thony please could you review? thanks

2021-05-07 09:56 UTC, N-thony commented
> @N-thony please could you review? thanks

@lloyddewit yes, I'm happy to review.

2021-05-07 10:56 UTC, N-thony commented on instat/dlgLocatingPointsInShapeFile.vb
>      Private Sub CoreControlsContentsChanged_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrReceiverLatitude.ControlContentsChanged, ucrReceiverLongitude.ControlContentsChanged, ucrSa
add ucrReceiverStationFilePolygon and ucrReceiverShapeFilePolygon?

2021-05-10 13:30 UTC, rdstern requested changes
@haward I have trivial comments avout the dialogue.  Please can you check on the spacing of some of the controls.  Then we should also reflect on the polygon label - perhaps it should be Name or Name of Polygon.?
But the main problem - I wonder if you checked this is that it copies the wrong thing into the station file.  I used the Kenya data where there are 51 stations.
a) When I use the zero level it just copies Kenya over and leaves the rest as NA.
b) When I use level 1 - county level.  It copies over the 47 counties in alphabetical order. The last 4 are NA.  It should be copying the 51 county names that correspond to the location of each of the stations.

Once you get that right, i will check the other options.  The last option is a fuzzy comparison to cope with small changes in the names, between the station file and the geometry file.

2021-05-12 10:01 UTC, HawardKetoyoMsatsi commented
@rdstern I have fixed the issue with level zero and Level one gadm files. Kindly have a look.

2021-05-12 11:43 UTC, rdstern commented
@HawardKetoyoMsatsi this is great - it works.
There are some trivial points and one larger one.  
a) Change `Name of Polygon (Optional):` to `Location (Optional): `
b) Add tooltips, for the Station it could say "Name of the Country, County or Ward, if available in the station file"  For the polygon it could say "Name of the Country, County or Ward in the shapefile"
c) the names generated will change to say location rather than polygon.

Now a bigger point.  But I am inclined to merge this first, after you have done this.  An AIMS student is looking at mapping, including this problem, for his essay.  But don't close #6373 yet, because there is something there not done yet.  Unless you are desperate to do it, I would like the AIMS student to look at this problem and then advise you what to do.

2021-05-13 08:43 UTC, HawardKetoyoMsatsi commented
@rdstern this is fixed

2021-05-14 14:41 UTC, lloyddewit requested changes
Thanks, just a few small comments

2021-05-14 14:41 UTC, lloyddewit commented on instat/dlgLocatingPointsInShapeFile.vb
> +    Private clsOpeningSubsetOperator, clsIsEqualToOperator, clsCompareColumnsdollarOperator,
`clsCompareColumnsdollarOperator` is not used, remove?

2021-05-14 14:41 UTC, lloyddewit commented on instat/dlgLocatingPointsInShapeFile.vb
> +        ttStationFile.SetToolTip(ucrReceiverShapeFilePolygon.txtReceiverSingle, "Name of the Country, County or Ward in the shapefile")
'Country, County or Ward` should not be capitalized
```suggestion
        ttStationFile.SetToolTip(ucrReceiverStationFilePolygon.txtReceiverSingle, "Name of the country, county or ward, if available in the station file")
        ttStationFile.SetToolTip(ucrReceiverShapeFilePolygon.txtReceiverSingle, "Name of the country, county or ward in the shapefile")
```

2021-05-14 14:41 UTC, lloyddewit commented on instat/dlgLocatingPointsInShapeFile.vb
> +    Private Sub CoreControlsContentsChanged_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrReceiverLatitude.ControlContentsChanged, ucrReceiverLongitude.ControlContentsChanged, ucrSa
Lines should not normally exceed 100 columns, add line breaks?

2021-05-15 11:23 UTC, HawardKetoyoMsatsi commented
@lloyddewit the above is fixe, please have a look.

2021-05-17 10:24 UTC, lloyddewit approved these changes

2021-05-17 10:26 UTC, lloyddewit commented
@rdstern There are just small changes since your last review, these should not have affected the functionality. Please could you test/approve? thanks

2021-05-17 13:03 UTC, rdstern approved these changes

2021-05-17 13:45 UTC, merged