New climatic data entry grid features
africanmathsinitiative/R-Instat pull request #6467
Opened 2021-05-12 13:11 UTC by Patowhiz

Fixes some items in issue #6352 and #6460.

1. I have changed how defaults are handled("NA", "BLANKS","0").
2. Made design changes in the options subdialog. 
3. "DELETE" action is now recognized.
4. Enhanced the summary system to include count, count>0 and mean.
5. Made major changes in the way the grid is filled and also how the grid subdialog is setup. 

@africanmathsinitiative/developers  @rdstern you can test the above changes as I push more changes that fix the items outlines in the issues.

2021-05-16 21:40 UTC, rdstern commented
In the calculations see the following:
![image](https://user-images.githubusercontent.com/11226469/118409999-2ace4980-b685-11eb-8339-2d376b511043.png)

The sum is correct.  The Count should be the Count of (non NA).  It could even be labelled Count (non NA) in the pull-down if you like.  Currently the Count is 31.  Here it should be 6.  It isn't the number of rows changed - which is 7 here.  It is the number of non-NA in the month.
Similarly the Mean should be the Sum/Count.  So here the Sum = 9 and the Mean = 0.29, i.e. 9/31.  It should be 9/6 = 1.5.

Copy and Paste seem to work - Great. 

I chose to save the flag information, even though there were no flag field, and it seems to create them for me.  If true that is great?

I checked on the default and it seems to work.

There is more, but I suggest we try to merge this as soon as the summary is corrected.

2021-05-17 14:24 UTC, rdstern approved these changes
@Patowhiz I have found one very minor point.  I am approving anyway in case it would be good to merge now and then continue on a separate pull request.  
If not, i.e. you will continue on the same pull request, then I entered a sum and it calculated the difference.  I then deleted what I had entered, - fine - but the difference remained.  It should clear too.

2021-05-17 15:25 UTC, Patowhiz commented
@rdstern I have foxed the "Delete" bug.

2021-05-17 15:53 UTC, rdstern submitted a review, later dismissed
@Patowhiz I am approving again.
@lloyddewit if the code is ok, then it would be good to merge.  There are more changes to come, but they could then be on another pull request.

2021-05-19 07:33 UTC, lloyddewit commented
@shadrackkibet please could you review? thanks

2021-05-19 17:10 UTC, shadrackkibet requested changes
@Patowhiz I had started reviewing but notice you are still making changes so perhaps I should wait?

2021-05-19 17:10 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +        End If
This is now duplicated in line 56. I suggest this be removed because it is not consistent with other subdialogs. We always `autoTranslate(Me)` on load in most subdialogs. We normally do not have `SetDefaults()` for subdialogs because the defaults are set in the main dialog and passed into the subdialog while `InitialiseControls()` is run when the user goes to the subdialog with a boolean set at the end of Initialise sub.

2021-05-20 07:42 UTC, rdstern requested changes
@Patowhiz the add seems not=w to work - great.
Change the label to Add/Edit new data only.  (The Add is before the Edit and get rid of the (NA).  I found it confusing.
Make the message "Previously existing data cannot be changed with the Add option selected."

I saw the 1st of the next month is already in the sub-dialogue, but not implemented?

2021-05-21 12:27 UTC, Patowhiz commented on instat/sdgClimaticDataEntryOptions.vb
> +        ucrInputDefaultValue.SetDropDownStyleAsNonEditable()
@shadrackkibet for now, this was agreed by @rdstern to make it uneditable. In future we could make it editable

2021-05-21 12:32 UTC, shadrackkibet commented on instat/sdgClimaticDataEntryOptions.vb
> +        ucrInputDefaultValue.SetDropDownStyleAsNonEditable()
I thought it is simple to make it editable. Are there any technical challenges?

2021-05-21 12:38 UTC, Patowhiz commented on instat/sdgClimaticDataEntryOptions.vb
> +        ucrInputDefaultValue.SetItems(dctDefaultValues, bSetCondtions:=False)
@shadrackkibet thanks for mentioning this. I've changed the code.

2021-05-21 19:26 UTC, Patowhiz commented on instat/sdgClimaticDataEntryOptions.vb
> +        End If
@shadrackkibet I agree. I've removed the subroutine.

2021-05-21 19:27 UTC, Patowhiz commented
@rdstern that is now implemented.

2021-05-21 19:34 UTC, Patowhiz commented on instat/sdgClimaticDataEntryOptions.vb
> +        ucrInputDefaultValue.SetDropDownStyleAsNonEditable()
@shadrackkibet yes its simple to make it editable. We opted to make uneditable because of some technical challenges in regards to validations of possible user inputs. For instance we want to restrict the defaults to numerics while allowing NA and blank. But seeing your comment, I think we can have it editable and still easily achieve what we want. I'll discuss it with @rdstern and possibly change this.

2021-05-21 20:49 UTC, rdstern submitted a review, later dismissed
@shadrackkibet it now all seems to work.  The radio buttons at the top could be changed, but as only one option is allowed, that can wait until next time.
So I am approving

2021-05-23 09:15 UTC, shadrackkibet requested changes
I have few comments.
-  This message could be better if it directs the user where the Add/Edit option is located. Otherwise, the user might be stuck. I suggest "Previously existing data cannot be changed with the **Add/Edit new data only** option selected in the options subdialog."

![image](https://user-images.githubusercontent.com/26301973/119236149-8ba2c980-bb3e-11eb-9855-ef6a4becf7d8.png)

- There following control doesn't display the default on the first load. 
![image](https://user-images.githubusercontent.com/26301973/119238809-9153db80-bb4d-11eb-93a1-d538f17dec2b.png)

2021-05-24 15:09 UTC, Patowhiz commented
Resolved all of the above @shadrackkibet comments.

2021-05-24 16:04 UTC, Patowhiz commented
@shadrackkibet thanks for the feedback. I have also included your suggestions.

2021-05-24 16:13 UTC, shadrackkibet commented
@rdstern please test and re-approve if you are happy. I don't expect any regression since your last testing.

2021-05-24 17:19 UTC, rdstern approved these changes
@shadrackkibet I have approved again

2021-05-24 19:36 UTC, shadrackkibet approved these changes

2021-05-24 19:37 UTC, merged