Adding annotate to our plotting system
africanmathsinitiative/R-Instat pull request #6484
Opened 2021-05-24 14:21 UTC by Ivanluv

fixes #4312
@africanmathsinitiative/developers this is ready for review. Annotations has been added as a new tab to the plot sub dialogue . @lilyclements could you look at these

2021-05-24 19:54 UTC, rdstern requested changes
@Ivanluv it is exciting to see this has progressed so far.
1. The label geom seems incomplete.  There needs to be a field for the label, as there is for the text geom.
2. I like the way the various limits are enabled and disabled as the geoms change.  I assume the spacing etc can be tidied later.
3. I assume it is adding a layer to the graph.  It isn't within the layers, so I don't know how to dictate its position relative to the other layers.
4.  I assume there could be multiple rectangles, or texts, say.  So shouldn't there be an option to use a data frame for them?

2021-05-26 13:16 UTC, Ivanluv commented
this is still in progress

2021-06-21 14:52 UTC, rdstern commented
@Ivanluv I think I have been leading you astray.  Apologies.  I am now using the examples on [this site](https://ggplot2.tidyverse.org/reference/annotate.html)

a) Asking for the data frame seems to have been an error on my part.  Can you delete it please.
b) Having made a mistake I now get:
![image](https://user-images.githubusercontent.com/11226469/122777852-5526ae80-d2a4-11eb-9ae0-af90b9cec6f3.png)

|Perhaps there is a good reason for this?

c) That's because of the mistakes in this example:
![image](https://user-images.githubusercontent.com/11226469/122778046-88693d80-d2a4-11eb-98ec-70ee39ef6929.png)

I had deleted the contents of 2 controls - which I could do?
![image](https://user-images.githubusercontent.com/11226469/122778150-a0d95800-d2a4-11eb-8639-6434a30cdd5c.png)

It then generated the following code:
```
# Code generated by the dialog, Bar and Pie Chart
Sheet.1_by_village_variety <- data_book$get_data_frame(data_name="Sheet.1_by_village_variety")
last_graph <- ggplot2::ggplot(data=Sheet.1_by_village_variety, mapping=ggplot2::aes(x=village, fill=variety)) + ggplot2::geom_bar(position="dodge") + ggplot2::annotate(ymin=2, xmin=2, xmax=4, ymax=4, geom="rect", fill="", colour="", alpha=0.20, size=5.0) + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="Sheet.1_by_village_variety")
data_book$get_graphs(data_name="Sheet.1_by_village_variety", graph_name="last_graph")

```
You can see it then does fill="",colour="" in the code, which R doesn't like.  There seems to be a very limited set of colours there.  I can type gray there and it works.  Or, if empty, getting rid of those commands also works.  Could you check on what to do there.

d) When I have text there I seem to be able to change almost all the controls.  Is that right, or should most be disabled as they are when I have a label?

![image](https://user-images.githubusercontent.com/11226469/122781375-a5534000-d2a7-11eb-857a-4936e2cf57f6.png)
  
e) With label most are disabled, but xend and yend are enabled?  Is that right - see below:
![image](https://user-images.githubusercontent.com/11226469/122782044-48a45500-d2a8-11eb-8d6b-e3fc98b14225.png)

This gives the following:  I also chose fill = black, but it didn't?
![image](https://user-images.githubusercontent.com/11226469/122782298-830df200-d2a8-11eb-8de6-9f2adc32c04d.png)

In the code it didn't give me a fill="black".  More checks and tests needed of those.

Cheers

Roger

2021-07-05 14:01 UTC, Ivanluv commented
@rdstern could you review this

2021-07-06 19:53 UTC, rdstern commented
@Ivanluv it looks better now, but doesn't seem to work.  I did a simple bar chart with the survey data and added annotate.

The code generated is as follows for first some text and also a rectangle.

Notice there is a `+ + `and no annotate.  Of course it gives an error

```
# Code generated by the dialog, Bar and Pie Chart

survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=village, fill=fertgrp)) + ggplot2::geom_bar(stat="count") +  + theme_grey() + ggplot2::scale_x_continuous(position="") + ggplot2::scale_y_continuous(position="")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))
# Code generated by the dialog, Bar and Pie Chart

survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=village, fill=fertgrp)) + ggplot2::geom_bar(stat="count") +  + theme_grey() + ggplot2::scale_x_continuous(position="") + ggplot2::scale_y_continuous(position="")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))
```

When you are checking could you also look at the defaults for the size and alpha.  I have a feeling they started at zere and zero.  Not sure though.
![image](https://user-images.githubusercontent.com/11226469/124658841-2dd30280-de9c-11eb-816b-b233160097cb.png)

2021-07-08 07:47 UTC, Ivanluv commented
@rdstern  I have fixed the errors

2021-07-08 12:59 UTC, rdstern commented
@Ivanluv this now seems to be working well.  It is getting very exciting in what it can do!

1) for text and label, why are xend and yend enabled?  I don't think they do anything.
2) rect - nice - seems to be working well.
3) segment - nice - seems to be working well.
4) pointrange - nice also - I note you only need 2 of xmin, xmax or ymin, ymax.  It is a point plus a line and either vertical or horizontal.  That's all fine.
5) linerange - nice again again you only need one half out of xmin, xmax or ymin, ymax.  
6)  errorbar and crossbar also seem ok.

So I would like just to suggest a change in the label positioning.  Could you move the Fill to just under the Colour.  Then the label itself is last - as for the text.
Underneath for each could you have a checkbox with the label Parse.  Default is unchecked.  If checked, then it adds the parse = TRUE to the R command.
Now the tricky bit.  I would like to find a way we could include any of these examples:

`p + annotate("text", x = 2:3, y = 20:21, label = c("my label", "label 2"))`

```
p + annotate("text", x = 4, y = 25, label = "italic(R) ^ 2 == 0.75",
  parse = TRUE)
```
```
p + annotate("text", x = 4, y = 25,
  label = "paste(italic(R) ^ 2, \" = .75\")", parse = TRUE)
```

I think this should work if we always have to type the quotes in the label ourselves.  So you don't add them.  And if you ever detect a "," then you add c(   ) to the text.  Initially you could add that anyway, rather than test.  It does no harm.

2021-07-13 08:52 UTC, Ivanluv commented
@rdstern  I have  implemented this `p + annotate("text", x = 2:3, y = 20:21, label = c("my label", "label 2"))`
and you don't have to type the quotes for `My label` and `label 2`.
Could you look at this

2021-07-13 10:28 UTC, rdstern approved these changes
@Ivanluv this looks great.  Let's merge if @lloyddewit is ok with the code

2021-07-21 11:20 UTC, rdstern commented
@lloyddewit or @shadrackkibet can this be merged.  It is a very useful improvement

2021-07-21 18:00 UTC, shadrackkibet requested changes

2021-07-21 18:00 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> -    Private bFirstLoad As Boolean = True
It is difficult to know what changed in this file because the github diff is confused!

2021-07-22 08:16 UTC, Ivanluv commented on instat/sdgPlots.vb
> +    Private Sub ucrChkNoOfRowsOrColumns_ControlValueChanged(ucrChangedControl As ucrCore)
Thanks for these. I have made the needed changes to the handlers

2021-07-22 08:19 UTC, Ivanluv commented on instat/sdgPlots.vb
> +            grpAnnotation.Visible = True
Done

2021-07-22 08:20 UTC, Ivanluv commented on instat/sdgPlots.vb
> +    End Sub
Done

2021-07-22 08:26 UTC, Ivanluv commented on instat/sdgPlots.vb
> +        If bControlsInitialised Then
when a new instance of the dialogue is created the location of some controls is 0 since they are not yet initialised and the text is empty hence the code in the else suite is run. I have  however reimplemented that by checking for the text from the annotations

2021-07-22 08:26 UTC, Ivanluv commented on instat/dlgBarAndPieChart.vb
> -    Private bFirstLoad As Boolean = True
how can I fix this?

2021-07-22 09:46 UTC, shadrackkibet requested changes

2021-07-22 09:46 UTC, shadrackkibet commented on instat/sdgPlots.vb
> +        grpAnnotation.Visible = False
Do you still need this?

2021-07-22 09:46 UTC, shadrackkibet commented on instat/sdgPlots.vb
> +        ucrNudLinetype.SetRDefault(1)
How did you determine these R defaults? (here and below). It's not clear from the documentation. I would rather have them added as parameter values by default.

2021-07-22 09:47 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> -    Private bFirstLoad As Boolean = True
Not sure how you could fix this easily.

2021-07-22 09:50 UTC, shadrackkibet commented on instat/sdgPlots.vb
> +        If bControlsInitialised Then
I am not sure I understand this clearly but if it works well no need to change it.

2021-07-22 09:59 UTC, Ivanluv commented on instat/sdgPlots.vb
> +        ucrNudLinetype.SetRDefault(1)
this R Defaults are were suggested by @lilyclements  in the issue

2021-07-22 10:01 UTC, Ivanluv commented on instat/sdgPlots.vb
> +        grpAnnotation.Visible = False
No. Am removing it

2021-07-22 10:24 UTC, shadrackkibet approved these changes
@rdstern functionality shouldn't be affected could you re-test and approve?

2021-07-22 18:57 UTC, rdstern approved these changes

2021-07-22 18:59 UTC, merged