Fixed bug in importing excel files
africanmathsinitiative/R-Instat pull request #6501
Opened 2021-05-27 11:28 UTC by Patowhiz

Fixes #6482
@africanmathsinitiative/developers this is ready for review.

2021-05-28 06:54 UTC, lloyddewit submitted a review, later dismissed

2021-05-28 06:54 UTC, lloyddewit commented
@rdstern please can you test? thanks

2021-06-04 11:08 UTC, Patowhiz commented
@rdstern you can now also test if this PR fixes issue #6476. I had to push changes here because they affect the same dialog. Thanks.

2021-06-04 12:43 UTC, Patowhiz commented
@lloyddewit I think this should now also have a "feature" label.

2021-06-05 21:09 UTC, rdstern commented
@Patowhiz great.  This now works fine on the import, with just the extension given as the sheet name.
But I wonder what should happen next?  When I open again it seems ok as well.

However, I tried closing the Data Book to go back to your introductory screen.  I think then perhaps the Open dialogue should reset?    (I suggest this is a reasonable thing to do, if the import of multiple files didn't work as well as would be hoped - that's the situation with the Pakistan files, where we find they are inconsistent.)

Currently, when I then try to open an rds file I get:

![image](https://user-images.githubusercontent.com/11226469/120905241-a732c780-c648-11eb-9216-15c833df93ff.png)

If I try to open a similar single file to before I get:

![image](https://user-images.githubusercontent.com/11226469/120905263-e7924580-c648-11eb-8761-4817622fb8b9.png)

In each case I have to press Reset.  Then I get the default directory:
![image](https://user-images.githubusercontent.com/11226469/120905321-36d87600-c649-11eb-92b3-59f78e117906.png)

Aha.  I need to press REset on the dialogue.  Then I close it and the try again from the start-up screen.  

I wonder what should happen?

2021-06-06 06:57 UTC, lloyddewit commented
> 
> 
> @lloyddewit I think this should now also have a "feature" label.

agreed

2021-06-06 09:42 UTC, Patowhiz commented
@rdstern thanks for the multiple testing. That's definitely a bug probably cause by my new additions. Let me fix that.

2021-06-14 19:34 UTC, Patowhiz commented
@rdstern I'm unable to reproduce the bug you described above. Closed the databook as explained above and reopened the dialog and it still retained its previous state. Perhaps a skype meeting to demonstrate how you got this bug or steps that I can take to reproduce it

2021-06-22 13:24 UTC, Patowhiz commented
@rdstern I have fixed the bug you described above. You can now review.

2021-06-23 07:48 UTC, rdstern approved these changes
From my point of view this seems ok

2021-06-25 05:58 UTC, Patowhiz commented
This PR is blocking issue #6196 and refactoring of the import dialog. It may potentially also block issue #6556.

2021-06-27 09:56 UTC, lloyddewit requested changes

2021-06-27 09:56 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +        'only add if its a file that was selected, don't folder paths
```suggestion
        'only add if its a file that was selected, don't add if folder path was selected
```

2021-06-27 09:56 UTC, lloyddewit approved these changes

2021-06-27 10:00 UTC, lloyddewit commented
@rdstern I made a small change to one of the comments. If you can approve again, then I'll merge, thanks

2021-06-27 10:15 UTC, rdstern approved these changes

2021-06-27 10:34 UTC, merged