Paste new data frame
africanmathsinitiative/R-Instat pull request #6503
Opened 2021-05-29 07:39 UTC by Patowhiz

Fixes #6061

2021-05-31 08:30 UTC, lloyddewit commented
@shadrackkibet please could you review? thanks

2021-06-01 18:06 UTC, shadrackkibet requested changes

2021-06-01 18:06 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
> +        clsTempImport.AddParameter("nrows", ucrNudPreviewLines.Value)
Why is this set manually? Can't this be done through `SetRcode`?

2021-06-01 18:06 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
> +        ucrNudPreviewLines.Value = 10
We shouldn't be setting this manually here. It should be added as a parameter value.

2021-06-01 18:06 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
> +        ucrNudPreviewLines.Maximum = 1000
I see the minimum is set in the control properties. I think we should set min/max here.

2021-06-01 18:16 UTC, shadrackkibet commented
- Sort out Tab order?
- Why the column name is SetRcode when nothing is on the clipboard? 
![image](https://user-images.githubusercontent.com/26301973/120371137-0e393f00-c31e-11eb-8837-9e288a81594d.png)
- I think it's better to have the preview controls at the bottom left. That is what we have in the import dialog.

2021-06-01 18:18 UTC, shadrackkibet requested changes

2021-06-01 18:18 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
> +        'so let clipr use its clipboard functionality. commented code left here for future refernce
```suggestion
        'so let clipr use its clipboard functionality. commented code left here for future reference
```

2021-06-01 18:22 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
> +        clsTempImport.AddParameter("header", If(ucrChkRowHeader.Checked, "TRUE", "FALSE"))
Why is this not done through SetRcode?

2021-06-02 11:14 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        clsTempImport.AddParameter("nrows", ucrNudPreviewLines.Value)
@shadrackkibet the R function variable used here is local to the VB.NET function.

2021-06-02 11:22 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        TestOkEnabled()
Yes it can be placed there as is the case in other dialogs. But I have it here because of what happens in `TestOkEnabled`. I choose to have it here to avoid the temporary "blinks" on the dialog as the user types in the name. The validation involves reading the clipboard data and I find it optimal and still functional to have it done here when this control has received user changes.

2021-06-02 11:25 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        TestOkEnabled()
This is a click event for a VB.NET button. VB.Net click events have different signatures to the custom events in R-Instat so I had to have this event on its own, thus the repetition.

2021-06-02 11:30 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        'ucrBase.iHelpTopicID = 332
@shadrackkibet 332 is just a random commented placeholder number that will be replaced later as the todo. states. I've changed it to blank.
@rdstern what should be the help id for this dialog? I can still leave it as a todo comment if it needs time to be created.

2021-06-02 11:39 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        ucrNudPreviewLines.Value = 10
@shadrackkibet why should we be adding it as a parameter value? 

I'm doing it manually because the control never reads nor writes to the base R function or any R functional global to this dialog class. It's specifically used for preview locally to the function used to preview the clipboard data.

2021-06-02 11:42 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        ucrNudPreviewLines.Maximum = 1000
Done.

2021-06-02 11:52 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        clsTempImport.AddParameter("header", If(ucrChkRowHeader.Checked, "TRUE", "FALSE"))
Same as above comment.

2021-06-02 12:03 UTC, Patowhiz commented
> * Sort out Tab order?
> * Why the column name is SetRcode when nothing is on the clipboard?
>   ![image](https://user-images.githubusercontent.com/26301973/120371137-0e393f00-c31e-11eb-8837-9e288a81594d.png)
> * I think it's better to have the preview controls at the bottom left. That is what we have in the import dialog.

@rdstern what's you suggestion on the new design changes proposed by @shadrackkibet above. I'm happy with either. My main concern would be the UX flow but I can see the benefit of the dialog consistent with the other dialog.

2021-06-02 12:18 UTC, rdstern commented
@Patowhiz and @shadrackkibet I don't have strong views.  I like consistency as a default.  But this may be sufficiently different that the change is sensible.  Here is the import dialogue.
![image](https://user-images.githubusercontent.com/11226469/120477980-45523380-c3a4-11eb-88fe-a0273d8ea1f1.png)

The preview isn't so wide, as here, so the Refresh preview is below the preview there.  And the important First Row is Column Names is top left, with other options.  However, it seems neat and clear where it is.  If there are other options, then I'd be inclined to put them together, and I suppose at the bottom.  If not, then I quite like it at the top, because that's where the first line - possibly the header line - will be too.

2021-06-02 17:03 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
> +        TestOkEnabled()
This means Ok will still be enabled even if the save control is empty although you can't click Ok?

2021-06-02 17:06 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
> +        clsTempImport.AddParameter("nrows", ucrNudPreviewLines.Value)
Can't we make the function global then it will be possible to SetRCode?

2021-06-02 17:11 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
> +        ucrNudPreviewLines.Value = 10
If you agree to make `clsTempImport` function global then it will be possible to set defaults this way. 

Briefly, I understand that in future we want dialogs to open from script therefore we should try to pass parameters by setting Rcode.

2021-06-02 17:43 UTC, shadrackkibet commented on instat/dlgPasteNewDataFrame.vb
>          ucrNudPreviewLines.Maximum = 1000
Use `ucrNudPreviewLines.SetMinMax()` to make this one line?

2021-06-03 10:14 UTC, Patowhiz commented
@africanmathsinitiative/developers a few comments to add;
1. This dialog will load slowly if the data to be pasted is long e.g data with 10 columns and over 2000 rows.
2. Reproducibility has taken precedence over optmisation in the execution of code.
3. `clsRcodeStructure` object that constructs "assign to" statements doesn't yet correctly support script produced by this dialog, so modification have been added to make this dialog work(check inline comments).

2021-06-03 10:14 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
>          ucrNudPreviewLines.Maximum = 1000
Done.

2021-06-03 10:24 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        ucrNudPreviewLines.Value = 10
> If you agree to make `clsTempImport `function global then it will be possible to set defaults this way.

@shadrackkibet yes that's one alternative. But I thought that will just complicate the dialog more and will still not achieve the required aim. The other alternative which is just to clone the R function object that is being "duplicated" by `clsTempImport`. I have chosen that alternative as it simplifies the code and could be used achieve the aim of reproducibility in future.

> Briefly, I understand that in future we want dialogs to open from script therefore we should try to pass parameters by setting Rcode.

@shadrackkibet yes. But `ucrNudPreviewLines` never reads nor writes to the dialog's base functions. Which means any changes made to it will never be logged in the R log file.

2021-06-03 10:31 UTC, Patowhiz commented
@africanmathsinitiative/developers after discussing @rdstern and @dannyparsons a few comments to add;
1. Reproducibility has taken precedence over optmisation in the execution of code (though this is only affected when the data is large).
2. This dialog may load slowly if the data to be pasted is large (e.g data with 10 columns and over 2000 rows) but this acceptable because we want to discourage users from "pasting" large data(for large data they should use import dialog).
3. `clsRcodeStructure` object that constructs "assign to" statements doesn't yet correctly support script produced by this dialog, so modification have been added to make this dialog work(check inline comments for further explanation).
4. Currently, this dialog will always show contents of the clipboard by reading from the system clipboard every time the dialog is loaded. Which means on reloading, the contents being previewed may be different. To make the dialog to open from script and preview the data from script, a design change will have to be made.

2021-06-03 10:33 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        clsTempImport.AddParameter("header", If(ucrChkRowHeader.Checked, "TRUE", "FALSE"))
This parameter is now read and written by the control. Done.

2021-06-03 10:41 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        TestOkEnabled()
@shadrackkibet thanks. I have modified the `TestOkEnabled` to work correctly when the save control is empty.

2021-06-03 12:57 UTC, Patowhiz commented
@rdstern based on @dannyparsons suggestion I have now restricted the allowable data paste to 1000 rows. Please retest this and check how it performs on your machine.

2021-06-03 15:19 UTC, rdstern requested changes
@Patowhiz this is great.  For me it works fine.  I tried with longer than 1000 rows and it was quick in not letting me.
I imported with 999 rows and 10 variables and it was quick.  
The only item to correct is that it always says there are 10 rows to import.  That's under the preview.  It should give the number of rows in the clipboard, not in the proview.

Then I am ready to approve!

2021-06-05 15:42 UTC, Patowhiz commented
@rdstern as discussed, I have removed the display of columns and rows found. Ready for your review.

2021-06-21 07:30 UTC, rdstern submitted a review, later dismissed
@lloyddewit from my point of view this is working really well.

2021-06-22 13:57 UTC, lloyddewit commented
@shadrackkibet Thank you for your peer reviews on this PR. It looks like most of your comments are now resolved. However, there are still some open comments. Your comments about SetRCode are especially important.
Please could you check if all your comments are resolved? If so, please could you approve?
I will then review, approve and merge.
Thanks

2021-06-22 14:00 UTC, shadrackkibet submitted a review, later dismissed
Thanks @lloyddewit I don't think it is worth delaying anymore. Over to you.

2021-06-24 10:45 UTC, lloyddewit requested changes
This looks good, just a few suggestions

2021-06-24 10:45 UTC, lloyddewit commented on instat/dlgPasteNewDataFrame.vb
> +        autoTranslate(Me)
This should be at the end of the sub.
Otherwise the text set in `InitialiseDialog` will not be translated.

2021-06-24 10:45 UTC, lloyddewit commented on instat/dlgPasteNewDataFrame.vb
> +    Private clsAddData, clsDataList, clsPasteFunction As New RFunction
Could we rename these RFunctions?
```suggestion
    Private clsAddDataFunction, clsDataListFunction, clsPasteFunction As New RFunction
```

2021-06-24 10:45 UTC, lloyddewit commented on instat/dlgPasteNewDataFrame.vb
> +    Public Sub SetClipBoardDataParameter()
Should this be private?
If it needs to be public, then we should add a header comment

2021-06-24 10:45 UTC, lloyddewit commented on instat/dlgPasteNewDataFrame.vb
> +            lblConfirmText.Text = "Could not preview data. Cannot be pasted."
Ensure text translated
```suggestion
                lblConfirmText.Text = GetTranslation("Click Ok to paste data to new data frames.")
                lblConfirmText.ForeColor = Color.Green
            Catch
                lblConfirmText.Text = GetTranslation("Could not preview data. Cannot be pasted.")
            End Try
        Else
            lblConfirmText.Text = GetTranslation("Could not preview data. Cannot be pasted.")
```

2021-06-30 10:08 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +        autoTranslate(Me)
Done.

2021-06-30 10:09 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +    Public Sub SetClipBoardDataParameter()
Yes, should be private. done

2021-06-30 10:09 UTC, Patowhiz commented on instat/dlgPasteNewDataFrame.vb
> +    Private clsAddData, clsDataList, clsPasteFunction As New RFunction
Done.

2021-06-30 10:56 UTC, lloyddewit approved these changes

2021-06-30 10:58 UTC, lloyddewit commented
@rdstern The changes since your last approval should not have affected the functionality. Please could you retest and approve? thanks

2021-06-30 11:02 UTC, rdstern approved these changes

2021-07-01 09:52 UTC, merged