Added more option in the file menu and icon toolstrip
africanmathsinitiative/R-Instat pull request #6507
Opened 2021-06-02 11:06 UTC by Patowhiz

Fixes #6466

@africanmathsinitiative/developers this is ready for review.

2021-06-03 07:43 UTC, lloyddewit commented
@Ivanluv - please could you peer review? thanks

2021-06-03 21:47 UTC, rdstern commented
It works - great.  But I currently have the maximum of 30 files and it is quite long.
a) One change I would like is to reset it once the menu is closed.  Currently, if you have ever pressed More, then it is there forever.
b) In the File menu the Exit option is the last one.  I suggest it be hidden when the More is pressed.
c) Sometimes the More is Plus?  I am happy with either, but wonder why the word changes?

Here is the file menu with the option in action.  

![image](https://user-images.githubusercontent.com/11226469/120715949-41660480-c4bd-11eb-9910-a583c02bf4ac.png)

I am sort of happy with that, (as long as the Exit isn't still there at the bottom, but it is perhaps slightly odd that the menu doesn't keep some of the other options visible.

@dannyparsons was very keen that we keep the options the same for the toolbar and the file menu.  I would like it there somewhere.  So if others feel it makes the File menu look too odd, then perhaps we just add it to the toolbar?

2021-06-05 12:48 UTC, Patowhiz commented
@rdstern I have added the above requested changes. You can now review.

2021-06-05 22:29 UTC, rdstern commented
@Patowhiz you asked to see the Plus.  I am not sure why it sometimes happens and am not against it!  Here is is this time!
![image](https://user-images.githubusercontent.com/11226469/120906978-a3f20880-c655-11eb-82f0-1621f5708534.png)

Happy with it now resetting each time.  I think that's better.

2021-06-05 22:29 UTC, rdstern approved these changes

2021-06-06 09:45 UTC, Patowhiz commented
@lloyddewit could the "Plus..." be related in anyway with the translation? In the code, I found some changes that make the "More..." text be retrieved through the translation function. That's my suspicion.

2021-06-06 09:51 UTC, rdstern commented
@Patowhi - sorry that's my mistake.  Of course - it IS the French!  So, nothing for you to do except (of course) include the time you have wasted looking for a non-existent problem that I have introduced!

2021-06-07 06:56 UTC, Ivanluv commented
@lloyddewit  the code looks okay from my end

2021-06-08 14:24 UTC, lloyddewit requested changes
This looks good! just a few small suggestions

2021-06-08 18:00 UTC, Patowhiz commented on instat/clsRecentFiles.vb
> +                strFileName = Path.GetFileName(strPath)
@lloyddewit I have declared the 2 variables just above the start of the for loop so that their addresses can be reused in the for loop and also be consistent with how I'm using the `ToolStripMenuItem `and `LinkLabel `objects that are also used in the for loop function.

2021-06-08 18:00 UTC, Patowhiz commented on instat/clsRecentFiles.vb
> +        Dim linkMenuItem As LinkLabel
Yes we can delete one of them.

2021-06-08 18:10 UTC, Patowhiz commented on instat/clsRecentFiles.vb
> +                strFileName = Path.GetFileName(strPath)
@lloyddewit after relooking the code, I think any optimization in regards to this function is insignificant compared to the code clarity, the list will never be big enough to cause any noticeable slow performance. So I've moved the declarations to the individual blocks.

2021-06-08 18:11 UTC, Patowhiz commented on instat/clsRecentFiles.vb
> +                If strFilePath.Contains("more") Then
Agreed and redone.

2021-06-08 18:14 UTC, Patowhiz commented
@lloyddewit I have made the suggested code changes. You can now review.

2021-06-09 07:52 UTC, lloyddewit requested changes
Thanks for the changes, I agree with them all.
I have a few extra comments

2021-06-09 07:52 UTC, lloyddewit commented on instat/clsRecentFiles.vb
>          If TypeOf sender Is ToolStripItem Then
If we add an extra condition to this `If` then could we remove lines 167, 169, 170, 172, 177, 179, 184?
```suggestion
        If TypeOf sender Is ToolStripItem AndAlso toolStripItem.Tag.ToString() = "MRU:more" Then
```

2021-06-09 07:52 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +        'then add and displays items (_in reverse order) for recent files
```suggestion
        'then add and display items (in reverse order) for recent files
```

2021-06-09 07:52 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +                    'if recent files are more than 5 then just the "more" link label and exit loop
```suggestion
                    'if recent files are more than 5 then display the "more" link label and exit loop 

```

2021-06-09 07:52 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +
```suggestion
```

2021-06-09 07:52 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +                    'set the tag - will be used to identify the ToolStripItem as an most recent(MRU) item
```suggestion
                    'set the tag - will be used to identify the ToolStripItem as a most recent(MRU) item 
```

2021-06-09 07:52 UTC, lloyddewit commented on instat/clsRecentFiles.vb
> +    ''' <param name="ucrDataViewWindow"></param>
Thanks for including these XML comments.
There should normally be a short description of each parameter

2021-06-10 17:12 UTC, Patowhiz commented on instat/clsRecentFiles.vb
>          If TypeOf sender Is ToolStripItem Then
@lloyddewit I will have to cast the `sender` for me to access the `Tag` function, I wanted to avoid the the "try cast" here. So I'm choosing to check the type then do a "1 time" direct cast to return the actual "type" so that I can access all the properties of the `ToolStripItem`.

2021-06-10 17:35 UTC, Patowhiz commented
@lloyddewit I have made the suggested changes above.

2021-06-11 07:23 UTC, lloyddewit commented on instat/clsRecentFiles.vb
>          If TypeOf sender Is ToolStripItem Then
@Patowhiz thanks, understood.
I don't think we need a `Trycast` here. We could safely write the statement as:
```
If TypeOf sender Is ToolStripItem AndAlso 
    DirectCast(sender, ToolStripItem).Tag.ToString() = "MRU:more" Then
```
It is safe because the `AndAlso` will guarantee that the `DirectCast` will only be called if `sender` is a `ToolStripItem`.
I'll go ahead and approve anyway, only implement the above suggestion if you wish to.

2021-06-11 07:24 UTC, lloyddewit approved these changes
Thanks, all looks good. there's just one optional suggestion. I'll go ahead and approve anyway.

2021-06-11 07:24 UTC, lloyddewit commented
@rdstern Please could you test/approve again? thanks

2021-06-11 12:40 UTC, Patowhiz commented on instat/clsRecentFiles.vb
>          If TypeOf sender Is ToolStripItem Then
@lloyddewit aha! I understand you now. Yes I could do that, but I still need the `Tag` regardless of whether its "MRU:More" option or not. To later be used as a file path if not "MRU:More" option. So I need to always do `If TypeOf sender Is ToolStripItem` check then after that store the `Tag` then exit the subroutine if the `Tag` is "MRU:More". Same applies for the LinkLabel option.

I could avoid do the above if I can somehow get the file path directly from the sender object, which in this case not possible without explicit cast. Not unless I assume it to always be an object that has a `Tag` property and let VB.NET handle implicit casting though that could open doors to logical errors in future.

2021-06-11 13:01 UTC, rdstern approved these changes
Still looks fine!

2021-06-14 10:29 UTC, lloyddewit commented on instat/clsRecentFiles.vb
>          If TypeOf sender Is ToolStripItem Then
yes, fair point, thanks for explaining

2021-06-14 10:30 UTC, merged