Updating the summary table dialogue
africanmathsinitiative/R-Instat pull request #6508
Opened 2021-06-02 15:37 UTC by Ivanluv

FIxes #6502 

@lilyclements  I am getting the following errors
![image](https://user-images.githubusercontent.com/45068931/120509365-1dc59000-c3d1-11eb-8a91-0d5fe842096c.png)

![image](https://user-images.githubusercontent.com/45068931/120509498-3b92f500-c3d1-11eb-9f1f-108c9b54a68d.png)

which seem to occur in the sample scripts

@lilyclements  could you kindly review this

2021-06-02 23:14 UTC, lilyclements commented
My apologies, I've not put the package names in. `pivot_longer` is in the `tidyr` package. I'll sort this asap.

2021-06-04 15:55 UTC, rdstern requested changes
@Ivanluv I was looking at the pull request in case it is working now.
1.  I use the usual survey data and asked for a table of mean yield for each village.
2. The first erros was not finding the variable called Summary_Variable.  That's because you used dash rather than underscore.
3. At the same time could you make the names all lower case, i.e. summary_variable, and value.  So we adhere to "good practice".  I suggest we may later want an option of saving this intermediate table.
4. Then I got stuck (in the script file) because it said it couldn't find a function called unite?

You may be past all this, but perhaps it helps?

2021-06-04 16:16 UTC, lilyclements commented
The `unite` function is called from the `tidyr` package - my apologies I must've missed that one. @Ivanluv do you mind changing `unite` to be `dplyr::unite`?

2021-06-13 19:28 UTC, lilyclements commented
The bug stating that the `unite` function cannot be found is occurring because it is from the `tidyr` package. `unite` is being called in a function in the `mmtable2` package, not in

2021-06-13 19:33 UTC, lilyclements commented
When running this function, there is a bug stating that the `unite` function cannot be found.
The `unite` function is being called in the `mmtable2` package without the `tidyr` package loaded (alongside a lot of other functions from the `tidyverse` suite) hence running the `mmtable2` code throws an error.

E.g.
```
remotes::install_github("ianmoran11/mmtable2")
library(mmtable2)
mtcars_summary <- mtcars %>% group_by(cyl) %>% summarise(mean(mpg))

mmtable2::mmtable(data = mtcars_summary, table_data = `mean(mpg)`) +
  header_left(cyl)
```
calls an error.

However, if you load the `tidyverse` library, the function works
```
library(tidyverse)

mmtable2::mmtable(data = mtcars_summary, table_data = `mean(mpg)`) +
  header_left(cyl)
```

@dannyparsons what do you think is the best way to handle this?

2021-06-21 18:34 UTC, dannyparsons commented
We can add `tidyr` to the list of packages that are explicitly loaded on start up here https://github.com/africanmathsinitiative/R-Instat/blob/master/instat/static/InstatObject/R/Rsetup.R#L200

Can you just check if it matters if it goes before or after `plyr`/`dplyr`?

2021-06-21 20:28 UTC, lilyclements commented
Thanks for this. It does not matter if it goes before or after `plyr` or `dplyr`. 
@Ivanluv would you mind creating a PR that adds in the `tidyr` package in the list that loads at the start (I am happy to do it but am away from my R-Instat laptop until tomorrow evening)

2021-06-27 08:41 UTC, rdstern requested changes
@Ivanluv this is starting to look good - at least in that I have tried various tables and don't get any errors!
But I also don't get any results.  When I check the objects I see that the tables are being produced.  Will there be results in the output window, or just in a browser for now?  Either way it would be easier to comment if there were some tables output.

If they are conveniently only in a browser, then that would be ok for now.  We are starting work on a new output window.  So you don't need to make too many special efforts on this one.  But there may anyway be different options for the display of the tables?

2021-06-28 08:05 UTC, Ivanluv commented
For now the results are just in the browser

2021-06-28 17:11 UTC, rdstern commented
@Ivanluv I wonder how much you are testing what you are producing?  I am treying with the usual simple survey.  

I now get  this in the browser:

![image](https://user-images.githubusercontent.com/11226469/123676630-15c80700-d83c-11eb-8624-2a2492950a91.png)

But only when I use Prepare > R Objects > View Object.

In the output window I got:

![image](https://user-images.githubusercontent.com/11226469/123676800-4c9e1d00-d83c-11eb-855d-e833993fbf1a.png)

2021-06-29 08:30 UTC, Ivanluv commented
> @Ivanluv I wonder how much you are testing what you are producing? I am treying with the usual simple survey.
> 
> I now get this in the browser:
> 
> ![image](https://user-images.githubusercontent.com/11226469/123676630-15c80700-d83c-11eb-8624-2a2492950a91.png)
> 
> But only when I use Prepare > R Objects > View Object.
> 
> In the output window I got:
> 
> ![image](https://user-images.githubusercontent.com/11226469/123676800-4c9e1d00-d83c-11eb-855d-e833993fbf1a.png)


@rdstern  I have fixed this

2021-06-30 09:44 UTC, rdstern commented
@Ivanluv and @lilyclements well done to you both, it now (all?) seems to work.  Now some questions - of course:
a) I got this table, with the margin in the wrong place
![image](https://user-images.githubusercontent.com/11226469/123936960-977b7a00-d98d-11eb-9f73-6975fe273858.png)
b) When I include margins I also get another data frame:  Here is an example:
![image](https://user-images.githubusercontent.com/11226469/123937170-ce519000-d98d-11eb-89b5-39aa4efec7dc.png)

c) I imagine that sometimes it could be useful to give that sort of data frame.  But it seems to be missing the weights?
d) Here is the dialogue as I used it:
![image](https://user-images.githubusercontent.com/11226469/123937565-330cea80-d98e-11eb-9880-e69e78011967.png)
Among the suggestions for more or changed items:
1) Change the default number of Column factors to 1.
2) Change the label to Treat Summaries as a Further Factor.  Then add an up-down to dictate where it fits.  It goes from 1 to 1 more than the number of ordinary factors.  Default is possibly the highest number, e.g. 3 in the example above.
3) In the number of significant figures it could be possible to allow typing (for now), so they could depend on which summary variable.  If we stick with one option, then I wonder if we change thatto decimal places?  Or allow a choice between decimal places and significant figures?

e) Then I wonder what else might be included here, i.e. in this dialogue?  So, what's next?  I am thinking when we merge then we will (currently) lose the old dialogue(s).  Do we want to do that yet?  I would like to merge as soon as possible, but suggest we may (for a period) still want to keep the old dialogues - at least for users to be able to provide results in the output window.

2021-07-05 06:00 UTC, rdstern commented
@Ivanluv and @lilyclements you have gone quiet again on my questions above.  

I have now found a bug - I suggest it might be a Lily query but I don't know.  It produces things like the mean and median ok, in fact I think everything on the first page.  So also quartiles, etc.

But on the second summary set I tried adding this:
![image](https://user-images.githubusercontent.com/11226469/124400996-7c5a9280-dd1e-11eb-9989-1043939700c5.png)

It then said as follows:

![image](https://user-images.githubusercontent.com/11226469/124401019-a3b15f80-dd1e-11eb-88ed-b5e05c125a27.png)

And the main line of code generated was as follows:


```
# Code generated by the dialog, Summary Tables

hh <- data_book$get_data_frame(data_name="hh")

summary_table <- data_book$summary_table(data_name="hh", summaries=c("summary_count_non_missing", "summary_median", "count_calc", "p10", "p25", "p75", "p90", "summary_mean"), na.rm=TRUE, factors="survey", columns_to_summarise=c("HH49","HH50","HH50A","HH51","HH52"), count_test="'>'", count_value=0, treat_columns_as_factor=TRUE, j=1)
```
The percentiles etc also don't work, but put a funny prob=0.25 - if I ask for that, into the command.


And 3 questions as well:
a) It only works if I have at least one factor?  Could it work without that?  It works fine if I add a factor with a single level, but the display is then a bit artificial.
b) I suggest changing the label on the second receiver from `Summary Columns:` to just `Variables:`.  This should also then change on the corresponding checkbox. 
c) There isn't yet any facility to be able to dictate the order of the selected summaries?  
d) Might it be possible, at least in some circumstances, to write the table back to a data frame?

2021-07-05 06:31 UTC, Ivanluv commented
@rdstern am looking at this today

2021-07-10 17:48 UTC, lilyclements commented
Thanks for the comments @rdstern 
To the points I have looked at so far:

> a) It only works if I have at least one factor? Could it work without that? It works fine if I add a factor with a single level, but the display is then a bit artificial.

I've amended the R code to do this and sent it in a PR for @Ivanluv to look at, and then merge into this.
It should then work for no factors in the R-code. The dialog code needs to be amended to have OK enabled when there are no factors

> c) There isn't yet any facility to be able to dictate the order of the selected summaries?

I will have a think into how to implement this, and discuss this with David

> d) Might it be possible, at least in some circumstances, to write the table back to a data frame?

I've started work on. Might need some help from Danny or Shadrack, but I'll see a bit more if I can work it out

Will look into the bugs you've outlined shortly.

2021-07-13 14:07 UTC, lilyclements commented
I've made some changes to the R code which, once merged into this PR, should solve the following problems:

> a) I got this table, with the margin in the wrong place

@rdstern I'm unable to replicate this error! I'm not sure why?

> b) When I include margins I also get another data frame: Here is an example:

This should be fixed now, thanks for pointing this out

> d) Might it be possible, at least in some circumstances, to write the table back to a data frame?

I have amended the R code so this should now be possible to code in the dialog.
@Ivanluv can you add in a checkbox called "Store Output". This should only be visible if there is **one column factor**. If this checkbox is checked then `store_table = TRUE`, otherwise `store_table = FALSE`. Default is that it is unchecked.

> I have now found a bug - I suggest it might be a Lily query but I don't know. It produces things like the mean and median ok, in fact I think everything on the first page. So also quartiles, etc.

I have fixed this bug now, thanks!

2021-07-14 10:20 UTC, lloyddewit commented
@Ivanluv is this ready for testing again or still ongoing? thanks

2021-07-14 11:00 UTC, Ivanluv commented
@lloyddewit its ready for testing

2021-07-15 10:29 UTC, rdstern submitted a review, later dismissed
Thanks for the help @Ivanluv I re-installed  and it is working fine now.

The only trivial point to fix, is that the storing of the data is in a different "shape" anyway to the layout of the tables.  Currently the Store is hidden when there is more than one factor.  It could be an option anytime.  (I tried from the script and it works fine with 2 factors.  Good to  take that restriction away.  I am approving anyway.

2021-07-16 13:08 UTC, lloyddewit commented
@HawardKetoyoMsatsi Please could you review? thanks

2021-07-21 11:31 UTC, rdstern approved these changes
@Ivanluv and @lilyclements this now all seems to work.  I am sure we may come back to it, but good to get this merged now.

I hope @shadrackkibet or @lloyddewit could check and merge!

2021-07-26 06:52 UTC, Ivanluv commented
@shadrackkibet  could you review this?

2021-07-29 09:20 UTC, shadrackkibet requested changes

2021-07-29 09:20 UTC, shadrackkibet commented on instat/dlgSummaryTables.vb
> +            clsMutableOperator.RemoveParameterByName("variablesLeftTop")
Do this at the start of the `sub` to avoid duplication?

2021-07-29 09:20 UTC, shadrackkibet commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +if (store_table == TRUE){
`store_table` is a boolean therefore no need to be explicit.

2021-07-29 09:20 UTC, shadrackkibet commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +      dplyr::mutate_at(vars(-value), ~forcats::as_factor(forcats::fct_relevel(., margin_name, after = Inf)))
```suggestion
shaped_cell_values <- dplyr::bind_rows(shaped_cell_values, margin_tables_all) %>%
  dplyr::mutate_at(vars(-value), ~replace(., is.na(.), margin_name)) %>%
  dplyr::mutate_at(vars(-value), ~forcats::as_factor(forcats::fct_relevel(., margin_name, after = Inf)))
```

2021-07-29 11:19 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +Imports instat
Done

2021-07-29 11:19 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +        lblDisplayNA.Enabled = False
the controls were not being used. I have removed them

2021-07-29 11:20 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +        ucrChkStoreResults.SetRDefault("False")
Thanks for these. Done

2021-07-29 11:20 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +    Private clsGetDataframe As New RFunction
Done

2021-07-29 11:21 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +        ucrNudColumnFactors.SetText(1)
It does not update any function

2021-07-29 11:21 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +        clsSummariesHeaderLeftTopFunction.AddParameter("summary", "summary", iPosition:=0, bIncludeArgumentName:=False)
Done

2021-07-29 11:22 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +        clsGetDataframe.SetAssignTo(ucrSelectorSummaryTables.ucrAvailableDataFrames.cboAvailableDataFrames.Text)
The parameter value required is a string

2021-07-29 11:24 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +                clsDefaultFunction.AddParameter("margins", Chr(34) & "summary" & Chr(34), iPosition:=8)
Great idea.Done

2021-07-29 11:24 UTC, shadrackkibet requested changes

2021-07-29 11:24 UTC, shadrackkibet commented on instat/dlgSummaryTables.vb
> +    Private Sub AddMutableFunctions()
Inline this sub because it is only needed in one place.

2021-07-29 11:25 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +            clsMutableOperator.RemoveParameterByName("variablesLeftTop")
This is the best implementation .Done

2021-07-29 11:26 UTC, Ivanluv commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +if (store_table == TRUE){
what is you suggestion?

2021-07-29 11:27 UTC, shadrackkibet commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +if (store_table == TRUE){
```suggestion
if (store_table){
```

2021-07-29 11:37 UTC, shadrackkibet commented on instat/dlgSummaryTables.vb
> +        clsGetDataframe.SetAssignTo(ucrSelectorSummaryTables.ucrAvailableDataFrames.cboAvailableDataFrames.Text)
What about when the data frame changes? Isn't this going to cause a bug because it is never updated?

2021-07-29 12:30 UTC, shadrackkibet commented
@Ivanluv could you test this much more? I did load some data and got a bug immediately! 

![image](https://user-images.githubusercontent.com/26301973/127491033-b989d6de-180a-42df-a1e2-da3a4ff17826.png)

2021-07-29 12:45 UTC, shadrackkibet commented on instat/dlgSummaryTables.vb
> +        clsGetDataframe.SetAssignTo(ucrSelectorSummaryTables.ucrAvailableDataFrames.cboAvailableDataFrames.Text)
I think you don't need `clsGetDataframeName`. I can't find where it is used in your code.

2021-07-29 12:52 UTC, Ivanluv commented
ee

> @Ivanluv could you test this much more? I did load some data and got a bug immediately!
> 
> ![image](https://user-images.githubusercontent.com/26301973/127491033-b989d6de-180a-42df-a1e2-da3a4ff17826.png)

reinstall the mmtable2 package to fix this

2021-07-29 12:55 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +        clsGetDataframe.SetAssignTo(ucrSelectorSummaryTables.ucrAvailableDataFrames.cboAvailableDataFrames.Text)
if you use the `summary ` and `both ` `margins `without  `clsGetDataframeName `it bugs

2021-07-29 15:09 UTC, shadrackkibet commented on instat/dlgSummaryTables.vb
> +        clsGetDataframe.SetAssignTo(ucrSelectorSummaryTables.ucrAvailableDataFrames.cboAvailableDataFrames.Text)
I identified the source of the bug in the Rcode. I will pull your branch and fix it.

2021-07-29 15:36 UTC, shadrackkibet requested changes

2021-07-29 15:36 UTC, shadrackkibet commented on instat/dlgSummaryTables.vb
> +        Dim iNumberOfColumns As Integer = ucrNudColumnFactors.GetText()
This will raise an exception when the Nud is empty. You need a check for safety!

2021-07-29 15:36 UTC, shadrackkibet commented on instat/dlgSummaryTables.vb
> +                    clsHeaderLeftFunction.SetRCommand("header_top_left")
Much more cleaner to have declarations at the beginning of the `sub`

2021-07-30 07:32 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +        Dim iNumberOfColumns As Integer = ucrNudColumnFactors.GetText()
I have added the check within the sub and in the `TeskOkEnabled`

2021-07-30 07:33 UTC, Ivanluv commented on instat/dlgSummaryTables.vb
> +                    clsHeaderLeftFunction.SetRCommand("header_top_left")
I agree. Done

2021-07-30 09:42 UTC, shadrackkibet commented
@rdstern could you please re-test and re-approve?

2021-07-30 09:44 UTC, rdstern commented
@shadrackkibet thanks.  Will do straight away!

2021-07-30 10:24 UTC, rdstern approved these changes
Great

2021-07-30 10:53 UTC, shadrackkibet approved these changes

2021-07-30 10:53 UTC, merged