Small bug fixes in Bar And Pie chart Dialog
africanmathsinitiative/R-Instat pull request #6517
Opened 2021-06-08 19:50 UTC by N-thony

Partially fixes #6135
This PR fixes the bug in the two comboxes to remember the states in reopen, and the presentation of the labels.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-06-09 05:49 UTC, rdstern requested changes
@N-thony that's already much better.  The oddity now is that we have the Position control when the option is set to count, but not otherwise.
I suggest the right-hand-side is going to be a bit more complicated anyway, with the multiple options for x or y.  So could you move the Position control to the left hand side.  It can be above the Flip button and a single line, so the control is just after the label.
This will make the dialogue a bit longer, which is ok.  There will be more options to come.

2021-06-09 06:51 UTC, N-thony commented
> @N-thony that's already much better. The oddity now is that we have the Position control when the option is set to count, but not otherwise.
> I suggest the right-hand-side is going to be a bit more complicated anyway, with the multiple options for x or y. So could you move the Position control to the left hand side. It can be above the Flip button and a single line, so the control is just after the label.
> This will make the dialogue a bit longer, which is ok. There will be more options to come.

@rdstern I'm not sure about it but after looking at the code, it seems to be a reason that I ignore for instance the Position control is visible when the option is set to count otherwise it is Y variable Receiver control which is at the same location with Position control. I wonder if it is good to move those two controls above Flip button. Can we have a quick chat?

2021-06-09 19:59 UTC, N-thony commented
@rdstern  I made the improvement regarding your suggestions in #6135 from item a) to d). Could you test? Thanks.

2021-06-10 05:26 UTC, rdstern requested changes
@N-thony that is a reasonable start, but there is a long way to go.
1) In the second option  there needs to be the x-variable label and control.  You have lost that.
2) Then there is a lot to do on the R code that is generated.  Currently the only difference in the R-code is whether the orientation is vertical or horizontal.  The R-code for the value option does not have the "identiry" option any more.  You need to examine the different options in the current Version 7.2 dialogue as a start.

2021-06-10 11:05 UTC, N-thony commented
@rdstern I have improved the code and design regarding your comments above. Could you test the change? Thanks.

2021-06-10 11:07 UTC, N-thony commented
@rdstern I have improved the code and design regarding your comments above. Could you test the change? Thanks.

2021-06-10 12:15 UTC, rdstern approved these changes
@N-thony excellent, this all seems to be working!

2021-06-10 12:16 UTC, rdstern submitted a review, later dismissed
@N-thony this all seems to be working.  Well done!  
@lloyddewit there is more to be done, but I suggest it would be good to merge this first.

2021-06-11 07:10 UTC, lloyddewit commented
@Ivanluv Please could you peer review? thanks

2021-06-12 06:49 UTC, rdstern commented
@N-thony there seem to be some problems of clearing part of the R-code.  I show the sequence that led to an error:
I ran a bar graph with my usual survey data.  Here is the command generated - this runs fine:

```
# Code generated by the dialog, Bar and Pie Chart
Sheet.1 <- data_book$get_data_frame(data_name="Sheet.1")
last_graph <- ggplot2::ggplot(data=Sheet.1, mapping=ggplot2::aes(x=village, fill=variety)) + ggplot2::geom_bar(position="dodge", stat="count") + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="Sheet.1")
data_book$get_graphs(data_name="Sheet.1", graph_name="last_graph")
```
This ran fine:
Then I loaded a dataset from the standard R library: datasets.  The data file is called BOD



Here is the completed dialogue - it is very simple:
![image](https://user-images.githubusercontent.com/11226469/121767709-eb92fb80-cb51-11eb-8b09-c494e0bf79c5.png)

```
# Code generated by the dialog, Open Dataset from Library
utils::data(package="datasets", X=BOD)

data_book$import_data(data_tables=list(BOD=BOD))

# Code generated by the dialog, Bar and Pie Chart
BOD <- data_book$get_data_frame(data_name="BOD")
last_graph <- ggplot2::ggplot(data=BOD, mapping=ggplot2::aes(x=Time, y=demand)) + ggplot2::geom_bar(position="dodge", stat="identity") + ggplot2::geom_text(mapping=ggplot2::aes(fill=variety), stat="count") + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text())
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="BOD")
data_book$get_graphs(data_name="BOD", graph_name="last_graph")

```

Here is the error:
![image](https://user-images.githubusercontent.com/11226469/121767720-06fe0680-cb52-11eb-9351-e05c007b4d14.png)

You see, in the error and also in the code above, that lots of the code remains from the previous graph.

If I first press Reset, then it delivers - instead - the following code:

```
# Code generated by the dialog, Bar and Pie Chart
BOD <- data_book$get_data_frame(data_name="BOD")
last_graph <- ggplot2::ggplot(data=BOD, mapping=ggplot2::aes(x=Time, y=demand)) + ggplot2::geom_bar(position="dodge", stat="identity") + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="BOD")
data_book$get_graphs(data_name="BOD", graph_name="last_graph")

```
This runs fine and gives the graph I want.

2021-06-14 08:34 UTC, Ivanluv commented on instat/dlgBarAndPieChart.vb
> +        Next
when  go to the `Bar Chart options ` button  and` Return `when I am within the `Value` radio button, I get the error below    
![image](https://user-images.githubusercontent.com/45068931/121863305-66037d00-cd04-11eb-961c-d33ad1487647.png)

2021-06-14 09:21 UTC, N-thony commented
@Ivanluv thanks for your comment above, I fix it is fixed now. Please have a look. Thanks.

2021-06-21 06:18 UTC, Ivanluv commented
@lloyddewit  this is good from my end

2021-06-21 15:14 UTC, rdstern approved these changes
@lloyddewit I think @Ivanluv is also ok with this.

2021-06-23 07:40 UTC, shadrackkibet commented
@N-thony could you improve the PR header? **Small bug fixes in Bar And Pie chart Dialog** is too general. Remember this header will be used to automatically generate release notes. Could you include the details of the bug fixed?

2021-06-24 10:02 UTC, lloyddewit approved these changes

2021-06-24 10:06 UTC, merged

2021-06-29 06:40 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.resx
> +  </data>
@N-thony @rdstern could you explain why the "pie-chart" option was disabled in this dialog? I am afraid these changes might have caused regression!