Export file dialog bug fix
africanmathsinitiative/R-Instat pull request #6539
Opened 2021-06-17 11:45 UTC by Patowhiz

Fixes #6530.

2021-06-17 11:50 UTC, Patowhiz commented on instat/dlgExportDataset.vb
> +        'autoTranslate(Me)
@lloyddewit I wasn't aware that this line was added ( `autoTranslate(Me)` ). I think because of the translations that you have been working on?
When the subroutine is executed `cboFileType.SelectedIndexChanged` is raised. I think the subroutine also tries to translate the contents of the `combobox` in a way that raises the event.

I have temporarily commented the line to wait for you feedback. It's the one causing the bug explained in the issue by @rdstern .

2021-06-18 09:39 UTC, lloyddewit commented on instat/dlgExportDataset.vb
> +        'autoTranslate(Me)
@Patowhiz `autoTranslate(me)` is called because the sub changes the label text and this text needs to be translated. `autoTranslate(me)` will update control text, which may trigger events. This is expected behaviour. 

Normally we should fix the code so that it can handle the triggered events. However in this case, there may be a simpler solution. The sub only seems to change the `lblConfirm` text. So we could potentially just translate the updated text and then delete the `autoTranslate(Me)` line. See example below. This would need testing.

If/when you test, please note that line 126 will not currently be translated because it contains a new line. The translation library doesn't currently translate multi-line text. Line 116 should translate correctly to French.

Hope this helps

![image](https://user-images.githubusercontent.com/57253949/122539663-213f5500-d028-11eb-8ede-e2e1dada9089.png)

2021-06-21 06:45 UTC, Patowhiz commented on instat/dlgExportDataset.vb
> +        'autoTranslate(Me)
@lloyddewit thanks.

in regards to the multi-line text( line 126), can I do something like;

2021-06-21 06:46 UTC, Patowhiz commented on instat/dlgExportDataset.vb
> +        'autoTranslate(Me)
@lloyddewit thanks.

in regards to the multi-line text( line 126), can I do something like;

`GetTranslation("Files with the same names will be overwritten.") & Environment.NewLine & GetTranslation("Click Ok to Confirm the Export.")`

Would the above alternative translate?

2021-06-21 06:53 UTC, Patowhiz commented on instat/dlgExportDataset.vb
> +        'autoTranslate(Me)
Looking at the translate api, it appears that it depends on whether the "Files with the same names will be overwritten." exists in the data source.

So briefly; the translation works by getting an entire sequence of characters(could be a word or an entire sentence) and tries to match it with an equivalent 'whole' sequence of characters in the data source from which it uses to get the translation 'equivalent'.

2021-06-21 06:59 UTC, Patowhiz commented
@rdstern this is ready for your testing. Please also test whether the translation works.

2021-06-22 14:21 UTC, lloyddewit commented on instat/dlgExportDataset.vb
> +        'autoTranslate(Me)
@Patowhiz 
Yes, you are exactly correct. Your proposed solution should translate correctly (assuming we also add the substrings and their French/Portguese translations to the translation database).
However, R-Instat has many multiline strings that need to be translated. Therefore I need to find a general solution for this and apply it consistently across R-Instat. Therefore, I suggest that, for now, you just set line 126 as it's done in the screenshot.

2021-06-22 14:23 UTC, lloyddewit requested changes

2021-06-22 14:23 UTC, lloyddewit commented on instat/dlgExportDataset.vb
> +            lblConfirm.Text = GetTranslation("Files with the same names will be overwritten.") & Environment.NewLine & GetTranslation("Click Ok to Confirm the Export.")
```suggestion
            lblConfirm.Text = GetTranslation("Files with the same names will be overwritten." & Environment.NewLine & "Click Ok to Confirm the Export.")
```

2021-06-22 14:25 UTC, Patowhiz commented on instat/dlgExportDataset.vb
> +        'autoTranslate(Me)
@lloyddewit done.

2021-06-24 15:21 UTC, lloyddewit approved these changes

2021-06-24 15:22 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2021-06-30 10:14 UTC, Patowhiz commented
@rdstern this waiting for your review.

2021-07-06 08:09 UTC, rdstern approved these changes
Looks fine now - relief!

2021-07-06 08:51 UTC, merged