Included trace when counting number of days entered in data entry
africanmathsinitiative/R-Instat pull request #6545
Opened 2021-06-21 15:07 UTC by Patowhiz

Fixes #6515.
@rdstern this is ready for review.

2021-06-21 15:24 UTC, rdstern approved these changes
Good change for trace values

2021-06-24 14:52 UTC, lloyddewit requested changes

2021-06-24 14:52 UTC, lloyddewit commented on instat/sdgClimaticDataEntry.vb
> +                strValue = 0
We are setting a string to an integer here. Is that correct?

2021-06-24 14:59 UTC, rdstern commented
I just report that the situation is when - in data entry - a trace rainfall is typed as t (or T), because that's what people would find convenient.  There are then various points at which we need to do something about it.  Trace, is a very small quantity (smaller than 0.1mm), but recognised as rain.  In the data entry we consider it like a value of zero, but a day that was entered - so it contributes to the count of days.  Later (when we write back to R-Instat, we transform it to 0.03mm.

2021-06-24 15:45 UTC, Patowhiz commented on instat/sdgClimaticDataEntry.vb
> +                strValue = 0
Aha yes. It should be "0", I missed this because .NET just implicitly casts it to "0".

2021-06-24 15:47 UTC, Patowhiz commented
@rdstern thanks for clarifying. I have made inline code comments for future developers to understand this.

2021-06-24 16:13 UTC, Patowhiz commented on instat/sdgClimaticDataEntry.vb
> +                strValue = 0
Corrected.

2021-06-27 08:08 UTC, lloyddewit approved these changes

2021-06-27 08:09 UTC, lloyddewit commented
@rdstern if you're happy to approve then we can merge, thanks

2021-06-27 09:20 UTC, rdstern approved these changes

2021-06-27 10:37 UTC, merged