Added back to back checkbox to the bar chart dialog
africanmathsinitiative/R-Instat pull request #6561
Opened 2021-06-28 17:50 UTC by N-thony

Fixes #6525
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-06-29 07:07 UTC, shadrackkibet requested changes
Please resolve the conflicts in this PR so that others can review this PR.

2021-06-29 07:07 UTC, shadrackkibet commented on instat/static/InstatObject/R/Rsetup.R
> +           "keyring", "klaR", "knitr", "labeling", "lemon",
This should not be edited manually. See the comment at the beginning of this file.

2021-06-29 07:12 UTC, shadrackkibet commented on instat/static/InstatObject/R/Rsetup.R
> +           "keyring", "klaR", "knitr", "labeling", "lemon",
If you would like this to be added as a new package then add/open an issue for it. Also, make sure you link to this PR.

2021-07-01 08:26 UTC, N-thony commented on instat/static/InstatObject/R/Rsetup.R
> +           "keyring", "klaR", "knitr", "labeling", "lemon",
@shadrackkibet I think this is resolved. Please, have a look. Thanks.

2021-07-01 10:08 UTC, rdstern requested changes
@N-thony I hoped to check, but there were build errors

2021-07-01 10:39 UTC, closed without merging