Copy from data view grid
africanmathsinitiative/R-Instat pull request #6567
Opened 2021-06-29 15:46 UTC by Patowhiz

Fixes#6071

@africanmathsinitiative/developers this is ready for review.

2021-07-01 10:09 UTC, lloyddewit commented
@rdstern Please could you thanks?
@HawardKetoyoMsatsi  Please could you peer review?
Thanks!

2021-07-04 14:04 UTC, Patowhiz commented
Subroutine `CopyRange()` is the only one changed in the 3 grids; `ucrDataview`, `ucrColumnMetadata`, `ucrDataFrameMetadata`.

2021-07-05 04:31 UTC, HawardKetoyoMsatsi commented
@lloyddewit  I am happy to review this

2021-07-05 07:00 UTC, rdstern approved these changes
@lloyddewit over to you.  This now copies, without copying the variable names.  I suggest that's right.  We then have Copy Special when we do want to copy the names.

2021-07-05 10:02 UTC, HawardKetoyoMsatsi commented
@lloyddewit could someone else help review this PR please it may take me longer than required.

2021-07-07 10:04 UTC, Patowhiz commented
@lloyddewit this PR is now blocking issue #6579. Thanks.

2021-07-08 11:12 UTC, lloyddewit requested changes
@Patowhiz Thanks, this looks good, I just have some small suggestions.

2021-07-08 11:12 UTC, lloyddewit commented on instat/ucrDataView.vb
> +                End If
```suggestion
                strAllContent &= strRowContent & If(iRowIndex < iEndRow, vbCrLf, "")
```

2021-07-08 11:12 UTC, lloyddewit commented on instat/ucrDataView.vb
> +                        strRowContent = strRowContent & vbTab & strCellContent
```suggestion
                        strRowContent &= vbTab & strCellContent
```

2021-07-08 11:12 UTC, lloyddewit commented on instat/ucrColumnMetadata.vb
> +    Public Sub CopyRange()
This sub looks nearly identical to the sub in `ucrDataView`.
Could we have a shared sub?
If we have to duplicate this `sub` here, then please look at my comments on this sub in `ucrDataView`.

2021-07-08 11:12 UTC, lloyddewit commented on instat/ucrDataFrameMetadata.vb
> +    Public Sub CopyRange()
This sub looks nearly identical to the sub in `ucrDataView`.
Could we have a shared sub?
If we have to duplicate this `sub` here, then please look at my comments on this sub in `ucrDataView`.

2021-07-08 11:12 UTC, lloyddewit commented on instat/ucrDataFrameMetadata.vb
> +Public Class ucrDataFrameMetadata
@shadrackkibet (or anyone else who reviews) GitHub shows many changes for this file but according to the diff in  VisualStudio only the `CopyRange` sub changed. I just mentioned this in case it saves you some time.

2021-07-08 11:12 UTC, lloyddewit commented on instat/ucrColumnMetadata.vb
>  Public Class ucrColumnMetadata
@shadrackkibet (or anyone else who reviews) GitHub shows many changes for this file but according to the diff in  VisualStudio only the `CopyRange` sub changed. I just mentioned this in case it saves you some time.

2021-07-08 11:13 UTC, lloyddewit commented
> 
> 
> @lloyddewit could someone else help review this PR please it may take me longer than required.

No problem, I can review. @shadrackkibet may also review if he wishes (but not mandatory).

2021-07-13 10:38 UTC, Patowhiz commented on instat/ucrColumnMetadata.vb
> +    Public Sub CopyRange()
@lloyddewit we could. But I couldn't find an ideal class to place it in. Any suggestion? 
I would have preferred placing it in a parent class "grid", but we don't have any currently, and creating one would need discussions.

2021-07-13 11:03 UTC, Patowhiz commented
@lloyddewit I have done the above suggested changes. Ready for you.

2021-07-13 11:03 UTC, Patowhiz commented on instat/ucrDataView.vb
> +                        strRowContent = strRowContent & vbTab & strCellContent
Done.

2021-07-13 11:08 UTC, Patowhiz commented on instat/ucrDataView.vb
> +                    strCellContent = grdData.CurrentWorksheet.GetCell(row:=iRowIndex, col:=iColIndex).DisplayText
Done.

2021-07-14 09:33 UTC, lloyddewit commented on instat/ucrColumnMetadata.vb
> +    Public Sub CopyRange()
@Patowhiz Thanks for the updates, this is the final open comment.
Currently, this PR adds 3 near-identical 'CopyRange' subs to 3 separate classes. For me, this is too much duplicated code so I think we need to find a solution. I agree that any parent 'clsGrid' would require discussion and it feels like an over-complex and unnatural solution.
Could we avoid inheritance and add a simpler 'clsReoGridUtilities' class? The class could contain a single sub something like:
```
    Public Shared Sub CopyRange(clsReoGrid As unvell.ReoGrid.ReoGridControl, strComment As String)
```
The sub would be 'shared' so that no object needs to be instantiated. The 3 CopyRange subs could then call this shared Sub.
What do you think?

2021-07-15 08:17 UTC, Patowhiz commented
@lloyddewit yes I agree, and that was my initial thought as well. 
@ChrisMarsh82 is working on a class for for filling grids.

@lloyddewit with this new information, should I still go ahead and create the new class that later may also become redundant or just leave the code as it is and have it pushed to @ChrisMarsh82 classes.

2021-07-15 11:12 UTC, lloyddewit commented
> 
> 
> @lloyddewit yes I agree, and that was my initial thought as well.
> @ChrisMarsh82 is working on a class for for filling grids.
> 
> @lloyddewit with this new information, should I still go ahead and create the new class that later may also become redundant or just leave the code as it is and have it pushed to @ChrisMarsh82 classes later?

@Patowhiz good point, thanks. I'll approve this PR. I suggest that we try and resolve the duplication in @ChrisMarsh82 's PR.

@ChrisMarsh82 Please see the open comments above about the duplication in the 'CopyRange' functions.
In PR #6585, you change some of the same classes as this PR. I think this could lead to merge conflicts and we may need to make changes to your code anyway. In parallel, we can look at potential duplication in the 'CopyRange' functions.

2021-07-15 11:12 UTC, lloyddewit approved these changes

2021-07-15 11:13 UTC, lloyddewit commented
@rdstern Please could you test again? thanks

2021-07-20 07:35 UTC, Patowhiz commented
@rdstern once this is re-tested and merged, we can proceed with copy special feature.

2021-07-20 07:51 UTC, rdstern approved these changes
Great.  Looking forward now to Copy Special!

2021-07-20 07:52 UTC, Patowhiz commented
@lloyddewit this is now ready for your approval and merging.

2021-07-20 08:38 UTC, merged

2021-08-02 14:18 UTC, shadrackkibet commented
I am afraid these changes might have introduced a bug. @lloyddewit do you have any suggestions on who should sort this out? It is partly because we didn't review this PR rigorously!

![image](https://user-images.githubusercontent.com/26301973/127875487-977cd788-2bc6-4d7d-9b7c-1626a95383e4.png)

2021-08-04 06:14 UTC, Patowhiz commented
@shadrackkibet, I've been away for a while, thanks for noticing this. Yes I can see that in your command the data name has not been added by the dialog. I will fix the bug.
Please also note, currently that all copy paste functionalities have been assigned to me.

2021-08-16 08:58 UTC, shadrackkibet commented
@Patowhiz I fixed the bug reported.

2021-09-08 04:40 UTC, Patowhiz commented
Thanks.