Added Lan button on toolbar to facilitate the view of English in translated menu
africanmathsinitiative/R-Instat pull request #6572
Opened 2021-07-01 10:13 UTC by N-thony

Fixes #6570
@rdstern for space issue I suggest adding the Lan button on the toolbar in this PR.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-07-01 10:22 UTC, lloyddewit commented
@HawardKetoyoMsatsi please could you review? thanks

2021-07-02 21:49 UTC, rdstern reviewed
Great - this seems to work.
1) It stays in English until the Lan button is pressed again.  That's unlike a dialogue that switches automatically back into French when re-opened, etc.  I was thinking that when a dialogue is used, then it would swich back automatically?  Now I am not sure what I prefer.  Perhaps @lloyddewit or @N-thony or @rachelkg might have views?
2) I'd like to improve on the Lan box if we can.  We were thinking of perhaps a nice looking L.  Perhaps @rachelkg might find something?

2021-07-05 08:34 UTC, lloyddewit commented
> It stays in English until the Lan button is pressed again. That's unlike a dialogue that switches automatically back into French when re-opened, etc. I was thinking that when a dialogue is used, then it would swich back automatically? Now I am not sure what I prefer. Perhaps @lloyddewit or @N-thony or @rachelkg might have views?

For me, it feels logical that the button just toggles the language on the menu bar. I think switching automatically to a different language when a dialog is opened could be confusing.

> I'd like to improve on the Lan box if we can. We were thinking of perhaps a nice looking L. Perhaps @rachelkg might find something?

For a translation symbol, I quite liked the one below (from [here](https://www.123rf.com/photo_108932826_stock-vector-global-dialog-line-icon-speech-bubbles-with-globe-inside-translation-concept-can-be-used-for-topics-.html)). Or just 'L' or 'Lan' with nice looking letters could also be fine. I'm happy if @rachelkg is willing to implement something.

![image](https://user-images.githubusercontent.com/57253949/124440586-0e908400-dd7b-11eb-862d-ec05f262817e.png)

2021-07-05 09:53 UTC, rdstern commented
I'd be very happy with the world symbol - seems fine.  Is it easy for a tooltip to change slightly.  It could say "Switch menus back to English"  when in (say) French.  If in English Switch language for menus back from English.  

Then let's get it merged.  It is a good improvement.

2021-07-05 11:42 UTC, HawardKetoyoMsatsi commented
The code looks fine however a small issues I found.
The menu items start fine.
![image](https://user-images.githubusercontent.com/16137042/124464718-35f84880-dd9d-11eb-94a8-6e4b0b5001f5.png)

But after you toggle between language changing on the column metadata the first option doesn't switch back to English although all others do. See below **Metadonee de colone** has not changed back to English while **Dataframe metadata** changed back to english
![image](https://user-images.githubusercontent.com/16137042/124465302-eebe8780-dd9d-11eb-9592-95e03f72087e.png)

![image](https://user-images.githubusercontent.com/16137042/124465792-7d330900-dd9e-11eb-8329-e503460e3982.png)

@N-thony If this is not bart of the issue you are fixing it can be opened in a new issue.

2021-07-05 13:30 UTC, HawardKetoyoMsatsi requested changes
@lloyddewit Besides the issue I mentioned about the dropdown **column metadata** icon failing to forget the first language it was translated to I find the code okay.

2021-07-06 10:36 UTC, lloyddewit commented
> 
> 
> @lloyddewit Besides the issue I mentioned about the dropdown **column metadata** icon failing to forget the first language it was translated to I find the code okay.

@HawardKetoyoMsatsi Thanks, this is a great observation. This is not a bug in @N-thony 's code but a currently missing part of the translation mechanism. I don't think it's urgent so I suggest we go ahead and merge this PR and fix the inconsistency separately. I added your observation to issue #3721 .

2021-07-06 10:50 UTC, lloyddewit requested changes
Looks good, just a couple of small suggestions

2021-07-06 10:50 UTC, lloyddewit commented on instat/frmMain.vb
> +
Can we delete this?
```suggestion
```

2021-07-06 10:50 UTC, lloyddewit commented on instat/frmMain.vb
> +    Public Sub EnableVisible(bVisble As Boolean)
```suggestion
    Public Sub EnableVisible(bVisible As Boolean)
```

2021-07-06 11:02 UTC, N-thony commented
@lloyddewit I think your comments above are resolved. Please have a look. Thanks.

2021-07-06 17:54 UTC, rachelkg commented
I am a bit late chiming in but I think the world symbol is good too. It seems more universally understandable than L as L is tied to the word language. 

I agree with @lloyddewit on this :"For me, it feels logical that the button just toggles the language on the menu bar. I think switching automatically to a different language when a dialog is opened could be confusing." I think one will be working in the language that one wants to be in, and will just toggle into a different language to check something.

2021-07-07 10:01 UTC, lloyddewit submitted a review, later dismissed

2021-07-07 10:12 UTC, lloyddewit commented
@rdstern There are some small changes since you last approved. These should not have affected the functionality. Please could you approve again so that we can merge?
@rachelkg Thank you for the comments and suggestions about the button appearance. I referenced these in issue #6588 and assigned this issue to you, I hope that's OK.
Thanks!

2021-07-08 06:51 UTC, shadrackkibet commented on instat/frmMain.vb
>      Private Sub SetMainMenusEnabled(bEnabled As Boolean)
- Space needed and the end of the sub? 

- Then a question about subroutine naming. This is just setting the visibility for the button. Since **Enabled** is another property and that isn't changed here! is it better to name this sub `SetLanButtonVisibility`?

2021-07-08 07:14 UTC, N-thony commented
@shadrackkibet thanks, I think your comments above are resolved.

2021-07-08 07:50 UTC, lloyddewit approved these changes
@N-thony great, thanks for thinking about understandable names

2021-07-08 09:03 UTC, shadrackkibet approved these changes
@rdstern I have approved it subject to your approval to confirm that it works correctly then we can then merge.

2021-07-08 09:34 UTC, rdstern approved these changes
@shadrackkibet I am happy to approve.  I was hoping it would be pretty simple to add the world symbol with the tooltips before merging.  But don't have a problem merging first - it is a very useful addition.

2021-07-08 09:51 UTC, shadrackkibet commented
Let's work on that separately which @lloyddewit has referenced as an issue above.

2021-07-08 09:51 UTC, merged