Added back to back checkbo to the bar and pie chart dialogue
africanmathsinitiative/R-Instat pull request #6573
Opened 2021-07-01 10:43 UTC by N-thony

Fixes #6525
@rdstern you had an issue on testing PR #6561, to solve the problem I just simply close it and open this one.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-07-03 09:53 UTC, rdstern requested changes
@N-thony it works!  And it also works when I stack the data, which is great.
The only problem I found was that you are able to choose the back-to-back option even when you have a simple boxplot with no additional factor.  I suggest it is disabled unless either the main control is multiple with more than one variable, or the additional factor is chosen.
Then I would like to merge, so you can add the polar part.  Or maybe you would like to add polar into this pull request?

2021-07-03 21:12 UTC, N-thony commented
@rdstern I think your comment above is resolved. I will add the polar once this is merged. Thanks.

2021-07-05 06:27 UTC, rdstern commented
@N-thony please sort out the enabling/disabling better for the back-to-back.
I tried for a simple back-to-back and it wasn't enabled.

Then I repeated one I did before, with multiple counts and it was enabled - good.  Then I stacked the data to do the same graph and it now was disabled.  But it still did it!

![image](https://user-images.githubusercontent.com/11226469/124426572-214a8f00-dd62-11eb-8eb9-8b5b5df20c05.png)

I think it is simple, isn't it?  You can have a back-to-back when you have the second factor variable filled.

2021-07-05 07:07 UTC, N-thony commented
> @N-thony please sort out the enabling/disabling better for the back-to-back.
> I tried for a simple back-to-back and it wasn't enabled.
> 
> Then I repeated one I did before, with multiple counts and it was enabled - good. Then I stacked the data to do the same graph and it now was disabled. But it still did it!
> 
> ![image](https://user-images.githubusercontent.com/11226469/124426572-214a8f00-dd62-11eb-8eb9-8b5b5df20c05.png)
> 
> I think it is simple, isn't it? You can have a back-to-back when you have the second factor variable filled.

@rdstern I have corrected the condition on back to back checkbox. Please have a look. Thanks.

2021-07-05 09:01 UTC, lloyddewit commented
@shadrackkibet you kindly reviewed PR #6561. This PR replaces that one. Please could you review this PR also? thanks

2021-07-06 08:28 UTC, rdstern submitted a review, later dismissed
@lloyddewit this is ok from my point of view.  It could (for me) eithjer be merged now, or wait until @N-thony has added pie charts.
If you could check?  If there are tasks now then I suggest he also adds pie charts.  But if ok, then let's merge.

2021-07-06 08:57 UTC, shadrackkibet commented
I suggest we add pie charts since it was there originally, then I will peer-review them all together.

2021-07-06 09:02 UTC, rdstern commented
OK @shadrackkibet .  @N-thony ready for you to go!  I just note that we will be more general than pie charts.  It also includes donut charts and pie charts with a second (possibly more) circle.  The code was written by @lilyclements and is all via polar coordinates.

2021-07-07 11:59 UTC, N-thony commented
@rdstern as we discussed in the chat. I have added pie and donut under the polar checkbox. Could you have a look? Thanks.

2021-07-07 21:08 UTC, rdstern commented
@N-thony and @lilyclements I have tried the code from Lily that Antoine has implemented.  I have also been looking at examples and this seemed the clearest for [pir and donut charts ](https://semba-blog.netlify.app/07/12/2019/pie-chart-and-donut-plot-with-ggplot2/).  

It all looks sufficiently different to the range of bar charts that I wonder if we are correct in trying to do them simply via polar?  Perhaps we should have special button (or buttons) at the top instead.  If so, then I hope there might just be one for Pie/Donut.  Some examples above are for multiple donut, but perhaps ignore that for now.  WE don't encourage pie-type charts too much, so I also don't want to spend too long on this topic.  But we do need something.

2021-07-14 08:43 UTC, shadrackkibet commented
What are the next steps after @rdstern comments above? Any changes/implementation required? Should something be disabled then we can review the code and merge?

2021-07-15 06:12 UTC, N-thony commented
> What are the next steps after @rdstern comments above? Any changes/implementation required? Should something be disabled then we can review the code and merge?

Make changes in pie and donut under the polar checkbox that I have implemented once what we need is clear in #6526.

2021-07-18 12:58 UTC, N-thony commented
@rdstern I have made a change on the implementation of the polar coordinate under the Polar checkbox, and added for radion buttons, x and y also Donut and Pie charts as discussed on Friday. Please have a look. Thanks.

2021-07-18 13:28 UTC, rdstern commented
@N-thony it is looking promising.  Can you check your code for the donut please.  I once got it like this - but only once!
```
# Code generated by the dialog, Bar and Pie Chart
survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(survey, ggplot2::aes(x=2, fill=village)) + ggplot2::geom_bar(stat="count") + ggplot2::coord_polar("y") + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
```

It has correctly added x=2 here.  Usually it gives x="".  And it has omitted to add + xlim(0.2,2.5) so you don't get a donut!

But we can now get a pie chart - so that's good!

2021-07-18 17:08 UTC, N-thony commented
> @N-thony it is looking promising. Can you check your code for the donut please. I once got it like this - but only once!
> 
> ```
> # Code generated by the dialog, Bar and Pie Chart
> survey <- data_book$get_data_frame(data_name="survey")
> last_graph <- ggplot2::ggplot(survey, ggplot2::aes(x=2, fill=village)) + ggplot2::geom_bar(stat="count") + ggplot2::coord_polar("y") + theme_grey()
> data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
> data_book$get_graphs(data_name="survey", graph_name="last_graph")
> ```
> 
> It has correctly added x=2 here. Usually it gives x="". And it has omitted to add + xlim(0.2,2.5) so you don't get a donut!
> 
> But we can now get a pie chart - so that's good!
> 
> I then tried with the summary data as here:
> 
> ![image](https://user-images.githubusercontent.com/11226469/126069037-5028cf09-1432-46b8-8026-a786045a7d0d.png)
> 
> I tried for the donut chart again - and got the pie for the same reason as mentioned above. Then I returned to the dialogue and pressed Ok again - that's a test you should be doing. Now I get an error. The code is now different - and says `x =,` so that's why I got the error!
> 
> ```
> # Code generated by the dialog, Bar and Pie Chart
> survey_by_village <- data_book$get_data_frame(data_name="survey_by_village")
> last_graph <- ggplot2::ggplot(survey_by_village, mapping=ggplot2::aes(x=, y=mean_yield, fill=village)) + ggplot2::geom_bar(stat="identity") + ggplot2::coord_polar("y") + theme_grey()
> data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey_by_village")
> data_book$get_graphs(data_name="survey_by_village", graph_name="last_graph")
> ```

@rdstern sorry for that, I made some corrections vis a vis to your comments above. I may have missed some other things when checking, hopefully, now it is ready for you to check. Thanks

2021-07-19 05:57 UTC, rdstern commented
@lilyclements great.  In your comments in #6523 I think you have nailed the bar charts/pie charts.  It was your racetrack example that I think is really important, because that is an example of (what I'll call a pie chart, with many segments.  That's important, because it allows us to have circular plots wherever we have bar charts on the dialogue.  I think we can have to donut type, so we may be home and dry!  Here is my adaptation of your code, adding an `expansion` to the command.
@lilyclements I think your discovery of position = "fill" is important in the code below!  That means it always goes round the full circle!

```
# Code generated by the dialog, Bar and Pie Chart
survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(survey, mapping=ggplot2::aes(x=variety, fill=village)) + ggplot2::geom_bar(stat="count",position="fill",width=0.9) + ggplot2::coord_polar("y") + theme_grey()+scale_x_discrete(expand = expansion(add = c(0,0)))
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))
```
I'm not suggesting we give the code as completely as this, but I think it includes all the possible options so far.

In the current dialogue it corresponds to this option - for our standard survey data.
![image](https://user-images.githubusercontent.com/11226469/126105141-e0a7edfb-2748-47ad-9c5a-f6b8358da517.png)

That gives this graph - I am calling it a sort of pie chart!
![image](https://user-images.githubusercontent.com/11226469/126105892-8b90beac-48fb-4a81-b431-24f0443b4000.png)

In the code above you don't need the scale_x_discrete command.

When I include that and make it c(2,0) the graph becomes:

![image](https://user-images.githubusercontent.com/11226469/126106070-151f17b8-7dec-455e-b677-2b9e36437f5f.png)

It is simpler too when there is only 1 factor: (At least if it is the Fill factor.  Then make x="", i.e. `aes(x="", fill=village))` for both pie and donut and you are back to:
 
![image](https://user-images.githubusercontent.com/11226469/126108384-17224a4d-dfb8-4548-9f6c-d304d01ec15b.png)

and:

![image](https://user-images.githubusercontent.com/11226469/126108524-715ab64d-6722-4c31-9557-1d9b52a21acf.png)

For the dialogue I suggest now:
a) Change the checkbox to Polar (i.e. delete the word Coordinates)
b) Only show the Donut and Pie when Polar is checked.  (And omit the x and y now.)
c) When checked, then Pie is the default.
d) No label round the radio buttons. 
e) They are next to the Polar checkbox 
f) Enough space after Pie for the word camembert in French!
 Then change the By Factor (Optional) to` By Factor (Fill)`

Finally I show this example - using width=1 and colour=black!
![image](https://user-images.githubusercontent.com/11226469/126109863-ee889032-ff8a-40f9-b673-f2c46ab6176a.png)

@lilyclements what do you think?  I write about the other part of your message below.

2021-07-19 06:34 UTC, rdstern commented
The second topic in @lilyclements message in #6523 concerned the important aspect of the order of the bars.  This should be easy, but I have one puzzle in the solution I suggest below.
There are functions in the forcats package for all we want.  So they can be inserted.  I suggest as follows - I am using the Climatic > Check Data > Boxplot dialogue just to show the sort of control to add!

![image](https://user-images.githubusercontent.com/11226469/126111573-23b21ee0-d255-4a25-a0ec-2ca5930e29a2.png)

So, I suggest we make the dialogue a bit wider and add a pull-down next to the 2 factor variables.  For the first it might only apply to the single option?  As I write this I suggest we should involve @shadrackkibet in this discussion and possibly also in the coding.  He will be taking over adding labels and perhaps could also do this as well, or at least advise.

So I suggest the pull-down has 4 options, namely:
a) `As given` (does nothing!
b) `Reverse` ( just add forcats::fct_rev( ))
c) `Ascending` (add forcats::fct_infreq(  ))
d) `Descending` (add - possibly - forcats::fct_rev(forcats::fct_infreq( )))

This might be quite simple to do?  And a powerful addition!

2021-07-19 08:59 UTC, lilyclements commented
@rdstern the first message sounds great - so to confirm I'm on the right page, under Frequency the only difference between donut and pie chart is that we run `+ scale_x_discrete(expand = expansion(add = c(2,0)))` for donut, and can have `c(0,0)` for pie (or not run it at all!). This sounds a lot more straight forward than I realised!

Adding a `width` and `colour` option looks good - are these things to offer on the main dialog or on a separate sub-dialog?

To the second message regarding the order of the bars, the four suggestions you have given sound good. To the "possibly", I believe the best way to `Descending` is by the code you have suggested given what was discussed [here](https://github.com/tidyverse/forcats/issues/209).

2021-07-19 14:27 UTC, rdstern commented
@lilyclements yes, that's right.  Unless I have it wrong.  `+ scale_x_discrete(expand = expansion(add = c(2,0)))` is added for the donut and omitted for the pie.  The (2,0) is to add a reasonable sized hole in the middle. and nothing at the outside.  

I was wondering about Adding Width as an additional option with the tooltip "Width of Bars" on the main dialogue.  I had not thought of Colour here, because we should then have Fill too I assume.  But, without Colour having no overlap, i.e. Width = 1, is more difficult to interpret.  On the plus side it applies equally to Bar and Pie.  I would first like to see how many options we have already on the main dialogue, because there is a Bar Chart options button that gives quite quick access to all these options.  

Before adding too much I would like to check on the full set of candidates for addition to the main dialogue .  I wonder about an option to not have the key, and possibly one to change a colour scale, or even a theme?

2021-07-19 17:49 UTC, rdstern approved these changes
@N-thony that's a good start.  Put Donut before Pie, so they can be closer together.  And now you have to change the code.  Have you been following Lily and my messages on this?

2021-07-20 06:31 UTC, N-thony commented
> I have been following this with the hope that we can review the code and merge soon then work on labels can start. @N-thony what kind of help can we provide so that this is completed or have something reasonable to merge and then perhaps continue later. Can we discuss this elsewhere?

Following the discussion the code needed was still changing, I have now to make the change again according to the last discussion.

2021-07-20 06:34 UTC, shadrackkibet commented
> > I have been following this with the hope that we can review the code and merge soon then work on labels can start. @N-thony what kind of help can we provide so that this is completed or have something reasonable to merge and then perhaps continue later. Can we discuss this elsewhere?
> 
> Following the discussion the code needed was still changing, I have now to make the change again according to the last discussion.

Thanks for the prompt response and all your efforts to complete this. Could you give a timeline on when you are going to complete that?

2021-07-20 06:36 UTC, N-thony commented
> > > I have been following this with the hope that we can review the code and merge soon then work on labels can start. @N-thony what kind of help can we provide so that this is completed or have something reasonable to merge and then perhaps continue later. Can we discuss this elsewhere?
> > 
> > 
> > Following the discussion the code needed was still changing, I have now to make the change again according to the last discussion.
> 
> Thanks for the prompt response and all your efforts to complete this. Could you give a timeline on when you are going to complete that?

Today, if there is nothing at this stage that will request a change.

2021-07-20 10:03 UTC, N-thony commented
> > > I have been following this with the hope that we can review the code and merge soon then work on labels can start. @N-thony what kind of help can we provide so that this is completed or have something reasonable to merge and then perhaps continue later. Can we discuss this elsewhere?
> > 
> > 
> > Following the discussion the code needed was still changing, I have now to make the change again according to the last discussion.
> 
> Thanks for the prompt response and all your efforts to complete this. Could you give a timeline on when you are going to complete that?

@shadrackkibet please have a look now. Thanks.

2021-07-20 10:14 UTC, rdstern commented
@N-thony it is getting there - slowly.  I think you are adding the code and hoping.  You could take longer and test more options for yourself.

This is the simplest combination:
![image](https://user-images.githubusercontent.com/11226469/126305064-c4d6065a-decc-43dc-9193-2f8185b2b0dd.png)

Here is your code for this:
```
survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(survey, mapping=ggplot2::aes(x="", fill=village)) + ggplot2::geom_bar(position="dodge", stat="count") + ggplot2::coord_polar("y") + xlim(0.2, 2.5) + scale_x_discrete(expand=expansion(add=c(2,0))) + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))

```
Look at the code we supplied to see that.
a) Ignore the setting of dodge and use position="fill".
b) The xlim(0.2,2.5) is left over from previously.  You don't need it.

I think you always want position = "fill" in the geom_bar part.

Now also check what you do for a pie chart when there is an x-variable, so 

![image](https://user-images.githubusercontent.com/11226469/126306704-d8f9094c-c630-4470-8776-41914a3d36f6.png)


You now get rid of the x-variable in the code to give this.
```
survey <- data_book$get_data_frame(data_name="survey")
last_graph <- ggplot2::ggplot(survey, ggplot2::aes(x="", fill=village)) + ggplot2::geom_bar(position="dodge", stat="count") + ggplot2::coord_polar("y") + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey")
data_book$get_graphs(data_name="survey", graph_name="last_graph")
rm(list=c("last_graph", "survey"))
```

a) Leave the x=variety in the command, so not x=""
b) As always put position="fill" - that was Lily's breakthrough!

2021-07-20 10:53 UTC, rdstern commented
Also make similar changes for the value option.  Simplest situation is here:

![image](https://user-images.githubusercontent.com/11226469/126311212-0347c2a9-33cc-445e-ad4c-0809a2eccac5.png)

From your current code:
a) Get rid on xlim - as before
b) Add position =fill - as before!

And so on!

2021-07-20 13:42 UTC, rdstern commented
This is much better now.  Here is the only problem I could find:

![image](https://user-images.githubusercontent.com/11226469/126333756-aadfac2d-e15b-4413-9f4d-e0d3e517fa58.png)

This is also a problem for the ordinary bar chart.  So when you have that right, the pie and donut will be ok too.

You can see from the dialogue that it should be `x=village,y=value,fill=variable`  But it isn't currently

Currently from that dialogue - not a pie or a donut I get:

```
survey_by_village <- data_book$get_data_frame(data_name="survey_by_village", stack_data=TRUE, measure.vars=c("min_yield","mean_yield","max_yield"))
last_graph <- ggplot2::ggplot(survey_by_village, mapping=ggplot2::aes(x=village, fill=value, y=variable)) + ggplot2::geom_bar(position="dodge", stat="identity") + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="survey_by_village")
data_book$get_graphs(data_name="survey_by_village", graph_name="last_graph")
rm(list=c("last_graph", "survey_by_village"))
```
You can see it has value and variable round the wrong way.  So the bar chart is wrong - and so is pie and donut.  Once fixed, all seem ok.

2021-07-20 15:20 UTC, rdstern approved these changes
@N-thony do you want to continue quickly adding the options to sort the frequencies.  Or should it be merged first?  I have approved in case you prefer for it to be merged, though I hope the sorting will be a small task?

2021-07-20 16:25 UTC, N-thony commented
> @N-thony do you want to continue quickly adding the options to sort the frequencies. Or should it be merged first? I have approved in case you prefer for it to be merged, though I hope the sorting will be a small task?

Okay, I can add it quickly.

2021-07-20 16:30 UTC, rdstern commented
@N-thony great.  Thanks

2021-07-20 19:06 UTC, shadrackkibet requested changes
Here are some questions and suggestions.

If you have the current receiver is the **X Variable** then you switch top radio buttons the focus is not changed.

![image](https://user-images.githubusercontent.com/26301973/126380868-17be02cb-7c2b-4441-9a39-2d19936bf0ba.png)

2021-07-24 06:54 UTC, N-thony commented
@shadrackkibet sorry for the delay. I have made the above corrections. Please have a look.

2021-07-24 08:39 UTC, shadrackkibet requested changes

2021-07-24 08:39 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +        rdoPie.Checked = True
What's the issue with conditions? did you try something and didn't work?

2021-07-24 08:39 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +            clsSubsetFunction2.AddParameter("1", clsROperatorParameter:=clsIsEqualToOperator2, iPosition:=1, bIncludeArgumentName:=False)
Why not use the correct parameters instead of `1`?

2021-07-24 08:39 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
>      Private clsPieAesFunction As New RFunction
Why the three `aes` functions? can't we use 2? If possible it would be better to have one. This brings a lot of duplication.

2021-07-24 08:39 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +        ucrReceiverByFactor.AddAdditionalCodeParameterPair(clsLevelsFunction, New RParameter("1", 0, bNewIncludeArgumentName:=False), iAdditionalPairNo:=3)
Use correct parameter name and therefore no need to hide. Check some other places as well.

2021-07-25 17:58 UTC, N-thony commented
@shadrackkibet thanks for the comments above and for the chat. I resolved some comments above and left others that I got stuck with as we discussed on chat. So, to gain on time since this is going long, I suggest that if you can take this over since you have to add the labels part meanwhile resolved the left comments then will have a look. Let me know if you are happy with that.

2021-07-29 09:27 UTC, shadrackkibet commented
Okay, could you mark the points you have resolved above?

2021-08-01 05:48 UTC, N-thony commented
> Okay, could you mark the points you have resolved above?

I have marked above the points that I have resolved.

2021-08-03 19:10 UTC, shadrackkibet approved these changes

2021-08-04 07:59 UTC, rdstern approved these changes
@shadrackkibet and @N-thony I am approving, because it would be so good to get this merged as it is currently.
There is still a lot to do on this dialogue - not least is the labelling of the second variable.  Then the sorting of the factors, the addition of lollipop and then (of course) the big one of adding labels.

2021-08-04 08:36 UTC, merged