#4832 Grid changes to allow paging
africanmathsinitiative/R-Instat pull request #6585
Opened 2021-07-05 13:13 UTC by ChrisMarsh82

Added Model and Databook folder and created model classes for the databook and dataframes.

2021-08-13 10:03 UTC, lloyddewit commented
> 
> 
> Added Model and Databook folder and created model classes for the databook and dataframes.

@ChrisMarsh82 Thanks for the PR. I liked how you labelled your commits. Tips for future PRs:
- When you open a PR its always good to give as much information as possible about the issue you're trying to solve.
- If this PR resolves an existing issue (e.g. issue #4832), then you should write 'Fixes issue #4832. GitHub will then automatically close the issue when this PR is merged.
- You shouldn't mention the issue number in the PR title
- The PR title is automatically included in the release notes provided to users. Therefore the title should explain (from a user perspective) what has changed. I updated the title but please feel free to improve

2021-08-13 10:19 UTC, lloyddewit commented
@ChrisMarsh82 I don't think the files below should be included in this PR. Can we remove them (I can help if needed)?
```
 instat/packages.config
 instat/translations/en/r_instat_not_menus.json
 instat/translations/rInstatTranslations.db
 instat/translations/translationsManuallyEntered.csv
 ...ges/TranslateWinForm.1.1.3/.signature.p7s → ...ges/TranslateWinForm.1.1.2
 packages/TranslateWinForm.1.1.2/lib/net461/TranslateWinForm.dll
 ...orm.1.1.3/lib/net461/TranslateWinForm.xml → ...orm.1.1.2/lib/net461/TranslateWinForm.xml
 packages/TranslateWinForm.1.1.3/lib/net461/TranslateWinForm.dll
```

2021-08-13 10:25 UTC, lloyddewit commented
@ChrisMarsh82 I get some build warnings
![image](https://user-images.githubusercontent.com/57253949/129343619-63633aab-7111-4613-9ba3-7675788ea7d5.png)

2021-08-13 10:38 UTC, lloyddewit commented
@ChrisMarsh82 I see that you created a folder structure for the VB files. I can see the advantages of structuring the files in this way. At some point, we should probably do this for all the source files in R-Instat.
The other VB files are currently in a flat structure. If we use a hierarchy, then I think we should do this consistently across the code base. Until then, I suggest we use the flat structure, else it gets confusing. We can discuss with @dannyparsons .

2021-08-13 10:54 UTC, lloyddewit requested changes
@ChrisMarsh82 I didn't really look at the contents of individual files in this review, I'll do that later. 
I added some higher level comments to the PR. There are also some merge conflicts.
The easiest way to resolve these comments and conflcts could be to make a new clean PR. We can discuss if needed.

2021-08-13 10:54 UTC, lloyddewit commented on instat/clsGridLink.vb
> +        Exit Sub
I assume that you'll delete the rest of this sub, is that correct?

2021-08-13 10:54 UTC, lloyddewit commented on instat/clsGridLink.vb
> +                                '  ucrDataViewer.SetColumnNames(strDataName, dfTemp.ColumnNames())
I assume that you'll delete this line?

2021-08-13 10:54 UTC, lloyddewit commented on instat/clsGridLink.vb
> +        If grdData.Worksheets.Count = 0 Then
This and all subsequent changes in this file are not real changes, the GitHub diff seems to be confused (or non-visible characters were inserted accidentally)

2021-08-13 14:01 UTC, ChrisMarsh82 commented
@lloyddewit I will try to sort conflicts and let you know if I need your help. May need to have another look at some of the code as my original plan was to remove clsLink completely. I seem to remember that was a grid that still used it but it may be worth me just changing that and removing the file altogether.

2021-08-13 14:01 UTC, ChrisMarsh82 commented
@lloyddewit @dannyparsons Regarding the file structure change. I feel we need to start doing this but it cannot be done in one pass. There is a problem with circular references in most of the files. My plan was to slowly move files into a file structure that don't have 'bad' references. That way we can add namespaces once all files are in structured folders.

2021-08-28 20:10 UTC, ChrisMarsh82 commented
@lloyddewit Sorry about the confusion on this one. I have now done it again on a completely new pull request see https://github.com/africanmathsinitiative/R-Instat/pull/6707
The new one is much cleaner.

2021-08-28 20:10 UTC, closed without merging