Added Density ridges to the Histogram dialogue
africanmathsinitiative/R-Instat pull request #6589
Opened 2021-07-07 14:20 UTC by HawardKetoyoMsatsi

Fixes #6278
@africanmathsinitiative/developers this is ready for review.
@rdstern  @shadrackkibet please take a look, I have added the density ridges and they work like other ggplot graphs. However, I will open an issue for more aesthetics and plot options that are frequently used but not featuring in the ggridges vignette to be added on a separate PR.

2021-07-08 06:09 UTC, rdstern commented
@HawardKetoyoMsatsi it works!  Great.  Well done.
Just one change I suggest, which is to have the fill also, by default, with the density ridges.  Then they become nice and colourful!
And there is a small problem with the coding to correct.  I added the Fill myself and that was fine.  Then I tried an ordinary density plot afterwards.  It had then also included the fill (sort of left over from the ridge plots) and that gave a problem.  Can you make sure that the settings from the density ridges are not used (by defautl) when the plot reverts to an ordinary density.

I also think (hope) there may be more options to add to the main dialogue, but that could be later.  Let's then get this version merged.

2021-07-08 06:28 UTC, shadrackkibet requested changes

2021-07-08 06:28 UTC, shadrackkibet commented on instat/dlgHistogram.vb
> +                ucrInputStats.Visible = False
Please use the linking i.e `.AddToLinkedControls` instead of doing this manually.

2021-07-08 06:28 UTC, shadrackkibet commented on instat/dlgHistogram.vb
> +    Private clsRidgesAesFunction As New RFunction
Question: Why can't we use `clsHistAesFunction` instead? I think you just need to update its parameters when the Ridges checkbox is checked.

2021-07-08 13:28 UTC, HawardKetoyoMsatsi commented on instat/dlgHistogram.vb
> +    Private clsRidgesAesFunction As New RFunction
@shadrackkibet the above have been fixed please take a look.

2021-07-08 13:37 UTC, HawardKetoyoMsatsi commented
@rdstern the above issue has been fixed, please take a look. The way the ggplot functions have been set requires one to add layers and their parameters from the sub dialogs.  I don't find errors anymore however some parameters fail to give meaningful graphs and once some parameters for a given graph are used switching to a new graph may require going back to the sub dialog to clear the unwanted parameters. I agree we should in future add controls for frequently used graph options

2021-07-08 18:08 UTC, rdstern submitted a review, later dismissed

2021-07-13 14:02 UTC, shadrackkibet requested changes
A question and comment below.

2021-07-13 14:02 UTC, shadrackkibet commented on instat/dlgHistogram.vb
> +        clsHistAesFunction.RemoveParameterByPosition(2)
Why remove parameters by position? and not by names? It is tricky to maintain positions, this might cause bugs in future if parameters are not added while maintaining the order in future.

2021-07-14 07:28 UTC, HawardKetoyoMsatsi commented on instat/dlgHistogram.vb
> +        'ucrFactorReceiver.AddAdditionalCodeParameterPair(clsHistAesFunction, New RParameter("y", iNewPosition:=2), iAdditionalPairNo:=1)
These were resolved in the previous commit, they are no more in the code.

2021-07-14 07:28 UTC, HawardKetoyoMsatsi commented on instat/dlgHistogram.vb
> +        clsHistAesFunction.RemoveParameterByPosition(2)
This too was resolved in the previous commit

2021-07-14 07:50 UTC, shadrackkibet commented on instat/dlgHistogram.vb
> +        'ucrFactorReceiver.AddAdditionalCodeParameterPair(clsHistAesFunction, New RParameter("y", iNewPosition:=2), iAdditionalPairNo:=1)
Your latest changes are from commit ID  `ffbd539`. As far I can see, this hasn't changed. Not unless you didn't push all your changes.

2021-07-16 10:07 UTC, HawardKetoyoMsatsi commented
@shadrackkibet The above have been fixed, however ucrChkRidges is not resetting properly, kindly advise me on an easy way to fix that. I am found some way to fix that but I thought there would be a better way.

2021-07-16 10:32 UTC, shadrackkibet commented
@HawardKetoyoMsatsi thanks for the fixes. You mention that **ucrChkRidges is not resetting properly**. What exactly do you mean? Does it not reset when you click the reset button?  Is it an issue with reopening the dialog? Any steps to replicate the bug? etc Could you also mention the solutions you have considered?
Explaining the problem clearly by giving more details and clarity about the problem you are having always help others to help you.

2021-07-19 08:20 UTC, HawardKetoyoMsatsi commented
Great lets have a skype call I discuss it I have a lot to explain...

2021-07-21 18:19 UTC, shadrackkibet commented
@HawardKetoyoMsatsi the resetting bug should be fixed when you merge the changes I added into your branch 2 days ago.

2021-07-22 05:00 UTC, shadrackkibet commented on instat/dlgHistogram.vb
> +        ucrChkRidges.SetRCode(clsHistAesFunction, bReset)
This checkbox doesn't pass any parameters. The checkbox is meant to switch between density ridges and density plots. Could you explain why you need this?

2021-07-22 07:28 UTC, shadrackkibet commented on instat/dlgHistogram.vb
>          End If
This `sub` could be combined with `SetDialogOptions()` but perhaps it is better to keep it this way because it clutters the subroutine. I leave this as a choice for you to consider or not.

Let us know when this is ready for re-testing again.

2021-07-22 13:00 UTC, HawardKetoyoMsatsi commented on instat/dlgHistogram.vb
>          End If
Hi Shadrack I am now done kindly retest this

2021-07-22 14:02 UTC, shadrackkibet commented
@rdstern please test.

2021-07-22 18:43 UTC, rdstern commented
@shadrackkibet and @HawardKetoyoMsatsi I now managed what I was aiming for.  But not at the first attempt.

I list below what I did, but mainly for the record.  I suggest there are 2 things to examine:

a) When now using ordinary density, (with a factor) it now adds the fill - where before it just used colour.  And it is very persistent.  If you go to the density options and remove the fill, then it works, but just once, and then insists on putting the fill back.
b) The multiple variables works for the ordinary density, but gives and error for the ridge plots.  The comparative code for the 2 are at the bottom of this message.
---------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/11226469/126680192-cca9bf68-e84e-4aeb-be3e-6492317f8dc1.png)

[zambia6_July.zip](https://github.com/africanmathsinitiative/R-Instat/files/6864032/zambia6_July.zip)

Here is the data if you wish to try.  The dialogue seems somewhat flaky.  I'll start again and go step-by-step.  (This actually worked except for the fill.  So I am just recording the steps as a record of what I did.  Earlier it gave me some errors.

Here is ordinary density - not ridge, and it is different now to Version 7,2 u=in giving fill, rather than colour.  It does facets ok though.
![image](https://user-images.githubusercontent.com/11226469/126681155-c55bd8a1-78f8-498a-ab62-c2bb62a799b2.png)

It works with the facets:
![image](https://user-images.githubusercontent.com/11226469/126681348-87879ca1-182f-4513-9078-30df6d03a5d0.png)

In density options it has given both fill and colour - it used to be just colour:
![image](https://user-images.githubusercontent.com/11226469/126681758-dc6e8faf-7d59-40bb-b869-59a285191bd4.png)

If I get rid of Fill, then it is OK - but just once.  It then insists on adding the fill again.  This is different to version 0.7.2.

Now I change to density ridges and it works fine!

Then I add a second layer - and it still works!

So I reset and go straight to denstiy ridges by month and with station as facet.

![image](https://user-images.githubusercontent.com/11226469/126687894-55c2a441-db18-4676-a4f7-893ad5df4f5c.png)

ok, but without colour.

Back to the dialogue, & just press Ok and they are now in colour.  The fill seems to have a mind of its own.

Perhaps I know the possible problem?  Reset and do density (and then density ridges from multiple:

![image](https://user-images.githubusercontent.com/11226469/126689398-06e92f8c-c141-4083-80bc-42896f65041b.png)

Density works fine, but density ridges does not  It gives:

![image](https://user-images.githubusercontent.com/11226469/126689657-677113bb-cad2-4d21-987e-1217d14538be.png)

The code generated for density (with facets set) was as follows - and works:

```
# Code generated by the dialog, Histogram Plot
zambia6 <- data_book$get_data_frame(data_name="zambia6", stack_data=TRUE, measure.vars=c("tmax","tmin"))
last_graph <- ggplot2::ggplot(data=zambia6, mapping=ggplot2::aes(x=value, fill=variable, colour=variable)) + ggplot2::geom_density(mapping=ggplot2::aes(y=stat(count))) + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text()) + ggplot2::facet_wrap(facets= ~ station, dir="h")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="zambia6")
data_book$get_graphs(data_name="zambia6", graph_name="last_graph")

```
The code for density ridges (which doesn't work) is as follows:  (Is the extra second line needed?

```
# Code generated by the dialog, Histogram Plot
zambia6 <- data_book$get_data_frame(data_name="zambia6", stack_data=TRUE, measure.vars=c("tmax","tmin"))
variable <- data_book$get_columns_from_data(data_name="", col_names="variable")
last_graph <- ggplot2::ggplot(data=zambia6, mapping=ggplot2::aes(x=value, fill=variable, y=variable)) + ggridges::geom_density_ridges(mapping=ggplot2::aes(x=data_book$get_columns_from_data(data_name="zambia6", col_names=c("tmax","tmin")), y=variable)) + theme_grey() + ggplot2::theme(axis.text.x=ggplot2::element_text()) + ggplot2::facet_wrap(facets= ~ station, dir="h")
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="zambia6")
data_book$get_graphs(data_name="zambia6", graph_name="last_graph")
```

2021-07-23 06:08 UTC, shadrackkibet commented
@HawardKetoyoMsatsi are you able to fix these bugs quickly? Otherwise, I am happy to take over the fixes while you focus on some other tasks.

2021-07-23 06:20 UTC, rdstern commented
@HawardKetoyoMsatsi and @shadrackkibet I would be very happy if they can be fixed and merged quickly.  

That's partly because there is another (small?) task for Haward on the same dialogue - dotplots - which I am hoping can also be used to introduce @Cal-Insta to the coding.  But it is sufficiently different that I strongly suggest we merge these changes first.

2021-07-23 08:23 UTC, HawardKetoyoMsatsi commented
Great I am working on this.

2021-07-23 08:45 UTC, shadrackkibet commented
Can you approximate how long it will take to complete it?

2021-07-23 08:52 UTC, HawardKetoyoMsatsi commented
Hi @shadrackkibet  I see I am still figuring out how to fix it may take me a bit long. 
Could you please go ahead and take over the need fixes so that I focus on Tufte plots I just got more corrections to do there. 
Is this okay with you?

2021-07-24 08:14 UTC, shadrackkibet commented
Did you fix this?

2021-07-26 15:01 UTC, HawardKetoyoMsatsi commented
Hi @shadrackkibet this has been fixed though missing a few things that am still on.

2021-07-27 09:43 UTC, HawardKetoyoMsatsi commented
@rdstern @shadrackkibet the above is fixed kindly take a look.

2021-07-28 06:42 UTC, shadrackkibet commented
@rdstern I did some quick testing and looks like the bugs are fixed. Could you please check and approve?

- Another enhancement we might consider separately is to change the order of receivers so that we have fill and colour immediately after y receiver.
- I think you earlier suggested that we can add the fill receiver into the main dialog. I agree.

![image](https://user-images.githubusercontent.com/26301973/127274563-79878afd-216c-4aa3-a56f-5f7efd9d4891.png)

2021-07-28 07:11 UTC, rdstern approved these changes
@shadrackkibet I am approving now.
a) I agree that it will be good to add the fill to the main dialogue and that sort of feature - adding extra convenient controls  - can beome a separate pull request.  Perhaps the sprint could look more generally at this aspect for these dialogues.
b) There is another issue to raise, in that the multiple variable options is now (perhaps correctly) disabled for the ridge plots.  It is still there for the otrdinary density and histogram and generates an error.  Testing and sorting out this single/multiple is again something we could perhaps examine during the sprint?

2021-07-28 08:06 UTC, shadrackkibet approved these changes

2021-07-28 08:06 UTC, merged