Added Tufte boxplots to the Boxplot, Jitter and Violin plot dialogue
africanmathsinitiative/R-Instat pull request #6594
Opened 2021-07-09 10:00 UTC by HawardKetoyoMsatsi

Fixes #6251
@rdstern and @shadrackkibet take a look, I have added the tufte boxplots.
@africanmathsinitiative/developers This is ready for review.

2021-07-09 16:05 UTC, rdstern commented
@HawardKetoyoMsatsi that's a good start.  Did you manage to get the Tufte boxplot to show outliers.  I checked on stack-overflow and found that you need to put stat="boxplot".  That should be the default, i.e. geom_tufteboxplot(stat="boxplot").  And that option should be added to the stat in the geom.
Could you also add coef (same default of 1.5 as for boxplot.  I couldn't see it documented anywhere, but it works fine.
Then I suggest your default could be median = "line".
In addition you need to check the code when any of the other options are used.
a) The proportional to size has no meaning and should be hidden.
b) The next 3 options should all work fine, except you then add an ordinary boxplot to the code.  Instead, if Tufte is selected, then put the tufte boxplot after the adjustment, where you currently have the additional ordinary boxplot.
c) In connecting the mean/median, change the width from 1.5 to 0.7.  That's at least for Tufte.

2021-07-12 06:50 UTC, lloyddewit commented
@N-thony please could you also review this one? thanks

2021-07-12 07:57 UTC, N-thony commented
> @N-thony please could you also review this one? thanks

@lloyddewit sure, happy to review.

2021-07-13 07:31 UTC, HawardKetoyoMsatsi commented
@rdstern  thanks so much for the observation, The three parameters are being added in a sub dialogue and it is unfortunate that when the geom_tufteboxplot() was added, the stat = "boxplot" option was left out we will have to add it in a new or. The bellow error will appear when you click on the button "Tufte Boxplot Options" but once we add the option (stat = "boxplot") in the subdialog the error will disappear.
![image](https://user-images.githubusercontent.com/16137042/125408907-0f9d6300-e3c4-11eb-97db-6637bd166c90.png)
Therefore we have to add  (stat = "boxplot") under geom_tufteboxplot.

2021-07-15 05:38 UTC, rdstern requested changes
@HawardKetoyoMsatsi it seems to work fine now.

Will you be adding the boxplot option to the geom in this pull request, or in a new one?

When you do, then remember to also add the coef as well - in the same place in the list as for the ordinary boxplots.

2021-07-21 14:44 UTC, rdstern commented
@HawardKetoyoMsatsi I still get the developer error, but I assume that is because the pull request hasn't been updated?  I think the new geom changes have now been merged, but perhaps not.

I did notice that you can't (currently for Tufte boxplots with the 2 factors.  The fill factor is not visible for the Tufte.  Fill, of course doesn't work with Tufte, but colour does as here?
![image](https://user-images.githubusercontent.com/11226469/126508357-858c79eb-529d-4ebe-8a39-887f6a4d786f.png)

So, I wonder, if we could keep the second factor in the boxplot dialogue, but if Tufte, then use colour rather than Fill?

Then I am ready to see this one merged.

2021-07-23 07:16 UTC, HawardKetoyoMsatsi commented
@rdstern I have made the above corrections I added second factor receiver to the boxplot and made the parameter name to be colour rather than fill, kindly take a look.

2021-07-23 07:37 UTC, rdstern submitted a review, later dismissed
@HawardKetoyoMsatsi looks good and happy to have a Tufte' style graph as an option.  Perhaps @shadrackkibet to check and merge?

2021-07-23 07:59 UTC, shadrackkibet requested changes

2021-07-23 07:59 UTC, shadrackkibet commented on instat/dlgBoxPlot.vb
> +    End Sub
Remove?

2021-07-23 07:59 UTC, shadrackkibet commented on instat/dlgBoxPlot.vb
>          Else
Combine with the sub above?

2021-07-23 07:59 UTC, shadrackkibet commented on instat/dlgBoxPlot.vb
> +        clsStatSummary.AddParameter("size", 1.5)
Enforce parameter positioning here elsewhere.

2021-07-23 09:26 UTC, HawardKetoyoMsatsi commented
@shadrackkibet I have fixed the above please take a look.

2021-07-23 09:30 UTC, shadrackkibet approved these changes
@rdstern functionality shouldn't be affected. Could you re-test and re-approve?

2021-07-23 09:55 UTC, rdstern approved these changes

2021-07-23 10:07 UTC, merged