Added Lan button in the Tools - Options dialog
africanmathsinitiative/R-Instat pull request #6628
Opened 2021-07-20 07:24 UTC by N-thony

Fixes #6601
@africanmathsinitiative/developers @rdstern @rachelkg this is ready for review. Thanks.

2021-07-21 07:51 UTC, lloyddewit commented
@HawardKetoyoMsatsi please could you review?
@rdstern Please could you test?
Thanks

2021-07-21 09:08 UTC, rdstern commented
This seems to work ok and could approve.  Except it doesn't work when you press the Apply button.

![image](https://user-images.githubusercontent.com/11226469/126462456-51e20965-fa8f-4998-a340-3e52c610d7a6.png)

So here it is with Lan active, but in English.

And here I am in French without the Lan

![image](https://user-images.githubusercontent.com/11226469/126462853-867d940a-eb77-4565-b2f9-aa34c4bf95d6.png)

When I go out and then in to the dialogue again, then it is ok.  But if the options are easy to activate on Apply as well as when the dialogue is loaded, that would be more complete.

Not worth too much time though.

2021-07-21 16:44 UTC, N-thony commented
> This seems to work ok and could approve. Except it doesn't work when you press the Apply button.
> 
> ![image](https://user-images.githubusercontent.com/11226469/126462456-51e20965-fa8f-4998-a340-3e52c610d7a6.png)
> 
> So here it is with Lan active, but in English.
> 
> And here I am in French without the Lan
> 
> ![image](https://user-images.githubusercontent.com/11226469/126462853-867d940a-eb77-4565-b2f9-aa34c4bf95d6.png)
> 
> When I go out and then in to the dialogue again, then it is ok. But if the options are easy to activate on Apply as well as when the dialogue is loaded, that would be more complete.
> 
> Not worth too much time though.

@rdstern thanks for your comment, I think it is now fixed/resolved. Please, have a look.

2021-07-21 19:04 UTC, rdstern approved these changes

2021-07-28 08:17 UTC, shadrackkibet commented
@HawardKetoyoMsatsi your peer review is still pending here.

2021-07-29 11:11 UTC, HawardKetoyoMsatsi requested changes

2021-07-29 11:11 UTC, HawardKetoyoMsatsi commented on instat/dlgOptions.vb
> +
Remove this empty line

2021-07-29 11:35 UTC, HawardKetoyoMsatsi commented
@shadrackkibet over to you.

2021-07-29 16:28 UTC, rdstern commented
Excellent idea.  Perhaps @Patowhiz can add that during the sprint?

2021-07-29 21:30 UTC, rdstern approved these changes

2021-07-30 04:13 UTC, shadrackkibet approved these changes

2021-07-30 04:14 UTC, merged