Bug fixes when reopen and re-run the R code on visdat dialog plus added the up down text size option
africanmathsinitiative/R-Instat pull request #6643
Opened 2021-07-26 18:11 UTC by N-thony

Fixes #6637
This fixes the error when re-running the R code on reopening of the dialog and added the up-down text size option.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-07-29 08:34 UTC, shadrackkibet commented
@Ivanluv could you please review?

2021-07-29 09:30 UTC, Ivanluv commented on instat/dlgVisualizeData.vb
> +        ucrChkAdjustSize.AddToLinkedControls(ucrNudAdjustSize, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, bNewLinkedChangeToDefaultState:=True, objNewDefaultS
I dont think you need  `bNewLinkedChangeParameter ` parameter in this linking

2021-07-29 09:33 UTC, Ivanluv commented on instat/dlgVisualizeData.vb
> +        clsBaseOperator.RemoveParameterByName("right")
could have these in an else statement within the if statement below?

2021-07-29 09:34 UTC, Ivanluv commented on instat/dlgVisualizeData.vb
> +
remove space

2021-07-29 09:58 UTC, N-thony commented on instat/dlgVisualizeData.vb
> +        clsBaseOperator.RemoveParameterByName("right")
I think it is better rather than having additional lines with else.

2021-07-29 10:02 UTC, N-thony commented
@Ivanluv I have resolved your comments above. Please have a look.

2021-07-29 10:20 UTC, Ivanluv commented
@shadrackkibet  this is okay from my end

2021-07-29 10:40 UTC, shadrackkibet requested changes
Only one minor change.

2021-07-29 10:40 UTC, shadrackkibet commented on instat/dlgVisualizeData.vb
> +        ucrNudAdjustSize.Maximum = 15
Use `.SetMinMax()`?

2021-07-29 10:40 UTC, shadrackkibet commented on instat/dlgVisualizeData.vb
>          ucrNudSamplingFunction.Maximum = 1
Alos o here

2021-07-29 10:41 UTC, shadrackkibet commented
@rdstern could you please check that this fixes the bug reported?

2021-08-04 07:48 UTC, rdstern requested changes
@N-thony this looks good.  Could you just make the default size 5 rather than 1.  Then I'll approve quickly.

2021-08-04 09:08 UTC, N-thony commented
> @N-thony this looks good. Could you just make the default size 5 rather than 1. Then I'll approve quickly.

@rdstern I have  changed the default sized. Please have a look. Thanks.

2021-08-04 09:28 UTC, rdstern requested changes
@N-thony that seems fixed.  But the dialogue is now too short - so we don't see all of the bottom controls

2021-08-04 11:11 UTC, N-thony commented
@rdstern sorry for this. I have corrected the size. Please have a look. Thanks.

2021-08-04 15:12 UTC, shadrackkibet commented on instat/dlgVisualizeData.vb
> +        clsBaseOperator.RemoveParameterByName("right")
It is logical to have this as an else. Therefore I agree with @Ivanluv suggestion.

2021-08-04 15:15 UTC, shadrackkibet commented
You added a control therefore make sure that the Tab order is sorted out.

2021-08-09 09:44 UTC, lloyddewit commented
@N-thony I understand that you've resolved all the comments, is that correct?
There's a merge conflict, will you resolve by making a new PR and closing this PR?

2021-08-12 07:16 UTC, lloyddewit commented
Replaced by PR #6666

2021-08-12 07:16 UTC, closed without merging