Removing duplicated code in clsRlink
africanmathsinitiative/R-Instat pull request #6648
Opened 2021-07-29 07:50 UTC by Ivanluv

fixes #6622
@africanmathsinitiative/developers  this is ready for review

2021-07-29 08:31 UTC, shadrackkibet commented
@N-thony please could you review?

2021-07-31 15:05 UTC, N-thony reviewed
Looking good from my end. Over to you @shadrackkibet. Thanks.

2021-08-01 12:20 UTC, shadrackkibet requested changes

2021-08-01 12:20 UTC, shadrackkibet commented on instat/clsRLink.vb
> +    Private Function GetColumnNames(strDataFrameName As String, strRCommand As String) As String()
Could you add the XML header to this new function?

2021-08-02 08:48 UTC, Ivanluv commented on instat/clsRLink.vb
> +    Private Function GetColumnNames(strDataFrameName As String, strRCommand As String) As String()
Done

2021-08-02 08:57 UTC, shadrackkibet approved these changes
@lloyddewit could you also review and merge.

2021-08-05 08:47 UTC, lloyddewit approved these changes

2021-08-05 08:49 UTC, lloyddewit commented
@shadrackkibet I just made some small updates to the function headers. Please could you approve again and merge? thanks

2021-08-05 09:12 UTC, shadrackkibet approved these changes

2021-08-05 09:12 UTC, merged