Added geom_text_repel and geom_label_repel from ggrepel package into the R-Instat list of geoms
africanmathsinitiative/R-Instat pull request #6649
Opened 2021-07-29 17:15 UTC by HawardKetoyoMsatsi

This Fixes #6626
@rdstern  this is ready for review.
@africanmathsinitiative/developers this is ready for review

2021-07-29 21:25 UTC, rdstern requested changes
@HawardKetoyoMsatsi that looks promising.  But is gives an error.  It generates the command ggplot2::geom_label_repel when it should be ggrepel instead.  Same for text _repel.

2021-07-30 07:21 UTC, HawardKetoyoMsatsi commented
@rdstern the above changes have been made.

2021-08-02 12:13 UTC, HawardKetoyoMsatsi commented
@rdstern could you please review this, It will be needed to be merged for the ggrepel to be used to solve another issue.

2021-08-02 13:17 UTC, rdstern submitted a review, later dismissed

2021-08-02 13:20 UTC, shadrackkibet requested changes

2021-08-02 13:20 UTC, shadrackkibet commented on instat/ucrGeom.vb
> +        'clsgeom_label_repel.AddLayerParameter("direction", "list", Chr(34) & "c"(Chr(34) & "both" & Chr(34), Chr(34) & "x" & Chr(34), Chr(34) & "y" & Chr(34)) & Chr(34), lstParameterStrings:={Chr(34
Why is this commented out?

2021-08-02 13:20 UTC, shadrackkibet commented on instat/ucrGeom.vb
> +        'clsgeom_text_repel.AddLayerParameter("direction", "list", Chr(34) & "c"(Chr(34) & "both" & Chr(34), Chr(34) & "x" & Chr(34), Chr(34) & "y" & Chr(34)) & Chr(34), lstParameterStrings:={Chr(34)
Also here

2021-08-02 14:19 UTC, HawardKetoyoMsatsi commented
@shadrackkibet the above is fixed, hovever due to the size of the ialog cant allow all parameters to be vissible
(inherit.aes,verbose,seeddirection) wont show for geom_text_repel while (show.legend, na.rm, seed, inherit.aes, verbose, direction) wont show for geom_label_repel

2021-08-02 15:31 UTC, shadrackkibet commented
Just before we merge this. Could you check with @maxwellfundi on the criteria he adopted before in choosing the number parameters to add? I guess the choice is based on those parameters that are used "mostly" which will need some research online. There is no need to add parameters that won't be visible in the dialog!

2021-08-03 15:30 UTC, rdstern approved these changes

2021-08-04 09:03 UTC, HawardKetoyoMsatsi commented
@shadrackkibet I updated the order and removed the extra parameters that cant apper whe R-instat is run

2021-08-04 15:09 UTC, shadrackkibet approved these changes
@rdstern could you check and re-approve?

2021-08-11 15:26 UTC, rdstern approved these changes

2021-08-12 07:17 UTC, merged