Improve the geom_smooth() parameters
africanmathsinitiative/R-Instat pull request #6654
Opened 2021-08-02 11:40 UTC by HawardKetoyoMsatsi

Fixes #6652
@rdstern this is ready for review.
@africanmathsinitiative/developers this is ready for review.
I added the `se `parameter however vb decodes if as `ifelse `but the r code generated it is correctly decoded as `se`.

2021-08-02 15:07 UTC, rdstern commented
I think that's right.  So just change the ifelse label to `se` instead.

But I also think there should be a linetype and size parameter in smooth, as there is for the line geom.

2021-08-03 14:24 UTC, HawardKetoyoMsatsi commented
@rdstern the above has been fixed

2021-08-03 15:34 UTC, rdstern submitted a review, later dismissed

2021-08-09 09:31 UTC, lloyddewit requested changes
@HawardKetoyoMsatsi thanks, just one very small question

2021-08-09 09:31 UTC, lloyddewit commented on instat/ucrGeom.vb
> +        clsgeom_smooth.AddLayerParameter("se ", "list", "TRUE", lstParameterStrings:={"TRUE", "FALSE"})
Are the spaces required?
```suggestion
        clsgeom_smooth.AddLayerParameter("formula", "editablelist", "y ~ x", lstParameterStrings:={"y ~ x", "y ~ poly(x, 2)", "y ~ log(x)", "y ~ splines::bs(x,3)"})
        clsgeom_smooth.AddLayerParameter("se", "list", "TRUE", lstParameterStrings:={"TRUE", "FALSE"})
```

2021-08-16 07:35 UTC, HawardKetoyoMsatsi commented on instat/ucrGeom.vb
> +        clsgeom_smooth.AddLayerParameter("se ", "list", "TRUE", lstParameterStrings:={"TRUE", "FALSE"})
Yes, the econd space sfter `se ` is needed. In case the space after `se ` is omitted vb labels `ifelse` instead of `se`

2021-08-16 07:45 UTC, HawardKetoyoMsatsi commented
@lloyddewit I have made the required changes please take a look.

2021-08-16 08:44 UTC, shadrackkibet commented on instat/ucrGeom.vb
> +        clsgeom_smooth.AddLayerParameter("se ", "list", "TRUE", lstParameterStrings:={"TRUE", "FALSE"})
This is strange. Could you add a comment to alert the next maintainer?

2021-08-16 09:38 UTC, HawardKetoyoMsatsi commented on instat/ucrGeom.vb
> +        clsgeom_smooth.AddLayerParameter("se ", "list", "TRUE", lstParameterStrings:={"TRUE", "FALSE"})
@shadrackkibet a comment has been added.

2021-08-16 10:36 UTC, shadrackkibet approved these changes
@rdstern could you re-test and approve if you are happy to merge?

2021-08-20 09:23 UTC, rdstern approved these changes

2021-08-20 11:22 UTC, dannyparsons approved these changes

2021-08-20 11:23 UTC, merged