Improvements to the Frequency dialogue
africanmathsinitiative/R-Instat pull request #6655
Opened 2021-08-02 13:28 UTC by Ivanluv

fixes #6640
This is still in progress

2021-08-03 09:52 UTC, Ivanluv commented
@lilyclements  when using the summary and both margin options am getting the following error
![image](https://user-images.githubusercontent.com/45068931/127996025-a2ac0a7c-548b-4d21-8c74-18fc6a2d7a26.png)
Is there a way I can fix this?

2021-08-03 11:36 UTC, lilyclements commented
In the frequency dialog you can only do outer margins, at least for now.
I need to discuss and amend the code for summary margins.

2021-08-03 12:51 UTC, Ivanluv commented
@lilyclements  okay.Thanks

2021-08-04 09:21 UTC, Ivanluv commented
@lilyclements could you look at these and suggest any more additions or changes I can make

2021-08-04 11:30 UTC, lilyclements reviewed
1. What is "Checkbox1" and the receiver by it? Should the receiver be disabled/hidden, and checkbox1? Or if not, can you name Checkbox1?
2. Can you align the group boxes a little more together?
3. Can you remove the margin group box. The only option is "Outer".
4. There is no option for the number of columns like in the Summary dialog. Can you add a "Column Factors:" control in and for it to work similar to the Summary Tables dialog?
5. Since there are no summary variables given, can you remove the "Treat Summaries as Further Factor" option, and the checkboxes that link to it when it is `TRUE` and `FALSE` except keep the "Display Summaries as Rows" checkbox.

2021-08-07 06:44 UTC, rdstern reviewed
@Ivanluv and @lilyclements that looks good for a start.  I notice zero frequencies are omitted.  Can there be an option to include them?  And the percentages don't yet work.  But I know this is work in progress.

2021-08-08 09:16 UTC, lilyclements commented
@rdstern what of the percentages do not work? There shouldn’t be any lost functionality from the previous frequency tables
By zero frequencies are omitted do you mean combinations with no frequencies currently come up as a blank or NA, or do you mean something else?

2021-08-08 10:46 UTC, rdstern commented
@lilyclements and @Ivanluv it just doesn't work!

When I don't have percentages it correctly gives the counts!  Here is the code - without requesting the percentages:

```
# Code generated by the dialog, Frequency
frequency_table <- data_book$summary_table(data_name="survey_subset1", factors=c("village","variety"), store_results=FALSE, treat_columns_as_factor=FALSE, summaries=count_label)

last_table <- mmtable2::mmtable(data=frequency_table, cells=value) + mmtable2::header_top_left(variable=village) + mmtable2::header_left_top(variable=variety)
data_book$add_table(table_name="last_table", table=last_table, data_name="survey_subset1")
data_book$get_tables(data_name="survey_subset1", table_name="last_table")

rm(list=c("last_table", "frequency_table"))

`That's fine.  Then I tick to add percentages.  Here is an example - I tried different ones:

![image](https://user-images.githubusercontent.com/11226469/128629313-0a26db8c-9b5d-4135-b7a1-b697d14f3717.png)

The code generated remains identical to the above - so whatever I do I still just get the counts!

2021-08-16 08:01 UTC, Ivanluv commented
@rdstern  I have fixed the added the frequency functionality

2021-08-16 08:08 UTC, rdstern commented
@Ivanluv great.  I'll check

2021-08-17 06:20 UTC, rdstern requested changes
@Ivanluv and @lilyclements great.  The percentages now work.  

The one item to fix, before merging, at this stage, is the order of factor levels.  This is the same in the frequency and summary dialogues.  The order in the tables should be the same as the order of those factors.  The current tables insist on the default alphabetical order.

2021-08-25 08:13 UTC, Ivanluv commented
@rdstern  I have fixed the ordering of factors

2021-08-25 08:26 UTC, rdstern approved these changes
@Ivanluv this now seems to work fine.  I am approving.
@shadrackkibet over to you.  We are now making real progress!

2021-08-25 08:30 UTC, shadrackkibet commented
@N-thony could you review first.

2021-08-30 08:39 UTC, lloyddewit approved these changes

2021-08-30 08:40 UTC, lloyddewit commented
@rdstern Please could you retest? thanks

2021-08-31 06:27 UTC, rdstern requested changes
@Ivanluv it now seems very solid.  I was really hoping to merge now, but one item to fix first is the display of margin totals.
The default is All, but you can type there.  However, even with the default I always get the margin title as NA - which is very confusing.  I was using the simple survey data set.   It should be obvious, whichever data you use.  I can add pictures if needed.  I hope it is simple to fix.

2021-08-31 08:47 UTC, Ivanluv commented
@lilyclements  could you help me with this ,I think the error might be in the summary function in R

2021-08-31 12:56 UTC, lilyclements commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> -  }
To fix the problem highlighted by @rdstern can you add here:

```
for (i in seq_along(factors)) {
    levels(shaped_cell_values[[i]]) <- c(levels(shaped_cell_values[[i]]), margin_name)
  }
```

2021-08-31 14:02 UTC, Ivanluv commented
@rdstern  the margin total is now fixed

2021-09-01 08:06 UTC, rdstern approved these changes
Great!

2021-09-01 08:24 UTC, lloyddewit approved these changes

2021-09-01 08:26 UTC, merged