Added sample as a summary into column statistics dialog
africanmathsinitiative/R-Instat pull request #6673
Opened 2021-08-14 07:43 UTC by shadrackkibet

fixes #6646

@rdstern here is the addition of sampling into the summary system. Please test.

2021-08-14 07:54 UTC, rdstern reviewed
@shadrackkibet looks good.  Did you also add the Replace checkbox?  If that is to sample with replacement, then it has no relevance, because we are only taking a single observation.  It could (sometimes) be nice to be able to take say 3 random observations and then this would be relevant.  But that opens the same potewntial "can of worms" as when I asked Danny if we could have 2 percentiles at the same time!

2021-08-14 08:00 UTC, shadrackkibet commented
We could allow sampling many but then it will mean the other summaries are duplicated. For example, with size = 5 we will have something like this? 
![image](https://user-images.githubusercontent.com/26301973/129439439-798c09f5-cb83-479d-b454-791489a9b85b.png)

2021-08-14 08:15 UTC, rdstern commented
aha.  Let's just stick with the 1 - otherwise it is different to all the other summaries and it isn't important enough for that.  At least not here!

2021-08-14 08:32 UTC, shadrackkibet commented
@rdstern done! You could test fully now. Thanks.

2021-08-14 08:51 UTC, rdstern requested changes
@shadrackkibet this is working fine.  I think I would slightly prefer to not have the set seed by default.  Then I am ready to approve.

2021-08-14 12:16 UTC, shadrackkibet commented
@rdstern that is done now.

2021-08-14 12:41 UTC, rdstern approved these changes

2021-08-15 07:57 UTC, lloyddewit approved these changes
@shadrackkibet I just had a couple of questions but they're not important so I'll approve.
I'll also merge. If you want to update the code further, then we can always do this in a separate PR.

2021-08-15 07:57 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +summary_sample <- function(x, replace = FALSE, seed, ...){
Is '...' needed here?

2021-08-15 07:57 UTC, lloyddewit commented on instat/sdgSummaries.vb
> +        ucrChkSample.AddToLinkedControls(ucrChkSetseed, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True)
rename to 'ucrChkSeed'?

2021-08-15 07:57 UTC, merged

2021-08-16 03:59 UTC, shadrackkibet commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +summary_sample <- function(x, replace = FALSE, seed, ...){
Yes, because there are some other unnamed parameters that could be passed to the sample function.

2021-08-16 04:01 UTC, shadrackkibet commented on instat/sdgSummaries.vb
> +        ucrChkSample.AddToLinkedControls(ucrChkSetseed, {True}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True)
Sure.