Improved Test/String Keyboard and  Added tooltips for the keys.
africanmathsinitiative/R-Instat pull request #6689
Opened 2021-08-20 17:36 UTC by Gioche6

We have done this with the help of @Wycklife 
We have fixed the following;
1. Changed the names of the keys you suggested
2. Added the three new keys you suggested
3. Added stringr package to the function of each and every key that had it missing.
4. Added tooltips for the keys.

@rdstern This is ready for review. Please let us know of any change/improvements.

2021-08-21 13:33 UTC, Wycklife commented
@rdstern Could you review please

2021-08-21 13:42 UTC, rdstern commented
will do

2021-08-22 10:23 UTC, rdstern requested changes
@Wycklife I saw that Gioche6 has done this pull request.  Could you please check with @maxwellfundi so they are all registered on github.  Then I can reply to them directly.
a) The pull request should have referenced the issue #6678 that was being addressed.  
b) They should have read through the issue carefully.  Then they would have seen that there was an additional file added with tooltips for the rest of the keyboard.  Can those be added as well please.
c) ends is incorrect change ear to eye to correct it.
d) Please also check extract.  Try it to check it is ok.  It may be.
e) Get rid of stringr:: in locate and locate2.  That's probably a mistake I made.  That's also important for them to learn, i.e. don't assume I am perfect.  Check yourselves that it is sensible.  If I omitted the stringr:: in all the other examples, then it should probably be omitted from the tooltip here.  At least I could be asked.
e) Can you make the keys on the bottom row less wide - so all 6 keys are the same total width as the 5 in the other rows.  Or at least almost.

2021-08-24 06:46 UTC, Gioche6 commented
@rdstern I and @Vitalis95 have made the changes you requested with the help of @Wycklife. Could you please have a look at them.

2021-08-25 10:26 UTC, rdstern approved these changes
@Gioche6 this now looks good.  Except the idea of getting rid of the wider key on the last line was that the dialogue could then be a bit smaller.
The key is now nicely placed, so please could the blank space at the right of the dialogue  be reduced.  Then I am ready to approve.

2021-08-25 10:29 UTC, rdstern requested changes
@Gioche6 this now looks good. Except the idea of getting rid of the wider key on the last line was that the dialogue could then be a bit smaller.
The key is now nicely placed, so please could the blank space at the right of the dialogue be reduced. Then I am ready to approve.

2021-08-25 10:53 UTC, shadrackkibet requested changes
I thought it will be good to review at this stage so that we can finish up.

@Gioche6 this is a good start and very promising. Keep up the good work!

Two points to note.
- Make sure you always check your changes in Visual studio and test thoroughly before you push them for review. 
- I will encourage you to write the code yourself and don't be tempted to copy-paste even if it is just text at this stage. You will be surprised how much you learn and understand the code.

2021-08-25 10:53 UTC, shadrackkibet commented on instat/ucrCalculator.vb
> +            ucrReceiverForCalculation.AddToReceiverAtCursorPosition("sum(Is.na())", 2)
Why the change? `Is.na()` is not a function in R.

2021-08-25 10:53 UTC, shadrackkibet commented on instat/ucrCalculator.vb
> +            ucrReceiverForCalculation.AddToReceiverAtCursorPosition("sum(x = , na.rm = False)", 17)
Also here `False` isn't a valid parameter value.

2021-08-25 10:53 UTC, shadrackkibet commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdUpper, "Change to upper case. For example str_to_upper("“Dr. Foster”") gives "“DR. FOSTER"”")
Also to note that there is clearly a difference in quotes between `""Dr. Foster""` and `"“Dr. Foster”"`. I guess it is because it was copied and pasted which I wouldn't encourage. Please change here and also in other places.

2021-08-31 11:26 UTC, rdstern approved these changes
Looks good now

2021-08-31 12:56 UTC, merged