Adding the pivot table to the Describe> Two Variable menu
africanmathsinitiative/R-Instat pull request #6704
Opened 2021-08-25 07:28 UTC by Ivanluv

@africanmathsinitiative/developers  this is ready for review
this fixes  #6634 and specifically for the Describe >Two Variable case.

2021-08-25 08:16 UTC, shadrackkibet commented
@HawardKetoyoMsatsi could you review the following.

2021-08-25 08:17 UTC, rdstern approved these changes
@Ivanluv this is just great.  @shadrackkibet can you check too and then we can merge.

2021-09-01 10:17 UTC, lloyddewit commented
@HawardKetoyoMsatsi Reminder: please could you review? thanks

2021-09-02 08:17 UTC, HawardKetoyoMsatsi requested changes
Do we have to do frmMain changes on the same PR? I don't see any problem with this, but I think according to what is required from R-Instat developers is the frmMain changes are done on a separate PR then merged quickly. 


I get this error when I try to either 
1.  when I try to enter a value in the receiver `Initial Row factor:` and the multiple receiver while the receiver` Initial Column factor:` is still empty.
3. delete an entry I have made in the receiver Initial Column factor while there is a value in the receivers `Initial Row factor:` and the multiple receiver 

![image](https://user-images.githubusercontent.com/16137042/131806970-3a1d60bc-7e06-4ca3-9674-9160070177e7.png)

2021-09-02 09:08 UTC, Ivanluv commented
@HawardKetoyoMsatsi could you check this again

2021-09-02 09:29 UTC, HawardKetoyoMsatsi commented
Yes, I see everything is fixed.
@shadrackkibet @lloyddewit  over to you.

2021-09-06 11:06 UTC, maxwellfundi commented
@lloyddewit  Please review this. I would like to reduce the ready PRs.

2021-09-06 11:06 UTC, lloyddewit requested changes

2021-09-06 11:06 UTC, lloyddewit commented on instat/dlgPivotTable.vb
> +                    If strItem <> ucrReceiverInitialRowFactor.GetVariableNames(bWithQuotes:=False) AndAlso strItem <> ucrReceiverInitialColumnFactor.GetVariableNames(bWithQuotes:=False) Then
In the lines above, before we call `GetVariableNamesList`, we check that the receiver is not empty. Should we do similar checks before executing these lines?

2021-09-06 11:06 UTC, lloyddewit commented on instat/dlgPivotTable.vb
> +                Dim iCount As Integer = 2
This variable is only used in the `For` loop. Move this declaration to just before the `For` loop?

2021-09-06 14:21 UTC, Ivanluv commented on instat/dlgPivotTable.vb
> +                    If strItem <> ucrReceiverInitialRowFactor.GetVariableNames(bWithQuotes:=False) AndAlso strItem <> ucrReceiverInitialColumnFactor.GetVariableNames(bWithQuotes:=False) Then
I don't think it will make much difference because The `for `loop wont execute when the list of columns in the receiver ie`ucrReceiverSelectedVariable.GetVariableNamesList(bWithQuotes:=False)` will be empty

2021-09-06 14:28 UTC, Ivanluv commented on instat/dlgPivotTable.vb
> +                Dim iCount As Integer = 2
After adding the 'happy path keeps left' principle ' this will be okay

2021-09-06 14:43 UTC, Ivanluv commented
@lloyddewit  could you look at this again

2021-09-06 15:26 UTC, lloyddewit commented on instat/dlgPivotTable.vb
> +                    If strItem <> ucrReceiverInitialRowFactor.GetVariableNames(bWithQuotes:=False) AndAlso strItem <> ucrReceiverInitialColumnFactor.GetVariableNames(bWithQuotes:=False) Then
`ucrReceiverInitialColumnFactor.GetVariableNames` is also called on line 188, and this is not part of the loop condition.
Could this potentially trigger an exception?

2021-09-07 08:46 UTC, lloyddewit commented on instat/dlgPivotTable.vb
> +                    If strItem <> ucrReceiverInitialRowFactor.GetVariableNames(bWithQuotes:=False) AndAlso strItem <> ucrReceiverInitialColumnFactor.GetVariableNames(bWithQuotes:=False) Then
@Ivanluv thanks for explaining on Skype, this comment is now resolved

2021-09-07 08:46 UTC, lloyddewit approved these changes

2021-09-07 08:49 UTC, lloyddewit commented
@rdstern There are some small changes since your last review, these should not have affected the functionality. Please could you test/approve again? thanks

2021-09-07 09:28 UTC, rdstern approved these changes
@lloyddewit and @lloyddewit great.

2021-09-07 09:53 UTC, merged