Refactoring the Recode Numeric dialogue
africanmathsinitiative/R-Instat pull request #6709
Opened 2021-08-31 13:48 UTC by Ivanluv

fixes #6472
@africanmathsinitiative/developers  this is ready for review

2021-08-31 17:14 UTC, rdstern requested changes
Has this been tested before.  I get the "usual" developer error when going into the dialogue - each time.
Apart from that, it seems to work ok.
It is a good example for an intern to investigate and possibly improve further.  It isn't an easy dialogue to use - and it is useful!
So, once the developer error is sorted, then could this be merged, and a new issue be made.  This would be to evaluate improving the dialogue.  This could be just by adding tooltips, or by adding extra options, or by considering using the cut2 function from Hmisc instead.  
I am happy to write this new issue.

2021-09-01 08:26 UTC, Ivanluv commented
@rdstern  the developer error is fixed

2021-09-01 08:31 UTC, rdstern approved these changes
Great

2021-09-01 10:15 UTC, lloyddewit commented
@N-thony Please could you review? thanks

2021-09-06 11:46 UTC, N-thony requested changes

2021-09-06 11:46 UTC, N-thony commented on instat/dlgRecodeNumeric.vb
> +            clsCutFunction.RemoveParameterByName("labels")
This parameter is removed here but there is no place that is added.

2021-09-06 12:08 UTC, Ivanluv commented on instat/dlgRecodeNumeric.vb
> +            clsCutFunction.RemoveParameterByName("labels")
it's is done on line 147

2021-09-06 12:58 UTC, N-thony commented on instat/dlgRecodeNumeric.vb
> +                If (ucrMultipleNumericRecode.clsRList.clsParameters.Count > 1 AndAlso (Not ucrInputMultipleLabels.clsRList.clsParameters.Count <> ucrMultipleNumericRecode.clsRList.clsParameters.Count
If (ucrMultipleNumericRecode.clsRList.clsParameters.Count > 1 AndAlso (Not ucrInputMultipleLabels.clsRList.clsParameters.Count <> ucrMultipleNumericRecode.clsRList.clsParameters.Count - 1)) OrElse (ucrMultipleNumericRecode.clsRList.clsParameters.Count = 1 AndAlso Integer.TryParse(ucrMultipleNumericRecode.clsRList.clsParameters(0).strArgumentValue, Nothing) AndAlso isNothing(ucrInputMultipleLabels.clsRList.clsParameters.Count)) Then

and no need to declare iTemp?

2021-09-07 08:50 UTC, Ivanluv commented on instat/dlgRecodeNumeric.vb
> +                If (ucrMultipleNumericRecode.clsRList.clsParameters.Count > 1 AndAlso (Not ucrInputMultipleLabels.clsRList.clsParameters.Count <> ucrMultipleNumericRecode.clsRList.clsParameters.Count
@N-thony  that's used to parse  each  `Rparameter's ``strArgumentValue `  
 in `ucrMultipleNumericRecode.clsRList `to integers

2021-09-07 09:41 UTC, N-thony commented on instat/dlgRecodeNumeric.vb
> +                If (ucrMultipleNumericRecode.clsRList.clsParameters.Count > 1 AndAlso (Not ucrInputMultipleLabels.clsRList.clsParameters.Count <> ucrMultipleNumericRecode.clsRList.clsParameters.Count
That is also good. Over to you @lloyddewit.

2021-09-07 12:29 UTC, lloyddewit requested changes

2021-09-07 12:29 UTC, lloyddewit commented on instat/dlgRecodeNumeric.vb
> +    Private Sub SetDefaults()
```suggestion

    Private Sub SetDefaults()
```

2021-09-07 12:30 UTC, lloyddewit submitted a review, later dismissed

2021-09-07 12:31 UTC, lloyddewit commented
@rdstern Please could you retest and approve? thanks

2021-09-20 17:19 UTC, rdstern submitted a review, later dismissed

2021-09-27 09:27 UTC, lloyddewit approved these changes

2021-09-27 09:29 UTC, lloyddewit commented
@rdstern I had to resolve a merge conflict in this PR. Please could you approve again so we can merge? Thanks

2021-09-27 11:47 UTC, rdstern approved these changes

2021-09-27 11:52 UTC, merged