Fixed the copy Row names into column issue
africanmathsinitiative/R-Instat pull request #6725
Opened 2021-09-06 15:41 UTC by Gioche6

Fixes issue #6684 

@africanmathsinitiative/developers , this is ready for review

The saving control was set as a text instead of a combo. I have fixed the issue and resized the dialog.

@rdstern , @Patowhiz , This is ready for review

2021-09-06 18:29 UTC, lloyddewit approved these changes

2021-09-06 18:30 UTC, lloyddewit commented
@rdstern Please can you test? thanks
(or one of the test team could test?)

2021-09-08 05:53 UTC, rdstern requested changes
I suggest a trivial change.  The default name is row_names.  Could we just call it row instead.  
 The reason is that the name is currently row_names(C) as it is a character variable.  But you don't see the C, in the spreadsheet.  With the shorter name you will.
I would still prefer row as the default name, but a more complex change could be to make the resulting variable numeric if the contents is the row number - which it usually is!

2021-09-08 07:49 UTC, Patowhiz commented
> I suggest a trivial change. The default name is row_names. Could we just call it row instead.
> The reason is that the name is currently row_names(C) as it is a character variable. But you don't see the C, in the spreadsheet. With the shorter name you will.

@rdstern, @Gioche6 will do the above in this PR.

> I would still prefer row as the default name, but a more complex change could be to make the resulting variable numeric if the contents is the row number - which it usually is!

@rdstern do you want us to prioritise the above in this code sprint? 
@Gioche6 create another issue from the above @rdstern comment. I thinks its best for to do it in a separate PR.

2021-09-08 07:50 UTC, Patowhiz commented
> I suggest a trivial change. The default name is row_names. Could we just call it row instead.
> The reason is that the name is currently row_names(C) as it is a character variable. But you don't see the C, in the spreadsheet. With the shorter name you will.

@rdstern, @Gioche6 will do the above in this PR.

> I would still prefer row as the default name, but a more complex change could be to make the resulting variable numeric if the contents is the row number - which it usually is!

@rdstern do you want us to prioritise the above in this code sprint? 
@Gioche6 create another issue from the above @rdstern comment. I thinks its best for to do it in a separate PR.

2021-09-08 08:27 UTC, lloyddewit approved these changes

2021-09-08 08:27 UTC, lloyddewit commented
@rdstern If you test/approve, then we can merge, thanks

2021-09-20 16:07 UTC, rdstern submitted a review, later dismissed

2021-09-20 17:36 UTC, Gioche6 commented
@rdstern  and @lloyddewit , I have fixed the merging conflict error that had appeared . This is ready for reviewing and merging.

2021-09-20 17:46 UTC, rdstern approved these changes

2021-09-22 05:16 UTC, Patowhiz commented
@rdstern, this looks good on my side. Ready for your review.

2021-09-22 07:06 UTC, shadrackkibet approved these changes
Minor comments. Either way, I approve and merge.

2021-09-22 07:06 UTC, shadrackkibet commented on instat/dlgRownamesOrNumbers.vb
>          ucrNewColumnName.SetLabelText("Column Name:")
Something to discuss and agree on and use consistently. Do we use `Column Name:` or `New Column Name:`?

2021-09-22 07:06 UTC, shadrackkibet commented on instat/dlgRownamesOrNumbers.vb
> +        ucrNewColumnName.SetPrefix("row")
`row_names` sounded much more appropriate to me.

2021-09-22 07:13 UTC, merged