Enabled new data frame dialog to 'try' running multiple lines
africanmathsinitiative/R-Instat pull request #6733
Opened 2021-09-07 10:40 UTC by Patowhiz

Fixes #6692
@africanmathsinitiative/developers this is ready for review.

@lloyddewit changes to the R link could be used to refactor code used in the script window. The functions added could also potentially be used in the new script dialog.
I also made the dialog to use the custom try control, this prompted me to enhance the custom try control.

2021-09-07 12:38 UTC, lloyddewit commented
@rdstern I suggest you first test, then I'll peer review, thanks

2021-09-07 12:49 UTC, rdstern requested changes
@Patowhiz I tried different examples and the Jane Austen one in #6692 still doesn't work.  It does if the main part is put onto a single line.  That's as before.

2021-09-07 15:48 UTC, rdstern submitted a review, later dismissed
@Patowhiz great it now works.  I hope @lloyddewit finds it ok too.
I did find that Try said it wouldn't work!  That's for the complicated example that is mentioned in the issue.  I persisted and it worked fine

2021-09-07 18:31 UTC, Patowhiz commented
@rdstern yes, the _try_ is currently set up to be a bit more restrictive for commands that create a new data frame, partly because of the limitations of the R.Net engine. All you have to do for the 'complex' sample code is remove the extra assignment(we can relax this restriction and make it consistent with _OK_  behavior).

@lloyddewit this is ready for you. Please note that additional changes that may require your attention tend to reformat the script code sent to the R.Net engine. I did this to ensure consistency and reliability in runnable commands being executed by the engine. I have demonstrated the reformatting to @rdstern.

Below is an example of how a script is reformatted;
From
```
text <- c("Because I could not stop for Death -",
          "He kindly stopped for me -",
          "The Carriage held but just Ourselves -",
          "and Immortality")
library(dplyr)
tibble(line = 1:4, text = text)
```

To 

```
text <- c("Because I could not stop for Death -","He kindly stopped for me -","The Carriage held but just Ourselves -","and Immortality")
library(dplyr)
data <- tibble(line = 1:4, text = text)
```

2021-09-08 10:54 UTC, lloyddewit submitted a review, later dismissed
@Patowhiz This all looks very good, I just pushed a couple of small changes to the XML headers, I hope that's OK

2021-09-08 10:54 UTC, lloyddewit commented on instat/ucrTry.vb
> +                            'don't break the if, we probably want to loop through to the last command checking validity?
In my view, if a command line fails then we don't need to continue. Therefore, I think it's OK to break the 'If' when a command line fails.

2021-09-08 10:54 UTC, lloyddewit commented on instat/clsRLink.vb
> +    ''' the command lines returned are re-formatted in a format that the R.Net engine can execute
```suggestion
    ''' Extracts all the complete runnable R commands from <paramref name="strScript"/>.
    ''' The command lines returned are re-formatted in a format that the R.Net engine can execute.
```

2021-09-08 10:54 UTC, lloyddewit commented on instat/clsRLink.vb
> +    ''' checks if the script passed is complete valid R script that can be run without an error
```suggestion
    ''' checks if <paramref name="strNewScript"/> is complete valid R script that can be run without an error
```

2021-09-08 10:57 UTC, lloyddewit commented
@rdstern There are no functional changes, please could you approve again? we can then merge, thanks

2021-09-08 11:30 UTC, rdstern approved these changes

2021-09-08 12:20 UTC, lloyddewit approved these changes

2021-09-08 12:21 UTC, merged

2021-09-10 06:58 UTC, Patowhiz commented on instat/ucrTry.vb
> +                            'don't break the if, we probably want to loop through to the last command checking validity?
@lloyddewit if so then we should only be checking for `Nothing` not length. Some commands return results of `Length = 0`

2021-09-10 10:26 UTC, lloyddewit commented on instat/ucrTry.vb
> +                            'don't break the if, we probably want to loop through to the last command checking validity?
@Patowhiz It's also a bit strange that we may set `bValid` to false, and then set it back to true with the next iteration of the loop.
Should we delete lines 138-142? Should we do this in a seprate PR?