Improving dlgStack
africanmathsinitiative/R-Instat pull request #6747
Opened 2021-09-08 14:31 UTC by Vitalis95

Fixes #6687  @rdstern @shadrackkibet @lloyddewit This is now ready for review.

2021-09-08 15:35 UTC, rdstern requested changes
@Vitalis95 this is great.  It works already!  I am not used to that.
One minor change is to restrict the single variable to just receive character-type variables.  I tried with others and it gives an error.  Then I think it can be merged.

2021-09-09 06:20 UTC, Vitalis95 commented
@rdstern  could you have a look at this again

2021-09-09 06:32 UTC, rdstern commented
Thanks @Vitalis95 - will do

2021-09-09 06:39 UTC, rdstern submitted a review, later dismissed
Looks very good!
So I have approved.  Let's see what @lloyddewit or @shadrackkibet thinks.  It would be great for this to be merged soon.

2021-09-09 08:34 UTC, shadrackkibet reviewed
@Vitalis95 this is a good start! I just have a few comments. Please work with @Ivanluv to resolve them. I will also be around to support you.

2021-09-09 08:34 UTC, shadrackkibet commented on instat/dlgStack.vb
> +        dctToken.Add("ptb", Chr(34) & "ptb" & Chr(34))
Use `Penn treebank` as the key here.

2021-09-09 08:34 UTC, shadrackkibet commented on instat/dlgStack.vb
> +        dctToken.Add("character_shingles", Chr(34) & "character_shingles" & Chr(34))
Use `Character shingles` as a key. Also, make sure the first letter is CAPITALISED in all cases.

2021-09-09 08:34 UTC, shadrackkibet commented on instat/dlgStack.vb
> +        dctFormat.Add("xml", Chr(34) & "xml" & Chr(34))
Same case here

2021-09-09 08:34 UTC, shadrackkibet commented on instat/dlgStack.vb
> +            If ucrChkCarryColumns.Checked Then
`AndAlso`?

2021-09-09 08:34 UTC, shadrackkibet commented on instat/dlgStack.vb
> +            End If
Do we really need a loop? This are just columns added into select function which could be done via setRcode.

2021-09-09 08:34 UTC, shadrackkibet commented on instat/dlgStack.vb
> +        clsSelectFunction.SetRCommand("select")
`SetPackageName`?

2021-09-09 08:34 UTC, shadrackkibet commented on instat/dlgStack.vb
> +        ucrReceiverColumnsToCarry.SetParameter(New RParameter("id.vars", 1))
Check the parameter name to use?

2021-09-09 09:39 UTC, Vitalis95 commented
@shadrackkibet please have a look at it.

2021-09-09 10:01 UTC, shadrackkibet commented on instat/dlgStack.vb
> +            End If
@Ivanluv if this sounds a bit complicated could you just make sure that these parameters are removed?

2021-09-09 12:34 UTC, rdstern approved these changes
Still seems fine to me

2021-09-09 14:56 UTC, lloyddewit commented
@shadrackkibet I see that you already reviewed this PR - Thank you! Please could you also do the final review and merge? thanks

2021-09-09 16:14 UTC, shadrackkibet approved these changes

2021-09-09 16:14 UTC, merged