Added reorder feature + minor bug fixes to the bar chart dialogue
africanmathsinitiative/R-Instat pull request #6750
Opened 2021-09-09 09:47 UTC by N-thony

Fixes #6582
@rdstern please have a look. Thanks.

2021-09-09 11:41 UTC, rdstern requested changes
@N-thony that is ok for the data option.  You can also do it for the frequency option.  It uses a slightly different function from forcats as explained in the new issue you are looking at.  (forcats is very powerful!)
I am confused about the label and also the position on the dialogue.  I was assuming it would go on the right, perhaps under the factor that it corresponds to.  Possibly just Reorder, but I am not sure now.  Once implemented for both options I suggest we merge and then discuss further.  I would then like to get @shadrackkibet view on this.

2021-09-09 13:26 UTC, N-thony commented
> @N-thony that is ok for the data option. You can also do it for the frequency option. It uses a slightly different function from forcats as explained in the new issue you are looking at. (forcats is very powerful!)
> I am confused about the label and also the position on the dialogue. I was assuming it would go on the right, perhaps under the factor that it corresponds to. Possibly just Reorder, but I am not sure now. Once implemented for both options I suggest we merge and then discuss further. I would then like to get @shadrackkibet view on this.

@rdstern Please have a look.

2021-09-09 14:40 UTC, N-thony commented
> > @N-thony that is ok for the data option. You can also do it for the frequency option. It uses a slightly different function from forcats as explained in the new issue you are looking at. (forcats is very powerful!)
> > I am confused about the label and also the position on the dialogue. I was assuming it would go on the right, perhaps under the factor that it corresponds to. Possibly just Reorder, but I am not sure now. Once implemented for both options I suggest we merge and then discuss further. I would then like to get @shadrackkibet view on this.
> 
> @rdstern Please have a look. There is a small issue for the frequency option that will good for me to fix after the quick chat with you.

I think reorder function requires x and y variables, that is why in my previous change I made it available only for the value option. Let me know if I'm wrong so that I can fix it quickly with your suggestion. Thanks.

2021-09-10 08:51 UTC, N-thony commented
@rdstern from our chat this moring, I made the first change by using forcats package. Please have a look and let me know on the next step.

2021-09-10 10:29 UTC, rdstern requested changes
@N-thony it is getting there, but only slowly!  
You are now correctly using infreq for the frequency option.  But you are also now using it for the data option, where you were fine before.  There it should be by the variable.
On the position, please move the control up, so it is clearly associated with the first variable

Then add the same code for the second factor, when it is used.

2021-09-10 12:00 UTC, N-thony commented
> @N-thony it is getting there, but only slowly!
> You are now correctly using infreq for the frequency option. But you are also now using it for the data option, where you were fine before. There it should be by the variable.
> On the position, please move the control up, so it is clearly associated with the first variable
> 
> Then add the same code for the second factor, when it is used.

@rdstern please have a look.

2021-09-14 06:58 UTC, rdstern approved these changes
I am ok with this now.  It is an obvious dialogue for a check also by @shadrackkibet

2021-09-16 17:44 UTC, shadrackkibet requested changes

2021-09-16 17:44 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +        ucrReceiverX.SetParameterIsRFunction()
But we do not need it as an Rfunction when it is an aesthetic?

2021-09-16 17:44 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +                    clsReorderFunction.AddParameter("y", ucrVariablesAsFactorForBarChart.GetVariableNames(False), iPosition:=1, bIncludeArgumentName:=0)
- Use the correct parameters. In this case, it should be `x`? 
- What does ` bIncludeArgumentName:=0` mean? 
Check other places as well.

2021-09-17 12:11 UTC, shadrackkibet commented
@rdstern I don't like the default x-axis labels when you reorder. It is much presentable if we have the variable name. You could change it by going the subdialog but wouldn't be nice to retain it by default? 
![image](https://user-images.githubusercontent.com/26301973/133772784-1269d505-41dc-401c-952c-eed09ccb1c25.png)
I also feel like we could improve on the design of this dialog. Perhaps a group box will look nice?
![IMG_20210917_150241_395](https://user-images.githubusercontent.com/26301973/133780565-117ba912-30b7-493e-b56d-865e583dbcc3.jpg)

2021-09-17 12:42 UTC, N-thony commented
> @rdstern I don't like the default x-axis labels when you reorder. It is much presentable if we have the variable name. You could change it by going the subdialog but wouldn't be nice to retain it by default?
> ![image](https://user-images.githubusercontent.com/26301973/133772784-1269d505-41dc-401c-952c-eed09ccb1c25.png)
> I also feel like we could improve on the design of this dialog. Perhaps a group box will look nice?
> ![IMG_20210917_150241_395](https://user-images.githubusercontent.com/26301973/133780565-117ba912-30b7-493e-b56d-865e583dbcc3.jpg)

@shadrackkibet I agree with you about adding the possibility of renaming the x-axis labels. Aslo, the improvement of the design looks interesting but from your screenshot above I can't see all the options controls in the groupbox. If @rdstern agree with that I will make the change. Thanks.

2021-09-17 14:14 UTC, rdstern commented
I would be happy with a redesign of this dialogue.  We currently also have 2 possible sorts, but they are not x and y.  They are the instance of having 2 x variables.  If that is confusing I am happy that we just have one - the main x.  @N-thony is improving the main reorder dialogue, so we can always reorder before doing the graph.  

Remember there are also lollipop graphs.  So there is quite a lot to show if everything is in a group box on the left-hand side.

You also criticize - correctly 0 the "interesting" variable titles.  I have no problem going back to the names.  I would also like to geo 2 steps further.  First I would like the option to use variable labels as well as the name.  This seems to be described with a vignette from the [expss package here](https://cran.r-project.org/web/packages/expss/vignettes/labels-support.html)

I have a slightly different suggestion on these titles for your consideration.  This is as follows:
a) We have a `Titles` button on each of the plotting dialogues.  This takes you straight to the Titles tab in the sub-dialogue.
b) Currently that tab just has the 3 main titles.  (Title, sub-title and Caption.  The x-axis and y axis titles are on different (and rather crowded tab s).  So move the x-axis titles and y-axiss titles to this Titles tab.

2021-09-21 12:51 UTC, N-thony commented
@rdstern we discussed about this recently and agreed that we can keep it as it is for now. Or would you like me to go ahead with the changes you suggested above and the redesign?

2021-09-21 15:55 UTC, rdstern submitted a review, later dismissed
@N-thony and @shadrackkibet I would be happy to merge now and then consider further improvements later.

2021-09-22 06:57 UTC, shadrackkibet requested changes

2021-09-22 06:57 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +        ucrReceiverX.AddAdditionalCodeParameterPair(clsReorderFunction, New RParameter("x", 0, bNewIncludeArgumentName:=False), iAdditionalPairNo:=1)
The parameters are still hidden for no reason? Same case in line 581, 592?

2021-09-22 06:57 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +        End If
Can we make it a bit clean and easy to read? Perhaps nest the `if` statements? eg
```
  If rdoFrequency.Checked Then
            ucrChkLollipop.Checked = False
            If ucrVariablesAsFactorForBarChart.bSingleVariable Then
                ucrInputReorderX.Visible = True
            Else
                ucrInputReorderX.Visible = False
                ucrInputReorderX.SetText(strNone)
            End If
  Else
            If ucrVariablesAsFactorForBarChart.bSingleVariable Then
                ucrInputReorderValue.Visible = True
            Else
                ucrInputReorderValue.Visible = False
                ucrInputReorderValue.SetText(strNone)
            End If
 End If
```
What do you think?

2021-09-22 08:11 UTC, N-thony commented
@shadrackkibet please have a look. Thanks.

2021-09-23 07:32 UTC, shadrackkibet commented
@rdstern please retest and approve. Functionality shouldn't be affected.

2021-09-23 07:49 UTC, rdstern approved these changes

2021-09-23 07:53 UTC, shadrackkibet approved these changes

2021-09-23 07:53 UTC, merged