Minor improvements to the pivot table dialog
africanmathsinitiative/R-Instat pull request #6757
Opened 2021-09-10 08:43 UTC by Vitalis95

@mmulahvictor and I fixed this issues.
This fixes the improvement issues: row variable be changed to multiple receiver and OK be enabled in the dialogue without having to input either the rows or columns raised on #6634 
@rdstern could you have a look at it

2021-09-10 10:42 UTC, rdstern requested changes
One very minor point.  Ok is now enabled even when there is no data frame in the file.  
There does not need to be a variable, but there should be a current data frame, before Ok is enabled.

The multiple row factors works fine.  Nice!

2021-09-10 11:47 UTC, Vitalis95 commented
@rdstern  please have a look at it again

2021-09-10 16:43 UTC, rdstern approved these changes
Great

2021-09-12 07:38 UTC, lloyddewit requested changes
@Vitalis95 This looks really good, just a couple of small suggestions

2021-09-12 07:38 UTC, lloyddewit commented on instat/dlgPivotTable.vb
> +        If ucrSavePivot.IsComplete AndAlso ucrSelectorPivot.ucrAvailableDataFrames.cboAvailableDataFrames.Text <> "" Then
Is this safer?
```suggestion
        If ucrSavePivot.IsComplete AndAlso Not String.IsNullOrEmpty(ucrSelectorPivot.ucrAvailableDataFrames.cboAvailableDataFrames.Text) Then
```

2021-09-12 07:38 UTC, lloyddewit commented on instat/dlgPivotTable.vb
> +
Remove?
```suggestion
```

2021-09-14 07:39 UTC, lloyddewit approved these changes

2021-09-14 07:40 UTC, lloyddewit commented
@rdstern Just a couple of small changes since your last approval that should not have affected functionality. Please could you approve again? thanks

2021-09-14 07:53 UTC, rdstern approved these changes

2021-09-14 08:15 UTC, merged