Adding Squish to the Transform Text Dialog
africanmathsinitiative/R-Instat pull request #6763
Opened 2021-09-13 11:33 UTC by Gioche6

Fixes issue #6705 

@africanmathsinitiative/developers , This is ready for review. 

@rdstern, I have added the squish radio button as requested to pass the function `str_squish.` 
Additionally, with the help of @Ivanluv , we have refactored the codes.

2021-09-14 07:43 UTC, lloyddewit commented
@Ivanluv Please could you peer review?
@rdstern Please could you test?
Thanks!

2021-09-20 13:07 UTC, Ivanluv commented
@rdstern  could you test this before I can review

2021-09-21 07:29 UTC, rdstern approved these changes
Over to @shadrackkibet or @lloyddewit for second aspproval and merging!

2021-09-21 07:39 UTC, shadrackkibet commented
@Ivanluv your code review is still pending? Let me know if I misunderstood.

2021-09-21 07:54 UTC, Ivanluv commented
@shadrackkibet Am reviewing it now

2021-09-21 08:02 UTC, Ivanluv commented on instat/dlgTransformText.vb
> +
could we have this as one line spacing?

2021-09-21 08:03 UTC, Ivanluv commented on instat/dlgTransformText.vb
> +
One line spacing here also

2021-09-21 08:33 UTC, Gioche6 commented on instat/dlgTransformText.vb
> +
@Ivanluv , this is done

2021-09-21 08:33 UTC, Gioche6 commented on instat/dlgTransformText.vb
> +
@Ivanluv , this is done

2021-09-21 08:40 UTC, Ivanluv commented
This is okay from my end. Over to you @lloyddewit

2021-09-27 06:07 UTC, Gioche6 commented
@rdstern , @lloyddewit , This PR is all ready for review and merging.

2021-09-27 08:36 UTC, lloyddewit requested changes
@Gioche6 Thanks, you implemented this very cleanly and it looks good.
I just had a couple of small suggestions.
We can then merge.

2021-09-27 08:36 UTC, lloyddewit commented on instat/dlgTransformText.vb
> +        ElseIf ucrChkLastOr.Checked AndAlso ucrChangedControl Is ucrChkFirstOr Then
Is this more readable if we make it consistent with the other conditions?
```suggestion
        ElseIf ucrChangedControl Is ucrChkFirstOr AndAlso ucrChkLastOr.Checked Then
```

2021-09-27 08:36 UTC, lloyddewit commented on instat/dlgTransformText.vb
> +        End If
Is it more readable if we follow the 'happy path stays left' principle?
```suggestion
        If Not rdoTrim.Checked Then
            Exit Sub
        End If

        If rdoSquish.Checked Then
            clsSquishTrimFunction.SetRCommand("str_squish")
            clsSquishTrimFunction.RemoveParameterByName("side")
        Else
            clsSquishTrimFunction.SetRCommand("str_trim")
            If rdoLeftPad.Checked Then
                clsSquishTrimFunction.AddParameter("side", Chr(34) & "left" & Chr(34), iPosition:=2)
            ElseIf rdoRightPad.Checked Then
                clsSquishTrimFunction.AddParameter("side", Chr(34) & "right" & Chr(34), iPosition:=2)
            ElseIf rdoBothPad.Checked Then
                clsSquishTrimFunction.AddParameter("side", Chr(34) & "both" & Chr(34), iPosition:=2)
            End If
        End If
```

2021-09-27 09:04 UTC, Gioche6 commented
@lloyddewit , Thankyou for the thoughtful suggestion. I have gone through them and I feel they are great. I have also been implemented now.

2021-09-27 09:15 UTC, lloyddewit approved these changes

2021-09-27 09:17 UTC, lloyddewit commented
@rdstern since your last approval, there are just a couple of small changes that should not have affected the functionality. Please could you approve again? We can then merge.
Thanks

2021-09-27 09:19 UTC, rdstern approved these changes

2021-09-27 10:03 UTC, merged