Add shape button to the heat map dialogue
africanmathsinitiative/R-Instat pull request #6766
Opened 2021-09-14 07:00 UTC by EstherNjeriLiberatta

@africanmathsinitiative/developers @rdstern @shadrackkibet @fran2or 
This is ready for review.

2021-09-14 08:07 UTC, lloyddewit commented
@N-thony Please could you peer review? thanks

2021-09-14 08:43 UTC, N-thony requested changes

2021-09-14 08:43 UTC, N-thony commented on instat/dlgRugPlot.vb
> +        ucrReceiverShape.AddAdditionalCodeParameterPair(clsShapeAes, New RParameter("size", 2), iAdditionalPairNo:=1)
Set the position to New RParameter("size", 0)

2021-09-14 08:43 UTC, N-thony commented on instat/dlgRugPlot.vb
> +        clsShapeFunction.AddParameter("mapping", clsRFunctionParameter:=clsShapeAes, iPosition:=1)
set iPosition = 0?

2021-09-14 08:43 UTC, N-thony commented on instat/dlgRugPlot.vb
> +        ucrReceiverShape.AddParameterPresentCondition(False, "geom_point", False)
Move these after line 100

2021-09-14 08:43 UTC, N-thony commented on instat/dlgRugPlot.vb
> +    Private Sub AllControlsContentsChanged() Handles ucrReceiverX.ControlContentsChanged, ucrSaveGraph.ControlContentsChanged, ucrVariableAsFactorForHeatMap.ControlContentsChanged, ucrChkAddLabels.Co
ucrChkColourPalette.ControlContentsChanged, ucrReceiverShape.ControlContentsChanged removed? since they are not in the sub TestOkEnabled

2021-09-14 09:20 UTC, EstherNjeriLiberatta commented on instat/dlgRugPlot.vb
> +    Private Sub AllControlsContentsChanged() Handles ucrReceiverX.ControlContentsChanged, ucrSaveGraph.ControlContentsChanged, ucrVariableAsFactorForHeatMap.ControlContentsChanged, ucrChkAddLabels.Co
Hello @N-thony, I've made the changes you have requested.

2021-09-14 10:51 UTC, N-thony commented on instat/dlgRugPlot.vb
> +    Private Sub AllControlsContentsChanged() Handles ucrReceiverX.ControlContentsChanged, ucrSaveGraph.ControlContentsChanged, ucrVariableAsFactorForHeatMap.ControlContentsChanged, ucrChkAddLabels.Co
@lloyddewit over to you.

2021-09-14 15:37 UTC, rdstern commented
![image](https://user-images.githubusercontent.com/11226469/133288102-3ace9bce-7af0-42fc-821f-abb1410f722b.png)

I am unconvinced by the extra value of this shape control.  It is just adding a point of varying size in the middle of each cell.  It isn't an extra I am very familiar with, in a heatmap.  Is this common?  If so, then we probably need more options, or we call it a size option, because there is only a single shape - namely a circle!

2021-09-14 18:53 UTC, fran2or commented
> ![image](https://user-images.githubusercontent.com/11226469/133288102-3ace9bce-7af0-42fc-821f-abb1410f722b.png)
> 
> I am unconvinced by the extra value of this shape control. It is just adding a point of varying size in the middle of each cell. It isn't an extra I am very familiar with, in a heatmap. Is this common? If so, then we probably need more options, or we call it a size option, because there is only a single shape - namely a circle!

@rdstern  I think you are right that the shape type and size feature is not common with heatmaps, however I think having it as an option (dialog should still work without it being checked or filled ) may be useful when people want to look at two measurements together (eg. yield and fertilizer amount - this is the single shape with  varying size). Another example which may make use of the type of shape could be yield (heatmap) and grouped fertilizer amounts (different shapes representing varied categories of  fertilizer amount groups).

2021-09-15 08:09 UTC, fran2or commented
Having discussed with @rdstern, he now agrees that this is a very useful addition.  Could you kindly change the label for that control from Shape to Points (Optional):  It should also detect whether the extra variable is numeric or a factor.  If factor, it uses different shapes and if numeric it uses different sizes.  Also please tell @shadrackkibet  that an extra geom is being used, for when he alters to Options button.

2021-09-15 12:58 UTC, EstherNjeriLiberatta commented
Hello @rdstern @shadrackkibet @fran2or, this is ready for review.

2021-09-16 07:29 UTC, EstherNjeriLiberatta commented
Hello @africanmathsinitiative/developers, This is ready for review.
@rdstern @shadrackkibet @fran2or, I have made the requested suggestions on the shape receiver.

2021-09-16 17:22 UTC, shadrackkibet requested changes

2021-09-16 17:22 UTC, shadrackkibet commented on instat/dlgRugPlot.vb
> +        clsGeomPointShapeFunction.AddParameter("mapping", clsRFunctionParameter:=clsShapeAes, iPosition:=0)
Only one `geom_point` and `aes` function should be enough. You only need to change `aes` parameters depending on the variable in the receiver. Does this make sense to you? If this complicates things for you then it is not worth it.

2021-09-16 17:26 UTC, shadrackkibet commented
@EstherNjeriLiberatta your design looks clean and controls are well aligned. I like it! 

Could you also make sure that the Tab order is sorted? Ask if you are not sure what that means.

2021-09-16 17:28 UTC, shadrackkibet commented
> Having discussed with @rdstern, he now agrees that this is a very useful addition. Could you kindly change the label for that control from Shape to Points (Optional): It should also detect whether the extra variable is numeric or a factor. If factor, it uses different shapes and if numeric it uses different sizes. Also please tell @shadrackkibet that an extra geom is being used, for when he alters to Options button.

@fran2or thanks for the alert. Well noted!

2021-09-16 17:37 UTC, EstherNjeriLiberatta commented on instat/dlgRugPlot.vb
> +        clsGeomPointShapeFunction.AddParameter("mapping", clsRFunctionParameter:=clsShapeAes, iPosition:=0)
@shadrackkibet Thank you for the corrections.

2021-09-16 17:54 UTC, EstherNjeriLiberatta commented on instat/dlgRugPlot.vb
> +        clsGeomPointShapeFunction.AddParameter("mapping", clsRFunctionParameter:=clsShapeAes, iPosition:=0)
It was quite confusing adding and removing parameters to the function so I decided to define more functions. If it is okay with you, please allow me to use the functions as I have them for now.

2021-09-16 17:58 UTC, shadrackkibet commented on instat/dlgRugPlot.vb
> +        clsGeomPointShapeFunction.AddParameter("mapping", clsRFunctionParameter:=clsShapeAes, iPosition:=0)
No problem. Let me know when you are done with other changes. I can help to sort it out.

2021-09-17 10:09 UTC, shadrackkibet commented on instat/dlgRugPlot.vb
> +        clsShapeAes.AddParameter("size", 5, iPosition:=1)
Just to add that if you are fixing size to numeric then you should add it into the `geom_point()` and not into `aes()`.

2021-09-20 06:13 UTC, EstherNjeriLiberatta commented
Hello, @rdstern @shadrackkibet This is ready for review.

2021-09-20 08:07 UTC, rdstern approved these changes
I am approving, because the only changes now are cosmetic, and I suggest there may be more later.  So, subject to @shadrackkibet or @lloyddewit it could be merged now.
a) Could change the label to simply Points (Optional):  
b) The label at the top could be changed to be Heat Map.  (It will soon change further!
c) In the special Options button, it goes to geom Tile.  So I would prefer to call it Tile Options here.

2021-09-20 08:58 UTC, lloyddewit commented
@shadrackkibet Thank you for the review you did earlier. If you're happy that all your comments are now resolved, then we can merge.

2021-09-20 10:14 UTC, shadrackkibet commented on instat/dlgRugPlot.vb
> +                    ucrNudShape.Visible = True
@lloyddewit the linking system should be improved to allow the state of the receiver as a datatype. This feature will help in such a case where linking has to be done manually.

2021-09-20 10:14 UTC, shadrackkibet approved these changes

2021-09-20 10:15 UTC, shadrackkibet commented on instat/dlgRugPlot.vb
> +        clsGeomPointShapeFunction.AddParameter("mapping", clsRFunctionParameter:=clsShapeAes, iPosition:=0)
Not done. But I will merge since this doesn't affect functionality.

2021-09-20 10:16 UTC, merged

2021-09-20 10:18 UTC, shadrackkibet commented
> I am approving, because the only changes now are cosmetic, and I suggest there may be more later. So, subject to @shadrackkibet or @lloyddewit it could be merged now.
> a) Could change the label to simply Points (Optional):
> b) The label at the top could be changed to be Heat Map. (It will soon change further!
> c) In the special Options button, it goes to geom Tile. So I would prefer to call it Tile Options here.

@EstherNjeriLiberatta could you work on these changes on a separate PR?

2021-09-20 10:29 UTC, EstherNjeriLiberatta commented
@shadrackkibet yes, I'll do that.