Added selection of columns functionality
africanmathsinitiative/R-Instat pull request #6767
Opened 2021-09-14 15:07 UTC by shadrackkibet

fixes #6426

This is not yet ready for review. I will send a notification when it is ready.

2021-09-16 16:08 UTC, rdstern reviewed
@shadrackkibet great this has started.  I couldn't see where to check?  I assume eventually on Data Options, and a replacement dialogue for Prepare > Data Frame > Hide/Show?

2021-09-16 16:37 UTC, shadrackkibet commented
Let us test it from my end at this stage. I will be in touch on skype.

2021-09-24 08:41 UTC, shadrackkibet commented
@rdstern hopefully you can test now.

2021-09-24 09:21 UTC, rdstern commented
This is great - and seems to work.  Happy to imporve if you think merging at this stage will help.
What's next for you (and for others if you are bringing them in.  Here are some points from this first look:
a) Could we make it easy to have all variables of a given type, e.g. all factors, all logical? 
b) Could it say how many variables are selected.  I tried some that didn't work and got none selected.  I wonder if there should be a warning in this case.
c) I wanted to select all that start with anything and then i in the second place.  I tried .i, but it didn't work.  Could there be a fixed, or regex option in the choice?
d) In the selector the top usually says Variables.  When there is a selection, could there be perhaps simply `(select1)` after this?
e) I look forward to being able to access these from the data options.  The tabs currently say Rows Columns .  I suggest `Rows (Filter) Columns (Select)`
Very exciting!

2021-09-25 07:24 UTC, rdstern commented
A job for @dannyparsons on the R side I assume.  I am keen to encourage more use of variable labels in our use of R.  Could @dannyparsons add the feature to be able to search in other attributes as well as the name.  Then, you add a group box in the sub-dialogue It has the label Select from:  Then there are 3 options inside.   Variable name,  Variable Label, Value Label.  Variable Name is ticked by default, and the others are not.

2021-09-25 08:38 UTC, rdstern commented
@shadrackkibet could you please also add the help context number 597.  Thanks

2021-09-28 11:11 UTC, rdstern approved these changes
Good to merge if possible now.  Then there are more dimensions of the general facility to add.  
@lloyddewit could you check?

2021-09-28 19:05 UTC, lloyddewit requested changes
This looks good, I just had some small comments

2021-09-28 19:05 UTC, lloyddewit commented on instat/dlgSelectColumns.vb
> +                'End If
Delete?

2021-09-28 19:05 UTC, lloyddewit commented on instat/dlgSelectColumns.vb
> +        'ucrInputSelectOperation.AddToLinkedControls(ucrInputColumnType, {"Where"}, bNewLinkedHideIfParameterMissing:=True)
delete?

2021-09-28 19:05 UTC, lloyddewit commented on instat/dlgSelectColumns.vb
> +                '
delete?

2021-09-28 19:05 UTC, lloyddewit commented on instat/dlgSelectColumns.vb
> +    End Sub
combine these into a single handler?

2021-09-29 09:20 UTC, shadrackkibet commented on instat/dlgSelectColumns.vb
> +                'End If
I need it when we add functionality to select factors, characters etc columns. I will add a comment!

2021-09-29 09:20 UTC, shadrackkibet commented on instat/dlgSelectColumns.vb
> +        'ucrInputSelectOperation.AddToLinkedControls(ucrInputColumnType, {"Where"}, bNewLinkedHideIfParameterMissing:=True)
For the same reason as above

2021-09-29 09:21 UTC, shadrackkibet commented on instat/dlgSelectColumns.vb
> +                '
same case

2021-09-29 09:21 UTC, shadrackkibet commented on instat/dlgSelectColumns.vb
> +    End Sub
agreed

2021-09-30 10:17 UTC, lloyddewit approved these changes

2021-09-30 10:18 UTC, lloyddewit commented
@rdstern Since your last approval, there are only small changes that should not affect functionality. Please could you approve again?
We can then merge, thanks

2021-09-30 10:22 UTC, shadrackkibet commented
@lloyddewit many thanks for the reviews.

2021-10-01 08:21 UTC, shadrackkibet commented
@rdstern?

2021-10-01 09:30 UTC, rdstern approved these changes
Great to merge, so I am approving.  There are many things to improve of course - and I just noticed another one - maybe two!
a) The default iin the sub-dialogue s to select the columns and that is fine.  There is still the Data Options button, and it is active.  I am not sure it should be there!
b) When I move to the Starts, etc, then the column selector remains visible and I like that.  I'd like even to be able to scroll there?  But we should disable the Add button to indicate that the list of variables is then just for viewing.

2021-10-01 09:33 UTC, merged