Made menu item names and dialog names consistent
africanmathsinitiative/R-Instat pull request #6768
Opened 2021-09-15 09:08 UTC by Gioche6

Fixes issue #6710

@africanmathsinitiative/developers , This is ready for review
@rachelkg and @Patowhiz , I have made all the changes listed on the  [Inconsistencies between Menu and Dialog names.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7156493/Inconsistencies.between.Menu.and.Dialog.names.xlsx)

@lloyddewit , I have changed the text descriptions as recommended. However, the text is not changing in run time because of the translation issue. I think this can be merged, but the issue to remain open until the translation issue is fixed, in which,  it will automatically change.

2021-09-15 11:17 UTC, lloyddewit commented
![image](https://user-images.githubusercontent.com/57253949/133423665-059430c3-8639-4119-ac94-230e9e8b7408.png)
 @Gioche6 For consistency, please could you also correct the capitalization here (e.g. make 'Non-Numeric')? Thanks

2021-09-15 11:30 UTC, lloyddewit requested changes
@Gioche6 Thank you for the changes. I just have a couple of small suggestions. 
I also updated the database and pushed the new database to this PR. This should allow you to test your changes.
I noticed that you have merge conflicts on 'frmMain'. You may need to make a new PR for this.

2021-09-15 11:30 UTC, lloyddewit commented on instat/dlgDeleteRowsOrColums.resx
> +    <value>Delete Rows or Columns</value>
```suggestion
    <value>Delete Columns or Rows</value>
```

2021-09-16 07:40 UTC, lloyddewit commented
> 
> 
> ![image](https://user-images.githubusercontent.com/57253949/133423665-059430c3-8639-4119-ac94-230e9e8b7408.png)
> @Gioche6 For consistency, please could you also correct the capitalization here (e.g. make 'Non-Numeric')? Thanks

@Gioche6 Please could you also resolve the above? thanks

2021-09-16 08:24 UTC, Gioche6 commented
@lloyddewit , I have made the change you requested.

2021-09-16 08:32 UTC, Gioche6 commented
@lloyddewit , I have resolved to do the changes in a separate PR, since this one has merging issues.

2021-09-16 08:58 UTC, closed without merging

2021-09-16 15:12 UTC, lloyddewit commented
replaced by PR #6771