Made default (column) names consistent following tidyverse style guide
africanmathsinitiative/R-Instat pull request #6779
Opened 2021-09-20 18:45 UTC by N-thony

Fixes #6291
This is to make the default name when a dialog produces a new column/graph/model/object/data frame following tidyverse style guide column name.
@lloyddewit @dannyparsons there is no coding in this PR and this is ready to be merge. Thanks.

2021-09-22 07:32 UTC, shadrackkibet requested changes
Some suggestions

2021-09-22 07:32 UTC, shadrackkibet commented on instat/dlgExtremesClimatic.vb
> +        ucrSaveDeclusteredPlot.SetPrefix("declustred_plot")
`declustered_plot`?

2021-09-22 07:32 UTC, shadrackkibet commented on instat/dlgInfillMissingValues.vb
> +            ucrSaveNewColumn.SetPrefix("tnt_" & ucrReceiverElement.GetVariableNames(False))
`int_`

2021-09-22 07:32 UTC, shadrackkibet commented on instat/dlgOtherRosePlots.vb
> +            ucrSaveGraph.SetPrefix("polar_annulus")
Seems we always add `plot/graph`? so `polar_annulus_plot`? Same case below.

2021-09-22 07:32 UTC, shadrackkibet commented on instat/dlgParallelCoordinatePlot.vb
> +        ucrSaveGraph.SetPrefix("par_coord")
`par_coord_plot`?

2021-09-22 07:32 UTC, shadrackkibet commented on instat/dlgTaylorDiagram.vb
> +        ucrSavePlot.SetPrefix("taylor_diagram")
add `plot`

2021-09-22 07:32 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +        ucrSavePlot.SetPrefix("cond_quantile")
`conditional_quantile_plot`?

2021-09-22 07:32 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +            ucrSavePlot.SetPrefix("cond_quantile")
`conditional_quantile_plot`

2021-09-22 07:32 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +            ucrSavePlot.SetPrefix("cond_eval")
`conditional_eval_plot`

2021-09-22 07:34 UTC, shadrackkibet commented on instat/dlgConditionalQuantilePlot.vb
> +            ucrSavePlot.SetPrefix("cond_eval")
perhaps `cond_eval_plot`? is that too long?

2021-09-22 08:02 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +            ucrSavePlot.SetPrefix("cond_eval")
it is too long but the meaning is clear, I think it is okay.

2021-09-22 08:02 UTC, N-thony commented on instat/dlgConditionalQuantilePlot.vb
> +            ucrSavePlot.SetPrefix("cond_eval")
it is too long but the meaning is clear, I think it is okay.

2021-09-22 08:27 UTC, N-thony commented
@shadrackkibet I made the corrections on your above comments. please have a look. Thanks.

2021-09-23 07:54 UTC, shadrackkibet commented
@rdstern ?

2021-09-23 08:21 UTC, rdstern approved these changes

2021-09-23 10:33 UTC, shadrackkibet approved these changes

2021-09-23 10:34 UTC, merged