Changing the Control and Dialog for the Rug Plot Dialog
africanmathsinitiative/R-Instat pull request #6780
Opened 2021-09-20 19:20 UTC by EstherNjeriLiberatta

@rdstern , I have made the changes you requested according to PR #6766 

- I have changed the label for the control `Variable (Optional)` to` Points (Optional)`.
- I have changed the `Heat Map Options` control label to `Tile Options`.
- I had already renamed the dialog to `Heat Map `, however not appearing on runtime because of translation issue. 

@lloyddewit , I have made the changes by renaming the controls and the dialog, but they can't appear on the run-time because of the translation issue. Kindly resolve it so that they appear on the run-time.

2021-09-21 07:08 UTC, EstherNjeriLiberatta commented
Hello @rdstern @shadrackkibet This fixes the issue of the name of the dialog from `Rug plot` to `Heat map.`

2021-09-21 07:35 UTC, shadrackkibet commented
@EstherNjeriLiberatta I really don't understand why you have 124 files changed.

2021-09-21 07:52 UTC, EstherNjeriLiberatta commented
@shadrackkibet Changing the name from dlgRugPlot to dlgHeatMapPlot brought all these changes.

2021-09-21 08:45 UTC, shadrackkibet approved these changes

2021-09-21 08:45 UTC, shadrackkibet commented on instat/dlgMyFirstDialog.vb
> +    End Sub
Including this new dialog?

2021-09-21 08:45 UTC, shadrackkibet commented on instat/Form1.vb
> +End Class
This as well?

2021-09-21 08:48 UTC, EstherNjeriLiberatta commented on instat/dlgMyFirstDialog.vb
> +    End Sub
Ooh no, sorry. I was trying to delete that. It was the first dialog I created.

2021-09-21 08:50 UTC, EstherNjeriLiberatta commented on instat/Form1.vb
> +End Class
Ooh God, how can I undo that?

2021-09-21 09:05 UTC, EstherNjeriLiberatta commented on instat/Form1.vb
> +End Class
I was deleting it as well

2021-09-21 09:41 UTC, rdstern requested changes
@EstherNjeriLiberatta that's looking good now.  I don't see the need to repeat the word Points twice.  Perhaps get rid of the group box, because there is now just the single control inside it.  Then I have made some more major suggestions for improvements in #6665, but would like to get the dialogue merged first in its current form.

2021-09-21 09:59 UTC, EstherNjeriLiberatta commented
@rdstern Okay, I will look at it.

2021-09-21 12:20 UTC, EstherNjeriLiberatta commented
@rdstern @shadrackkibet this is ready for review.

2021-09-21 14:42 UTC, rdstern approved these changes
@EstherNjeriLiberatta this looks fine now.  I am approving in case @shadrackkibet would like to merge as it is.  But I realise that it doesn't yet work with the option to include multiple y-variables.  It can be made to work and here is the code:
'''heatmap <- data_book$get_data_frame(data_name="heatmap", stack_data=TRUE, measure.vars=c("no.input","fert.1","fert.2","organic.fert","leg.2","leg.1","leg.4","leg.5","leg.3","leg.7","leg.6"))
last_graph <- ggplot2::ggplot(data=heatmap, mapping=ggplot2::aes(x=sitefm., fill=value,y=variable)) + ggplot2::geom_tile() + theme_grey()+coord_flip()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="heatmap")
data_book$get_graphs(data_name="heatmap", graph_name="last_graph")
rm(list=c("last_graph", "heatmap"))'''

I tried with the same date I have now included.  I read in the data in the unstacked shape and can show you how if need be.. You need to do the following:
a) Allow the x to be completed, that's the other factor.
b) Put value into the fill control.  (You will see that is done  with variable in some other dialogues.
c) Generate the code where the y = variable, fill = value. as in the code above.
d) Also have a checkbox on the left with coord_flip.  Call it Swap x and y.  Generate coord_flip() when it is checked.  (You will see that on some other dialogues.

If this is too difficult for now, then we could merge as you have it.  In that case, copy this suggestion into a new issue, or combine it with the other suggestions I have made in #6665

2021-09-22 06:07 UTC, EstherNjeriLiberatta commented
@shadrackkibet Please allow me to I finish with these changes.

2021-09-23 09:22 UTC, EstherNjeriLiberatta commented
Hello @shadrackkibet I realised I need more time to work on these changes, please could you merge this. I'll add it as a new issue.

2021-09-23 10:15 UTC, shadrackkibet commented
@EstherNjeriLiberatta thanks for the notification. I am still not confident with merging this PR in the current state. Let us get a second opinion from @lloyddewit. Points to understand;

- Why there are so many file changes.
- There are two files that should be removed - `dlgMyFirstDialog` and `Form1`. 
- I see changes from `dlgReorderLevels` dialog. Did you intend to make these changes?

2021-09-23 11:22 UTC, EstherNjeriLiberatta commented
@shadrackkibet No, I had not intended to make these changes.

2021-09-24 13:36 UTC, closed without merging