Added geom_text_wordcloud and geom_text_wordcloud_area geoms.
africanmathsinitiative/R-Instat pull request #6785
Opened 2021-09-21 15:57 UTC by HawardKetoyoMsatsi

@rdstern @africanmathsinitiative/developers 
This is ready for review.

2021-09-21 17:49 UTC, rdstern requested changes
@HawardKetoyoMsatsi shouldn't the label be a character (possibly a factor variable.  Currently it is just a numeric variable.
I couldn't check fully, because the current master version has an odd problem that is also evident in your version.  This is nothing to do with your work.

2021-09-22 06:59 UTC, HawardKetoyoMsatsi commented
@shadrackkibet Ann wanted to use the geom_text_wordcloud and geom_text_wordcloud_area could you please have a quick look at this PR
 I found the aesthetic parameter called angle should be passed as a numeric value. However, all aesthetic parameters in R-Instar set up aesthetics to accept input from receivers only. Is there a way they can be set up the parameters to accept inputs from ucrNuds or text inputs? If not we can leave that to be passed b the dialog.

2021-09-22 07:17 UTC, rdstern requested changes
@HawardKetoyoMsatsi now it accepts a factor, but not a text variable.  I am nit sure it makes sense with a numeric variable, but we can try.  So you might remove any restriction on the label?

2021-09-23 10:16 UTC, HawardKetoyoMsatsi commented
@rdstern I remoned thedatatype restriction on the label parameter. 
@shadrackkibet @anastasia-mbithe  In this PR angle parameter is restricted to a numeric variable however it can also accept a numeric value. All aes() parameters should be variables but these geom functions are a bit strange they take some aes() parameters either variables or values).

2021-09-23 10:33 UTC, rdstern commented
@HawardKetoyoMsatsi I can't see anything wrong, but it throws an exception, see below, with any example:  It also takes me to the same point when I type Library(ggwordcloud) into the script window.  Do you get that?  
![image](https://user-images.githubusercontent.com/11226469/134492742-61b458c1-2883-45d9-ac17-51b98cc62c05.png)

2021-09-24 09:24 UTC, HawardKetoyoMsatsi commented
The functions geom_text_wordcloud() and geom_text_wordcloud_area() seem to give the above error even when used in the r script in a branch without the changes I made in this PR. Maybe there could be a bigger issue with these functions.

2021-09-27 11:48 UTC, rdstern approved these changes

2021-09-27 11:54 UTC, shadrackkibet approved these changes

2021-09-27 11:54 UTC, shadrackkibet commented on instat/ucrGeom.vb
> +        'clsgeom_text_wordcloud.AddLayerParameter("area_corr", "boolean", "FALSE")
I assume this is commented out because of the limitation on the number of controls we can show?

2021-09-27 11:54 UTC, merged