Fixing the Developer error when adding geom_abline layer
africanmathsinitiative/R-Instat pull request #6792
Opened 2021-09-24 08:52 UTC by Ivanluv

fixes #6211
@africanmathsinitiative/developers this is ready for review

2021-09-24 11:22 UTC, shadrackkibet requested changes

2021-09-24 11:22 UTC, shadrackkibet commented on instat/ucrGeom.vb
> +        clsgeom_mosaic.AddLayerParameter("size", "numeric", "1", lstParameterStrings:={1, 1}) 'not certain if the size goues up to this much
Remove the comment now. Since it doesn't make sense again?

2021-09-24 11:57 UTC, Ivanluv commented on instat/ucrGeom.vb
> +        clsgeom_mosaic.AddLayerParameter("size", "numeric", "1", lstParameterStrings:={1, 1}) 'not certain if the size goues up to this much
I have removed it

2021-09-24 12:56 UTC, shadrackkibet approved these changes
@rdstern please test.

2021-09-27 10:43 UTC, rdstern approved these changes

2021-09-27 11:42 UTC, merged