Adding the Help ID to the Two variable Pivot Table Dialogue
africanmathsinitiative/R-Instat pull request #6800
Opened 2021-09-27 11:41 UTC by Ivanluv

This PR adds the Help topic ID for the Two Variable Pivot Table dialogue
@africanmathsinitiative/developers this is ready for review

2021-09-27 12:01 UTC, shadrackkibet requested changes

2021-09-27 12:01 UTC, shadrackkibet commented on instat/dlgPivotTable.vb
> +        ucrBase.iHelpTopicID = 417
We always want this to be the first line on InitialiseDialog.

2021-09-27 13:40 UTC, Ivanluv commented on instat/dlgPivotTable.vb
> +        ucrBase.iHelpTopicID = 417
Done

2021-09-27 13:42 UTC, shadrackkibet approved these changes
@rdstern please approve

2021-09-28 06:23 UTC, rdstern approved these changes

2021-09-28 07:48 UTC, merged