Improved the Recode factor levels dialogue in differents way with forcats functions
africanmathsinitiative/R-Instat pull request #6803
Opened 2021-09-27 14:33 UTC by N-thony

Fixes #6778 
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-09-28 06:20 UTC, rdstern commented
@N-thony well done on the drop option.  This is already working well.
I checked the lump option with the (ggplot2) diamonds data where the clarity factor has 8 levels.
Could you label the first option 
`Levels with at least this frequency`

Also label the second option as 
`This number of common levels`

And the third as 
`Levels with at least this proportion`

I don't understand the current "Other" option.  Is this still to be done?  Did you look at the Filter sub-dialogue control for a factor, where you can choose a selection of levels?

2021-09-29 06:41 UTC, N-thony commented
@rdstern I have changed the control as we discussed under the Other option, please have a look. Thanks.

2021-09-29 08:52 UTC, rdstern submitted a review, later dismissed
@N-thony great - well done!  Over to @shadrackkibet or @lloyddewit for the next step

2021-09-30 09:13 UTC, N-thony commented
@lloyddewit over to you.

2021-10-01 08:58 UTC, lloyddewit requested changes
@N-thony Looks good, just a few small comments

2021-10-01 08:58 UTC, lloyddewit commented on instat/dlgRecodeFactor.vb
> +    Private clsFctLowFreqFunction, clsFctLumpPropFunction, clsFctLumpMinFunction, clsFctLumpnFunction As New RFunction
Is this naming more consistent?
```suggestion
    Private clsFctLowFreqFunction, clsFctLumpPropFunction, clsFctLumpMinFunction, clsFctLumpNFunction As New RFunction

```

2021-10-01 08:58 UTC, lloyddewit commented on instat/dlgRecodeFactor.vb
>          End If
Simplify `If` condition?
```suggestion
        If ucrReceiverFactor.IsEmpty OrElse Not ucrSaveNewColumn.IsComplete Then
            ucrBase.OKEnabled(False)
        ElseIf rdoRecode.Checked Then
            ucrBase.OKEnabled(ucrFactorGrid.IsColumnComplete("New Label"))
        ElseIf rdoOther.Checked Then
            ucrBase.OKEnabled(Not String.IsNullOrEmpty(ucrFactorLevels.GetSelectedLevels()))
        ElseIf rdoLump.Checked Then
            ucrBase.OKEnabled(False)
        End If
```

2021-10-01 08:58 UTC, lloyddewit commented on instat/dlgRecodeFactor.vb
>          DefaultNewName()
I know that this is not your code, but ...
`DefaultNewName` is very small and only called here. Could we delete `DefaultNewName` and paste its code in here instead?
```suggestion
        If (Not ucrSaveNewColumn.bUserTyped) AndAlso (Not ucrReceiverFactor.IsEmpty) Then
            ucrSaveNewColumn.SetPrefix(ucrReceiverFactor.GetVariableNames(bWithQuotes:=False) & "_recoded")
        End If
```

2021-10-01 09:20 UTC, N-thony commented
@lloyddewit thanks for your review. This is ready for re-review.

2021-10-03 22:34 UTC, rdstern requested changes
@N-thony the lump no longer allows ok.  Also it adds recorded to the existing name.  So I already had data1_recoded and it therefore made it data1_recoded_recoded.  I wonder what would have happened if I used the command 5 times?

2021-10-04 06:16 UTC, N-thony commented
> @N-thony the lump no longer allows ok. Also it adds recorded to the existing name. So I already had data1_recoded and it therefore made it data1_recoded_recoded. I wonder what would have happened if I used the command 5 times?

@rdstern I have corrected this and fixes some bugs. Please have a look.

2021-10-04 09:39 UTC, rdstern approved these changes
@N-thony that's better!

2021-10-05 14:14 UTC, lloyddewit approved these changes

2021-10-05 14:15 UTC, merged