Added Treemap and Wordcloud in the Bar chart dialog
africanmathsinitiative/R-Instat pull request #6805
Opened 2021-09-28 10:02 UTC by anastasia-mbithe

@rdstern @shadrackkibet I have added the Treemaps and Wordcloud in the Bar chart dialog you can have a look at it.

2021-09-28 11:46 UTC, shadrackkibet requested changes
A few quick code checks. @rdstern please check on the functionality.

2021-09-28 11:46 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +    End Sub
Remove. Always check your changes before pushing to avoid such.

2021-09-28 11:46 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +        End If
Set the parameter and SetRcode to the control.

2021-09-28 11:46 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +                ucrInputLabelSize.Visible = False
Isn't possible to use our linking system? i.e `AddToLinkedControls`?

2021-09-28 11:50 UTC, anastasia-mbithe commented on instat/dlgBarAndPieChart.vb
> +    End Sub
Okay, I'll delete that.

2021-09-28 11:54 UTC, anastasia-mbithe commented on instat/dlgBarAndPieChart.vb
> +        End If
Here I had added an additional pair parameter but couldn't work without adding this.
We had to have layout in clsGeomTreemapFunction and also in clsGeomTreemapTextFunction of which they should be the same. That's why we opted for this instead of having a second layout control.

2021-09-28 12:01 UTC, anastasia-mbithe commented on instat/dlgBarAndPieChart.vb
> +                ucrInputLabelSize.Visible = False
I have linked all to the checkbox but the buttons shouldn't appear all at once in all radio buttons. I was conditioning them to appear in the required radio buttons. Those that appear in rdoTreemap are different from the ones appearing in rdoFrequency and rdoValue

2021-10-01 10:07 UTC, shadrackkibet commented
@Ivanluv could you test this? Can you also liaise with @anastasia-mbithe to see if you can resolve any pending issues?

2021-10-01 11:52 UTC, Ivanluv commented
@anastasia-mbithe  could we look at this when  you have time

2021-10-05 12:15 UTC, anastasia-mbithe commented
@rdstern @shadrackkibet  I feel this is ready for review now. Kindly have a look at it.

2021-10-06 05:47 UTC, shadrackkibet commented
Great. @rdstern please test.

2021-10-07 18:31 UTC, shadrackkibet commented
@rdstern word cloud should be working. Which error did you get? Perhaps you can post the error then we can try investigating.

2021-11-01 10:31 UTC, anastasia-mbithe commented
@N-thony kindly have a look at this.

2021-11-01 11:52 UTC, anastasia-mbithe commented
@rdstern  and @shadrackkibet, This is ready for review, kindly have a look into it.

2021-11-03 17:58 UTC, rdstern commented
@anastasia-mbithe well done.  This seems to work much better now.
![image](https://user-images.githubusercontent.com/11226469/140165529-c060002d-9152-47cb-99f4-6fb022134a2d.png)

Perhaps there can be more option s in the future, but (from my point-of-view) we could merge now.  let's see what @shadrackkibet says!

The one minor point is that the title of the dialogue is still the old `Bar and Pie chart`.  See above for the change.

2021-11-04 19:03 UTC, N-thony requested changes
Under Treemap and WorldCloud options, there are too many spaces between differents labels and corresponding ucrReceivers. Make them consistent
![image](https://user-images.githubusercontent.com/68591383/140403355-cba4246d-7fce-42fc-a7c2-4ed9904658d8.png)

2021-11-04 19:07 UTC, N-thony commented
- Center the panels so that it will not be more space on the right side
- Move the dataframe a bit down so that it will be on the same line with Single/Multiple receive under Frequency and Value options, also with Area and Label labels under Treemap and WolrdCloud options.
![image](https://user-images.githubusercontent.com/68591383/140404022-84d9efca-c706-4e57-acce-3f06b8f79374.png)

2021-11-04 19:10 UTC, N-thony commented
Align the controls on the left side
![image](https://user-images.githubusercontent.com/68591383/140404409-bcffc741-de59-4e02-932f-ce147c97a8a6.png)

2021-11-04 19:13 UTC, N-thony commented
When I click on Reset Start and Layout keep their state. Make the resetting proper to the controls.
![image](https://user-images.githubusercontent.com/68591383/140404786-aaf4ebb0-11fc-4832-8920-a87bb34d152b.png)

2021-11-05 10:18 UTC, anastasia-mbithe commented
@N-thony , I hope the issues above are now sorted out.

2021-11-05 11:24 UTC, N-thony requested changes

2021-11-05 11:24 UTC, N-thony commented on instat/dlgBarAndPieChart.vb
> +
Remove line 1014

2021-11-05 11:24 UTC, N-thony commented on instat/dlgBarAndPieChart.vb
>      End Sub
Add one line space after line 1006

2021-11-05 11:24 UTC, N-thony commented on instat/dlgBarAndPieChart.vb
Remove space, same on line 867

2021-11-05 19:27 UTC, N-thony approved these changes

2021-11-06 10:03 UTC, shadrackkibet requested changes

2021-11-06 10:03 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +            TestOkEnabled()
I see the comment above. Is this true? 

Could you also explain why you need `TestOkEnabled()` here?

2021-11-06 10:03 UTC, shadrackkibet commented on instat/dlgBarAndPieChart.vb
> +            TestOkEnabled()
Same case

2021-11-08 08:59 UTC, anastasia-mbithe commented
@shadrackkibet I don't see their relevance in the code as well, since with or without it still works the same, am going to remove the lines. I have also noted a bug in the frequency button, am working on it right now. I'll let you know when its fixed and ready for review. Thank you.

2021-11-08 10:31 UTC, anastasia-mbithe commented
@shadrackkibet kindly have a look at it now.

2021-11-08 10:55 UTC, shadrackkibet commented
I note that there are issues with synchronizing the main dialog with changes in the sub dialog. However, I think it is worth merging first at this stage.

@rdstern could you please re-test and approve if you're are happy we merge.

2021-11-08 12:08 UTC, rdstern approved these changes
Looks good

2021-11-08 12:12 UTC, shadrackkibet approved these changes

2021-11-08 12:12 UTC, merged