Scaledlg
africanmathsinitiative/R-Instat pull request #6812
Opened 2021-09-30 13:25 UTC by Vitalis95

2021-10-01 08:27 UTC, shadrackkibet commented
@HawardKetoyoMsatsi please test the functionality.

2021-10-01 10:02 UTC, HawardKetoyoMsatsi commented
Fine I will take a look.

2021-10-03 05:27 UTC, rdstern requested changes
@Vitalis95 it says there are build errors.  This may be just me, but I can't test.  Perhaps you can fix, or I could also look at it working on your machine - shared perhaps with skype?

2021-10-03 07:02 UTC, shadrackkibet commented
@rdstern I suggest you wait for Haward to look into this first then you can test.

2021-10-04 04:54 UTC, HawardKetoyoMsatsi requested changes
1. I see frmMain changes in your PR kindly conform with @shadrackkibet whether you can commit frmMain main in this PR.
2. I see a problem with your frmMain resource file which is causing the build errors please take a look.

2021-10-04 04:54 UTC, HawardKetoyoMsatsi commented on instat/dlgCluster.vb
> +        End If
Make this condition complete.

2021-10-04 04:54 UTC, HawardKetoyoMsatsi commented on instat/dlgCluster.vb
> +    End Sub
This sub should also handle control contents change for rdoSelectedColumn.

2021-10-04 07:08 UTC, Vitalis95 commented on instat/dlgCluster.vb
> +    End Sub
I will add the changes

2021-10-04 07:54 UTC, Vitalis95 commented on instat/dlgCluster.vb
> +    End Sub
@HawardKetoyoMsatsi I think the panel controls this? Radio buttons doesn't have the control content changed property.

2021-10-06 13:33 UTC, shadrackkibet commented
@rdstern check on the functionality. 

We will sort out the changes on the main form later. Thanks

2021-10-06 14:51 UTC, rdstern requested changes
@Vitalis95 it says there are build errors?  Sorry @shadrackkibet I don't know how to proceed further in such a case?

2021-10-07 17:49 UTC, shadrackkibet commented
Makes sense. Happy with your suggestions @lloyddewit

2021-10-11 10:16 UTC, lloyddewit commented
> 
> 
> @shadrackkibet @lloyddewit does it mean that I should close this PR?

As discussed on WhatsApp:

![image](https://user-images.githubusercontent.com/57253949/136773922-e8f0bcc3-eb78-465a-8476-d4c5511f67ce.png)

2021-10-18 13:06 UTC, shadrackkibet commented
@rdstern hold on a bit. We will sort this out soon. Thanks

2021-10-19 07:35 UTC, Vitalis95 commented
@rdstern  have a look it now, I have added the dist function. The data I am using to test is from library (cluster: voters.repub). Thanks

2021-10-19 09:46 UTC, shadrackkibet commented
At the same time @Gioche6 could you test and review the code?

2021-10-19 11:24 UTC, Gioche6 commented
@shadrackkibet , Sure. I'll be glad to to so

2021-10-28 21:30 UTC, rdstern submitted a review, later dismissed

2021-10-29 08:28 UTC, lloyddewit submitted a review, later dismissed
@Vitalis95 - Thank you for the changes, I'mm happy to approve.
@shadrackkibet - I saw that you also started to review. That's good, because you have good experience with the R-Instat dialog idioms and this will help Vitalis.
We can merge after you approve. Thanks

2021-11-01 12:05 UTC, Vitalis95 commented
@shadrackkibet  have a look at it.

2021-11-12 10:38 UTC, shadrackkibet requested changes
Not stable yet. From a user perspective, there are various issues which we need to sort out. Like when you use a data frame with non-numeric columns you get errors. Perhaps we should try to stop this? There are also reset issues for example the radio button selected doesn't reset to the default. Should we restrict selected variables to only numerics?

2021-12-07 11:44 UTC, Vitalis95 commented
The receiver for the selected variables only allows numeric variables. I made the  default to be selection of variables as suggested by @rdstern but not the whole data frame  
The data frame should have numeric columns that is why  with non-numeric columns it gives an error. I will be later adding daisy function for non-numeric columns (factors) -  @shadrackkibet @rdstern

2021-12-12 11:43 UTC, rdstern approved these changes
Now seems to work.  Are there more checks or can this be merged?

2021-12-13 10:46 UTC, lloyddewit commented
> Now seems to work. Are there more checks or can this be merged?

@shadrackkibet Thank you for reviewing this PR earlier. You had some comments. Are these now resolved and may we merge?
Thanks

2021-12-14 07:54 UTC, shadrackkibet commented
> Not stable yet. From a user perspective, there are various issues which we need to sort out. Like when you use a data frame with non-numeric columns you get errors. Perhaps we should try to stop this? There are also reset issues for example the radio button selected doesn't reset to the default. Should we restrict selected variables to only numerics?

@Vitalis95 did anything change after this comment? Apologies if I missed out on something.

2021-12-14 09:12 UTC, Vitalis95 commented
> > Not stable yet. From a user perspective, there are various issues which we need to sort out. Like when you use a data frame with non-numeric columns you get errors. Perhaps we should try to stop this? There are also reset issues for example the radio button selected doesn't reset to the default. Should we restrict selected variables to only numerics?
> 
> @Vitalis95 did anything change after this comment? Apologies if I missed out on something.

@shadrackkibet The receiver for the selected variables only allows numeric variables. I made the default to be selected variables as suggested by @rdstern but not the whole data frame
The whole data frame allows only numeric columns that is why with non-numeric columns it gives an error, @shadrackkibet you can guide me on this , to stop the error in case of a data frame with non-numeric columns.
Thanks.

2021-12-14 13:59 UTC, shadrackkibet commented
Hide non-numeric columns from the selector. To do this set the receiver to allow only numerics.  Pseudocode as follows `ucReceiverName.SetDataType("numeric")` also change the selector header to "Numerics" which should be something like `ucrReceivername.strSelectorHeader = "Numerics"`.

2021-12-14 14:46 UTC, shadrackkibet approved these changes
I approve and merge because what is here works already. Although there are still some issues, it qualifies as the initial implementation. I suggest we address them separately.

2021-12-14 14:46 UTC, merged