Added more recoding options into recode numeric dialog
africanmathsinitiative/R-Instat pull request #6857
Opened 2021-10-15 18:00 UTC by mmulahvictor

Fixes #6851
@africanmathsinitiative/developers this is ready for review
@rdstern @shadrackkibet have a look at it.

2021-10-21 08:48 UTC, mmulahvictor commented
@rdstern I have completed the changes above.

2021-10-28 15:03 UTC, rdstern submitted a review, later dismissed
@mmulahvictor great.  I am approving.  Let's see what @lloyddewit or @shadrackkibet feel.

2021-11-03 14:39 UTC, mmulahvictor commented
@N-thony I have made the changes

2021-11-03 15:45 UTC, N-thony commented
@mmulahvictor thanks. Over to you @shadrackkibet

2021-11-05 08:37 UTC, shadrackkibet commented
Very minor suggestions.

- Push the receiver label to left a bit... so that it aligns properly
- Should Ok be enabled in this kind of instance?
![image](https://user-images.githubusercontent.com/26301973/140478726-7cbdf3d3-4995-4740-850d-7b8852fbe0af.png)
![image](https://user-images.githubusercontent.com/26301973/140478788-aeb3ae0d-c3be-416c-b395-411b83171e60.png)
![image](https://user-images.githubusercontent.com/26301973/140479043-5fac2422-5dd5-4645-bfb9-c45cabae2282.png)

- The **Label Groups with Means** doesn't reset?
- Change the save control label to **New Column Name:** also **Break Points:**?
- Perhaps, a general problem with the save control. Reset doesn't work when you switch position. I claim it should switch to the default.

2021-11-05 09:03 UTC, shadrackkibet requested changes

2021-11-05 09:03 UTC, shadrackkibet commented on instat/dlgRecodeNumeric.vb
> +        AddParameters()
Could you explain why you added this here?

2021-11-07 11:35 UTC, rdstern commented
In addition:
a) The group box is labelled Quantile Groups.  It should be just Groups.
b) I tried with the gss_cat data from the forcats package.  I started with the 3rd button and the limits 30,50,70 and it worked fine.  Then I changed to the quantiles, and it still repeated the previous command.
c) I then did reset and tried the quantiles again.  When I use the default of 4 it gives the command as 
`recode <- Hmisc::cut2(x=age) ` which is not what's wanted!  
If I change to 5 it is ok, i.e. `recode2 <- Hmisc::cut2(g=5, x=age)`  so I think you just need to include g=4 above.
The option with m=2000 worked ok, please check also with the default, that it is also fine!

2021-11-08 12:46 UTC, mmulahvictor commented
@shadrackkibet I have completed the changes above.

2021-11-08 18:02 UTC, shadrackkibet commented
@mmulahvictor I did refactor the code a bit. Pull the changes and test.

2021-11-09 05:17 UTC, mmulahvictor commented
@shadrackkibet When I select the Quantiles radio button and do aReset, it brings the following error.
![Screenshot (26)](https://user-images.githubusercontent.com/60970331/140866818-4cecd7d3-9bd9-4e77-b08e-29dee957914e.png)

2021-11-15 09:52 UTC, lloyddewit commented
@rdstern if you can test/approve again, then I'll do the final peer review and (hopefully) merge.
thanks

2021-11-25 12:33 UTC, rdstern requested changes
This is looking good now.
a) Could ypou make 4 the default for the quantiles, and (say) 5 for the Minimum.  (They are currently 1.)
b) The means option should be unticked by default.  It doesn't yet work.  I don't see a change in the code when it is ticked.

2021-12-06 07:26 UTC, mmulahvictor commented
@rdstern and @shadrackkibet can you look at this change. This is a screenshot of the developer error.
![Screenshot (32)](https://user-images.githubusercontent.com/60970331/144804746-f9eab6fc-8930-4594-932c-0481a188a148.png)

2021-12-06 07:42 UTC, shadrackkibet commented
@mmulahvictor anything remaining? I can help sort it out now.

2021-12-06 07:47 UTC, mmulahvictor commented
@shadrackkibet  everything is done now.

2021-12-06 08:25 UTC, shadrackkibet requested changes

2021-12-06 08:25 UTC, shadrackkibet commented on instat/dlgRecodeNumeric.vb
> +        ucrNudMinimum.SetMinMax(5)
I think it is correct to set the minimum value as 1. We want `4` and `5` as the parameter defaults and not the minimum value a control can allow. This means the user can't input a value less than 4 or 5 respectively. To sort this out add these as parameter vaues in setDefaults.

2021-12-08 08:23 UTC, lloyddewit commented
@mmulahvictor Thank you for this PR. 
Do you believe that you've now resolved all the comments from @rdstern and @shadrackkibet? 
Is this PR ready for final approvals and merge?
Thanks for clarifying

2021-12-08 08:34 UTC, mmulahvictor commented
Thank you @lloyddewit 
I have resolved all the changes.

2021-12-09 09:30 UTC, lloyddewit commented
@rdstern @shadrackkibet Please could you give your final approvals? thanks

2021-12-09 11:46 UTC, shadrackkibet commented
@mmulahvictor please update this branch with the master branch.

2021-12-21 15:42 UTC, rdstern requested changes
The default for quantiles is still 1.  Could it be made (say) 4.  And could the word quantiles be changed to become Levels.  It is just the number of levels of the factor being produced.
It is looking good now, so I would like to get it merged.

2021-12-23 11:48 UTC, mmulahvictor commented
> The default for quantiles is still 1. Could it be made (say) 4. And could the word quantiles be changed to become Levels. It is just the number of levels of the factor being produced. It is looking good now, so I would like to get it merged.

@rdstern I made the changes on the default for the Quantiles and it is working. The images below shows that the least you can select is 1 and the default is 4 respectively.

![Screenshot (35)](https://user-images.githubusercontent.com/60970331/147235945-921bfe40-eb15-43a6-8892-e480243e4a8b.png)
![Screenshot (34)](https://user-images.githubusercontent.com/60970331/147235969-67fb0769-c6d5-4830-8f9d-36a9ed51e9e2.png)

2022-01-03 09:19 UTC, lloyddewit commented
@rdstern @shadrackkibet Please could you give your final approvals? thanks

2022-01-04 13:26 UTC, rdstern submitted a review, later dismissed
Seems fine now

2022-01-10 07:02 UTC, shadrackkibet commented
@mmulahvictor could you sort out the conflict then we can merge?

2022-01-10 07:55 UTC, mmulahvictor commented
@shadrackkibet  I have resolved the issue

2022-01-10 09:47 UTC, shadrackkibet commented
@mmulahvictor I can't test it. I get the following build errors.
![image](https://user-images.githubusercontent.com/26301973/148745845-48bd0fdf-70e2-4554-adfa-3b799a492489.png)

2022-01-11 06:50 UTC, shadrackkibet commented
I get more build errors. Looks like there is a problem with this file. Perhaps that is because you manually edited the resource file which is normally very tricky.

![image](https://user-images.githubusercontent.com/26301973/148894371-0ec24196-1bc3-416b-9ebe-d77b60a64977.png)

The simplest way to sort this out is to redo these changes in a new PR. You could just copy-paste carefully.

2022-01-14 07:26 UTC, shadrackkibet commented
@mmulahvictor any progress on this?

2022-01-14 07:44 UTC, mmulahvictor commented
> @mmulahvictor any progress on this?

I have a system crash right now which I am trying to restore it but I only remain with changes on the designer.

2022-01-18 08:30 UTC, shadrackkibet commented
I hope the crash was sorted out? Could you report on the progress here?

2022-01-18 08:43 UTC, mmulahvictor commented
Yeah it is sorted out. I am currently installing R-Instat on Ubuntu as suggested by Maxwell and Danny. I will complete this by today and continue with this work afterwards.

2022-01-18 19:25 UTC, lloyddewit commented
replaced by PR #7136

2022-01-18 19:25 UTC, closed without merging