Improvements to Stack(Pivot Longer) dialog
africanmathsinitiative/R-Instat pull request #6876
Opened 2021-10-21 07:46 UTC by Vitalis95

Partially solves #6868
@rdstern @shadrackkibet, this is for the Drop Missing Values Checkbox. Have a look at it.

2021-11-03 11:34 UTC, Vitalis95 commented
@shadrackkibet, have a look at it.

2021-11-04 10:01 UTC, lloyddewit commented
@Vitalis95 Please could you resolve @N-thony 's comment above? thanks

2021-11-04 18:18 UTC, rdstern submitted a review, later dismissed
@Vitalis95 to me this looks fine now.  Let's see what @shadrackkibet thinks?

2021-11-05 10:27 UTC, N-thony commented
Push a bit  Name to label to the left, so that it aligns properly with other controls on the left side. Same case with New Data Frame Name label
![image](https://user-images.githubusercontent.com/68591383/140496417-e392f2be-f0ce-49c2-bbe1-ea23e7a74bbd.png)

2021-11-05 10:30 UTC, N-thony commented on instat/dlgStack.vb
> +    End Sub
Add one line space after line 355

2021-11-05 11:45 UTC, Vitalis95 commented
@N-thony , I have made the alignments.

2021-11-05 19:19 UTC, N-thony approved these changes

2021-11-12 07:08 UTC, rdstern submitted a review, later dismissed
Looks good now.

2021-11-19 09:48 UTC, lloyddewit requested changes
@Vitalis95 Thanks, this looks good, just a few suggestions

2021-11-19 09:48 UTC, lloyddewit commented on instat/dlgStack.vb
> +    Private clsSplitColumnsInGroups As RFunction
Rename to make it clearer that its a function?
```suggestion
    Private clsSplitColumnsFunction As RFunction
```
or a different name if you prefer

2021-11-19 09:48 UTC, lloyddewit commented on instat/dlgStack.vb
> +        clsReshapeFunction.AddParameter("direction", Chr(34) & "long" & Chr(34))
Would it be safer and more readable to explicitly set `iPosition:=0'?

2021-11-19 09:48 UTC, lloyddewit commented on instat/dlgStack.vb
> +            If ucrReceiverColumnsToBeStack.IsEmpty OrElse Not ucrSaveNewDataName.IsComplete OrElse ucrInputNamesTo.IsEmpty OrElse ucrInputValuesTo.IsEmpty OrElse ucrFactorInto.IsEmpty OrElse (ucrRece
add line breaks so that each line is max 100 columns

2021-11-19 09:48 UTC, lloyddewit commented on instat/dlgStack.vb
> +    Private Sub SetSingleOrMultipleOptions()
This sub is only called from one location (line 358).
Delete this sub and move its contents to line 358?

2021-11-19 14:14 UTC, Vitalis95 commented
@lloyddewit  I have made the changes. Thanks

2021-11-22 10:18 UTC, lloyddewit approved these changes
@Vitalis95 thanks, looks good

2021-11-22 10:20 UTC, lloyddewit commented
@rdstern there's been some small changes since your last approval, please could you retest? thanks

2021-11-25 14:36 UTC, rdstern approved these changes
Great!

2021-11-26 10:22 UTC, merged