Changed unstack (pivot wider) dialog to use pivot_wider function
africanmathsinitiative/R-Instat pull request #6884
Opened 2021-10-28 08:17 UTC by Gioche6

Fixes #6871

@africanmathsinitiative/developers , This is ready for review
@shadrackkibet , I have changed the function from reshape to `pivot_wide`r as suggested. Kindly review if the codes works well. 
@rdstern , I have added the `values_fill` and `names_prefix `checkboxes as suggested in issue #6871. Kindly test if it's now alright.

2021-11-04 09:32 UTC, Ivanluv commented
@Gioche6  is this ready for review

2021-11-04 17:24 UTC, rdstern submitted a review, later dismissed
@Gioche6 great.  From my point of view this seems to work.  Let's see what @shadrackkibet says

2021-11-05 05:20 UTC, Gioche6 commented
@rdstern, Currently  I am working on implementing the code nicely to prevent any future bugs with the help of @Ivanluv . I will push the changes once done for testing. For  now, this is still in progress. Thank you

2021-11-05 06:32 UTC, rdstern commented
@Gioche6 thank you for the update.  Let me know when I can check again.

2021-11-05 08:50 UTC, Gioche6 commented
@rdstern . This is ready for testing Now. I have been working on how to best implement the carry columns control and the multiple receiver for columns to unstack. I believe it works better now. I look forward to your comments on this. 

@Ivanluv , Kindly review the same. Thank you

2021-11-05 09:23 UTC, Ivanluv commented on instat/dlgUnstack.vb
>          clsSelectFunction.AddParameter("comma", clsROperatorParameter:=clsCommaOperator, bIncludeArgumentName:=False)
parameter position

2021-11-05 09:25 UTC, Ivanluv commented on instat/dlgUnstack.vb
> +
remove the space

2021-11-05 09:25 UTC, Ivanluv commented on instat/dlgUnstack.vb
> +
Remove the space

2021-11-05 09:40 UTC, Gioche6 commented on instat/dlgUnstack.vb
> +
Done

2021-11-05 09:40 UTC, Gioche6 commented on instat/dlgUnstack.vb
> +
Done

2021-11-05 09:40 UTC, Gioche6 commented
@Ivanluv , I've done the changes as you requested.

2021-11-05 09:45 UTC, Ivanluv submitted a review, later dismissed

2021-11-08 06:07 UTC, Gioche6 commented
@rdstern , This is now ready for testing. Thank you

2021-11-08 06:29 UTC, rdstern approved these changes
@Gioche6 - great - seems to work fine.

2021-11-08 08:48 UTC, shadrackkibet requested changes

2021-11-08 08:48 UTC, shadrackkibet commented on instat/dlgUnstack.vb
> +        ucrChkCarryColumns.Checked = False
Remove the manual checking. You could use a dummy function to set the default.

2021-11-08 08:48 UTC, shadrackkibet commented on instat/dlgUnstack.vb
> +    Private clsUnstackedOperator, clsCommaOperator, clsFormula, clspipeOperator As New ROperator
`clsFormulaOperator`?

2021-11-08 08:48 UTC, shadrackkibet commented on instat/dlgUnstack.vb
> +            clsDcastFunction.AddParameter(New RParameter("values_fill", "0", iNewPosition:=7))
Technically we should be doing this under `InitialiseDialog()`. I am keen to understand why you chose to have it here.

2021-11-09 07:33 UTC, Gioche6 commented on instat/dlgUnstack.vb
> +        ucrChkCarryColumns.Checked = False
Done

2021-11-09 07:35 UTC, Gioche6 commented on instat/dlgUnstack.vb
> +            clsDcastFunction.AddParameter(New RParameter("values_fill", "0", iNewPosition:=7))
The default value is set to be 0, which don't appear as its the ucrNud default value. Hence I have made some changes and resulted adding the parameter manually for the 0 to appear in the` values_fill` parameter

2021-11-09 07:37 UTC, Gioche6 commented
@shadrackkibet , This is ready for review.

2021-11-12 07:33 UTC, Gioche6 commented
@rdstern . This is now ready for testing. Thank you.

2021-11-12 09:25 UTC, rdstern commented
@Gioche6 the multiple option still seems flaky:
![image](https://user-images.githubusercontent.com/11226469/141442456-5fc23fc6-1ee7-4d47-87b4-9838567b4750.png)
 The `columns to carry` control closes each time you return to the dialogue and I could not always get it to work when it had the data.  

I used the World Bank  data from the tidyR package.  You can unstack each year, so multiple years gives an example for multiple.  You need to carry the country.

2021-11-12 10:52 UTC, Gioche6 commented
@rdstern , I have made sure the checkbox works well now. Could you please test it. Thank you

2021-11-12 13:08 UTC, rdstern requested changes
@Gioche6 now I see what I did wrong last time.  But it is still not quite right - at least for beginners like me!
So with the same dataset I used multiple and then made the factor of the variable to unstack by.  Then I worked in order - please try too.  
I unstacked the data for 2000 to 2003.  Then I clicked on the Carry checkbox.  It now opens the multiple receiver, but it still leaves the focus on the columns to unstack!
So if you now click on Country, then it goes into the wrong receiver.  You don't see that, because the receiver is full.
Now you realise and it goes into the Carry receiver too.  But I don't think it works well when Country is in both!
The solution is simply when you click on the Carry checkbox, then move the focus automatically to that multiple receiver.

2021-11-26 10:31 UTC, Gioche6 commented
@rdstern , I have fixed the issue arising when changing the data frame and having the carry columns  receiver highlighted when the the carry columns checkbox is checked. Please test if it is working fine . Thank you

@shadrackkibet , this is ready for review.

2021-11-26 12:44 UTC, rdstern approved these changes
Great.  Seems to work.  Over to you @shadrackkibet

2021-12-06 14:18 UTC, shadrackkibet requested changes

2021-12-06 14:18 UTC, shadrackkibet commented on instat/dlgUnstack.vb
> +        ucrChkCarryColumns.SetRDefault("FALSE")
I understand this is a dummy function. I suggest you add this parameter in setDefaults then remove the RDefaults here.

2021-12-06 14:52 UTC, Gioche6 commented on instat/dlgUnstack.vb
> +        ucrChkCarryColumns.SetRDefault("FALSE")
This is Done

2021-12-06 14:52 UTC, Gioche6 commented
@shadrackkibet , I have resolved the issue above, Could you please see if its okay? Thank you.

2021-12-06 15:39 UTC, shadrackkibet commented
Could you try to sort out the following minor issues;

1) OK should not be enabled in the following instances because when I click Ok I get bugs!

![image](https://user-images.githubusercontent.com/26301973/144872885-6b728459-c23b-4f46-8893-21889f405325.png)
![image](https://user-images.githubusercontent.com/26301973/144873102-a7910839-2a5c-44b3-be00-1576856c2df3.png)

2) The checkbox appears to overlap with the receiver.

![image](https://user-images.githubusercontent.com/26301973/144873281-6fecafa7-5e1a-498b-bcb5-f3510fcafefc.png)

3) We shouldn't have instances where the current receiver is hidden. Otherwise, the user will be confused about where to add a variable.

![image](https://user-images.githubusercontent.com/26301973/144873431-bca24702-5d0b-482e-b916-e2e7af16144e.png)
4) I would prefer an input textbox rather than NUD for the following;
 
![image](https://user-images.githubusercontent.com/26301973/144874675-be56f472-1ba9-41e1-8fef-5d59fc8e3253.png)

In the function help it is stated as follows;

>Optionally, a (scalar) value that specifies what each value should be filled in with when missing.
> This can be a named list if you want to apply different aggregations to different value columns.

You can ignore point (4) for now.

2021-12-07 09:54 UTC, Gioche6 commented
@shadrackkibet , I have resolved item 1 to 3. I have made sure the design is correctly implemented as well as Test Ok. Kindly review, Thank you.

2021-12-09 07:38 UTC, shadrackkibet commented
@Gioche6 this is making good progress. Let us try to test it a bit more to identify if there are any bugs.

I tried to trick it a bit and I was able to get the following bug under Restore Hierarchy (Sorry I can't remember the steps) - By the way, I was using the French translation.
![image](https://user-images.githubusercontent.com/26301973/145353811-95adfa1a-1aa2-4a15-8195-555ffcf2b1e6.png)

2021-12-09 12:01 UTC, Gioche6 commented
@shadrackkibet , I managed to detect the error and have now solved it. Additionally, I have worked on `TestOk` for the `rdo hierachy`. Kindly review and test. Thank you

2021-12-16 11:52 UTC, Gioche6 commented
@shadrackkibet , Could you review this. I've been testing using various datasets and works fine.

2021-12-17 08:18 UTC, shadrackkibet commented
@Gioche6 thanks for the reminder. I will look into this now.

2021-12-17 08:39 UTC, shadrackkibet commented
@Gioche6 I got the following still. 

1) Do we want to enable Ok when the multiple receiver is empty? I clicked Ok which produced the following code.

```
us_rent_income <- data_book$get_data_frame(data_name="us_rent_income")
us_rent_income_unstacked <- tidyr::pivot_wider(data=us_rent_income, names_from=NAME, values_from=moe)
data_book$import_data(data_tables=list(us_rent_income_unstacked=us_rent_income_unstacked))

rm(list=c("us_rent_income_unstacked", "us_rent_income"))
```
![image](https://user-images.githubusercontent.com/26301973/146513919-fc3850a4-1bce-4e4d-a0c5-1ca49e20d966.png)

2) When I click single Ok is now disabled.

![image](https://user-images.githubusercontent.com/26301973/146514423-3da48fe3-5b43-4d55-8a51-31cde582a83a.png)

NB: A user can be easily confused and not know what to do when Ok is disabled in instances when it should be enabled.

2021-12-17 09:55 UTC, shadrackkibet commented
@rdstern I don't remember why we choose to restrict this dialog to only unstack by factors. I think we should at least allow characters as well? this will also mean we change the label. What do you think?

2021-12-17 10:27 UTC, Gioche6 commented
@shadrackkibet , I have fixed the minor TESTOK bug. Kindly check if its okay. Thank you.

2022-01-02 08:53 UTC, rdstern requested changes
I have used the dialogue quite a lot in writing the help and it seems to be working well.  Just 2 small points:
a) When the data frame is changed the suggested name of the new file remains the same.  It should update.
b) One section not updated yet is the restore hierarchy options.  This still uses the reshape2::dcast function.  There is a data.table::dcast which is still current.  I found this worked just as well, so suggest that trivial change could be made.  Perhaps someone who knows more R, e.g. @shadrackkibet could confirm.

2022-01-14 07:42 UTC, shadrackkibet commented
@Gioche6 could you sort out conflicts?

a) Straight forward to change.
b) I agree with the change to `data.table::dcast()`  for efficiency purposes. data.table functions are well known for that!

2022-01-14 08:22 UTC, Gioche6 commented
@Shadrack, I have sort out the merge conflicts and did some minor design changes. Kindly review. Thanks

2022-01-14 08:23 UTC, shadrackkibet commented
> I have used the dialogue quite a lot in writing the help and it seems to be working well. Just 2 small points: a) When the data frame is changed the suggested name of the new file remains the same. It should update. b) One section not updated yet is the restore hierarchy options. This still uses the reshape2::dcast function. There is a data.table::dcast which is still current. I found this worked just as well, so suggest that trivial change could be made. Perhaps someone who knows more R, e.g. @shadrackkibet could confirm.

Did you also sort out this ones?

2022-01-14 08:25 UTC, Gioche6 commented
Item (a) is sorted. I am working on item (b)

2022-01-14 15:04 UTC, Gioche6 commented
@rdstern . I have changed the the function used in Restore Hierarchy to `data.table::dcast` as you suggested. I have also made sure that the Data frame names update. Kindly test. Thank you. 

@shadrackkibet , Kindly review. Thank you.

2022-01-18 08:00 UTC, shadrackkibet commented
@rdstern this looks stable and complete now. Please test.

2022-01-24 07:17 UTC, shadrackkibet commented
@rdstern this PR needs your assessment then we can possibly merge it.

2022-01-24 12:33 UTC, rdstern commented
@shadrackkibet sorry, but the restore hierarchy now works slightly differently to the one before (in version 7.3.1)
![image](https://user-images.githubusercontent.com/11226469/150782713-3b85b77a-72a2-49a5-8dfc-53d400b1c86c.png)

Here it is in 7.3.1 from restore hierarchy with rwanda data from the Instat climatic library.  
![image](https://user-images.githubusercontent.com/11226469/150783396-352df184-f6fe-4e9b-a842-46f3fa175e93.png)


Restore by Station name.  (Don't worry about the 8 lines rather than 4 - that's a different (interesting) question!)


It works in the pull request, but gives the results differently - including the counts for each station.  And doesn't include the unstacking variable.  That's different.  If I want those counts then I'll get them as a summary later!  

Could you adjust the command in the new version to give the results above
And it doesn't include

2022-01-24 12:34 UTC, rdstern requested changes
Change suggested to give same results as before.

2022-01-25 10:39 UTC, Gioche6 commented
@rdstern , I have made the adjustment needed. The restore hierarchy now produces the same result as before. I would love to know how you think about it after testing. Thank you
@shadrackkibet , This is ready for review. Thank you

2022-01-25 11:20 UTC, rdstern commented
@Gioche6 that's better, because it now includes all variables.
![image](https://user-images.githubusercontent.com/11226469/150967324-fa8e3fa6-dcd9-493b-8392-8ef47ab83d9a.png)

But it still includes the counts which we don't need.  I hope that is also easy to fix.  I would like to get this merged in the coming version.

2022-01-25 12:45 UTC, Gioche6 commented
@rdstern , I have corrected that feature. The counts will no longer appear. Kindly test. Thank you

2022-01-25 13:28 UTC, rdstern approved these changes
@Gioche6 great.  I hope @lloyddewit and/or @shadrackkibet are ok with the code, so this can be merged.

2022-01-25 13:32 UTC, Gioche6 commented
@shadrackkibet , This is ready for review

2022-01-25 15:34 UTC, shadrackkibet commented
- I am not sure what happened to the grid. See below

![image](https://user-images.githubusercontent.com/26301973/151006614-16a1c8fd-ceea-4347-8eef-36e63d2f1793.png)

![image](https://user-images.githubusercontent.com/26301973/151006700-03d49d9e-0996-4c2f-9d5f-c8c6d07fa2c4.png)

- I also get this when I try importing shapefiles.
![image](https://user-images.githubusercontent.com/26301973/151007356-0bc7cde7-9a21-40f5-9bfd-09e34fb051b3.png)

![image](https://user-images.githubusercontent.com/26301973/151007142-6c808049-7101-412f-be02-eca912b421eb.png)

This is an issue that might not be linked to this PR.

2022-01-25 16:09 UTC, rdstern submitted a review, later dismissed
@shadrackkibet your comment made me check the dialogue a bit more - the other options.
I don't get your problem with the data sets I have used.  I agree it is probably a reogrid problem and not necessarily linked to this dialogue.  I have had your problem when (like your example) a variable contains a very long list.  It then seems to wordwrap - which I would sometimes like.  But in our case we don't yet have that option, so the cells then become very deep.  And as the word-wrapping is caused by a single variable - the polygon coordinates usually - it makes the grid look very odd.  Good to get some examples and make a separate issue I think.

2022-01-25 16:37 UTC, shadrackkibet requested changes
@Gioche6 I had a few changes to request. Perhaps with a question.

2022-01-25 16:37 UTC, shadrackkibet commented on instat/dlgUnstack.vb
> +    End Sub
I am not sure why you resorted to doing this manually anyway. In principle `ucrNudValuesFill`  should pass the parameter to `clsDcastFunction` function, then the linking you have in line 83 will take care of removing and adding? 
Does this make sense?

2022-01-25 16:37 UTC, shadrackkibet commented on instat/dlgUnstack.vb
>      End Sub
I always like making this the last `Sub` for consistency.

2022-01-25 16:37 UTC, shadrackkibet commented on instat/dlgUnstack.vb
> +    End Sub
Could you move this to line 188?

2022-01-25 16:37 UTC, shadrackkibet commented on instat/dlgUnstack.vb
> +    End Sub
Perhaps even this one?

2022-01-26 07:20 UTC, Gioche6 commented
@shadrackkibet , I have made the changes you requested.

2022-01-26 08:38 UTC, rdstern approved these changes
Still looks fine and a good improvement

2022-01-26 08:45 UTC, shadrackkibet approved these changes

2022-01-26 08:46 UTC, merged