Function definition for specific R Functions
africanmathsinitiative/R-Instat pull request #6885
Opened 2021-10-28 11:06 UTC by Ivanluv

fixes #6853 
This is still in progress

2021-11-16 15:31 UTC, lloyddewit requested changes

2021-11-16 15:31 UTC, lloyddewit commented on instat/clsRLink.vb
> +    Private Function GetRFunctionDefinitionParameters(strFunctionName As String) As List(Of clsRParameter)
Please could you add an XML header? This header should include examples of what's returned for some example functions.

2021-11-16 15:31 UTC, lloyddewit commented on instat/clsRLink.vb
> +                While (iParameterName < expTemp.AsCharacter().Length)
It's hard to understand the code below without knowing the structure of what the R function returns.
Please could you add a comment that shows some examples of what the R function returns?

2021-11-16 15:31 UTC, lloyddewit commented on instat/clsRLink.vb
> +                    iParameterValue = iParameterValue + 3
```suggestion
                    iNewArgPosition += 1
                    iParameterName += 3
                    iParameterValue += 3
```

2021-11-16 15:31 UTC, lloyddewit commented on instat/clsRLink.vb
> +                        If expTemp.AsCharacter(iParameterValue) = "" Then
```suggestion
                        If String.IsNullOrEmpty(expTemp.AsCharacter(iParameterValue)) Then
```

2021-11-16 15:31 UTC, lloyddewit commented on instat/clsRLink.vb
> +                        'Empty string are not accepted hence the mdidifaction below
what does 'mdidifaction ' mean?

2021-11-16 15:31 UTC, lloyddewit commented on instat/clsRLink.vb
> +                    If expTemp.AsCharacter(iParameterValue).Contains("[1]") Then
Are we sure that it's always '[1]'? Is it possible to have a default with more than one element?

2021-11-16 15:31 UTC, lloyddewit commented on instat/clsRLink.vb
> +                            clsNewRParameter.clsArgValueDefault = New RScript.clsRScript("""").lstRStatements(0).clsElement
Should this be `""""""` or `Chr(34) & Chr(34)` ?
What type of element should this be? Is `Nothing` acceptable?

2021-11-16 15:31 UTC, lloyddewit commented on instat/clsRLink.vb
> +                    clsNewRParameter.strArgName = expTemp.AsCharacter(iParameterName)
Is the argument name always preceded by '$'? If so, do we need to strip this off?

2021-11-17 13:12 UTC, Ivanluv commented on instat/clsRLink.vb
> +            Evaluate("rm(" & strTempAssignTo & ")", bSilent:=True)
When using `RunInternalScriptGetValue `I loose information when getting the parameters eg double quotes around parameter values If they have one

2021-11-17 13:12 UTC, Ivanluv commented on instat/clsRLink.vb
> +            If expTemp IsNot Nothing Then
Done

2021-11-17 13:13 UTC, Ivanluv commented on instat/clsRLink.vb
> +        Dim iParameterValue As Integer = 1
Sure, this is much better.

2021-11-17 13:15 UTC, Ivanluv commented on instat/clsRLink.vb
> +    Private Function GetRFunctionDefinitionParameters(strFunctionName As String) As List(Of clsRParameter)
I have added this. Could have a look

2021-11-17 13:17 UTC, Ivanluv commented on instat/clsRLink.vb
> +                While (iParameterName < expTemp.AsCharacter().Length)
I have added one in the XML header

2021-11-17 13:17 UTC, Ivanluv commented on instat/clsRLink.vb
> +                    iParameterValue = iParameterValue + 3
Done

2021-11-17 13:18 UTC, Ivanluv commented on instat/clsRLink.vb
> +                        'Empty string are not accepted hence the mdidifaction below
sorry, it should have been "modification". I have corrected this

2021-11-17 13:19 UTC, Ivanluv commented on instat/clsRLink.vb
> +                    If expTemp.AsCharacter(iParameterValue).Contains("[1]") Then
Am not so sure on this ,maybe I could investigate

2021-11-17 13:20 UTC, Ivanluv commented on instat/clsRLink.vb
> +                            clsNewRParameter.clsArgValueDefault = New RScript.clsRScript("""").lstRStatements(0).clsElement
This is the case when we have no default parameter, I have replaced the parameter value with the text "NODEFAULTVALUE"

2021-11-17 13:26 UTC, Ivanluv commented on instat/clsRLink.vb
> +                    clsNewRParameter.strArgName = expTemp.AsCharacter(iParameterName)
Yes, we need to trim that off. Thank you for the reminder

2021-11-18 08:09 UTC, lloyddewit commented on instat/clsRLink.vb
> +            Evaluate("rm(" & strTempAssignTo & ")", bSilent:=True)
yes, I think you explained that to me before, thanks for the reminder

2021-11-18 08:38 UTC, lloyddewit commented on instat/clsRLink.vb
> +        If Evaluate(strTempAssignTo & " <- " & "capture.output(" & clsAsListFunction.ToScript() & ")", bSilent:=True) Then
We can apply the 'happy path stays left' principle here also.
If the evaluate fails, then we can just return nothing.

2021-11-18 08:38 UTC, lloyddewit commented on instat/clsRLink.vb
> +    ''' </summary>
Thanks for the XML header.
The list looks OK in the header but when the XML is processed, the line breaks are ignored and all the lines merge together.
Please could you format the parameters as an XML list? You can find an example in `clsRCodeStructure`.

Please also ensure that all lines are 100 columns or less.

![image](https://user-images.githubusercontent.com/57253949/142380196-a12f903c-73ca-4896-b64b-e1494fca73f5.png)

![image](https://user-images.githubusercontent.com/57253949/142380265-ae29c645-450a-43f3-9eef-c5f2fad6a873.png)

2021-11-18 08:38 UTC, lloyddewit commented on instat/clsRLink.vb
> +                While (iParameterName < expTemp.AsCharacter().Length)
The XML header gives examples of what the VB function returns but not what the R function returns.
Please could you show what the R function returns (e.g. for `str_split`)?

2021-11-18 08:46 UTC, lloyddewit commented on instat/clsRLink.vb
> +                            clsNewRParameter.clsArgValueDefault = New RScript.clsRScript("""").lstRStatements(0).clsElement
Could we just leave it as `Nothing` instead?
```
                    If Not String.IsNullOrEmpty(expTemp.AsCharacter(iParameterValue)) Then
                        clsNewRParameter.clsArgValueDefault = New RScript.clsRScript(expTemp.AsCharacter(iParameterValue)).lstRStatements(0).clsElement
                    End If
```

2021-11-18 08:49 UTC, lloyddewit requested changes
Thanks for the improvements, I just have a couple of open questions

2021-11-18 08:49 UTC, lloyddewit commented on instat/clsRLink.vb
> +                    clsNewRParameter.clsArgValueDefault = New RScript.clsRScript(strcleanArgument).lstRStatements(0).clsElement
remove `RScript` (also in lines below)?
```suggestion
                    clsNewRParameter.clsArgValueDefault = New clsRScript(strcleanArgument).lstRStatements(0).clsElement
```

2021-11-19 12:48 UTC, Ivanluv commented on instat/clsRLink.vb
> +                While (iParameterName < expTemp.AsCharacter().Length)
I have made changes, you could have a look

2021-11-19 12:50 UTC, Ivanluv commented on instat/clsRLink.vb
> +                            clsNewRParameter.clsArgValueDefault = New RScript.clsRScript("""").lstRStatements(0).clsElement
when having that `expTemp.AsCharacter(iParameterValue)`  evaluates to `"" `which gives the follloring error

![image](https://user-images.githubusercontent.com/45068931/142625462-7d15befe-55b5-47a8-9764-8679e35eb20f.png)

2021-11-19 12:51 UTC, Ivanluv commented on instat/clsRLink.vb
> +        If Evaluate(strTempAssignTo & " <- " & "capture.output(" & clsAsListFunction.ToScript() & ")", bSilent:=True) Then
Done .Thanks

2021-11-19 12:51 UTC, Ivanluv commented on instat/clsRLink.vb
> +                    clsNewRParameter.clsArgValueDefault = New RScript.clsRScript(strcleanArgument).lstRStatements(0).clsElement
Done

2021-11-19 12:51 UTC, Ivanluv commented on instat/clsRLink.vb
> +    ''' </summary>
could you have a look at the change

2021-11-22 09:50 UTC, lloyddewit reviewed
Thanks, if you can make these final changes, then I think it's ready

2021-11-22 09:50 UTC, lloyddewit commented on instat/clsRLink.vb
> +    ''' </summary>
Simplify comment?
```suggestion
    ''' <summary>   
    ''' Gets the list of clsRParameters from the <paramref name="strFunctionName"/> function 
    ''' definition. 
    ''' For example, the function "str_split(string, pattern, n = Inf, simplify = FALSE)" returns 
    ''' the following parameters:
    ''' <list type="bullet">
    '''     <item><description>
    '''             clsParameter 1: Argument Name ="string" , Parameter position = 0 , Default value = NOTHING 
    '''     </description></item><item><description>
    '''             clsParameter 2: Argument Name = "patterm" , Parameter position = 1 , Default value = NOTHING
    '''     </description></item><item><description>
    '''             clsParameter 3: Argument Name="n" , Parameter position = 2 , Default value = "Inf"
    '''     </description></item><item><description>
    '''             clsParameter 4: Argument Name="simplify" , Parameter position = 3 , Default value = "FALSE")
    '''     </description></item>
    ''' </list></summary>
    ''' 
    ''' <param name="strFunctionName">  The function name provided. </param>
    '''
    ''' <returns>   The list of clsRParameters. </returns>
```

2021-11-22 09:50 UTC, lloyddewit commented on instat/clsRLink.vb
> +        clsFormalsFunction.SetRCommand("formals")
add comment about formals here (rather than in the XML header)?
```suggestion
        'The 'formals' function returns the parameters for a specified function. 
        'for example, for the function "str_split(string, pattern, n = Inf, simplify = FALSE)", formals returns
        '    $string
        '    $pattern 
        '    $n 
        '    [1] Inf 
        '    $simplify 
        '    [1] FALSE 
        clsFormalsFunction.SetRCommand("formals")
```

2021-11-22 09:50 UTC, lloyddewit commented on instat/clsRLink.vb
> +                'End If
remove the commented out lines?

2021-11-22 09:51 UTC, lloyddewit commented
@Ivanluv I had an Internet issue and GitHub added my comments twice, sorry for that

2021-11-22 13:50 UTC, Ivanluv commented on instat/clsRLink.vb
> +                'End If
they are needed, I forgot to uncomment when testing

2021-11-22 13:51 UTC, Ivanluv commented
> @Ivanluv I had an Internet issue and GitHub added my comments twice, sorry for that

okay

2021-11-23 08:29 UTC, lloyddewit approved these changes
Thanks, looks good

2021-11-23 08:33 UTC, lloyddewit commented
@Ivanluv This PR contains 37 files. However, yesterday PR #6975 was merged. This added RScript 1.0.4 to R-Instat. Therefore 36 of the 37 files in this PR are no longer needed.
Please could you close this PR and make a new PR that branches from the latest master and only includes the clsRLink changes. We can then approve and merge the new PR.
Thanks

2021-11-23 13:57 UTC, closed without merging