Corrected and improved the Prepare > Column: Text > Split dialogue
africanmathsinitiative/R-Instat pull request #6892
Opened 2021-11-01 07:50 UTC by N-thony

Fixes #6889 
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-11-01 10:20 UTC, rdstern requested changes
@N-thony sorry I was wrong, you do need the str_split_fixed, when you fix the number of splits.  Otherwise you get a single variable with a c(  ) when there is more than one split.
I notice when you use the option for any number of splits it always puts the result at the end - and ignores the position setting.  I don't know if there is anything you can do about this?  If not, then maybe the Position button should be disabled or hidden for that option?

2021-11-01 11:30 UTC, N-thony commented
> @N-thony sorry I was wrong, you do need the str_split_fixed, when you fix the number of splits. Otherwise you get a single variable with a c( ) when there is more than one split. I notice when you use the option for any number of splits it always puts the result at the end - and ignores the position setting. I don't know if there is anything you can do about this? If not, then maybe the Position button should be disabled or hidden for that option?

Done.

2021-11-01 11:46 UTC, rdstern commented
Great, the main one is done.  Just checking on the other point, namely when getting Maximum number of components they are all at the end of the data, and not just after the column used - though it says they will be when you press that button.  I assume the current code can't cope with not knowing how many variables to include.  Maybe you can fix that, or perhaps disable the Position button for this option?

2021-11-01 11:54 UTC, N-thony commented
> Great, the main one is done. Just checking on the other point, namely when getting Maximum number of components they are all at the end of the data, and not just after the column used - though it says they will be when you press that button. I assume the current code can't cope with not knowing how many variables to include. Maybe you can fix that, or perhaps disable the Position button for this option?

Resolved

2021-11-01 12:19 UTC, rdstern commented
@N-thony that's great, but I now detect another problem.  The world_bank_pop is a good dataset to use, because that has a variable called indicator with contents like `SP.URB.TOTL`.
So I tried first without the regex, and then I ticked regex.  With your code it never runs with regex.  Your command is still: 
`split <- stringr::str_split(string=indicator, pattern=stringr::fixed("."), n=Inf, simplify=TRUE)`

With regex ticked it should become simply:
`split <- stringr::str_split(string=indicator, pattern=".", n=Inf, simplify=TRUE)`

Try it, and you will see the difference.

I am a bit concerned that is might also still be incorrect in the Find/Replace options?

2021-11-01 13:45 UTC, N-thony commented
> world_bank_pop

@rdstern I tried on my side and it works fine
![image](https://user-images.githubusercontent.com/68591383/139681531-f6d72b3a-4bd2-49c6-b6ec-a81d6e2c4ab2.png)

2021-11-01 17:14 UTC, N-thony commented
> @N-thony that's great, but I now detect another problem. The world_bank_pop is a good dataset to use, because that has a variable called indicator with contents like `SP.URB.TOTL`. So I tried first without the regex, and then I ticked regex. With your code it never runs with regex. Your command is still: `split <- stringr::str_split(string=indicator, pattern=stringr::fixed("."), n=Inf, simplify=TRUE)`
> 
> With regex ticked it should become simply: `split <- stringr::str_split(string=indicator, pattern=".", n=Inf, simplify=TRUE)`
> 
> Try it, and you will see the difference.
> 
> I am a bit concerned that is might also still be incorrect in the Find/Replace options?

@rdstern I have corrected the regex code. Please take a look.

2021-11-01 17:48 UTC, rdstern approved these changes
@N-thony if @shadrackkibet is ok, then this could be merged.

2021-11-04 06:23 UTC, N-thony commented
@HawardKetoyoMsatsi over to you.

2021-11-05 04:16 UTC, HawardKetoyoMsatsi requested changes
The code looks good. Maybe if you could reduce blank lines 15-17 of dlgSplitText.vb to one line.

2021-11-05 04:38 UTC, N-thony commented
> The code looks good. Maybe if you could reduce blank lines 15-17 of dlgSplitText.vb to one line.

Done

2021-11-05 06:57 UTC, N-thony commented
> > The code looks good. Maybe if you could reduce blank lines 15-17 of dlgSplitText.vb to one line.
> 
> Done

@HawardKetoyoMsatsi I have resolved your comment above.

2021-11-06 19:27 UTC, shadrackkibet requested changes

2021-11-06 19:27 UTC, shadrackkibet commented on instat/dlgSplitText.vb
> +        ucrChkAddKeyboard.Enabled = False
Why manual checking?

2021-11-06 19:27 UTC, shadrackkibet commented on instat/dlgSplitText.vb
> +        ucrChkIncludeRegularExpressions.SetDefaultState(False)
Do you really need this?

2021-11-06 19:27 UTC, shadrackkibet commented on instat/dlgSplitText.vb
> +        ucrChkIncludeRegularExpressions.Checked = False
Same case here.

2021-11-07 07:59 UTC, N-thony commented
@shadrackkibet I resolved your comment above. Please take a look.

2021-11-07 09:26 UTC, N-thony commented on instat/dlgSplitText.vb
> +        End Select
This is because of the value coming from the input control e.g Comma , we just need the comma symbol. I don't see another way to do that if not like this. Otherwise, you can suggest to me how to do it simply.

2021-11-07 09:32 UTC, rdstern approved these changes

2021-11-07 09:49 UTC, shadrackkibet requested changes
Under splitting into binary columns I got the following R code 
`split <- questionr::multi.split(var=village, split.char="instat.RFunction")`

@N-thony I would suggest you take time to first thoroughly test things before you even invite others to test them. Some obvious issues like the one above should be easy to detect if you test things thoroughly.

2021-11-07 09:49 UTC, shadrackkibet commented on instat/dlgSplitText.vb
> -        'ucrInputPattern.SetRDefault(Chr(34) & " " & Chr(34)) 'This is the default for clsTextComponents
Could you explain why you removed this? It is good practice to first understand why the code was added initially before removing it.

2021-11-07 09:49 UTC, shadrackkibet commented on instat/dlgSplitText.vb
> +        End If
Simply `.SetParameter` for this control.

2021-11-07 09:49 UTC, shadrackkibet commented on instat/dlgSplitText.vb
>          ucrChkAddKeyboard.Enabled = False
We encourage the hiding of controls that do not work.

2021-11-07 09:49 UTC, shadrackkibet commented on instat/dlgSplitText.vb
> +        ucrChkIncludeRegularExpressions.SetText("Include Regular Expressions")
Do we need this checkbox when splitting into binary columns?

2021-11-07 09:49 UTC, shadrackkibet commented on instat/dlgSplitText.vb
> +        End Select
This is clearly a duplication of what you've under `InitialiseDialog()`.

2021-11-08 13:30 UTC, N-thony commented on instat/dlgSplitText.vb
> +        End Select
@shadrackkibet any suggestion about this?

2021-11-08 14:14 UTC, N-thony commented
@shadrackkibet hopefully this is okay now. Take a look!

2021-11-08 14:30 UTC, N-thony commented
@shadrackkibet hopefully this is okay now? Take a look.

2021-11-11 18:42 UTC, N-thony commented
> @shadrackkibet hopefully this is okay now? Take a look.

@shadrackkibet how about this?

2021-11-16 11:05 UTC, lloyddewit requested changes

2021-11-16 11:05 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +        End Select
If you have a dictionary that defines the correct character for each description (e.g. ',' for 'Comma ,'), then you can replace this `Select` with a single line.

2021-11-16 13:23 UTC, N-thony commented on instat/dlgSplitText.vb
> +        ucrChkIncludeRegularExpressions.SetText("Include Regular Expressions")
I had a look at the code for the available option under splitting into binary and the R code, I think we don't need it. That is why is hidden when going to the splitting option

2021-11-16 13:23 UTC, N-thony commented
@lloyddewit I made the changes regarding your comment above. Please take a look.

2021-11-17 08:33 UTC, lloyddewit reviewed
Looks good, just one open question

2021-11-17 08:33 UTC, lloyddewit commented on instat/dlgSplitText.vb
> +        Else
Is the user allowed to enter patterns that are not in the pre-defined list?

2021-11-17 08:37 UTC, N-thony commented on instat/dlgSplitText.vb
> +        Else
@lloyddewit yes.

2021-11-17 08:39 UTC, lloyddewit commented
@shadrackkibet Thank you for your earlier review. There is one open comment. Please could you check that it's resolved?
I already set your other comments to resolved, I hope that's OK.
Thanks

2021-11-17 09:05 UTC, lloyddewit submitted a review, later dismissed

2021-11-17 09:07 UTC, lloyddewit commented
@rdstern There are changes since you last tested. Please could you test again? thanks

2021-11-25 14:49 UTC, rdstern requested changes
@N-thony please try again with the tidyr world bank population.  There is a variable that splits nicely into 3 with dot as the separator.  But it also works with regular expression ticked, which it shouldn't!  It currently gives split <- stringr::str_split_fixed(string=indicator, pattern=stringr::fixed("."), n=3)
so I think it is still not permitting the regular expression?

2021-11-25 15:22 UTC, N-thony commented
> @N-thony please try again with the tidyr world bank population. There is a variable that splits nicely into 3 with dot as the separator. But it also works with regular expression ticked, which it shouldn't! It currently gives split <- stringr::str_split_fixed(string=indicator, pattern=stringr::fixed("."), n=3) so I think it is still not permitting the regular expression?

@rdstern this seems to be fixed now. Please take a look. Thanks.

2021-11-25 15:56 UTC, rdstern approved these changes
I am happy now and approving.  @lloyddewit there is just a tiny code change since you accepted before.

2021-11-26 08:47 UTC, lloyddewit approved these changes

2021-11-26 08:48 UTC, lloyddewit commented
@shadrackkibet there's still an open comment from you above, so we also need your approval before merging. Please could you take a look? thanks

2021-11-26 10:09 UTC, shadrackkibet approved these changes

2021-11-26 10:38 UTC, merged