Minor improvements to the Prepare >Column:Text > Tranform Dialogue
africanmathsinitiative/R-Instat pull request #6897
Opened 2021-11-04 15:02 UTC by EstherNjeriLiberatta

Fixes issue #6890
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-11-04 17:41 UTC, rdstern approved these changes
@EstherNjeriLiberatta this is excellent.  The only very minor point is that the Pad option (and also words (that you didn't look at) don't "remember" the settings of the string.  They always return to Space ( ).
Happy to approve at the same time and hope @shadrackkibet likes what you have done.

2021-11-05 08:16 UTC, EstherNjeriLiberatta commented
@rdstern I looked into the problem. Requesting @lloyddewit to look into it. It is caused by `autoTranslate`. Thanks

![image](https://user-images.githubusercontent.com/74548350/140479226-fb619d65-f880-4351-a336-afaf14c4c9e0.png)

2021-11-05 09:19 UTC, Ivanluv commented on instat/dlgTransformText.vb
> +        ucrPnlOperation.AddToLinkedControls(ucrNudWidth, {rdoPad}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, objNewDefaultState:=20, bNewLinkedChangeToDefaultState:=
you don't need `objNewDefaultState:=20, bNewLinkedChangeToDefaultState:=True` when adding the parameters to the functions within the `setRDefaults()`.Also get rid of `bNewLinkedAddRemoveParameter:=True ` to  maintain previous state

2021-11-05 09:20 UTC, Ivanluv commented on instat/dlgTransformText.vb
> +        ucrPnlOperation.AddToLinkedControls(ucrNudWidthTrunc, {rdoTruncate}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, objNewDefaultState:=20, bNewLinkedChangeToDefa
Do the same here

2021-11-05 09:20 UTC, Ivanluv commented on instat/dlgTransformText.vb
> +        ucrPnlOperation.AddToLinkedControls(ucrNudWidthWrap, {rdoWrap}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, objNewDefaultState:=40, bNewLinkedChangeToDefaultSt
Do the same here

2021-11-05 09:26 UTC, EstherNjeriLiberatta commented on instat/dlgTransformText.vb
> +        ucrPnlOperation.AddToLinkedControls(ucrNudWidthWrap, {rdoWrap}, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True, objNewDefaultState:=40, bNewLinkedChangeToDefaultSt
Okay

2021-11-05 09:42 UTC, EstherNjeriLiberatta commented
@Ivanluv I've made the requested changes. This ready for review.

2021-11-05 09:45 UTC, Ivanluv submitted a review, later dismissed

2021-11-05 09:53 UTC, EstherNjeriLiberatta commented
@rdstern @africanmathsinitiative/developers This is ready for review.

2021-11-05 11:12 UTC, rdstern approved these changes

2021-11-06 09:49 UTC, shadrackkibet commented
@EstherNjeriLiberatta could you improve the PR title? **Improved the Prepare >Column:Text > Transform Dialogue** is too general. Add some specific details to specify what changed.

2021-11-06 10:28 UTC, EstherNjeriLiberatta commented
@shadrackkibet Done. I hope it's better? 
I also made a few changes on the Case and Pad options.

2021-11-06 19:42 UTC, shadrackkibet requested changes

2021-11-06 19:42 UTC, shadrackkibet commented on instat/dlgTransformText.vb
> +                ucrBase.OKEnabled(True)
Could make this one line to reduce the lines of code i.e `rdoTruncate.Checked OrElse rdoTrim.Checked OrElse rdoWrap.Checked Then`

2021-11-06 20:20 UTC, EstherNjeriLiberatta commented
@shadrackkibet Done.

2021-11-07 09:14 UTC, rdstern approved these changes
Looks fine still

2021-11-07 09:20 UTC, shadrackkibet approved these changes

2021-11-07 09:21 UTC, merged