Changed the function on the Infilling daily climatic plus minor improvement
africanmathsinitiative/R-Instat pull request #6935
Opened 2021-11-11 14:03 UTC by N-thony

Fixes #6915
@dannyparsons @rdstern I have changed chillR::patch_daily_temperatures() to the new function chillR::patch_daily_temps() as requested in the corresponding issue. Please take a look.
@africanmathsinitiative/developers this is ready for review. Thanks.

2021-11-12 06:42 UTC, rdstern submitted a review, later dismissed
@N-thony this seems to work fine.  I am not sure what the new feature brings, but think it could be important and wonder whether we gamble and include it this time?  Over to you @dannyparsons

2021-11-12 10:36 UTC, dannyparsons commented
I'd like to be cautious and not change this last minute, as this is an important feature and I don't yet understand why there was a completely new function. The additional parameter looks useful. It's great this change was done so quickly. I suggest merging it soon after the release and testing well in R the two functions and the new parameter.

2021-11-15 10:33 UTC, lloyddewit commented
@Ivanluv Please could you peer review? thanks

2021-11-15 11:22 UTC, Ivanluv commented on instat/dlgInfillMissingValues.vb
> +        If ucrChkTimeInterval.Checked AndAlso ucrNudTimeInterval.GetText <> "" AndAlso ucrInputTimeInterval.GetText <> "" Then
Could use ucrNudTimeInterval.isEmpty()  and ucrInputTimeInterval.isEmpty() instead

2021-11-15 11:23 UTC, Ivanluv commented
@shadrack could you help me in reviewing the data object code

2021-11-15 11:37 UTC, N-thony commented on instat/dlgInfillMissingValues.vb
> +        If ucrChkTimeInterval.Checked AndAlso ucrNudTimeInterval.GetText <> "" AndAlso ucrInputTimeInterval.GetText <> "" Then
@Ivanluv I have resolved this.

2021-11-15 12:14 UTC, Ivanluv reviewed
The vb code looks okay from my end

2021-11-16 09:55 UTC, lloyddewit submitted a review, later dismissed

2021-11-16 09:58 UTC, lloyddewit commented
@rdstern just one small change since your last approval, that shouldn't have affected the functionality. Please could you test/approve again?

@shadrackkibet I couldn't see anything controversial in the R code so I suggest that we go ahead and merge anyway.

Thanks!

2021-11-16 10:59 UTC, dannyparsons commented
I'd just like to check the difference between the two functions before we merge, particularly as this is an important feature for WMO workshops.

2021-11-25 15:45 UTC, rdstern requested changes
@N-thony 2 small changes.
1) The setting of the new parameter isn't remembered when you return to the dialogue.
2) Could you change the saving control.  With save single (in the same dialogue) it includes the position button.  It would be good to use that as well here.

2021-11-25 17:23 UTC, N-thony commented
> @N-thony 2 small changes.
> 
> 1. The setting of the new parameter isn't remembered when you return to the dialogue.
> 2. Could you change the saving control.  With save single (in the same dialogue) it includes the position button.  It would be good to use that as well here.

@rdstern I had a quick look into the R code and in order to make the change concerning item 2. I needed to edit the R code and this result in the fact that we will not have the following output again in the Output Window.
@dannyparsons what do you think of that change?
![image](https://user-images.githubusercontent.com/68591383/143482190-eeb557f9-58b3-4efc-b937-9b6b370888a0.png)

2021-11-25 23:25 UTC, dannyparsons commented
Looks good, but what is the `NULL` in the output?

2021-11-25 23:47 UTC, rdstern commented
@N-thony are you saying you now get no output at all?  I did like the one-line summary and (in general) like to have something in the output window from the functions that change the data frame.

2021-11-26 06:54 UTC, N-thony commented
@rdstern as we discussed some minute ago, I put back the input new column control and got rid of the `NULL` in the output when printing the one-lin summary. Please take a look?

2021-11-27 09:29 UTC, rdstern approved these changes
Check with @dannyparsons but I would be happy to see this merged now.

2021-11-29 07:24 UTC, dannyparsons approved these changes

2021-11-29 07:25 UTC, merged