Changed output window to be a tab based window.
africanmathsinitiative/R-Instat pull request #6958
Opened 2021-11-17 16:36 UTC by ChrisMarsh82

I have added R-Script as it is needed to test these changes however that work is done under  #6953

@dannyparsons Once you have a chance to look through this it would be good to decide how the main output tab should work. It is set up to be a log at the moment i.e. can't change anything. This makes sense in the way the OutputLogger is designed. If this needs to change may need to re-think the structure. Maybe another option would be to decide which tabs are the active recorders? i.e. which tabs will receive the new outputs?

2021-11-18 09:52 UTC, lloyddewit commented
@ChrisMarsh82 As I mentioned yesterday in PR #6953 , I made a new RScript NuGet package that does not include the XUnit dependencies (v. 1.0.4). This should reduce the number of dependencies from 32 to 5.

I suggest that you make a new PR with RScript 1.0.4, this will reduce the number of files in the PR and make it more manageable. You can then close both this PR and PR #6953 .

2021-11-18 10:08 UTC, lloyddewit commented
@ChrisMarsh82 I had a quick look through the files. If you make the changes above, then there are about 13 VB files for me to review.
If you can make the new PR this week, then I can aim to finish my review by mid next week. Would that be OK?

2021-11-21 21:48 UTC, dannyparsons commented
Looks good. I haven't found any broken or missing functionality. I've tried different kinds of output and didn't find any issues.

@africanmathsinitiative/developers We need more reviews on this as it's a big change. Particularly to check for any breaking changes.

@rdstern What do you think the name of the main tab should be? Maybe `Main`? I don't think `Output` is right.

A few comments:

1. Does there have to be scroll bars for the blocks? It makes it a bit harder to navigate and also reduces the space on the screen. I would be happy just to have the long output without the additional scroll bars.

![image](https://user-images.githubusercontent.com/11214914/142779203-4181d5a5-9732-4332-b688-56d7c5b80786.png)

2. After running a command it should scroll to the bottom. It doesn't currently.
3. The sizes seem quite different in this new output than the previous one. The output was a lot bigger than before. Not a problem, but we may need to adjust the default sizes for comments, code and output. 
4. The output window seems to refresh when a dialog is closed without running a command. It should only refresh when a command has been run.
5. I would like to be able to delete an item from the Output tab. For example, the first output I made was way too big and didn't display nicely and make the whole window a bit messy, so I wanted to delete it and do it again.
6. There used to be a right click menu in the Output Window. Some of these options will still be needed.
![image](https://user-images.githubusercontent.com/11214914/142779998-1897648a-1451-4a0b-96a0-85efc30d11ba.png)
7. `Ctrl + C` when highlighting text doesn't seem to work anymore.
**Other comments that are non essential and could be addressed in future work**
8. When I saved the output as an RFT it was 96MB but it only had one graph in and some text output. That seems quite big. Not sure if that was happening before too. Not a serious problem but the file is bigger than I expected.
9. The multiple tabs works well. It would be good to be able to delete a secondary tab directly. I'm not sure the tab should be deleted when all the items are deleted - can be discussed.
10. It would be nice to be able to scroll up and down the window with the mouse wheel, or keyboard up/down arrows.
11. Select/Deselect all buttons would be nice.

2021-11-22 09:48 UTC, N-thony commented
> Looks good. I haven't found any broken or missing functionality. I've tried different kinds of output and didn't find any issues.
> 
> @africanmathsinitiative/developers We need more reviews on this as it's a big change. Particularly to check for any breaking changes.
> 
> @rdstern What do you think the name of the main tab should be? Maybe `Main`? I don't think `Output` is right.
> 
> A few comments:
> 
> 1. Does there have to be scroll bars for the blocks? It makes it a bit harder to navigate and also reduces the space on the screen. I would be happy just to have the long output without the additional scroll bars.
> 
> ![image](https://user-images.githubusercontent.com/11214914/142779203-4181d5a5-9732-4332-b688-56d7c5b80786.png)
> 
> 2. After running a command it should scroll to the bottom. It doesn't currently.
> 3. The sizes seem quite different in this new output than the previous one. The output was a lot bigger than before. Not a problem, but we may need to adjust the default sizes for comments, code and output.
> 4. The output window seems to refresh when a dialog is closed without running a command. It should only refresh when a command has been run.
> 5. I would like to be able to delete an item from the Output tab. For example, the first output I made was way too big and didn't display nicely and make the whole window a bit messy, so I wanted to delete it and do it again.
> 6. There used to be a right click menu in the Output Window. Some of these options will still be needed.
>    ![image](https://user-images.githubusercontent.com/11214914/142779998-1897648a-1451-4a0b-96a0-85efc30d11ba.png)
> 7. `Ctrl + C` when highlighting text doesn't seem to work anymore.
>    **Other comments that are non essential and could be addressed in future work**
> 8. When I saved the output as an RFT it was 96MB but it only had one graph in and some text output. That seems quite big. Not sure if that was happening before too. Not a serious problem but the file is bigger than I expected.
> 9. The multiple tabs works well. It would be good to be able to delete a secondary tab directly. I'm not sure the tab should be deleted when all the items are deleted - can be discussed.
> 10. It would be nice to be able to scroll up and down the window with the mouse wheel, or keyboard up/down arrows.
> 11. Select/Deselect all buttons would be nice.

12. I have tried to clear the output window from Tools > Clear Output Window and it seems to not work yet
     
![image](https://user-images.githubusercontent.com/68591383/142839393-0e1c324b-60c0-4576-a4e4-f1f7319ecf05.png)

2021-11-22 11:10 UTC, dannyparsons commented
@N-thony have you added comments here? I just see a quote of my comment.

2021-11-22 11:11 UTC, N-thony commented
> @N-thony have you added comments here? I just see a quote of my comment.

yes

2021-11-22 11:35 UTC, dannyparsons commented
I don't see your comments, can you repost them?

2021-11-22 11:39 UTC, N-thony commented
12. I have tried to clear the output window from Tools > Clear Output Window and it seems to not work yet
     
![image](https://user-images.githubusercontent.com/68591383/142839393-0e1c324b-60c0-4576-a4e4-f1f7319ecf05.png)

2021-11-22 11:57 UTC, dannyparsons commented
Thanks, sorry I didn't see that before.

2021-11-24 08:04 UTC, lloyddewit commented
> @ChrisMarsh82 As I mentioned yesterday in PR #6953 , I made a new RScript NuGet package that does not include the XUnit dependencies (v. 1.0.4). This should reduce the number of RScript dependencies from 32 to 5.
> 
> I suggest that you make a new PR with RScript 1.0.4, this will reduce the number of files in the PR and make it more manageable. You can then close both this PR and PR #6953 .

@ChrisMarsh82 Please could you close this PR and make a new PR without the XUnit dependencies? If you do this, then I can peer review the code in the new PR, thanks

2021-11-24 09:37 UTC, ChrisMarsh82 commented
@lloyddewit all dependencies are taken out now

2021-11-24 11:37 UTC, lloyddewit requested changes
@ChrisMarsh82 this looks good, I like the way you implemented this. Here are some initial comments.

2021-11-24 11:37 UTC, lloyddewit commented on instat/Model/Output/clsOutputLogger.vb
> +        If filteredList Is Nothing And bCreate Then
Will the line above always set `filteredList` to a a found list or a default list? Will `filteredList` ever be `Nothing`?

2021-11-24 11:37 UTC, lloyddewit commented on instat/Model/Output/clsOutputLogger.vb
> +        If _filteredOutputs.Where(Function(x) x.StrName = strListName).Any() Then
```suggestion
        If Trim(strListName) Is "" OrElse
            _filteredOutputs.Where(Function(x) x.StrName = strListName).Any() Then
```

2021-11-24 11:37 UTC, lloyddewit commented on instat/My Project/app.manifest
> +﻿<?xml version="1.0" encoding="utf-8"?>
why is this file needed in this PR? why didn't R-Instat require it before?

2021-11-24 11:37 UTC, lloyddewit commented on instat/UserControl/ucrOutputPage.vb
> +            Dim elemets As New List(Of clsOutputElement)
```suggestion
            Dim elements As New List(Of clsOutputElement)
```

2021-11-24 11:37 UTC, lloyddewit commented on instat/UserControl/ucrOutputPage.vb
> +    ''' Copys selected elenments to clipboard
```suggestion
    ''' Copies selected elenments to clipboard
```

2021-11-24 16:51 UTC, lloyddewit requested changes
I finished my review

2021-11-24 16:51 UTC, lloyddewit commented on instat/UserControl/ucrOutputPages.vb
> +        Set(ByVal value As InstatOptions)
what is the purpose of 'ByVal' here?

2021-11-24 16:51 UTC, lloyddewit commented on instat/UserControl/ucrOutputPages.vb
> +        _allOutputPages.Remove(found)
```suggestion
        For Each outputPage In _allOutputPages
            If outputPage.Tag = tabName Then
                _allOutputPages.Remove(outputPage)
                Exit For
            End If
        Next
```

2021-11-24 16:51 UTC, lloyddewit commented on instat/UserControl/ucrOutputPages.vb
> +            strTabName = strTabName + "1"
```suggestion
            strTabName &= "1"
```
This line will make names like "tabName1", "tabName11", "tabName111" etc.
Would "tabName1", "tabName2" etc be better?

2021-11-24 16:51 UTC, lloyddewit commented on instat/UserControl/ucrOutputPages.vb
> +        For Each element In _selectedOutputPage.SelectedElements
Should this explicitly specify order by ascending ID (to be consistent with line 230 above)?

2021-11-24 16:51 UTC, lloyddewit commented on instat/Translations.vb
> -        HandleError(TranslateWinForm.clsTranslateWinForm.TranslateMenuItems(frmMain.ucrOutput.Name, frmMain.ucrOutput.mnuContextRTB.Items, strDbPath, strLanguageCode))
Where are the new output windows translated?

2021-11-24 16:51 UTC, lloyddewit commented on instat/Translations.vb
> +        Dim strTranslationsPath As String = String.Concat(System.Windows.Forms.Application.StartupPath, "/translations")
I'm assuming that `/` works with both Windows and Linux, is that correct?

2021-11-29 11:32 UTC, ChrisMarsh82 commented on instat/Model/Output/clsOutputList.vb
> +        If outputElement.Id < _output.Count Then
They do start at 1
outputElement.Id = filteredList.Output.Count + 1

2021-11-29 11:32 UTC, ChrisMarsh82 commented on instat/Model/Output/clsOutputList.vb
> +        If outputElement.Id > 1 Then
They do start at 1
outputElement.Id = filteredList.Output.Count + 1

2021-11-29 11:36 UTC, ChrisMarsh82 commented on instat/Model/Output/clsOutputLogger.vb
> +        If filteredList Is Nothing And bCreate Then
It calls GetFilteredList if it exists or not. The optional bCreate decides if it should be created or return nothing if it doesn't exist

2021-11-29 11:37 UTC, ChrisMarsh82 commented on instat/UserControl/ucrOutputPage.vb
> +            Dim elemets As New List(Of clsOutputElement)
Changed

2021-11-29 11:42 UTC, ChrisMarsh82 commented on instat/UserControl/ucrOutputPages.vb
> +        Set(ByVal value As InstatOptions)
This is added automatically by Visual Studio. Then visual studio tells you it's not needed. Will take it out.

2021-11-29 11:45 UTC, ChrisMarsh82 commented on instat/UserControl/ucrOutputPages.vb
> +        For Each element In _selectedOutputPage.SelectedElements
Added in

2021-11-29 12:58 UTC, ChrisMarsh82 commented on instat/My Project/app.manifest
> +﻿<?xml version="1.0" encoding="utf-8"?>
removed

2021-11-29 12:59 UTC, ChrisMarsh82 commented on instat/My Project/app.manifest
> +﻿<?xml version="1.0" encoding="utf-8"?>
removed

2021-11-29 17:11 UTC, ChrisMarsh82 commented on instat/Translations.vb
> +        Dim strTranslationsPath As String = String.Concat(System.Windows.Forms.Application.StartupPath, "/translations")
yep

2021-11-29 17:38 UTC, ChrisMarsh82 commented on instat/Translations.vb
> -        HandleError(TranslateWinForm.clsTranslateWinForm.TranslateMenuItems(frmMain.ucrOutput.Name, frmMain.ucrOutput.mnuContextRTB.Items, strDbPath, strLanguageCode))
Added translations back in

2021-11-29 21:39 UTC, ChrisMarsh82 commented
Can't resolve the merge issue. Tried to use command line but it either wanted me to create a new pull request with all the changes duplicated or just didn't notice the conflict. - frmOutputWindow should just be deleted.

@dannyparsons  I fixed some of the issues however the refreshing when the dialog closes, scroll bars on the elements and font sizes don't seem to be an issue for me. I changed the dialogs running on 100% zoom to see if this makes any difference. Hopefully we can chat first thing tomorrow about it.

2021-11-30 07:14 UTC, dannyparsons commented
Could you maybe manually undo the changes to the conflicting files? It's just two and the changes are small. Then we could merge and redo the changes as needed.

2021-11-30 07:43 UTC, merged