Detecting and Removing empty columns and rows while importing data.
africanmathsinitiative/R-Instat pull request #6966
Opened 2021-11-19 09:02 UTC by anastasia-mbithe

Hello @rdstern  and @shadrackkibet I added the remove_empty() function  in the import dialog but it's still in progress. There are some issues to be sorted out before its ready for review. Thanks

2021-11-19 12:45 UTC, anastasia-mbithe commented
@rdstern  and @shadrackkibet  you can have a look at it now, I feel its ready for reviews.

2021-11-22 10:13 UTC, lloyddewit commented
@HawardKetoyoMsatsi Please could you peer review? thanks

2021-11-23 16:56 UTC, HawardKetoyoMsatsi requested changes

2021-11-26 08:39 UTC, anastasia-mbithe commented
The functions were written as such before, am not sure if its fine changing all the function names in the dialog, so that it can be consistent with the other dialogs.

2021-11-26 09:52 UTC, lloyddewit commented
> The functions were written as such before, am not sure if its fine changing all the function names in the dialog, so that it can be consistent with the other dialogs.

@HawardKetoyoMsatsi @anastasia-mbithe Thank you for the review and feedback. I agree that we should follow the naming conventions. For example, `clsDetectEmptyCols` is an RFunction so it should be `clsDetectEmptyColsFunction`. This increases readability. 

@anastasia-mbithe please could you ensure that all the newly added variables follow this convention? You are correct that there are many existing variables that don't follow this convention. We should change these if/when we refactor this dialog. In general, I don't think we should refactor dialogs whenever we make a small change to them. This would risk introducing regression.

@HawardKetoyoMsatsi Do you find the above a reasonable way ahead?
Thanks!

2021-11-26 09:53 UTC, lloyddewit commented on instat/dlgImportDataset.vb
>          clsFileNamesWithExt = New RFunction
I don't think we need to rename variables that already existed before this PR (see my comment below)

2021-11-27 11:58 UTC, anastasia-mbithe commented
@lloyddewit and @HawardKetoyoMsatsi , I changed the naming of the two functions that were affected, you can have a look at it.

2021-11-30 08:35 UTC, lloyddewit requested changes
@anastasia-mbithe this looks very good. I just have one comment

2021-11-30 08:35 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +        End If
Is this function more readable if we invert the main 'If' (change the 'AndAlso's to 'OrElse's)?
Can we also add line breaks into the main 'If'?
```suggestion
        If strFileExtension = ".rds" _
                OrElse ucrBase.clsRsyntax.clsBaseFunction Is clsImportExcelMulti _
                OrElse ucrBase.clsRsyntax.clsBaseFunction Is clsImportMultipleFiles _
                OrElse ucrBase.clsRsyntax.clsBaseFunction Is clsImportMultipleTextFiles Then
            ucrChkDropEmptyCols.Visible = False
            ucrBase.clsRsyntax.SetBaseRFunction(clsPreviousBaseFunction)
        Else
            ucrChkDropEmptyCols.Visible = True
            If ucrChkDropEmptyCols.Checked Then
                Dim clsTempFunction As RFunction = clsPreviousBaseFunction.Clone
                clsTempFunction.RemoveAssignTo()
                clsTempFunction.bExcludeAssignedFunctionOutput = False
                clsPipeOperator.AddParameter("y", clsRFunctionParameter:=clsTempFunction, iPosition:=0)
                ucrBase.clsRsyntax.SetBaseROperator(clsPipeOperator)
            Else
                ucrBase.clsRsyntax.SetBaseRFunction(clsPreviousBaseFunction)
            End If
        End If
```

2021-12-01 07:49 UTC, anastasia-mbithe commented
@lloyddewit  hello, I just made the change and still works fine. Thank you.

2021-12-01 08:43 UTC, lloyddewit approved these changes

2021-12-01 08:45 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2021-12-04 08:50 UTC, rdstern approved these changes
I am happy to approve, though I note it only deletes variables with NA.  So empty character variables are still read.
I do not want issue 6883 to be closed though, because I still would like to be able to remove empty rows and variables (including empty character variables, once they are in R-Instat.  This could usefully be added to the Prepare > Delete Columns/Rows dialogue as suggested in this issue.

2021-12-07 10:35 UTC, merged