Bug fixed on reading data sets from Library
africanmathsinitiative/R-Instat pull request #6974
Opened 2021-11-22 08:12 UTC by N-thony

Fixes #6969
@rdstern this fixes the bug that was appearing when trying to load the data library especially in the case described in the corresponding issue. Could you take a look? Thanks.

2021-11-22 11:12 UTC, N-thony commented
> Fixes #6969 @rdstern this fixes the bug that was appearing when trying to load the data library especially in the case described in the corresponding issue. Could you take a look? Thanks.

2021-11-22 11:13 UTC, lloyddewit approved these changes

2021-11-22 11:13 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +        Dim strLength As Integer = strValue.IndexOf(")") - startIndex
R-Instat naming convention for integers is `iStartIndex` etc.

2021-11-22 11:19 UTC, N-thony commented on instat/dlgFromLibrary.vb
> +        Dim strLength As Integer = strValue.IndexOf(")") - startIndex
@lloyddewit I have made the change.

2021-11-22 11:29 UTC, lloyddewit requested changes

2021-11-22 11:29 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +        Dim strLength As Integer = strValue.IndexOf(")") - iStartIndex
naming convention?

2021-11-23 09:09 UTC, lloyddewit approved these changes

2021-11-25 08:37 UTC, rdstern approved these changes
Nice.  I also tested on the survey package that has a similar situation and they now read ok too.

2021-11-26 08:44 UTC, merged