Improved the Climatic > Prepare > Conversions dialogue
africanmathsinitiative/R-Instat pull request #6985
Opened 2021-11-25 10:21 UTC by N-thony

Fixes #6970
@africanmathsinitiative/developers @rdstern I have made the improvement regarding the corresponding issue. This is ready for review. Thanks.

2021-11-26 10:19 UTC, lloyddewit commented
@rdstern Please could you test?
@HawardKetoyoMsatsi Please could you review?
Thanks

2021-11-27 09:49 UTC, rdstern requested changes
@N-thony that's great - it all works already, including just a single number.
So just some cosmetics on that option
a) The saving is still there, even though it isn't used.  So the bottom line should be hidden.
b) Similarly hide the option to use a variable in the set of N,S,E,W options.  You can't have a variable there when you are typing the lat or long coordinates.
c) I tried typing 6 degrees and 20 minutes and it gives many decimals in the output.  i.e. -6.3333333333.  I couldn't find the function to see whether there is an argument to limit the precision.  If not, then you could issue the command as round(   ,3) say.

2021-11-29 11:32 UTC, N-thony commented
@rdstern I resolved your comments above and made the change on the use of the input combo for direction as we discussed this morning. Please take a look. Thanks.

2021-12-04 08:35 UTC, rdstern submitted a review, later dismissed
Looks ok now.  Great!

2021-12-07 10:38 UTC, lloyddewit commented
@HawardKetoyoMsatsi reminder: please can you review? thanks

2021-12-14 07:22 UTC, HawardKetoyoMsatsi requested changes

2021-12-14 07:22 UTC, HawardKetoyoMsatsi commented on instat/dlgConversions.vb
> +    Private Sub ucrPnlConversions_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrPnlConversions.ControlContentsChanged, ucrReceiverElement.ControlContentsChanged, ucrReceiverDate.Con
Add ucrSaveConversions.ControlContentChanged here?

2021-12-14 07:31 UTC, N-thony commented on instat/dlgConversions.vb
> +    Private Sub ucrPnlConversions_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrPnlConversions.ControlContentsChanged, ucrReceiverElement.ControlContentsChanged, ucrReceiverDate.Con
@HawardKetoyoMsatsi thanks, I resolved it. Please take a look.

2022-01-04 11:19 UTC, lloyddewit requested changes

2022-01-04 11:19 UTC, lloyddewit commented on instat/dlgConversions.vb
> +            If (Not ucrReceiverDegrees.IsEmpty AndAlso ucrSaveConversions.IsComplete AndAlso ucrChkVariable.Checked) OrElse (Not ucrChkVariable.Checked AndAlso Not ucrInputDegree.IsEmpty) Then
Split over multiple lines so that we don't exceed 100 colums?
Please could you do the same for line 284 (even though it's not your code)? thanks

2022-01-04 11:31 UTC, N-thony commented on instat/dlgConversions.vb
> +            If (Not ucrReceiverDegrees.IsEmpty AndAlso ucrSaveConversions.IsComplete AndAlso ucrChkVariable.Checked) OrElse (Not ucrChkVariable.Checked AndAlso Not ucrInputDegree.IsEmpty) Then
Thanks @lloyddewit, I resolved this.

2022-01-04 11:46 UTC, lloyddewit approved these changes

2022-01-04 11:48 UTC, lloyddewit commented
@rdstern Since you last approved, there has just been a couple of small changes that should not have affected the functionality. Please could you test/approve again? thanks

2022-01-04 15:18 UTC, rdstern approved these changes
Looks good

2022-01-05 10:40 UTC, merged