Added option to use DataViewGirds if Linux
africanmathsinitiative/R-Instat pull request #6991
Opened 2021-11-28 20:09 UTC by ChrisMarsh82

Added IGrid interface so that grids can be changed easily between DataViewGrid and Reo Grid. 
IGrid is used by the user control(ucrDataView, ucrColumnMetadata, and ucrDataframeMetadata) The ReoGrid and DataViewGrid implement the interface.

Issues within the DataViewGrid regarding editing the grid directly so have disabled for now

@dannyparsons having issues with setting SheetTabWidth, Can't work out why it keeps resetting.

2021-11-29 10:03 UTC, dannyparsons commented
Thanks for this. Here's a few things I noticed:

**Windows Grid**
1. The sheets tab is not visible by default when I loaded a dataset. I had to reduce the size of the scroll bar to be able to see it.
2. The font seems to be different than before? Not a problem but probably safer to keep as it was.

![image](https://user-images.githubusercontent.com/11214914/143839546-7f644a2d-a0c8-49ec-9bb3-fbbfba4ba954.png)

3. When I had a filter, the info text was too long to fit in the Data View unless I make it bigger than half the screen. Can we reduce the text size or have it dynamically reduce?

![image](https://user-images.githubusercontent.com/11214914/143840520-aa1faa98-1d1d-4872-a0cc-662c12640905.png)

4. Issue #6921 has reappeared. I think it just needs the forced refresh done in #6933 

Now going to look at the Linux grid...

2021-11-29 10:40 UTC, dannyparsons commented
I've looked at the Linux grid too. No further issues found. It's very nice that the sheet tabs are underneath the sheet scroll bar, I wish we had that in ReoGrid too!

2021-11-29 10:41 UTC, dannyparsons commented
Note that 3. was a problem before this change.

2021-11-29 10:56 UTC, lloyddewit requested changes

2021-11-29 10:56 UTC, lloyddewit commented on instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
> +        End If
combine into single `if` (see above)?

2021-11-29 10:56 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    Private Property IGrid_Enabled As Boolean Implements IGrid.Enabled
```suggestion
    Private Property Grid_Enabled As Boolean Implements IGrid.Enabled
```

2021-11-29 10:56 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    Private Property IGrid_Visible As Boolean Implements IGrid.Visible
```suggestion
    Private Property Grid_Visible As Boolean Implements IGrid.Visible
```

2021-11-29 10:56 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +        End If
```suggestion
        End If
        Return Nothing
```

2021-11-29 10:56 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +    Public Function WorksheetCount() As Integer Implements IDataViewGrid.WorksheetCount
```suggestion
    Public Function GetWorksheetCount() As Integer Implements IDataViewGrid.WorksheetCount
```

2021-11-29 10:56 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataframeMetadataReoGrid.vb
> +    Private lstNonEditableColumns As New List(Of String)
where is this list populated?

2021-11-29 10:56 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataframeMetadataReoGrid.vb
> +    Private Sub Worksheet_AfterCellEdit(sender As Object, e As CellAfterEditEventArgs)
remove underscores from this and following subs?

2021-11-29 10:56 UTC, lloyddewit commented on instat/ucrColumnMetadata.vb
> +        ' If True Then
delete?

2021-11-29 10:56 UTC, lloyddewit commented on instat/ucrDataFrameMetadata.vb
> +        'If True Then
delete?

2021-11-29 21:42 UTC, ChrisMarsh82 commented on instat/ucrColumnMetadata.vb
> +        ' If True Then
This is here on purpose so we can quickly change between Reo and dataview grids.

2021-11-29 21:43 UTC, ChrisMarsh82 commented on instat/ucrDataFrameMetadata.vb
> +        'If True Then
This is here on purpose so we can quickly change between Reo and dataview grids.

2021-11-29 21:51 UTC, ChrisMarsh82 commented on instat/Interface/IDataframeMetaDataGrid.vb
> +    Sub SetMainWorksheetUp(strWorksheetName As String)
This is confusing I will change it to SetupMainWorksheet. It did make sense if you read it in a Yorkshire accent.

2021-11-29 21:51 UTC, ChrisMarsh82 commented on instat/Interface/IDataViewGrid.vb
> +    Function WorksheetCount() As Integer
Changed

2021-11-29 21:51 UTC, ChrisMarsh82 commented on instat/Interface/IGrid.vb
> +    Function GetWorksheet(name As String) As clsWorksheetAdapter
Changed

2021-11-29 21:51 UTC, ChrisMarsh82 commented on instat/Interface/IGrid.vb
> +    Property Visible() As Boolean
Changed

2021-11-29 21:54 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +    Public Function WorksheetCount() As Integer Implements IDataViewGrid.WorksheetCount
Changed

2021-11-29 21:56 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/ReoGrid/ucrDataframeMetadataReoGrid.vb
> +    Private Sub Worksheet_AfterCellEdit(sender As Object, e As CellAfterEditEventArgs)
This is standard for Events. It is used in all the other events. i.e. controlName_Click

2021-11-29 22:02 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
> +    Private Property IGrid_Visible As Boolean Implements IGrid.Visible
Auto generated

2021-11-29 22:03 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
> +    Public Function AddNewWorksheet(name As String) As clsWorksheetAdapter Implements IGrid.AddNewWorksheet
Done

2021-11-29 22:03 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
> +    Public Function GetGrid(worksheetName As String) As DataGridView
Done

2021-11-29 22:04 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
> +                tcTabs.SelectedTab = tabPage
Updated to exit loop

2021-11-29 22:06 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
> +        Dim p = tcTabs.PointToClient(Cursor.Position)
updated p and r

2021-11-29 22:07 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    Private Property IGrid_Enabled As Boolean Implements IGrid.Enabled
Auto generated

2021-11-29 22:07 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    Private Property IGrid_Visible As Boolean Implements IGrid.Visible
Auto generated

2021-11-29 22:10 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
> +        End If
done

2021-11-30 10:27 UTC, dannyparsons approved these changes
Tested and works well so merging.

2021-11-30 10:27 UTC, merged