Returning the quarter abbr as factor on the Use Date Dialogue
africanmathsinitiative/R-Instat pull request #7030
Opened 2021-12-02 11:08 UTC by N-thony

Fixes #7027 
@dannyparsons please take a look. Thanks

2021-12-02 11:24 UTC, dannyparsons requested changes

2021-12-02 11:24 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +      self$add_columns_to_data(col_name = col_name, col_data = make_factor(quarter_labels), adjacent_column = adjacent_column, before = FALSE)
This won't ensure that the levels are in the right order. We should specify the levels explicitly to ensure they are correct.
Also, looking at the above I also see why the code runs very slowly for this. Because it is looping for each value, which is extremely inefficient.
There are much simpler ways of changing the values.
I think this needs to be redone in a simpler and more efficient way.
@shadrackkibet Could you look at this too?

This should only need to be two lines, something like:
```r
q <- lubridate::quarter(col_data, with_year = with_year, fiscal_start = s_start_month)
q <- quarter_label(q, fiscal_start = s_start_month)
```
The second function just does a replace of the numeric values with the labels.

2021-12-02 13:18 UTC, N-thony commented on instat/static/InstatObject/R/data_object_R6.R
> +      self$add_columns_to_data(col_name = col_name, col_data = make_factor(quarter_labels), adjacent_column = adjacent_column, before = FALSE)
@dannyparsons I think something like this should work fine

  if (start_month %in% s_month){
    switch(start_month,
      "1"={ qtr <- dplyr::recode(quarter, "1" = "JFM", "2" = "AMJ", "3" = "JAS", "4" = "OND")},
       .
       .
       .
    )
    return(qtr)
  }

2021-12-02 14:14 UTC, N-thony commented
@dannyparsons I made the improvement to the `get_quarter_label ` function following your comment above. Please take a look.

2021-12-02 14:45 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +      "12"= { qtr <- plyr::revalue(x = factor(quarter), replace=c("1" = "DJF", "2" = "MAM", "3" = "JJA", "4" = "SON"))},
@dannyparsons I will look into this.

2021-12-02 16:06 UTC, N-thony commented on instat/static/InstatObject/R/data_object_R6.R
> +      "12"= { qtr <- plyr::revalue(x = factor(quarter), replace=c("1" = "DJF", "2" = "MAM", "3" = "JJA", "4" = "SON"))},
@shadrackkibet I'm trying to improve my understanding of R programming.  I have a small change regarding danny's comment. I have pushed so that you can appreciate it but I will wait also for you.

2021-12-06 07:49 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +      "12"= { qtr <- plyr::revalue(x = factor(quarter), replace=c("1" = "DJF", "2" = "MAM", "3" = "JJA", "4" = "SON"))},
Thanks. Should I go ahead and look into it or you are still making changes?

2021-12-06 07:51 UTC, N-thony commented on instat/static/InstatObject/R/data_object_R6.R
> +      "12"= { qtr <- plyr::revalue(x = factor(quarter), replace=c("1" = "DJF", "2" = "MAM", "3" = "JJA", "4" = "SON"))},
Please, go ahead.

2021-12-17 16:10 UTC, N-thony commented on instat/static/InstatObject/R/data_object_R6.R
> +      "12"= { qtr <- plyr::revalue(x = factor(quarter), replace=c("1" = "DJF", "2" = "MAM", "3" = "JJA", "4" = "SON"))},
@shadrackkibet how about this?

2022-01-03 10:10 UTC, lloyddewit commented
@shadrackkibet please could you take a look at this when you have time? thanks

2022-01-21 22:53 UTC, merged

2022-02-09 16:37 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +  mabb <- c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D", "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")
@N-thony @shadrackkibet Make use of `month_abb_english` to avoid writing this out. There definitively shouldn't be a manual repetition of any vector when you can use `rep`.

Replace with:
`rep(substr(month_abb_english, 1, 1), 2)`

2022-02-10 09:44 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +  mabb <- c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D", "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")
@dannyparsons this was changed a while ago see https://github.com/africanmathsinitiative/R-Instat/pull/7137

2022-02-10 10:22 UTC, dannyparsons commented on instat/static/InstatObject/R/data_object_R6.R
> +  mabb <- c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D", "J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")
Ah, great, I thought this was the update, thanks.