Added column selection feature into the right clicks
africanmathsinitiative/R-Instat pull request #7033
Opened 2021-12-02 13:21 UTC by shadrackkibet

@ChrisMarsh82 here are the changes I have made while adding column selection into the right clicks for Data View and Column Metadata. Works well on windows from my end.  I am not sure what I should do on the Linux side of things.

I am looking forward to your guidance. We can do a quick call if that is much more efficient.

Thanks.

2021-12-02 13:28 UTC, shadrackkibet commented on instat/Model/DataFrame/clsDataFrameFilter.vb
> +    End Function
@ChrisMarsh82 I was a bit in a catch 22 situation here. Since we have Column Selections and Filters. Should we create a new class for column selections since we have `clsDataFrameFilter` or we rename this class to include column selections?

2021-12-02 15:44 UTC, ChrisMarsh82 commented
@shadrackkibet looks good from the initial look of it and the way you have done it means it shouldn't be any different in Linux. 
I think putting it in the filter will work well. I need to check a few things that I should be able to do Monday. 

Question: I can't see where it would be displayed to users that they are looking at a subset of columns. Should this be added to the lblColDisplay in SetDisplayLabels?

2021-12-02 15:50 UTC, shadrackkibet commented
@ChrisMarsh82  thanks for looking into this.

> Question: I can't see where it would be displayed to users that they are looking at a subset of columns. Should this be added to the lblColDisplay in SetDisplayLabels?

This is not yet ready. I am tweaking the R method for this. I will alert you once it is ready.

2021-12-07 13:40 UTC, ChrisMarsh82 commented on instat/Model/DataFrame/clsDataFrameFilter.vb
> +    End Function
Should this be changed to RowFilterApplied and ColumnFilterApplied? They can both sit in clsDataFrameFilter or you could create clsDataframeRowFilter and clsDataframeColumnFilter.  Once you have the R commands working it would be easier to see what the best route would be. I assume both filters would work in a very similar way?

2022-01-04 21:39 UTC, rdstern commented
@shadrackkibet is anything more needed, before I test.  I am keen to continue progress on select, including applying it to the grid.

2022-01-13 11:01 UTC, rdstern requested changes
@shadrackkibet seems to work and looks good.  
The only minor change is that the term Remove Current Column Selection is so long that it has made the whole right-click menu wider.  I suggest Remove Column Selection is fine.  Or it could be Remove Current Selection, but I think I prefer the former.  Then it could be merged.

2022-01-13 17:34 UTC, rdstern approved these changes
Looks good.  I hope this can be merged soon?

2022-01-14 11:27 UTC, ChrisMarsh82 approved these changes

2022-01-14 11:28 UTC, merged