Opening an R script to the Script Window from Open From Library
africanmathsinitiative/R-Instat pull request #7038
Opened 2021-12-06 08:14 UTC by N-thony

Fixes #6984 
This PR adds the Niger script file to the Climatic > Niger folder and also the facility to open an R script to the Script Window from Open From Library.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2021-12-07 11:17 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +                        End Try
This try block is duplicated below. Remove the duplication?
(there are various ways you could do this)

2021-12-07 11:17 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +            If strFileExtension = ".r" Then
general comment:
Are multiple imports allowed for `'r` files (see line 601)

2021-12-07 11:17 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +                Me.Close()
The dialog isn't closed for other file formats, whats the reason for doing it here?

2021-12-07 11:17 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +                            MessageBox.Show("Could not load the script from file." & Environment.NewLine & "The file may be in use by another program or you may not have access to write to the specif
break up over several lines?

2021-12-07 11:17 UTC, lloyddewit commented on instat/ucrScript.vb
> +                        End Try
remove the duplication?

2021-12-07 11:47 UTC, N-thony commented on instat/dlgImportDataset.vb
> +            If strFileExtension = ".r" Then
@lloyddewit thanks for the quick call. We agreed to leave it as it is for now.

2021-12-07 11:51 UTC, N-thony commented
@lloyddewit I have resolved your comments above. Please take a look. Thanks

2021-12-08 10:37 UTC, lloyddewit requested changes
Thanks, just a couple of small suggestions for readability

2021-12-08 10:37 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +                     "Load Script From File", MessageBoxButtons.YesNo) = DialogResult.Yes Then
A line should not exceed 100 columns.
Add some newlines to the `If` statement?

2021-12-08 10:37 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +                        MessageBox.Show("Could not load the script from file." & Environment.NewLine & "The file may be in use by another program or you may not have access to write to the specified
A line should not exceed 100 columns.
Add some newlines?

2021-12-08 10:37 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +            If strFileExtension = ".r" Then
Yes, this function contains functionality that is not relevent for R script imports.
Part of the problem is that the Import dialogwas designed for importing datasets. But we are using it to populate the script window. This is not a natural fit and I think it reduces the understandability of the code.
We could refactor dlgImportDataset but I think this is too much work.
On balance, I think your implementation is an OK option for now.

2021-12-08 10:50 UTC, N-thony commented
@lloyddewit I resolved your comment above. Please take a look. Thanks.

2021-12-08 22:43 UTC, rdstern requested changes
I first tried with the script window empty and it worked fine.  It also didn't ask me - which it used to - and was unnecessary.
So - good so far.
Then I tried with a second file and with something already in the script window.  It warned me - that's good too.
So I said no  (I realise I should have tested yes as well, but didn't.)  Anyway after no it returned me to the ordinary Import file dialogue with that R file.  So I pressed Ok and it gave me an error.

Two points follow from this:
a) It would be good if the Import dialogue could also recognise an R-file and put it into the script window.  Currently the only way is via right-click once in the script window.
b) A separate point is whether it should go to the import dialogue when I say No to overwriting the existing file in the script window.  I'm not sure about this.

2021-12-10 06:40 UTC, N-thony commented
> I first tried with the script window empty and it worked fine. It also didn't ask me - which it used to - and was unnecessary. So - good so far. Then I tried with a second file and with something already in the script window. It warned me - that's good too. So I said no (I realise I should have tested yes as well, but didn't.) Anyway after no it returned me to the ordinary Import file dialogue with that R file. So I pressed Ok and it gave me an error.
> 
> Two points follow from this: a) It would be good if the Import dialogue could also recognise an R-file and put it into the script window. Currently the only way is via right-click once in the script window. b) A separate point is whether it should go to the import dialogue when I say No to overwriting the existing file in the script window. I'm not sure about this.

@rdstern I resolved your comments above, please take a look. Thanks,

2021-12-11 07:32 UTC, rdstern requested changes
@N-thony this now works perfectly - though with a big "but"!  
As far as I have tested the File > Open From Library seems to work ok.  (As I write this I realis that I haven't tested fully when you load a sequence of R files and then a data file and then an R file again.  So that will be good to check.
But, now the new code interacts with the File > Input from file dialogue, and in a pretty fundamental way.
a) I had a file in the script window.  When I use File > Import File (instead of Input from library), it gives me the warning that I would expect from the Input from Library dialogue.  
b) So I cleared the script window and tried File > Import again.  Then it returned the previous script automatically!
Now I would also like the File > Import File dialogue to be able to import a file into the script window.  I assumed this would be a separate issue, but perhaps it may be simpler to add this feature to the File > Import dialogue now???

2021-12-11 10:20 UTC, N-thony commented
@rdstern the change I made temporarily resolved your comments above. With a possibility to import an r script From both File and Library.

2022-01-04 18:51 UTC, rdstern approved these changes
@N-thony great - this seems to work now.

2022-01-05 10:44 UTC, lloyddewit approved these changes

2022-01-05 10:48 UTC, merged