Changed model error message.
africanmathsinitiative/R-Instat pull request #7051
Opened 2021-12-08 07:49 UTC by Gioche6

Fixes #6972

@africanmathsinitiative/developers , This is ready for review.
@shadrackkibet , I have changed the error message in for the try model to be `Model runs ok` and `Problem Detected running model or no output to display`  if model in not well implemented. 

I have let the command try message to remain as it was. I understand there is a ongoing discussion on the error messages, however, I'd like to know your thoughts on this. Thank you.

2021-12-09 09:38 UTC, lloyddewit commented
@HawardKetoyoMsatsi Please could you peer review? thanks

2021-12-14 08:53 UTC, Gioche6 commented
This merges the new changes made on PR #7055

2021-12-15 06:58 UTC, HawardKetoyoMsatsi requested changes

2021-12-15 06:58 UTC, HawardKetoyoMsatsi commented on instat/ucrTry.vb
> +                                ucrInputTryMessage.txtInput.BackColor = Color.LightGreen
One of the output messages is _runs without Error_ and the other is _runs okay_. If they mean the same thing why don't we output the same message?
If they mean different things then it is okay to have them so.

2021-12-15 06:58 UTC, HawardKetoyoMsatsi commented on instat/ucrTry.vb
> +                            ucrInputTryMessage.SetName("Problem detected running " & CommandModel & " or no output to display.")
Same to the error messages here

2021-12-16 09:10 UTC, Gioche6 commented on instat/ucrTry.vb
> +                                ucrInputTryMessage.txtInput.BackColor = Color.LightGreen
@HawardKetoyoMsatsi  in models, especially ANOVA models `errors` are interpreted differently. An error in a model could be the residuals, and therefore having an error message saying `model runs without error` could lead to confusion especially for statisticians and researchers as it would basically mean the model ignore the residual.

2021-12-16 09:14 UTC, Gioche6 commented on instat/ucrTry.vb
> +                            ucrInputTryMessage.SetName("Problem detected running " & CommandModel & " or no output to display.")
>@HawardKetoyoMsatsi in models, especially ANOVA models `errors` are interpreted differently. An error in a model could be the residuals, and therefore having an error message saying `model runs without error` could lead to confusion especially for statisticians and researchers as it would basically mean the model ignore the residual.

@HawardKetoyoMsatsi , I hope you do get my point from the above explanation. It is the reason @shadrackkibet  suggested a change as in the issue #6972 , to prevent any confusion to those who understand errors differently.

2021-12-17 03:53 UTC, HawardKetoyoMsatsi commented
@Gioche6 I missed part of the discussion in the issue, this is perfect.
@shadrackkibet I am okay with it, over to you.

2022-01-03 09:35 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2022-01-06 06:31 UTC, maxwellfundi commented
@rdstern this is ready for your review

2022-01-07 16:05 UTC, rdstern approved these changes

2022-01-10 09:58 UTC, lloyddewit commented
@HawardKetoyoMsatsi thank you for the review. I set your comments to resolved.

2022-01-10 10:00 UTC, lloyddewit approved these changes

2022-01-10 10:04 UTC, merged

2022-01-11 15:42 UTC, lloyddewit commented on instat/ucrTry.vb
> +            CommandModel = "model"
I corrected this in PR #7097