Fixing Error on Display Daily dialogue
africanmathsinitiative/R-Instat pull request #7053
Opened 2021-12-08 08:39 UTC by EstherNjeriLiberatta

Fixes issue #7016 

@N-thony kindly review this. I think the error is now fixed.

2021-12-08 10:21 UTC, N-thony requested changes
Under Table option. Can you fix this small design issue with missing checkbox going over its groupbox
![image](https://user-images.githubusercontent.com/68591383/145191414-977ade0f-9936-4202-918c-a73199a9274c.png)

2021-12-08 10:21 UTC, N-thony commented on instat/dlgDisplayDailyData.vb
> +        ucrChkMissing.AddToLinkedControls({ucrInputComboMissing}, {True}, bNewLinkedUpdateFunction:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True)
Do you need bNewLinkedUpdateFunction:=True?

2021-12-08 10:21 UTC, N-thony commented on instat/dlgDisplayDailyData.vb
> +        ' ucrChkMissing.SetParameter(ucrInputComboMissing.GetParameter)
Remove? Same with other commented line

2021-12-08 13:07 UTC, rdstern submitted a review, later dismissed
seems ok now

2021-12-08 14:09 UTC, EstherNjeriLiberatta commented on instat/dlgDisplayDailyData.vb
> +        ucrChkMissing.AddToLinkedControls({ucrInputComboMissing}, {True}, bNewLinkedUpdateFunction:=True, bNewLinkedAddRemoveParameter:=True, bNewLinkedHideIfParameterMissing:=True)
Hello @N-thony I've commented out the SetRCode for ucrInputComboMissing and replaced it with that. It does the same thing but it helps remove the confusion between the `ucrChkMissing` and `ucrInputComboMissing` controls.

2021-12-08 15:29 UTC, EstherNjeriLiberatta commented
@N-thony I fixed the checkbox overlap. I also noticed an inconsistency in spelling of colour on the `Rug color` label. I fixed that too. Thanks.

@rdstern This is ready for review.

2021-12-16 10:23 UTC, lloyddewit commented
> @N-thony I fixed the changes you requested. 

@EstherNjeriLiberatta I don't think you resolved @N-thony 's comments in `dlgDisplayDailyData.vb`, please could you double-check? thanks

2021-12-16 10:37 UTC, EstherNjeriLiberatta commented
@lloyddewit No problem, thank you.

2021-12-17 09:41 UTC, EstherNjeriLiberatta commented
Hello @N-thony please review the changes I've made.
@rdstern @africanmathsinitiative/developers This is ready for review.

2022-01-04 15:57 UTC, rdstern approved these changes
Great.

2022-01-05 08:30 UTC, lloyddewit approved these changes

2022-01-05 08:33 UTC, merged