Made the size of Reogrid texts info dynamic
africanmathsinitiative/R-Instat pull request #7059
Opened 2021-12-08 15:28 UTC by N-thony

Fixes #7008 
@africanmathsinitiative/developers @ChrisMarsh82 @dannyparsons this is ready for review. Thanks.

2021-12-08 15:33 UTC, N-thony commented
> Fixes #7008 @africanmathsinitiative/developers @ChrisMarsh82 @dannyparsons this is ready for review. Thanks.

Please wait a bit before the review. I will let you know, I found a small bug.

2021-12-08 16:17 UTC, ChrisMarsh82 commented
@N-thony  If you delete the font from the label controls you then can control the font from the TblPanPageDisplay. You will also need to check the size in a loop so that the size can be decremented more than once. 
ResizeLabel should be called within SetDisplayLabels as this makes sure the labels are being resized every time they are changed.

2021-12-08 16:21 UTC, ChrisMarsh82 commented
Here is a link to the type loop you will need. Its in c# but you get the idea
https://stackoverflow.com/questions/9527721/resize-text-size-of-a-label-when-the-text-gets-longer-than-the-label-size

2021-12-08 16:34 UTC, dannyparsons commented
Could you not calculate the size needed once instead of incrementally decreasing? - that seems inefficient, especially if it's done every time there's a refresh. 

The link from Chris links to another answer that does this using the ratios https://stackoverflow.com/questions/9527721/resize-text-size-of-a-label-when-the-text-gets-longer-than-the-label-size/20457976#20457976 Can we use the same idea?

2021-12-09 08:49 UTC, N-thony commented
@ChrisMarsh82 @dannyparsons I have tried different approaches you have provided in the above links. I found Danny's approach a bit longer and complicated than the one from Chris with some adaptation I done, please take a look.

2021-12-10 06:32 UTC, N-thony commented
> SetDisplayLabels

@ChrisMarsh82 please could you take a look now. This seems to work. Thanks

2021-12-15 12:24 UTC, ChrisMarsh82 commented
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/CHRIST~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:AllowPNG/>
 </o:OfficeDocumentSettings>
</xml><![endif]-->
<link rel=themeData
href="file:///C:/Users/CHRIST~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/CHRIST~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">
<!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:View>Normal</w:View>
  <w:Zoom>0</w:Zoom>
  <w:TrackMoves/>
  <w:TrackFormatting/>
  <w:PunctuationKerning/>
  <w:ValidateAgainstSchemas/>
  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>
  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
  <w:DoNotPromoteQF/>
  <w:LidThemeOther>EN-GB</w:LidThemeOther>
  <w:LidThemeAsian>X-NONE</w:LidThemeAsian>
  <w:LidThemeComplexScript>X-NONE</w:LidThemeComplexScript>
  <w:Compatibility>
   <w:BreakWrappedTables/>
   <w:SnapToGridInCell/>
   <w:WrapTextWithPunct/>
   <w:UseAsianBreakRules/>
   <w:DontGrowAutofit/>
   <w:SplitPgBreakAndParaMark/>
   <w:EnableOpenTypeKerning/>
   <w:DontFlipMirrorIndents/>
   <w:OverrideTableStyleHps/>
  </w:Compatibility>
  <m:mathPr>
   <m:mathFont m:val="Cambria Math"/>
   <m:brkBin m:val="before"/>
   <m:brkBinSub m:val="&#45;-"/>
   <m:smallFrac m:val="off"/>
   <m:dispDef/>
   <m:lMargin m:val="0"/>
   <m:rMargin m:val="0"/>
   <m:defJc m:val="centerGroup"/>
   <m:wrapIndent m:val="1440"/>
   <m:intLim m:val="subSup"/>
   <m:naryLim m:val="undOvr"/>
  </m:mathPr></w:WordDocument>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <w:LatentStyles DefLockedState="false" DefUnhideWhenUsed="false"
  DefSemiHidden="false" DefQFormat="false" DefPriority="99"
  LatentStyleCount="376">
  <w:LsdException Locked="false" Priority="0" QFormat="true" Name="Normal"/>
  <w:LsdException Locked="false" Priority="9" QFormat="true" Name="heading 1"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 2"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 3"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 4"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 5"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 6"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 7"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 8"/>
  <w:LsdException Locked="false" Priority="9" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="heading 9"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 1"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 6"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 7"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 8"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index 9"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 1"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 2"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 3"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 4"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 5"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 6"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 7"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 8"/>
  <w:LsdException Locked="false" Priority="39" SemiHidden="true"
   UnhideWhenUsed="true" Name="toc 9"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="Normal Indent"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footnote text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="annotation text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="header"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footer"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="index heading"/>
  <w:LsdException Locked="false" Priority="35" SemiHidden="true"
   UnhideWhenUsed="true" QFormat="true" Name="caption"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="table of figures"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="envelope address"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="envelope return"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="footnote reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="annotation reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="line number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="page number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="endnote reference"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="endnote text"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="table of authorities"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="macro"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="toa heading"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Number"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 4"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List 5"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 2"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 3"/>
  <w:LsdException Locked="false" SemiHidden="true" UnhideWhenUsed="true"
   Name="List Bullet 4"/>
  <w:LsdException Locked [...]

2021-12-17 10:52 UTC, ChrisMarsh82 commented
@N-thony 

This is the pseudo-code you should be basing your code on:
```
Resize Procedure
  Set Text to standard size
  While Text does not fit and Text is greater than minimum size
     Decrement text by 0.5
  End While
```


If we look at the code you have so far:
```
        If lblRowDisplay.Width + TextRenderer.MeasureText(lblRowDisplay.Text, New Font(lblRowDisplay.Font.FontFamily, lblRowDisplay.Font.Size, lblRowDisplay.Font.Style)).Width > tlpTableContainer.Width Then
            While lblRowDisplay.Width + TextRenderer.MeasureText(lblRowDisplay.Text, New Font(lblRowDisplay.Font.FontFamily, lblRowDisplay.Font.Size, lblRowDisplay.Font.Style)).Width > tlpTableContainer.Width AndAlso
              lblRowDisplay.Font.Size > minSize
                lblRowDisplay.Font = New Font("Microsoft Sans Serif", lblRowDisplay.Font.Size - 0.5F, lblRowDisplay.Font.Style)
                lblColDisplay.Font = New Font("Microsoft Sans Serif", lblRowDisplay.Font.Size - 0.5F, lblRowDisplay.Font.Style)
            End While
        Else
            While lblRowDisplay.Width + TextRenderer.MeasureText(lblRowDisplay.Text, New Font(lblRowDisplay.Font.FontFamily, lblRowDisplay.Font.Size, lblRowDisplay.Font.Style)).Width < tlpTableContainer.Width AndAlso
          lblRowDisplay.Font.Size < maxSize
                lblRowDisplay.Font = New Font("Microsoft Sans Serif", lblRowDisplay.Font.Size + 0.5F, lblRowDisplay.Font.Style)
                lblColDisplay.Font = New Font("Microsoft Sans Serif", lblRowDisplay.Font.Size + 0.5F, lblRowDisplay.Font.Style)
            End While
        End If
```
The text is not set to standard size at the start of the procedure. - This is done in the second while which then overcomplicates the procedure.

The first IF statement doesn't do anything. The WHILE clause does the same comparison and there is no code that's in the if statement that is not in the while clause. 

While Clause: 
`            While lblRowDisplay.Width + TextRenderer.MeasureText(lblRowDisplay.Text, New Font(lblRowDisplay.Font.FontFamily, lblRowDisplay.Font.Size, lblRowDisplay.Font.Style)).Width > tlpTableContainer.Width`

This is not checking the right thing. If this works it is more of luck than anything else. 
`lblRowDisplay.Width` is added to the `TextRender.MeasureText(lblRowDisplay.Text ...` which is the same value. This needs to take the width of all the labels in the `tlpPanPageDisplay`

`> tlpTableContainer.Width` is not the right panel. Although this will work as it will generally be the same size as `tlpPanPageDisplay` it is not the panel where the labels are.

````
                lblRowDisplay.Font = New Font("Microsoft Sans Serif", lblRowDisplay.Font.Size - 0.5F, lblRowDisplay.Font.Style)
                lblColDisplay.Font = New Font("Microsoft Sans Serif", lblRowDisplay.Font.Size - 0.5F, lblRowDisplay.Font.Style)
````
This should be the font on the `tlpPanPageDisplay` as it will change all the fonts including the navigation symbols '<<<>>>'

Your min size is set to 2. Is this a viable size? have you tested what this looks like when the font is set to this size?


I think you are getting close. If you go through these points one at a time I'm sure you can get it to work.

2021-12-18 12:37 UTC, N-thony commented
@ChrisMarsh82 thanks for your review and the pseudo-code above. This seems to work now even if we had a small issue with that. As discussed yesterday for the small issue that was coming from the code when resizing I made a small change by doubling the width of the column display label in the sum of labels width in the TblPanelLayout to allow to have access to the steps that will allow the resizing of the text to fit the TblPanelLayout. The minimum size can also go to less than five to allow texts to resize and fit when collapsing the splitContainer. Please take a look. Thanks.

2021-12-18 13:21 UTC, N-thony commented
@ChrisMarsh82 thanks for your review and the pseudo-code above. This seems to work now even if we had a small issue with that. As discussed yesterday for the small issue that was coming from the code when resizing I made a small change by doubling the width of the column display label in the sum of labels width in the TblPanelLayout to allow to have access to the steps that will allow the resizing of the text to fit the `TblPanelLayout`. The minimum size `5` can also go to less than five to allow texts to resize and fit when collapsing the splitContainer. Please take a look. Thanks.

2021-12-21 14:46 UTC, ChrisMarsh82 commented
@N-thony This looks like it works really well now. Well done!

One minor change I would like you to make. The WHILE statement has `(lblColDisplay.Width * 2)` I don't understand why we would need to take the lblColDisplay into account twice. I think what may be needed is a buffer as there are other things taking up space other than the labels. I have done some testing and a 50-pixel buffer seems to work well. 
I would change the WHILE statement to be: 
```
While lblRowDisplay.Width + lblColDisplay.Width + 50 +
                    lblColBack.Width + lblColFirst.Width + lblColLast.Width + lblColNext.Width +
                    lblRowBack.Width + lblRowFirst.Width + lblRowNext.Width + lblRowLast.Width > TblPanPageDisplay.Width AndAlso
                    TblPanPageDisplay.Font.Size > minSize
```

Also putting the WHILE statement over multiple lines would help the readability.


Other than this I think the code is good to go and works very well.

2021-12-21 14:59 UTC, ChrisMarsh82 submitted a review, later dismissed

2022-01-04 10:43 UTC, lloyddewit requested changes
@N-thony This looks good, just one small suggestion

2022-01-04 10:43 UTC, lloyddewit commented on instat/ucrDataView.vb
> +        Dim minSize As Single = 5
I suggest to use `Const` and follow the naming conventions.
I agree that the naming conventions add nothing to readability here but I want to stay consistent with the rest of R-Instat.
```suggestion
        Dim Const iMinSize As Single = 5
```

2022-01-04 11:00 UTC, N-thony commented on instat/ucrDataView.vb
> +        Dim minSize As Single = 5
Thanks @lloyddewit, I resolved this

2022-01-04 11:29 UTC, lloyddewit approved these changes

2022-01-04 11:30 UTC, lloyddewit commented
@ChrisMarsh82 please can you approve again? we can then merge, thanks

2022-01-04 11:37 UTC, ChrisMarsh82 approved these changes

2022-01-04 11:45 UTC, merged