Replaces PR 6994 about the implementation the regex sub dialog under Prepare > Column:Text > Split dialogue
africanmathsinitiative/R-Instat pull request #7062
Opened 2021-12-09 12:49 UTC by N-thony

@lloyddewit  @rdstern  this PR replaces PR #6994 due to the issue coming from 66 files as explained in that PR.
@rdstern you can still test this. But they are still changes you raised on items b) c) and d) I need to resolve after a quick discussion for clarification. Thanks.

2021-12-11 06:23 UTC, N-thony commented
@rdstern as we discussed I added the regex function when it is chosen and this resolves your comment b) in PR #6994, please take a look.
I'm not yet sure on the position of the Boundary, perhaps we can also discuss about it and how it works?

2021-12-11 11:37 UTC, rdstern requested changes
@N-thony they all seem to work.  Well done.
I am now querying "the icing on the cake".  I think you have to give coll when using our default, because the stringr default is regex.  If easy, when it uses the default, could the command be given more simply?  In particular I think that when using regex and case = FALSE, then the command could be very simple?
Then happy when you can add the boundary.  I am not completely sure what it does - perhaps you are?

2021-12-11 16:49 UTC, N-thony commented
> 

@lloyddewit I need to make the text change of `Word Count` to `Count` as @rdstern suggested during our discussion, I did the text change but it still shows `World Count` and this comes from the translation. As we did recently, if you agree, this can be done in a separate PR by setting rdoCount `DoNotTranslate`?

2021-12-11 17:01 UTC, rdstern commented
@lloyddewit but here we would like a translation and I think this may already be "in the system" and not implemented yet.  At least it was requested earlier.  It is an example where we do (I think) still want to translate, but the changed text.  Currently it is Word Count - translated as Nombre de mots.  I suggest just Count, because it could be counting the number of characters, or words or sentences.  I assume that is translated into French as Nombre instead.

2021-12-11 17:18 UTC, N-thony commented
> @lloyddewit but here we would like a translation and I think this may already be "in the system" and not implemented yet. At least it was requested earlier. It is an example where we do (I think) still want to translate, but the changed text. Currently it is Word Count - translated as Nombre de mots. I suggest just Count, because it could be counting the number of characters, or words or sentences. I assume that is translated into French as Nombre instead.

And if @lloyddewit agree to change it manually, the correct translation in French I think it will be `Compter` rather than `Nombre` according to what it is doing and making it consistent with other radio buttons text in French translated.

2021-12-11 17:45 UTC, N-thony commented
> @N-thony they all seem to work. Well done. I am now querying "the icing on the cake". I think you have to give coll when using our default, because the stringr default is regex. If easy, when it uses the default, could the command be given more simply? In particular I think that when using regex and case = FALSE, then the command could be very simple? Then happy when you can add the boundary. I am not completely sure what it does - perhaps you are?

@rdstern please take a look at the output r code. For the implementation of the Boundary, more change in the design part, perhaps in another issue?

2021-12-12 08:19 UTC, rdstern requested changes
@N-thony I was trying to check the boundary control, but it wasn't enabled?
You also said that boundary was useful in the split dialogue, but I don't even see the regex there anymore.  Good to change the name of this PR?

2021-12-12 08:24 UTC, N-thony commented
> @N-thony I was trying to check the boundary control, but it wasn't enabled? You also said that boundary was useful in the split dialogue, but I don't even see the regex there anymore. Good to change the name of this PR?

@rdstern you are right, I will add the boundary same time with regex in the Split dialogue after merging this if all is ok.

2021-12-12 08:29 UTC, rdstern commented
ok. Can you make an issue with what remains on boundary and the split.  Then I will approve so the code can be checked too.

2021-12-12 08:31 UTC, rdstern submitted a review, later dismissed
This is a very useful advance.  The boundary control is yet to be finalised, but that is being addressed in another issue.  So I am approving.  This is a good one to add!

2021-12-16 08:31 UTC, lloyddewit commented
> > @lloyddewit but here we would like a translation and I think this may already be "in the system" and not implemented yet. At least it was requested earlier. It is an example where we do (I think) still want to translate, but the changed text. Currently it is Word Count - translated as Nombre de mots. I suggest just Count, because it could be counting the number of characters, or words or sentences. I assume that is translated into French as Nombre instead.
> 
> And if @lloyddewit agree to change it manually, the correct translation in French I think it will be `Compter` rather than `Nombre` according to what it is doing and making it consistent with other radio buttons text in French translated.

@N-thony Please could you:

- [ ] Change the translation in the translations database
- [ ] Change the translation in the CrowdIn system (this is needed, otherwise the database will revert to the old translation the next time we update the database from the CrowdIn JSON file)

Thanks

2021-12-16 08:35 UTC, lloyddewit commented
@HawardKetoyoMsatsi Please could you peer review? thanks

2021-12-16 11:00 UTC, lloyddewit commented
> Change the translation in the CrowdIn system (this is needed, otherwise the database will revert to the old translation the next time we update the database from the CrowdIn JSON file)

@N-thony The new English text is ' Count'. This does not yet exist CrowdIn so you'll need to take some extra steps:

- [ ] add ' Count' to `r_instat_not_menus.json'. When this is merged, it can be imported into CrowdIn. I think this happens automatically, but you may need to ask @dannyparsons . When it's in CrowdIn, you can change the French translation to ' Compter'.
- [ ] Add a new row for ' Count' to `translationsManuallyEntered.csv`


![image](https://user-images.githubusercontent.com/57253949/146358542-eaa450c1-72a2-4c87-aca0-d86bab494413.png)

2021-12-16 12:07 UTC, HawardKetoyoMsatsi commented
I Still find this issue. When I try searching for " double quotes using the escape character, after running when I reopen the dialogue doesn't remember double quotes.
What I run
![image](https://user-images.githubusercontent.com/16137042/146368293-d97bb525-9b77-42e4-9b08-1ba3e3cc125f.png)

When I reopen the dialog
![image](https://user-images.githubusercontent.com/16137042/146368408-61c4f566-e44a-41e2-8498-0347ab049f02.png)

Could this be an issue with string handling properties?

2021-12-16 12:15 UTC, HawardKetoyoMsatsi requested changes

2021-12-16 12:25 UTC, HawardKetoyoMsatsi requested changes

2021-12-16 12:25 UTC, HawardKetoyoMsatsi commented on instat/dlgStringHandling.vb
> +
About I don't know whether double double blank lines are encouraged in R-Instat if not then I guess you will have to remove one blank line here too.

2021-12-16 13:49 UTC, N-thony commented
@HawardKetoyoMsatsi thanks for your comments. I resolved them, please take a look.

2021-12-16 13:52 UTC, N-thony commented
@HawardKetoyoMsatsi thanks for your comments. I resolved them, please take a look.

2021-12-16 14:55 UTC, HawardKetoyoMsatsi commented
@N-thony great, it now works fine.
@lloyddewit over to you.

2022-01-04 15:44 UTC, rdstern submitted a review, later dismissed
@N-thony I am happy to approve.  But you started with the Split dialogue and that now doesn't yet have the keyboard.  
Would you like to make that a separate issue, or would you prefer to add it now?

2022-01-05 05:19 UTC, N-thony commented
> @N-thony I am happy to approve. But you started with the Split dialogue and that now doesn't yet have the keyboard. Would you like to make that a separate issue, or would you prefer to add it now?

Thanks, @rdstern, I would prefer now to add it then.

2022-01-05 08:44 UTC, lloyddewit commented
I updated issue 6893 to show that this PR only partly solves it.

2022-01-05 10:37 UTC, lloyddewit requested changes

2022-01-05 10:37 UTC, lloyddewit commented on instat/sdgConstructRegexExpression.vb
> +        ttAddKeyboard.SetToolTip(cmdAny1, " Matches any character. For example,str_count(c(""rss"",""r.s.t""),""."") gives 3 5.  Using \\. Gives 0 2 ")
Extra spaces complicate the translations. Remove spaces at start and end?

2022-01-05 10:37 UTC, lloyddewit commented on instat/sdgConstructRegexExpression.vb
> +        ttAddKeyboard.SetToolTip(cmdbegin, " Start of the string. For example, str_count(c(""rss"",""r.s.t""),""^r\\."") gives 0 1")
remove space at start?

2022-01-05 10:37 UTC, lloyddewit commented on instat/sdgConstructRegexExpression.vb
> +        ttAddKeyboard.SetToolTip(cmdZero, "0 or more times. For example, str_count(c(""bt"",""bat"",""boot"",""boat""),""b[ao]*t"") gives 1 1 1 1 ")
remove space at end?

2022-01-05 10:37 UTC, lloyddewit commented on instat/sdgConstructRegexExpression.vb
> +        ttAddKeyboard.SetToolTip(cmdZeroOrOne, "0 or 1 times. For example, str_count(c(""bt"",""bat"",""boot"",""boat""),""b[ao]?t"") gives 1 1 0 0 ")
remove space at end?

2022-01-05 10:37 UTC, lloyddewit commented on instat/sdgConstructRegexExpression.vb
> +
```suggestion
```

2022-01-05 10:52 UTC, lloyddewit approved these changes

2022-01-05 12:37 UTC, N-thony commented
@lloyddewit thanks for your review and the quick chat, I made the change and this is ready for @rdstern's review.

2022-01-07 11:50 UTC, rdstern approved these changes
Looks good now

2022-01-10 10:07 UTC, lloyddewit commented
@N-thony This is tested and reviewed. Unfortunately, a merge conflict was triggered by another PR. Please could you resolve so that we can merge? Thanks

2022-01-10 10:15 UTC, N-thony commented
> @N-thony This is tested and reviewed. Unfortunately, a merge conflict was triggered by another PR. Please could you resolve so that we can merge? Thanks

@lloyddewit I resolved the conflict. Thanks.

2022-01-11 15:24 UTC, lloyddewit commented
@N-thony I still see 5 merge conflicts, maybe they're new? please could you fix? thanks

2022-01-11 16:12 UTC, N-thony commented
> @N-thony I still see 5 merge conflicts, maybe they're new? please could you fix? thanks

Thanks, @lloyddewit, I resolved the conflicts. Please take a look.

2022-01-12 10:26 UTC, lloyddewit approved these changes

2022-01-12 10:28 UTC, lloyddewit commented
@rdstern Since your last approval, there have been some merge conflicts resolved and other (hopefully non-functional) changes. Please can you test/approve? thanks

2022-01-12 12:55 UTC, rdstern requested changes
@N-thony I now get build errors

2022-01-12 13:00 UTC, N-thony commented
> 

@rdstern it runs ok on my side. @lloyddewit could you try to run on your side. Thanks.

2022-01-12 13:06 UTC, N-thony commented
> > 
> 
> @rdstern it runs ok on my side. @lloyddewit could you try to run on your side? Thanks.

@rdstern I will close this one and create another to avoid the build error.

2022-01-12 17:06 UTC, rdstern commented
@N-thony thanks.  It will be good to get this merged.

2022-01-12 20:47 UTC, N-thony commented
> > Change the translation in the CrowdIn system (this is needed, otherwise the database will revert to the old translation the next time we update the database from the CrowdIn JSON file)
> 
> @N-thony The new English text is ' Count'. This does not yet exist in CrowdIn so you'll need to take some extra steps:
> 
> * [ ]  add ' Count' to `r_instat_not_menus.json'. When this is merged, it can be imported into CrowdIn. I think this happens automatically, but you may need to ask @dannyparsons . When it's in CrowdIn, you can change the French translation to ' Compter'.
> * [ ]  Add a new row for ' Count' to `translationsManuallyEntered.csv`
> 
> ![image](https://user-images.githubusercontent.com/57253949/146358542-eaa450c1-72a2-4c87-aca0-d86bab494413.png)

@lloyddewit I think I have missed this part of adding `Count` to  `r_instat_not_menus.json`. Could this be done same time in PR #7108? Thanks.

2022-01-13 16:22 UTC, closed without merging

2022-01-13 16:22 UTC, N-thony commented
I have closed this one since it is replaced by #7118