Implemented the Ctrl+C on the new Output Window
africanmathsinitiative/R-Instat pull request #7066
Opened 2021-12-13 20:06 UTC by N-thony

Fixes #7000
@dannyparsons I have here implemented the Ctrl+C as you suggested in the corresponding issue with the Output Window.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.
@ChrisMarsh82 I have additionally fixed the bug when copying text from `Output Window` to `Script Window` by Clicking on `Copy Tab` as I have explained in the issue. The change is made in `CopySelectedElementsToClipboard()`

2022-01-05 14:37 UTC, dannyparsons commented
@ChrisMarsh82 Could you do a quick sanity check of this? It looks sensible to me.

@rdstern Could you also test?

2022-01-06 16:24 UTC, dannyparsons commented on instat/UserControl/ucrOutputPage.vb
> +            Clipboard.SetText(strClip, TextDataFormat.Text)
These lines shouldn't be duplicated. Extract to a Sub if it's required in multiple places.

2022-01-06 17:44 UTC, N-thony commented on instat/UserControl/ucrOutputPage.vb
> +            Clipboard.SetText(strClip, TextDataFormat.Text)
Thanks @dannyparsons, I resolved this.

2022-01-07 12:09 UTC, rdstern reviewed
I am not quite sure what is expected here.
I put some results into the output window.
I could then tick the box and perss the copy button, or ctrl C.  Then I could paste into the script window.  It pasted fine, but the font was changed, so it didn't look great.  I don't know if that is the copy/paste, or the script window?
I then tried to mark pare of the output in the output window to copy and didn't see how to do that.

2022-01-07 14:20 UTC, N-thony commented
> I am not quite sure what is expected here. I put some results into the output window. I could then tick the box and perss the copy button, or ctrl C. Then I could paste into the script window. It pasted fine, but the font was changed, so it didn't look great. I don't know if that is the copy/paste, or the script window? I then tried to mark pare of the output in the output window to copy and didn't see how to do that.

Thanks @rdstern for your review and the discussion, I have made the change as suggested. For pasting the output from Describe>One Variable>Summarise dialogue into the script window, I think that may be an issue with the Script Window. I will have  look at it in a separate issue. Please take a look of the current change. Thanks.

2022-01-08 17:54 UTC, rdstern requested changes
@N-thony I can now mark a block in the output window.
But I now have some problems in the script window that were not there before.  I don't seem to be able to use ctrl V.  And more major is that the Clear does not seem to work any more in the script window.  
Pasting into the script window isn't the most important from the output window.  I am just using that because it is convenient.  Usually I will be pasting into word or Excel.  So I am not clear why anything needs to have changed in the script?

2022-01-10 09:18 UTC, N-thony commented
> @N-thony I can now mark a block in the output window. But I now have some problems in the script window that were not there before. I don't seem to be able to use ctrl V. And more major is that the Clear does not seem to work any more in the script window. Pasting into the script window isn't the most important from the output window. I am just using that because it is convenient. Usually I will be pasting into word or Excel. So I am not clear why anything needs to have changed in the script?

@rdstern I was not able to reproduce the problems. Could you test again? Thanks.

2022-01-13 18:06 UTC, N-thony commented
> > @N-thony I can now mark a block in the output window. But I now have some problems in the script window that were not there before. I don't seem to be able to use ctrl V. And more major is that the Clear does not seem to work any more in the script window. Pasting into the script window isn't the most important from the output window. I am just using that because it is convenient. Usually I will be pasting into word or Excel. So I am not clear why anything needs to have changed in the script?
> 
> @rdstern I was not able to reproduce the problems. Could you test again? Thanks.

@rdstern could you test this too? Thanks.

2022-01-22 05:45 UTC, rdstern approved these changes
Seems fine now

2022-01-24 11:07 UTC, lloyddewit requested changes
@N-thony Thank you, just a couple of open questions

2022-01-24 11:07 UTC, lloyddewit commented on instat/UserControl/ucrOutputPage.vb
> +        With richText
What's the purpose of using 'With'? I undwerstand that, in this context, it just adds 2 extra lines of code and an extra indent.
Would it be more readable without?

2022-01-24 11:07 UTC, lloyddewit commented on instat/UserControl/ucrOutputPage.vb
> +                If Line <> "" Then strClip &= Line & Environment.NewLine
What's the reason for not copying blank lines?
Should we comment the reason?

2022-01-24 11:32 UTC, dannyparsons commented on instat/UserControl/ucrOutputPage.vb
> +                If Line <> "" Then strClip &= Line & Environment.NewLine
Blank lines might be useful in a multi line copy, why ignore them?

2022-01-24 11:32 UTC, N-thony commented
@lloyddewit thanks for your comments. I resolved them. Please take a look.

2022-01-24 11:40 UTC, lloyddewit submitted a review, later dismissed

2022-01-24 11:41 UTC, lloyddewit commented
@rdstern Since your last approval, there was just a small change that shouldn't have affected the functionality. Please could you approve again? thanks

2022-01-24 12:00 UTC, dannyparsons requested changes
In the current master if I copy some output using the Copy button in the Output Window e.g. from One Variable Summarise, then it pastes into Word with the formatting and colour.

When I try it on this PR the formatting is lost. So this needs to be retained.

2022-01-24 12:29 UTC, N-thony commented
> In the current master if I copy some output using the Copy button in the Output Window e.g. from One Variable Summarise, then it pastes into Word with the formatting and colour.
> 
> When I try it on this PR the formatting is lost. So this needs to be retained.

@dannyparsons could you test this again? Thanks.

2022-01-24 12:33 UTC, dannyparsons commented
Still doesn't work for me. Did you try this yourself and it worked?

2022-01-24 14:11 UTC, N-thony commented
> Still doesn't work for me. Did you try this yourself and it worked?

@dannyparsons I did the test and it seems to work now.
![image](https://user-images.githubusercontent.com/68591383/150798324-73a34a62-3a71-4e8d-aad4-58bf2810bd24.png)

2022-01-25 11:04 UTC, rdstern commented
![image](https://user-images.githubusercontent.com/11226469/150965208-a38fafc1-f9a8-4d98-9ca7-f74b934ddc69.png)

@N-thony Here for an example - from the review of copy first with marking copy and secondly with ctrl <C>

2022-01-25 14:34 UTC, N-thony commented
> ![image](https://user-images.githubusercontent.com/11226469/150965208-a38fafc1-f9a8-4d98-9ca7-f74b934ddc69.png)
> 
> @N-thony Here for an example - from the review: First of copy having ticked a section and secondly marking the section and then using your ctrl C. I also tried all the different paste options in Word and can't get the same font/formatting as from the Copy button.

@rdstern thanks for your request. I have made a small change as shown below. Please take a look.

![image](https://user-images.githubusercontent.com/68591383/150996487-9d5cf014-372b-49aa-92cb-1f7f319347a6.png)

2022-01-25 17:14 UTC, lloyddewit approved these changes

2022-01-28 09:33 UTC, lloyddewit commented
@dannyparsons I understand from @rdstern that you're happy now with this PR, and we can merge.
However, you requested a change earlier so I am blocked from merging.
Please could you approve and merge?
Thanks

2022-01-28 10:22 UTC, dannyparsons approved these changes

2022-01-28 10:23 UTC, merged