Adding Degree button to the Climate>Prepare>Transform dialogue
africanmathsinitiative/R-Instat pull request #7068
Opened 2021-12-14 13:46 UTC by anastasia-mbithe

This fixes issue #6990.
Hello, @rdstern I have added the controls and functions. Though, this is still in progress. There are some small fixes I am still working on.

2021-12-15 07:58 UTC, rdstern requested changes
@anastasia-mbithe I know this is still "work in progress".  It is looking good already!
a) Could you add ther s, so the button at the top is called Degrees.
b) In the QC dialogue we have Tmax before Tmin.  Could that be the order here too.
c) Changing the radio button options you have added, seems also to refresh the data selector.  Does that need to be done?
d) And an extra bit of work.  I am adding another issue (number #7069) on the same dialogue.  I hope it is sufficiently small that you could include the changes here.

2021-12-16 18:04 UTC, anastasia-mbithe commented
@rdstern Kindly have a look at this.

2022-01-06 06:28 UTC, maxwellfundi commented
@rdstern  this is ready for a re-review

2022-01-07 11:38 UTC, rdstern requested changes
@anastasia-mbithe it looks like nice code and I assume is almost ready.
But I tried with dodoma and then with the tidy version from Ghana.  I used max and min.  It gives an error repeatedly saying argument 1 (or parameter 1 is empty.  That was for diurnal range and also HDD.  It seems to work ok for tmean.

2022-01-11 14:16 UTC, anastasia-mbithe commented
@rdstern This is ready for review now. I sorted out the issue and added functions to the HDD, GDD and ModifiedGDD to work well when we have Tmin and Tmax.

2022-01-11 21:03 UTC, rdstern commented
@anastasia-mbithe this is all looking pretty good.  
a) Set yourself a high standard in the lining up of the controls you add.  So here the tmax and tmin (and tmean) could be aligned with the controls above.  And the labels could be in exactly the same vertical position.
b) In the variable names we produce I suggest they be in lower case.  Keep the capitals (as you have them) on the dialogue.  But make the resulting variable names as hdd and gdd, etc.
c) You may wish to check with wikipedia, but I think the hdd are positive values.  So add a minus in the formula you produce.
d) In calculating gdd I got some very odd values.  Then I realised it was because I had changed the baseline for hdd to 35, but kept the gdd as 15.  It seemed to pick up the 35 in the logical part of the gdd formula.  See below:

```
# Code generated by the dialog, Transform
min_temperature <- data_book$get_columns_from_data(data_name="ghana", col_names="min_temperature")
max_temperature <- data_book$get_columns_from_data(data_name="ghana", col_names="max_temperature")
group_by_station <- instat_calculation$new(type="by", calculated_from=list("ghana"="station"))
transform_calculation <- instat_calculation$new(type="calculation", function_exp="(((min_temperature + max_temperature) / 2) - 15) * (((min_temperature + max_temperature) / 2) > 35)", result_name="GDD", manipulations=list(group_by_station), save=2, before=FALSE, calculated_from=list("ghana"="max_temperature","ghana"="min_temperature"))
data_book$run_instat_calculation(calc=transform_calculation, display=FALSE)
```

d) The formula for the modified gdd is also wrong - and still has my 35 from the previous HDD.

```
# Code generated by the dialog, Transform
min_temperature <- data_book$get_columns_from_data(data_name="ghana", col_names="min_temperature")
max_temperature <- data_book$get_columns_from_data(data_name="ghana", col_names="max_temperature")
group_by_station <- instat_calculation$new(type="by", calculated_from=list("ghana"="station"))
transform_calculation <- instat_calculation$new(type="calculation", function_exp="(min(30, (min_temperature + max_temperature) / 2) - 35) * ((min_temperature + max_temperature) / 2) > 35", result_name="ModifiedGDD", manipulations=list(group_by_station), save=2, before=FALSE, calculated_from=list("ghana"="max_temperature","ghana"="min_temperature"))
data_book$run_instat_calculation(calc=transform_calculation, display=FALSE)

```
e) Make that name mgdd.

f) I wonder what the programmers will say about your repeated use of `(min_temperature + max_temperature) / 2)` in these formulae, rather than calculating and using tmean?

2022-01-12 11:58 UTC, anastasia-mbithe commented
@rdstern you can have a look at this now.
I have disabled HDD,GDD and Modified GDD, when having tmin and tmax so that they can be used with tmean only, to avoid repetition of (tmin+tmax) / 2
For HDD, it returns a positive value other than 0 when the tmean<15(baseline)

2022-01-12 12:32 UTC, rdstern commented
@anastasia-mbithe no that is not what I was meaning!  The idea is to have efficient code, but not to limit the users.  So please check with @maxwellfundi or others how to improve your code, so you can allow the R calculations to be efficient and not repetitive.  

For example I don't like it and am no good at programming, but could your the second line become:
tmean <- (data_book$get_columns_from_data(data_name="ghana", col_names="max_temperature")+min_temperature)/2
I would like simpler than this and it may not work?

2022-01-14 09:57 UTC, anastasia-mbithe commented
@rdstern Kindly have a look at this.

2022-01-14 18:13 UTC, rdstern requested changes
The first 2 options seem to work.  The up-down for the next 2 should display the point as they only go up by 0.1 at a time.  And the third one isn't the same.  Is there a reason for the difference.  I changed the HDD to 35.  I get an error for each of these.  How much are you checking them, before asking me?

2022-01-17 07:08 UTC, anastasia-mbithe commented
@rdstern  Hello, is it okay if I just set the baseline to one decimal place since the increment is 0.1?

2022-01-17 07:17 UTC, rdstern commented
@anastasia-mbithe you've got it!  The 3 controls should all be to one decimal place.  This is the way you increment.  Also the actual data are usually recorded to one decimal.  In addition, when you test, try with the up-down feature.  But also confirm that typing an accepted number is also possible.  When I want to change 15 to 35 it takes forever with the up-down.  But I usually just type 35 and it works fine.  That option should still remain.

2022-01-17 08:42 UTC, anastasia-mbithe commented
@rdstern I have just added the one decimal place feature. From my end, am not getting any errors while using HDD, GDD and MGDD as you mention on Friday. I have been testing it using 15, 25, 35 as well as any random number I just type and am getting no errors. It's working well from my end.

2022-01-17 11:52 UTC, rdstern commented
Please can you also try my example.  I am using the tidy Ghana data from the library.  And it still says:

![image](https://user-images.githubusercontent.com/11226469/149763269-466d067f-fc72-442f-b917-629919ee1cf7.png)

That is on the third option, (HDD) after running the first 2 options, which seem to work fine.  I tried again after a reset and it crashed me out.  

I checked the up-down controls and they seem better now.  But I wonder why you didn't change the limit control.  There you just type anything you like.  I tried typing aa and it accepted that.  I didn't try running it.  That should become another up-down.

Aha, I have now also tried with dodoma and it works.  So it may be ok with a single station.  But it crashes with multiple stations.  You might like to examine the calculation code carefully, because this isn't a set of calculations that should need to worry about that aspect.  All is just within a single row.  So single or multiple stations should have no effect.  Have you understood the calculations you are doing really carefully.  If not, (and it is quite tricky stuff) then check with Haward or one of the others.

2022-01-20 07:41 UTC, anastasia-mbithe commented
Hello @rdstern, That issue is fixed now and the dialog is working well with both single and multiple station data. I'll be glad if you check it out.

2022-01-20 08:54 UTC, rdstern submitted a review, later dismissed
@anastasia-mbithe you are right, it does now seem to be working well.  @shadrackkibet or @lloyddewit good to check the code, so we can merge

2022-01-20 15:33 UTC, lloyddewit requested changes
@anastasia-mbithe Thank you, this looks good.
I just had a few small questions.

2022-01-20 15:33 UTC, lloyddewit commented on instat/dlgTransformClimatic.vb
> +                clsTransformCheck = clsRTransform
these 4 lines are duplicated in the `ElseIf` statements below.
Should we move these lines to a small private function (with parameters for `"diurnal"` and `clsDiurnalRangeOperator`)?

2022-01-20 15:33 UTC, lloyddewit commented on instat/dlgTransformClimatic.vb
>      Private Sub GroupByStation()
Would something like this be more readable?
Please double-check my logic!
```
    Private Sub GroupByStation()
        If ucrReceiverStation.IsEmpty() OrElse rdoDegree.Checked Then
            clsGroupByStation.RemoveParameterByName("calculated_from")
            clsTransformManipulationsFunc.RemoveParameterByName("group_by_station")
        Else
            clsGroupByStation.AddParameter("calculated_from",
                        "list(" & strCurrDataName & "=" & ucrReceiverStation.GetVariableNames & ")",
                        iPosition:=3)
            clsTransformManipulationsFunc.AddParameter("group_by_station",
                        clsRFunctionParameter:=clsGroupByStation, bIncludeArgumentName:=False,
                        iPosition:=0)
        End If
    End Sub
```

2022-01-20 15:33 UTC, lloyddewit commented on instat/dlgTransformClimatic.vb
> +                clsRTransform.AddParameter("calculated_from", "list(" & strCurrDataName & "=" & ucrReceiverTMax.GetVariableNames & "," & strCurrDataName & "=" & ucrReceiverTMin.GetVariableNames & ")"
move these 3 duplicated lines to a private function?
Also, is `iPosition:=0` correct in the first command (it could be, it just looked a bit inconsistent so I wanted to check)?

2022-01-21 09:01 UTC, anastasia-mbithe commented on instat/dlgTransformClimatic.vb
> +                clsRTransform.AddParameter("calculated_from", "list(" & strCurrDataName & "=" & ucrReceiverTMax.GetVariableNames & "," & strCurrDataName & "=" & ucrReceiverTMin.GetVariableNames & ")"
The iPosition:=0 is correct. And is there need for another private sub since they are already in one and the functions do change with the corresponding radio buttons.

2022-01-21 18:50 UTC, anastasia-mbithe commented
@lloyddewit Thanks for the review, kindly check if the code is okay as you intended.

2022-01-24 09:24 UTC, lloyddewit commented on instat/dlgTransformClimatic.vb
> +        clsRCountFunction.AddParameter("FUN", "sum", iPosition:=2)
@anastasia-mbithe please could you clarify before you resolve the comment? thanks

2022-01-24 09:51 UTC, anastasia-mbithe commented on instat/dlgTransformClimatic.vb
> +        clsRCountFunction.AddParameter("FUN", "sum", iPosition:=2)
@lloyddewit , I didn't notice I moved it, guess it was just a mistake.

2022-01-24 10:27 UTC, lloyddewit requested changes
thank you for the changes. I reviewed them all and I'm happy.
I unresolved one of the old comments, please could you check it?
I also have a couple of extra comments about readability.
Thanks

2022-01-24 10:27 UTC, lloyddewit commented on instat/dlgTransformClimatic.vb
> +            rdoMultSpells.Checked OrElse rdoSpell.Checked OrElse rdoWaterBalance.Checked Then
- If we do a double indent then it's clearer that the line is part of the `If` condition
- It's also more readable if we have use `_` and then put the boolean operator at the start of the line
```suggestion
        If rdoCount.Checked OrElse rdoCumulative.Checked OrElse rdoMoving.Checked _
                OrElse rdoMultSpells.Checked OrElse rdoSpell.Checked OrElse rdoWaterBalance.Checked Then
```

2022-01-24 10:27 UTC, lloyddewit commented on instat/dlgTransformClimatic.vb
> +                Not ucrInputEvaporation.IsEmpty) OrElse (rdoEvapVariable.Checked AndAlso Not ucrReceiverEvap.IsEmpty)))) Then
- the same check is duplicated 3 times. If we use a local boolean, then its more readable
- Please use double indenting as described above
- Please use extra indents to make it clearer to the reader how the checks are nested
```suggestion
            Dim betweenOuterOk As Boolean = (((ucrInputCondition.GetText = "Between" OrElse
                        ucrInputCondition.GetText = "Outer") AndAlso Not ucrInputSpellLower.IsEmpty AndAlso
                        Not ucrInputSpellUpper.IsEmpty) OrElse (ucrInputCondition.GetText = "<=" AndAlso
                        Not ucrInputSpellUpper.IsEmpty) OrElse (ucrInputCondition.GetText = ">=" AndAlso
                        Not ucrInputSpellUpper.IsEmpty))

            If Not ucrReceiverData.IsEmpty AndAlso ucrSaveColumn.IsComplete AndAlso ((rdoCount.Checked AndAlso
                ucrNudCountOver.GetText <> "" AndAlso betweenOuterOk) OrElse (rdoCumulative.Checked AndAlso
                Not ucrInputCumulative.IsEmpty) OrElse (rdoMoving.Checked AndAlso
                Not ucrInputSum.IsEmpty AndAlso ucrNudSumOver.GetText <> "") OrElse
                (rdoSpell.Checked AndAlso betweenOuterOk) OrElse (rdoMultSpells.Checked AndAlso
                ucrNudMultSpells.GetText <> "" AndAlso betweenOuterOk) OrElse (rdoWaterBalance.Checked AndAlso
                ucrNudWBCapacity.GetText <> "" AndAlso ((rdoEvapValue.Checked AndAlso
                Not ucrInputEvaporation.IsEmpty) OrElse (rdoEvapVariable.Checked AndAlso Not ucrReceiverEvap.IsEmpty)))) Then

```

2022-01-24 13:33 UTC, anastasia-mbithe commented
@lloyddewit I have implemented the suggested changes. For the unresolved old comment, I had replied in the conversation for the particular comment.

2022-01-24 16:55 UTC, rdstern approved these changes
still looks ok to me

2022-01-24 16:57 UTC, lloyddewit requested changes

2022-01-24 16:57 UTC, lloyddewit commented on instat/dlgTransformClimatic.vb
> +                Not ucrReceiverEvap.IsEmpty)))) Then
Thank you for the changes. I think that we can still make this more readable.
See example below.
Please check that the logic is still correct!
thanks
```
        If rdoCount.Checked OrElse rdoCumulative.Checked OrElse rdoMoving.Checked _
                OrElse rdoMultSpells.Checked OrElse rdoSpell.Checked _
                OrElse rdoWaterBalance.Checked Then
            Dim betweenOuterOk As Boolean = Not ucrInputSpellUpper.IsEmpty _
                    AndAlso (
                        ((ucrInputCondition.GetText = "Between" OrElse ucrInputCondition.GetText = "Outer") _
                            AndAlso Not ucrInputSpellLower.IsEmpty) _
                        OrElse (ucrInputCondition.GetText = "<=") _
                        OrElse (ucrInputCondition.GetText = ">="))
            If Not ucrReceiverData.IsEmpty AndAlso ucrSaveColumn.IsComplete _
                    AndAlso ((rdoCount.Checked AndAlso ucrNudCountOver.GetText <> "" AndAlso betweenOuterOk) _
                        OrElse (rdoCumulative.Checked AndAlso Not ucrInputCumulative.IsEmpty) _
                        OrElse (rdoMoving.Checked AndAlso Not ucrInputSum.IsEmpty AndAlso ucrNudSumOver.GetText <> "") _
                        OrElse (rdoSpell.Checked AndAlso betweenOuterOk) _
                        OrElse (rdoMultSpells.Checked AndAlso ucrNudMultSpells.GetText <> "" AndAlso betweenOuterOk) _
                        OrElse (rdoWaterBalance.Checked AndAlso ucrNudWBCapacity.GetText <> "" _
                            AndAlso ((rdoEvapValue.Checked AndAlso Not ucrInputEvaporation.IsEmpty) _
                                OrElse (rdoEvapVariable.Checked AndAlso Not ucrReceiverEvap.IsEmpty)))) Then

```

2022-01-24 19:59 UTC, anastasia-mbithe commented on instat/dlgTransformClimatic.vb
> +                Not ucrReceiverEvap.IsEmpty)))) Then
The logic looks correct to me. Thanks

2022-01-25 08:53 UTC, lloyddewit approved these changes

2022-01-25 08:55 UTC, lloyddewit commented
@rdstern another (but hopefully final) test/approval from you is needed, then it's ready for merge.
Would you like to merge this PR in 0.7.4 or is it safer to wait until next week?
thanks

2022-01-25 09:20 UTC, rdstern approved these changes
This is one I am happy to approve and would very much like to see in 0.7.4 (next Monday).
By the way I note one really nice new feature in the current grid.  Usually, with temperaure data the first (1000) rows are empty.  But now you can press the double arrow to go straight to the bottom of the grid.  Very nice.

2022-01-25 10:45 UTC, merged

2022-01-25 10:59 UTC, lloyddewit commented
@anastasia-mbithe 
I think this is the fifth significant PR you've merged since September.
In these PRs, I found your code carefully written, consistent and tidy. This is important for readability and maintainability.
Congratulations on another successful merge and thank you for your contributions.

A small point: In your opening comment, I changed 'This fixes issue #6990' to 'This fixes #6990'. I did this so that issue #6990 is closed when this PR is merged. If you specifically didn't want issue #6990 to be closed, then please let me know. Thanks

(A while ago, I may have incorrectly advised you or others to write 'fixes **issue** #nnnn' but GitHub doesn't recognise this.)

2022-01-25 13:58 UTC, anastasia-mbithe commented
@lloyddewit Thank you so much for that and also for the correction, I appreciate.