Updated database from PRs 6956, 7058 and 7062
africanmathsinitiative/R-Instat pull request #7070
Opened 2021-12-16 09:05 UTC by N-thony

@lloyddewit this PR contains the updated database as suggested on PRs 6956, 7058, and 7062 due to the conflicts. Please take a look. Thanks

2022-01-03 10:39 UTC, lloyddewit requested changes

2022-01-03 10:39 UTC, lloyddewit commented on instat/translations/translationsManuallyEntered.csv
> +Count,en,Count
Should this be ' Count' (i.e. preceded by space)? See PR #7062

2022-01-10 13:57 UTC, N-thony commented
@lloyddewit I have updated the database here rather than opening another PR, and this is because of the small bug in the input station to remembering the state on reopening as related in #6989. Please take a look. Thanks.

2022-01-11 16:02 UTC, lloyddewit approved these changes

2022-01-11 16:02 UTC, lloyddewit commented on instat/translations/translateIgnore.txt
> +# Partially fixes issue, related to PR #7070
@N-thony which issue does it fix? Please state issue number. If there is no related issue, then just state `# Related to PR #7070`

2022-01-11 16:04 UTC, lloyddewit commented
> @lloyddewit I have updated the database here rather than opening another PR, and this is because of the small bug in the input station to remembering the state on reopening as related in #6989. Please take a look. Thanks.

@N-thony the database is a binary file so there is no 'diff' available, and I cannot see what you've changed. If you change the database, then please state exactly which rows you changed (and preferably include a screenshot of the changed rows), thanks

2022-01-11 16:09 UTC, N-thony commented
> > @lloyddewit I have updated the database here rather than opening another PR, and this is because of the small bug in the input station to remembering the state on reopening as related in #6989. Please take a look. Thanks.
> 
> @N-thony the database is a binary file so there is no 'diff' available, and I cannot see what you've changed. If you change the database, then please state exactly which rows you changed (and preferably include a screenshot of the changed rows), thanks
I have changed `dlgInventoryPlot_ucrInputFacetBy` and `dlgInventoryPlot_ucrInputFacetBy_cboInput` `id_text ` to `DoNotTranslate`
![Uploading image.png…]()

2022-01-11 16:24 UTC, lloyddewit commented
@N-thony Thank you for the clarification.
In `translateIgnore.txt` you added the following lines:
```
# In the 'Boxplot' dialog, the selected 'Facet' either for Station, Year or Within Year should not be translated
# Fixes issue #6185, item a), related to PR #7058
dlgClimaticBoxPlot_ucrInputStation%
dlgClimaticBoxPlot_ucrInputYear%
dlgClimaticBoxPlot_ucrInputWithinYear%
dlgClimaticBoxPlot_ucrInputWithinYear_cboInput%
```
However the database contains the following:

![image](https://user-images.githubusercontent.com/57253949/148981146-c7697cb4-4e3c-42df-b5ab-f652fb6ce972.png)
Should these rows be `DoNotTranslate`?

2022-01-11 16:25 UTC, lloyddewit requested changes

2022-01-11 16:25 UTC, lloyddewit commented on instat/translations/translateIgnore.txt
> +dlgClimaticBoxPlot_ucrInputWithinYear_cboInput%
This line is not needed because it's covered by the line above ('%' is a wildcard).
```suggestion
```

2022-01-11 16:25 UTC, lloyddewit commented on instat/translations/translateIgnore.txt
> +dlgInventoryPlot_ucrInputFacetBy_cboInput%
This line is not needed because it's covered by the line above ('%' is a wildcard).
```suggestion
```

2022-01-12 10:53 UTC, lloyddewit approved these changes

2022-01-12 11:00 UTC, lloyddewit commented
@shadrackkibet Please could you test whether this PR fully resolves issue #6185? If yes, then please could you approve and merge this PR? thanks

2022-01-12 13:29 UTC, shadrackkibet commented
The bug reported still exists.

![image](https://user-images.githubusercontent.com/26301973/149149340-faf97768-1e31-406f-9ddc-a4d679519bdc.png)

2022-01-12 13:37 UTC, N-thony commented
> The bug reported still exists.
> 
> ![image](https://user-images.githubusercontent.com/26301973/149149340-faf97768-1e31-406f-9ddc-a4d679519bdc.png)

@shadrackkibet thanks for your review. I think this PR concerns item a) on issue #6185, it partially fixes that issue and another issue of control not remembering the state on reopening due to the translation. I may fix that bug in another PR.

2022-01-12 13:40 UTC, N-thony commented
> > The bug reported still exists.
> > ![image](https://user-images.githubusercontent.com/26301973/149149340-faf97768-1e31-406f-9ddc-a4d679519bdc.png)
> 
> @shadrackkibet thanks for your review. I think this PR concerns item a) on issue #6185, it partially fixes that issue, and other issues of control not remembering the state on reopening due to the translation. I may fix that bug in another PR.

I got an issue with my local branch, I'm cloning again the repo and then I will take a look of the bug. Thanks

2022-01-12 13:53 UTC, shadrackkibet approved these changes
Great. I will merge these changes for now while you consider fixing the other bugs in a separate PR.

2022-01-12 13:53 UTC, merged