Fixed bug on Climatic > InventoryPlot dialogue
africanmathsinitiative/R-Instat pull request #7090
Opened 2022-01-10 15:50 UTC by N-thony

Fixes #7015 
@dannyparsons @ChrisMarsh82  I have tried to fix the bug on the InventoryPlot, please take a look.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2022-01-10 16:11 UTC, rdstern submitted a review, later dismissed
@N-thony that's a releif - it seems to work again!

2022-01-10 18:25 UTC, N-thony commented on instat/Model/Output/clsOutputElement.vb
> +        If rScript.GetLstTokens(rScript.GetLstLexemes(strScript)) Is Nothing Then
@dannyparsons I resolved this. Please take a look. Thanks.

2022-01-11 08:55 UTC, lloyddewit requested changes

2022-01-11 08:55 UTC, lloyddewit commented on instat/UserControl/ucrOutputPage.vb
> +            Exit Function
'Exit Function' is normally used to return a value that was set earlier, e.g.:
``` 
'Returns "Hello"
Private Function Example2() As String
  Example2 = "Hello"
  Exit Function
End Function
```
On line 163, it will return `Nothing`. This is correct but it is clearer to write `Return Nothing`.

2022-01-11 08:55 UTC, lloyddewit commented on instat/UserControl/ucrOutputPage.vb
> +        If outputElement.FormatedRScript Is Nothing Then
If `outputElement` is `Nothing`, then this line triggers an exception. Would it be safer to write:
```suggestion
        If outputElement Is Nothing OrElse outputElement.FormatedRScript Is Nothing Then
```

2022-01-11 09:02 UTC, N-thony commented on instat/UserControl/ucrOutputPage.vb
> +            Exit Function
@lloyddewit many thanks for this. You are right.

2022-01-11 09:03 UTC, N-thony commented on instat/UserControl/ucrOutputPage.vb
> +            Exit Function
@lloyddewit I have resolved your comment. Please take a look. Thanks.

2022-01-11 11:21 UTC, dannyparsons approved these changes
Tested and this works well.

2022-01-11 12:13 UTC, N-thony commented
@rdstern could you test/approve? Thanks.

2022-01-11 15:52 UTC, rdstern approved these changes

2022-01-11 16:09 UTC, lloyddewit approved these changes

2022-01-11 16:09 UTC, merged