Adding sub dialogue for formatting of summary tables
africanmathsinitiative/R-Instat pull request #7107
Opened 2022-01-12 11:05 UTC by Ivanluv

@africanmathsinitiative/developers this fixes  #6770 and replaces PR #6977

2022-01-12 18:53 UTC, lloyddewit commented
@Ivanluv Thanks, is this PR ready for test/review or are you still working on it?
(if not ready, then you could set this PR to 'draft' to make its status clearer)

2022-01-13 05:58 UTC, Ivanluv commented
@lloyddewit thank you for the reminder.@africanmathsinitiative/developers  this is ready for review

2022-01-14 11:35 UTC, rdstern requested changes
I keep having more questions, but if @lilyclements agrees, I would like to merge this as soon as possible.  So just one thing to check - hope it is easy.  
This is that the order of the variables in the table is not the same as the order in the receiver.  I think it is alphabetical in the table.  I can live with this temporarily if it is difficult to fix?
My next question (for a new issue?) is how to dictate the order of the summaries in relation to the variables and the other factors in the table?

2022-01-14 16:23 UTC, lilyclements commented
> This is that the order of the variables in the table is not the same as the order in the receiver

This is fixed in PR #7128

2022-01-14 16:30 UTC, lilyclements commented
> I keep having more questions, but if @lilyclements agrees, I would like to merge this as soon as possible

@rdstern I agree that this is good to merge, and you can outlined your questions elsewhere to work on

2022-01-14 17:09 UTC, rdstern submitted a review, later dismissed
@lloyddewit or @shadrackkibet there is still a lot to do on improving the tables.  But this is already a major improvement on 7.3.1 and I suggest it be merged, and then we make another issue for further improvements.  I have checked and @lilyclements agrees to merga at this point.

2022-01-14 19:41 UTC, lloyddewit commented
@HawardKetoyoMsatsi Please could you do the first review? thanks

2022-01-17 10:49 UTC, HawardKetoyoMsatsi commented
![image](https://user-images.githubusercontent.com/16137042/149735836-13e3d14b-6730-4abc-bc03-453218ef29d8.png)

The design of the sub dialog looks good, with just a few enhancements.
Add (:) after `Title Font` and `Title Size` labels.
The Minimum value of the input `Title Size:` is set to zero, Could it have been a positive value?

2022-01-17 10:51 UTC, HawardKetoyoMsatsi requested changes

2022-01-17 10:51 UTC, HawardKetoyoMsatsi commented on instat/dlgFrequency.vb
> -    Private clsMmtableOperator As New ROperator
Remove this line, clsMmtableOperator has been initialized twice

2022-01-18 07:38 UTC, Ivanluv commented
> The Minimum value of the input `Title Size:` is set to zero, Could it have been a positive value?

I have that set to 1 now

2022-01-18 07:40 UTC, Ivanluv commented on instat/dlgFrequency.vb
> -    Private clsMmtableOperator As New ROperator
I cant seem to find the other initialization

2022-01-18 08:16 UTC, HawardKetoyoMsatsi commented on instat/dlgFrequency.vb
> -    Private clsMmtableOperator As New ROperator
Check clsMmtableOperator appears in both lines 24 and 25.

2022-01-19 07:14 UTC, Ivanluv commented
@HawardKetoyoMsatsi are you done reviewing this?

2022-01-19 09:44 UTC, HawardKetoyoMsatsi commented
Thanks, @Ivanluv I see the changes I requested have been made. 
@lloyddewit over to you.

2022-01-19 11:50 UTC, lloyddewit requested changes

2022-01-19 11:50 UTC, lloyddewit commented on instat/dlgSummaryTables.vb
>                  iColumn = iColumn + 1
shorten and make more readable?
```suggestion
                Dim clsHeaderFunction As New RFunction
                clsHeaderFunction.SetPackageName("mmtable2")
                clsHeaderFunction.SetRCommand(If(iColumn < iNumberOfColumns, "header_top_left", "header_left_top"))
                clsHeaderFunction.AddParameter("variable", strColumn, iPosition:=0)
                clsColumnOperator.AddParameter(strColumn, clsRFunctionParameter:=clsHeaderFunction, iPosition:=iColumn)
                iColumn += 1
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/dlgSummaryTables.vb
>              For Each strcolumn As String In ucrReceiverFactors.GetVariableNamesAsList
```suggestion
            For Each strColumn As String In ucrReceiverFactors.GetVariableNamesAsList
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +Public Class sdgFormatSummaryTables
```suggestion

Public Class sdgFormatSummaryTables
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +    'when openning the subdialogue from multiple dialogues
```suggestion
    'The dummy Function is used by input controls that add the parameter manually,
    'when opening the subdialogue from multiple dialogues
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +    Public Sub InitialiseControls()
```suggestion

    Public Sub InitialiseControls()
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkTitleFootnote.AddParameterPresentCondition(False, "titlefootnote", False)
`"titlefootnote"` is different to the parameter set on line 45 (`"title_footnote"`). 
The same is true on other calls to `AddParameterPresentCondition` below.
Does this matter?
Sorry if this is an ignorant question

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +        ucrChKAddSecondFootnote.SetText("Add Second footnote")
```suggestion
        ucrChKAddSecondFootnote.SetText("Add second footnote")
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkAddSourcenote.SetText("Add Source")
```suggestion
        ucrChkAddSourcenote.SetText("Add source")
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkAddHeader.SetText("Add Header")
```suggestion
        ucrChkAddHeader.SetText("Add header")
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkAddTableFormat.SetText("Add Table format")
```suggestion
        ucrChkAddTableFormat.SetText("Add table format")
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkStyleText.SetText("Add Text style")
```suggestion
        ucrChkStyleText.SetText("Add text style")
```

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +        ucrInputCellFootnote.SetParameter(New RParameter("cellFootnote", iNewPosition:=4))
This parameter name has a different format than the others (I expected "cell_footnote"), is it correct?

2022-01-19 11:50 UTC, lloyddewit commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkStyleBoarder.AddParameterPresentCondition(False, "boarderStyle", False)
should it be 'border' not 'boarder'?

2022-01-20 08:03 UTC, Ivanluv commented on instat/sdgFormatSummaryTables.vb
> +        ucrInputCellFootnote.SetParameter(New RParameter("cellFootnote", iNewPosition:=4))
Yes, it should be `cell_footnote`

2022-01-20 08:04 UTC, Ivanluv commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkStyleBoarder.AddParameterPresentCondition(False, "boarderStyle", False)
`border`...I have corrected that

2022-01-20 08:04 UTC, Ivanluv commented
@lloyddewit could you have a look again

2022-01-20 16:11 UTC, lloyddewit commented
@Ivanluv thank you for all the changes, I'm happy with all the comments you marked as resolved.
There are 3 unresolved comments above (I had to click on a link in the list to unhide them, so maybe you didn't see them), please could you try and resolve these also?
Thanks

2022-01-21 06:31 UTC, Ivanluv commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkTitleFootnote.AddParameterPresentCondition(False, "titlefootnote", False)
I have made the changes

2022-01-21 06:33 UTC, Ivanluv commented on instat/sdgFormatSummaryTables.vb
> +        ucrChKAddSecondFootnote.SetText("Add Second footnote")
Done

2022-01-21 06:33 UTC, Ivanluv commented on instat/sdgFormatSummaryTables.vb
> +        ucrChkAddSourcenote.SetText("Add Source")
Done

2022-01-21 06:37 UTC, Ivanluv commented
@lloyddewit I missed the three comments but they are now resolved. Could you have a look?

2022-01-24 10:51 UTC, lloyddewit commented
> @lloyddewit I missed the three comments but they are now resolved. Could you have a look?

@Ivanluv thanks for fixing those, I set them to resolved

2022-01-24 10:53 UTC, lloyddewit approved these changes

2022-01-24 10:54 UTC, lloyddewit commented
@rdstern Please could you test again?
Some of the parameters have changed since your last approval, so it may be worth a full test.
Thanks!

2022-01-24 17:45 UTC, rdstern commented
@Ivanluv just checking.  I get the right answers here, but the order is still alphabetical of the variables, and not the order they were in the dialogue.  I am pretty sure this was fixed by @lilyclements so assume it might be ok once merged?  Am I right?
![image](https://user-images.githubusercontent.com/11226469/150834316-bf8ee1c9-52bb-416a-8ada-eacc24988525.png)

And then it gets more "interesting" when I add the margins!  This might be a @lilyclements question?
![image](https://user-images.githubusercontent.com/11226469/150835729-04add97c-b030-4785-b62d-dbf3d85b3046.png)

That's from the dialogue with the R-Instat review like this:
![image](https://user-images.githubusercontent.com/11226469/150836004-fa4409fa-0271-4627-8614-1b0c8b023333.png)

The R-code is here:

![image](https://user-images.githubusercontent.com/11226469/150836106-21544107-6cbf-4a4c-b6af-1e8d50973aae.png)

And I haven't got to the sub-dialogues yet!

2022-01-24 18:25 UTC, rdstern commented
On the sub-dialogues I was able to play and got this far:
![image](https://user-images.githubusercontent.com/11226469/150841338-db53304b-3e85-491c-a1df-5b067657db20.png)

I had hoped to put some colour into the table itself, but didn't manage.  I also wrote some text as a "stub" but couldn't find it.  And I tried to align the numbers above as left and they still seem right!

The code for the above is here:
![image](https://user-images.githubusercontent.com/11226469/150841671-e39af0f8-f2d3-44b6-9626-d77f396cee21.png)

Overall we always knew the formatting is "work-in-progress" and I'd be happy for these to be merged as is, once the main part is examined.

It would be really good to get this into the forthcoming release, because the existing version has a serious bug.

2022-01-25 10:47 UTC, Ivanluv commented
> @Ivanluv just checking. I get the right answers here, but the order is still alphabetical of the variables, and not the order they were in the dialogue. I am pretty sure this was fixed by @lilyclements so assume it might be ok once merged? Am I right?

True this is fixed, I had not updated the branch but now it should be okay

2022-01-25 17:08 UTC, lloyddewit approved these changes

2022-01-25 17:09 UTC, lloyddewit commented
@rdstern If you can approve, then we can merge, thanks

2022-01-26 16:25 UTC, lilyclements commented
> And then it gets more "interesting" when I add the margins! This might be a @lilyclements question? ![image](https://user-images.githubusercontent.com/11226469/150835729-04add97c-b030-4785-b62d-dbf3d85b3046.png)

@rdstern thanks - I think this should be now fixed in PR #7172 (it is working from my side now anyway).

2022-01-26 16:25 UTC, lilyclements commented
> And then it gets more "interesting" when I add the margins! This might be a @lilyclements question? ![image](https://user-images.githubusercontent.com/11226469/150835729-04add97c-b030-4785-b62d-dbf3d85b3046.png)

@rdstern thanks - I think this should be now fixed in PR #7172 (it is working from my side now anyway).

2022-01-28 09:44 UTC, lloyddewit commented
@Ivanluv @lilyclements As you know, we're hoping to build a new release on Monday. 
I understand from @rdstern that: 

'PR #7107 and PR #7172 are (together) the important ones.  Together they are almost ok now, but I am not sure if they will both merge, or Ivan could incorporate 7172 in his 7107.  There also remains a very minor issue I found, that if variable names contain a ".", then it gives an error.  Lily is checking, but we could merge anyway if she doesn't find it.'

If there's any chance of making progress today on these PRs, then that would be great.
I'm available this morning and then travelling this afternoon/evening. I'll check again on Sunday to see if there's anything I can review/approve/merge.

Thanks

2022-01-28 10:01 UTC, Ivanluv commented
@lloyddewit   I could incorparate PR #7172 into PR #7107 then have #7172 closed to avoid conflicts

2022-01-28 10:53 UTC, lloyddewit commented
> @lloyddewit I could incorparate PR #7172 into PR #7107 then have #7172 closed to avoid conflicts

@Ivanluv Sounds sensible. If you think this is the best approach, then please go ahead.
Will you or @lilyclements still try and resolve the '.' issue first, or do you prefer to merge and solve the issue in a separate PR?

2022-01-28 11:01 UTC, lilyclements commented
> > @lloyddewit I could incorparate PR #7172 into PR #7107 then have #7172 closed to avoid conflicts
> 
> @Ivanluv Sounds sensible. If you think this is the best approach, then please go ahead. Will you or @lilyclements still try and resolve the '.' issue first, or do you prefer to merge this PR first and solve the issue in a new PR?

I will look into this issue today and it is easier to do it on a new PR.

2022-01-30 15:35 UTC, merged