Fixed the message to not appear when no data is loaded
africanmathsinitiative/R-Instat pull request #7109
Opened 2022-01-12 12:37 UTC by N-thony

Fixes #7102 
@dannyparsons this PR fixed the small bug related to the corresponding issue. Please take a look. Thanks.

2022-01-13 07:10 UTC, Patowhiz commented on instat/frmMain.vb
>                                           MessageBoxButtons.YesNo, "Close Data") Then
@N-thony would be ideal to pass this `"Are you sure you want to close your data?"` and `"Any unsaved changes will be lost."` through the translations function. 
You don't necessarily have to do it in this PR and I'm also not sure if we the 2 corresponding translations in the database. (@lloyddewit  could easily add the translations later and not have to change this line)

2022-01-13 07:42 UTC, N-thony commented on instat/frmMain.vb
>                                           MessageBoxButtons.YesNo, "Close Data") Then
@Patowhiz we don't have the 2 corresponding translations in the database that is the reason I made directly the change here.

2022-01-13 08:46 UTC, dannyparsons commented on instat/frmMain.vb
>                                           MessageBoxButtons.YesNo, "Close Data") Then
Good point, we should work on having all our messages going through the translation system. Can be done separately from this PR.

2022-01-13 08:50 UTC, dannyparsons submitted a review, later dismissed
Looks good to me

2022-01-13 12:21 UTC, shadrackkibet requested changes

2022-01-13 12:21 UTC, shadrackkibet commented on instat/frmMain.vb
> +            If ucrDataViewer.GetWorkSheetCount() = 0 OrElse DialogResult.Yes = MsgBox("Are you sure you want to close you data?" &
Looks like you reverted the typo correction?

2022-01-13 12:23 UTC, N-thony commented on instat/frmMain.vb
> +            If ucrDataViewer.GetWorkSheetCount() = 0 OrElse DialogResult.Yes = MsgBox("Are you sure you want to close you data?" &
Yes, as @Patowhiz, I will fix that in another PR. But first I will check with @lloyddewit for the possibility.

2022-01-13 12:34 UTC, shadrackkibet commented on instat/frmMain.vb
> +            If ucrDataViewer.GetWorkSheetCount() = 0 OrElse DialogResult.Yes = MsgBox("Are you sure you want to close you data?" &
Okay

2022-01-13 12:35 UTC, shadrackkibet submitted a review, later dismissed

2022-01-14 09:59 UTC, lloyddewit commented on instat/frmMain.vb
>                                           MessageBoxButtons.YesNo, "Close Data") Then
`MsgBox` text is not currently translated. Some `MsgBox` text is multiline and/or contains variable values. This text will be more difficult to translate.
I suggest that we implement the `MsgBox` translation mechanism, across all of R-Instat, in a separate PR.
In summary, I think @N-thony was correct to fix this typo here.

2022-01-14 10:00 UTC, lloyddewit commented on instat/frmMain.vb
> +            If ucrDataViewer.GetWorkSheetCount() = 0 OrElse DialogResult.Yes = MsgBox("Are you sure you want to close you data?" &
@N-thony your original typo fix was correct (see my comment above)
```suggestion
            If ucrDataViewer.GetWorkSheetCount() = 0 OrElse DialogResult.Yes = MsgBox("Are you sure you want to close your data?" &
```

2022-01-14 10:03 UTC, lloyddewit approved these changes

2022-01-14 10:04 UTC, lloyddewit commented
@shadrackkibet @rdstern Please could one of you test/merge? thanks

2022-01-14 10:04 UTC, shadrackkibet approved these changes

2022-01-14 10:04 UTC, merged