Added checkbox to Random samples
africanmathsinitiative/R-Instat pull request #7117
Opened 2022-01-12 19:11 UTC by Vitalis95

Fixes #7077 
This fixes part (e) and (f) of the issue.
@africanmathsinitiative/developers , this is ready for review.

2022-01-13 21:09 UTC, rdstern submitted a review, later dismissed
Looks good

2022-01-14 08:22 UTC, Ivanluv commented on instat/dlgRandomSample.vb
> +        ucrChkRngKind.SetParameter(New RParameter("checked", 0))
You also don't need this since it's adding parameter within its `controlValueChanged `event

2022-01-14 08:22 UTC, Ivanluv commented on instat/dlgRandomSample.vb
> +        ucrChkRngKind.SetValuesCheckedAndUnchecked("TRUE", "FALSE")
Remove this too

2022-01-14 08:24 UTC, Ivanluv commented on instat/dlgRandomSample.vb
> +        ucrChkRngKind.AddParameterValuesCondition(False, "checked", "FALSE")
use 
```
 ucrChkRngKind.AddRSyntaxContainsFunctionNamesCondition(True, {"RNGkind"})
  ucrChkRngKind.AddRSyntaxContainsFunctionNamesCondition(False, "RNGkind"},False)
```
instead

2022-01-14 08:24 UTC, Ivanluv commented on instat/dlgRandomSample.vb
> +        clsDummyFunction = New RFunction
Remove this too

2022-01-14 08:25 UTC, Ivanluv commented on instat/dlgRandomSample.vb
> +        clsDummyFunction.AddParameter("checked", "FALSE", iPosition:=0)
This is also not needed

2022-01-14 08:25 UTC, Ivanluv commented on instat/dlgRandomSample.vb
> +        ucrChkRngKind.SetRCode(clsDummyFunction, bReset)
This is also not needed

2022-01-14 08:26 UTC, N-thony commented
@Vitalis95 I have tried to run this and I have this in the output
![image](https://user-images.githubusercontent.com/68591383/149475697-188ac1e5-8e11-4e06-b945-dc8a4c18015d.png)

2022-01-14 08:26 UTC, Ivanluv reviewed
@shadrackkibet  Other than the minor changes required this looks okay from my end

2022-01-14 13:22 UTC, Vitalis95 commented
@Ivanluv , @N-thony I  have made the changes. Have look at it
Thanks.

2022-01-14 13:44 UTC, Vitalis95 commented
@N-thony , have look at again. Thanks

2022-01-14 13:51 UTC, N-thony approved these changes

2022-01-14 14:00 UTC, Ivanluv submitted a review, later dismissed

2022-01-14 19:33 UTC, lloyddewit submitted a review, later dismissed

2022-01-14 19:35 UTC, lloyddewit commented
@Vitalis95 Thank you for this PR. Do you want issue #7077 to be closed automatically when this PR merges? If not, then please change first line of the first comment.

@rdstern Please can you test? 

Thanks

2022-01-15 07:44 UTC, Vitalis95 commented
@lloyddewit, let the issue #7077 be closed automatically once the PR is merged. Thanks

2022-01-15 10:30 UTC, rdstern requested changes
Looks good.  But could you add default as the fist option, as mentioned in the issue.  The reason is as follows, from the documentation:
"Use "default" to return to the R default."

So, remember when it is set, it is a special command which (I don't think is cleared at all).  So it will apply for future dialogues - not just this one, that use a random number generator.  So the default option is where you give the command with default as the string.  Unusually that's not the same as not giving the command. .

2022-01-17 07:57 UTC, Vitalis95 commented
@rdstern, I have added "default" as first option. Have look at it.

2022-01-17 11:20 UTC, rdstern approved these changes
Looks good now.  I am happy that the default option is added and seems to work fine.
@lloyddewit and @shadrackkibet you approved before and the change is very minor.  So I hope this can be merged?

2022-01-18 06:54 UTC, shadrackkibet requested changes
Looks good. Check code comments and the two below.

- Sort out the Tab order.
- Align left of the RNG Combobox with the controls below it.

2022-01-18 06:54 UTC, shadrackkibet commented on instat/dlgRandomSample.vb
> +        ucrInputRngKind.SetItems(dctRNGKind)
Make this drop-down non-editable because we have specific options to choose from. Although the function allows partial matching I don't think this is a sensible reason to make it editable.

2022-01-18 06:54 UTC, shadrackkibet commented on instat/dlgRandomSample.vb
> +            ucrBase.clsRsyntax.AddToBeforeCodes(clsRNGKindFunction, iPosition:=0)
Check that the `iposition` number is correct here. I think this function should run before `set.seed()` therefore you need to change position in line 189 to 1?

2022-01-18 06:54 UTC, shadrackkibet commented on instat/dlgRandomSample.vb
> +        ucrChkRngKind.SetText("RNGKind")
**RNG** is an abbreviation. Therefore I think the label should be two words? i. e "RNG Kind"

2022-01-18 06:54 UTC, shadrackkibet commented on instat/dlgRandomSample.vb
> +        ucrChkRngKind.SetRSyntax(ucrBase.clsRsyntax, bReset)
The `.SetRsyntax` should be sufficient no need to `.SetRcode`

2022-01-18 12:35 UTC, Vitalis95 commented
@shadrackkibet , I have made the changes. Thanks

2022-01-18 18:09 UTC, shadrackkibet requested changes

2022-01-18 18:09 UTC, shadrackkibet commented on instat/dlgRandomSample.vb
> +        dctRNGKind.Add("default", Chr(34) & "default" & Chr(34))
The name should start with capital `D` i.e "Default"

2022-01-19 06:36 UTC, Vitalis95 commented
![default](https://user-images.githubusercontent.com/89011415/150077021-6e7c0840-7eab-4e63-9491-e84c39d96307.jpg)
@shadrackkibet,  this the error that is produced when I change it to "Default". I think it should remain "default".

2022-01-19 06:46 UTC, Vitalis95 commented
@shadrackkibet , have look at it.

2022-01-19 07:02 UTC, rdstern commented
@Vitalis95 I don't have strong views on this.  The command to R must be given in lower case, i.e. default.  If you wish, you can still have Default in the dialogue as long as you change to lower case, when issuing the command.  R is strict here.

2022-01-24 07:21 UTC, Vitalis95 commented
@rdstern , Please could you test? thanks

2022-01-24 13:53 UTC, rdstern approved these changes

2022-01-24 15:09 UTC, shadrackkibet approved these changes

2022-01-24 15:10 UTC, merged