Improving the Describe > One Variable > Summarise dialogue
africanmathsinitiative/R-Instat pull request #7123
Opened 2022-01-13 13:39 UTC by Ivanluv

fixes #7081 
@africanmathsinitiative/developers this is ready for review
@rdstern In this PR I have added the functionality to control the orientation, i.e. choosing whether the variables or the summaries go down in the summary table

2022-01-14 10:44 UTC, rdstern commented
@Ivanluv well done.  That looks great for a start.
a) Omit the Treat Columns as Factor checkbox, but always do that, so the 2 other controls are always visible.
b) Change the Label for the first from Summary to Summaries.  Default is for it to be checked.
c) Now a puzzle that might be more difficult to resolve, namely the receiver can take any type of variable.  So could be factor, or ordered factor or date, etc.  Currently it gives an error for dates or factors or character variables.  Daters should be ok (in the long run) to solve, and also need to be possible in the general tabulation.  I am happy for most summaries to be missing when they don't apply.  But I would like to be able to cope with those that do.  I hope you may have ideas on what can be done in mmtable2, e.g. dates, and what might be impossible.   
d) Could you also check on different types of output - this applies to the general tabulation as well.  Currently it is html.  @Patowhiz is looking into whether that may be possible in the output window.  I wonder whether there might be other options, particularly simple ones that could go into the current output window.

2022-01-20 17:15 UTC, rdstern commented
@Ivanluv it now seems to get the correct summaries, but in the wrong order.
![image](https://user-images.githubusercontent.com/11226469/150387648-e7cc8259-0d08-4507-ad10-fbf1e586fe4d.png)
This was the dialogue:
![image](https://user-images.githubusercontent.com/11226469/150387845-f3a16960-ee34-4e92-a309-a582c4911e91.png)

a) You can see that Blue Sky remains at the top in the results, but its summary is at the bottom!
b) The summary for R-Instat is in second place (towards the top - but it should be second from the bottom.
c) The labelling has become alphabetical.

And, may need @lilyclements help - it doesn't work for factor variables. etc.  I would like it to do something for variables of any type.  Not sure what to do here?

2022-01-21 22:17 UTC, rdstern requested changes
Comments given for changes

2022-01-24 06:18 UTC, Ivanluv commented
@lilyclements  any suggestions here

2022-01-26 17:01 UTC, lilyclements commented
@Ivanluv have you tried updating your branch? I am not getting this error if I try it on the version in #7107 - which I assume is more updated.

2022-01-27 06:48 UTC, Ivanluv commented
> And, may need @lilyclements help - it doesn't work for factor variables. etc. I would like it to do something for variables of any type. Not sure what to do here?

@lilyclements  I have updated this branch and its now working okay

2022-01-27 06:49 UTC, Ivanluv commented
> And, may need @lilyclements help - it doesn't work for factor variables. etc. I would like it to do something for variables of any type. Not sure what to do here?

@lilyclements d you have any ideas how we could fix this?

2022-01-27 10:39 UTC, rdstern requested changes
@Ivanluv this is now working fine.  Now I tried with other types of data (not-numeric) and it doesn't like that.
Now I thought you might need help from @lilyclements for this.  But then I tried with our summary system and that handles all types of data perfectly - even character variables.  And dates come out fine as dates in the summary.  So I wonder if that can provide the code to be used before going into mmtable?  
I treid with dodoma data, so there is a date variable  and also month as a factor.  Then I made month into character.  It just gives NA when it can't work out the summary!

On the actual dialogue could you have the Variables as rows checked by default.

2022-01-27 11:11 UTC, Ivanluv commented
@rdstern by the "summary system" do you mean summary tables?

2022-01-27 11:39 UTC, rdstern commented
No, I meant Prepare > Data: Reshape > Column Summaries.  The first receiver is Variable(s) to Summarise and it allows all types of variable - as does your Describe > One Variable > Summarise.  And it also has the same sub-dialogue as yours, and copes with any summary for any type!  Just what we need in your One Variable dialogue!

2022-01-27 16:37 UTC, rdstern commented
@Ivanluv you ask - " should we have the results stored as it is being done in the Describe > One Variable > Summarise?"  I assume you mean as is done in the Prepare > One Variable > Column Summaries"

I would not, at least for now.  Once we are able to do sensible summaries for variables of all types, then I would like to merge and then reflect and consider.  

What is done here is a great update, and very useful.  I am more concerned here with the tables of results.  And they are able to use any of the summaries we have in our system.  There will be more to do, but that can come later.  We need it to stay simple, but could usefully add the options for the missing values - now that we have them in a package.
Then I am waiting for Patrick to sort out html for the output window, which will be great.

Then (as you say) there will be 2 further directions:  
a) More flexibility on the output.  We could add the presentation options from the Summary tables work.  But let's finish that on the summary tables dialogue first.  Then this dialogue could allow users to practice with very simple structures.
b) We could permit the save - as you say.

We also apply these ideas to the 2-way and 3-way tables - if we have the 3-way - I think so!  

Then in simple graphs and tables (which IS descriptive statistics after all) we have a package to be envied!
This will be good for both teaching and also doing!

2022-01-28 11:38 UTC, rdstern reviewed
@Ivanluv not sure what has happened here?  This now seems like the old dialogue again?

2022-01-28 11:55 UTC, Ivanluv commented
@rdstern  Am still making the changes  for the dialogue.

2022-01-30 18:02 UTC, rdstern requested changes
Hi @Ivanluv I assume these changes are "work in progress?", but I had a quick look.
a) The options are now visible all the time.  Should not be, for the default where the summary is used.
b) The default of ticking the Variables as rows is still to be done.
c) The summary gives an error now.

2022-01-31 13:21 UTC, Ivanluv commented
@rdstern could you have a look

2022-01-31 16:19 UTC, rdstern commented
@Ivanluv I think you may be a few tweaks away from what's needed.
I used the review data as before.
a) It now does not give an error when you add the category variables.  Hooray!
b) The answers seem to be correct.
c) But the variables are in alphabetical order - not the order in the dialogue.  (We used to have that problem with the tables.
d) And the proportions don't work.  They give missing values.  (I had the count > 0 as the statistic)
e) And the Omit Missing Values checkbox doesn't seem to work.  - the summary sums are still given as missing.

Here is the table I got:
![image](https://user-images.githubusercontent.com/11226469/151830250-998abf77-223c-4889-a8fe-54de4b8e3d0f.png)

And here are the commands you generated:
![image](https://user-images.githubusercontent.com/11226469/151831332-b096003b-7743-42c4-88ee-b509bc019b1c.png)

2022-02-01 11:48 UTC, Ivanluv commented
> c) But the variables are in alphabetical order - not the order in the dialogue. (We used to have that problem with the tables.

@lilyclements could you look at the RCode and see what I might have missed in the code for this error to occur. Could you also help me find out why the proportions are not working (part (d) of Rogers review above)

2022-02-13 22:05 UTC, rdstern commented
@Ivanluv @lilyclements will soon be looking at the R code.  In the meantime could you make a cosmetic change to the dialogue as follows:
Change the radio buttons Default and Customised to our more usual ones (when they change other controls, i.e. they become 2 option buttons at the top.
With the customised we should also check - if it is easy - adding the Missing Value option button (sub-dialogue) from Summary - mI assume that will be easy?

2022-02-14 13:25 UTC, lilyclements commented
@Ivanluv if the user selects to modify/choose the summary statistics to display, you are currently using `$calculate_summary` not `$summary_table`. 

`$summary_table` is a wrapper for `$calculate_summary` therefore you do not need to use `$pivot_longer` with `$summary_table` as that is all incorporated into the code.
Additionally, the alphabetical order would be sorted with `$summary_table` since this is already written in.
Is there a reason to not use `summary_table`?

In PR #7230, the code is fixed to use date variables in the summary functions. Once this is merged in, then update your master and hopefully that will work! (Or you can merge it into this PR if you think that's more appropriate).

2022-02-14 15:40 UTC, lilyclements commented
@Ivanluv I'm not sure if this will fix the proportions problem. If it is still a problem after changing the function then I can look into it then

2022-03-08 12:57 UTC, lilyclements commented
@Ivanluv how is this work going?

2022-03-08 14:14 UTC, Ivanluv commented
@lilyclements  am waiting for PR #7230 to be merged

2022-03-14 12:36 UTC, Ivanluv commented
@rdstern @lilyclements  I have merged PR #7230 into this and made the changes as suggested by @lilyclements i.e using the `summary_table `function instead of the `$calculate_summary` function. There is however a challenge when trying to find summaries not supported by certain data types eg getting the sum of factor columns as below.

![image](https://user-images.githubusercontent.com/45068931/158173039-a0725b44-c9b6-4b81-b6a9-7feda0a0347c.png)


![image](https://user-images.githubusercontent.com/45068931/158172958-85bd676f-eee4-4908-babd-9eedde837fc1.png)

![image](https://user-images.githubusercontent.com/45068931/158173107-b59c5deb-a781-4d8e-b99a-920b04f8600a.png)

After the error the table won't be produced even if one of the selected columns supports the summary

2022-03-16 12:24 UTC, rdstern commented
It is looking nice
![image](https://user-images.githubusercontent.com/11226469/158587961-ab01dd34-7dc7-4fe0-874a-58968e1af744.png)


Note sensible summaries for date variables.  And I made month into an ordered factor, so it can get the min and max!  That's nice to explain to people!


But we do need to solve the problem that @Ivanluv mentioned, namely that it can't cope with some summary statistics - like sum, or mean, for a factor.  When values are missing, and that option isn't given, then that cell is blank.  We need the same for those statistics for a factor variable, etc.

One small change if @Ivanluv can't solve the current error, is to move the Missing option to below the other 2 checkboxes.  Then it will be in the same relative position as in the summary dialogue.  
But we can't merge until we can present tables of results for datasets (like the simple survey) that mix factors and variates.

2022-03-24 14:04 UTC, lilyclements commented
So the sum/mean for factor is a problem in `calculate_summary` function. The same error reported by @Ivanluv can occur elsewhere in R-Instat. For example, in the "Column Summaries" dialog - 

![image](https://user-images.githubusercontent.com/21180424/159926461-7c603f5c-ada4-4242-bed7-601515f6b370.png)

I'll work on getting this into the `calculate_summary` function.

2022-03-29 15:41 UTC, lilyclements commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
>          summary_margins[[length(summary_margins) + 1]] <- data_book$calculate_summary(data_name = "summary_margins_df", columns_to_summarise = "value", summaries = summaries, factors = facts, store_r
here

2022-03-29 15:41 UTC, lilyclements commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
>          data_book$delete_dataframes(data_names = "summary_margins_df")
finally here. Thanks!

2022-03-29 15:52 UTC, lilyclements commented
> @rdstern @lilyclements I have merged PR https://github.com/africanmathsinitiative/R-Instat/pull/7230 into this and made the changes as suggested by @lilyclements i.e using the summary_table function instead of the $calculate_summary function. There is however a challenge when trying to find summaries not supported by certain data types eg getting the sum of factor columns as below.

@Ivanluv @rdstern I have now fixed this bug in PR #7338

2022-03-31 09:08 UTC, Ivanluv commented
@lilyclements  I have pulled you changes from  PR #7338 and am getting the following error
![image](https://user-images.githubusercontent.com/45068931/161019423-86907f17-dcf6-43e4-bdf5-fbe772318baf.png)

![image](https://user-images.githubusercontent.com/45068931/161019539-fab2e426-df1f-4895-a122-339234b4af82.png)
![image](https://user-images.githubusercontent.com/45068931/161019692-6a87800a-baab-4f25-b70f-a992ddf6f18d.png)

2022-03-31 09:40 UTC, lilyclements reviewed
@Ivanluv is village or size a character variable? If so then the following should fix it. If not, then the following will fix another potential bug so can you implement the following anyway:

2022-03-31 09:40 UTC, lilyclements commented on instat/static/InstatObject/R/Backend_Components/calculations.R
> +        curr_data_list[[c_data_label]] <- curr_data_list[[c_data_label]] %>%
@Ivanluv can you change “factor | Date” to
“factor | character | Date”

it is important to have a space between the | too

2022-03-31 09:57 UTC, Ivanluv commented on instat/static/InstatObject/R/Backend_Components/calculations.R
> +        curr_data_list[[c_data_label]] <- curr_data_list[[c_data_label]] %>%
On it

2022-03-31 10:20 UTC, Ivanluv commented on instat/static/InstatObject/R/Backend_Components/calculations.R
> +        curr_data_list[[c_data_label]] <- curr_data_list[[c_data_label]] %>%
@lilyclements  the bug is now fixed

2022-04-01 20:45 UTC, rdstern commented
@Ivanluv was this supposed to work now?  I tried with a minimum for a factor and it said that isn't allowed.

2022-04-07 06:42 UTC, rdstern commented
@Ivanluv and @lilyclements I am hoping this will be included in the Version 0.7.5 update?  That's in 2 weeks time.  OK?

2022-04-08 09:35 UTC, lilyclements commented
> @Ivanluv was this supposed to work now? I tried with a minimum for a factor and it said that isn't allowed.

@rdstern which combinations do we not want to work?

**Factors and characters:**
minimum/maximum
mean
median
sum
range
SD
variance

**Ordered factors:**
mean
median
sum
range
SD
variance

**Dates:**
sum?

I have not yet put in that min/max (amongst others in the list above) shouldn't work for factors or characters, but that is very quick to add. I'll add any other combinations when you've responded to this so I know if there's any I'm missing here. Thanks!

2022-04-08 09:51 UTC, rdstern commented
@lilyclements and @Ivanluv I'd prefer to look at this the other way round, namely what is sensible for different types.  I am just keen that we have an option to mix the data types in this dialogue, rather than having to think carefully what to put in the the receiver.
So numeric allows everything.  Logical and date are special cases of numeric
a) Ordinary factors (or character) only allow number of values, including number of unique values, number of missing, etc.
b) Ordered factors allow max and min (and they should therefore allow range - perhaps we don't yet use the range function?
c) Ordered factors currently don't allow anything else.  I actually don't wee why they can't allow median and other percentiles, because they are ordered.  But let's stick with what R does for now.  
d) So only the numeric types allow means, sd, skewness and everything else.  And for now percentiles, and proportions, etc.

2022-04-12 12:44 UTC, Ivanluv commented
@lilyclements what is you suggestion on how to proceed ?

2022-04-25 07:21 UTC, closed without merging