Partially Fixes issue #6903 ( Prepare>Data Reshape>Random Subset )
africanmathsinitiative/R-Instat pull request #7133
Opened 2022-01-18 07:53 UTC by EstherNjeriLiberatta

2022-01-18 11:30 UTC, lloyddewit commented
@Ivanluv Please could you review? thanks

2022-01-18 11:52 UTC, Ivanluv submitted a review, later dismissed

2022-01-18 19:35 UTC, lloyddewit requested changes
@EstherNjeriLiberatta Looks good, just one small comment

2022-01-18 19:35 UTC, lloyddewit commented on instat/dlgRandomSubsets.vb
> +    Private clsDataFrameFunction, clsSampleNFunctionDataframeFunction, clsSetSeed, clsSampleFunction, clsRerunFunction As New RFunction
Thanks for naming these `...Function`, this helps readability. 
Should we also rename `clsSetSeed` to `clsSetSeedFunction` for consistency?

2022-01-19 07:43 UTC, EstherNjeriLiberatta commented
@lloyddewit I have made the requested changes. Thanks

2022-01-19 10:35 UTC, lloyddewit approved these changes

2022-01-19 10:35 UTC, lloyddewit commented
@rdstern please could you test? thanks

2022-01-20 16:29 UTC, rdstern commented
![image](https://user-images.githubusercontent.com/11226469/150380119-3d58c537-5373-4f0d-ad8f-72891636ab02.png)

a) Please check the code.  You can see I don't get 10 columns here, just 2.  Ask @HawardKetoyoMsatsi or others if you need help.
b) I used the checkbox to set the seed.  When I return to the dialogue, it is unchecked.  It should remember it was checked before.  The other controls do all seem to remember.

2022-01-21 22:15 UTC, rdstern requested changes
Comments given for changes needed

2022-01-25 13:11 UTC, EstherNjeriLiberatta commented
@rdstern I have fixed the changes you requested. Kindly review.

@africanmathsinitiative/developers This is ready for review.

2022-01-25 13:36 UTC, rdstern submitted a review, later dismissed
@EstherNjeriLiberatta great.  This now seems to work fine.

2022-01-25 16:23 UTC, shadrackkibet requested changes
@EstherNjeriLiberatta well done. This is good progress.

I have reviewed your PR by adding in comments and suggestions where possible. I hope these comments are useful to improve the code. Let me know if something isn't clear enough. I am happy to write more here to explain if you feel something isn't clear or even follow up elsewhere.

2022-01-25 16:23 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
>      End Sub
This should change. We should run this when set seed checkbox state changes i.e ....controlValue changed event. Then we should do this as before codes. So something like this.
```
    Private Sub ucrChkSetSeed_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrChkSetSeed.ControlValueChanged
        If ucrChkSetSeed.Checked Then
            ucrBase.clsRsyntax.AddToBeforeCodes()
        Else
            ucrBase.clsRsyntax.RemoveFromBeforeCodes()
        End If
    End Sub
```

Remember to clear codes in setdefault.

2022-01-25 16:23 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        clsSampleNFunctionDataframeFunction.SetRCommand("data.frame")
Remove this function because we can force `get_columns_from_data()` to extract a single column as a dataframe by doing
`ucrReceiverSubsets.bForceAsDataFrame = True` on initialise.

2022-01-26 15:30 UTC, EstherNjeriLiberatta commented
@africanmathsinitiative/developers This is ready for review.

2022-01-26 16:48 UTC, shadrackkibet requested changes

2022-01-26 16:48 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +            frmMain.clsRLink.RunScript(clsSetSeedFunction.ToScript(), strComment:="dlgRandomSubset: Setting the seed for random number generator")
Do you still need this? I see it already in line 180.

2022-01-27 09:49 UTC, EstherNjeriLiberatta commented
@shadrackkibet Thank you for the corrections. 
@africanmathsinitiative/developers This is ready for review.

2022-01-27 10:09 UTC, rdstern submitted a review, later dismissed
Still works ok for me

2022-01-28 05:43 UTC, shadrackkibet requested changes

2022-01-28 05:43 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        clsRerunFunction.AddParameter("expr", clsRFunctionParameter:=clsSampleFunction)
With parameter names, the position doesn't matter. For consistency, always add parameter positions. Check other places as well.

2022-01-28 05:43 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
>      End Sub
I like to make this the last `sub`

2022-01-28 05:43 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
Since you now have this. Should just remove `clsSampleNFunctionDataframeFunction`

2022-01-28 07:19 UTC, EstherNjeriLiberatta commented on instat/dlgRandomSubsets.vb
> +        clsRerunFunction.AddParameter("expr", clsRFunctionParameter:=clsSampleFunction)
Alright, thanks.

2022-01-28 07:19 UTC, EstherNjeriLiberatta commented on instat/dlgRandomSubsets.vb
>      End Sub
Okay

2022-01-28 07:19 UTC, EstherNjeriLiberatta commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
I need that function to convert the variable in the sample_n function into a data frame that is;
`sample_n (data.frame(<variable>), size=...)`. It didn't work when I removed it.

I also decided to keep `bIncludeArgumentName:= False` in line 40 as it is because I did not want `x`  to appear within the function e.g. `sample_n (data.frame(x=field), size=...)`. I would like the R code to look simple. Thanks.

2022-01-28 09:23 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
You mention that " It didn't work when I removed it". What exactly do you mean? Did it give an error? If yes which error message? Did you get an exception etc... 

Just saying that things didn't work doesn't help me to help you.

2022-01-28 09:48 UTC, EstherNjeriLiberatta commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
Okay, sorry. I guess I can show you what the R code looks like. I didn't know how best to explain it.
The function is on the second highlight. Thanks for helping.

![image](https://user-images.githubusercontent.com/74548350/151523187-a53e04f7-f8dd-4d2d-84e6-3c5514d24ade.png)

2022-01-28 09:59 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
Does this work for you?
```

# Code generated by the dialog, Random Subsets

field <- data_book$get_columns_from_data(data_name="survey", col_names="field", force_as_data_frame=TRUE)
survey_random <- data.frame(X=purrr::rerun(.n=1, expr=dplyr::sample_n(tbl=field, size=36)))
data_book$import_data(data_tables=list(survey_random=survey_random))

rm(list=c("survey_random", "field"))
```

2022-01-28 10:09 UTC, EstherNjeriLiberatta commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
No, the field variable has to be converted into a data frame in the function `sample_n()`

2022-01-28 10:10 UTC, EstherNjeriLiberatta commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
It should be `sample_n(tbl=data.frame(<variable>),...`

2022-01-28 10:22 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
Isn't it already a data frame when you do this? `field <- data_book$get_columns_from_data(data_name="survey", col_names="field", force_as_data_frame=TRUE)`

2022-01-28 11:56 UTC, EstherNjeriLiberatta commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
I get this error when I try that. 
```
field <- data_book$get_columns_from_data(data_name="survey", col_names="field", col_names="field", force_as_data_frame=TRUE)
survey_random2 <-data.frame(X=purrr::rerun(.n=4, expr=dplyr::sample_n(tbl=field, size=36)))
data_book$import_data(data_tables=list(survey_random2=survey_random2))
```

![image](https://user-images.githubusercontent.com/74548350/151542251-4d1b2e6c-d8e6-4ccb-aad7-769a75540d88.png)

2022-01-28 13:49 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
That is because you have `col_names` twice in this line; 

`data_book$get_columns_from_data(data_name="survey", col_names="field", col_names="field", force_as_data_frame=TRUE)`

2022-01-28 16:54 UTC, EstherNjeriLiberatta commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
May I contact you on skype, if you don't mind

2022-01-28 17:12 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
Sure

2022-01-31 07:49 UTC, shadrackkibet commented on instat/dlgRandomSubsets.vb
> +        ucrReceiverSubsets.bForceAsDataFrame = True
Resolved over skype.

2022-01-31 09:12 UTC, EstherNjeriLiberatta commented
I made corrections to the code:
i. Removed `clsSampleNDataFrameFunction` as it was repeating what `ucrReceiverSubsets.bForceAsDataFrame = True` was doing i.e. converting the varibles into a data frame.
ii. Added parameter positions to all parameters for consistency.

@shadrackkibet Thank you.
@africanmathsinitiative/developers This is ready for review.

2022-01-31 09:28 UTC, shadrackkibet commented
@rdstern could you test and re-approve? In theory, there shouldn't be any functionality change since your last approval.

@EstherNjeriLiberatta just to let you know that I made a small edit in the `clsRSyntax.vb` file.

![image](https://user-images.githubusercontent.com/26301973/151768983-8a7833c3-6d03-46bd-b7b9-7eb56b59f1db.png)

2022-01-31 10:03 UTC, rdstern approved these changes
Well done.  Seems fine to me

2022-01-31 10:39 UTC, shadrackkibet approved these changes

2022-01-31 10:40 UTC, merged