Sorted out efficiency and correctly labelling of quarter abbreviations in the use date dialog
africanmathsinitiative/R-Instat pull request #7137
Opened 2022-01-18 17:58 UTC by shadrackkibet

This PR branches from #7030 hence fixes #7027.

@N-thony here are the R code changes needed for this to work properly.  I have sorted out the following issues.

-  Moved the function `get_quarter_label()`  into the list of stand-alone functions. This is because this function doesn't depend on objects in the `DataSheet`.
- Ensured that levels are in the right order by explicitly specifying levels `factor(x = qtr, levels = unique(qtr))`.
- Improved efficiency by avoiding the `for` loop.
- Removed repetition.

@dannyparsons please check when you have time.

@africanmathsinitiative/developers this is ready for review.

2022-01-18 18:23 UTC, N-thony commented
> This PR branches from #7030 hence fixes #7027.
> 
> @N-thony here are the R code changes needed for this to work properly. I have sorted out the following issues.
> 
> * Moved the function `get_quarter_label()`  into the list of stand-alone functions. This is because this function doesn't depend on objects in the `DataSheet`.
> * Ensured that levels are in the right order by explicitly specifying levels `factor(x = qtr, levels = unique(qtr))`.
> * Improved efficiency by avoiding the `for` loop.
> * Removed repetition.
> 
> @dannyparsons please check when you have time.
> 
> @africanmathsinitiative/developers this is ready for review.

@shadrackkibet thanks. I also checked on my side, it works fine. :)

2022-01-18 19:50 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    mabb <- substr(month.abb, 1, 1)
Will `substr(month.abb, 1, 1)` just return "J"?
Or did I misunderstand?
Thanks

2022-01-19 08:47 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    mabb <- substr(month.abb, 1, 1)
OK, got it, now I understand
thanks

2022-01-19 09:11 UTC, lloyddewit requested changes

2022-01-19 09:11 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    mabb <- substr(month.abb, 1, 1)
The `mabb` calculated on line 2519 also works when `start_month` is `1`.
Should we remove this `if` statement?

2022-01-19 09:11 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    mabb <- rep(substr(month.abb, 1, 1), times = 2)[start_month:(12 + start_month)]
```suggestion
    mabb <- rep(substr(month.abb, 1, 1), times = 2)[start_month:(11 + start_month)]
```

2022-01-19 09:11 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  qtr <- ifelse(quarter == 1, paste(mabb[1:3], collapse = ""), ifelse(quarter == 2, paste(mabb[4:6], collapse = ""), ifelse(quarter == 3, paste(mabb[7:9], collapse = ""), paste(mabb[10:12], collapse
If we calculate a `start_pos` (e.g. `start_pos <= 1 + ((quarter-1) * 3)`), then we could shorten this line, e.g
```
qtr <- paste(mabb[start_pos:start_pos+2], collapse = "")
```

2022-01-19 10:21 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  if (!all(quarter %in% 1:4)) stop("All values must be in range of 1:4")
Make the messages more consistent and useful?
```suggestion
  if (!start_month %in% 1:12) stop(start_month, " is an invalid start month, must be in range of 1:12")
  if (!all(quarter %in% 1:4)) stop(quarter, " is an invalid quarter, must be in range of 1:4")
```

2022-01-20 11:44 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    mabb <- substr(month.abb, 1, 1)
Absolutely! thanks for the insights on simplification.

2022-01-20 11:47 UTC, shadrackkibet commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  qtr <- ifelse(quarter == 1, paste(mabb[1:3], collapse = ""), ifelse(quarter == 2, paste(mabb[4:6], collapse = ""), ifelse(quarter == 3, paste(mabb[7:9], collapse = ""), paste(mabb[10:12], collapse
Yes, I got the idea. I will simplify it further. Thanks for pointing out this.

2022-01-20 12:05 UTC, shadrackkibet commented
@lloyddewit thanks for the review. Your insights were useful in simplifying the code.

2022-01-20 16:19 UTC, lloyddewit approved these changes
@shadrackkibet Thank you! looks good to me

2022-01-20 16:21 UTC, lloyddewit commented
@shadrackkibet who's the best person for final approval?

2022-01-20 16:37 UTC, rdstern commented
I am happy to approve the changes to the quarter function.  I am a bit concerned about the look of other controls in the dialogue?  Is this something that will be ok in the merged version?
![image](https://user-images.githubusercontent.com/11226469/150381910-6048381a-0ca3-4251-87a3-a4208192d153.png)

2022-01-21 22:44 UTC, rdstern approved these changes
@shadrackkibet I am approving, given @dannyparsons is happy.  I am still concerned at the lack of visible checkboxes in the dialogue and hope that won't be the case in the merged version.

2022-01-21 22:53 UTC, shadrackkibet commented
Great, I am going to merge the `quarter` changes now.

@africanmathsinitiative/developers could someone help with sorting out the visibility of some checkboxes in this dialog? This is something in the current master.

2022-01-21 22:53 UTC, merged