Partially fixes issue # 6782 (Adding Choropleth map dialogue)
africanmathsinitiative/R-Instat pull request #7143
Opened 2022-01-20 10:28 UTC by EstherNjeriLiberatta

Partially fixes issue #6782, In this PR I have made a few adjustments to the heatmap dialogue and added a choropleth map option as another button. 
To test the choropleth map use the data set below. 
[mydata.csv](https://github.com/africanmathsinitiative/R-Instat/files/7904311/mydata.csv)

@rdstern @africanmathsinitiative/developers This is ready for review.

2022-01-20 16:29 UTC, lloyddewit commented
@N-thony Please could you review? thanks

2022-01-21 07:34 UTC, N-thony requested changes

2022-01-21 07:34 UTC, N-thony commented on instat/dlgHeatMapPlot.vb
> +        clsReorderFunction.SetRCommand("reorder")
Why did the same functions call two times?

2022-01-21 07:34 UTC, N-thony commented on instat/dlgHeatMapPlot.vb
> +        clsLabelAesFuction = New RFunction
clsLabelAesFunction?

2022-01-21 07:34 UTC, N-thony commented on instat/dlgHeatMapPlot.vb
>      End Sub
Move this after line 684 with one line space

2022-01-21 07:34 UTC, N-thony commented on instat/dlgHeatMapPlot.vb
> +        ucrNudShapeHeatMap.Visible = False
I think this is done already in MakeNudVisible()?

2022-01-21 07:34 UTC, N-thony commented on instat/dlgHeatMapPlot.vb
> +        ucrPnlOptions.AddToLinkedControls({ucrChkAddLabels, ucrChkColourPalette}, {rdoHeatMap, rdoChoroplethMap})
Do you need this line 102?

2022-02-16 14:10 UTC, EstherNjeriLiberatta commented
Thankyou @N-thony , I've made some of the changes you requested, kindly review. Thanks

2022-02-17 06:53 UTC, N-thony commented
> Thankyou @N-thony , I've made some of the changes you requested, kindly review. Thanks

@EstherNjeriLiberatta, we can have a quick call on this when you have time.

2022-03-28 07:43 UTC, shadrackkibet commented
@HawardKetoyoMsatsi happy to take over?

2022-03-28 08:43 UTC, HawardKetoyoMsatsi commented
@shadrackkibet yes I will fix this.

2022-03-28 09:46 UTC, EstherNjeriLiberatta commented
@HawardKetoyoMsatsi Thank you for helping out on this, I'll work with you to know how you fix the problem I was having.

2022-04-13 07:58 UTC, HawardKetoyoMsatsi commented
@EstherNjeriLiberatta I have managed to fix this error in R. Since you had already written the vb code once you have time we can add the R-code I wrote into your vb code together.

2022-04-13 09:14 UTC, EstherNjeriLiberatta commented
Thank you, @HawardKetoyoMsatsi Getting to you on skype.

2022-04-25 05:57 UTC, HawardKetoyoMsatsi commented
@EstherNjeriLiberatta How far with this task, Have you been able to add the R code I gave you in R-Instat.

2022-05-17 13:46 UTC, EstherNjeriLiberatta commented
Hello @lilyclements when running the code below I get the following error. What could the problem be in the code?

```
# Code generated by the dialog, Heat Map

mydata1 <- data_book$get_data_frame(data_name="mydata1")
cnames <- aggregate(cbind(x=long, y=lat) ~ murder, data=mydata1, FUN=function(x)  mean(range(x)))
last_graph <- ggplot2::ggplot(data=mydata1, mapping=ggplot2::aes(x=long, y=lat, fill=murder)) + ggplot2::geom_polygon(mapping=ggplot2::aes(group=group)) + ggplot2::geom_point(data=cnames, mapping=ggplot2::aes(size=murder, x=long, y=lat)) + theme_grey()
data_book$add_graph(graph_name="last_graph", graph=last_graph, data_name="mydata1")
data_book$get_graphs(data_name="mydata1", graph_name="last_graph")
rm(list=c("last_graph", "mydata1", "cnames"))
```
![image](https://user-images.githubusercontent.com/74548350/168825083-263a1945-cc94-48d0-902e-6861bdd92bfe.png)

2022-05-17 13:52 UTC, lilyclements commented
@EstherNjeriLiberatta the error says "object 'long' not found".

You use "long" in the `cbind` function, and do not call it from the data frame. Can you show me all of the R output for this code? I am just wondering if you run `long <- data_book$get_variables_from_data(...)` or whichever the function is!

2022-05-17 14:07 UTC, lilyclements commented
Great, so you want to call `long <- data_book$get_columns_from_data(...)`. To do this, you just have to run in the dialog code `ucrSelectorLong.SetParameterIsRFunction`, and similarly for the latitude selector.

2022-05-17 14:16 UTC, EstherNjeriLiberatta commented
Okay, thank you so much

2022-05-19 10:13 UTC, EstherNjeriLiberatta commented
@lilyclements @rdstern  This is ready for your review. I used the [Alabama.csv](https://github.com/africanmathsinitiative/R-Instat/files/8728012/Alabama.csv) dataset. This was a relatively easy dataset to use, it was difficult finding a good one. The `Group/ID` receiver is attaching the regions to their specific longitude and latitude. In case you have a dataset that does not have a numerical value for the regions you would have to duplicate the region/village/sublocation column of the areas and convert them to numeric. Then rename that column as `group`  and you can safely use it in the ` Group/ID` receiver. Maybe we could find an alternative way to do this with your help Lily. 
The `Fill `and `Points(Optional)` receivers should have similar variables preferably numeric, categorical data didn't seem to work well. 
The Heatmap also has some additions that's the reorder options and swapping the x and y axis.

![Heatmap  filled](https://user-images.githubusercontent.com/74548350/169267722-b015978d-e7dc-405c-8625-52b98a952c55.jpg)
The output you have now a opposed to before using the points is as in the image below:
![image](https://user-images.githubusercontent.com/74548350/169268643-ccbbe850-d534-4297-a2db-b2d187136ded.png)

With the labels you get : 

![image](https://user-images.githubusercontent.com/74548350/169269019-0e3c0945-1f37-4040-827a-e3ff77f8e154.png)

2022-05-23 11:59 UTC, lilyclements reviewed
This is looking great! Nice one. A few small bugs:

1. You get an error that `long` is not found when the `Points (Optional)` receiver is filled. The R code is:

```
Alabama <- data_book$get_data_frame(data_name="Alabama")
cnames <- aggregate(cbind(x=long, y=lat) ~ region, data=Alabama, FUN=function(x)  mean(range(x)))
last_graph <- ggplot2::ggplot(data=Alabama, mapping=ggplot2::aes(x=long, y=lat, fill=region)) +
  ggplot2::geom_polygon(mapping=ggplot2::aes(group=region)) +
  ggplot2::geom_point(data=cnames, mapping=ggplot2::aes(size=long, x=x, y=y)) +
  theme_grey()
```

If you look at `cnames`, you'll see it is a data frame with three variables `region`, `x`, and `y`.
However, you run the line
`...+ geom_point(data=cnames, mapping=ggplot2::aes(size=long, x=x, y=y)) + ... `,
that is, the R code calls a data frame `cnames`, and then looks for the `long` variable in it.
Presumably, in the `aggregate` function you rename `long` to be `x`, so you just want to run:
`...+ geom_point(data=cnames, mapping=ggplot2::aes(size=x, x=x, y=y)) + ... `,
(that is, replace "long" with "x" for the `geom_point`).


2. If I set the "fill" receiver to be a factor, I get an error. The error message says that "round not meaningful for factors".
So, here the issue is in the R code what you run 
`... + geom_text(..., label = round(x = region, digits = 2)), ...) + ...`
We only want to run `round(x = <fill variable>, digits = 2))` if the fill variable is numeric. Otherwise, we can just run 
`... + geom_text(..., label = <fill variable>, ...) + ...`

3. Out of interest, the "Size" variable has a input drop down for it. Why aren't we using a nud? 

4. Just check the TestOK again - at the moment I can press okay after checking "Add labels", but not having a value in the colour input box.

Overall it looks really good! Nice one.

2022-05-24 07:28 UTC, EstherNjeriLiberatta commented
@lilyclements Thank you for your review. Could we have a skype call to explain some of the issues above?

2022-06-07 07:39 UTC, N-thony commented
> @rdstern @lilyclements This is ready for review. The choropleth map is now using` tidyverse` as opposed to `aggregate()`. Thankyou.

@rdstern @lilyclements could you review? Thanks.

2022-06-07 11:13 UTC, rdstern commented
It seems to be getting there.
a) In the labels I found, if you have the points and use Middle, then they overtype.  Can you change out to Up, and make it -1 rather than -0.25.  And Down could be 1 rather than 5?
b) The main problems comes when you use the Plot options or Polygon Options.  If you press on Polygon Options and then Return, it gives an error, while Plot options and return now omits the y in the polygon.
c) Make the title of the dialogue Heat/Choropleth

2022-06-14 09:36 UTC, N-thony commented
> It seems to be getting there. a) In the labels I found, if you have the points and use Middle, then they overtype. Can you change out to Up, and make it -1 rather than -0.25. And Down could be 1 rather than 5? b) The main problems comes when you use the Plot options or Polygon Options. If you press on Polygon Options and then Return, it gives an error, while Plot options and return now omits the y in the polygon. c) Make the title of the dialogue Heat/Choropleth

@EstherNjeriLiberatta please, can you make these changes?

2022-06-15 10:54 UTC, EstherNjeriLiberatta commented
@rdstern I've made the changes you requested.
@africanmathsinitiative/developers This is ready for review.

2022-06-15 18:19 UTC, lloyddewit commented
@N-thony @lilyclements Thank you for your reviews and testing. Are you happy that all your comments are resolved? If so, please could you approve and set any still open comments to 'resolved'.
Thanks

2022-06-16 09:46 UTC, lilyclements reviewed
@EstherNjeriLiberatta this is really good, made for a difficult game of "find a bug", but I eventually got one! Just a very minor comment to resolve. It's looking great! Nice one!

2022-06-16 09:46 UTC, lilyclements commented on instat/dlgHeatMapPlot.vb
> +    Private Sub AllControlsContentsChanged() Handles ucrInputColour.ControlContentsChanged, ucrReceiverX.ControlContentsChanged, ucrSaveGraph.ControlContentsChanged, ucrVariableAsFactorForHeatMap.Con
You also want the labels checkbox in here - otherwise at the moment:
I make the colour input empty
OK is disabled
I uncheck the checkbox that makes the colour input visible
OK is still disabled

2022-06-16 09:49 UTC, lilyclements submitted a review, later dismissed

2022-06-16 10:10 UTC, N-thony submitted a review, later dismissed

2022-07-09 10:42 UTC, rdstern approved these changes

2022-07-10 09:14 UTC, lloyddewit requested changes
@EstherNjeriLiberatta Thank you, this looks good, my suggestions are mainly about simplifying the code and readability. There are also two open comments from @N-thony , please could you resolve these also?
Thanks!

2022-07-10 09:14 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +            If ucrChkPoints.Checked Then
```suggestion
        If rdoChoroplethMap.Checked AndAlso ucrChkPoints.Checked Then
```

2022-07-10 09:14 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +        End If
simplify to single line?

2022-07-18 13:23 UTC, EstherNjeriLiberatta commented on instat/dlgHeatMapPlot.vb
> +        End If
Done

2022-07-18 13:24 UTC, EstherNjeriLiberatta commented on instat/dlgHeatMapPlot.vb
> +    Private Sub MakeVisible()
Resolved

2022-07-18 13:25 UTC, EstherNjeriLiberatta commented
@N-thony @africanmathsinitiative/developers This is ready for review.

2022-07-19 07:46 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +
```suggestion
```

2022-07-19 07:46 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +        clsReorderFunction.SetRCommand("reorder")
Duplicate lines. Should we just remove the duplicates? Or should we call `SetPackageNamee()` before the `SetRCommand()` call?
(On 21 Jan, @N-thony had the same comment but it was marked 'outdated' before it was resolved. I have now set @N-thony 's comment to resolved so that it is not duplicated.)

2022-07-19 07:46 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +        End If
Are you willing to resolve? Or do you have a different preference?

2022-07-19 07:46 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +        End If
Are you willing to resolve? Or do you have a different preference?

2022-07-19 09:41 UTC, lloyddewit requested changes
@EstherNjeriLiberatta Thank you for the changes. 
Please could you also look at the 2 unresolved comments from 10 July (see unresolved comments above)
Thanks

2022-07-19 09:41 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +        clsDummyFunction.AddParameter("choropleth_geom_point", If(ucrChkPoints.Checked, True, False), iPosition:=0)
```suggestion
        clsDummyFunction.AddParameter("choropleth_geom_point", ucrChkPoints.Checked, iPosition:=0)
```

2022-07-19 14:05 UTC, EstherNjeriLiberatta commented
@lloyddewit I hope I have resolved all the requested changes from you and @N-thony, thank you so much.
This is ready for review.

2022-07-21 07:08 UTC, lloyddewit requested changes
@EstherNjeriLiberatta This looking really good, you've made some good quality improvements since the first commits.

I think we're very nearly ready to merge, just a couple of final questions.
Thank you for your patience

2022-07-25 09:08 UTC, EstherNjeriLiberatta commented
@lloyddewit Thank you, I have made the changes.

2022-07-26 06:31 UTC, lloyddewit approved these changes

2022-07-26 06:33 UTC, lloyddewit commented
@rdstern There are significant changes since your last approval. If you can test/approve again, then we can merge, thanks

2022-07-30 11:49 UTC, rdstern approved these changes

2022-07-31 10:27 UTC, merged