Issue 7151 small fix needed in edit script dialogue
africanmathsinitiative/R-Instat pull request #7168
Opened 2022-01-26 09:07 UTC by HawardKetoyoMsatsi

Fixes #7151
@rdstern, @africanmathsinitiative/developers this is ready for review.

2022-01-26 09:52 UTC, rdstern commented
@HawardKetoyoMsatsi it still seems the same as before:
![image](https://user-images.githubusercontent.com/11226469/151140885-c8f9e358-2545-49f4-ae91-13ef8bf84e3c.png)


When I press Ok it puts the commands in the output window, but not the result.
When I press To Script it puts the code into the script window.  Running from there gives the result.

2022-01-26 12:25 UTC, HawardKetoyoMsatsi commented
@rdstern I suppose you may not have pulled my changes correctly. 
The code produces correct results from my end.
Below is the output I get.

![image](https://user-images.githubusercontent.com/16137042/151162520-f9e63b51-2891-45d0-8cc2-47c4ad685706.png)

2022-01-26 16:39 UTC, rdstern approved these changes
Great - yes it does work!

2022-01-27 08:53 UTC, lloyddewit requested changes

2022-01-27 08:53 UTC, lloyddewit commented on instat/dlgScript.vb
> +        Return If(strText <> "", frmMain.clsRLink.RunScriptFromWindow(strNewScript:=strText, strNewComment:=strComment), "")
safer to use IsNullOrEmpty?
```suggestion
        Return If(String.IsNullOrEmpty(strText), "", frmMain.clsRLink.RunScriptFromWindow(strNewScript:=strText, strNewComment:=strComment))
```

2022-01-27 08:53 UTC, lloyddewit commented on instat/dlgScript.vb
> +        RunText(txtScript.Text)
What is the purpose of using a private function? could we delete the function and copy the code here?
We ignore the returned value, is that correct?

2022-01-27 14:49 UTC, HawardKetoyoMsatsi commented
@lloyddewit  I have made the requested changes. Please take a look.

2022-01-27 19:21 UTC, lloyddewit approved these changes

2022-01-27 19:25 UTC, lloyddewit commented on instat/dlgScript.vb
> +        RunText(txtScript.Text)
@HawardKetoyoMsatsi `clsRLink.RunScriptFromWindow()' returns any part of the script that was not executed. It should be rare that part of the script is not executed and I'm not sure it's worth showing a warning dialog for this. I saw that you decided to ignore this returned value. I think that's reasonable.

2022-01-27 19:27 UTC, lloyddewit commented
@rdstern Since your last approval, the code was simplified. The functionality should (in theory!) be the same. Please could you test/approve again?
Should we merge this PR for 0.7.4 or should we wait?

2022-01-27 22:32 UTC, rdstern approved these changes
Still seems fine

2022-01-28 08:47 UTC, lloyddewit commented
@rdstern This is a small, low risk change. So I went ahead and merged.

2022-01-28 08:47 UTC, merged