Added distributions to show model, random samples and general dialogs
africanmathsinitiative/R-Instat pull request #7175
Opened 2022-01-27 13:15 UTC by Vitalis95

Partially fixes #7125
@rdstern @shadrackkibet @lloyddewit  I have added Hypergeometric distribution and non-centrality parameter to chi-square and t distributions.
However, adding the remaining distributions has been a challenge. It is a bit complicated implementing the functions because it affects the 3 dialogs.  Please I need your help on this.
Thanks

2022-01-27 19:13 UTC, lloyddewit commented
@Vitalis95 Thank you for tackling this issue.
In your comment, I changed 'Partially fixes #7125' to 'Fixes (partially) #7125'. Otherwise, the issue willl be closed automatically when this PR merges.
You requested help. Do you need help:
- understanding the text in the issue?
- or what the dialogs should look like?
- or how to code the dialog changes?

thanks for clarifying

2022-01-28 05:42 UTC, Vitalis95 commented
@lloyddewit thanks for that change.
The help I need is how to code the dialog changes. Thanks

2022-01-28 08:41 UTC, lloyddewit commented
@Vitalis95 Thank you for the clarification. @Ivanluv has good experience coding dialog boxes, maybe you could ask him initially for advice?

2022-02-01 12:22 UTC, Vitalis95 commented
@rdstern @shadrackkibet @dannyparsons 
The multinomial distribution works well in random sample dialog however, in show model dialog I get the following errors,
For quantiles;
![qmultinom](https://user-images.githubusercontent.com/89011415/151964486-6e13b214-2ea9-4dab-bd41-d34f2311aa69.jpg)

For probabilities;
![pmult](https://user-images.githubusercontent.com/89011415/151964985-28bb4fb5-552c-49ad-a2e1-4d1bf6f3165a.jpg)

The multinomial distribution from stats package has the following functions;
rmultinom(n, size, prob)
dmultinom(x, size = NULL, prob, log = FALSE)

qmultinom and pmultinom which brings the error are not there. 
Thanks.

2022-02-01 13:06 UTC, Vitalis95 commented
@rdstern @shadrackkibet 
I have added multinomial distribution, it works well in random sample dialog. However, in show model dialog , I'm getting an error and I have shared above. Thanks

2022-02-01 13:42 UTC, rdstern commented
@Vitalis95 I have had a look and am impressed that you got this working for the random samples even!  I failed and so looked on [stackoverflow here](https://stackoverflow.com/questions/59160552/random-number-generation-from-multinomial-distribution-in-r-using-rmultinom-fu).  

The answer there indicated that what I think is useful is sort of the multiple equivalent of bernoulli, rather than real multinomial.  - which gives vectors.  There it indicates that we could use sample instead.

Then I checked with bernoulli and found it gives an error in the probability distributions dialogue, that we need to fix.  That's because it uses the binomial function, without saying it is for one trial.

I wondered whether - instead - there is a bernoulli function.  So, I now suggest as follows for both problems.

a) Add the mc2d package
b) Swap the bernoulli method (using binom) by the bern function from this package
c) Use the empiricalD function for the (sort of) multinomial sampling.  For example rempiricalD(43,1:5, prob=c(10, 10, 10, 0, 10))

I suggest that the user has to give the prob values as here, - single control and commas between.  At least 2 values I guess but perhaps 1 would work!  It would be trivial.  Then provide the values - 1 to however many probabilities.

I wonder what we should call it - perhaps multiple?

Then, if this works and you still feel like more, the triangular distribution is also in the same package and could be easy to add?

2022-02-04 09:20 UTC, Vitalis95 commented
@rdstern @shadrackkibet , I have added discrete empirical distribution and triangular distribution from mc2d package.
For the bernoulli distribution, I had discussions with @shadrackkibet and he suggested I  retain the binom function but I add size=1 (the number of trials).

2022-02-04 10:30 UTC, shadrackkibet commented
@Vitalis95 I made the following additions;

- Loaded the package so that distribution work on Show Model.
- Added `mc2d` package as a new package to be installed in the next release.

Pull changes and test if it works from your end.

2022-02-04 12:12 UTC, Vitalis95 commented
@shadrackkibet , I have pulled and tested. It works

2022-02-04 16:00 UTC, rdstern requested changes
Looks good.  One trivial point that was there before.  could bernoulli please be spelled with the extra l.
Then I am concerned about the freedom in the typing in the empirical distribution.  I tried a negative value in the probabilities and it gave a sensible error message.  So that's ok.
But I wonder about the freedom in choosing the discrete values.  I tried 1,2,3,4,5 and it didn't like that.  I tried 1:10 when there were still only 5 probabilities and it was not happy.  
My suggestion is to be more restrictive.  Make the values obviously non-editable and always 1:x.  If I change the probabilities then it changes the second value?  So 1,1,1 would change the values into 1:3.  So you can easily do 3 point, 5, point, 7 point etc, and it always gives probabilities of the integers 1 upwards.

2022-02-09 13:01 UTC, Vitalis95 commented
@rdstern , @shadrackkibet  I have changed the values in discrete empirical  to be non-editable and also when changing the probabilities then it changes the second value automatically.
For the birthday distribution, I was getting an error while generating quantiles and probabilities in R, I asked the mosaic people how to use birthday distribution from stats package in mosaic package, and they said the names of the functions are not really part of a standard suite of d-, p-, and q-functions for a family of distributions.
Here is the respond; have a look at it.
https://github.com/ProjectMOSAIC/mosaic/issues/792

Thanks.

2022-02-15 14:20 UTC, Vitalis95 commented
@rdstern  I have added arima.sim to Random sample dialog to Simulate from an ARIMA model. It has AR parameter.
I will be adding a checkbox that Plots several time series . For time being, have a look at this.

2022-02-16 11:23 UTC, rdstern requested changes
@Vitalis95 that was a good try on the arima.  But I have realised it is much more complicated than that.  It will probably become a button at the top, so there will be Independent and ARIMA.  But that can wait until we have more on time series.
So aplogies, but let's not have the ARIMA checkbox for now.
The empirical looks much better now.
Could you add a tooltip when there is that option, saying Input relative values separated by commas, For example 3,2,1.
In the field, don't make the user type the c( ).  Instead you add that in the code.
Then let's merge!

2022-02-16 13:33 UTC, Vitalis95 commented
@rdstern  I have added the tooltip and also c() in the code.
Have a look at it.

2022-03-01 11:15 UTC, rdstern approved these changes
Looks good

2022-03-02 08:16 UTC, lloyddewit commented on instat/ucrDistributions.vb
> +    Private intNumber As Integer
remove?

2022-03-02 08:33 UTC, lloyddewit commented on instat/ucrDistributionsWithParameters.vb
> +                ttEmpirical.SetToolTip(ucrInputParameter2.txtInput, "Input relative values separated by commas, For example 3,2,1.")
This tool tip is set every time `ucrInputParameter2` changes.
Should we just set the tool tip once somewhere else?

2022-03-02 12:34 UTC, Vitalis95 commented
@lloyddewit have a look at it,
thanks

2022-03-02 13:10 UTC, rdstern approved these changes

2022-03-02 13:50 UTC, shadrackkibet approved these changes

2022-03-03 09:25 UTC, lloyddewit approved these changes

2022-03-03 09:27 UTC, merged