Added Up arrow button on Import Dataset Dialogue
africanmathsinitiative/R-Instat pull request #7184
Opened 2022-02-01 05:33 UTC by N-thony

This PR will replace 7177 due to build errors.
Still fixing some bugs.

2022-02-16 12:12 UTC, rdstern submitted a review, later dismissed
Looks fine still

2022-02-16 19:06 UTC, lloyddewit commented
@N-thony is this ready for review now or do you still plan changes? thanks

2022-02-17 06:51 UTC, N-thony commented
> @N-thony is this ready for review now or do you still plan changes? thanks

yes @lloyddewit, we can also have a quick on that if it is okay with you.

2022-02-28 09:44 UTC, rdstern commented
@lloyddewit is this now ok to merge?

2022-02-28 14:08 UTC, lloyddewit requested changes
@N-thony thanks, just one question

2022-02-28 14:08 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +            SetDialogStateFromFile(Strings.Left(strCurrentDirectory, InStrRev(strCurrentDirectory, "\") - 1), strFileExtension)
if the separator is '/', then will this fail?

2022-02-28 15:00 UTC, N-thony commented on instat/dlgImportDataset.vb
> +            SetDialogStateFromFile(Strings.Left(strCurrentDirectory, InStrRev(strCurrentDirectory, "\") - 1), strFileExtension)
In this case, yes, I have added the check of the correct separator in the path. Thanks.

2022-03-02 08:01 UTC, lloyddewit requested changes
@N-thony Thanks for resolving the last comments, I just spotted something else

2022-03-02 08:01 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +        If GetCorrectSeparatorInPath() <> "" Then
`GetCorrectSeparatorInPath` always returns `/` or '\`, therefore this `If` condition will always be true and the `Else` will never be reached.

2022-03-02 08:08 UTC, N-thony commented on instat/dlgImportDataset.vb
> +        If GetCorrectSeparatorInPath() <> "" Then
You are right, I just resolved this. Thanks.

2022-03-02 09:14 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +        If GetCorrectSeparatorInPath() <> "" Then
I think we still need to check if `strCurrentDirectory` contains at least one separator.
If not, then the line below may give strange results.
```
        SetDialogStateFromFile(Strings.Left(strCurrentDirectory, InStrRev(strCurrentDirectory, GetCorrectSeparatorInPath()) - 1), strFileExtension)
```
I suggest that you put the `If/Else` statements back, and change the `If` condition so that it checks that there is at least one separator.
Does this make sense?

2022-03-02 09:36 UTC, N-thony commented
@lloyddewit I made the change as requested. Please take a look. Thanks.

2022-03-02 10:49 UTC, lloyddewit requested changes

2022-03-02 10:49 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +        Return strSepearator
```suggestion
        Dim strSeparator As String = ""
        If strCurrentDirectory.Contains("/") Then
            strSeparator = "/"
        ElseIf strCurrentDirectory.Contains("\") Then
            strSeparator = "\"
        End If
        Return strSeparator
```

2022-03-02 10:51 UTC, lloyddewit commented
@rdstern Just a couple of small changes since you last approved, please could you test again? thanks

2022-03-08 11:59 UTC, N-thony commented
> @rdstern Just a couple of small changes since you last approved, please could you test again? thanks

@rdstern how about this?

2022-03-08 13:42 UTC, rdstern approved these changes
still fine to me!

2022-03-09 07:51 UTC, merged