Implements the delete key for Reogrids
africanmathsinitiative/R-Instat pull request #7186
Opened 2022-02-02 07:01 UTC by derekagorhom

fixes issue #7149 
@africanmathsinitiative/developers this is ready for review. 

@rdstern @shadrackkibet @N-thony 

I have implemented the Delete key for the Reogrid and it replaces the data with NA.

2022-02-02 08:21 UTC, rdstern commented
@derekagorhom I have tried and still get the old message.

Then I get the following error:
![image](https://user-images.githubusercontent.com/11226469/152116456-4c614ef7-24a6-4226-9889-9ee25b887736.png)

I can't use the delete key to delete anything.

I would like you to start the trend for everyone of saying more of what you have been able to do.  So what data did you use, and what did you delete that worked.  Then I can start by trying to repeat that.

I used these data below and imported just the first sheet:

[Copy of R GUI Comparison Table.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7984634/Copy.of.R.GUI.Comparison.Table.xlsx)

I tried deleting a single cell in the Blue Sky variable.  Got an error.
I marked a block - just within this same column.  Same error.
I made the first variable into a factor and tried to delete a single cell - same error.
I then tried deleting a single cell in the second variable, which is still a character variable.  - same error.

This is the sort of thing that I would like you to offer when it works.  I will then try deleting a rectangle of multiple variables, etc.  No point here, because nothing works.  

So, either I am using the wrong version mine is #7186 .  Or it isn't really ready yet.

And please also change the message.  There will be an undo.  So the second line can be deleted.

2022-02-02 09:42 UTC, N-thony commented
> @derekagorhom I have tried and still get the old message.
> 
> Then I get the following error: ![image](https://user-images.githubusercontent.com/11226469/152116456-4c614ef7-24a6-4226-9889-9ee25b887736.png)
> 
> I can't use the delete key to delete anything.
> 
> I would like you to start the trend for everyone of saying more of what you have been able to do. So what data did you use, and what did you delete that worked. Then I can start by trying to repeat that.
> 
> I used these data below and imported just the first sheet:
> 
> [Copy of R GUI Comparison Table.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7984634/Copy.of.R.GUI.Comparison.Table.xlsx)
> 
> I tried deleting a single cell in the Blue Sky variable. Got an error. I marked a block - just within this same column. Same error. I made the first variable into a factor and tried to delete a single cell - same error. I then tried deleting a single cell in the second variable, which is still a character variable. - same error.
> 
> This is the sort of thing that I would like you to offer when it works. I will then try deleting a rectangle of multiple variables, etc. No point here, because nothing works.
> 
> So, either I am using the wrong version mine is #7186 . Or it isn't really ready yet.
> 
> And please also change the message. There will be an undo. So the second line can be deleted.

It seems like the `replace_values_with_NA()` is missing in `data_object_R6.R` and `instat_object_R6.R`

2022-02-02 10:24 UTC, derekagorhom commented
> > @derekagorhom I have tried and still get the old message.
> > Then I get the following error: ![image](https://user-images.githubusercontent.com/11226469/152116456-4c614ef7-24a6-4226-9889-9ee25b887736.png)
> > I can't use the delete key to delete anything.
> > I would like you to start the trend for everyone of saying more of what you have been able to do. So what data did you use, and what did you delete that worked. Then I can start by trying to repeat that.
> > I used these data below and imported just the first sheet:
> > [Copy of R GUI Comparison Table.xlsx](https://github.com/africanmathsinitiative/R-Instat/files/7984634/Copy.of.R.GUI.Comparison.Table.xlsx)
> > I tried deleting a single cell in the Blue Sky variable. Got an error. I marked a block - just within this same column. Same error. I made the first variable into a factor and tried to delete a single cell - same error. I then tried deleting a single cell in the second variable, which is still a character variable. - same error.
> > This is the sort of thing that I would like you to offer when it works. I will then try deleting a rectangle of multiple variables, etc. No point here, because nothing works.
> > So, either I am using the wrong version mine is #7186 . Or it isn't really ready yet.
> > And please also change the message. There will be an undo. So the second line can be deleted.
> 
> It seems like the `replace_values_with_NA()` is missing in `data_object_R6.R` and `instat_object_R6.R`. I have added that and it works fine on y side. @derekagorhom you need to add that back or check if you missed to staged `data_object_R6.R` and `instat_object_R6.R`. ![image](https://user-images.githubusercontent.com/68591383/152129974-5826fd2f-f850-4585-aab9-3e0be524cba7.png)

understood

2022-02-02 11:25 UTC, derekagorhom commented
sorry everyone, my Git just crashed so i am working on cloning a new one. 
i will make changes to the delete message as soon as possible

2022-02-02 11:35 UTC, shadrackkibet commented
@derekagorhom meanwhile I have added the R code back to this PR. You will need to pull the changes when you get things working from your end.

2022-02-02 11:37 UTC, derekagorhom commented
> @derekagorhom meanwhile I have added the R code back to this PR. You will need to pull the changes when you get things working from your end.

i will do that

2022-02-02 11:54 UTC, rdstern submitted a review, later dismissed
@derekagorhom and @shadrackkibet meanwhile I have tested this pull request and it now seems to work fine.  
The message will be wrong (in the future) but I am approving this for now, because that change could always be made later.
I notice the Delete cells is still evident at the top of the right-click.  I still don't think it is important enough for that, but others may disagree.  

This is one useful step in being able to enter (small amounts of) data using R-Instat.

Over to @shadrackkibet or @lloyddewit for a final check.

2022-02-03 08:44 UTC, lloyddewit commented
@derekagorhom This PR was approved by @rdstern . Do you expect to make further changes when your Git is fixed? Or should we start the final reviews now?
Thanks

2022-02-03 09:22 UTC, derekagorhom commented
No please @lloyddewit  you can go ahead and start further reviews

2022-02-03 10:20 UTC, lloyddewit commented
@N-thony Thank you for supporting this PR earlier. Please could you do the first peer review? 
Thanks

2022-02-03 13:38 UTC, N-thony requested changes

2022-02-03 13:38 UTC, N-thony commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +        'End If
You can uncomment this since it is needed in other Reogrid where Delete from key is not yet implemented

2022-02-03 13:38 UTC, N-thony commented on instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
> +    End Function
On line 125 column is defined as DataGridViewRow but I think we need DataGridViewColumn...
But also I'm not sure this will work with the Linux version

2022-02-03 13:38 UTC, N-thony commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +
Remove space

2022-02-03 13:38 UTC, N-thony commented on instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
> +
Remove space

2022-02-04 11:22 UTC, rdstern approved these changes
Still seems to work fine!

2022-02-08 11:02 UTC, lloyddewit requested changes

2022-02-08 11:02 UTC, lloyddewit commented on instat/ucrDataView.vb
> +        Dim deleteCell = MsgBox("This will replace the selected cells with missing values (NA)." & Environment.NewLine & "Continue?", MessageBoxButtons.YesNo, "Delete Cells")
add line break(s) so line doesn't exceed 100 columns?

2022-02-08 12:46 UTC, derekagorhom commented on instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
> +    Public Sub DeleteCells(lstRowNames As List(Of String), lstColumnNames As List(Of String))
thanks for the corrections @lloyddewit 
firstly, the aim of deleting cells is to replace the values that were in those cells with NA. 
secondly, if the 1stRowNmaes parameter is not needed, we can remove it from the function.
thirdly, the delete cell function is supposed to be used to delete particular values in the dataframe that the user would not like to use. 

As the change in for replace_values_with_NA. that was a Pull request shadrack due to the fact that we are replacing the values in the cell not the cell itself

2022-02-14 16:35 UTC, lloyddewit commented on instat/ucrDataView.vb
> +        Dim deleteCell = MsgBox("This will replace the selected cells with missing values (NA)." & Environment.NewLine & "Continue?", MessageBoxButtons.YesNo, "Delete Cells")
@derekagorhom I unresolved this comment because the lines are still too long, this makes the code hard to read. Please could you add line breaks, for example:
```
        If GetSelectedRows.Count = GetCurrentDataFrameFocus()?.iTotalRowCount Then
            MsgBox("Cannot delete all visible Rows." & 
                   Environment.NewLine & "Use Prepare > Data Object > Delete Data Frame if you wish to delete the data.", 
                   MsgBoxStyle.Information, "Cannot Delete All Rows")
        Else
            If GetSelectedColumns.Count = GetCurrentDataFrameFocus()?.iTotalColumnCount Then
                MsgBox("Cannot delete all visible columns." & Environment.NewLine & 
                       "Use Prepare > Data Object > Delete Data Frame if you wish to delete the data.", 
                       MsgBoxStyle.Information, "Cannot Delete All Columns")
            Else
                Dim deleteCell = MsgBox("This will replace the selected cells with missing values (NA)." & 
                                        Environment.NewLine & "Continue?", 
                                        MessageBoxButtons.YesNo, "Delete Cells")
```

2022-02-15 07:59 UTC, derekagorhom commented
@lloyddewit  i have made the changes, please could you check again?

2022-02-15 11:15 UTC, shadrackkibet commented
@derekagorhom from a user perspective, should we have the following message when I select rows to delete? Should't we replace the entire row with NA's?

![image](https://user-images.githubusercontent.com/26301973/154050801-d4949ae3-cd67-4e9f-97c7-da48a99daac9.png)

2022-02-15 11:54 UTC, rdstern commented
@derekagorhom and @shadrackkibet that's a good spot.  I agree that we don't want that message.  We are not trying to delete the whole data frame. 

I think replacing by NA is just what Excel would do.  Like Excel, we can alternatively delete the rows, but that is different.  

I assume we could delete all the data i.e. replace everything by NA.  That would still keep the names, etc.

Sounds nasty, but we will also soon have an undo as well!

2022-02-15 12:08 UTC, derekagorhom commented
thank you @shadrackkibet  i have made the necessary corrections

2022-02-15 17:03 UTC, lloyddewit commented
> @lloyddewit i have made the changes, please could you check again?

I saw changes for one comment, thank you, and I set this comment to resolved.
I still have one open comment above, I don't see any changes for this, please could you investigate? thanks

![image](https://user-images.githubusercontent.com/57253949/154111670-88367f56-0142-4604-8877-e94c1258ae15.png)

2022-02-16 04:43 UTC, derekagorhom commented
> > @lloyddewit i have made the changes, please could you check again?
> 
> I saw changes for one comment, thank you, and I set this comment to resolved. I still have one open comment above, I don't see any changes for this, please could you investigate? thanks
> 
> ![image](https://user-images.githubusercontent.com/57253949/154111670-88367f56-0142-4604-8877-e94c1258ae15.png)

![deletecells](https://user-images.githubusercontent.com/76208189/154197567-5bb2ecab-be83-476c-a3f6-22d865cfa7b7.png)

@lloyddewit  i have added the description to the code

2022-02-16 04:55 UTC, derekagorhom commented
Also i could not remove the `lstRowNames` from` line 332` without it affecting `line 337` due to the fact that `row_index` is needed for `$replace_values_with_NA` to work

2022-02-16 07:52 UTC, Patowhiz commented
I'm following this cause of the copy paste functionality that touches he same classes.

2022-02-16 07:57 UTC, Patowhiz commented on instat/static/InstatObject/R/data_object_R6.R
> +}
@N-thony this is more of a question than a recommendation, you may have already tested it and found it insufficient.

@N-thony I thought the `replace_value_in_data` was sufficient for this functionality?  It has all the proper checks and if you give it a set of NA's it will do the replacement correctly. I once used it for a similar functionality that you are trying to achieve here.

2022-02-17 07:04 UTC, N-thony commented on instat/static/InstatObject/R/data_object_R6.R
> +}
@Patowhiz I think you are right, what `replace_values_with_NA` is trying to do can be done in `replace_value_in_data `. Can you provide an example of where you used it?
@shadrackkibet what do you think? Do we really need `replace_values_with_NA` or just use `replace_value_in_data `?

2022-02-17 07:09 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
> +}
Try it out first. If that is sufficient then remove `replace_values_with_NA`

2022-02-17 07:13 UTC, N-thony commented on instat/static/InstatObject/R/data_object_R6.R
> +}
@derekagorhom can you try and let me know if you need help.
Btw, I think this is working well, and it is sufficient for me also this PR is about to be merged, this may take longer for @derekagorhom to try it, why not to try it in a separate PR?

2022-02-17 07:23 UTC, derekagorhom commented on instat/static/InstatObject/R/data_object_R6.R
> +}
> @derekagorhom can you try and let me know if you need help. Btw, I think this is working well, and it is sufficient for me also this PR is about to be merged, this may take longer for @derekagorhom to try it, why not to try it in a separate PR?

@N-thony please can you try it out

2022-02-17 07:25 UTC, derekagorhom commented on instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
> +    Public Sub DeleteCells(lstRowNames As List(Of String), lstColumnNames As List(Of String))
> The mainter may have some questions about this function, for example:
> 
>     * Is `replace_values_with_NA` the same as deleting cells?
> 
>     * If we are only deleting colums, then what is the purpose of the `lstRowNames` parameter?
> 
>     * Are we deleting all the specified rows and columns? or only some cells?
> 
> 
> Please could you expand the comment to clearly explain the purpose of the function and the parameters?
> 
> Also, is the name a bit misleading? Would it be better to call it something like `ReplaceCellsWithNA`?

and also this changes requested by @lloyddewit, i dont think these changes are possible for me, but if @N-thony  can try, i will be grateful

2022-02-17 07:26 UTC, N-thony commented on instat/static/InstatObject/R/data_object_R6.R
> +}
I will try it in a separate PR then. We can keep this as it is sufficient for me in this PR.

2022-02-17 17:56 UTC, lloyddewit approved these changes

2022-02-17 18:00 UTC, lloyddewit commented
@rdstern Please could you test again?
@shadrackkibet I approved, but you may have an open comment above. Please could you also approve?
Thanks

2022-02-17 19:51 UTC, shadrackkibet approved these changes

2022-02-18 07:01 UTC, shadrackkibet commented
@rdstern If you can do a quick [sanity check](https://en.wikipedia.org/wiki/Sanity_check) and approve then we can merge.

2022-02-18 08:27 UTC, rdstern approved these changes
Great.  Looks good now.

2022-02-18 08:39 UTC, lloyddewit commented
I'll go ahead and merge. I understand that @Patowhiz has some extra ideas for improvements, these can be done in a separate PR.

2022-02-18 08:40 UTC, merged