Fixing Reset issue in Prepare>Numeric>Transform dialog
africanmathsinitiative/R-Instat pull request #7188
Opened 2022-02-02 12:15 UTC by anastasia-mbithe

This partially fixes #7076 
Hello, @rdstern and @shadrackkibet. This fixes the reset issue in the Numeric Transform dialog.

2022-02-12 20:38 UTC, rdstern reviewed
@anastasia-mbithe I am now confused by this.  I tested this and the error is still there.  But it now seems ok in the master version, so I think the error has been fixed in the position control.

In that case surely this can simply be closed?

2022-02-14 06:53 UTC, anastasia-mbithe commented
@rdstern if the issue was fixed in the position control then am good if its closed.

2022-02-14 17:17 UTC, lloyddewit commented
I closed because of comments above. We can always reopen if needed.

2022-02-15 07:32 UTC, anastasia-mbithe commented
@rdstern, we should consider reopening this PR, since PR #7076 did not fix the reset issue. I went ahead this morning to test the changes in the master and the reset issue is still there and this PR fixes that. 
You can consider re-testing the master.

2022-02-16 11:32 UTC, rdstern approved these changes
@anastasia-mbithe great.  This now seems to work well

2022-02-17 06:24 UTC, shadrackkibet requested changes

2022-02-17 06:24 UTC, shadrackkibet commented on instat/dlgTransform.vb
> +    Private Sub BaseFunctions()
This `sub` has only 1 reference. I suggest you remove the `sub` and move the code to where it is referenced.

2022-02-17 07:05 UTC, shadrackkibet approved these changes

2022-02-17 07:05 UTC, merged

2022-02-17 07:07 UTC, shadrackkibet commented on instat/dlgTransform.vb
> +    Private Sub BaseFunctions()
I will fix this while working on #7236. Please ignore it.