Fixes position error when user changes the selected data frame in dialogs
africanmathsinitiative/R-Instat pull request #7191
Opened 2022-02-03 07:57 UTC by Patowhiz

Fixes issue #7076 .
@africanmathsinitiative/developers this is ready for review.

@dannyparsons @rdstern the key question is, if a user changes the data frame selected on the dialog, what should be the default position of the new column produced? I've set it to always revert back to 'end'. If you want that changed, please let me know.

2022-02-03 08:50 UTC, dannyparsons commented
Yes, the default goes to "end" if the data frame is changed.

2022-02-03 09:59 UTC, Patowhiz commented on instat/ucrSave.vb
> +            'reset the super selected option, because the control has reset the position variables
```suggestion
            'reset the user selected option, because the control has reset the position variables

```

2022-02-04 10:48 UTC, rdstern approved these changes
@Patowhiz great - this seems to be fixed.  @lloyddewit or @shadrackkibet over to you

2022-02-04 13:16 UTC, shadrackkibet requested changes
@Patowhiz I suggested some minor typo changes

2022-02-04 13:16 UTC, shadrackkibet commented on instat/ucrSave.vb
> +    'In future this could be used to determine whether to change the position of existing coulmns or not.
```suggestion
    'In future, this could be used to determine whether to change the position of the existing column or not.

```

2022-02-04 13:16 UTC, shadrackkibet commented on instat/ucrSave.vb
> +    ''' <summary>   If true then set the R "before" parameter to true, else set it to false.
```suggestion
    ''' <summary>   If true then set the R "before" parameter to TRUE, else set it to FALSE.

```

2022-02-04 13:47 UTC, Patowhiz commented
@shadrackkibet thanks for the review.  I have committed your suggestions.

2022-02-04 15:10 UTC, shadrackkibet commented
@rdstern - No functionality change since your last approval. If you do approve then we can merge.

2022-02-04 16:14 UTC, rdstern approved these changes
Still works fine for me.

2022-02-04 16:19 UTC, shadrackkibet approved these changes

2022-02-04 16:22 UTC, merged