Added option on File > New Data Frame to provide variable names
africanmathsinitiative/R-Instat pull request #7194
Opened 2022-02-03 09:34 UTC by N-thony

Fixes #7147 
This is still a work in progress. Actually waiting for the R code to link with the front end.

2022-02-15 18:44 UTC, N-thony commented
Hi @shadrackkibet, could you also help here with the R code? Thanks.

2022-02-15 19:06 UTC, shadrackkibet commented
Sure, I had missed it! Thanks for the reminder I will have it on my todo list.

2022-02-28 09:42 UTC, rdstern commented
@shadrackkibet have you forgotten this again?

2022-02-28 10:22 UTC, shadrackkibet commented
No, this is on my radar.

2022-03-17 21:03 UTC, rdstern requested changes
@N-thony this is promising.  But I opened the grid and then changed 2 variables to 4 and it was curious and then gave me 6.  So there's bit's to check in the grid.
Then it could be good to have a drop-down with some suggestions for the factor levels - plus people being able to enter as you suggest.  
Within this can you trap things like 1:5 and make that the name as 1,2,3,4,5.  Also a:d perhaps.  There needs to be a way of having a factor with a lot of levels, e.g. 0:20,25, 98,99.
Examples ytou give could include No, Yes, then Bad, Poor, Average, Good, Great
0-4,5-9,10,14,15,19, 20,64, 65+

2022-03-18 06:15 UTC, rdstern commented
A few more comments:
a) If I don't ask for names, just press Ok, then it still gives me logical variables called data.1, data.2.  If I ask for the names, then do nothing except press Ok, there are 2 character variables called x1, x2.  This is what should happen if I don't ask for the names, i.e. it should give the same result.
b) As mentioned above, if I change 2 to (say) 4, and then open the grid, I get 9!
c) I assume pasting will eventually work in this grid.  So I could get variable names (and labels) from Excel, and paste them into this grid?

2022-03-26 08:01 UTC, rdstern commented
@N-thony I had a look yesterday and it is certainly improved.  I am still having Visual Studio problems, so I am not sure I looked at the latest version.
The only problem was that I couldn't type into the factor levels.  I had to accept the defaults.  So I checked 1:5 and that was fine.  But what if I wanted 1:10, or something different.  The tooltip said to type separated by commas, but I couldn't type anything.
 But overall it is looking really good now.  And important.

2022-03-27 06:53 UTC, rdstern requested changes
@N-thony I am (at last - thanks to @dannyparsons ) able to review the current dialogue.  Very promising.
a) As mentioned previously, I am happy with the options for the factor variable, but you must also be able to include your own.  So, when you define a factor you can enter values separated by commas, just as you say in the tooltip.
b) When I define an integer, then it doesn't copy that variable.  (So a dataframe of 4 variables, where 2 are integer, only gives 2 variables.
c) The default can currently be anything.  So, for numeric I can currently type Roger as the default.  For integer I can give 7.5 as the default!  For simplicity I don't mind that, as long as you check when making the data frame, and change them into NA if they are illegal.  In the same way I don't mind if you could give factor levels whatever the type of column.  They would then just be ignored,  unless you later changed the type of variable to be a factor.

2022-03-29 07:34 UTC, rdstern commented
@N-thony that's getting there.
1) It still doesn't seem to work well with an integer variable.  Sometimes it ignores the column, and other times it isn't defined as integer.  If that is giving problems then delete that possibility for now.
2) When I change the number of variables it resets everything.  I'd like the remaining variables to stay as before.
3) I added `Don't Know` as another level.  It got rid of the space, before making the factor level.
4) I made a mistake on the factor levels and it gave me an error I found difficult.  That's ok for now)
5) For reference, if I make a blank factor, then I get one with no levels.  I suggest a new issue for the levels/labels factor, so add level is still enabled when there are no levels.

2022-03-29 08:14 UTC, N-thony commented
@rdstern sorry, it is not difficult, I just missed that. I'm looking into 2) 3) and 4) now.

2022-03-29 08:16 UTC, rdstern commented
great

2022-03-29 12:40 UTC, N-thony commented
@rdstern we did check of this in our last discussion and it seems to work fine. Please could you test on your side.
One thing is when you define a column with blank levels and check that column with Levels/Labels, the include level is disable and this is preventing to add levels at this situation and also Level label at the top still count the Level at 1 though there is no level. As you said at 5) it will be good to fix it in a separate PR.

2022-03-29 12:54 UTC, rdstern approved these changes
@N-thony great.
@shadrackkibet or @lloyddewit to check, so we can merge

2022-04-02 09:59 UTC, lloyddewit commented
@HawardKetoyoMsatsi Please could you do the first peer review? thanks

2022-04-06 06:26 UTC, N-thony commented
> @HawardKetoyoMsatsi Please could you do the first peer review? thanks

@HawardKetoyoMsatsi how about your review here?

2022-04-06 12:54 UTC, HawardKetoyoMsatsi commented
> 

@lloyddewit If this is urgent someone else can help take over with the review? if it is not urgent then I will submit my review before the end of the day on Friday.

2022-04-06 19:24 UTC, lloyddewit requested changes
@N-thony Thank you, I liked your coding style, your code is looking very clean and professional.
I had some comments.
This review is ongoing, I will continue from `dataTypeGridView_CellValidating()`

2022-04-06 19:24 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            End If
is this simpler?
```suggestion
            strTemp &= If(i > 0, ",", "") _
                    & Chr(34) _
                    & If(String.IsNullOrEmpty(strCh), "", strCh.Trim()) _
                    & Chr(34)
```

2022-04-06 19:24 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        strTemp = "c" & "("
```suggestion
        Dim strTemp As String = "c" & "("
```

2022-04-06 19:24 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +    Private Function GetLabelAsRString(lstLabels As List(Of String)) As String
please see my comments for `GetLevelsAsRString()`

2022-04-06 19:24 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                    = (DataGridViewDataErrorContexts.Formatting Or DataGridViewDataErrorContexts.PreferredSize)) Then
```suggestion
        If e.Context _
                    = (DataGridViewDataErrorContexts.Formatting Or DataGridViewDataErrorContexts.PreferredSize) Then

```

2022-04-06 19:24 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                dataTypeGridView.Rows.Insert(iRow, iAddRow)
Is the name `iAddRow` a bit confusing? is something like `iNumRowsToInsert` more understandable?

2022-04-06 19:26 UTC, lloyddewit commented
> > 
> 
> @lloyddewit If this is urgent someone else can help take over with the review? if it is not urgent then I will submit my review before the end of the day on Friday.

@HawardKetoyoMsatsi don't worry, I know you're busy this week with `cdms.products`. I've started reviewing this PR and I think one review will be enough.
I'll ask you to peer review the next PR :)

2022-04-07 06:45 UTC, N-thony commented on instat/dlgNewDataFrame.vb
> +                            AndAlso IsNumeric(strLevels.Substring(2, strLevels.IndexOf(":"))) Then
This to avoid having something like `1:b`, in R 1:5 will create a sequence of 1,2,3,4,5. So, I'm checking if both side are numerics.

2022-04-07 18:11 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                            AndAlso IsNumeric(strLevels.Substring(2, strLevels.IndexOf(":"))) Then
I see that you fixed this in the code, thanks

2022-04-07 18:13 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                    'developer error?
I saw that you removed `Case Else`. I thought it was a good check. Add it back with a developer error?

2022-04-07 18:17 UTC, lloyddewit commented
> @lloyddewit I resolved your first review, please take a look. Thanks.

@N-thony , thanks, there's just one open comment from the first review (see above)

2022-04-07 18:43 UTC, lloyddewit requested changes
Just a few extra comments.
I now finished my review

2022-04-07 18:43 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                dataTypeGridView(dataTypeGridView.CurrentRow.Cells("colLevels").ColumnIndex, dataTypeGridView.CurrentRow.Cells("colLevels").RowIndex).Value = e.FormattedValue
line too long? add line breaks?
(or make temp variables `iColumnIndex` and `iRowIndex` to make line more readable)

2022-04-07 18:43 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            AddHandler selectedComboBox.SelectionChangeCommitted, AddressOf selectedComboBox_SelectionChangeCommitted
are we removing and adding the same handler function? what's the purpose of this?

2022-04-07 18:43 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                dataTypeGridView(dataTypeGridView.CurrentRow.Cells("colLevels").ColumnIndex, dataTypeGridView.CurrentRow.Cells("colLevels").RowIndex).Value = ""
make temp variables `iColumnIndex` and `iRowIndex` to make lines shorter and more readable?

2022-04-07 18:43 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        Dim i As Integer
```suggestion
        Dim i As Integer = 0
```

2022-04-07 18:51 UTC, N-thony commented on instat/dlgNewDataFrame.vb
> +            AddHandler selectedComboBox.SelectionChangeCommitted, AddressOf selectedComboBox_SelectionChangeCommitted
I will remove it, it is not needed

2022-04-08 05:08 UTC, N-thony commented
@lloyddewit I resolved your second review, please take a look. Thanks.

2022-04-11 15:46 UTC, lloyddewit approved these changes

2022-04-11 15:48 UTC, lloyddewit commented
@rdstern please could you retest? thanks

2022-04-12 14:31 UTC, rdstern approved these changes

2022-04-13 07:31 UTC, merged