Fixes Bug in Regular Sequence
africanmathsinitiative/R-Instat pull request #7217
Opened 2022-02-10 08:04 UTC by derekagorhom

fixes issue #7199 

fixed the bug in `Regular sequence` by changing the code in `line 182` 
to 
`ucrNudRepeatValues.AddAdditionalCodeParameterPair(clsSeqDateFunction, New RParameter("each", 1), iAdditionalPairNo:=1)`

@africanmathsinitiative/developers  can anyone review this.

2022-02-10 08:13 UTC, derekagorhom commented
@Patowhiz here is the pull request

2022-02-10 08:17 UTC, rdstern submitted a review, later dismissed
@derekagorhom and @Patowhiz it now seems fine to me.  I assume @Patowhiz has also checked whether anything need be changed for any other dialogues.
I am approving and very happy to see this correction.

2022-02-10 10:24 UTC, dannyparsons commented
The `each` parameter should be there, but it is in `rep` not `seq`. The code examples that you shared were already correct, `each` was in `rep`.

2022-02-10 10:29 UTC, Patowhiz commented
@dannyparsons you may have missed my `seq.Date` example, have a look at it below. The `each` is in the `seq.Date` and `rep`. So what I mean is, if @derekagorhom chooses to still use the `seq.Date`, then the `each` parameter passed to it should be removed. If he chooses to use the `seq` same change will automatically apply.

```
regular <- rep(x=seq.Date(from=as.Date(x="2018/1/1"), each=1, to=as.Date(x="2018/12/31"), by="1 days"), each=1, length.out=36)
data_book$add_columns_to_data(data_name="survey", col_name="regular", col_data=regular, before=FALSE)
rm(regular)
```

2022-02-10 11:47 UTC, derekagorhom commented
> @dannyparsons you may have missed my `seq.Date` example, have a look at it below. The `each` is in the `seq.Date` and `rep`. So what I mean is, if @derekagorhom chooses to still use the `seq.Date`, then the `each` parameter passed to it should be removed. If he chooses to use the `seq` same change will automatically apply.
> 
> ```
> regular <- rep(x=seq.Date(from=as.Date(x="2018/1/1"), each=1, to=as.Date(x="2018/12/31"), by="1 days"), each=1, length.out=36)
> data_book$add_columns_to_data(data_name="survey", col_name="regular", col_data=regular, before=FALSE)
> rm(regular)
> ```

Thanks for reminding me @Patowhiz i will make the necessary changes

2022-02-10 12:09 UTC, derekagorhom commented
@dannyparsons @Patowhiz after i commented out `clsRepFunction.AddParameter("each", 1, iPosition:=2)
` in` line 140`
i run the dates sub of the Regular on the script and i got this 

```
regular <- rep(x=seq.Date(from=as.Date(x="2018/1/1"), to=as.Date(x="2018/12/31"), by="1 days"), length.out=15527)
data_book$add_columns_to_data(data_name="mydata", col_name="regular", col_data=regular, before=FALSE)

rm(regular)
```

which is what I and @Patowhiz  wanted you to be aware of since `each` is not necessary for the dates dialogue.

2022-02-11 08:40 UTC, dannyparsons commented
Thanks, yes sorry for the confusion. `each` is in `rep` only, that's correct.

2022-02-14 13:29 UTC, derekagorhom commented
> @derekagorhom is this PR ready for test/review again or do you still have more changes to make? thanks

no please

2022-02-14 18:51 UTC, lloyddewit requested changes

2022-02-14 18:51 UTC, lloyddewit commented on instat/dlgRegularSequence.vb
> +        'clsRepFunction.AddParameter("each", 1, iPosition:=2)
delete this line instead of commenting it out?

2022-02-15 07:58 UTC, derekagorhom commented
@lloyddewit  i have made the changes, please could you check again?

2022-02-15 08:35 UTC, Patowhiz commented
@lloyddewit please note that this PR has been replaced by PR #7231

2022-02-15 08:36 UTC, closed without merging