Adding dates functionality in summary tables code
africanmathsinitiative/R-Instat pull request #7230
Opened 2022-02-14 13:20 UTC by lilyclements

@rdstern @Ivanluv this should allow dates to work in the `summary_tables` function regardless of margins.

@africanmathsinitiative/developers this is ready to review.

For example

```
# Setting working directory, sourcing R code and loading R packages
setwd(dir="C:/Users/user/Source/Repos/R-Instat/instat/static/InstatObject/R")

source(file="Rsetup.R")

data_book <- DataBook$new()

options(dplyr.summarise.inform=FALSE)

# Option: Number of digits to display
options(digits=4)

# Option: Show stars on summary tables of coefficients
options(show.signif.stars=FALSE)

# Code generated by the dialog, Import Dataset
new_RDS <- readRDS(file="C:/Users/user/Documents/dodoma.RDS")
data_book$import_RDS(data_RDS=new_RDS)

summary_table <- data_book$summary_table(data_name="dodoma", columns_to_summarise=c("date", "year"),
                                         factors = c("month_abbr"),
                                         summaries=c("summary_mean", "summary_min", "summary_max"),
                                         treat_columns_as_factor = TRUE, include_margins = TRUE,
                                         margins = "summary")

mmtable2::mmtable(data=summary_table, cells=value) + mmtable2::header_top_left(variable='summary') +
    mmtable2::header_left_top('month_abbr') +
  mmtable2::header_left_top('variable')
```

2022-02-15 07:40 UTC, Ivanluv commented
@lilyclements I have tryied the code you have attached and am getting the following error
![image](https://user-images.githubusercontent.com/45068931/154013844-9d1ef79d-8e62-4afc-9b49-d5f00bd24d05.png)

2022-02-15 11:58 UTC, rdstern commented
@ivan that's a good spot.  I ran an example, with just the station as a factor, see below.  So I was just going to accept, when I saw your message.  Then added month too and got this message
![image](https://user-images.githubusercontent.com/11226469/154057792-00ad1006-94ca-4e5a-8598-bd20da27142a.png)

2022-02-15 14:37 UTC, lilyclements commented
@Ivanluv I am not getting this error - did you update your branch?

@rdstern This error is occurring in the `mmtable2` function. I am not sure what is triggering it but am trying to investigate it. It is not unique to this branch, though. It occurs for me on other branches.

2022-02-16 11:37 UTC, Ivanluv commented
@lilyclements  I have updated my branch but am getting the following error
![image](https://user-images.githubusercontent.com/45068931/154256616-cba17571-c560-4bd5-aaf5-7278ad09152b.png)
 .This is by running the  following piece of code in the script window(piece of code from the sample cod you have above)
```
summary_table <- data_book$summary_table(data_name="dodoma", columns_to_summarise=c("date", "year"),
                                         factors = c("month_abbr"),
                                         summaries=c("summary_mean", "summary_min", "summary_max"),
                                         treat_columns_as_factor = TRUE, include_margins = TRUE,
                                         margins = "summary")

mmtable2::mmtable(data=summary_table, cells=value) + mmtable2::header_top_left(variable='summary') +
    mmtable2::header_left_top('month_abbr') +
  mmtable2::header_left_top('variable')
```

2022-03-02 13:59 UTC, lilyclements commented
@Ivanluv I am not getting this error - would you mind sending a copy of your "Dodoma" data set? Perhaps I modified mine at some point without realising.

2022-03-03 07:08 UTC, Ivanluv commented
@lilyclements  this is the file [dodoma.zip](https://github.com/africanmathsinitiative/R-Instat/files/8175683/dodoma.zip)

2022-03-03 11:31 UTC, lilyclements commented
Thanks very much for this @Ivanluv - I am now getting the error so it is that our data sets are slightly different. However, this error also occurs for me on the master branch (if I run without `"date"` in `columns_to_summarise`). So this is not a new bug introduced by this code, which means in my opinion this is okay to merge.

It is a bug, though. So we should write an issue on it and I will investigate it further and fix it in another PR.
From a quick look - it only occurs if `margins = "summary"`.

2022-03-03 13:25 UTC, lilyclements commented
Previous comment being said, I've fixed the bug now anyway @Ivanluv

2022-03-04 06:39 UTC, rdstern requested changes
@lilyclements I still get an error.  I can give more details if needed, but \i think it is general.  
Use any dataset with a date variable.  Then it works fine for me to get the default of the mean date, with one factor.  But when I put 2 factors there - station and month, say, then it gives an error

2022-03-04 11:38 UTC, lilyclements commented
@rdstern is the error 

`  Cannot find linking columns to merge output from sub calculations with data for calculated_from. `

This is an issue in the summary system (I think) - it occurs in other functions like `calculate_summary`. I'll write up an issue on it, but it isn't caused by the code changes here

2022-03-04 12:53 UTC, rdstern commented
@lilyclements I tried with the Ghana 2 stations from the climatic library.
a) Try with a single factor - either station or month, and it is fine.  (There is an odd result in January when finding the mean by month???
b) But putting both factors in, as shown below, givesthe error shown below:

![image](https://user-images.githubusercontent.com/11226469/156766690-fae29672-3f1c-4fb2-ac8d-9ad8846d0b31.png)


The code is as follows:
```
# The dialog, Summary Tables
summary_table <- data_book$summary_table(data_name="ghana", columns_to_summarise="date", factors=c("month_abbr","station"), summaries=c("summary_mean"), treat_columns_as_factor=FALSE)

last_table <- (mmtable2::mmtable(data=summary_table, cells=value) + mmtable2::header_top_left(variable='summary-variable') + mmtable2::header_top_left(variable=month_abbr) + mmtable2::header_left_top(variable=station))
data_book$add_table(table_name="last_table", table=last_table, data_name="ghana")
data_book$get_tables(data_name="ghana", table_name="last_table")

```

2022-03-04 13:09 UTC, lilyclements commented
This is an issue in mmtable2, not introduced by this code. I should flag it though with the mmtable2 author. 

I’ll check the odd result in January when finding mean by month

2022-03-05 07:35 UTC, rdstern commented
@lilyclements and let's not spend too long then on this quirk, unless it also affects other types of variable.  Tables of statistics by dates is a luxury!

2022-03-08 12:58 UTC, lilyclements commented
@rdstern great. In which case, I'll write up an issue on that and this should be ready for re-review.

2022-03-08 16:14 UTC, rdstern approved these changes
ok, I am going to approve, so it can be merged, given approval from @lloyddewit or @shadrackkibet

2022-03-09 07:57 UTC, lloyddewit commented
@shadrackkibet This PR is an R change so it probably makese sense for you to review/approve, is that OK from your side?
thanks

2022-04-03 14:26 UTC, closed without merging