Fixes the regular sequence bug, refactors and improves its code
africanmathsinitiative/R-Instat pull request #7231
Opened 2022-02-14 13:22 UTC by Patowhiz

Fixes #7199
Replaces PR #7217

Fixes the original bug explained in the issue and also the other issues raised in comments.

@derekagorhom this PR includes you changes in PR #7217. I decided to create a new PR because it will be easier for me to answer any questions raised about the changes made to other files.

@africanmathsinitiative/developers this is ready for review.

@rdstern @derekagorhom I looked into using the 'seq' function for both numeric and date options but I didn't do it in this PR, the changes made here surpassed my time estimates for such implementation. Perhaps @derekagorhom can have a look at it. I'm still not sure on how it can be correctly done and I could just create a new issue about it. Thanks.

2022-02-16 12:43 UTC, rdstern submitted a review, later dismissed
@Patowhiz now looks good to me

2022-02-16 19:51 UTC, lloyddewit requested changes
Looks good, just a few small comments

2022-02-16 19:51 UTC, lloyddewit commented on instat/ucrDataFrameLength.vb
> +        Return iLength
If `Integer.TryParse()` can parse the text into an Integer, then it returns True, else False.
Should we check the result of the parse?
If it fails, then should we raise a developer error or return a default value like zero?
```suggestion
        Return If(Integer.TryParse(txtInput.Text, iLength), iLength, 0)
```

2022-02-16 19:51 UTC, lloyddewit commented on instat/dlgRegularSequence.vb
> +    Private strDefaultSequenceOption As String = ""
Should this be a string? 

Or should it be an enumeration? Or a boolean?

2022-02-16 19:51 UTC, lloyddewit commented on instat/dlgRegularSequence.vb
> +        If ucrSelectDataFrameRegularSequence.cboAvailableDataFrames.Text <> "" AndAlso
safer?
```suggestion
        If Not String.IsNullOrEmpty(ucrSelectDataFrameRegularSequence.cboAvailableDataFrames.Text) AndAlso
```

2022-02-16 19:51 UTC, lloyddewit commented on instat/dlgRegularSequence.vb
> +                Return
better for a sub?
```suggestion
                Exit Sub
```

2022-02-16 19:51 UTC, lloyddewit commented on instat/dlgRegularSequence.vb
> +            Return
```suggestion
            Exit Sub
```

2022-02-16 20:35 UTC, Patowhiz commented on instat/dlgRegularSequence.vb
> +    Private strDefaultSequenceOption As String = ""
I used a string because it seemed simple and the option is never exposed externally to other classes. It's entirely used internally. I could also use a `boolean` if you strongly think it's the best this case, I preferred a string just incase in future we have an extra option. It will be easier to just add that option with a corresponding subroutine for external setting.

2022-02-17 08:23 UTC, rdstern approved these changes
Still seems ok

2022-02-17 17:46 UTC, lloyddewit commented on instat/dlgRegularSequence.vb
> +    Private strDefaultSequenceOption As String = ""
@Patowhiz I agree that if we add another option in future, then `Boolean` is not extendable so may not be a good choice here.
I personally find `Enum` the most natural fit here, it is more readable, more constrained, and allows better static checking at compile time.

2022-02-17 17:46 UTC, lloyddewit commented
@Patowhiz just one outstanding comment above, what do you think?

2022-03-27 14:59 UTC, rdstern commented
@Patowhiz the last mention of this is conflicts.  I had earlier approved.

2022-03-30 14:07 UTC, Patowhiz commented on instat/dlgRegularSequence.vb
> +    Private strDefaultSequenceOption As String = ""
@lloyddewit `Enums` it is. Done.

2022-03-30 14:09 UTC, Patowhiz commented
@rdstern you may want to test and review this urgently before conflicts. 
It has changes to `frmMain` and also other dialog changes due to enhancements made to control `ucrDataFrameLength`

2022-03-31 09:38 UTC, lloyddewit commented
> @Patowhiz I have approved. Has @lloyddewit remaining point been addressed?

yes, fully addressed thank you

2022-03-31 09:38 UTC, lloyddewit approved these changes

2022-03-31 09:40 UTC, merged