Renamed Dialogue controls texts in the database
africanmathsinitiative/R-Instat pull request #7243
Opened 2022-02-17 15:43 UTC by N-thony

Fixes (partially) #7073 
@lloyddewit @shadrackkibet this just update the database by renaming the menu and dialogue text to `View/Delete Labels` for View Label dialogue.
![image](https://user-images.githubusercontent.com/68591383/154516768-53bb0aef-4e5d-4d91-aef2-789ce940da16.png)

2022-02-17 18:16 UTC, lloyddewit commented
@N-thony Thanks for the database update. 
I assume the change to the `translations` table, fixes the specific issue but it has the side effect that 'View Labels...' will always be translated to 'View/Delete Labels...' for all controls . This may be confusing for future developers. 
I suggest, that you reverse your current changes and instead:
- translation table:
    - View/Delete Labels..., en, View/Delete Labels...
    - View/Delete Labels, en, View/Delete Labels
- form_controls
    - for all affected controls, set the id text to 'View/Delete Labels' or 'View/Delete Labels...' as appropriate

Does that make sense?

Note: In your comment, I also changed 'Partially fixes` to 'Fixes (partially)', otherwise the issue will be closed automatically when this PR is merged.

2022-02-17 18:28 UTC, N-thony commented
> * View/Delete Labels

@lloyddewit thanks, I made the requested changes.

2022-02-22 11:48 UTC, lloyddewit requested changes
@n-thony The database changes look good, thanks.
One question: `dlgFromLibrary` files are changed, this will cause merge problems for PR #7244 . Are these changes needed?

2022-02-22 12:31 UTC, N-thony commented
> @N-thony The database changes look good, thanks. One question: `dlgFromLibrary` files are changed, this will cause merge problems for PR #7244 . Are these changes needed?

@lloyddewit yes.

2022-02-28 10:05 UTC, lloyddewit approved these changes
@N-thony thanks, just one question, if you can resolve this, then I'll approve

2022-02-28 10:05 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +    Private Sub ucrInputPackages_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrInputPackages.ControlValueChanged
are these functions needed? is it possible to undo the changes to this file?

2022-03-01 11:30 UTC, N-thony commented on instat/dlgFromLibrary.vb
> +    Private Sub ucrInputPackages_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrInputPackages.ControlValueChanged
@lloyddewit I have removed this, take a look. Thanks.

2022-03-02 08:40 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
>  End Class
```suggestion

End Class
```

2022-03-02 08:41 UTC, lloyddewit approved these changes

2022-03-02 09:41 UTC, N-thony commented
@lloyddewit after the quick discussion with Shadrack, the `Label no preview`  on the `Import dataset dialogue` should remain as it was. I have reverted the change in the database
![image](https://user-images.githubusercontent.com/68591383/156335928-2b64f7e8-5559-4dab-991b-f675afd761db.png)

2022-03-03 12:34 UTC, shadrackkibet approved these changes

2022-03-03 12:34 UTC, merged