Add ggpairs to the Describe > Two Variables > Graphs dialogue
africanmathsinitiative/R-Instat pull request #7245
Opened 2022-02-18 15:27 UTC by Ivanluv

This adds the `Pairs` radio buttons in the Describe > Two Variables > Graphs dialogue with its corresponding functionality that used the `ggpairs` function
@africanmathsinitiative/developers  this is ready for review

2022-02-19 02:50 UTC, rdstern commented
@Ivanluv that's a good start.
a) Could you swap round the 2 buttons at the top.  Pairs is simpler than By, so it could be first.
b) The receiver in pairs is currently restricted to variables of a single type.  An exciting aspect of pairs is that the types can be mixed.  So can you not have this restriction.
c) When you change the button at the top, the selected variables in the multiple receiver, should clear.  Otherwise that will complicate things, given the restrictions are different.
d) There could well be (later) a Paits Option, but I am not sure the Plot options will work.  I need to check that more

2022-02-20 07:18 UTC, rdstern commented
@Ivanluv and @lilyclements I am adding Lily into the discussion, because I suggest this is a useful function, both in its own right and as a challenge to our dialogue system.  I suggest we could usefully merge in stages, but try - eventually - to offer much of the flexibility that you can get when using it in command mode.

I propose the first aspect of this flexibility could (perhaps) go on the main dialogue.  I am sure there will be more options for a Pairs Options button.  And the main Plot Options may, indeed be useful, though some tabs would be disabled - e.g. facets.

So I propose a big group box, called Type of Display.  (I is quite complicated, so it may  - later(?) - or after discussion, move to the Pairs Options sub-dialogue.  If not, then most of the other options would go on the sub-dialogue.

There are 3 checkboxes across (or down) labelled Upper, Diagonal, Lower (for the 3 arguments (upper, diag, lower) in the function.) Default is unchecked, and then that's all you see.  (If across then in Order Lower, Diagonal, Upper, because Lower nis the most important.)
If checked, then there is a set of pull-downs, perhaps combo boxes.  For Upper and Lower, they are Labelled Continuous, Combo, Discrete, NA.  If the check-boxes go across, then these go down.
For Continuous the options are:
('points', 'smooth', 'smooth_loess', 'density', 'cor', 'blank')
For Combo they are:
('box', 'box_no_facet', 'dot', 'dot_no_facet', 'facethist', 'facetdensity', 'denstrip', 'blank')
For Discrete - which could perhaps be better labelled as Factor:
('facetbar', 'ratio', 'blank')
For NA
('na', 'blank')
For Diagonal there are just 3 pull-downs.  (They are for a single distribution, so Combo makes no sense.
Continuous: ('densityDiag', 'barDiag', 'blankDiag')
Discrete (Factor): ('barDiag', 'blankDiag')
NA: ('naDiag', 'blankDiag')

Pretty exciting stuff.

2022-02-21 13:36 UTC, Ivanluv commented
This is still in progress

2022-02-22 12:40 UTC, Ivanluv commented
@rdstern could you look at this again. In the latest changes I have:

1. Swapped the pair and the by radio buttons where the pair radio button is now the first radio button and by is the second radio button
2. Removed restriction for the multiple receiver when within the pair radio button .Also the multiple receiver is now cleared when changing between the radio buttons
3. Added the colour single receiver for the pair option 
4. Added the Type of Display group box functionality for the pairs option

2022-02-22 13:28 UTC, rdstern commented
@Ivanluv great - will do

2022-02-22 17:42 UTC, rdstern submitted a review, later dismissed
Looks great.  Hope @shadrackkibet or @lloyddewit can approve the code.  This is a very atrractive addition!

2022-02-28 09:41 UTC, lloyddewit requested changes
Thanks looks good, just a few questions?

2022-02-28 09:41 UTC, lloyddewit commented on instat/dlgDescribeTwoVarGraph.vb
> +    Public strFirstVariablesType, strSecondVariableType As String
- could these be `private`?
- Should these be enumerations rather than strings?

2022-02-28 09:41 UTC, lloyddewit commented on instat/dlgDescribeTwoVarGraph.vb
> +        ucrChkUpper.SetText("Upper")
- should this be "Diagonal"?
- these `SetText` calls are duplicated further down, are they needed here?

2022-02-28 09:41 UTC, lloyddewit commented on instat/dlgDescribeTwoVarGraph.vb
> +    Private Sub AddColumnParameter()
This is only called once, dow e need a seperate `Sub` for this?

2022-02-28 11:15 UTC, Ivanluv commented on instat/dlgDescribeTwoVarGraph.vb
> +    Public strFirstVariablesType, strSecondVariableType As String
> * could these be `private`?

yes

> * Should these be enumerations rather than strings?

They can't be an enumeration because there values are changing

2022-02-28 11:19 UTC, Ivanluv commented on instat/dlgDescribeTwoVarGraph.vb
> +        ucrChkUpper.SetText("Upper")
I have removed the duplications and correctly updated the spelling

2022-02-28 11:22 UTC, Ivanluv commented on instat/dlgDescribeTwoVarGraph.vb
> +    Private Sub AddColumnParameter()
Done

2022-02-28 11:23 UTC, Ivanluv commented
@lloyddewit  could you have a look again

2022-02-28 12:51 UTC, lloyddewit commented on instat/dlgDescribeTwoVarGraph.vb
> +    Public strFirstVariablesType, strSecondVariableType As String
ok understood

2022-02-28 12:52 UTC, lloyddewit approved these changes

2022-02-28 13:21 UTC, rdstern approved these changes
Still looks good!

2022-02-28 14:11 UTC, merged