Improving the contrasts dialog
africanmathsinitiative/R-Instat pull request #7251
Opened 2022-02-22 08:58 UTC by anastasia-mbithe

This fixes #4356 
@shadrackkibet and @rdstern, This is still in progress.

2022-02-27 05:33 UTC, rdstern commented
@anastasia-mbithe This is very good progress on this dialogue.  As I see it, there are 2 small tasks and one larger one remaining:
a) When the dialogue runs it  would be good to have something displayed in the Output window.  I suggest something like 
`Factor xxx has yyy contrasts`.  xxx is the name of the factor and yyy is the same as the entry, e.g. Treatment, User Defined.
b) It is very good that you can paste into the grid, when `User Defined` is selected.  Could Copy (ctrl<C>) also be implemented?  (That should be very easy.  Perhaps check with @N-thony if need be.
c) Now the bigger one.  When in User Defined, for any factor it should (initially) show the user defined contrasts for that factor, if they have been defined.  If not, then it should show an empty grid, i.e. zeros.  Currently - I am using the usual survey dataset, it keeps the display within the dialogue, when you move from one factor to another.
This should be quite easy to do, because the next dialogue, i.e. Factor Data Frame, already does it.  So it must be using a function that displays the user defined values when they exist.  You should just use that function and display zeros otherwise.

2022-03-05 07:51 UTC, rdstern requested changes
@anastasia-mbithe I had another look at the dialogue and believe you have now added the <ctrl> C, and that's great.  The other tasks should be quick, if you are (or will be) in Maseno and get some help from Antoine or Shadrack?  
And I am afraid I have thought of something else that would be good to add - and again I am sure @N-thony could help if you need it.  This is to display the labels in a factor as well.  I am using the usual survey data and the labels for the variety are NEW, OLD, TRAD.  Currently we just have 1, 2, 3 displayed.

2022-03-14 08:51 UTC, anastasia-mbithe commented
@rdstern We managed to have the grid show existing contrasts in the grid, when user defined option is selected. However, we did not find a way to change the labels that appear i.e village 1, village 2 etc. The contrasts function in R is set to give such output when another contrast other than Control Treatment is used.

2022-03-15 06:47 UTC, rdstern submitted a review, later dismissed
@anastasia-mbithe well done.  That is very nice now. I am approving and hope that @shadrack, or @lloyddewit can check the code, so this can be merged.
Once merged, then we can have another issue, but not urgent for a) Allowing fixed format for numbers when needed.  (That's for polynomial contrasts) and b) adding the factor labels.

2022-03-15 07:11 UTC, shadrackkibet reviewed
Please first remove commented code. Otherwise, explain why we still need it.

2022-03-15 08:52 UTC, anastasia-mbithe commented
@shadrackkibet, The commented code in the Getcontrast() sub, allows editing of the column headers and row headers, hence could be a way to fix the label issue, but it works for the control Treatment option only and bugs with the other options. I thought of keeping it so that if needed, someone could improve it in future.

2022-03-15 10:07 UTC, anastasia-mbithe commented
@rdstern @shadrackkibet, The dialog now gives a message in the output window; Factor xxx has yyy contrasts.

2022-03-15 15:43 UTC, shadrackkibet requested changes

2022-03-15 15:57 UTC, shadrackkibet commented on instat/dlgContrasts.vb
> +        ' Dim strColumnHeaders() As String
Remove

2022-03-15 15:57 UTC, shadrackkibet commented on instat/dlgContrasts.vb
> +        'grdLayoutForContrasts.SetSettings(WorkbookSettings.View_ShowHorScroll, False)
Remove

2022-03-15 15:59 UTC, shadrackkibet commented
@anastasia-mbithe could you also change the PR title? This is too general. What exactly improved?
![image](https://user-images.githubusercontent.com/26301973/158419423-7ce80442-ef57-4342-b0c0-cf77765fbdd5.png)

2022-03-16 13:07 UTC, anastasia-mbithe commented
@shadrackkibet Is the new title okay?

2022-03-16 15:56 UTC, shadrackkibet commented
@rdstern please test and re-approve.

2022-03-17 08:15 UTC, rdstern approved these changes
![image](https://user-images.githubusercontent.com/11226469/158765465-f470327a-68e1-4180-ade8-a93ab41a8fe3.png)

This can be for the future, i.e. to be able to sort out the precision that is being used in these displays.  But I would be happy for this to be merged now, and that becomes a new, and perhaps more general issue.

2022-03-17 09:10 UTC, shadrackkibet approved these changes

2022-03-17 09:10 UTC, merged