Added Help to each right-click menu and also to the script window
africanmathsinitiative/R-Instat pull request #7268
Opened 2022-03-03 13:18 UTC by Wycklife

Fixes #7067

@africanmathsinitiative/developers This is ready for review

2022-03-04 12:28 UTC, rdstern commented
@Wycklife I like the fact the help on (even right-click) on the script window, goes to the script window
But I think the same on the log window also goes to the script window.  So that should change.
The main right-click menu is also available on the left in the column metadata window.  Add the help there, just as in the data window, and it goes to the same place.
There is also a right-click in the data selector in each dialogue.  You could add Help there as well.  It could go to the `Controls on Each Dialogue` in the `Menus and Dialogues` section

2022-03-07 07:41 UTC, Wycklife commented
@rdstern You mean help on Log window goes to the script window? I thought it should go to the Log window?

2022-03-07 07:53 UTC, rdstern commented
@Wycklife it currently goes to the script window.  I also think it should go to the log window

2022-03-07 07:55 UTC, Wycklife commented
@rdstern Let me check a gain, thanks.

2022-03-07 08:44 UTC, Wycklife commented
@rdstern I have made the changes you requested. Could you please test and let me know. Thank you.

2022-03-09 07:16 UTC, rdstern approved these changes
@Wycklife this all looks good now.  Great.  With a check from @lloyddewit this could be merged.

2022-03-09 07:48 UTC, lloyddewit requested changes
@Wycklife thanks for the changes, just a couple of questions

2022-03-09 07:48 UTC, lloyddewit commented on instat/ucrColumnMetadata.vb
> +    End Sub
Combine these into a single sub? e.g. something like:
```suggestion
    Private Sub mnuHelp_Click(sender As Object, e As EventArgs) Handles mnuHelp1.Click, mnuHelp2.Click
        Help.ShowHelp(Me, frmMain.strStaticPath & "\" & frmMain.strHelpFilePath, HelpNavigator.TopicId, "543")
    End Sub
```

2022-03-09 07:48 UTC, lloyddewit commented on instat/ucrDataView.vb
> +    End Sub
Combine these into a single sub?

2022-03-09 07:48 UTC, lloyddewit commented on instat/ucrScript.vb
> +    End Sub
Merge into sub above?

2022-03-09 11:13 UTC, Wycklife commented on instat/ucrColumnMetadata.vb
> +    End Sub
Fixed

2022-03-09 11:13 UTC, Wycklife commented on instat/ucrDataView.vb
> +    End Sub
Fixed

2022-03-09 11:13 UTC, Wycklife commented on instat/ucrScript.vb
> +    End Sub
Fixed.

2022-03-09 18:40 UTC, lloyddewit approved these changes
@Wycklife thanks for the changes, happy to approve

2022-03-09 18:42 UTC, lloyddewit commented
@rdstern The changes should not have affected the functionality but it would be good to check. If you're able to test/approve again, then we can merge, thanks

2022-03-09 19:51 UTC, rdstern approved these changes
Still good

2022-03-10 14:47 UTC, merged