Added delete labels to the new recoded factor column in Recode Factor Dialogue
africanmathsinitiative/R-Instat pull request #7291
Opened 2022-03-10 16:27 UTC by N-thony

Fixes #7275 
@rdstern @shadrackkibet  as discussded on skype I have added the delete of labels to the new recoded column factor, please take a look. Thanks.
@africanmathsinitiative/developers this is ready for review. Thanks.

2022-03-11 06:43 UTC, rdstern approved these changes
@N-thony great - this works!  So I am approving.  
I did notice an inconvenience in the Recode (where you simply put the values in.
I give an example, which is to recode fert (7 levels) into None (0), Some (0.5 up to 2.5) Max (3).
a) When I do this, and return to the dialogue it has not remembered these new codes.
b) I would like to be able to copy down/paste into the new values.  I seem to have to enter them one-at a time.
This could be as a new issue if you prefer?  And it isn't that urgent.

2022-03-11 09:10 UTC, N-thony commented
> @N-thony great - this works! So I am approving. I did notice an inconvenience in the Recode (where you simply put the values in. I give an example, which is to recode fert (7 levels) into None (0), Some (0.5 up to 2.5) Max (3). a) When I do this, and return to the dialogue it has not remembered these new codes. b) I would like to be able to copy down/paste into the new values. I seem to have to enter them one-at a time. This could be as a new issue if you prefer? And it isn't that urgent.

@rdstern I have fixed item b), I think perhaps item a) to can be fixed in a separate PR. Please take a look. Thanks.

2022-03-11 09:34 UTC, rdstern approved these changes
Great

2022-03-15 10:47 UTC, lloyddewit requested changes
@N-thony thanks, looks good, I just have one small comment

2022-03-15 10:47 UTC, lloyddewit commented on instat/dlgRecodeFactor.vb
> +    Private clsRemoveLabelsFunction, clsAddLabelsFunction As New RFunction
remove `clsAddLabelsFunction `?

2022-03-15 13:01 UTC, lloyddewit approved these changes

2022-03-16 08:35 UTC, rdstern approved these changes

2022-03-16 19:43 UTC, merged