Corrected the convert to numeric popup dialogue
africanmathsinitiative/R-Instat pull request #7300
Opened 2022-03-14 10:01 UTC by N-thony

Fixes #7293
I have added the checking when nothing is a numeric in the column to convert to numeric and also changed `Labelled Convert` to `Ordinal Convert`
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2022-03-14 10:49 UTC, rdstern requested changes
@N-thony almost I think.  As discussed use Labelled convert - as before - when labelled, and ordinal convert when there are no labels.

2022-03-17 07:52 UTC, rdstern approved these changes
Looks good now

2022-03-17 19:52 UTC, lloyddewit requested changes
@N-thony thanks, looks good, just a couple of small questions

2022-03-17 19:52 UTC, lloyddewit commented on instat/frmConvertToNumeric.vb
> +            cmdLabelledConvert.Text = "Lebelled Convert"
```suggestion
            cmdLabelledConvert.Text = "Labelled Convert"
```

2022-03-17 19:52 UTC, lloyddewit commented on instat/frmConvertToNumeric.vb
> +            lblOrdinal.Visible = False
Move this out of the `if else` block and set it to `lblOrdinal.Visible = Not bCheck`?

2022-03-17 19:52 UTC, lloyddewit commented on instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
> +
```suggestion
```

2022-03-18 13:46 UTC, N-thony commented
@lloyddewit I resolved your comments. Please take a look. Thanks.

2022-03-19 07:31 UTC, rdstern approved these changes
Still looks good to me

2022-03-20 19:02 UTC, lloyddewit approved these changes

2022-03-20 19:03 UTC, merged