Improved the Two Variables Graph dialog
africanmathsinitiative/R-Instat pull request #7307
Opened 2022-03-15 13:03 UTC by Ivanluv

fixes (partly) #7260

- Hiding of the group box below the Plot Options button when having the categoric by categoric options (within the by radio button)
- Aligning of the multiple and single receivers

2022-03-15 14:03 UTC, lloyddewit requested changes
thanks, just a few questions

2022-03-16 06:34 UTC, Ivanluv commented on instat/dlgDescribeTwoVarGraph.vb
> +            clsGgmosaicProduct.AddParameter("columns" & iPosition, ucrReceiverFirstVars.ucrMultipleVariables.GetVariableNames(bWithQuotes:=False), iPosition:=iPosition, bIncludeArgumentName:=False)
Done

2022-03-16 06:35 UTC, Ivanluv commented on instat/dlgDescribeTwoVarGraph.vb
> +        For Each strVariables In ucrReceiverFirstVars.ucrMultipleVariables.GetVariableNamesList(bWithQuotes:=False)
`strVariables` is being used, I have made the correction

2022-03-16 06:36 UTC, Ivanluv commented on instat/dlgDescribeTwoVarGraph.vb
> +        Dim iPosition As Integer = 0
Correction are done

2022-03-16 06:36 UTC, Ivanluv commented on instat/dlgDescribeTwoVarGraph.vb
> +            iPosition = iPosition + 1
Done

2022-03-16 06:38 UTC, Ivanluv commented on instat/dlgDescribeTwoVarGraph.vb
> +        If ucrReceiverFirstVars.ucrMultipleVariables.GetVariableNamesList(bWithQuotes:=False).Count > 0 Then
Done

2022-03-16 11:50 UTC, rdstern approved these changes
Exciting addition!

2022-03-16 11:51 UTC, rdstern approved these changes
Exciting addition

2022-03-16 20:03 UTC, lloyddewit approved these changes

2022-03-16 20:04 UTC, merged