Updated Merge Additional Data dialog
africanmathsinitiative/R-Instat pull request #7309
Opened 2022-03-15 14:46 UTC by N-thony

Fixes #7029 
In this PR I have made the following changes:

- Changed the texts the dialogue and menu also updated the database from `Merge Additional Data dialog` to `Add (Merge) Data`
- Also added two possilities of saving the data either in the current dataframe or the new dataframe
I had a discussion with @Patowhiz where we decided on the use of `add_columns_to_data` for the option of saving the merged dataframe to the current dataframe.
@africanmathsinitiative/developers @rdstern this is ready for review. Thanks.

2022-03-16 20:07 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2022-03-17 06:06 UTC, rdstern requested changes
@N-thony excellent.  I assume it will later be in the Prepare menu.  Meantime I have checked it in the Options by Context menu.
I added the lat and long in the Niger data.  The one item to change is that it included the name variable by default.  I took it out, because it is not one I am adding (it is already there!).
I realise it needs to be included in the command.  But, I would like the code to include it, if it isn't added by the user.

2022-03-17 06:25 UTC, Ivanluv approved these changes

2022-03-28 11:48 UTC, N-thony commented
@rdstern I have a conflict here that I cannot resolve, it is coming from the database change. @Vitalis95 was happy to take over all the tasks concerning changing the text on the control and also in the database.
I will close this one and open another one.

2022-03-28 12:56 UTC, closed without merging