Fixing bugs in the Lollipop Option in the Bar Chart dialog
africanmathsinitiative/R-Instat pull request #7314
Opened 2022-03-16 11:46 UTC by anastasia-mbithe

This fixes #7295
@rdstern @N-thony, the Lollipop function does not include the bar chart function, so it only gives the Lollipop graph. The Lollipop options use geom_lollipop now. I have also added a checkbox for the first Reorder under rdoValue, and linked the second reorder and Position with the By Factor receiver.

2022-03-16 16:27 UTC, rdstern approved these changes
Excellent

2022-03-17 06:23 UTC, Ivanluv commented on instat/dlgBarAndPieChart.vb
> +        'ucrInputAddReorder.bUpdateRCodeFromControl = True
Could you remove the commented section

2022-03-17 06:23 UTC, Ivanluv commented on instat/dlgBarAndPieChart.vb
> +        'ucrInputReorderValue.bUpdateRCodeFromControl = True
Remove this too

2022-03-17 06:23 UTC, Ivanluv commented on instat/dlgBarAndPieChart.vb
> +        'clsReorderFunctionValue.SetRCommand("reorder")
Remove

2022-03-17 06:24 UTC, Ivanluv commented on instat/dlgBarAndPieChart.vb
> +            'cmdBarChartOptions.Visible = True
Remove

2022-03-17 20:06 UTC, lloyddewit requested changes
@Ivanluv Thank you for the peer review.
@anastasia-mbithe looks good, just a few more questions/comments

2022-03-17 20:06 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +            End If
```suggestion
            ucrInputBarChartPositions.Visible =  Not ucrReceiverByFactor.IsEmpty()
```

2022-03-17 20:06 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +                End If
```suggestion
                ucrInputAddReorder.Visible = Not ucrReceiverByFactor.IsEmpty()
                If Not ucrInputAddReorder.Visible Then
                    ucrInputAddReorder.SetText(strNone)
                End If
```

2022-03-17 20:06 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +                    ucrInputAddReorder.SetText(strNone)
See suggestion above

2022-03-17 20:06 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +    ucrInputReorderX.ControlValueChanged, ucrInputAddReorder.ControlValueChanged, ucrInputReorderValue.ControlValueChanged, ucrNudMaxSize.ControlValueChanged, ucrChkIncreaseSize.ControlValueChanged,
Add extra line breaks (max line length should be 100 columns), and fix indents

2022-03-17 20:06 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +    Private Sub ucrChkBacktoback_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrChkBacktoback.ControlValueChanged, ucrVariablesAsFactorForBarChart.ControlValueChanged, ucrReceiverX.Cont
add extra line breaks

2022-03-22 07:30 UTC, anastasia-mbithe commented
@lloyddewit, Can you kindly have a look at this.

2022-03-23 19:05 UTC, lloyddewit approved these changes
@anastasia-mbithe thanks for the changes, looks good!

2022-03-23 19:06 UTC, lloyddewit commented
@rdstern just a few changes since your last approval, if you can test/approve again, then we can merge.
Thanks

2022-03-27 08:42 UTC, rdstern approved these changes
Looks very good now.

2022-03-27 13:18 UTC, merged