UcrSelector enhancements
africanmathsinitiative/R-Instat pull request #7322
Opened 2022-03-23 03:48 UTC by Patowhiz

Fixes partly #7162.
@africanmathsinitiative/developers this is ready for review.

2022-03-23 03:54 UTC, Patowhiz commented
When testing this I noticed there is a bug when importing spss data, for instance the spss dataset in issue #7161.
I'm not sure what's causing the issue. So @rdstern you may test the loading of dialogs using the `poulet` dataset from package `factoMineR`

2022-03-27 07:45 UTC, rdstern submitted a review, later dismissed
@Patowhiz and @shadrackkibet I tried with the poulet data as you suggested.  The selector works fine now.  I have not checked back to the time difference, but this is very satisfactory now.  So I am approving.
I hope @shadrackkibet can check the code and merge, when he is happy.  Perhaps, at the same time he could try the steps I took, because I seemed to find problems with his select.  This should not affect the merging of this, but I wonder what is happening with select?
a) I wanted to see whether the selector would cope well when there was a selection.  So I selected all variables that start with A.  It took a long time to make the selection - then it turned the names red - as desired, but did not seem to make the select that I thought.
b) Then I tried the row names dialogue - and this gives an error with selected data - I must check if that is general, and will report.
However these do not affect that I think this is now working for these very wide datasets.  I hope this can be merged and look forward to the other efficiency moves - loading the data, and also factor variables with many levels.  But this is a great first step.

2022-04-04 21:05 UTC, rdstern commented
@lloyddewit I was happy to approve this well over a week ago.  @shadrackkibet has been quiet, so I wonder if you could check and merge if ok.  My comments above were in relation to Shadrack's select work, rather than this pull request.  If we merge then I'll copy them into a new issue for select.

2022-04-05 09:36 UTC, lloyddewit requested changes
@Patowhiz Thank you for the clear and well-commented code. Just a couple of small questions

2022-04-11 11:05 UTC, Patowhiz commented on instat/ucrSelector.vb
> +    Private _strCurrentSelectorFillCondition As String = ""
@lloyddewit  I thought of that too but I had an issue with code clarity though that's arguable (the scope and initialization aspect of static variable inside functions and how fundamentally different they are in VB.Net compared to other OOP languages.)
I have no strong objection about it (it's a VB.NET feature anyway )so I have just replaced the global variable with the static function scoped variable as you have suggested.

2022-04-11 11:07 UTC, Patowhiz commented
@lloyddewit ready for your review.

2022-04-11 18:09 UTC, lloyddewit approved these changes
@N-thony Thank you! happy to approve

2022-04-11 18:10 UTC, lloyddewit commented
@rdstern Only a small change since your last approval, please could you test/approve?
Thanks

2022-04-13 18:54 UTC, merged