Combining the frequency and Summary Table in one dialogue
africanmathsinitiative/R-Instat pull request #7325
Opened 2022-03-23 09:23 UTC by Ivanluv

This PR combines the Summary and Frequency Table and replaces PR #7320
To avoid translation file  conflict the dialogue is under the` Describe>Specific Table\Graph>Summary Table.. `menu. After this get merged I will then  change the menu item text  to `Summary\Frequency Table..`

2022-03-23 09:24 UTC, Ivanluv commented
@lloyddewit @N-thony  could you review

2022-03-27 06:49 UTC, N-thony requested changes
@Ivanluv this looks good, just small comment.

2022-03-27 06:49 UTC, N-thony commented on instat/dlgSummaryTables.vb
> +            cmdFormatTable.Location = New Point(286, iCmdFormatYPosition)
This can be replaced directly with Y position number rather than having this `iCmdFormatYPosition` and then remove lines 38 and 59? What do you think?

2022-03-27 09:33 UTC, rdstern commented
@Ivanluv I wasn't sure I would like this change, once I saw it in action.  But I do!  It is a good improvement to combine the dialogues.
The only change from my point of view is that I suggest Frequency Tables are simpler than Summary tables.  So I would prefer them to be swapped round,  So they are called Frequency/Summary Tables, and that becomes the menu name too.  And Frequency Table is the first (and initial default) button.

2022-03-28 13:22 UTC, Ivanluv commented
@rdstern I have added the Frequency radio button to be the first in the dialogue. I will edit the menu option name after merging to avoid conflict that arise from editing translation file

2022-04-01 16:59 UTC, rdstern approved these changes

2022-04-02 09:48 UTC, lloyddewit approved these changes
@Ivanluv Thank you for this PR, I found your changes clean and readable.
I added some comments, but I think they are too small to justify delaying the merge. So I'm happy to approve as is.

2022-04-02 09:48 UTC, lloyddewit commented on instat/dlgSummaryTables.vb
> +        ucrReceiverMultiplePercentages.SetLinkedDisplayControl(lblFactorsAsPercentage)
should this 'TODO' be resolved in this PR?

2022-04-02 09:48 UTC, lloyddewit commented on instat/dlgSummaryTables.vb
> +                iNumberOfColumns = ucrNudColumnFactors.GetText()
`GetText()` returns a string. This line will throw an exception if the string is not a valid integer. Is it safer to do something like
```
                If Not Integer.TryParse(ucrNudColumnFactors.GetText(), iNumberOfColumns) Then
                    ' raise developer error  
                End If
```

2022-04-02 09:48 UTC, lloyddewit commented on instat/dlgSummaryTables.vb
>              iNumberOfColumns = ucrNudColumnFactors.GetText()
see comment above (I know it's not your code!)

2022-04-02 09:50 UTC, merged