UcrButtons OK and To Script Enhancements
africanmathsinitiative/R-Instat pull request #7326
Opened 2022-03-23 14:34 UTC by Patowhiz

Fixes issue #7180
@africanmathsinitiative/developers this is ready for review.

I couldn't find a .Net split button as requested by @rdstern. I had to design and implement one that adapts to the issue raised. 
If there is one that exists I'm happy to replace it with the one created here. Thanks.

2022-03-23 18:54 UTC, lloyddewit commented
@Ivanluv Please could you review?
@rdstern Please could you test?
thanks!

2022-03-25 06:42 UTC, Ivanluv submitted a review, later dismissed

2022-03-27 06:29 UTC, rdstern submitted a review, later dismissed
@Patowhiz I like this and am very happy with your little drop-down.
a) It changes the action of To Script to be consistent with the Ok button.  I am happy with that.
b) It adds the simple drop-down so you can easily opt to keep the dialogue open.  This seems to work fine.
c) It has no "memory", i.e. the default action is always to close the dialogue, if you press the main button.  That's fine too.

I suggest this is a good one for @dannyparsons to check and merge.  He may have some comments?  I am approving.
Once approved, then I envisage that certain dialogues might add further options, because there could be an obvious follow-up dialogue, and perhaps this could then be implemented.  For example after the Check Nonnumeric it could also add `Ok and Filter`.

2022-03-27 10:32 UTC, Patowhiz commented
@rdstern I agree.

And also, please do test with different language settings. Just to make sure that the button's calculation size settings are correct.

2022-03-30 09:35 UTC, Patowhiz commented
@rdstern @lloyddewit this may need to be reviewed urgently. 
More enhancements may be needed that relate to issue #7205 being implemented by @derekagorhom.
Thanks.

2022-03-30 09:54 UTC, rdstern commented
I have approved, so over to @shadrackkibet or @lloyddewit to check and merge

2022-04-02 14:21 UTC, lloyddewit requested changes
Thanks, this looks good. 
I only have a few questions/comments, mainly about naming conventions

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +        ret_size.Width += (Padding.Horizontal + 6)
```suggestion
        ret_size.Height += Padding.Vertical + 6
        ret_size.Width += Padding.Horizontal + 6
```

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +        Dim image_size As Size = If(Image Is Nothing, Size.Empty, Image.Size)
naming conventions?

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +        Dim image_size As Size = If(Image Is Nothing, Size.Empty, Image.Size)
naming conventions?

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +    Private Function CalculateButtonAutoSize() As Size
is `GetAutoSize()` more consistent?

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +    Private Function OverlayObjectRect(ByRef container As Rectangle, ByRef sizeOfObject As Size, alignment As System.Drawing.ContentAlignment) As Rectangle
`GetOverlayObjectRect(...`?

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +        Dim element_spacing As Integer = 0
Naming conventions in this sub?

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +        Dim element_spacing As Integer = 0
Naming conventions in this sub?

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +    Private Sub SplitMenu_Popup(sender As Object, e As EventArgs)
when is this triggered?

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +            _skipNextOpen = (_dropDownRectangle.Contains(PointToClient(Cursor.Position))) AndAlso MouseButtons = MouseButtons.Left
```suggestion
            _skipNextOpen = _dropDownRectangle.Contains(PointToClient(Cursor.Position)) AndAlso MouseButtons = MouseButtons.Left
```

2022-04-02 14:21 UTC, lloyddewit commented on instat/ucrSplitButton.vb
> +    Private Function AlignInRectangle(outer As Rectangle, inner As Size, align As System.Drawing.ContentAlignment) As Rectangle
`GetAlignInRectangle(...`?

2022-04-11 11:36 UTC, Patowhiz commented on instat/ucrSplitButton.vb
> +        ret_size.Width += (Padding.Horizontal + 6)
Done

2022-04-11 11:36 UTC, Patowhiz commented on instat/ucrSplitButton.vb
> +        Dim image_size As Size = If(Image Is Nothing, Size.Empty, Image.Size)
Done

2022-04-11 11:46 UTC, Patowhiz commented on instat/ucrSplitButton.vb
> +    Private Sub SplitMenu_Popup(sender As Object, e As EventArgs)
Thanks. I had initially added support for the old .Net `ContextMenu` which had a `Popup` event instead of `Opening` event. Later I realized we will never need to support it.

I have removed the event

2022-04-11 11:56 UTC, Patowhiz commented on instat/ucrSplitButton.vb
> +    Private Function AlignInRectangle(outer As Rectangle, inner As Size, align As System.Drawing.ContentAlignment) As Rectangle
Done

2022-04-11 11:57 UTC, Patowhiz commented on instat/ucrSplitButton.vb
> +            _skipNextOpen = (_dropDownRectangle.Contains(PointToClient(Cursor.Position))) AndAlso MouseButtons = MouseButtons.Left
Done

2022-04-11 11:57 UTC, Patowhiz commented on instat/ucrSplitButton.vb
> +        Dim element_spacing As Integer = 0
Done

2022-04-11 11:57 UTC, Patowhiz commented on instat/ucrSplitButton.vb
> +        Dim element_spacing As Integer = 0
Done

2022-04-11 12:18 UTC, Patowhiz commented on instat/ucrSplitButton.vb
> +        If RightToLeft = RightToLeft.Yes Then
@lloyddewit I added this to support locales using right-to-left fonts. 
For instance;

**LTR**
To Script | ↓ 

will be

**RTL**
 ↓ | To Script

You can test this block by changing the language settings of your machine.

However, I have resolved to comment this block out and just always assume we will only support left-to-right fonts. Should we ever want to support RTF in this way, then this commented block could be used. Right now it's not a check feature that will be used.

2022-04-11 18:06 UTC, lloyddewit approved these changes

2022-04-11 18:07 UTC, lloyddewit commented
@Patowhiz Thank you, happy to approve
@rdstern Please could you retest?
Thanks

2022-04-13 07:42 UTC, merged

2022-04-13 07:52 UTC, lloyddewit commented
@Patowhiz Thanks for yet another good PR.
The PR title is automatically included in the release notes. These notes should be easy to understand for users, not just developers. Therefore, in my view, the PR title should be written from the user's perspective. The PR title should say which dialog(s) is/are changed and how the dialog's use behaviour is changed. In the PR title, we shouldn't mention ucr controls or any other internal details (but these technical details are of course very welcome in the opening comment).
So sometimes I update the PR title, I hope that's OK from your side

2022-04-13 11:12 UTC, Patowhiz commented
Absolutely fine by me and very welcomed. I should improve my PR titles based on the guidelines in your comment.