Added a feature to Convert Two digit year to Four digit in the Climatic> Prepare> Conversions dialog
africanmathsinitiative/R-Instat pull request #7329
Opened 2022-03-25 17:14 UTC by anastasia-mbithe

This fixes #7254

@rdstern @N-thony, I have added a checkbox under the Units top button, such that when you have a two digit year column i.e 01, 23, 45; the function converts the two digit to four digit year column with a base year of 30. Years less than 30, 2000 is added to them and those greater than 30 1900 is added.
@rdstern you can confirm whether the checkbox in the design is in the right position.

2022-03-28 08:55 UTC, anastasia-mbithe commented
Made some minor changes to the function name

2022-03-29 10:12 UTC, Vitalis95 requested changes
![image](https://user-images.githubusercontent.com/89011415/160588644-61fb1d45-ecc9-4af0-9575-32ef18b584cb.png)
Remove line 192 if you don't need it

2022-03-29 13:12 UTC, shadrackkibet commented
@Vitalis95 have you completed your review? I also expect you to test this PR to confirm if it fixes the issue.

2022-03-29 15:20 UTC, Vitalis95 approved these changes
It looks fine

2022-03-31 10:36 UTC, lloyddewit requested changes

2022-03-31 10:36 UTC, lloyddewit commented on instat/dlgConversions.vb
> +        ucrReceiverElement.AddAdditionalCodeParameterPair(clsYearConversionFunction, (New RParameter("x", 0)), iAdditionalPairNo:=3)
Currently, if someone runs this code after 2030, then all dates after 2030 will be converted to 1931, 1932 etc.
Even if R-Instat is replaced, then there is a big chance that this code will be reused in the replacement for R-Instat, so I think we should make it future proof.
Would it be possible to get the current date, and then pass the current year as the 'base'?

2022-03-31 10:36 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +convert_yy_to_yyyy <- function (x, base=2030) {
I find it dangerous to hard-code the year (see comment above). Remove the default '2030' and make this a mandatory parameter?

2022-04-04 14:21 UTC, anastasia-mbithe commented
@lloyddewit, I had a discussion with @rdstern and @N-thony on this and we resolved to change the design. So, there's a new top button added (Year) with a receiver and a up-down control that allows one to set the base year. It has a range of 2000-2100 with the default set at 2030.
You can test it.

2022-04-04 15:04 UTC, rdstern requested changes
Asked for additional control to be added

2022-04-04 17:55 UTC, lloyddewit commented
> @lloyddewit, I had a discussion with @rdstern and @N-thony on this and we resolved to change the design. So, there's a new top button added (Year) with a receiver and a up-down control that allows one to set the base year. It has a range of 2000-2100 with the default set at 2030. You can test it.

Thank you for the explanation, I resolved my comments above. When @rdstern approves, then I'll review/approve again.

2022-05-03 11:54 UTC, rdstern approved these changes

2022-05-03 12:17 UTC, lloyddewit approved these changes

2022-05-03 12:18 UTC, merged