Fixes importing of same data frame names from RDS files
africanmathsinitiative/R-Instat pull request #7336
Opened 2022-03-29 13:55 UTC by Patowhiz

Fixes #7298.
@africanmathsinitiative/developers this is now ready for review.

2022-03-30 13:34 UTC, Patowhiz commented on instat/static/InstatObject/R/data_object_R6.R
>        dplyr::rename_with(
@shadrackkibet @lloyddewit I remove the symbol `|>`  in line 806 because RStudio flagged it as a syntax error. I think it was added unintentionally on another PR.
If it's not, let me know so that I can added it back.

2022-03-30 13:36 UTC, Patowhiz commented
@rdstern you may have to review this to avoid conflicts. It has changes to the R script file and the PR now fixes 2 critical bug issues. 
Thanks.

2022-03-30 13:43 UTC, N-thony submitted a review, later dismissed
@Patowhiz thanks, @rdstern I also checked the deleting of labels and still works fine

2022-03-30 14:43 UTC, rdstern approved these changes
@Patowhiz relief that another issue seems fixed.  @shadrackkibet or @lloyddewit ready for you to check and merge

2022-04-01 07:29 UTC, shadrackkibet commented on instat/static/InstatObject/R/data_object_R6.R
>        dplyr::rename_with(
This is a native pipe operator `|>` (requires `R 4.1+`) similar to `%>%` in `magrittr` R package. Similar to `|` in powershell.
I suspect you might be using an older version of Rstudio that flags it as a syntax error.

2022-04-02 11:58 UTC, lloyddewit requested changes
@Patowhiz Thanks, this looks good to me. If you can resolve the comment about the pipe operator, then I can approve.
Thanks

2022-04-04 13:37 UTC, Patowhiz commented on instat/static/InstatObject/R/data_object_R6.R
> +      private$data <- curr_data
```suggestion
      private$data <- curr_data |>

```

2022-04-04 13:42 UTC, Patowhiz commented
@lloyddewit I have resolved @shadrackkibet comment about the pipe operator. Thanks.

2022-04-04 18:27 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
>        dplyr::rename_with(
FYI, I don't get the syntax error.
I'm using Microsoft Visual Studio Community 2019, Version 16.11.11 and R 4.1.2

2022-04-04 18:27 UTC, lloyddewit approved these changes

2022-04-04 18:29 UTC, lloyddewit commented
@rdstern One small change since your last approval, there's a small risk that it affected the functionality. If you could test/approve again then we can merge.
Thanks

2022-04-04 20:53 UTC, rdstern approved these changes

2022-04-05 07:20 UTC, merged