Added an option to Add Key for the new column in Prepare>Data Frame>Row Numbers/Names
africanmathsinitiative/R-Instat pull request #7345
Opened 2022-03-31 07:50 UTC by anastasia-mbithe

This fixes #7323 
@rdstern and @shadrackkibet, I have added a checkbox to Add Keys to the New column created by the first option (Copy row names into Column). The checkbox is checked by default. I have been using the mtcars dataset to test the dialogue.
I have also fixed some other bug issues on the dialog. You can have a look at it.

2022-03-31 08:52 UTC, rdstern commented
@anastasia-mbithe great - thanks - will do

2022-03-31 16:33 UTC, rdstern requested changes
@ana that's great - it works fine
a) In the label you can delete into and have a capital for Data in Data Frame
b) Something new in this dialogue recently is that the default (if you don't use the Position button) is for the row to be the last column in the data frame.  IOn earlier versions it used to be the first one.  I don't know when that changed, (certainly before your work) but could you please change it back.  

And your comment in the pull request was great - very clear.

2022-04-01 19:28 UTC, rdstern approved these changes
@anastasia-mbithe excellent - many thanks
Over to @lloyddewit or @shadrackkibet to check and merge

2022-04-02 14:52 UTC, lloyddewit requested changes

2022-04-02 14:52 UTC, lloyddewit commented on instat/dlgRownamesOrNumbers.vb
> +    Private ResetRCode As Boolean = True
```suggestion
```

2022-04-02 14:54 UTC, lloyddewit approved these changes
@anastasia-mbithe I found your coding very clean and readable, thank you.
I just made one samll change, and I'm happy to approve

2022-04-02 14:54 UTC, lloyddewit commented
@rdstern I just made one small change that will not affect the functionality. If you approve again, then we can merge
thanks

2022-04-03 05:11 UTC, rdstern approved these changes
@lloyddewit this is still working fine, so I am approving.

It has uncovered a new problem, I think, namely when a variable is deleted, that is a key, (or part of a key), then the key remains.  That should not be the case.  I'll make a new issue.

2022-04-04 17:50 UTC, merged