Enhancement of the Merge Additional Dialogue
africanmathsinitiative/R-Instat pull request #7347
Opened 2022-03-31 10:28 UTC by N-thony

Fixes #7029
This PR replaces PR #7333 due to the conflicts.
@rdstern I made the changes here from your review in PR #7333, please take a look. Thanks.#7123 
@africanmathsinitiative/developers this is ready for review.

2022-03-31 20:18 UTC, rdstern approved these changes
@N-thony I am approving as it seems to work.  I tried the full merge which does work on a left join - as you said.  But the resulting data frame is much larger.  So I wonder if you could do a check that the resulting frame is ther same length as the original.  If not, then it either stops, or it then puts the result into a new data frame.  But that could come later.  I would be happy to merge first.  So hope that @shadrackkibet might check and merge.

2022-04-01 06:09 UTC, rdstern commented
@N-thony and @shadrackkibet I have been thinking a bit more about the problem with the joining in the Add (Merge) dialogue.  I think it only works if it is a 1:1 or Many:1 join?  If I am right, then a simple check, could be that the number of values in the right-hand side are unique.  So those variables could be a key.  So why not apply that check first.  We already have that check in the key dialogue.  Perhaps we could even add the check to the dialogue?

2022-04-01 09:20 UTC, N-thony commented
> @N-thony and @shadrackkibet I have been thinking a bit more about the problem with the joining in the Add (Merge) dialogue. I think it only works if it is a 1:1 or Many:1 join? If I am right, then a simple check, could be that the number of values in the right-hand side are unique. So those variables could be a key. So why not apply that check first. We already have that check in the key dialogue. Perhaps we could even add the check to the dialogue?

@rdstern I have added the check of variables uniqueness, could you test?

2022-04-01 09:52 UTC, rdstern commented
Started ok with our usual survey, with 3 variables missing in one of them.  OK not enabled.  Then added row and it was ok.
But then deleted row and added village in the joining columns.  This gave an error with message
![image](https://user-images.githubusercontent.com/11226469/161237575-167cfa60-a22c-42d8-846f-d26b577b6980.png)

Then the columns were incorrect here.

![image](https://user-images.githubusercontent.com/11226469/161237740-c3c78831-ae4f-455b-9214-4ec2faa172d4.png)

Thern it crashed!

So I tried again.  without the row I found OK wasn't enabled.  It was then enabled when I added the checkbox to put it into a new data frame.  Good.
Then I deleted all linking except Village - which still works into a new data frame.  But it doesn't let me.  I woulod like to be able to merge on village only into a new data frame.

I wonder about a checkbox (default unchecked) above Other and with with label `From Data Frame Checked for Unique Values for Join `  If checked it adds the control from the Key dialogue.  

Finally I notice the name at the top should change to `Add (Merge) Data`

2022-04-01 10:42 UTC, N-thony commented
> 

@rdstern I have tried several time to reproduce this bug but I couldn't. Perhaps as discussed on Skype if you find this again we can have a quick call again?

2022-04-01 16:17 UTC, rdstern commented
@N-thony I can't repeat it either. I assume the title will change automatically, and also expect @Vitalis95 to add it to the Prepare menu.  So approving as is.  Perhaps @shadrackkibet or @dannyparsons can also check the functioning as they examine the code?

2022-04-01 16:17 UTC, rdstern submitted a review, later dismissed

2022-04-02 18:47 UTC, lloyddewit requested changes
@N-thony Thank you, this looks very good. Just a few questions

2022-04-02 18:47 UTC, lloyddewit commented on instat/dlgMergeAdditionalData.vb
> +    Private lstVariables As New List(Of String)
make this a local variable in `AddColumns()`?

2022-04-02 18:47 UTC, lloyddewit commented on instat/dlgMergeAdditionalData.vb
> +        Dim i As Integer = 0
For each of these local variables, if we move the declaration to the block where the variable is used, then it makes the code more readable. Example for `i` below.
However, if you prefer it the way it is, then please leave unchanged.
```suggestion
```

2022-04-02 18:47 UTC, lloyddewit commented on instat/dlgMergeAdditionalData.vb
> +                i = 0
```suggestion
                Dim i As Integer = 0
```

2022-04-02 18:47 UTC, lloyddewit commented on instat/dlgMergeAdditionalData.vb
> +        Dim dctJoinColumns As New Dictionary(Of String, String)
The key and value always seem to be equal. So could we use a list instead of a dictionary?

2022-04-02 18:47 UTC, lloyddewit commented on instat/dlgMergeAdditionalData.vb
> +    Private bUniqueChecked As Boolean = False
`bUniqueChecked` sounds like it should be true if uniqueness has been checked, else false.
However, this boolean is set to false if uniqueness checked but duplicates found.
Therefore this name is a bit confusing.
Rename (e.g. `bJoinColsAreUnique`) or add a comment?

2022-04-02 19:06 UTC, N-thony commented on instat/dlgMergeAdditionalData.vb
> +        Dim dctJoinColumns As New Dictionary(Of String, String)
@lloyddewit I think we may have a case that we will need to join by different column name but which has the same structure e.g we can link A.x = B.y where A, B are datasets and x,y are variables with same structure.

2022-04-02 19:32 UTC, N-thony commented
@lloyddewit I resolved your comments, please take a look

2022-04-03 05:43 UTC, rdstern submitted a review, later dismissed
I am approving, because it still works.
However, I tried with the linking variables, before filling the multiple receiver.  I had just village, which @N-thony is wrong.
Then I tried to fill the multiple receiver, and it gave me the message each time.  I'm not delighted by that, though most users will complete the multiple receiver first.  I would prefer not to check there and to add the check in the current key dialogue, as an option below.  (Default unchecked.) Then,  if the user wants to check uniqueness, there is an obvious way to do it.  (And doing that check would not trigger the message, because that would be a repeat of the check.
But it could come later if needed.  It would be good to get this dialogue merged and added to the Prepare menu.

2022-04-03 12:01 UTC, N-thony commented
> I am approving, because it still works. However, I tried with the linking variables, before filling the multiple receiver. I had just village, which @N-thony is wrong. Then I tried to fill the multiple receiver, and it gave me the message each time. I'm not delighted by that, though most users will complete the multiple receiver first. I would prefer not to check there and to add the check in the current key dialogue, as an option below. (Default unchecked.) Then, if the user wants to check uniqueness, there is an obvious way to do it. (And doing that check would not trigger the message, because that would be a repeat of the check. But it could come later if needed. It would be good to get this dialogue merged and added to the Prepare menu.

@rdstern please take a look. I made the change as agreed from our recent Skype call discussion.

2022-04-04 11:18 UTC, N-thony commented
> The functioning is to me, now perfect. Please could the messages change slightly. Then I will be really happy to approve. a) When ok, i.e. green, it says `Join column(s) unique in From Data Frame` I am not assuming people automatically understand about the concept of a key. So I am less keen on mentioning that. b) When not ok, i.e. red it says something like `From Data Frame entries not unique.` I am not mentioning the option of New Data frame in the message, because usually the action will be to make them unique instead.

@rdstern I have changed the message, please take a look. Thanks.

2022-04-04 11:23 UTC, rdstern submitted a review, later dismissed
Great and a good improvement.  There is work still for @Vitalis95 I think, so it is included also in the Prepare menu.  But that's a separate pull request.
@lloyddewit or @shadrackkibet I hope this can be merged soon.

2022-04-04 18:11 UTC, lloyddewit requested changes

2022-04-04 18:11 UTC, lloyddewit commented on instat/dlgMergeAdditionalData.vb
>          Else
```suggestion
        cmdCheckUnique.Enabled = Not ucrReceiverSecond.IsEmpty OrElse Not ucrInputMergingBy.IsEmpty
```

2022-04-04 18:11 UTC, lloyddewit commented on instat/dlgMergeAdditionalData.vb
> +        End If
```suggestion
```

2022-04-04 18:11 UTC, lloyddewit commented on instat/dlgMergeAdditionalData.vb
> +        Dim dctJoinColumns As New Dictionary(Of String, String)
```suggestion
```

2022-04-04 18:12 UTC, lloyddewit approved these changes

2022-04-04 18:14 UTC, lloyddewit commented
@N-thony Thank  you I marked all my previous comments as resolved.
@rdstern I made some small adjustments, the functionality should be the same, please could you do a quick sanity check and approve again?
Thanks

2022-04-04 20:30 UTC, rdstern approved these changes
Great!

2022-04-05 07:16 UTC, merged