Refactors ucrFactor control and the dialogs that use it
africanmathsinitiative/R-Instat pull request #7358
Opened 2022-04-05 19:10 UTC by Patowhiz

Fixes #6936

Still in progress.

2022-04-08 15:37 UTC, Patowhiz commented
@rdstern you can start testing performance and functionality of this using @dannyparsons suggested dataset in issue #6936.
I'll write a detailed description of what has been done in this PR and why many dialogs have been changed after I'm done with 2 more dialogs;
1. Procurement > Corruption Risk Index (CRI) > Define Corruption Risk Index (CRI)
2. Structured > Survival > Define...

To get a good understanding of the performance difference in regards to wide datasets. Compare this PR with any latest changes from the master or old versions. 
Thanks

2022-04-11 05:50 UTC, Patowhiz commented
@africanmathsinitiative/developers this is now ready for review. 
You can test performance and functionalities added in this PR using @dannyparsons suggested dataset in issue #6936. 
This PR refactors and enhances `ucrFactor` control.
It also has changes to the dialogs and sub dialogs that use the control;

1. Prepare > Column: Factor > Levels/Labels...
2. Prepare > Column: Factor > Recode Levels...
3. Prepare > Column: Factor > Reference Level...
4. Prepare > Column: Factor > Unused Levels
5. Prepare > Data Frame > Filter Rows... - Define New Filter
6. Prepare > Data Frame > Filter Rows... - Filter From Factors
7. Climatic > Check Data > QC Rainfall... - Omit Months
8. Procurement > Corruption Risk Index (CRI) > Define Corruption Risk Index (CRI)
9. Structured > Survival > Define...

Please note, changes to the above dialogs and sub dialogs are strictly aimed at adapting them to use the improved controlled. Careful testing needed.
Some of these dialogs need refactoring as well.

To get a good understanding of the performance difference in regards to wide datasets from a user perspective, please compare this PR with any latest changes from the master or old versions using the suggested data set.

@rdstern @lloyddewit in regards to `ucrFactor` control, the next step after this PR is to implement copy pasting and possibly make the control use the custom grid control, especially because of Linux platforms. 
Thanks.

2022-04-11 06:56 UTC, rdstern approved these changes
Looks good to me.  I have checked some, but not all the options.  I also tried with a regular sequence in the diamonds data that was simply 1 to 53000, so with 53000 levels.  That also works ok.  I don't know whether we want to have an upper limit, above which we give a warning.  Would that be easy?  It will hardly ever be needed?

Good to have a check of the code - I assume that's @lloyddewit ?

2022-04-11 09:24 UTC, Patowhiz commented
@rdstern on the issue of upper limit we can do that in a separate PR (the selector may need that too). Ideally, this control could be made to read from structures created by @ChrisMarsh82 then those structures could implement the limits, just like the way the data view window reads from those structures. 

@rdstern in regards to testing, I would strongly suggest another user to test all options in these dialogs. Just incase I missed something, I did my own testing but would be good to have an extra set of eyes. This PR should not introduce a new bug especially to critically dialogs like the filter.

2022-04-11 15:56 UTC, lloyddewit commented
@Ivanluv please could you review? thanks

2022-04-12 11:44 UTC, Ivanluv submitted a review, later dismissed

2022-04-13 10:48 UTC, lloyddewit requested changes
@Patowhiz This looks great, I especially liked all the comments.
I made some optional suggestions, see what you think.
I reviewed everything except `ucrFactor.vb`. I_ still need to review the 2nd part of `ucrFactor.vb`. I still need to review `CreateAndFillNewDataSheet()` and the code that follows it. I'll try and complete this review tonight or tomorrow.

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +        'Once the receiver is refactored this comment can be removed.
```suggestion
        'todo Once the receiver is refactored this comment can be removed.

```

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +        MsgBox("Cutting is currently disabled. This feature will be included in future versions." & Environment.NewLine & "Try copying and deleting from one column cells at a time.", MsgBoxStyle.Info
```suggestion
        MsgBox("Cutting is currently disabled. This feature will be included in future versions." &
               Environment.NewLine & "Try copying and deleting from one column cells at a time.",
               MsgBoxStyle.Information, "Cannot cut from cells")
```

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +            MsgBox("Deleting cells is currently disabled. This feature will be included in future versions." & Environment.NewLine & "To remove a cell's value, replace the value with NA.", MsgBoxStyl
add line breaks?

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +                MsgBox("Levels must not be decimal .", MsgBoxStyle.Information, "Invalid Value")
```suggestion
                MsgBox("Levels must not be decimal", MsgBoxStyle.Information, "Invalid Value")

```

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +    'sets the state of the control, linked receiver and grid properties
tag with `<summary>`?

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +        'OnControlValueChanged()
delete?

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +        'the alternative way of getting the column type is by calling (left here for later reference)
```suggestion
        'the alternative way of getting the column type is by calling (todo left here for later reference)
```

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +        'removal of this Visibility setting can removed once ucrFilter has been fully refactored
```suggestion
        'todo removal of this Visibility setting can removed once ucrFilter has been fully refactored
```

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +    ''' applies the appropriate settings to the worksheet
add <para> tags (else it's displayed as single continuous sentence)

2022-04-13 10:48 UTC, lloyddewit commented on instat/ucrFactor.vb
> +        Dim clsRFunctionGetFactorData As New RFunction
```suggestion
        Dim clsConvertToCharFunction As New RFunction
        Dim clsGetFactorDataFunction As New RFunction
```

2022-04-13 18:52 UTC, lloyddewit requested changes
@Patowhiz I finished my review

2022-04-21 12:21 UTC, Patowhiz commented on instat/ucrFactor.vb
> +    ''' applies the appropriate settings to the worksheet
Done

2022-04-21 12:23 UTC, Patowhiz commented on instat/ucrFactor.vb
> +        'OnControlValueChanged()
Done.

2022-04-21 14:18 UTC, Patowhiz commented on instat/ucrFactor.vb
> +    Private _extraColNames As IEnumerable(Of String) = {}
@lloyddewit yes I did think of the `HashSet`. It directly complements the conceptual intent of these collections.
My problem was .Net `HashSet` do not preserve order (how I wish they had a java equivalent `LinkedHashSet `) . But after looking at how I designed the code, these collections will technically never have their elements changed (no `remove()` will ever be called directly on the collections), so no order issues will ever occur.

I have now refactored the code to use the `HashSet`.

2022-04-21 14:20 UTC, Patowhiz commented
@lloyddewit I have added your very useful suggestions. 
This is now ready for your review.

2022-04-22 07:52 UTC, lloyddewit commented
> @lloyddewit I have added your very useful suggestions. This is now ready for your review.

@Patowhiz Great. I'm happy with all the comments set to resolved. There's also a block of unresolved comments (starting at `dlgRecodeFactor.vb`), did you get a chance to look at these?
Thanks

2022-04-22 16:35 UTC, Patowhiz commented on instat/dlgRecodeFactor.vb
> +                                            extraColNames:={"New Label"},
@lloyddewit Ooh yes. This should be a constant string. let me implement that.

2022-04-22 16:39 UTC, Patowhiz commented on instat/dlgRecodeFactor.vb
> +                                            extraColNames:={"New Label"},
Done.

2022-04-22 16:44 UTC, Patowhiz commented on instat/mdlCoreControl.vb
> +        If enumerable Is Nothing OrElse enumerable.Count < 1 Then
```suggestion
        If enumerable Is Nothing OrElse enumerable.Count = 0 Then
```

2022-04-22 16:46 UTC, Patowhiz commented
@lloyddewit I think I have now made all your suggestions. Thanks.

2022-04-23 09:48 UTC, Patowhiz commented on instat/ucrFilter.vb
> +    'making sure that this is only called during this control's loading event should be prioritised
```suggestion
    'making sure that this is only called during this control's loading event should be prioritised
    'See issue #7408 comments

```

2022-04-23 09:55 UTC, Patowhiz commented on instat/ucrFactor.vb
> +        'todo removal of this Visibility setting can removed once ucrFilter has been fully refactored
```suggestion
        'todo removal of this Visibility setting can removed once ucrFilter has been fully refactored
        'see issue #7408  comments
```

2022-04-25 08:33 UTC, lloyddewit commented
> @lloyddewit I think I have now made all your suggestions. Thanks.

@Patowhiz There are 8 open comments above. For each comment, please could you resolve, or state that you rejected the comment?
thanks

2022-04-25 08:52 UTC, Patowhiz commented on instat/ucrFactor.vb
> +    Private _extraColNames As IEnumerable(Of String) = {}
Done

2022-04-25 08:53 UTC, Patowhiz commented on instat/ucrFactor.vb
> +                'then cet the body to be a radio button
Done

2022-04-25 08:54 UTC, Patowhiz commented on instat/ucrFactor.vb
> +        Dim clsRFunctionGetFactorData As New RFunction
Done

2022-04-25 08:55 UTC, Patowhiz commented on instat/ucrFactor.vb
> +        'removal of this Visibility setting can removed once ucrFilter has been fully refactored
Done.

2022-04-25 08:55 UTC, Patowhiz commented on instat/dlgLabelsLevels.vb
> +        'todo. commented out temporariry
Done.

2022-04-25 08:55 UTC, Patowhiz commented on instat/dlgLabelsLevels.vb
> +        'todo. commented out temporariry
Done.

2022-04-25 08:56 UTC, Patowhiz commented on instat/dlgRecodeFactor.vb
> +    Private Sub ucrFactorGrid_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrFactorGrid.ControlValueChanged
Done.

2022-04-25 08:56 UTC, Patowhiz commented on instat/dlgLabelsLevels.vb
>          End If
Done.

2022-04-25 08:56 UTC, Patowhiz commented on instat/ucrFactor.vb
> +        'the alternative way of getting the column type is by calling (left here for later reference)
Done.

2022-04-25 13:14 UTC, Patowhiz commented on instat/ucrFactor.vb
> +    Private WithEvents _ucrLinkedReceiver As ucrReceiverSingle
Yes  I found that weird too.

2022-04-25 13:15 UTC, Patowhiz commented
@lloyddewit I think I have now resolved all the comments. Thanks.

2022-04-25 17:51 UTC, lloyddewit approved these changes

2022-04-25 17:51 UTC, lloyddewit commented
@rdstern if you can test/approve again, then we can merge, thanks

2022-04-25 23:42 UTC, rdstern approved these changes
@Patowhiz seems fine now - and fast.  There's relatively little to show for all this work, but it was really important.  Well done.  Good to merge and still to keep checking.

2022-04-26 09:10 UTC, merged