Removes redundant event and control in ucrInputs
africanmathsinitiative/R-Instat pull request #7368
Opened 2022-04-11 10:23 UTC by Patowhiz

Fixes #7367
@africanmathsinitiative/developers this is ready for review.
Dialogs affected;
1. File > Import Import From File... 
2. File > New Data Frame...
3. Population pyramid. @rdstern is aware that this dialog is not used anywhere and it's functionality is already implemented elsewhere. I had to make changes to it because it was also using a `ucrSaveGraph` control, a redundant and unused control which I just deleted to avoid future confusion.

This PR has no direct and indirect functionality changes to the used dialogs affected (population pyramid exempted).

2022-04-11 17:52 UTC, lloyddewit commented
@N-thony Please could you review?
@rdstern Please could you test?
Thanks!

2022-04-12 18:52 UTC, lloyddewit commented
@rdstern In issue #7367 you asked 'what do I test?'.
I think that you should test if the 3 dialogs listed above still function correctly (functionality of first 2 should be unchanged).

2022-04-21 14:31 UTC, Patowhiz commented
@rdstern would be useful if you could review this. It affects the import dialog that may need additions sooner or later. Thanks.

2022-04-21 15:30 UTC, rdstern reviewed
@Patowhiz I found nothing wrong and tried New Data Frame and Open.  So sort of ok by me.
But I was confused by the name of your event.  At the top it says "redundant event and control in ucrinputs".  But the name of your pull request is regular sequencebug?  Is that intentional?

2022-04-21 17:52 UTC, Patowhiz commented
@rdstern that's just the name of my branch not the PR. 
I used this branch as a continuation of the bug I fixed in the regular sequence dialog.

Sorry for the confusion.

2022-04-22 08:00 UTC, lloyddewit commented
@N-thony did you get a chance to review?

2022-04-22 08:01 UTC, N-thony commented
> @N-thony did you get a chance to review?

@lloyddewit sorry, I missed this, let me do it now.

2022-04-25 08:29 UTC, N-thony reviewed
@Patowhiz this looks good to me, just few comment. In the ucrInput control line 325 could we make it better when the Case is 0?

2022-04-25 08:29 UTC, N-thony commented on instat/ucrInput.vb
>      Dim strReservedWords() As String = ({"if", "else", "repeat", "while", "function", "for", "in", "next", "break", "TRUE", "FALSE", "NULL", "Inf", "NaN", "NA", "NA_integer_", "NA_real_", "NA_complex
Private?

2022-04-25 08:42 UTC, Patowhiz commented on instat/ucrInput.vb
>      Dim strReservedWords() As String = ({"if", "else", "repeat", "while", "function", "for", "in", "next", "break", "TRUE", "FALSE", "NULL", "Inf", "NaN", "NA", "NA_integer_", "NA_real_", "NA_complex
```suggestion
    Protected ReadOnly strReservedWords() As String = ({"if", "else", "repeat", "while", "function", "for", "in", "next", "break", "TRUE", "FALSE", "NULL", "Inf", "NaN", "NA", "NA_integer_", "NA_real_", "NA_complex_", "NA_character_"})
```

2022-04-25 08:44 UTC, Patowhiz commented on instat/ucrInput.vb
>      Dim strReservedWords() As String = ({"if", "else", "repeat", "while", "function", "for", "in", "next", "break", "TRUE", "FALSE", "NULL", "Inf", "NaN", "NA", "NA_integer_", "NA_real_", "NA_complex
@N-thony done. I used Protected because I think it's child controls may want to use this if they override the validation functions.

2022-04-25 08:45 UTC, N-thony approved these changes

2022-04-26 15:00 UTC, lloyddewit requested changes
@Patowhiz Thank you, looks good.
Just one suggested change

2022-04-27 05:18 UTC, Patowhiz commented on instat/dlgPopulationPyramids.vb
> +''' So possibly this dialog can be deleted all together
@lloyddewit I agree. I have deleted the dialog.

2022-04-27 05:24 UTC, Patowhiz commented
> @Patowhiz this looks good to me, just few comment. In the ucrInput control line 325 could we make it better when the Case is 0?

Yes, possibly even remove it. Do you mind if that is just done in another PR? I think it would be generally safer for this control to do the refactoring in bits.
I can create an issue about, `ucrInput` validation refactoring.

2022-04-27 07:47 UTC, lloyddewit approved these changes

2022-04-27 07:48 UTC, lloyddewit commented
@Patowhiz @N-thony Thank you for the changes and review.
@rdstern If you can test/approve, then we can merge
Thanks!

2022-05-03 09:21 UTC, rdstern approved these changes
Those dialogues seem to work ok

2022-05-03 09:52 UTC, merged