Improves the use of long datasets with the Regular sequence dialog.
africanmathsinitiative/R-Instat pull request #7395
Opened 2022-04-21 08:20 UTC by anastasia-mbithe

This fixes #7388 

@rdstern, I have added a checkbox that when checked, we have the preview. I created a data frame of 200,000 rows and it worked well. Using 2,000,000 rows, it is well until you check the checkbox. So, I feel for a data frame with about 2,000,000 rows, it's safe having the regular sequence without checking for the preview at the moment. 
But since some people may find the preview useful, maybe we could show the preview for the first 1000 rows. What do you think?

2022-04-21 10:20 UTC, lloyddewit requested changes
@anastasia-mbithe code looks good, thank you
just one small suggestion

2022-04-21 10:20 UTC, lloyddewit commented on instat/dlgRegularSequence.vb
> +        End If
```suggestion
        txtPreview.Visible = ucrChkPreview.Checked
        lblPreview.Visible = ucrChkPreview.Checked
        lblMessage.Visible = ucrChkPreview.Checked
```

2022-04-25 07:50 UTC, lloyddewit approved these changes

2022-04-25 07:50 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2022-04-26 00:43 UTC, rdstern approved these changes
@anastasia-mbithe this seems good now.

2022-04-26 08:05 UTC, merged