Added the Sequence data type to the new dataframe grid
africanmathsinitiative/R-Instat pull request #7399
Opened 2022-04-22 07:11 UTC by N-thony

Fixes (partially) #7387 
@rdstern I have added the Sequence data type as suggested in the corresponding issue, please take a look.
@africanmathsinitiative/developers this is ready for review.

2022-04-23 04:26 UTC, rdstern submitted a review, later dismissed
@N-thony great - this works fine for me!  Over to @lloyddewit for possible merging.  The other part is less urgent, and can come later.

2022-04-25 08:48 UTC, lloyddewit commented
@N-thony may I review or are you still updating? thanks

2022-04-25 08:49 UTC, N-thony commented
> @N-thony may I review or are you still updating? thanks

You can review. Thanks.

2022-04-26 01:01 UTC, rdstern requested changes
@N-thony If you are going to do it they way you have suggested, then it has got to be cleverer code than this, see below:
![image](https://user-images.githubusercontent.com/11226469/165197800-670b0545-5d49-4fc6-ae81-a1f58e4cd8ed.png)

The regular sequence dialogue works fine for this example.
![image](https://user-images.githubusercontent.com/11226469/165198030-f0001e11-fa5a-4f8d-90b5-a112f4fec416.png)

Good to have those examples,  After NA have 0, then 1, then abc, then 1,10 etc.

2022-04-26 09:52 UTC, lloyddewit requested changes

2022-04-26 09:52 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                    Dim iTemp As Integer = iRows + CInt(strDefault) - 1
```suggestion
```

2022-04-26 09:52 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        If e.ColumnIndex = 3 Then
```suggestion
        ElseIf e.ColumnIndex = 3 Then
```

2022-04-26 09:52 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +
```suggestion
```

2022-04-26 09:52 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            'End If
```suggestion
```

2022-04-26 09:52 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +
```suggestion
```

2022-04-26 09:52 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            Dim iRowDefaultIndex As Integer = dataTypeGridView.CurrentRow.Cells("colDefault").RowIndex
```suggestion
```

2022-04-28 07:50 UTC, N-thony commented
@rdstern could you test this now? Thanks.

2022-04-28 08:31 UTC, rdstern requested changes
@N-thony the sequence looks fine now.
However, the factor type doesn't seem to work now

2022-04-28 08:47 UTC, N-thony commented
> @N-thony the sequence looks fine now. However, the factor type doesn't seem to work now

@rdstern this is fixed now.

2022-04-28 10:40 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                    Dim iTemp As Integer = iRows + CInt(strDefault) - 1
still needs resolving

2022-04-28 10:43 UTC, lloyddewit commented
@N-thony from my previous review, there's still one comment that needs resolving
thanks

2022-04-28 10:44 UTC, lloyddewit commented
I will review the recent changes

2022-04-28 10:48 UTC, lloyddewit approved these changes

2022-04-28 10:49 UTC, lloyddewit commented
> @N-thony from my previous review, there's still one comment that needs resolving thanks

@N-thony Please ignore, I made the change, I think its uncontroversial.
Thanks

2022-04-28 13:00 UTC, rdstern approved these changes

2022-04-28 18:11 UTC, merged