Reordered columns on the DataFrame Metadata grid
africanmathsinitiative/R-Instat pull request #7402
Opened 2022-04-22 09:57 UTC by N-thony

Fixes (partially) #7339
@rdstern I did items 1) 2) and 3) the remaining items 4) and 5) are a bit tricky to implements, probably in another PR. Please take a look.
@africanmathsinitiative/developers this is ready for review.

2022-04-25 08:38 UTC, lloyddewit requested changes
@N-thony Thank you, just one samll comment

2022-04-25 08:38 UTC, lloyddewit commented on instat/static/InstatObject/R/instat_object_R6.R
> +    if(all(c(data_name_label, label_label, row_count_label, column_count_label, data_type_label, is_calculated_label, is_hidden_label, is_linkable, key_label) %in% names(retlist))) retlist <- retlist
A line should not exceed 100 columns.
Add line breaks?

2022-04-25 09:22 UTC, N-thony commented on instat/static/InstatObject/R/instat_object_R6.R
> +    if(all(c(data_name_label, label_label, row_count_label, column_count_label, data_type_label, is_calculated_label, is_hidden_label, is_linkable, key_label) %in% names(retlist))) retlist <- retlist
@lloyddewit I have added line breaks, please take a look.

2022-04-25 18:42 UTC, lloyddewit approved these changes

2022-05-03 11:47 UTC, rdstern approved these changes

2022-05-03 12:58 UTC, merged