Added data frame null check in selector control
africanmathsinitiative/R-Instat pull request #7403
Opened 2022-04-22 13:05 UTC by Patowhiz

Fixes #7400

@africanmathsinitiative/developers  @N-thony  this is ready for review. Thanks.

2022-04-25 07:09 UTC, lloyddewit commented
@rdstern If you test (and @N-thony reviews), then I think we can merge this quite quickly, thanks

2022-04-25 12:19 UTC, N-thony approved these changes

2022-04-25 12:20 UTC, N-thony commented
@lloyddewit  over to you.

2022-04-25 17:58 UTC, lloyddewit requested changes

2022-04-25 17:58 UTC, lloyddewit commented on instat/ucrSelector.vb
> +    Private Function GetSelectorFillCondition(dataFrame As clsDataFrame, strElementType As String, lstCombinedMetadataLists As List(Of List(Of KeyValuePair(Of String, String()))), strHeading As Strin
```suggestion
    Private Function GetSelectorFillCondition(dataFrame As clsDataFrame, strElementType As String,
            lstCombinedMetadataLists As List(Of List(Of KeyValuePair(Of String, String()))),
            strHeading As String, arrStrExcludedItems As String(), strDatabaseQuery As String,
            strNcFilePath As String)
```

2022-04-25 17:58 UTC, lloyddewit commented
@rdstern if you test/approve, then we can merge, thanks

2022-04-25 23:35 UTC, rdstern approved these changes
Great.  Seems fine now

2022-04-26 07:40 UTC, lloyddewit commented
@Patowhiz The PR title should make sense for a typical RInstat user. I changed the PR title, please check and update if needed. Thanks

2022-04-26 07:40 UTC, merged