Display the data viewer selected sheet when the selected data frame in the dialog's selector is not the same as that of the data viewer
africanmathsinitiative/R-Instat pull request #7404
Opened 2022-04-22 16:19 UTC by Patowhiz

Replaces #7370
Fixes #7371
Fixes #4712
Fixes #7288

@africanmathsinitiative/developers this is ready for review.

2022-04-22 16:26 UTC, Patowhiz commented
When reviewing this PR as a user. You may get the bug being solved by @N-thony in PR #7355.

2022-04-23 14:27 UTC, Patowhiz commented
@rdstern changes made here touch almost all dialogs. And the changes themselves span over 14 files (increasing risk of conflicts). You may want to prioritize reviewing this PR. Thanks.

2022-04-25 07:20 UTC, lloyddewit commented
@Ivanluv please can you review? thanks

2022-04-25 08:44 UTC, N-thony commented
@Patowhiz I have checked the functionality and it works fine.
Just few suggestions
![image](https://user-images.githubusercontent.com/68591383/165052602-c2cbec41-7414-487d-8e36-6793519b8ba3.png)
1) Could the selected dataset in DataView window as shown in red on the dialogue be a bit wider?
2) Could we have more description i.e a tooltip as you suggested that will help the user to understand the purpose of that name on Dialogue?
3) Could we find another for the selected dataframe name rather than the current position i.e **Data Frame:    `w_kenya_al`**? It is a bit confusing
This change overwrite the change I made in PR #7370, there for I will close it. Thanks.

2022-04-25 09:04 UTC, Patowhiz commented
@rdstern I'm waiting for your response in regards to item 3 raised by @N-thony in the [comment](https://github.com/africanmathsinitiative/R-Instat/pull/7404#issuecomment-1108263952) above.

2022-04-26 00:20 UTC, rdstern reviewed
@Patowhiz that's an interesting change.  Here is the example I used:
![image](https://user-images.githubusercontent.com/11226469/165194561-01c32f23-57ca-4958-be41-5e0c0376628c.png)

I had thought differently, i.e. in the example above to just put `wkenya_stationinfo` in red?  That's just to alert the user, that it is no longer the currently visible data frame.  If we stick with your system then I would like the full name to be given.  

We should check with others, as I am not a great design person.

2022-04-26 07:07 UTC, Patowhiz commented
@rdstern your [way](https://github.com/africanmathsinitiative/R-Instat/pull/7404#pullrequestreview-952573196) is a bit advanced from implementation point of view but simpler to the users. So I'll implement that.

2022-04-26 13:34 UTC, Patowhiz commented
@rdstern @N-thony this is now ready for review.

2022-04-27 05:14 UTC, Patowhiz commented
@rdstern @N-thony @lloyddewit this is now ready for review.

Would be useful if this could be review while @ChrisMarsh82 is here. Then I can add more functionalities required in the .Net data book structures that are needed by the controls. Thanks.

2022-04-28 08:11 UTC, rdstern approved these changes
Great.  If the code is ok @lloyddewit or @ChrisMarsh82 then good to merge

2022-04-28 08:43 UTC, lloyddewit commented
> Great. If the code is ok @lloyddewit or @ChrisMarsh82 then good to merge

I can review/merge this PR

2022-04-28 08:47 UTC, lloyddewit commented
@Ivanluv On 25 April, I requested your review, did you get a chance to do this?

2022-04-28 09:04 UTC, Ivanluv commented
@lloyddewit Sorry for the late replay .The code looks okay from my end

2022-04-28 09:20 UTC, merged

2022-04-28 09:46 UTC, lloyddewit requested changes
@Patowhiz I liked your coding style, thank you.
Just a couple of small questions

2022-04-28 09:46 UTC, lloyddewit commented on instat/ucrDataFrame.vb
> +    'the ControlValueChanged is sufficent enough. So delete?
Your suggestion sounds like a cleaner solution.
Should we implement in this PR?

2022-04-28 09:46 UTC, lloyddewit commented on instat/ucrDataFrame.vb
> +            Next
would this work?
```suggestion
            cboAvailableDataFrames.Items.AddRange(frmMain.DataBook.DataFrames.ToArray)
```

2022-04-28 09:57 UTC, lloyddewit commented
@Patowhiz it looks like @ChrisMarsh82 and I both reviewed this PR at the same time. I see that this PR is now merged.
Please could you address the comments in a new PR? 
thanks and sorry for the inconvenience

2022-04-28 10:26 UTC, Patowhiz commented
@lloyddewit yes, I'll address the issues in a separate PR.

2022-05-04 10:43 UTC, Patowhiz commented on instat/ucrDataFrame.vb
> +            Next
@lloyddewit I don't think so. What we want here is to display the names of the data frame which are contained in the `strName` property of the  DataFrame objects.

2022-05-04 15:44 UTC, lloyddewit commented on instat/ucrDataFrame.vb
> +            Next
yes, you're correct

2022-05-06 05:47 UTC, Patowhiz commented on instat/ucrDataFrame.vb
> +    'the ControlValueChanged is sufficent enough. So delete?
This has now been done in PR #7451.

2022-05-06 07:51 UTC, lloyddewit commented on instat/ucrDataFrame.vb
> +    'the ControlValueChanged is sufficent enough. So delete?
great, thanks