Improvements to the One Variable Summaries
africanmathsinitiative/R-Instat pull request #7410
Opened 2022-04-25 07:20 UTC by Ivanluv

fixes #7081 and replaces PR #7123

@africanmathsinitiative/developers this is ready for review

2022-04-25 18:12 UTC, lloyddewit commented
@HawardKetoyoMsatsi Please could you review?
@rdstern Please could you test?
Thanks!

2022-04-25 23:31 UTC, rdstern requested changes
@Ivanluv and @lilyclements this is excellent now.  All over except the shouting!  I used the usual survey data and could get all I wanted in terms of the summary statistics.
Just some cosmetic things remain. I think:
a) Is the terminology the wrong way round?  The default is Display summaries as rows.  I think you mean columns?  When I make both summaries and variables as rows, then I only get one row and many columns.  So maybe all you need to change is the label.
b) When I untick both, there is just a single column.  And there is no labelling, just the numbers.
c) There is the margin All, over which I have no control.  In my examples it just gives the total count.  I'm not sure what that means and am not sure I want  the margin here?

2022-04-26 10:01 UTC, Ivanluv commented
@rdstern could you have a look again?

2022-04-26 12:18 UTC, HawardKetoyoMsatsi submitted a review, later dismissed
@Ivan I requested for a few changes, please take a look.

2022-04-26 12:18 UTC, HawardKetoyoMsatsi commented on instat/dlgOneVariableSummarise.vb
> +    Private Sub Controls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrReceiverOneVarSummarise.ControlContentsChanged, ucrNudMaxSum.ControlContentsChanged
I guess you need to listen to events happening in ucrReceiverOneVarSummarise and clsSummariesList

2022-04-26 12:18 UTC, HawardKetoyoMsatsi commented on instat/dlgOneVariableSummarise.vb
> +        ElseIf rdoDefault.Checked Then
could this just be an Else instead of ElseIf

2022-04-26 12:18 UTC, HawardKetoyoMsatsi commented on instat/dlgOneVariableSummarise.vb
> +            cmdSummaries.Visible = True
Could cmdSummaries be set as setLinkedDisplayControl

2022-04-26 12:18 UTC, HawardKetoyoMsatsi commented on instat/dlgOneVariableSummarise.vb
> +            cmdSummaries.Visible = False
Same here

2022-04-27 06:05 UTC, Ivanluv commented on instat/dlgOneVariableSummarise.vb
> +
Done

2022-04-27 06:05 UTC, Ivanluv commented on instat/dlgOneVariableSummarise.vb
> +    Private Sub Controls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrReceiverOneVarSummarise.ControlContentsChanged, ucrNudMaxSum.ControlContentsChanged
Its already done

2022-04-27 06:07 UTC, Ivanluv commented on instat/dlgOneVariableSummarise.vb
> +        ElseIf rdoDefault.Checked Then
Done

2022-04-27 06:08 UTC, Ivanluv commented on instat/dlgOneVariableSummarise.vb
> +            cmdSummaries.Visible = True
That is not possible when the `cmdSummaries`   radio buttons within the panel

2022-04-27 06:09 UTC, Ivanluv commented on instat/dlgOneVariableSummarise.vb
> +            cmdSummaries.Visible = False
That's not possible

2022-04-28 13:15 UTC, rdstern approved these changes
@Ivanluv and @lilyclements  - great!

2022-04-29 10:17 UTC, lloyddewit commented
> @HawardKetoyoMsatsi ?

@HawardKetoyoMsatsi Thank you for your review. I went through the comments/responses and set the comments to resolved. If I misunderstood anything, then let me know.
Thanks

2022-04-29 10:18 UTC, lloyddewit approved these changes
@Ivanluv Thank you! looks good

2022-04-29 10:20 UTC, lloyddewit commented
@Ivanluv does this PR fully resolve #7081? Or just partially?

2022-04-29 10:21 UTC, merged

2022-05-04 06:18 UTC, Ivanluv commented
@lloyddewit  this fully fixes #7081