Making InputParameter1 editable in Random sample dialog
africanmathsinitiative/R-Instat pull request #7412
Opened 2022-04-25 07:53 UTC by Vitalis95

Fixes #7406 
@rdstern this PR makes ucrInputParameter1 to be editable for some distributions.

2022-04-25 18:19 UTC, lloyddewit requested changes

2022-04-25 18:19 UTC, lloyddewit commented on instat/ucrDistributionsWithParameters.vb
> +            OnControlValueChanged()
```suggestion
        OnControlValueChanged()
```

2022-04-25 18:24 UTC, lloyddewit approved these changes

2022-04-26 00:38 UTC, rdstern approved these changes
@Vitalis95 seems fine to me

2022-04-26 09:03 UTC, merged