Minor Changes to Column:Text > Transform Dialogue
africanmathsinitiative/R-Instat pull request #7416
Opened 2022-04-25 14:17 UTC by derekagorhom

fixes #7398 

@rdstern @lilyclements 
This is ready for review

2022-04-25 18:40 UTC, lloyddewit requested changes

2022-04-25 18:40 UTC, lloyddewit commented on instat/dlgTransformText.vb
> +            Me.Size = New Size(482, iFullHeight / 1.27)
Do we need to hard-code this value? What's the problem with using `Me.Width`?

2022-04-25 20:15 UTC, derekagorhom commented
Sorry @lloyddewit  i had trouble with reducing the width on the dialogue, i later changed the `Autosize` to `false`. i guess i forgot to change it back to `Me.width` in` line 372`

2022-04-26 09:06 UTC, lloyddewit approved these changes

2022-04-26 09:07 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-04-28 07:39 UTC, rdstern approved these changes
Looks fine to me and useful.  Can the code be checked by @lloyddewit or @ChrisMarsh82 so this can be merged?

2022-04-28 08:30 UTC, merged