Made the change to the metadata to update the Data Frame Metadata grid
africanmathsinitiative/R-Instat pull request #7423
Opened 2022-04-27 11:52 UTC by N-thony

Fixes (partially) #7351 
@rdstern I have updated the metadata to be able to drop the key columns when there is no keys.
These changes concern items a) b) and c), please take a look.

2022-04-27 12:11 UTC, N-thony commented
> Fixes (partially) #7351 @rdstern @lilyclements I have updated the metadata to be able to drop the key columns when there is no keys. These changes concern items a) b) and c), please take a look.

2022-04-27 13:48 UTC, lilyclements reviewed
@N-thony this looks good. However, there is still a column called "Is_Key" in the data frame metadata that is created when a key creates, but does not remove when the key is removed.

1. Upon opening the survey data I have the following metadata
<img width="406" alt="image" src="https://user-images.githubusercontent.com/21180424/165532791-743574e1-1764-4c30-8659-74c2ed9b23f1.png">

2. I add a key and so the metadata shows the key column

<img width="512" alt="image" src="https://user-images.githubusercontent.com/21180424/165532976-d50f16b6-8041-484a-ae7e-c77cc785d7b1.png">

3. I remove the key. But we now have a variable "Is_Key" in the metadata
<img width="509" alt="image" src="https://user-images.githubusercontent.com/21180424/165533497-41c1c934-222f-4039-9d63-c44e41b13217.png">

2022-04-27 13:48 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +    #self$append_to_metadata(next_default_item(key_label, names(self$get_metadata())), paste(col_names, collapse = ","))
Remove this if we don't use it?

2022-04-27 13:48 UTC, lilyclements commented on instat/static/InstatObject/R/instat_object_R6.R
> +  #private$.links[[link_name]] <- NULL
and this?

2022-04-28 07:23 UTC, N-thony commented on instat/static/InstatObject/R/instat_object_R6.R
> +  #private$.links[[link_name]] <- NULL
Thanks @lilyclements , I resolved your comments.

2022-04-28 10:56 UTC, lloyddewit requested changes
@N-thony There is still an open comment from @lilyclements . If you can resolve this, then I'm happy to approve

2022-04-28 11:44 UTC, N-thony commented
> @N-thony There is still an open comment from @lilyclements . If you can resolve this, then I'm happy to approve

@lloyddewit I think all is resolved now.

2022-04-28 12:37 UTC, lilyclements commented
Looks good! @lloyddewit @rdstern this is ready for you to review

2022-04-28 13:38 UTC, rdstern approved these changes
I'm not sure this is quite right yet, but it is much better than before, so I'm approving.  It looks perfect anyway.
a) I created key automatically in survey data through the Row Numbers/Names
b) Then key 1 from Village + Field.  This replaces the row in the metadata.  Good.  Could it also delete key?  I don't think it does - and that might be all that's needed.  It could even report in the Output Window that key1 defined, key delewted?

2022-04-28 19:03 UTC, lloyddewit approved these changes

2022-04-28 19:06 UTC, merged