fixing minor bug in Rename Column Dialogue
africanmathsinitiative/R-Instat pull request #7427
Opened 2022-04-28 09:39 UTC by derekagorhom

fixes issue #7422 , minor bug in Prepare>DataFrame>Rename Column Dialogue 

Enabling the `ok button` for the multiple option 

@africanmathsinitiative/developers  this PR is ready for review

2022-04-28 11:20 UTC, lloyddewit requested changes

2022-04-28 11:20 UTC, lloyddewit commented on instat/dlgName.vb
> +            End If
```suggestion
            End If
            bCurrentCell = True
```

2022-04-28 11:20 UTC, lloyddewit commented on instat/dlgName.vb
> +            If Not CheckNames(value, iCol) Then
`CheckNames()` will only return False if `iCol` is 1. 
Therefore, we only need to call `CheckChange()` when `iCol` is 1.
If we only call this function once, then do we need a separate function at all?

2022-04-28 11:20 UTC, lloyddewit commented on instat/dlgName.vb
> +            CheckChange(dctRowsNewLabelChanged, iColIndex)
Please see my comment above

2022-04-28 12:37 UTC, derekagorhom commented on instat/dlgName.vb
> +            CheckChange(dctRowsNewLabelChanged, iColIndex)
```
ElseIf iColIndex = 2 Then
            CheckChange(dctRowsNewLabelChanged, iColIndex)
```
was used to enable the `ok buttom` for the multiple and single option in the dialogue but @N-thony  might be able to give a better explanation for why the separate function in  `checkchange()`

2022-04-28 18:57 UTC, lloyddewit commented on instat/dlgName.vb
> +            CheckChange(dctRowsNewLabelChanged, iColIndex)
@derekagorhom Could we delete `CheckNames()` and `CheckChange()`, and then rewrite `ValidateNamesFromDictionary() as below?
```
    Private Sub ValidateNamesFromDictionary(iColIndex As Integer)
        'TODO this needs to be implemented in the appropriate ucrControl
        Select Case iColIndex
            Case 1
                For Each strValue In dctRowsNewNameChanged.Values
                    Dim parsedValue As Boolean
                    If String.IsNullOrEmpty(strValue) _
                            OrElse containsFrench(strValue) _
                            OrElse Boolean.TryParse(strValue, parsedValue) _
                            OrElse strValue.ToLower.Equals("t") OrElse strValue.ToLower.Equals("f") _
                            OrElse IsNumeric(strValue) Then
                        MsgBox("The column name must not be a numeric or contain space or french accent or be a boolean e.g TRUE, FALSE, T, F.")
                        bCurrentCell = False
                        Exit For
                    End If
                    bCurrentCell = True
                Next
            Case 2
                bCurrentCell = True
        End Select
        TestOKEnabled()
    End Sub
```
Would that work?

I also noticed that the error message states that spaces are not allowed.
Please could you confirm this?
If spaces are not allowed, then please could you add a check for this?

Thanks

2022-04-29 06:20 UTC, derekagorhom commented on instat/dlgName.vb
> +            CheckChange(dctRowsNewLabelChanged, iColIndex)
It seems to work fine like now, i have not experienced the error message you mentioned above. maybe after i add this commit you could retest and confirm.

2022-04-29 09:09 UTC, lloyddewit commented on instat/dlgName.vb
> +            CheckChange(dctRowsNewLabelChanged, iColIndex)
@derekagorhom Thank you for the change.
- The `CheckNames()` function is no longer needed. Please could you delete it?
- Regarding the error message, I think there is a misunderstanding. I did not experience the error message during runtime, I just looked at the error message in the code. The error message states that spaces are not allowed. Is this correct (i.e. are spaces in a column name not allowed)? 
Please could you confirm this?
If spaces are not allowed, then please could you add a check for this?

Thanks

2022-05-02 15:23 UTC, derekagorhom commented on instat/dlgName.vb
> +            CheckChange(dctRowsNewLabelChanged, iColIndex)
@lloyddewit please i did the changes you requested, are there any more recommendations for this PR....

2022-05-03 09:37 UTC, lloyddewit commented on instat/dlgName.vb
> +            CheckChange(dctRowsNewLabelChanged, iColIndex)
@derekagorhom Please expand the `If` statement on line 229 so that it also checks that the column name does not contain any spaces.
Thanks

2022-05-19 08:59 UTC, N-thony commented
@derekagorhom is this ready for review?

2022-05-19 10:32 UTC, N-thony commented
> Not yet, I still needs the Contains function to check if the column name contains any spaces

@derekagorhom let's discuss on Slack.

2022-05-19 10:47 UTC, derekagorhom commented
Hello @lloyddewit please, I think the dialog does not need the contains function. if you check` line` 246 to 257, `ValidateRVariable` ensures labels do not contain spaces after you edit it. So could you test the dialog again, it should work.

2022-05-29 08:05 UTC, lloyddewit requested changes

2022-05-29 08:05 UTC, lloyddewit commented on instat/dlgName.vb
> +                        MsgBox("The column name must not be a numeric or contain space or french accent or be a boolean e.g TRUE, FALSE, T, F.")
```suggestion
                        MsgBox("The column name must not be a numeric or French accent or be a boolean e.g TRUE, FALSE, T, F.")
```

2022-05-29 08:06 UTC, lloyddewit approved these changes

2022-05-29 08:13 UTC, lloyddewit commented
> Hello @lloyddewit please, I think the dialog does not need the contains function. if you check` line` 246 to 257, `ValidateRVariable` ensures labels do not contain spaces after you edit it. So could you test the dialog again, it should work.

Thank you for the explanation.
I wasn't questioning the functionality. The point I was trying to make was that the error check and the error message should be consistent.
If we do not check for spaces in the `If` condition, then the error message should not state that spaces are illegal (even if spaces are replaced with a '.' elsewhere in the code). 
I updated the error message and approved.
I hope this makes sense, thanks

2022-05-29 08:16 UTC, lloyddewit commented
@rdstern Please could you test? thanks

2022-06-06 06:25 UTC, rdstern approved these changes
seems fine now

2022-06-06 07:53 UTC, merged