Improvements to the Describe > Two\Three Variable > Summaries dialog
africanmathsinitiative/R-Instat pull request #7442
Opened 2022-05-04 08:58 UTC by Ivanluv

This replaces PR #7343.
 @lloyddewit  I have addressed the comments you had from PR #7343 in this changes.

2022-05-04 09:16 UTC, rdstern commented
@Ivanluv one small point is that when there are 2 factors there is a black sort of flash as the dialogue changes size.
More important is that this doesn't seem to work!  With the usual survey data and the factors I get as follows:
![image](https://user-images.githubusercontent.com/11226469/166653981-98b9f00d-cbf4-439c-a753-e40da944dd9a.png)

2022-05-04 09:52 UTC, Ivanluv commented
@rdstern  could you have a look again?

2022-05-04 10:42 UTC, lloyddewit requested changes
@Ivanluv Thanks for the new PR, a couple of comments still open from PR #7343, and a couple of new ones

2022-05-04 10:42 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +          power_sets_summary <- power_sets[-(length(power_sets))]
indentation?

2022-05-04 10:42 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +          }
indentation?

2022-05-04 10:42 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +        }
@lilyclements 
Most of this code is duplicated below.
If we move the `if (is.null(columns_to_summarise))` check inside the `for loop`, then can we remove the duplication?

2022-05-04 10:42 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +          }
indentation?

2022-05-04 10:42 UTC, lloyddewit commented on instat/dlgDescribeTwoVariable.vb
> +                lblFirstType.ForeColor = SystemColors.Highlight
will this overwrite the assignments on lines 390 and 391?

2022-05-04 10:42 UTC, lloyddewit commented on instat/dlgDescribeTwoVariable.vb
> +                iPosition = iPosition + 1
```suggestion
                iPosition += 1
```

2022-05-04 10:42 UTC, lloyddewit commented on instat/dlgDescribeTwoVariable.vb
> +                    clsCombineFactorsFunction.AddParameter(strColumn, strColumn, bIncludeArgumentName:=False, iPosition:=iPosition)
If we use `iPosition` here, then the positions may not be consecutive.
Does this matter? Or is it cleaner to have a seprate variable for the `clsCombineFactorsFunction` parameters?

2022-05-04 10:42 UTC, lloyddewit commented on instat/dlgDescribeTwoVariable.vb
> +            clsCombineFactorsFunction.AddParameter(ucrReceiverSecondVar.GetVariableNames, ucrReceiverSecondVar.GetVariableNames, bIncludeArgumentName:=False, iPosition:=iPosition + 1)
do we need to increment `iPosition`?

2022-05-04 10:42 UTC, lloyddewit commented on instat/dlgDescribeTwoVariable.vb
> +                ucrInputMarginName.Visible = ucrChkDisplayMargins.Checked
more readable?
```suggestion
                ucrInputMarginName.Visible = True
```

2022-05-04 11:43 UTC, Ivanluv commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +          power_sets_summary <- power_sets[-(length(power_sets))]
Done

2022-05-04 11:43 UTC, Ivanluv commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +          }
Done

2022-05-04 11:44 UTC, Ivanluv commented on instat/dlgDescribeTwoVariable.vb
> +                lblFirstType.ForeColor = SystemColors.Highlight
Yes, I have made the correction

2022-05-04 11:44 UTC, Ivanluv commented on instat/dlgDescribeTwoVariable.vb
> +                iPosition = iPosition + 1
Done

2022-05-04 11:46 UTC, Ivanluv commented on instat/dlgDescribeTwoVariable.vb
> +                    clsCombineFactorsFunction.AddParameter(strColumn, strColumn, bIncludeArgumentName:=False, iPosition:=iPosition)
The positions don't matter

2022-05-04 11:46 UTC, Ivanluv commented on instat/dlgDescribeTwoVariable.vb
> +            clsCombineFactorsFunction.AddParameter(ucrReceiverSecondVar.GetVariableNames, ucrReceiverSecondVar.GetVariableNames, bIncludeArgumentName:=False, iPosition:=iPosition + 1)
No, thanks for the reminder. That's now fixed

2022-05-04 12:59 UTC, rdstern approved these changes
This is now working and it would be great if it can be included.
The funny jump in the dialogue, as it enlarges is still there.  But if the code is acceptable to @lloyddewit or others, then I would like to merge, even if another issue is added.

2022-05-04 16:29 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +          }
```suggestion
        power_sets_summary <- power_sets[-(length(power_sets))]
      } 
      else {
        if ("outer" %in% margins) {
          power_sets_summary <- power_sets
        }
        else {
          power_sets_summary <- power_sets[(c(length(power_sets)))]
        }
```

2022-05-04 16:29 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +          }
```suggestion
        if (length(summary_margins) == 1) {
          summary_margins <- data.frame(summary_margins, `summary-variable` = "count", factors = NA)
          names(summary_margins) <- c("value", "summary-variable", factors)
        }else {
          for (col in 1:ncol(summary_margins)) {
            # TODO: if the colname is the same as a factor, then do nothing
            colnames(summary_margins)[col] <- sub("_value", "_all", colnames(summary_margins)[col])
          }
          summary_margins <- summary_margins %>%
          tidyr::pivot_longer(cols = !factors, names_to = "summary-variable", values_to = "value")
        }
```

2022-05-04 16:29 UTC, lloyddewit commented on instat/dlgDescribeTwoVariable.vb
> +                ucrInputMarginName.Visible = ucrChkDisplayMargins.Checked
yes, my mistake, sorry

2022-05-04 16:31 UTC, lloyddewit commented
@lilyclements or @Ivanluv If you can resolve the last open comment above, then I can approve
Thanks

2022-05-05 07:16 UTC, Ivanluv commented
@lloyddewit @lilyclements is the best person to look on that open comment. I suggest we have this merged then I can write an issue on that

2022-05-05 14:05 UTC, lloyddewit commented
@lilyclements Please could you resolve the last remaining comment in a new PR (when you're back from leave, no hurry)?

@rdstern Normally I'd ask you to approve again but the changes since your last approval should not affect functionality, and it will be good to include this PR in this week's release build. So I'll go ahead and merge.

2022-05-05 14:06 UTC, merged