Added Lists in the New Data Frame dialog
africanmathsinitiative/R-Instat pull request #7468
Opened 2022-05-11 07:30 UTC by anastasia-mbithe

This fixes #7387 
@rdstern, @N-thony.
 I have added the second part of the issue to the dialog. This is ready for review.

2022-05-16 03:55 UTC, rdstern requested changes
@anastasia-mbithe this is great, and it mostly works.  
a) I suggest adding a checkbox, default unchecked, with label something like` R Command` as the label.  If checked, then it shows to box with the command, and that could be shorter as well.  
b) It mostly works fine and gives the lists we need.  A few do not work, and I think they all give the same error.  Here is an example:
![image](https://user-images.githubusercontent.com/11226469/168516898-b38f7eb3-7831-4c7a-a9a5-63366c74c599.png)

Others with the same error include words/word_clues, where none of words_five, four, six work.
This error could be a bit more of a puzzle to diagnose?

2022-05-16 12:21 UTC, anastasia-mbithe commented
@rdstern, can we have the lists as a tibble instead of as a data frame?

2022-05-16 12:26 UTC, rdstern commented
I assume that could be nice, but I am not sure why you are asking for this?  What's the advantage?  I am adding @lilyclements who is much better placed to answer/confirm this.

2022-05-16 12:39 UTC, anastasia-mbithe commented
@rdstern, a tibble can accommodate the unequal number of rows, and that could fix our issue here. Though the general output looks different from what data.frame gives.

![games cluedo](https://user-images.githubusercontent.com/89011047/168593783-5863ed67-62c2-4c43-b62c-c2d0ef9cd5ae.png)
This is what we will have for the "games/cluedo"

![animals dinosaurs](https://user-images.githubusercontent.com/89011047/168594204-4d1900dc-7770-4884-9ff4-477d703fa506.png)
And this for the "animals/dinosaurs"

2022-05-16 13:08 UTC, lilyclements commented
@anastasia-mbithe can you post the R code for if we used a tibble here and for if we used a table here? Might give me a better idea of the aim of the dialog.

I know we do want to use tibbles  instead of data frames in R Instat. It does introduce some differences (eg no row names). So this could be a good place to start on that. I’m not entirely sure what the “hold up” is on that.

2022-05-16 13:24 UTC, anastasia-mbithe commented
![tibble](https://user-images.githubusercontent.com/89011047/168602185-a380b2db-0400-4546-a830-51c79a4a5d16.png)
This is the code when using tibble and it runs fine.

![errorTable](https://user-images.githubusercontent.com/89011047/168602333-9354b440-c3ef-4827-a716-680f9c7ed592.png)
I have used table and it gives this error too.

2022-05-16 13:29 UTC, anastasia-mbithe commented
@lilyclements, The other option we have is filling the shortest column with NAs to match the number of rows of the longest column, then having it as a data frame. I found cbind.fill()/ rbind.fill(), though I couldn't find the functions in the current R version. Do you know of another function that could do the same?

2022-05-17 03:59 UTC, rdstern commented
@anastasia-mbithe I really like your search for solutions here.  I was happy with the data layout for the dinosaurs in a data frame, and would not want to lose that layout.  I'd like to solve the importing of these troublesome lists with something that could be used by schoolchildren, even if they have to learn some data manipulation.  So, making the data into a proper list, or into multiple variables would be ideal.

2022-05-19 09:10 UTC, N-thony commented
> @anastasia-mbithe I really like your search for solutions here. I was happy with the data layout for the dinosaurs in a data frame, and would not want to lose that layout. I'd like to solve the importing of these troublesome lists with something that could be used by schoolchildren, even if they have to learn some data manipulation. So, making the data into a proper list, or into multiple variables would be ideal.

@anastasia-mbithe any progress?

2022-05-19 10:12 UTC, anastasia-mbithe commented
> > @anastasia-mbithe I really like your search for solutions here. I was happy with the data layout for the dinosaurs in a data frame, and would not want to lose that layout. I'd like to solve the importing of these troublesome lists with something that could be used by schoolchildren, even if they have to learn some data manipulation. So, making the data into a proper list, or into multiple variables would be ideal.
> 
> @anastasia-mbithe any progress?

@N-thony Not yet, am still looking for a way to have the "particular" lists as a data frame.

2022-05-23 11:25 UTC, lilyclements commented
@rdstern @anastasia-mbithe I don't think I fully understand what we want the output to be in R-Instat for something like `games/cluedo`.

In R, if I run `rcorpora::corpora("games/cluedo")`, I get a lot of lists with different lengths:

```
$description
[1] "Characters, rooms and weapons from the board game Cluedo / Clue."

$victim
$victim$Cluedo
[1] "Dr Black"

$victim$Clue
[1] "Mr Boddy"


$suspects
$suspects$Cluedo
[1] "Miss Scarlett"   "Professor Plum"  "Mrs Peacock"     "Reverend Green"  "Colonel Mustard" "Mrs White"      

$suspects$Clue
[1] "Miss Scarlet"    "Professor Plum"  "Mrs Peacock"     "Mr Green"        "Colonel Mustard" "Mrs White"      


$weapons
$weapons$Cluedo
[1] "candlestick" "dagger"      "lead pipe"   "revolver"    "rope"        "spanner"    

$weapons$Clue
[1] "candlestick" "knife"       "lead pipe"   "revolver"    "rope"        "wrench"     


$rooms
 [1] "kitchen"       "ballroom"      "conservatory"  "dining room"   "cellar"        "billiard room" "library"       "lounge"        "hall"          "study"        

$secret_passages
     [,1]      [,2]          
[1,] "kitchen" "study"       
[2,] "lounge"  "conservatory"
```

1. How would we want this displayed in R-Instat?
2. If we do the `tibble` suggestion from @anastasia-mbithe we get the output below
`data.frame(tibble::tibble(rcorpora::corpora("games/cluedo")))`
This makes the most sense to me.

```
                                                                                                                                        rcorpora..corpora..games.cluedo..
1                                                                                                        Characters, rooms and weapons from the board game Cluedo / Clue.
2                                                                                                                                                      Dr Black, Mr Boddy
3 Miss Scarlett, Professor Plum, Mrs Peacock, Reverend Green, Colonel Mustard, Mrs White, Miss Scarlet, Professor Plum, Mrs Peacock, Mr Green, Colonel Mustard, Mrs White
4                                                          candlestick, dagger, lead pipe, revolver, rope, spanner, candlestick, knife, lead pipe, revolver, rope, wrench
5                                                                       kitchen, ballroom, conservatory, dining room, cellar, billiard room, library, lounge, hall, study
6                                                                                                                                    kitchen, lounge, study, conservatory
```

3. Running a list with just two elements, such as  `rcorpora::corpora("animals/dinosaurs")`, works in creating a data frame.
(I say two elements, because it gives `"description"` and `"dinosaurs"`).
Using `tibble` here makes it messy.
(`tibble::tibble(rcorpora::corpora("animals/dinosaurs"))`)
So, just to make it a bit more complicated, we want to say something like:

```
data <- rcorpora::corpora("animals/dinosaurs") 
if (length(data) == 2){
  data.frame(data = data.frame(data))
} else {
  data.frame(data = data.frame(tibble::tibble(data)))
}
```
The "if" statement can be in VB code not R code, and so this can be run in a sub.

(side note: `as_tibble` does not work for lists of different sizes, which is why using `tibble`)

4. So, I agree with should use `tibble` for lists of different element sizes (e.g. `"games/cluedo"`), but only if that is the sort of output we want! If we do use `tibble` for those lists, we should only use them on lists with different sizes.

2022-05-30 12:05 UTC, lilyclements commented
@rdstern I've noticed this is in "blocker" - would you mind having a look at my comment above when you get the time?

2022-05-31 09:58 UTC, lilyclements commented
@rdstern we have three different examples here.
A list of two, but with a single entry in the second part (the dinosaur name)
df <- rcorpora::corpora("animals/dinosaurs")

A list of two, but with multiple entries in the second part (e.g. "take advantage of", "bully", ...)
`df <- rcorpora::corpora("words/word_clues/clues_five")` 

A list of more than two
`df <- rcorpora::corpora("games/cluedo")`

To handle these three cases, I've written some R code (below):

```
data_unlist <- NULL
for (i in 1:length(df)){
  if (names(df[i]) == "description") {
    description <- df[i][[1]]
  } else {
    if (class(df[[i]]) == "character"){
      data_unlist[[i]] <- data.frame(list = df[[i]])
    } else if (class(df[[i]]) == "list"){
      data_unlist_i <- purrr::map(.x = names(df[[i]]), .f = ~data.frame(list = df[[i]][[.x]]))
      names(data_unlist_i) <- names(df[[i]])
      data_unlist[[i]] <- plyr::ldply(data_unlist_i, .id = "name")
    } else if ("matrix" %in% class(df[[i]])){
      data_unlist[[i]] <- data.frame(list = do.call(paste, c(data.frame(df[[i]]), sep="-")))
    }
  }
}
names(data_unlist) <- names(df)
data_unlist <- plyr::ldply(data_unlist, .id = "variable")
data_full <- data.frame(description = description, data_unlist)
head(data_full)
```

We could make this into a function to be called into the dialog for this particular package? Or would we rather avoid writing our own functions?

2022-05-31 14:14 UTC, lilyclements commented
@rdstern great, should we store the function in `stand_alone_functions.R`

2022-06-09 08:57 UTC, anastasia-mbithe commented
@lilyclements, I made the changes although there's a consistent error for all datasets like I had explained to you before. Kindly have a look at the code.

![image](https://user-images.githubusercontent.com/89011047/172807176-a16c73d0-e7f2-4d19-a323-194e0485b34d.png)

2022-06-14 06:22 UTC, N-thony commented
> @lilyclements, I made the changes although there's a consistent error for all datasets like I had explained to you before. Kindly have a look at the code.
> 
> ![image](https://user-images.githubusercontent.com/89011047/172807176-a16c73d0-e7f2-4d19-a323-194e0485b34d.png)

@lilyclements please could you help here? Thanks.

2022-06-15 07:02 UTC, anastasia-mbithe commented
@lilyclements Thank you for the changes. The function is now working well and even for the "special" case lists. As I was testing randomly, everything was well until I got to "religion/christian_saints" and it gives this error;

![image](https://user-images.githubusercontent.com/89011047/173762970-b31f8430-6a28-43e6-969a-7fccd42dbd01.png)

I checked the list in R and noticed it has two variables with many missing values. Is there a way we can add NAs to the empty cells?

2022-06-16 07:43 UTC, anastasia-mbithe commented
Thank you so much @lilyclements.
@rdstern and @lloyddewit,  this is ready for review.

2022-06-16 10:41 UTC, rdstern requested changes
@anastasia-mbithe and @lilyclements excellent.  That all seems to work now.
The large space for the command seems a bit overwhelming - especially for beginners.  Could you have a checkbox that says "Show Command:" default is unchecked.  If checked, then there is a one-line field that shows the command exactly as now.
Then we are ready to merge.  I have looked at some of the "awkward" examples, which expose some limitations in our tidying dialogues.  That's fine and we will improve them steadily!

2022-06-16 15:18 UTC, rdstern submitted a review, later dismissed
@anastasia-mbithe great!

2022-06-17 10:05 UTC, lloyddewit requested changes
@anastasia-mbithe Another readable and tidy implementation - thank you.
I also appreciated the small points like extra line breaks when needed.
I just had some small suggestions for you to consider

2022-06-17 14:23 UTC, lilyclements commented on instat/static/InstatObject/R/stand_alone_functions.R
> +        if (class(data[[i]]) == "character"){
It would. I only wrote it like this because it was personally more "readable" - to "separate" checking the description from checking the class to be like:

"Is it a description?
   If Yes - do this.
   If No - check class"

But, happy for it to be changed to your suggestion here (and remove the addition `{` elsewhere)

2022-06-20 07:20 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +        if (class(data[[i]]) == "character"){
thanks, understood. I think readability is the top priority so I'm happy to leave as is.

2022-06-20 07:55 UTC, anastasia-mbithe commented
@lloyddewit I have made all suggested changes, take a look.

2022-06-20 08:51 UTC, lloyddewit requested changes
@anastasia-mbithe Thank you for the changes. Your updates created some extra opportunities for simplification. What do you think?

2022-06-20 08:51 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            arrAvailableLists = chrListNames.ToArray
could we simplify even more?
```suggestion
            arrAvailableLists = expTemp.AsCharacter.ToArray
```

2022-06-20 08:51 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        expTemp = frmMain.clsRLink.RunInternalScriptGetValue(clsListFunction.ToScript, bSilent:=True)
simplify?
```suggestion
        Dim expTemp As SymbolicExpression = frmMain.clsRLink.RunInternalScriptGetValue(clsListFunction.ToScript, bSilent:=True)
```

2022-06-20 08:51 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        Dim expTemp As SymbolicExpression
```suggestion
```

2022-06-20 08:51 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            If ucrInputListInCategory.GetText <> "" Then
is this simpler?
```suggestion
        ElseIf ucrInputListInCategory.GetText <> "" Then
```

2022-06-20 10:40 UTC, anastasia-mbithe commented on instat/dlgNewDataFrame.vb
> +            If ucrInputListInCategory.GetText <> "" Then
I have deleted the bit before this, since it wasn't being used after we changed the functionality.

2022-06-21 07:53 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            If ucrInputListInCategory.GetText <> "" Then
@anastasia-mbithe Thanks
I saw that you deleted the code below. This will change the functionality. If you're confident it's correct, then that's fine with me. I just wanted to mention it in case it was not intentional.
```
If ucrInputCategory.GetText = "" Then
            clsCorporaFunction.AddParameter("category", Chr(34) & ucrInputListInCategory.GetText & Chr(34),
                                            bIncludeArgumentName:=False, iPosition:=0)
```

2022-06-21 07:53 UTC, lloyddewit submitted a review, later dismissed

2022-06-21 07:54 UTC, lloyddewit commented
@rdstern if you can test/approve again, then we can merge, thanks

2022-06-28 05:54 UTC, N-thony commented
> @rdstern if you can test/approve again, then we can merge, thanks

@Amsale2022 could you also test? Thanks.

2022-07-03 08:12 UTC, rdstern requested changes
@anastasia-mbithe this is looking great.
Just a few now give an error.
a) maths, primes and primes binary gives a message about setting an attribute on NULL?  I am sure that used to work before?:
![image](https://user-images.githubusercontent.com/11226469/177031129-cf8ca55f-8726-44a5-9f44-e6c8c9ccbccf.png)



b) religion > religions ansd colors > Palettes gives a different error:

![image](https://user-images.githubusercontent.com/11226469/177031097-ab46f5d9-86ba-4f03-b43a-72f970e078c7.png)

I have checked down to games, and the rest seem to work fine.


Now humans US Presidents gives:

![image](https://user-images.githubusercontent.com/11226469/177042756-6d832e77-83ee-4aea-b8a2-b482eef77d3e.png)

2022-07-04 13:58 UTC, rdstern reviewed
@anastasia-mbithe this is looking great.
Just a few now give an error.
a) maths, primes and primes binary gives a message about setting an attribute on NULL?  I am sure that used to work before?:
![image](https://user-images.githubusercontent.com/11226469/177031129-cf8ca55f-8726-44a5-9f44-e6c8c9ccbccf.png)



b) religion > religions ansd colors > Palettes gives a different error:

![image](https://user-images.githubusercontent.com/11226469/177031097-ab46f5d9-86ba-4f03-b43a-72f970e078c7.png)

I have checked down to games, and the rest seem to work fine.

2022-07-04 14:02 UTC, rdstern commented
This now seems better.  The primes and the binary primes now works well.  I really like an example with binary numbers.

religion > religions still doesn't work
Societies and groups > animal welfare  doesn't work
the special case of terrorist groups, seems not to work for any country
technology > programming languages
words > verbs with something doesn't work.

2022-07-04 17:41 UTC, rdstern commented
@lilyclements I am sorry it is giving so much trouble. 
a) The religion > Religions still doesn't work I am afraid.  Perhaps give up on that?
b) The programming languages does work fine now.  So do the societies terrorist groups, where none used to work.  Great.
c) Technology > Programming languages now works
d) Transportation > Commerical airlines doesn't work - not important
e) the words/word clues don't work, for any of them.  Giving:

![image](https://user-images.githubusercontent.com/11226469/177199714-59742bc4-c150-4fea-97b5-a19dd6ad445f.png)


f) The only one that worries me is "Words/Verbs with conjugations" - the last one in that list.  It gives the following message:

![image](https://user-images.githubusercontent.com/11226469/177198563-223f9be7-7e26-4302-afe3-f7f7b9b01af3.png)

After getting that message, if I return to other things that do work, they still do, but I get the nasty message again each time? However, when I use File > Close Data Book, I can start again without now getting that message.


 f) I wonder if it is worth changing the Show Command into a Try Command, with our usual Try code.  Then It can go green for those - most of them that work.

2022-07-04 18:31 UTC, lilyclements commented
@rdstern had a small bug in the last version which prevented some of the functions from working - including `religion > religions`, `words/word` ones

2022-07-04 19:16 UTC, rdstern commented
Looks very good now.  religion works as do the word clues.  The only 2 I can find that don't work now are 
a) transportation > commercial aircraft  - but that's of minor importance.
b) words > verbs with conjugations still gives the annoying error that then persists.  But perhaps that can wait?  If so, I'll approve now.

2022-07-04 19:30 UTC, lilyclements commented
@rdstern i suggest we write them up in an issue. I’m happy to write the issue tomorrow.

2022-07-05 05:44 UTC, rdstern approved these changes
This is great and almost everything is working now.  I am approving in its current form, though there may be a new issue to enable the final couple of lists to be imported - or at least trapped.

2022-07-05 09:33 UTC, lloyddewit requested changes
@lilyclements Thanks for the recent changes, I just have a couple of comments about readability

2022-07-05 09:33 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +        data_unlist[[i]] <- plyr::ldply(data_unlist_2, .id = "variable2")
@lilyclements Would it be more readable to move this code into a separate function?
Also, this code seems to be going down 4 levels and doing similar things at each level (with the exception of the 4th level). 
Some lines of code are repeated several times.
Could we replace this nested/duplicated code with a smaller recursive function?

2022-07-05 09:33 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  return(data_full)
@lilyclements 
```suggestion
    if (!is.null(description)){
      return (data.frame(description = description, data_unlist))
    } 
    return (data.frame(data_unlist))
```

2022-07-05 10:50 UTC, lilyclements commented on instat/static/InstatObject/R/stand_alone_functions.R
> +        data_unlist[[i]] <- plyr::ldply(data_unlist_2, .id = "variable2")
Yes I was thinking this too. I wrote a comment, but just realised I wrote it in the "commit" so it was lost!

"these should all work now. The main issue was with the religion one - it contains a list in a list in a list in a list in a list (`data$Abrahamic$Christianity$`Eastern Christianity`$`Russian Orthodox Old Believers``) so it took a little while.

I think there is a much nicer way to do it than I am doing. I have seen, for example, Danny call his own function in the function. I think that is what we would want here. I can spend some time on cleaning this up and looking into that, if you think it is worth it? Alternatively, I can do that on another branch once this is merged."

I can do a recursive function. Shall I do it on this branch or elsewhere? I do not know how long it will take as I have not written recursive before. I also have a few other priorities to get to this week

2022-07-08 06:32 UTC, rdstern submitted a review, later dismissed

2022-07-11 10:40 UTC, lilyclements commented
@lloyddewit after our call, I found a solution which avoids recursion but is hopefully still readable - or at least, a lot less complex, and works for infinite list lengths. Let me know what you think.

2022-07-12 06:32 UTC, lloyddewit approved these changes
Wow, the latest commit is a big reduction in size/complexity. It looks like you used the power of the R libraries to do the heavy lifting, which is great.
I approved, there's just one open question.
Also, you mentioned that you might add some comments to explain what's happening. Do you still plan to do that? An example of a mult-level list would be helpful.

2022-07-12 06:32 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +          names(data_unlist[[i]]) <- c(paste0("variable", 1:(length(data_unlist[[i]])-1)), "list")
I trust you but I just wanted to double-check. Is the '-1' is correct here?

2022-07-12 06:41 UTC, rdstern submitted a review, later dismissed
Great

2022-07-12 09:31 UTC, lilyclements commented on instat/static/InstatObject/R/stand_alone_functions.R
> +          names(data_unlist[[i]]) <- c(paste0("variable", 1:(length(data_unlist[[i]])-1)), "list")
Yes. So in line 2573 we run

`          data_unlist[[i]] <- cbind(data.frame(split), value = new_data$value)`

This means we are combining the columns of the data frame, `split` with the vector `value`.

As a result, there are `n` variables in the combined data frame, where `n-1` come from the `split` data frame, and the final one comes from the vector `value`.
On line 2574 we then are renaming the variables of this new combined data frame to be consistent with the variables created for the other `types` (e.g. characters, matrix, etc).
So `paste0("variable", 1:(length(data_unlist[[i]])-1))` will rename the first variables as `variable1`, ..., `variable_(n-1)` for the `n-1` variables from the `split` data frame, then `list` at the end renames the `value` variable.

2022-07-12 09:57 UTC, lilyclements commented
@lloyddewit thanks for the reminder - I have just added some comments into the function. However, this has dismissed yours and @rdstern's reviews. Sorry for that - would you mind reapproving?

2022-07-12 10:21 UTC, lloyddewit requested changes

2022-07-12 10:21 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +	  # add in the separated list to the value variable, and rename the variables
```suggestion
	     # add in the separated list to the value variable, and rename the variables
```

2022-07-12 10:22 UTC, lloyddewit requested changes

2022-07-12 10:22 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +          new_data <- tidyr::as_tibble(unlist(data), rownames = "rowname")
```suggestion
	     # if there are nested lists, the "rowname" variable combines the different lists together.
	     # We want to separate these into separate variables to make the data more usable and readable.
	     # We do this by `str_split_fixed`, and `gsub`.
          new_data <- tidyr::as_tibble(unlist(data), rownames = "rowname")
```

2022-07-12 10:23 UTC, lloyddewit approved these changes

2022-07-12 10:24 UTC, merged