Adding the random split dialog to form main
africanmathsinitiative/R-Instat pull request #7470
Opened 2022-05-15 09:33 UTC by mmulahvictor

I have added the new Random Split dialog to the form main.

This PR is replacing #7376 

@shadrackkibet and @lloyddewit can you merge this for @rdstern to review PR https://github.com/africanmathsinitiative/R-Instat/pull/7272.

2022-05-16 10:27 UTC, lloyddewit requested changes
Thanks, this looks good.
The only issue is the `.RHistory` file. I don't think that this should be in this PR, please could you remove it?

2022-05-16 10:29 UTC, lloyddewit commented
@rdstern This PR should open an empty dialog. Please could you check that the menus and tool strip are as you expect? We can then merge, and you can then test PR #7272 properly.
Thanks!

2022-05-16 12:28 UTC, lloyddewit requested changes

2022-05-16 12:28 UTC, lloyddewit commented on instat/frmMain.Designer.vb
> +        Me.ucrDataViewer.grdCurrSheet = Nothing
This line triggers a build error

![image](https://user-images.githubusercontent.com/57253949/168591319-a2158634-4f4b-43e3-9bb3-30876e3639a0.png)

2022-05-16 12:28 UTC, lloyddewit commented on instat/frmMain.Designer.vb
> +        Me.mnuPrepareDataReshapeRandomSplit.Text = "Random Split..."
If the user selects clicks this menu option, then it will open an empty dialog box.
This is probably OK because we expect the real dialog to be added before the next release.
However, we should normally only merge 'releasable' chenges to the main branch.
In this PR, please could you set this menu option's visible attribute to false so that the user cannot see it?
When you merge these changes into PR #7272 , you can set 'visible' back to True.

2022-05-16 14:16 UTC, rdstern commented
@lloyddewit sounds good

2022-05-17 05:56 UTC, mmulahvictor commented
@lloyddewit can you see if it is working correctly now?

2022-05-17 07:45 UTC, lloyddewit approved these changes
@mmulahvictor Thank you, this is good.
I noticed that you set 'enabled' to false. It's probably slightly cleaner to set 'visible' to false instead but this isn't so important.
I'm happy to approve and merge.

2022-05-17 07:45 UTC, merged