Combined the three plot options buttons in Climatic Maps
africanmathsinitiative/R-Instat pull request #7481
Opened 2022-05-18 07:37 UTC by N-thony

Fixes #7472
@africanmathsinitiative/developers this is ready for review.
@rdstern @lilyclements could you test this?

2022-05-18 09:35 UTC, lilyclements commented on instat/dlgClimaticStationMaps.vb
> +    Private Sub cmdPlotOptions_Click(sender As Object, e As EventArgs)
Out of interest, now that these do not have the "Handles ...", what does this Sub do?

2022-05-18 09:35 UTC, lilyclements commented on instat/dlgClimaticStationMaps.vb
> +    Private Sub cmdPlotOptions_Click(sender As Object, e As EventArgs)
And the other cmd*Options_Click subs

2022-05-18 09:47 UTC, lloyddewit requested changes

2022-05-18 09:47 UTC, lloyddewit commented on instat/dlgClimaticStationMaps.vb
> +    Private Sub cmdPlotOptions_Click(sender As Object, e As EventArgs)
If this function does not handle any event(s), then it will never be called.
Delete this function?

2022-05-18 09:47 UTC, lloyddewit commented on instat/dlgClimaticStationMaps.vb
> +    Private Sub cmdSFOptions_Click(sender As Object, e As EventArgs)
If this function does not handle any event(s), then it will never be called.
Delete this function?

2022-05-18 09:47 UTC, lloyddewit commented on instat/dlgClimaticStationMaps.vb
> +    Private Sub cmdMapOptions_Click(sender As Object, e As EventArgs)
If this function does not handle any event(s), then it will never be called.
Delete this function?

2022-05-18 12:11 UTC, N-thony commented
> @lilyclements I think we reviewed in parallel and came up with the same comment! @N-thony Sorry for any confusion

@lloyddewit @lilyclements I resolved your comments? :)

2022-05-18 12:40 UTC, lloyddewit commented
> > @lilyclements I think we reviewed in parallel and came up with the same comment! @N-thony Sorry for any confusion
> 
> @lloyddewit @lilyclements I resolved your comments? :)

@N-thony please can you also resolve my first comment (`cmdPlotOptions_Click()`)? thanks

2022-05-18 13:51 UTC, N-thony commented
> > > @lilyclements I think we reviewed in parallel and came up with the same comment! @N-thony Sorry for any confusion
> > 
> > 
> > @lloyddewit @lilyclements I resolved your comments? :)
> 
> @N-thony please can you also resolve my first comment (`cmdPlotOptions_Click()`)? thanks

@lloyddewit I resolved your last comment.

2022-05-18 17:12 UTC, lloyddewit approved these changes

2022-05-18 17:12 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-05-19 10:38 UTC, rdstern approved these changes
@N-thony very nice.  Much neater than before.  And good that you also fixed the other bug at the same time, so it goes to the label option now.

2022-05-25 08:13 UTC, N-thony commented
@shadrackkibet can you test/merge this?

2022-05-25 08:18 UTC, shadrackkibet commented
I don't think I have privileges to merge PRs again. I think the process of merging PRs might have changed?

2022-05-25 08:20 UTC, N-thony commented
> I don't think I have privileges to merge PRs again. I think the process of merging PRs might have changed?

Okay, I will check with @ChrisMarsh82, thanks.

2022-05-25 10:24 UTC, merged