Bug fixed: File > Close Data Book
africanmathsinitiative/R-Instat pull request #7482
Opened 2022-05-18 13:53 UTC by N-thony

Fixes #7475
@lloyddewit as discussed this bug was due to the fact the check when closing the databook was not done correctly, please take a look.
@africanmathsinitiative/developers this is ready for review.

2022-05-18 17:33 UTC, lloyddewit requested changes

2022-05-18 17:33 UTC, lloyddewit commented on instat/frmMain.vb
> +    Public Property bDataSaved As Boolean
In VB dotnet, the default value for a boolean is False. 
Removing the assignment does not change the behaviour but it makes the code less readable.
Undo this change?

2022-05-18 17:33 UTC, lloyddewit commented on instat/frmMain.vb
>          End If
Is something like this more readable?

```suggestion
        If ucrDataViewer.GetWorkSheetCount() <= 0 Then
            Exit Sub
        End If

        If Not bDataSaved _
                AndAlso DialogResult.No = MsgBox("Are you sure you want to close your data?" &
                                    Environment.NewLine & "Any unsaved changes will be lost.",
                                    MessageBoxButtons.YesNo, "Close Data") Then
            Exit Sub
        End If

        clsRLink.CloseData()
```

2022-05-19 07:18 UTC, N-thony commented
Thanks @lloyddewit, I resolved your comment.

2022-05-19 09:13 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-05-20 05:50 UTC, rdstern requested changes
@N-thony it now works - but perhaps too well!
The previous Close - when it worked - also gave the message:
![image](https://user-images.githubusercontent.com/11226469/169459382-e9a4d6ff-a764-4e6e-a5fa-a46b968883cd.png)

Now it seems to close fine, but without the message.  I rather liked the warning we had before.

2022-05-20 06:13 UTC, N-thony commented
> @N-thony it now works - but perhaps too well! The previous Close - when it worked - also gave the message: ![image](https://user-images.githubusercontent.com/11226469/169459382-e9a4d6ff-a764-4e6e-a5fa-a46b968883cd.png)
> 
> Now it seems to close fine, but without the message. I rather liked the warning we had before.

@rdstern the message is still there but only when the data are not saved, otherwise it will close without a message.
Do we still need to give a message even if the data are already saved and there is no changes?

2022-05-20 06:29 UTC, rdstern approved these changes
Good response @N-thony and you are correct!  Well done.  That's better!

2022-05-29 08:51 UTC, merged