Converted output produced to character or numeric in correlation dialog
africanmathsinitiative/R-Instat pull request #7500
Opened 2022-05-24 12:18 UTC by Vitalis95

Fixes #7430 
@rdstern @lilyclements @Ivanluv 
This PR converts the output produced to either character or numeric depending on the value you input on `Display on Diagonal`  control.

2022-05-25 06:58 UTC, N-thony requested changes
@Vitalis95 great, just a small comment.

2022-05-25 06:58 UTC, N-thony commented on instat/dlgCorrelation.vb
> +        dctNaPrint.Add("blank", Chr(34) & "" & Chr(34))
dctNaPrint.Add("blank", Chr(34) & Chr(34))?

2022-05-25 07:23 UTC, Vitalis95 commented
@N-thony its ok now.

2022-05-25 07:24 UTC, N-thony approved these changes
Great

2022-05-28 10:47 UTC, shadrackkibet requested changes

2022-05-28 10:47 UTC, shadrackkibet commented on instat/dlgCorrelation.vb
>          clsFashionDataFrameFunction.AddParameter("na_print", Chr(34) & " " & Chr(34), iPosition:=3)
Why do you need the same R command repeated? This code is clearly not [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

2022-05-28 10:58 UTC, shadrackkibet requested changes
1) Empty space. Consider increasing the size of the dialog when the checkbox is checked and reducing otherwise.
![image](https://user-images.githubusercontent.com/26301973/170822352-f4af17ae-355a-4f0c-a9c4-b7ec8ae2ad3c.png)
2) Tab order

2022-05-28 10:58 UTC, shadrackkibet commented on instat/dlgCorrelation.vb
> +        clsDataFramePipeOperator.AddParameter("right", clsRFunctionParameter:=clsMutateFunction, iPosition:=1)
Same case here! the left and right of this operator are the same!

2022-05-31 12:02 UTC, Vitalis95 commented
@rdstern @shadrackkibet , I have made the changes with @Ivanluv

2022-06-02 09:58 UTC, rdstern requested changes
Excellent.  This seems to work well.
A very minor concern, is that, when expanded, the dialogue is quite long, and I worry slightly that this might be a problem on some machines with lower resolution.
I suggest moving the display options checkbox up a bit, and also reducing the distance down to the group-box labelled Display Options.

Then this is a good improvement to merge.

2022-06-07 08:59 UTC, rdstern approved these changes
Please can @shadrackkibet comment on this now and give the second approval.  I am approving, because the size of the dialogue is now ok.  The confusion on the data frame and the correlation object still exists, though we now correctly have all 3.  But the bottom checkbox says Name for Data Frame, and really means (also) the name of the correlation object.

2022-06-08 08:21 UTC, merged