Changes to PICSA Rainfall Graph.
africanmathsinitiative/R-Instat pull request #7505
Opened 2022-05-27 08:35 UTC by derekagorhom

Fixes Issue #7498 

Making changes in PICSA rainfall Graph, I went ahead with the first option, i.e 
Keep the PICSA Options as it is. So the 2 buttons remain. Also put the Down arrow on the Plot Options, and include Plot Options Line Options, Point Options there.

@N-thony @rdstern this PR is ready for review.

2022-05-29 10:31 UTC, lloyddewit commented
@Ivanluv Please could you peer review? thanks

2022-05-30 08:56 UTC, rdstern requested changes
Good start.
a) The main Plot options doesn't work now.  When using the main button it should be the same as the down arrow and Plot Options.
b) The Point options, gives line Options and not points.

2022-05-31 11:58 UTC, derekagorhom commented
Hello @rdstern, I have made the changes requested could you re-test again.

2022-06-02 08:50 UTC, rdstern approved these changes
looks good now

2022-06-02 09:09 UTC, Ivanluv submitted a review, later dismissed

2022-06-03 07:53 UTC, lloyddewit requested changes

2022-06-03 07:53 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +    Private Sub toolStripMenuItemPointOption_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemPointOption.Click
what's the difference between this sub and `toolStripMenuItemLineOptions_Click()`?
Remove duplication?

2022-06-03 07:55 UTC, lloyddewit commented
@derekagorhom Thank you for the changes. 
Please do not have lines of code that are more than 100 columns wide (it's bad for readability). I added line breaks. Please check that they are OK.
I also have one open comment above.
Thanks

2022-06-03 08:26 UTC, derekagorhom commented on instat/dlgPICSARainfall.vb
> +    Private Sub toolStripMenuItemPointOption_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemPointOption.Click
Sorry these are not duplicates, one is for the line option and the other is for the Point option.

2022-06-03 08:34 UTC, derekagorhom commented on instat/dlgPICSARainfall.vb
> +    Private Sub toolStripMenuItemPointOption_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemPointOption.Click
@lloyddewit the difference lies in the `sdgLayerOptions.SetupLayer`, the `LineOptions` has `clsNewGeomFunc:=clsGeomLine`
while the` PointOptions` has `clsNewGeomFunc:=clsPointsFunc`

2022-06-03 08:35 UTC, derekagorhom commented
> @derekagorhom Thank you for the changes. Please do not have lines of code that are more than 100 columns wide (it's bad for readability). I added line breaks. Please check that they are OK. I also have one open comment above. If we can resolve this, then I think we can merge. Thanks

duly noted

2022-06-03 09:47 UTC, derekagorhom commented
@lloyddewit i have made the changes requested, can you review again?

2022-06-03 13:27 UTC, lloyddewit requested changes

2022-06-03 13:27 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +
```suggestion
```

2022-06-03 13:27 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +        TestOkEnabled()
```suggestion
     openSdgLayerOptions(clsPointsFunc)
```

2022-06-03 13:27 UTC, lloyddewit commented on instat/dlgPICSARainfall.vb
> +    Private Sub toolStripMenuItemPointOption_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemPointOption.Click
Can we call `openSdgLayerOptions()` here also? 
(see comment below)

2022-06-03 13:35 UTC, derekagorhom commented
@lloyddewit i tried using `openSdgLayerOptions()` for the Point (I changed the `clsGeomLine` to `clsPointsFunc` i ended up with lots of errors and that's where the problem with the commits started

2022-06-03 13:45 UTC, lloyddewit submitted a review, later dismissed
@rdstern If you can test/approve again, then we can merge, thanks

2022-06-04 08:44 UTC, rdstern requested changes
It is a detail, but I wonder if something can be done about this "feature".  I tried the Line option and found this:
![image](https://user-images.githubusercontent.com/11226469/171991637-80cd9818-164a-4d31-bb6c-689ad07d6310.png)

The x was included, but not the y.  When I returned to the main dialogue, the y was now unset.  It had been set before, with the variable sumrain:
![image](https://user-images.githubusercontent.com/11226469/171991705-5f3917eb-4227-4f4a-a759-9d87d5651c4e.png)

I tried also with the Dodoma data from the library, and the problem is the same.

2022-06-06 11:26 UTC, derekagorhom commented
@rdstern i have made some changes to the dialogue and the sub dialogues. could you Re-test

2022-06-06 11:40 UTC, rdstern approved these changes
Great.  Well done.

2022-06-07 07:34 UTC, lloyddewit approved these changes

2022-06-07 07:36 UTC, merged