Added missing Geoms in the plot options sub dialogue. Climatic>Mapping>Map.
africanmathsinitiative/R-Instat pull request #7506
Opened 2022-05-27 14:25 UTC by EstherNjeriLiberatta

Fixes #7494 
@rdstern @africanmathsinitiative/developers This is ready for review.

2022-05-27 14:50 UTC, rdstern commented
@EstherNjeriLiberatta very well done, that looks great.
I was surprised, though, in the order of the layers.  It had the labels first, then the points and third was the sf.  I expected them to be the other way round.
Then I tried changing the label size to 0.3 and that gave me the following error, see below.  I wonder if that is because of the ordering of the layers?
![image](https://user-images.githubusercontent.com/11226469/170723688-d3e4c2be-4769-483a-810d-618b81710e65.png)

2022-06-02 08:25 UTC, N-thony commented
> @EstherNjeriLiberatta very well done, that looks great. I was surprised, though, in the order of the layers. It had the labels first, then the points and third was the sf. I expected them to be the other way round. Then I tried changing the label size to 0.3 and that gave me the following error, see below. I wonder if that is because of the ordering of the layers? ![image](https://user-images.githubusercontent.com/11226469/170723688-d3e4c2be-4769-483a-810d-618b81710e65.png)

@EstherNjeriLiberatta thanks for this, is it ready for review?

2022-06-02 12:14 UTC, EstherNjeriLiberatta commented
@rdstern The error was coming about when you edit into the sub dialogue which was causing the data to be lost in the geom_point or geom_label_repel code. It is now fixed by adding the dataset to the ggplot() function. The order of the geoms is also fixed. This is ready for review.
@N-thony I have fixed the issue, it's now okay. Thanks

2022-06-02 21:18 UTC, rdstern requested changes
@EstherNjeriLiberatta that's good and seems to work fine.
Ideally, the Point Options and Label Repel options would also be included in the drop-down.  
If that is tricky, then we could merge this and consider the extra geoms as an additional issue?

2022-06-03 12:11 UTC, EstherNjeriLiberatta commented
@rdstern I suggest we open another issue on this and merge this one. Thank you

2022-06-03 16:42 UTC, rdstern approved these changes
@EstherNjeriLiberatta that's good and seems to work fine.
Ideally, the Point Options and Label Repel options would also be included in the drop-down.  
If that is tricky, then we could merge this and consider the extra geoms as an additional issue?

After your comment I am approving and perhaps you could make a new issue of the point about adding the remaining geoms into the pull-down.

2022-06-03 18:20 UTC, lloyddewit requested changes

2022-06-03 18:20 UTC, lloyddewit commented on instat/dlgClimaticStationMaps.vb
> -        clsParamOperator.Clear()
Also delete declaration on line 48?

2022-06-03 18:20 UTC, lloyddewit commented on instat/dlgClimaticStationMaps.vb
> +                clsGGplotOperator.RemoveParameterByName("scale_shape_manual")
parameter already removed above. Do we need these lines?

2022-06-04 06:43 UTC, EstherNjeriLiberatta commented
@lloyddewit I have resolved your comments above. Thank you.

2022-06-05 07:29 UTC, lloyddewit approved these changes
@EstherNjeriLiberatta Thank you, looks good

2022-06-05 07:30 UTC, lloyddewit commented
@rdstern Some code changes since your last approval. In theory, the functionality should not be affected. If you can test/reapprove, then we can merge. Thanks

2022-06-05 07:53 UTC, rdstern approved these changes

2022-06-05 08:13 UTC, merged