Reodering DataFrame
africanmathsinitiative/R-Instat pull request #7508
Opened 2022-05-30 09:34 UTC by N-thony

Fixes (partially) #4557 
@shadrackkibet @lilyclements I checked the R code, then I found that on line 128, we were trying to check the obj class type as `data_object` i.e ` if(!is.list(new_data_objects) || (length(new_data_objects) > 0 && !all("data_object" %in% sapply(new_data_objects, class))))` to `if(!is.list(new_data_objects) || (length(new_data_objects) > 0 && !all("DataSheet" %in% sapply(new_data_objects, class))))`, please have a look, if everything is okay, I will then check the reodering in the front end.

2022-05-30 16:10 UTC, shadrackkibet commented
@N-thony  we still need to check for  `data_object` for backward compatibility purposes. Therefore this check should change to something like `!any(c("DataSheet","data_object") %in% sapply(new_data_objects, class))`

2022-05-31 15:11 UTC, N-thony commented
@shadrackkibet @Patowhiz I have managed to update the reordering of the data frame from the front end as it is done in the back-end with the Data Frame MetaData, and fixed some bugs, please take a look.
@rdstern could you test?

2022-06-02 07:39 UTC, N-thony commented
> 

@Patowhiz thanks, I will discuss what I have done here with @ChrisMarsh82 and also about his approach.

2022-06-03 07:50 UTC, rdstern requested changes
@N-thony this looks great and all seems to work.  So the points I make are all cosmetic.
a) The right-click at the bottom of the data frame remains disabled.  It is time now to enable it.  The dialogue works fine and is enabled.
b) When I go in to the dialogue for the first time, it is empty.  No data frames.  Reset doesn't help.  But if I go out, and then back in again, it is fine, and then ok from then onwards.
c) The control is on the left of the dialogue.  The same control for reordering columns is more on the right, because there is another control on the left.  I wonder if the control should be in the same position on the two dialogues.  (But you are better than me on design issues, so you decide on this.)
d) Then the important things seem to work fine - they reorder with no problem, and are correctly changed on the sheet metadata.
e) When finished it always moves to the last dataframe.  That seems to be independent of the last one that was used, or where you started, with this dialogue.  I don't have much of a problem with this, but wonder if it could return to the dat frame where I started?  That will often be the right-click data frame I guess, once that option works.
f) Finally I notice the "obvious" way - used in Excel, still works.  So I can click on a dataframe in reogrid and it changes position there.  But, of course, the metadata hasn't changed.  I am assuming this feature can't be trapped and made to work, and so wonder if it can be disabled?  Maybe that is a @Patowhiz question?

2022-06-03 08:03 UTC, N-thony commented
f) Finally I notice the "obvious" way - used in Excel, still works. So I can click on a dataframe in reogrid and it changes position there. But, of course, the metadata hasn't changed. I am assuming this feature can't be trapped and made to work, and so wonder if it can be disabled? Maybe that is a @Patowhiz question?
@rdstern I think there is an issue #7477 on this, it was reported during the KMD workshop.

2022-06-03 11:06 UTC, Patowhiz commented
@rdstern @N-thony  Like I said before, I think the approach done here needs to be consistent with how data frame metadata changes has been implemented.

Currently, we don't have the mechanism of tracking data book metadata changes at the .Net level. That's where I'd suggest we start with. It's very likely that in future we may want to track other data book metadata changes too. So I'd recommend adding that feature now.

If that's implemented, most of the code changes here may no longer be needed

Thanks.

2022-06-03 11:30 UTC, N-thony commented
> @rdstern @N-thony Like I said before, I think the approach done here needs to be consistent with how data frame metadata changes has been implemented.
> 
> Currently, we don't have the mechanism of tracking data book metadata changes at the .Net level. That's where I'd suggest we start with. It's very likely that in future we may want to track other data book metadata changes too. So I'd recommend adding that feature now.
> 
> If that's implemented, most of the code changes here may no longer be needed
> 
> Thanks.

@Patowhiz this is just what was before but now it is done with Chris structure, we still need to discuss approaches, as you said above, I will discuss that with @ChrisMarsh82 when he will be back.

2022-06-06 09:53 UTC, N-thony commented
> 

I have checked the code, and this is already happening but need some check with @ChrisMarsh82 in `RefreshDataFrames sub` in the `clsDataBook`.

2022-06-07 13:34 UTC, N-thony commented
@ChrisMarsh82 please have a look, thanks.
@rdstern could you re-test?

2022-06-07 15:09 UTC, ChrisMarsh82 commented
@N-thony This looks good from the Reo grid side. Will need to be implemented for Linux grid. It is just tab pages used in the linux grid so you should be able to use something like this https://stackoverflow.com/questions/12001502/how-to-easily-reorder-tabcontrol

2022-06-08 06:12 UTC, Patowhiz commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    End Sub
@N-thony I'm probably missing something, is it true that `bFound` will always be true when after it's set to true once?
Looking at this code I didn't see where it's set back to false.

2022-06-08 06:13 UTC, Patowhiz commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    End Sub
Or may be it doesn't really matter?

2022-06-08 06:18 UTC, Patowhiz commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    End Sub
Then also looking at `ReOrderWorksheets()` subroutine. Does it generally assume that all worksheets are always not in their previous position(order) and therefore attempts to always change all their indexes(positions)? That is,
`grdData.MoveWorksheet(fillWorkSheet, iNewPosition)`
will always be executed even for worksheets that retained their position?

2022-06-08 06:40 UTC, N-thony commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    End Sub
> Then also looking at `ReOrderWorksheets()` subroutine. Does it generally assume that all worksheets are always not in their previous position(order) and therefore attempts to always change all their indexes(positions)? That is, `grdData.MoveWorksheet(fillWorkSheet, iNewPosition)` will always be executed even for worksheets that retained their position?

If the position is still the same then there is no problem, it will retain the same position otherwise it will move it to the specific new position.

2022-06-08 06:42 UTC, N-thony commented
> @N-thony This looks good from the Reo grid side. Will need to be implemented for Linux grid. It is just tab pages used in the linux grid so you should be able to use something like this https://stackoverflow.com/questions/12001502/how-to-easily-reorder-tabcontrol

Thanks for the link, let me find out how to implement it in VB.

2022-06-08 07:30 UTC, Patowhiz commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    End Sub
@N-thony understood.
I'm I correct to state that the ordering implementation here assumes the following;
1. The data book will always have all the data frames even the ones hidden from the user.
2. The grid may not have all the data frame worksheets equivalent, for instance hidden data frames may not be in the in the grid as work sheets.
3. All data frames in the data book are assumed to have changed their order positions

2022-06-08 08:33 UTC, N-thony commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    End Sub
Yes, you are correct.

2022-06-08 10:03 UTC, ChrisMarsh82 approved these changes

2022-06-08 10:17 UTC, Patowhiz commented on instat/Model/DataFrame/clsDataBook.vb
> +        End If
@N-thony according to the way `RefreshDataFrames()` is implemented, at line 155 during runtime, the count of `lstOfCurrentRDataFrameNames` will always be the same as `_lstDataFrames`. I don't think we really need that check.

2022-06-08 10:58 UTC, rdstern approved these changes
Looks fine to me.

2022-06-09 06:57 UTC, Patowhiz commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    End Sub
@N-thony okay.
Below is an alternative implementation that can be adapted to achieve the same. You may choose to ignore it, I have no strong objection.

```
Private Sub ReOrderWorksheets() Implements IGrid.ReOrderWorksheets
        'assuming the databook will always have all the data frames 
        'and the grid may not have all the data frame worksheets equivalent
        'and all data frames in the data book have changed their order positions 
        'get data frames sheets in the grid based on the databook data frames position order
        'and add it to the list.
        Dim lstWorkSheetsFound As New List(Of Worksheet)
        For Each clsDataframe In _clsDataBook.DataFrames
            Dim fillWorkSheet As Worksheet = grdData.GetWorksheetByName(clsDataframe.strName)
            If fillWorkSheet IsNot Nothing Then
                lstWorkSheetsFound.Add(fillWorkSheet)
            End If
        Next
        'then reorder the worksheets based on the filled list
        For i As Integer = 0 To lstWorkSheetsFound.Count - 1
            grdData.MoveWorksheet(lstWorkSheetsFound(i), i)
        Next
    End Sub
```

2022-06-09 09:34 UTC, lloyddewit commented
@N-thony Thanks for this. There are 2 approvals so in theory, we can merge.
However, there is still an open comment above from @Patowhiz related to `ReOrderWorksheets()`. The code he proposes looks more readable to me than the current implementation. If the code works, then would you consider pasting it in?

2022-06-09 09:46 UTC, N-thony commented
> @N-thony Thanks for this. There are 2 approvals so in theory, we can merge. However, there is still an open comment above from @Patowhiz related to `ReOrderWorksheets()`. The code he proposes looks more readable to me than the current implementation. If the code works, then would you consider pasting it in?

@lloyddewit okay, I made the change and fixed the small bug coming from the proposed code, have a look. Thanks.

2022-06-09 10:03 UTC, Patowhiz commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    End Sub
@N-thony just 3 more questions before this is merged, 

1. Why do we need line 90,  `grdData.CurrentWorksheet = lstWorkSheetsFound(i)`? Does moving of worksheets change `grdData.CurrentWorksheet`  property? 
2. When I reorder the worksheet, should the active worksheet, that is,  `grdData.CurrentWorksheet` be changed to the last one?
3. Now that you decided to adapt my code suggestion, do you think it's a good idea to do the same for the data grid view?

Thanks.

2022-06-09 10:10 UTC, N-thony commented
> > @N-thony Thanks for this. There are 2 approvals so in theory, we can merge. However, there is still an open comment above from @Patowhiz related to `ReOrderWorksheets()`. The code he proposes looks more readable to me than the current implementation. If the code works, then would you consider pasting it in?
> 
> @lloyddewit okay, I made the change and fixed the small bug coming from the proposed code, have a look. Thanks.

It looks good the code but this is what you get after running, that why we need `grdData.CurrentWorksheet`
before reordering
![image](https://user-images.githubusercontent.com/68591383/172822480-a3e77599-7fdf-4d67-8b30-01013aacea62.png)
after reordering
![image](https://user-images.githubusercontent.com/68591383/172822550-7bb300d5-bbe9-4e1a-b967-7f3799eadfdd.png)

2022-06-09 10:29 UTC, rdstern submitted a review, later dismissed
I remain happy with the implementation of this feature and it would be good if we can include it in the forthcoming version.
It seems to work fine for me.  I did notice that it leaves you at the last data frame, rather than the one where you started the command.  I am sort of ok with that.

2022-06-09 10:38 UTC, lloyddewit commented
> I remain happy with the implementation of this feature and it would be good if we can include it in the forthcoming version. It seems to work fine for me. I did notice that it leaves you at the last data frame, rather than the one where you started the command. I am sort of ok with that.

@Patowhiz @N-thony It would also be good if @Patowhiz 's remaining comments above could be resolved. Would this be possible by end today (or latest tomorrow)? Or should we go ahead and merge and make a new PR for any further changes?

2022-06-09 10:45 UTC, N-thony commented
> > I remain happy with the implementation of this feature and it would be good if we can include it in the forthcoming version. It seems to work fine for me. I did notice that it leaves you at the last data frame, rather than the one where you started the command. I am sort of ok with that.
> 
> @Patowhiz @N-thony It would also be good if @Patowhiz 's remaining comments above could be resolved. Would this be possible by end today (or latest tomorrow)? Or should we go ahead and merge and make a new PR for any further changes?

@lloyddewit I will make the change if necessary in another PR for point 3), I don't see any problem with 1) and  2)

2022-06-09 11:39 UTC, Patowhiz commented
@rdstern what you noticed and sort of okay with, is what I'm asking @N-thony about.

If I have 5 worksheets and the 2nd is the one active, if I reorder the worksheets. 

1. Which worksheet should be the active one? 
2. Should it be the original one or the last one in the new order?

That one line of code is meant to always have the last worksheet in the new order be active one, that's what you have noticed.
Removing that one line of code retains the original active worksheet. 

I would suggest to retain the original worksheet as the active one. Reason being the user is just reordering data frames not change the active data frame.
@rdstern @N-thony  I'm happy to be convinced otherwise.

2022-06-09 11:46 UTC, N-thony commented
> > @rdstern what you noticed and sort of okay with, is what I'm asking @N-thony about.
> > If I have 5 worksheets and the 2nd is the one active, if I reorder the worksheets.
> > 
> > 1. Which worksheet should be the active one?
> > 2. Should it be the original one or the last one in the new order?
> > 
> > That one line of code is meant to always have the last worksheet in the new order be active one, that's what you have noticed. Removing that one line of code retains the original active worksheet.
> > I would suggest to retain the original worksheet as the active one. Reason being the user is just reordering data frames not change the active data frame. @rdstern @N-thony I'm happy to be convinced otherwise.
> 
> @Patowhiz it is fine, as it is okay at this point with Roger, I'm opening another issue where I will fix that.

@lloyddewit if you are happy with my suggestion, once this is merged, I will open another issue where I will work on that aspect of remaining to current worksheet.

2022-06-09 11:47 UTC, rdstern approved these changes
Agreed with a new issue of keeping the original data frame.

2022-06-09 11:49 UTC, Patowhiz commented
@rdstern @N-thony another test case scenario for you.

Load the climatic_guide_datasets.xlsx from the library the import all the sheets from the excel file.
Select the 3rd work sheet in the data viewer, then go to the calculator dialog, enter "surface", click Ok. 

The last worksheet is the one that becomes active. I think that's not what a user may expect.





 in addition try using 
I have 2 extra objections

2022-06-09 11:51 UTC, N-thony commented
> @rdstern @N-thony another test case scenario for you.
> 
> Load the climatic_guide_datasets.xlsx from the library the import all the sheets from the excel file. Select the 3rd work sheet in the data viewer, then go to the calculator dialog, enter "surface", click Ok.
> 
> The last worksheet is the one that becomes active. I think that's not what a user may expect.

See my comment above,

2022-06-09 12:01 UTC, Patowhiz commented
@rdstern @N-thony then also using the same file with the same number of worksheets(31).

Do the same calculator operation, notice how the grid blinks several times and it's just 31 sheets. This is similar to what we had before with the dialogs. This problem also compounds for very sheets added. Try using 62 sheets.

This is because this function now gets called every single time we have an output from an operation, and it's not just once. So we are always reordering data frames, which I'm objecting because of performance. 

@lloyddewit @N-thony like I said before, I understand getting this right requires several other aspects to be built in, and that may require time.

We can merge this if it's urgently needed by @rdstern for the next release but lets be aware of the problems introduced. If not urgent then I strongly suggest we pause and get it right first.

2022-06-09 12:06 UTC, Patowhiz commented
The other point that I can add. In this implementation, we are also always reordering data frames every time we create a new data frame. After now testing this, I'm convinced that's a future potential performance issue that will force us to refactor this feature.

2022-06-09 18:11 UTC, lloyddewit approved these changes
@N-thony @Patowhiz thanks for both the implementation and review comments.
As discussed in the comments above, I'll merge this PR and @N-thony can adress the potential performance and other concerns in a new issue.

2022-06-09 18:17 UTC, merged