Small improvement in the Prepare > Data Frame > Row Numbers/Names dialogue
africanmathsinitiative/R-Instat pull request #7523
Opened 2022-06-03 13:55 UTC by Ivanluv

fixes #7513
@africanmathsinitiative/developers this is ready for review

2022-06-03 18:26 UTC, lloyddewit requested changes

2022-06-03 18:26 UTC, lloyddewit commented on instat/dlgRownamesOrNumbers.vb
> +    Private clsSetRowNames As New RFunction
```suggestion
    Private clsSetRowNamesFunction As New RFunction
```

2022-06-03 18:27 UTC, lloyddewit commented
@rdstern please could you test? thanks

2022-06-04 08:24 UTC, rdstern approved these changes
Looks fine now

2022-06-05 07:43 UTC, merged