Minor improvement to the column meta data
africanmathsinitiative/R-Instat pull request #7526
Opened 2022-06-06 08:23 UTC by N-thony

Fixes #7477 
@rdstern I have made the improvement to the column meta data to change to the current data frame when the current data frame has changed from data view. Please have a look. Thanks
@africanmathsinitiative/developers this is ready for review.

2022-06-06 08:45 UTC, lloyddewit requested changes

2022-06-06 08:45 UTC, lloyddewit commented on instat/frmMain.vb
> +
Remove (see comment below)?
```suggestion
```

2022-06-06 08:45 UTC, lloyddewit commented on instat/ucrDataView.vb
> +        frmMain.UpCurrentColumnMetaDataFrame(_grid.CurrentWorksheet.Name)
`frmMain.ucrColumnMeta` is public. Would it be simpler just to call like this?
```suggestion
        frmMain.ucrColumnMeta.SetCurrentDataFrame(_grid.CurrentWorksheet.Name)
```

2022-06-06 08:50 UTC, N-thony commented on instat/ucrDataView.vb
> +        frmMain.UpCurrentColumnMetaDataFrame(_grid.CurrentWorksheet.Name)
@lloyddewit this is resolved, thanks.

2022-06-06 08:55 UTC, lloyddewit approved these changes
@N-thony Thanks, looks good

2022-06-06 08:56 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-06-06 09:42 UTC, rdstern approved these changes
@N-thony great.  I am also very happy that these are changes proposed by other than me.  Also they are relatively small, but add to the convenience, and that is important for R-Instat.  Our catch-phrase is "making it easy" and this sort of thing helps!

2022-06-06 10:29 UTC, merged

2022-06-08 11:22 UTC, N-thony commented
@lloyddewit I have tried to test this with Linux version unfornately I was getting the following bug, I have fixed it in PR #7537
![image](https://user-images.githubusercontent.com/68591383/172604105-72050cd7-3f00-4edd-bf00-355c3692b23a.png)