Implemented the PICSA Temperature and General dialogue
africanmathsinitiative/R-Instat pull request #7564
Opened 2022-06-16 12:55 UTC by Vitalis95

Fixes #7499 
@rdstern, @N-thony , @lloyddewit ,  in this PR  I have added Fitted Line and se to Temperature graph  and General graph sub-menus 
I have also added  extra tab for  labelling the slope of the fitted line  i,e Regression equation and significance level

2022-06-16 15:47 UTC, rdstern commented
@Vitalis95 this is already excellent.
a) The default used be with points, i.e. that option was ticked.  I think it gives the points now, but it starts unticked.  Could you check this?
b) At the top left it always says `PICSA Rainfall Graphs`.  Could it say PICSA Temperature Graphs for the Temperatures and PICSA General Graphs for the General.  Can it also say that in the Last dialogues?
c) Could you reduce the vertical space a little from the data selector, to the PICSA Options and also between the 2 buttons, i.e.  to the Plot options.
d) In the Slope Tab, make it `Slopes `instead.
e) Change the label Significance Level to `Correlation (plus p value)`
f) Add a Position label for each, with your positions Top Left and Bottom Left as the defaults, but the option to choose another corner.
g) It is probably already worth merging then, but we will also have to start thinking a bit harder!

2022-06-17 14:16 UTC, Vitalis95 commented
@rdstern , I have added the labels and also changed the name at top for the dialogs
Have a look at it

2022-06-17 22:08 UTC, rdstern requested changes
@Vitalis95 this is looking really good.  My only problem is that the position of the regression line (at least) seems very disobedient!  I can't get it to the top whatever I try.  I need to get rid of the label.y = 100 to do that.  And when I choose right it is too far to the right.  I wonder what can be done simply?

2022-06-20 06:47 UTC, Vitalis95 commented
@rdstern , I have sorted out the issue when you choose right it is not too far to the right. 
For the label.y=100 this means at 100th unit in the y axis, regression line equation will be shown, if you change it to 1200, it will be shown there. If you change the position to top,  you will not get to the top because you have specified(label.y = 100). I have removed that parameter.

2022-06-23 07:15 UTC, rdstern approved these changes
Great.  I hope this could even be merged and added to the released version if ok?  It would be very useful for PICSA training in Zimbabwe next week, and then particularly in the India workshop in early July.  Perhaps this is @dannyparsons or @ChrisMarsh82 to check first.

2022-06-23 11:42 UTC, Vitalis95 commented on instat/sdgPICSARainfallGraph.vb
> +        dctLegendXPosition.Add("Center", Chr(34) & "center" & Chr(34))
@lloyddewit , they are in the function as shown below. I added both of them

![image](https://user-images.githubusercontent.com/89011415/175289670-563c932a-3a16-4cd8-b5b5-f15a4859063a.png)

2022-06-23 11:44 UTC, Vitalis95 commented
@lloyddewit , have a look at it again. Thanks

2022-06-24 08:31 UTC, lloyddewit commented on instat/sdgPICSARainfallGraph.vb
> +        dctLegendXPosition.Add("Center", Chr(34) & "center" & Chr(34))
@Vitalis95 Thanks for the extra info.
I assume that 'center' and 'centre' are allowed so that developers don't get an error if they type the US or UK spelling.
In R-Instat, I understand that the user will select from a drop-down so cannot enter an unsupported spelling. If the user see's both 'center' and 'centre' in the list, then they may get confused. Would it be simpler just to use one of the spellings?
I'll go ahead and approve anyway. If @rdstern approves, then we can merge.

@rdstern Are you OK with the above? Does R-Instat generally use UK or US spellings?

2022-06-24 08:32 UTC, lloyddewit approved these changes

2022-06-24 08:32 UTC, lloyddewit commented
@rdstern If you can retest/approve, then we can merge, thanks

2022-06-25 19:25 UTC, rdstern approved these changes
So much better than the one we are using in 7.6.

2022-06-26 07:53 UTC, merged