Updated Box Plot dialogue's Plot Options to the new system.
africanmathsinitiative/R-Instat pull request #7570
Opened 2022-06-27 09:53 UTC by EstherNjeriLiberatta

Partially fixes #7556
In this PR, I have replaced the `Box Options` button in the Box plot dialogue with the current `Plot Options` button which includes a drop-down.
@rdstern @africanmathsinitiative/developers  This is ready for review.

2022-07-01 08:47 UTC, rdstern reviewed
@N-thony this is great.  I have 2 small cosmetic points - but please only if you agree.  I am not so good on these aspects.
I wonder if the width of the Options button should be the same as the width of the selector?  And aligned with it.
Could there be a horizontal line below the first entry?#

What do you think.  This would apply to each of them.  

It does make the dialogue look simpler, which is a good thing.

2022-07-02 08:48 UTC, N-thony commented
> @N-thony this is great. I have 2 small cosmetic points - but please only if you agree. I am not so good on these aspects. I wonder if the width of the Options button should be the same as the width of the selector? And aligned with it. Could there be a horizontal line below the first entry?#
> 
> What do you think. This would apply to each of them.
> 
> It does make the dialogue look simpler, which is a good thing.

@rdstern I agrre with you, @EstherNjeriLiberatta please, could you make these changes?

2022-07-13 15:13 UTC, rdstern commented
@EstherNjeriLiberatta please check the horizontal line for yourself, as it may not be needed.  One example is Model > Fit Model > One Variable - the Test button and the button that says Binomial.  But looking at that, I am not sure whether a line is needed, given there are far fewer entries.

2022-07-13 15:46 UTC, EstherNjeriLiberatta commented
@rdstern  Thank you I have checked it, and I agree with you. The dialogue is ready for review.

2022-07-14 17:43 UTC, rdstern requested changes
@EstherNjeriLiberatta it is doing more than I thought - but also therefore sometimes less!
When I am on boxplot, then I can get the ordinary plot options and boxplot options.  I can press violin, but I still get the boxplot options.  If I check tufte, then I get tufteboxplots.
I was thinking that I might get what I press, even though it isn't sensible.  I am happy that I can't, but is it possible to disable the ones that I can't get?
If I am on boxplot (or tufte), or violin, then I can check the points and this adds the jitter layer.  But I can't get it.  I should be able to.

2022-07-20 13:37 UTC, EstherNjeriLiberatta commented
@rdstern I have disabled the options that are not needed when you click on either button box/Tufte, jitter, or violin. It's possible to get the jitter layer when you check the Add points however only on the plot options.

2022-07-30 15:06 UTC, rdstern requested changes
@EstherNjeriLiberatta that has been ambitious, to just have those enabled, that relate to the options chosen.  It is working well, except that the boxplot and violin plots allow points to be added.  When that checkbox is used, it is adding a jitter plot, so that option should then be enabled.

2022-08-01 13:22 UTC, EstherNjeriLiberatta commented
@rdstern This is ready for review. Thank you.

2022-08-16 08:52 UTC, EstherNjeriLiberatta commented
@N-thony Kindly review the changes. Thank you

2022-08-29 11:30 UTC, N-thony requested changes

2022-08-29 11:30 UTC, N-thony commented on instat/dlgBoxPlot.vb
>          End If
Do you still need this?

2022-08-29 11:30 UTC, N-thony commented on instat/dlgBoxPlot.vb
>          End If
Same here too, do you need these if blocks since they don't have code inside

2022-08-29 11:30 UTC, N-thony commented on instat/dlgBoxPlot.vb
> +        End If
here too

2022-09-09 10:25 UTC, EstherNjeriLiberatta commented
@N-thony Thank you for reviewing. I have made the changes you requested.

2022-10-31 05:57 UTC, N-thony approved these changes
Great, @rdstern over to you

2022-10-31 11:38 UTC, lloyddewit requested changes

2022-10-31 11:38 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +        clsBaseOperator.AddParameter(strFirstParameterName, clsRFunctionParameter:=clsCurrGeomFunction, iPosition:=2)
The reason we need this line is because `clsCurrGeomFunction` is a reference. On lines 327, 333 etc. we change `clsCurrGeomFunction` to reference a different object. However the `clsBaseOperator` parameter still references the previous object.
Line 347 solves this by resetting the parameter to the new object referenced by `clsCurrGeomFunction`.
To make the code easier to understand, we could delete this block and set the `clsBaseOperator` parameter explicitly just after lines 327, 333, 338 and 342, for example
```
               clsCurrGeomFunction = clsTufteBoxplotFunction
               lsBaseOperator.AddParameter(strFirstParameterName, clsRFunctionParameter:=clsTufteBoxplotFunction, iPosition:=2)
``` 
What do you think?
(I hope this makes sense, if not, then let me know)

2022-10-31 11:38 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +                'Warning: what if someone used the name value for one of it's variables independently from the multiple variables method ? Here if the receiver is actually in single mode, the variabl
Also ensure comment does not exceed 100 columns.
```suggestion
                'In the y case, the value stored in the clsRaesFunction in the multiplevariables case is "value", however that one shouldn't be written in the multiple variables receiver (otherwise it would stack all variables and the stack ("value") itself!).
                'Warning: what if someone used the name value for one of it's variables independently from the multiple variables method ? Here if the receiver is actually in single mode, the variable "value" will still be given back, which throws the problem back to the creation of "value" in the multiple receiver case.

```

2022-10-31 11:38 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +        'Question to be discussed: After running through the sdgLayerOptions, the clsCurrDataFrame parameters seem to have been cleared, such that in the multiple variable case, clsCurrDataFrame need
Also ensure comment does not exceed 100 columns
```suggestion
        'TODO: After running through the sdgLayerOptions, the clsCurrDataFrame parameters seem to have been cleared, such that in the multiple variable case, clsCurrDataFrame needs to be repopulated with "stack", "measure.vars" and "id.vars" parameters. Actually, even when repopulated, they are still not appearing in the script. ??
```

2022-10-31 11:38 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +        'ucrVariablesAsFactorForBoxplot.SetReceiverStatus()
delete?
```suggestion
```

2022-10-31 11:38 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +    Private Sub toolStripMenuItemBoxOptions_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemBoxOptions.Click
This function is almost the same as the 3 functions that follow.
Is it possible to combine into a single function?
Please see example in `dlgPICSARainfall.vb`.

![image](https://user-images.githubusercontent.com/57253949/198998385-97a0a40c-51ec-4289-9b1c-4e1a47e2e181.png)

2022-10-31 11:38 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +        ElseIf rdoViolin.Checked Then
would this work?
```suggestion
        If rdoBoxplotTufte.Checked OrElse rdoViolin.Checked Then
```

2022-10-31 11:38 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +        toolStripMenuItemTufteOptions.Enabled = (rdoBoxplotTufte.Checked AndAlso ucrChkTufte.Checked)
```suggestion
        toolStripMenuItemTufteOptions.Enabled = rdoBoxplotTufte.Checked AndAlso ucrChkTufte.Checked

```

2022-11-20 22:22 UTC, rdstern requested changes
This is much closer than the other version.

@N-thony please check whether @EstherNjeriLiberatta has the time to do this quickly.  If not, then please re-allocate.

1) Here is the current version in 0.7.7
![image](https://user-images.githubusercontent.com/11226469/202929339-8f5240a8-a620-47bb-8659-ffd005bcb65d.png)
Notice that the new version has lost the Add Points row of controls.
That should be returned.  
And when it is ticked, then also enable Jitter as well as Box, because it is adding a layer
b) Add a Summary option into the pull-down.  When the Groups to Connect is ticked, then stat-summary is enabled.
c) And change Box to Boxplot.

2023-02-14 08:32 UTC, merged