fixed Bug in DataFrameMetadata
africanmathsinitiative/R-Instat pull request #7571
Opened 2022-06-27 11:36 UTC by derekagorhom

Fixes #7568 
This PR is ready for review
@N-thony can you test

2022-06-27 12:17 UTC, N-thony requested changes

2022-06-27 12:17 UTC, N-thony commented on instat/ucrDataFrameMetadata.vb
> +                    strScript = frmMain.clsRLink.strInstatDataObject & "$rename_dataframe(data_name =" & Chr(34) & strPreviousValue & Chr(34) & ", new_val = " & strNewValue & ")"
@derekagorhom great, can you get rid of line 28? I think you don't need it again.

2022-06-27 12:30 UTC, derekagorhom commented on instat/ucrDataFrameMetadata.vb
> +                    strScript = frmMain.clsRLink.strInstatDataObject & "$rename_dataframe(data_name =" & Chr(34) & strPreviousValue & Chr(34) & ", new_val = " & strNewValue & ")"
Done

2022-06-28 05:53 UTC, N-thony commented
> Fixes #7568 This PR is ready for review @N-thony can you test

@Amsale2022 could you test? Thanks.

2022-07-02 09:05 UTC, N-thony approved these changes

2022-07-06 08:14 UTC, lloyddewit approved these changes

2022-07-30 15:28 UTC, rdstern approved these changes

2022-07-31 10:22 UTC, merged