Updated Histogram dialogue's Plot Options to the new system.
africanmathsinitiative/R-Instat pull request #7572
Opened 2022-06-27 13:19 UTC by EstherNjeriLiberatta

Partially fixes #7556
In this PR, I have replaced the` Histogram Options` button in the Histogram plot dialogue with the current `Plot Options` button which includes a drop-down.
@rdstern https://github.com/orgs/africanmathsinitiative/teams/developers This is ready for review.

2022-07-03 14:52 UTC, rdstern requested changes
Apart from the cosmetic changes, the pull-down is ok.
However, all the options lead to geom histogram.  They should each provide their own geom.

2022-07-20 15:15 UTC, EstherNjeriLiberatta commented
@rdstern I have done the cosmetic changes and disabled the other options when you are on a particular button e.g. Histogram. This will display only the geom from that option.

2022-07-30 15:48 UTC, rdstern submitted a review, later dismissed
Looks good

2022-07-31 17:17 UTC, lloyddewit requested changes
Looks good, just a few small suggestions

2022-07-31 17:17 UTC, lloyddewit commented on instat/dlgHistogram.vb
> +                toolStripMenuItemFrequencyPolygonOptions.Enabled = False
simplify? e.g.
```
        toolStripMenuItemHistogramOptions.Enabled = False
        toolStripMenuItemDotOptions.Enabled = False
        toolStripMenuItemDensityOptions.Enabled = False
        toolStripMenuItemDensityRidgesOptions.Enabled = False
        toolStripMenuItemFrequencyPolygonOptions.Enabled = False
        If rdoHistogram.Checked Then
            toolStripMenuItemHistogramOptions.Enabled = True
            If ucrChkDisplayAsDotPlot.Checked Then
                toolStripMenuItemHistogramOptions.Enabled = False
                toolStripMenuItemDotOptions.Enabled = True
```

2022-07-31 17:17 UTC, lloyddewit commented on instat/dlgHistogram.vb
> +                toolStripMenuItemDotOptions.Enabled = False
```suggestion
```

2022-07-31 17:17 UTC, lloyddewit commented on instat/dlgHistogram.vb
> +                toolStripMenuItemFrequencyPolygonOptions.Enabled = False
```suggestion
```

2022-07-31 17:17 UTC, lloyddewit commented on instat/dlgHistogram.vb
> +                    toolStripMenuItemDotOptions.Enabled = False
```suggestion
```

2022-07-31 17:17 UTC, lloyddewit commented on instat/dlgHistogram.vb
> +                    toolStripMenuItemFrequencyPolygonOptions.Enabled = False
```suggestion
```

2022-07-31 17:17 UTC, lloyddewit commented on instat/dlgHistogram.vb
> +                toolStripMenuItemDensityRidgesOptions.Enabled = False
```suggestion
```

2022-08-03 06:49 UTC, lloyddewit commented on instat/dlgHistogram.vb
> +                toolStripMenuItemFrequencyPolygonOptions.Enabled = False
@EstherNjeriLiberatta I changed the code to the following, I hope that's OK:
```
        If rdoHistogram.Checked Then
            toolStripMenuItemHistogramOptions.Enabled = Not ucrChkDisplayAsDotPlot.Checked
            toolStripMenuItemDotOptions.Enabled = ucrChkDisplayAsDotPlot.Checked
            toolStripMenuItemDensityOptions.Enabled = False
            toolStripMenuItemDensityRidgesOptions.Enabled = False
            toolStripMenuItemFrequencyPolygonOptions.Enabled = False
            If ucrChkDisplayAsDotPlot.Checked Then
                clsRgeomPlotFunction.SetRCommand("geom_dotplot")
            Else
                clsRgeomPlotFunction.SetRCommand("geom_histogram")
            End If
```

2022-08-03 07:07 UTC, lloyddewit requested changes
@EstherNjeriLiberatta Thanks for resolving the previous comment, I just have one open question.
Thanks

2022-08-03 07:07 UTC, lloyddewit commented on instat/dlgHistogram.vb
> +            toolStripMenuItemFrequencyPolygonOptions.Enabled = False
I would expect this sub to explicitly set 'enabled' for these 5 controls.
However there are several paths through this sub where some of these 5 controls are not explicitly set. 
For example, enabled for the first 2 controls are only set if `rdoHistogram.Checked` is `True`, otherwise they are left unchanged.
Is that correct?

2022-08-03 07:30 UTC, EstherNjeriLiberatta commented on instat/dlgHistogram.vb
> +            toolStripMenuItemFrequencyPolygonOptions.Enabled = False
@lloyddewit Thank you so much for the corrections, I found a better way to do this which I have applied to the boxplot dialogue. Let me change this too. Thanks again!

2022-08-04 06:48 UTC, lloyddewit approved these changes

2022-08-04 06:54 UTC, lloyddewit commented
@rdstern There have been some changes since your last approval. If you can test/approve again, then we can merge, thanks.

@EstherNjeriLiberatta Thanks for the chat yesterday. I merged your latest changes. If @rdstern wants more changes, then we can discuss how best to solve your git issue.

2022-08-04 07:38 UTC, rdstern approved these changes
Excellent.  I hadn't realised I was making it so hard!

2022-08-04 08:42 UTC, merged