Corrected spacing and Updated Plot Options to new system in Points (Scatter) plot dialogue
africanmathsinitiative/R-Instat pull request #7574
Opened 2022-06-27 14:48 UTC by EstherNjeriLiberatta

Fixes #7573 
Partially fixes #7556
In this PR, I have replaced the` Point Options` button in the Scatter plot dialogue with the current `Plot Options` button which includes a drop-down and made minor design improvements.
@rdstern @africanmathsinitiative/developers This is ready for review.

2022-06-28 05:52 UTC, N-thony commented
> Fixes #7573 Partially fixes #7556 In this PR, I have replaced the` Point Options` button in the Scatter plot dialogue with the current `Plot Options` button which includes a drop-down and made minor design improvements. @rdstern @africanmathsinitiative/developers This is ready for review.

@Amsale2022 please could you test?

2022-07-03 14:18 UTC, rdstern requested changes
a) The spacing has given a problem here.  It now says `Add Line of Best`  and the word `fit ` is no longer showing.  Once corrected, check also there is room for the whole text, once translated into French.  Perhaps the dialogue can't be made so narrow.
b) There is an option of adding a rug plot.  So the plot pull down should add rug plot as well.

2022-07-20 06:17 UTC, N-thony commented
> a) The spacing has given a problem here. It now says `Add Line of Best` and the word `fit ` is no longer showing. Once corrected, check also there is room for the whole text, once translated into French. Perhaps the dialogue can't be made so narrow? b) Ther line of best fit is a geom smooth. So that should be added to the pull-down. The pull-down should include all the options directly from the main dialogue. c) There is an option of adding a rug plot. So the plot pull down should add rug plot as well.

@EstherNjeriLiberatta can you make these changes? Thanks.

2022-08-01 11:55 UTC, EstherNjeriLiberatta commented
@rdstern Please review these changes. I've widened the dialogue to allow the french translation to be seen. The rug and smooth options are now added in the drop-down. Enabled only when their respective check boxes are checked. Thank you.

2022-08-12 06:18 UTC, N-thony commented
> @rdstern Please review these changes. I've widened the dialogue to allow the french translation to be seen. The rug and smooth options are now added in the drop-down. Enabled only when their respective check boxes are checked. Thank you.

@rdstern  please have a look.

2022-08-29 11:23 UTC, N-thony submitted a review, later dismissed

2022-09-02 10:07 UTC, lloyddewit approved these changes

2022-09-02 10:07 UTC, lloyddewit commented on instat/dlgScatterPlot.vb
> +    Private Sub toolStripMenuItemSmoothOptions_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemSmoothOptions.Click
This sub seems very similar to the sub above.
Move code to a private function?

2022-09-02 10:08 UTC, lloyddewit requested changes
I think I approved by mistake, please see my comments above

2022-09-09 10:02 UTC, EstherNjeriLiberatta commented on instat/dlgScatterPlot.vb
> +                'Warning: what if someone used the name value for one of it's variables independently from the multiple variables method ? Here if the receiver is actually in single mode, the variabl
@lloyddewit it is not my comment and I'm not sure about this can you help with rephrasing this?

2022-09-09 10:12 UTC, EstherNjeriLiberatta commented
@lloyddewit Thank you for reviewing. I have made the requested changes.

2022-09-09 14:51 UTC, lloyddewit approved these changes

2022-09-09 14:54 UTC, lloyddewit commented
@EstherNjeriLiberatta I pushed a change to try and improve the readability of the `EnableDisableOptions()` function. This also resolves the open comment above.
Please could you review my change?

@rdstern If you can test/approve, then we can merge

Thanks!

2022-09-10 17:19 UTC, rdstern approved these changes
Excellent

2022-09-12 07:16 UTC, merged

2022-09-12 07:18 UTC, lloyddewit commented
> @EstherNjeriLiberatta I pushed a change to try and improve the readability of the `EnableDisableOptions()` function. This also resolves the open comment above. Please could you review my change?

@EstherNjeriLiberatta I went ahead and merged but if you could find time to review the change, then I'd appreciate. If needed, I can implement any suggestions in a new PR.