Updated HeatMap dialogue's Plot Options to the new system.
africanmathsinitiative/R-Instat pull request #7578
Opened 2022-06-28 13:54 UTC by EstherNjeriLiberatta

Partially fixes #7556
In this PR, I have replaced the `Tile Options` button in the `HeatMap plot` dialogue with the current Plot Options button which includes a drop-down.
@rdstern @africanmathsinitiative/developers  This is ready for review.

2022-07-03 13:58 UTC, rdstern submitted a review, later dismissed
Looks fine, the cosmetic changes apart.  It would be good to merge this, because it will change once the choropleth maps are added.

2022-07-05 07:38 UTC, lloyddewit requested changes
@EstherNjeriLiberatta thanks, looks good, just a couple of small questions

2022-07-05 07:38 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +    Private Sub toolStripMenuItemPlotOptions_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemPlotOptions.Click
Is this function identical to the function above?
If yes, then could the function above also handle the `toolStripMenuItemPlotOptions.Click` event?

2022-07-05 07:38 UTC, lloyddewit commented on instat/dlgHeatMapPlot.vb
> +    Private Sub cmdOptions_Click_1(sender As Object, e As EventArgs) Handles cmdOptions.Click
what's the reason for renaming this sub to `cmdOptions_Click_1`?

2022-07-13 15:57 UTC, EstherNjeriLiberatta commented
@rdstern @lloyddewit thank you for those corrections, I have made the changes you requested. This is ready for review.

2022-07-14 07:30 UTC, lloyddewit commented
@rdstern if you can retest/approve, then we can merge, thanks

2022-07-30 16:01 UTC, rdstern approved these changes
@EstherNjeriLiberatta don't mind this, but it presumably will also change with your choropleth pull request?

2022-08-05 10:00 UTC, EstherNjeriLiberatta commented
@lloyddewit

2022-08-05 10:00 UTC, closed without merging