Ensuring the multiple receiver to clear on reopen when column no longer exists
africanmathsinitiative/R-Instat pull request #7581
Opened 2022-06-29 07:50 UTC by N-thony

Fixes #7577 
@africanmathsinitiative/developers @rdstern @Amsale2022 this is ready for review. Thanks.

2022-06-30 19:41 UTC, Patowhiz commented
@N-thony could you explore getting this information from the .Net databook.
One of the objectives in refactoring current R-Instat implementations is to have very minimal interactions with R especially when loading dialogs. It helps with making R-Instat work optimally with both wide and long datasets.

I understand there may be no structures in place yet for the above functionality. If so and it needs more discussions, I'm happy if a to do comment linking to this PR or issue is added. So that in future once those structures are added we can easily refactor the code added here.
In addition, I have a similar draft PR #7440 that attempts to add some of these structures. It's far from being ready but demonstrates my line of thought.

On a separate note, kindly use a wide data set when testing this addition. To just make sure we don't introduce regression.

2022-07-06 08:03 UTC, lloyddewit submitted a review, later dismissed

2022-07-06 10:07 UTC, N-thony commented
> @N-thony Thank you for the changes, I approved. Regarding @Patowhiz 's comments, do you plan to address these in this PR (i.e. by deleting the column using VB rather than R), or do you prefer to do this in future in a separate PR? If you prefer a separate PR, then please could you raise an issue for this that references this PR (#7581)?
> 
> @rdstern Please could you test?
> 
> Thanks!

@lloyddewit I have opened an issue for the improvement of this, also I did test with a large dataset and it seems to work fine.

2022-07-14 17:25 UTC, rdstern commented
@Patowhiz are you now ok with this one?

2022-07-19 09:26 UTC, rdstern commented
@Patowhiz are you now ok with this change?

2022-07-21 10:02 UTC, Patowhiz commented
@N-thony @lloyddewit @rdstern below is my feedback.

I have tested this PR using poulet dataset in `factoMineR` package. It has 43 rows and 7407 variables. We have it in our library.

The code additions done here will result to a performance regression when it comes to reloading dialogs when working with such similar wide data sets.

The `Add` subroutine, changed here, is called for every variable read from the R script function during `SetRCode`. So if we have 7407 variables in the R script function, the code added here goes back to R, 7407 times. We definitely don't want that.
This is what the selector used to do before we refactored it. 

Also note, the selector already clears the column that doesn't not exist, I wonder if you could explore using it to clear the columns in this receiver. The 2 are already linked anyway, so we just need to improve that linking in away that variable in the receiver are consistent with variable in the selector. 

I understand that route is also not so clear because the current selector and receiver link needs to be refactored too!

2022-11-20 22:03 UTC, rdstern commented
@N-thony given the comments above, what is to be done with this.  Do we just close this pull request for now?

2022-11-24 12:09 UTC, Patowhiz commented
@rdstern @N-thony 
I would suggest to do this in the following steps;

1. Find a way for the specific metadata changes at R level to be detected at .Net level. this could be implemented in a general way, to cover specifc metadata change.
2. Improve the .Net data book metadata implementation. It should contain enough metadata information about the data frame in a way that the controls read from it. 
3. Make the selector and receivers read data from the .Net data book. Refreshing of selectors and receivers will no longer have a huge performance overhead. This will delink the selectors and receivers from R. Which is want we are consistently trying to do!
4. Finally solve the issues outlined here.

@rdstern if we solve the above issues, we can have dialogs be "overlays".

2023-01-11 17:52 UTC, rdstern commented
@N-thony I wonder what should happen here.  I note, from @Patowhiz this links to the topic of wide data sets, and I hope there can be work on their efficient handling soon.  It is now almost a year since Chris and Patrick were of the view that we should be able to cope with data sets of almost any width?

2023-01-12 10:31 UTC, Patowhiz commented
@rdstern as I [commented](https://github.com/africanmathsinitiative/R-Instat/pull/7581#issuecomment-1379267994) above, to do this correctly, we have to refactor the metadata change detection at both .Net and R level. And the receivers should read the  metadata from the .Net data book structures.

2023-01-13 10:42 UTC, lloyddewit commented
@rdstern @Patowhiz @N-thony 

I understand from the comments above, that the solution in this PR will not work well for wide data sets. 

@Patowhiz stated:

> The Add subroutine, changed here, is called for every variable read from the R script function during SetRCode. So if we have 7407 variables in the R script function, the code added here goes back to R, 7407 times. We definitely don't want that. 

On 24 Nov, @Patowhiz suggested doing the work at the dotnet level (see above). This would require deeper architectural understanding and is dependent on other refactorings. We may have to wait a long time for this to be implemented.

As a compromise, could we use the R function that @N-thony developed but ensure that we only call it once (rather than 7407 times)? Could we achieve this by moving the R code out of the `Add()` sub and then calling it just once for the entire list of column names (i.e. set the `col_names` parameter to be a list of columns)? If this approach won't work, is there another approach using R that would work with a single R function call?

If doing this in dotnet is the only fast enough solution, then we may need to close this PR and reassign issue #7594 and issue #7577 .

What are your views?

2023-01-16 07:11 UTC, N-thony commented
> 

@lloyddewit thanks for this, I will try your approach first and let you know how it goes.

2023-01-19 09:36 UTC, N-thony commented
@lloyddewit as discussed I found that we don't need to use R since the selector list will always contains the updated list of variable. As the code need to be refactor as suggested above, this seems to be a temporary solution. Please have a look.
@rdstern you can also test if everything is okay?

2023-01-19 12:00 UTC, lloyddewit requested changes
@N-thony Thank you for coming up with this idea. I find it a simple and pragmatic solution.
Just a few small comments.

2023-01-19 12:21 UTC, N-thony commented on instat/ucrReceiverMultiple.vb
> +    Public Overrides Sub RemoveVariablesInReceiver(lstViewItem As ListView)
I think the name you have proposed is clear, I like it. I added the XML header too.

2023-01-19 12:23 UTC, N-thony commented on instat/ucrReceiver.vb
> +    Public Overridable Sub RemoveVariablesInReceiver(lstViewItem As ListView)
yes, if I delete this sub, we do get the build errors.

2023-01-19 12:27 UTC, N-thony commented
@lloyddewit please take a look, I resolved your comments above.

2023-01-20 10:02 UTC, lloyddewit approved these changes
@N-thony excellent, thanks

2023-01-20 10:03 UTC, lloyddewit commented
@rdstern there are some code changes since your last approval. If you can retest/approve, then we can merge.
Thanks

2023-01-20 10:30 UTC, rdstern approved these changes
Nice

2023-01-20 10:46 UTC, merged

2023-01-20 11:19 UTC, Patowhiz reviewed
@N-thony @lloyddewit many thanks for this.
As a temporary implementation, I agree this will suffice.
I only have a few comments regarding the implementation. See my review.

In addition, @N-thony I think it would have been good if you could add a few comments that mention this PR and it's comments. I tend to think, it's a good to declare all temporary solutions in the comments. 
As @rdstern has mentioned before, it is now becoming critical that we correctly implement working with wide data sets.

Thanks.

2023-01-20 11:19 UTC, Patowhiz commented on instat/ucrReceiverMultiple.vb
> +    Public Overrides Sub RemoveAnyVariablesNotInList(lstViewItem As ListView)
@N-thony @lloyddewit I was expecting to see this implementation done for the single receivers as well. Or did they not need this implementation. The block at the `ucrReceiver` is empty.

2023-01-20 11:19 UTC, Patowhiz commented on instat/ucrReceiver.vb
> +    Public Overridable Sub RemoveAnyVariablesNotInList(lstViewItem As ListView)
@N-thony @lloyddewit It also seems a bit odd to have the list view as a parameter of the `RemoveAnyVariablesNotInList()`, considering all receivers already have link to the selector. We could just use the selector variable define in line 22. In addition, we wouldn't want this function be used to remove variables from any other list view other than the linked selector.

2023-01-23 09:00 UTC, lloyddewit commented
@Patowhiz Thank you for the review, and helpful comments.

> As a temporary implementation, I agree this will suffice.

This solution checks that the variables listed in the receiver currently exist in the selector. I agree that this assumes that the selector lists the correct variables but the receiver already depends on the selector so I think this is a reasonable assumption. For me this PR is a simple and pragmatic solution. Hopefully the receivers will be refactored at one point, but I don't see the solution in this PR as more 'temporary' than other code.

@N-thony The comments above look like good code quality improvements. If you agree they are worth adding, then will you do this in a separate PR?
Thanks for your help and patience

2023-01-23 09:46 UTC, Patowhiz commented on instat/ucrSelector.vb
>          EnableDataOptions(strCurrentType)
In addition, should this happen for all receivers or just the current receiver? If all, then I think the linked receivers are the ones that should listen to selector variables changes and remove the variables they contain but are not in the selector.

2023-01-23 09:47 UTC, Patowhiz commented
@lloyddewit you are correct, it's not more 'temporary' than other code.
Thanks.