Fixed a Minor bug of Y-axis unsetting  itself in PICSA Rainfall dialog
africanmathsinitiative/R-Instat pull request #7612
Opened 2022-07-12 11:36 UTC by Vitalis95

Fixes #7607 
@rdstern @N-thony @lloyddewit  this PR fixes the issue when you set Y-axis  at any point  then it doesn't unset itself when dialogue is used repeatedly

2022-07-12 19:57 UTC, rdstern requested changes
@Vitalis95 this is much better and the control now seems to behave itself when the y-axis is numeric.  But it still goes wrong when using dates.  I will send you the data for the plot below through skype.

It would be excellent if you can fix this too, at the same time?  

To be clear what I did.  I first did plots where y is the sum_rain.  I get the mean line and also set the y-axis to start at zero.  All seems ok now.

Now I change and plot the start_rain.  Now the y-axis is a date, and the default is for the y-axis to start at day 1.  I untick this.  
The graph works fine.
Then I return to the dialogue and the PICSA plot sub-dialogue.  Then I go to the Lines tab.  I don't change anything, but do the plot again.  Now the graphs start on Jan 1.  When I return the the PICSA sub-dialogue I find the y-axis control is ticked and at the default of 1.  I hope you can prevent that?

2022-07-14 08:08 UTC, Vitalis95 commented
@rdstern , can you have a look at it now

2022-07-14 17:23 UTC, rdstern approved these changes
@Vitalis95 excellent.  Looks fine now.  Many thanks.  Hope @lloyddewit likes it so it can be merged.

2022-07-15 06:41 UTC, lloyddewit approved these changes

2022-07-15 06:44 UTC, merged