Fixes translation layout
africanmathsinitiative/R-Instat pull request #7622
Opened 2022-07-15 13:08 UTC by Fidel365

Fixes (partially) #7598 
@N-thony and @derekagorhom this PR is ready for preview 
I fixed point 1 to point 4 of the issue

2022-07-17 07:07 UTC, N-thony commented on instat/dlgImportDataset.vb
> +    End Sub
remove?

2022-07-17 08:30 UTC, Fidel365 commented
@N-thony I have made the changes requested

2022-07-17 11:36 UTC, N-thony commented
> @N-thony I have made the changes requested

@Fidel365 we still the problem of controls overlapping on others in the French version
![image](https://user-images.githubusercontent.com/68591383/179396274-3abb1c85-2fc4-4137-84ed-6923e1ebe505.png)

2022-07-18 16:59 UTC, N-thony commented
> @N-thony and @derekagorhom I have made the changes requested except for number 5 because of the nature of the checkbox

@Fidel365 it looks fine when you try to import a `.csv file`, but not with a `.xlsx or .xls file`. You can try with any excel data file.
![image](https://user-images.githubusercontent.com/68591383/179563870-d96b8f9f-8cf6-4a40-97cb-e69b096103b2.png)

2022-07-19 11:24 UTC, Fidel365 commented
@N-thony  @derekagorhom , I have made the changes in excel too!

2022-07-19 14:49 UTC, Fidel365 commented
@N-thony, okay, am winding up on the other parts

2022-07-20 07:32 UTC, Fidel365 commented
@N-thony , I have fixed the remainder part of the issue!

2022-07-21 11:27 UTC, N-thony commented
> @N-thony , I have fixed the remainder part of the issue!

@Fidel365 same time

1. can you make the first plot width same as the one just below?

![image](https://user-images.githubusercontent.com/68591383/180202215-016023f1-a909-4259-8fc2-0af3aa745713.png)

2.  can you also make the change to this checkbox by increasing the width to 128?
![image](https://user-images.githubusercontent.com/68591383/180202426-7dc5a2cc-d493-48ac-9864-d4e1c79b4f65.png)

3. also in the PICSA option subdialogue, can you increase the width of the checked checkboxes to fit the French?
![image](https://user-images.githubusercontent.com/68591383/180202677-e0ba88ae-4250-4cf0-8442-630840be7942.png)

2022-07-22 07:24 UTC, N-thony commented
![image](https://user-images.githubusercontent.com/68591383/180386346-3c687008-2bca-4141-b324-99fd4f3a44c4.png)

@Fidel365 I'm not able to test this, @rdstern @lloyddewit would you like to test? Thanks.

2022-07-22 07:46 UTC, Fidel365 commented
I'm having the same problem when I try to run it from my side, I think the
errors are coming from dlgImportDataset.Designer, I'll try to fix them

On Fri, Jul 22, 2022, 10:24 N-thony ***@***.***> wrote:

> [image: image]
> <https://user-images.githubusercontent.com/68591383/180386346-3c687008-2bca-4141-b324-99fd4f3a44c4.png>
>
> @Fidel365 <https://github.com/Fidel365> I'm not able to test this,
> @rdstern <https://github.com/rdstern> @lloyddewit
> <https://github.com/lloyddewit> would you like to test? Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/africanmathsinitiative/R-Instat/pull/7622#issuecomment-1192268399>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZU67SFN2NCGRJ4NI32IPHLVVJEDZANCNFSM53VRSWZA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-22 10:38 UTC, Fidel365 commented
@N-thony , I'm done with number 1

2022-07-31 11:45 UTC, N-thony commented
@Fidel365 is this ready for re-review?

2022-08-01 12:02 UTC, Fidel365 commented
@N-thony , it is ready

2022-08-02 15:47 UTC, Fidel365 commented
@N-thony , it's ready for the re-review

2022-08-03 05:44 UTC, N-thony requested changes

2022-08-03 05:44 UTC, N-thony commented on instat/dlgImportDataset.vb
> +    End Sub
remove?

2022-08-03 06:34 UTC, lloyddewit submitted a review, later dismissed

2022-08-03 06:35 UTC, lloyddewit commented
@rdstern If you can test/approve, then we can merge, thanks

2022-08-03 06:35 UTC, lloyddewit commented on instat/dlgImportDataset.vb
> +    End Sub
@N-thony this seems resolved now, so I'll go ahead and ask @rdstern to test

2022-08-03 06:57 UTC, N-thony commented
> @rdstern If you can test/approve, then we can merge, thanks

@Fidel365 is working now on point 3.

2022-08-03 07:20 UTC, N-thony submitted a review, later dismissed

2022-08-03 07:37 UTC, lloyddewit approved these changes

2022-08-06 11:15 UTC, rdstern approved these changes
I am approving, because it looks improved.
![image](https://user-images.githubusercontent.com/11226469/183246505-dada0d08-1d37-467b-b8cf-616cb532e40b.png)

I note one item here not translated, but that may come elsewhere?

2022-08-07 08:20 UTC, merged