Filtering of empty rows
africanmathsinitiative/R-Instat pull request #7629
Opened 2022-07-16 13:24 UTC by shadrackkibet

fixes #6406

@rdstern I added an option "isEmpty" into the dropdown. When you select this option it allows you to click Add Condition then you can select only empty rows. What do you think?
![image](https://user-images.githubusercontent.com/26301973/179356778-4440ffbb-11c5-47c9-ad95-f8f736126da0.png)

2022-07-17 06:04 UTC, rdstern commented
That's an interesting way to do it - and seems to work fine.  I thought we would just enable the `As Condition` button with an empty string, but I am also happy with this solution.  
a) I assume we can name it as we want, so would `is.empty`, rather than `isEmpty` be more consistent with the `is.na`?
b) We should then also add `!is.empty` for the opposite - as we have for `!is.na`.

2022-07-17 11:18 UTC, shadrackkibet commented
@rdstern I agree to the request above and I have actioned it accordingly.

2022-07-17 11:35 UTC, rdstern submitted a review, later dismissed
@shadrackkibet this is great.  Not the way I was thinking, but this way seems better.  And excellent that you are back to R-Instat, even though no longer with INNODEMS.  I hope @lloyddewit can approve, so you can proceed to the useful ADD facility after this is merged!

2022-07-18 06:11 UTC, lloyddewit requested changes

2022-07-18 06:11 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +          }
```suggestion
        } else if (condition[["operation"]] == "is.empty" || condition[["operation"]] == "! is.empty"){
          col_is_empty <- self$get_columns_from_data(condition[["column"]], use_current_filter = FALSE) == ""
          if (condition[["operation"]] == "is.empty") {
            result[, i] <- col_is_empty
          } else {
            result[, i] <- !col_is_empty
          }
```

2022-07-18 06:13 UTC, lloyddewit approved these changes
@shadrackkibet Tidy fix, thanks, happy to approve.
I just fixed a small indentation issue.

2022-07-18 06:16 UTC, merged