Boxplot Options
africanmathsinitiative/R-Instat pull request #7655
Opened 2022-07-26 08:43 UTC by Fidel365

Fixes(partially) #7556 
Procurement>Describe>Numeric>Boxplot
@N-thony , this PR is ready for review

2022-07-27 06:12 UTC, Fidel365 commented
@N-thony , the recent commit fixes minor overlapping issues

2022-07-28 10:21 UTC, lloyddewit commented
@rdstern please could you test? thanks

2022-07-30 18:33 UTC, rdstern commented
@Fidel365 I note this (and some other of your pull requests seem to overlap with those by @EstherNjeriLiberatta .  For this one - boxplots - how do your changes relate to her pull request in #7570 ?

2022-08-01 08:38 UTC, Fidel365 commented
@rdstern , we are working on the same dialogues but from different menus, we are trying to update all dialogues to geom options.e.g The boxplot commit follows the path Climatic>Describe>Boxplot

2022-08-01 08:47 UTC, rdstern commented
@Fidel365 thank you for the clarification.  It was just that at the top of your pull request, you mention the `Procurement menu`.  The boxplot dialogue there is just the same as the main one.  That's unlike the `Climatic > Check Data > Boxplot `that you have now mentioned and that is using a different dialogue - so great that you are adapting that one.  I'll check it now.

2022-08-29 06:11 UTC, N-thony commented
@EstherNjeriLiberatta can you test/review this? Thanks.

2022-09-09 12:06 UTC, EstherNjeriLiberatta requested changes

2022-09-09 12:06 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> -                cmdBoxPlotOptions.Text = "Box Options"
This too

2022-09-09 12:06 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> -            cmdBoxPlotOptions.Text = "Jitter Options"
And this

2022-09-09 12:06 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> -            cmdBoxPlotOptions.Text = "Violin Options"
This one too

2022-09-09 12:06 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> -            cmdBoxPlotOptions.Enabled = True
Here as well

2022-09-09 12:06 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> -            cmdBoxPlotOptions.Enabled = False
And here

2022-09-09 12:06 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +                'Observe that changing the check of the chkVarwidth here doesn't trigger the checkchanged event.
These lines

2022-09-09 12:06 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +            'chkVarwidth.Checked = False
This too

2022-09-09 12:19 UTC, EstherNjeriLiberatta requested changes

2022-09-09 12:19 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +                'cmdBoxPlotOptions.Text = "Tufte Box Options"
You could remove this because it's not needed.

2022-09-09 12:19 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +                'cmdBoxPlotOptions.Text = "Box Options"
This too

2022-09-09 12:19 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +            'cmdBoxPlotOptions.Text = "Jitter Options"
This one too

2022-09-09 12:19 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +            'cmdBoxPlotOptions.Text = "Violin Options"
This one as well

2022-09-09 12:19 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +            'cmdBoxPlotOptions.Enabled = True
Here

2022-09-09 12:19 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +            'cmdBoxPlotOptions.Enabled = False
And here

2022-09-09 12:19 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +                'Observe that changing the check of the chkVarwidth here doesn't trigger the checkchanged event.
These lines?

2022-09-09 12:19 UTC, EstherNjeriLiberatta commented on instat/dlgBoxPlot.vb
> +            'chkVarwidth.Checked = False
This too

2022-09-27 13:38 UTC, N-thony commented
@derekagorhom can you take this over?

2022-09-28 08:24 UTC, derekagorhom commented
> @derekagorhom can you take it over?

@Fidel365 still working on it, i will help him with the corrections

2022-09-30 12:16 UTC, Fidel365 commented
@EstherNjeriLiberatta , this PR is ready for a rereview

2022-10-03 07:49 UTC, lloyddewit commented
> @EstherNjeriLiberatta , this PR is ready for a rereview

@EstherNjeriLiberatta I understand that you're currently working on other projects. I checked the new commit and all your comments above are resolved.
To avoid potential delays, I'm happy to peer review this PR.

2022-10-03 10:54 UTC, Fidel365 commented
@lloyddewit , it's ready for testing

2022-10-04 08:06 UTC, lloyddewit commented
@rdstern Please can you test? thanks

2022-11-20 21:55 UTC, rdstern requested changes
@N-thony it would be good to re-allocate this work now.
1) Please note that the dialogue has now got out-of line - compare the position of the receivers for the Points and the Group option in 0.7.7 and the new one.  I give both below:
![image](https://user-images.githubusercontent.com/11226469/202927862-d603048a-0367-417a-8c07-78913ab50070.png)
And in the new one:
![image](https://user-images.githubusercontent.com/11226469/202927947-d0f51b1d-99ad-4481-9909-95e2ebdf7f67.png)
 The Add Points and Groups to Connect should move back to their original positions.
b) Change Box to Boxplot
c) Add the other options (Tufte, Jitter, Violin) into the pull-down.  Note that the work has been, because when I move to Jitter or Tufte or Violin and press on Box it goes to the right place.
d) I don't mind if they all remain available all the time.  But if you are disabling those that don't apply, then note that you should enable Jitter, (as well as Boxplot) when you Add Points.  
e) Also add Summary when you join the means/medians and go to stat_summary.?

2022-11-20 22:14 UTC, rdstern commented
@N-thony after the above I am closing this one now, and continuing with #7570 .
Please reopen if I have got that wrong.

2022-11-20 22:14 UTC, closed without merging