Layout updates to PICSA menu
africanmathsinitiative/R-Instat pull request #7680
Opened 2022-07-28 22:18 UTC by rachelkg

I made a few small changes to make French text visible.

2022-07-29 06:35 UTC, lloyddewit requested changes

2022-07-29 06:35 UTC, lloyddewit commented on instat/sdgPICSARainfallGraph.vb
> +
```suggestion
```

2022-07-29 06:37 UTC, lloyddewit approved these changes

2022-07-29 06:37 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-07-30 18:37 UTC, rdstern approved these changes

2022-07-31 10:29 UTC, merged