In End of Rains Season dialog, increased capacity default from 1 to 100
africanmathsinitiative/R-Instat pull request #7711
Opened 2022-08-01 10:35 UTC by Fidel365

Fixes #7690 
@N-thony , this PR is ready for review

2022-08-02 05:24 UTC, N-thony commented on instat/dlgEndOfRainsSeason.vb
> +        ucrNudCapacity.SetMinMax(100, Integer.MaxValue)
This now means the minimum will be 100 and we cannot go below. I suggest you keep everything as it was 
and on line 637 change the parameter value to `100`

2022-08-02 06:36 UTC, Fidel365 commented
@N-thony , I have made the changes

2022-08-02 07:47 UTC, N-thony requested changes

2022-08-02 07:47 UTC, N-thony commented on instat/dlgEndOfRainsSeason.vb
> +        clsIfElseRainMaxFunction.AddParameter("yes", iCapacityDefault, iPosition:=100)
I meant clsIfElseRainMaxFunction.AddParameter("yes", "100", iPosition:=0)

2022-08-02 09:58 UTC, Fidel365 commented
@N-thony , this PR is ready for re-review

2022-08-02 18:48 UTC, lloyddewit approved these changes

2022-08-02 18:53 UTC, lloyddewit requested changes

2022-08-02 18:53 UTC, lloyddewit commented on instat/dlgEndOfRainsSeason.vb
> +        clsIfElseRainMaxFunction.AddParameter("yes", "100", iPosition:=0)
is it better to pass an integer rather than a string?
```suggestion
        clsIfElseRainMaxFunction.AddParameter("yes", 100, iPosition:=0)
```

2022-08-03 10:48 UTC, Fidel365 commented
@N-thony , @lloyddewit , this PR is ready

2022-08-04 07:00 UTC, lloyddewit approved these changes

2022-08-04 07:01 UTC, lloyddewit commented
@rdstern @N-thony Please could one of you test/approve? thanks

2022-08-04 07:05 UTC, N-thony approved these changes

2022-08-04 07:31 UTC, rdstern approved these changes

2022-08-04 08:40 UTC, merged