minor change
africanmathsinitiative/R-Instat pull request #7715
Opened 2022-08-02 15:29 UTC by Fidel365

Fixes #7670 
@N-thony , this PR is ready for preview

2022-08-03 05:40 UTC, N-thony commented
> Fixes #7670 @N-thony , this PR is ready for preview

@Fidel365 can you imporve the title of this PR more clear. When you say `minor change` it is not clear what this PR seeks to address.

2022-08-03 05:42 UTC, N-thony requested changes

2022-08-03 05:42 UTC, N-thony commented on instat/dlgClimaticSummary.vb
> -        'ucrReceiverWithinYear.strSelectorHeading = "Factors"
any reason of removing this?

2022-08-03 07:39 UTC, Fidel365 commented
@N-thony , It did not see it's relevance there

2022-08-03 07:42 UTC, N-thony commented
> @N-thony , It did not see it's relevance there

it is needed to give a user an idea from the selector which type of variable is expected to the corresponding receiver. 
So, I suggest that you put it back.

2022-08-03 08:45 UTC, Fidel365 commented
@N-thony , this PR is ready for re-review

2022-08-05 08:51 UTC, EstherNjeriLiberatta commented
> > Fixes #7670 @N-thony , this PR is ready for preview
> 
> @Fidel365 can you improve the title of this PR to make it more clear? When you say `minor change` it is not clear what this PR seeks to address.

@Fidel365 Please make your title clearer as addressed by @N-thony. Which dialogue is this and what minor changes have you made? It's important especially to avoid working on similar dialogs. Thank you.

2022-08-12 06:23 UTC, N-thony commented
> @N-thony , this PR is ready for re-review

@Fidel365 did you resolve my comment above?

2022-08-12 12:08 UTC, Fidel365 commented
@N-thony , I have changed the title of this PR

2022-09-30 18:44 UTC, Fidel365 commented
@N-thony , can you review this?

2022-10-03 06:58 UTC, N-thony requested changes

2022-11-20 21:35 UTC, rdstern submitted a review, later dismissed
@N-thony from my point of view this seems fine now.  If the code is ok, then perhaps @lloyddewit could merge this.

2022-11-22 10:19 UTC, lloyddewit requested changes

2022-11-22 10:19 UTC, lloyddewit commented on instat/dlgClimaticSummary.vb
>          'ucrReceiverWithinYear.strSelectorHeading = "Factors"
```suggestion
```

2022-11-22 10:21 UTC, merged