Correct misleading message in Tools > Install R package dialogue
africanmathsinitiative/R-Instat pull request #7718
Opened 2022-08-03 07:51 UTC by Ivanluv

fixes #7707 
@africanmathsinitiative/developers  this is ready for review

2022-08-03 10:12 UTC, lloyddewit requested changes

2022-08-03 10:12 UTC, lloyddewit commented on instat/dlgRPackages.vb
> +            ucrInputMessage.SetText("Not a current CRAN package. Perhaps it has been archived")
How do we know that this is the reason that the `package_check` command failed? Could it also be an Internet connection error or another reason? Do we need to do some extra checking?

2022-08-04 11:20 UTC, Ivanluv commented on instat/dlgRPackages.vb
> +            ucrInputMessage.SetText("Not a current CRAN package. Perhaps it has been archived")
I have added an internet connection error check and slightly modified the checking function

2022-08-05 06:46 UTC, lloyddewit requested changes
@Ivanluv Thanks for adding the extra messages, I think this is a big improvement.
I added some extra comments

2022-08-05 06:46 UTC, lloyddewit commented on instat/dlgRPackages.vb
>          Else
delete this `Else`?

2022-08-05 06:46 UTC, lloyddewit commented on instat/dlgRPackages.vb
>          If expOutput IsNot Nothing AndAlso Not expOutput.Type = Internals.SymbolicExpressionType.Null Then
There are some conditions below where `ucrInputMessage` is not set to anything.
We should also follow the 'happy path stays left' principle.
Suggested code below, could you think of a better message?
```suggestion
        If expOutput Is Nothing OrElse expOutput.Type = Internals.SymbolicExpressionType.Null Then
            ucrInputMessage.SetText("Cannot get package information.")
            Exit Sub
        End If
```

2022-08-05 06:46 UTC, lloyddewit commented on instat/dlgRPackages.vb
>              If chrOutput.Count >= 1 Then
```suggestion
        If chrOutput.Count < 1 Then
            ucrInputMessage.SetText("<add message here>")
            Exit Sub
        End If                
```

2022-08-05 06:46 UTC, lloyddewit commented on instat/dlgRPackages.vb
> +                If chrOutput(0) = "1" Then
Replace this `If` and `ElseIf` construction with a `Select Case` structure?

2022-08-05 09:07 UTC, Ivanluv commented on instat/dlgRPackages.vb
>          Else
Done

2022-08-05 09:07 UTC, Ivanluv commented on instat/dlgRPackages.vb
>          If expOutput IsNot Nothing AndAlso Not expOutput.Type = Internals.SymbolicExpressionType.Null Then
Done

2022-08-05 09:07 UTC, Ivanluv commented on instat/dlgRPackages.vb
>              If chrOutput.Count >= 1 Then
Done

2022-08-05 09:08 UTC, Ivanluv commented on instat/dlgRPackages.vb
> +                If chrOutput(0) = "1" Then
Done

2022-08-05 09:33 UTC, lloyddewit commented
@Ivanluv I don't see the changes, did you push?

2022-08-08 06:54 UTC, Ivanluv commented
> @Ivanluv I don't see the changes, did you push?

@lloyddewit could you check again

2022-08-09 09:59 UTC, lloyddewit approved these changes

2022-08-09 10:00 UTC, lloyddewit commented
@rdstern please could you test? thanks

2022-09-10 16:53 UTC, rdstern commented
@lloyddewit It now seems to say the following whatever package I use.
![image](https://user-images.githubusercontent.com/11226469/189493531-6d036eaf-4fa2-459f-a138-0dd3c9bcfc5e.png)

So it is now unusable - what's going on here?

2022-09-12 09:45 UTC, rdstern commented
@N-thony I am not sure whether you could take this over, or re-allocate it.

2022-10-24 13:29 UTC, N-thony commented
@rdstern I have tested this and it works for me. What you need before testing this is installing `pingr` package Ivan used here to satisfy the connecting to the internet.
This package should be added in the list of default packages of R-Instat.

2022-10-26 09:26 UTC, lloyddewit commented
> What you need before testing this is installing pingr package Ivan used here to satisfy the connectivity check to the internet. This package should be added in the list of default packages of R-Instat.

@N-thony Please could you add the `pingr` package to R-Instat. An example of doing this is in PR #7557. If you add the `coin` package at the same time, then you can close PR #7719.
Thanks

2022-11-20 21:24 UTC, rdstern approved these changes
I installed the pingr package, and it now works fine.

2022-11-24 11:19 UTC, merged