Fixes translation layout
africanmathsinitiative/R-Instat pull request #7762
Opened 2022-08-11 15:07 UTC by Fidel365

Fixes (partially) #7650 
fixes translation layout in french
Describe>Specific Tables/Graphs>Line/Smooth/Dumbbell/Slope plot....
@N-thony , @rdstern , this PR is ready for review

2022-08-12 06:28 UTC, lloyddewit requested changes

2022-08-12 06:28 UTC, lloyddewit commented on instat/dlgLinePlot.vb
> +    End Sub
Remove empty subs?

2022-08-12 12:10 UTC, Fidel365 commented
@lloyddewit , I have made the changes requested

2022-08-15 07:59 UTC, lloyddewit approved these changes

2022-08-15 07:59 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-08-29 05:40 UTC, N-thony commented
@Fidel365 please align the controls well
![image](https://user-images.githubusercontent.com/68591383/187130407-beba5b1c-24d7-4447-90b3-9e0ff9d61af3.png)
![image](https://user-images.githubusercontent.com/68591383/187130453-14faddb3-0641-4a8c-b52b-8feeba14b7cd.png)
![image](https://user-images.githubusercontent.com/68591383/187130493-4e274138-75f0-4285-a3b7-7f33e11398f4.png)
![image](https://user-images.githubusercontent.com/68591383/187130531-072b62a5-2753-46f2-bce7-92c90921a2b1.png)

2022-10-01 11:35 UTC, Fidel365 commented
@N-thony , I have made the changes requested

2022-10-03 07:00 UTC, N-thony requested changes

2022-10-03 07:00 UTC, N-thony commented on instat/dlgLinePlot.vb
> +    End Sub
can you remove this?

2022-10-03 11:03 UTC, Fidel365 commented
@N-thony , I have made the changes

2022-10-24 11:33 UTC, N-thony commented
@Fidel365 could we have a quick call?

2022-10-25 06:42 UTC, Fidel365 commented
@N-thony , yes offcourse

2022-10-25 07:45 UTC, Fidel365 commented
@N-thony , this PR is ready for rereview

2022-10-31 07:07 UTC, N-thony approved these changes
@rdstern over to you

2022-10-31 09:16 UTC, lloyddewit approved these changes

2022-10-31 09:16 UTC, lloyddewit commented
@rdstern If you can test/approve, then we can merge, thanks

2022-11-01 11:20 UTC, rdstern commented
@Fidel365 this is looking quite good now.  
![image](https://user-images.githubusercontent.com/11226469/199220586-806f07e0-a0f1-443a-bca8-d0d62ce58dbd.png)

I notice the Add SE is just Ajouter.  Perhaps @N-thony can advise if it could become just a bit wider and be Ajouter ES, or es, or we need to have erreur standard?
Then the line Utiliser le chemin ou - I am not sure about, because it remains in French when we click on the Lan button.  I suggest here we change the English and delete the "Use".  So in English it just says Path or Step.  Then it will be wide enough in French.  And we should change it in the radio buttons too.

Maybe this can be done quickly now by @N-thony or @MeSophie?

2022-11-03 11:07 UTC, MeSophie commented
> @Fidel365 this is looking quite good now. ![image](https://user-images.githubusercontent.com/11226469/199220586-806f07e0-a0f1-443a-bca8-d0d62ce58dbd.png)
> 
> I notice the Add SE is just Ajouter. Perhaps @N-thony can advise if it could become just a bit wider and be Ajouter ES, or es, or we need to have erreur standard? Then the line Utiliser le chemin ou - I am not sure about, because it remains in French when we click on the Lan button. I suggest here we change the English and delete the "Use". So in English it just says Path or Step. Then it will be wide enough in French. And we should change it in the radio buttons too.
> 
> Maybe this can be done quickly now by @N-thony or @MeSophie?

@rdstern the modifications that I made are on PR#7951. And also changed **Ajouter SE** to **Ajouter ES** in Crowdin.

2022-11-06 09:36 UTC, lloyddewit commented
@rdstern I approved the 'Ajouter ES' change in CrowdIn. It will be visible when PR #7943 is merged. Are you are ready to approve this PR (PR #7762) based on @MeSophie 's comment above? If so, then we can merge, thanks

2022-11-06 09:46 UTC, rdstern approved these changes
Absolutely!

2022-11-06 10:07 UTC, merged