Enhances the output viewer to display html outputs in windows machines
africanmathsinitiative/R-Instat pull request #7782
Opened 2022-08-17 10:01 UTC by Patowhiz

2022-08-19 11:58 UTC, Patowhiz commented
@rdstern could you try testing this. I'm not sure if the Nuget `CefSharp` libraries will be downloaded automatically.
If they don't I'll have to test this with @lloyddewit first to understand why.
If the packages are not copied directly R-Instat will fall back to using the browser.
kindly let me know

2022-08-23 07:09 UTC, lloyddewit commented
@Patowhiz 
I was able to build this PR.
I checked out the PR branch and it showed lots of red-underlined errors in my open editor windows.
When I started a build, I got a message in the VS status bar that it was restoring NuGet packages. This solved the compilation errors (see below).
![image](https://user-images.githubusercontent.com/57253949/186093022-381cb607-9dcc-4c75-b825-bea4d1004789.png)

When I ran the PR and generated a table, I go the following result. Is that what you would expect?

![image](https://user-images.githubusercontent.com/57253949/186093672-cf0577aa-43db-4408-b055-a58012619716.png)

2022-08-23 07:47 UTC, Patowhiz commented
@lloyddewit yes! Thank you very much. 
Do you prefer we "git ignore" the files you suggested before @rdstern starts the testing?
I'm not sure how to do that, but I can try. Still your help will be highly appreciated. If you prefer doing that quickly and just updating this PR that's also okay.

2022-08-23 09:38 UTC, lloyddewit commented
@Patowhiz I could experiment a bit with the minimal number of cef files that we should include in this PR. I could do this today or tomorrow.
For me, it would be acceptable, if the first time a developer checks out this PR, then VS updates its development environment. I think this is a normal/acceptable approach.

2022-08-24 11:01 UTC, lloyddewit commented
@Patowhiz 
I investigated if we could remove the new NuGet packages from this PR.
I suggest to make the changes below to the `R-Instst/.gitignore' file. I didn't want to push this change directly to this PR.
I tried several times to create a temporary branch with this PR's changes without the NuGet packages for testing, but Visual Studio gave me an error when I tried to load the project.
If you make the change, and it works, then I don't know if the cef files will be automatically removed from this PR, or if we need to make a new PR without the cef files.

We could also consider a more general approach and remove all the NuGet packages from our git repo. See [here](https://docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control).

![image](https://user-images.githubusercontent.com/57253949/186401156-e9dec0e7-57c6-447b-97b8-6485f2547860.png)

```
# PR #7782 adds a feature to display html in the output window.
# This requires the cef packages. These packages are more than 0.4 GB.
# We want to prevent these packages from being stored in the R-Instat GitHub repository.
/packages/cef.redist.x64.104.4.18/
/packages/cef.redist.x86.104.4.18/
/packages/CefSharp.Common.104.4.180/
/packages/CefSharp.WinForms.104.4.180/
```

2022-08-25 08:59 UTC, rdstern commented
This is looking great - very exciting.

I also like the maximise feature.

However I am not supposed to praise, but be critical.  So, for the graphs, when I maximise the new version looks as though the top has been chopped a bit.  Compare a boxplot with the R-Viewer:
![image](https://user-images.githubusercontent.com/11226469/186619102-35e2269d-56ec-40fc-9542-dea5f607648d.png)

I realise there is just one format, currently, for saving graphs, and that will be extended later.

I really like the feature that I can just work in the output window and then maximise and look at any of the graphs in more detail later.

On the tables it seems to work.  Here is a table previously and now.

![image](https://user-images.githubusercontent.com/11226469/186620906-bebeaa1f-dea7-41c3-a48e-22ce9ed02dab.png)

I note - again the top line is missing now, and the default font/formatting seems different.

I also had one instance (only 1) for the following black square for a simple table.  When I maximised it was there fine.
![image](https://user-images.githubusercontent.com/11226469/186621595-e15cc2f2-fd00-423e-a6a3-f499992d0416.png)

This was just the following table:
![image](https://user-images.githubusercontent.com/11226469/186621804-0470c4b6-7641-489e-b85b-19f18dce574d.png)

I suggest we will want to take advantage sometimes of the ability (at least with the tables) to produce latex - and I presume rtf, as these are the 3 for the gt package?

2022-09-05 22:29 UTC, Patowhiz commented
This PR now aims to fix issue #7121 and #7808.

2022-09-06 08:16 UTC, lloyddewit commented
@Patowhiz thank you for the recent changes. 
Is this PR now ready for final testing and review or do you still expect to make changes.
What's the status of the 700+ cef files?
thanks

2022-09-06 23:37 UTC, Patowhiz commented
@lloyddewit I amended the git ignore file as suggested. I think we may have to delete the already pushed `cef` files manually. 

I decided to make changes that affect processing of objects this week thus expounding the original issue. It strongly relates to the improvements we want in regards to outputs that are displayable by the output viewer. This includes major R level changes that @lilyclements will review.

The changes now affect all dialogs that produce an output that is displayed by the output viewer.
@rdstern changes made also allow us to save text summaries like `skimr` outputs.
  
@lloyddewit @rdstern I'm now going through every dialog to make sure that I'm aware of all the regression introduced in this PR. The bigger task is making the dialogs take advantage of the new simplified implementation. @lloyddewit I suggest you have a look at the code (especially the deeper) before I re-task the team here to undertake that task.

2022-09-07 00:27 UTC, Patowhiz commented
@lilyclements this is ready for your R review.
@lloyddewit this is ready for your review as well.

@rdstern I'm already aware of some of the cosmetic issues and the output viewer issues. I'll address those in a separate PR. This PR has big changes. You can test this as well. In particular notice how from dialog **One Variable Summarise** as indicated above, we can now save such summary objects and even maximise them just like graphs and tables.

Thanks.

2022-09-07 08:59 UTC, rdstern commented
@Patowhiz I tested with one-variable summarise, and with the Prepare > Check Data > View Labels that also directs data to the new output window.  Looks good.
I suggest it is time to go ahead and make the hopefully minor changes in the remaining dialogues so all the html output goes to the new window.
Two small points:
a) I got the black screen once again as mentioned above.
b) In a maximised graph it is not quite the same as the R-viewer.  There it starts as the same size as (I assume) the original and then maximise changes the graph to fill the screen.  And you can have intermediate sizes which is sometimes useful also.

2022-09-07 09:10 UTC, lilyclements requested changes
Looks good!

The View Objects and View Graph dialogs aren't displaying the object names for me if I create a graph (I haven't checked for other objects)
![image](https://user-images.githubusercontent.com/21180424/188838973-b79384b7-6550-489f-8dc6-67f10429a75d.png)

Otherwise, I just have some minor comments.

2022-09-07 09:10 UTC, lilyclements commented on instat/static/InstatObject/R/instat_object_R6.R
> +DataBook$set("public", "get_object_names", function(data_name, object_type_label, include_overall = TRUE, include, exclude, type = "", include_empty = FALSE, as_list = FALSE, excluded_items = c(), in
remove `type = ""`?

2022-09-07 09:10 UTC, lilyclements commented on instat/static/InstatObject/R/instat_object_R6.R
> +  #todo. deprecated. Delete after doing the necessary refactoring.
Is this still a "TODO" out of interest?
If so, is this written up in an issue?

2022-09-07 09:10 UTC, lilyclements commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    return("")
Why can't it return the `graph_object`?

2022-09-07 09:10 UTC, lilyclements commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  message("R viewer NOT detected. File saved in location ", file_name)
Do we use capitals elsewhere in warning messages in R-Instat?

2022-09-07 09:10 UTC, lilyclements commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    return("")
Do you know why `return(utils::capture.output(...))` doesn't  work?

2022-09-07 10:32 UTC, Patowhiz commented
> @Patowhiz I tested with one-variable summarise, and with the Prepare > Check Data > View Labels that also directs data to the new output window. Looks good. I suggest it is time to go ahead and make the hopefully minor changes in the remaining dialogues so all the html output goes to the new window. Two small points: a) I got the black screen once again as mentioned above. b) In a maximised graph it is not quite the same as the R-viewer. There it starts as the same size as (I assume) the original and then maximise changes the graph to fill the screen. And you can have intermediate sizes which is sometimes useful also.

@rdstern thanks for testing this.
I will look into the black screen in a separate PR. It may be a HDPI issue.
The maximised graph is indeed not the same as the R-Viewer. When the R viewer is maximised, it literally reruns the R graphics code that draws the plot in the R viewer(sort of like redrawing or repainting). In principle that's how R graphics works, it paints on the given size of the screen.
Our custom maximised form just loads an existing image file, and displays it in the widened screen, the attempts to display it while maintaining the aspect ratio. We could explore doing what the R viewer does in a separate PR. We may have to be a bit clever here.

2022-09-07 11:14 UTC, Patowhiz commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    return("")
It can.

2022-09-07 11:14 UTC, Patowhiz commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  message("R viewer NOT detected. File saved in location ", file_name)
changed to small letters.

2022-09-07 11:44 UTC, Patowhiz commented on instat/static/InstatObject/R/instat_object_R6.R
> +DataBook$set("public", "get_objects", function(data_name, object_name, object_type_label, include_overall = TRUE, as_list = FALSE, include_empty = FALSE, force_as_list = FALSE, internal = TRUE, ...)
Because it's use has been removed. printing of objects has generally been moved to `view_object` function. That now applies to graphs as well.

2022-09-07 11:54 UTC, Patowhiz commented on instat/static/InstatObject/R/labels_and_defaults.R
> +surv_label="surv" #todo. deprecated.
Yes. Removed

2022-09-07 11:54 UTC, Patowhiz commented on instat/static/InstatObject/R/instat_object_R6.R
> +DataBook$set("public", "get_object_names", function(data_name, object_type_label, include_overall = TRUE, include, exclude, type = "", include_empty = FALSE, as_list = FALSE, excluded_items = c(), in
Yes. removed

2022-09-07 11:55 UTC, Patowhiz commented on instat/static/InstatObject/R/instat_object_R6.R
> +  #todo. deprecated. Delete after doing the necessary refactoring.
I've deleted the entire code block. No longer needed.

2022-09-07 11:55 UTC, Patowhiz commented on instat/static/InstatObject/R/data_object_R6.R
> +      #todo. check if type is recognised?
Removed. No longer necessary

2022-09-07 12:33 UTC, lilyclements approved these changes
Thanks for the changes - this looks good to me!

2022-09-07 13:24 UTC, Patowhiz commented
Thanks @lilyclements for reviewing this. Next task is to discuss how these objects can be saved and restored after the data book is saved by the user.
As discussed, @rdstern @lloyddewit I have written the issues expected and follow up fixes after this PR is merged in issue #7852.

2022-09-07 14:55 UTC, rdstern approved these changes
Now I have reproduced the problem systematically.  It is just the first time it uses the output window for html.
a) I first tried with the survey.  I used the Frequency/summary tables.  
When I use it again it is fine.
b) I then restarted R-Instat and used the Prepare > Check Data > Labels dialogue - same result.  Then I repeat the dialogue and it is fine.
c) So I start again and use a different dataset - the diamonds from the library.  Do a frequency table and again get the problem.  Then repeat and it is fine.
d) Fourth try.  Start again, use survey, and get a text output.  That's fine.  Then get a frequency table - same problem.
Repeat the dialogue and fine.

By the way it still gives the black screen (momentarily), but then it goes and the result is displayed.

e) Fifth try.  Start again. Survey dataset.  Use Pivot table.  Same problem.  Use it again and it is fine.

![image](https://user-images.githubusercontent.com/11226469/188906220-a353a43d-390f-4125-b8c9-7cb28c3c7ee1.png)

I can live with it, and so am approving.  If the code is ok I could accept it as now, so we merge quickly, and it can be fixed later.

2022-09-07 14:55 UTC, rdstern submitted a review, later dismissed
Now I have reproduced the problem systematically.  It is just the first time it uses the output window for html.
a) I first tried with the survey.  I used the Frequency/summary tables.  
When I use it again it is fine.
b) I then restarted R-Instat and used the Prepare > Check Data > Labels dialogue - same result.  Then I repeat the dialogue and it is fine.
c) So I start again and use a different dataset - the diamonds from the library.  Do a frequency table and again get the problem.  Then repeat and it is fine.
d) Fourth try.  Start again, use survey, and get a text output.  That's fine.  Then get a frequency table - same problem.
Repeat the dialogue and fine.

By the way it still gives the black screen (momentarily), but then it goes and the result is displayed.

e) Fifth try.  Start again. Survey dataset.  Use Pivot table.  Same problem.  Use it again and it is fine.

![image](https://user-images.githubusercontent.com/11226469/188906220-a353a43d-390f-4125-b8c9-7cb28c3c7ee1.png)

I can live with it, and so am approving.  If the code is ok I could accept it as now, so we merge quickly, and it can be fixed later.

2022-09-07 23:10 UTC, Patowhiz commented
@rdstern thanks for reviewing this.
I have added the issue you have identified in issue #7852 as one of the high priority follow ups.

2022-09-07 23:42 UTC, Patowhiz commented
As discussed with @lloyddewit this PR has now been replaced by PR #7853.

2022-09-07 23:42 UTC, closed without merging