Renaming Lists in the New DataFrame dialog
africanmathsinitiative/R-Instat pull request #7788
Opened 2022-08-18 12:35 UTC by anastasia-mbithe

fixes #7771 
This is still in progress, am working to fix some emerging bugs.

2022-08-19 08:48 UTC, anastasia-mbithe commented
@rdstern, this is ready for review. Kindly have a look at it.

2022-08-19 09:29 UTC, lloyddewit requested changes

2022-08-19 09:29 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        'ucrNewDFName.SetPrefix("data")
delete this line?

2022-08-19 09:29 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +    Private clsEmptyOverallFunction, clsEmptyMatrixFunction, clsNewDataFrameFunction, clsGetCategories,
```suggestion
    Private clsEmptyOverallFunction, clsEmptyMatrixFunction, clsNewDataFrameFunction, clsGetCategoriesFunction,
```

2022-08-19 09:29 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            End If
should there be an `ElseIf` here to call `ucrNewDFName.SetPrefix(...`?
Otherwise `SetPrefix()` won't be called, but maybe that's the intention?

2022-08-19 11:38 UTC, anastasia-mbithe commented on instat/dlgNewDataFrame.vb
> +            End If
It still calls SetPrefix("data") when the ucrInputListInCategory is empty

2022-08-19 11:59 UTC, lloyddewit requested changes

2022-08-19 11:59 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            End If
Sorry, I don't understand.
If `rdoLists.Checked` is True and `ucrInputListInCategory.IsEmpty` is also True, then where is `SetPrefix()` called?

2022-08-19 11:59 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        clsGetCategories, clsSjLabelledFunction, clsConstructFunction, clsDummyLabelFunction,
```suggestion
        clsGetCategoriesFunction, clsSjLabelledFunction, clsConstructFunction, clsDummyLabelFunction,

```

2022-08-22 10:04 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        clsGetCategories, clsSjLabelledFunction, clsConstructFunction, clsDummyLabelFunction,
This comment is not yet resolved.

2022-08-22 10:11 UTC, lloyddewit requested changes

2022-08-22 10:11 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        End If
simplify?
```suggestion
        If rdoLists.Checked AndAlso Not ucrInputListInCategory.IsEmpty Then
            ucrNewDFName.SetPrefix(ucrInputListInCategory.GetText)
        Else
            ucrNewDFName.SetPrefix("data")
        End If
```

2022-08-23 09:31 UTC, anastasia-mbithe commented on instat/dlgNewDataFrame.vb
> +        clsGetCategories, clsSjLabelledFunction, clsConstructFunction, clsDummyLabelFunction,
It is resolved, Kindly check in the latest commits

2022-08-23 09:33 UTC, anastasia-mbithe commented
The last commit includes changes that fixes #7799 as well.

2022-08-23 09:54 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        clsGetCategories, clsSjLabelledFunction, clsConstructFunction, clsDummyLabelFunction,
@anastasia-mbithe I think there is a misunderstanding. In various comments above, I asked 3 or 4 times for `clsGetCategories` to be renamed to `clsGetCategoriesFunction`. This is a simple change and you've told me several times that you've done it but I still can't see the change in this PR. Am I missing something? Would it help to discuss verbally? Thanks for your understanding.

2022-08-23 09:56 UTC, lloyddewit commented
> The last commit includes changes that fixes #7799 as well.

I updated the PR description so that when this PR is merged, it automatically closes the issue.

2022-08-23 17:52 UTC, rdstern commented
On the File > New, I was ok with the row numbers being 10 and not I million.
Then when you press to see the names I am happy with the first variable x1, as you have it.
The second variable should be left as it was before, i.e. as a character variable filled with NA. 
So:
![image](https://user-images.githubusercontent.com/11226469/186229649-fbc28d2c-7fcb-4b02-ad8b-473d5b4b1ecc.png)

2022-08-26 14:01 UTC, rdstern commented
@anastasia-mbithe in my comment above I realise that the 1,1000000 looks a bit odd for a beginner.  So make it 1,1000 instead I think.  Then it does not need changing for any data frame up to 1000.

2022-09-01 08:51 UTC, anastasia-mbithe commented
@rdstern, I can't get a way of separating the change in the first row not to affect the second row, since the code fills the grid up to the nth row. It can however be done manually when one is using the dialog. @N-thony, you can check whether my view/ suggestion is correct.

2022-09-14 07:00 UTC, rdstern commented
@N-thony could you examine the code for the defined variables?  It should be easy to have the default of the first variable being numeric (with a variable from 1 upwards), while the default for any remaining variables remains as a character variable?

2022-09-26 12:33 UTC, anastasia-mbithe commented
@N-thony , kindly have a look at this.

2022-09-27 11:22 UTC, N-thony requested changes

2022-09-27 13:00 UTC, N-thony approved these changes
@rdstern could you test?

2022-09-28 16:11 UTC, rdstern approved these changes
@anastasia-mbithe and @N-thony I was poised to say we should give in on these changes.  That's because they were taking too long, and were not so important.  But to my great pleasure it all seems to work fine now.  That's really great.  Many thanks!  @lloyddewit I hope the code is ok so this can be merged.

2022-09-29 10:30 UTC, lloyddewit approved these changes

2022-09-29 10:35 UTC, merged