Modifying the plot option control in Describe>Specific tables/Graphs>Bar Chart
africanmathsinitiative/R-Instat pull request #7810
Opened 2022-08-25 06:37 UTC by Fidel365

Fixes(partially) #7556 
@N-thony , @lloyddewit , this PR is ready for preview

2022-08-25 09:53 UTC, lloyddewit commented
@Ivanluv Please could you review?

@Fidel365 Is this PR ready for test by @rdstern or would you prefer that @N-thony tests first?

thanks

2022-08-25 10:03 UTC, Fidel365 commented
@N-thony can test it first

2022-08-25 11:24 UTC, Ivanluv approved these changes

2022-08-28 05:48 UTC, N-thony requested changes

2022-08-28 05:48 UTC, N-thony commented on instat/dlgBarAndPieChart.vb
> +    'End Sub
remove?

2022-08-28 05:48 UTC, N-thony commented on instat/dlgBarAndPieChart.vb
> +        'ChangeButtonsText()
remove?

2022-08-28 05:48 UTC, N-thony commented on instat/dlgBarAndPieChart.vb
> +    End Sub
remove?

2022-08-28 05:48 UTC, N-thony commented on instat/dlgBarAndPieChart.vb
> +    End Sub
remove?

2022-10-01 10:50 UTC, Fidel365 commented
@N-thony , I have made the changes requested

2022-10-31 07:21 UTC, N-thony requested changes
@Fidel365 it will also be good to disable options in the button drop down list when you are not under that option

2022-10-31 07:21 UTC, N-thony commented on instat/dlgBarAndPieChart.vb
> +        End If
you can use ElseIF on line 1003 and Else on line 1009
also remove line 1007

2022-11-20 11:16 UTC, rdstern approved these changes
@N-thony you had at least one issue with the code.
The new sub-dialogue feature seems to be working, so I am approving.
@lloyddewit perhaps the coding issues can be fixed quickly, and then this could be merged?  Please note there is (I think) another pull request with the lollipop option to merge too.  Perhaps the order of merging needs to be resolved too.
Once they are both merged, I note for the future that I was not able to do a decent pie chart - so I will need to look at that aspect!  I noticed that:
a) I simply couldn't get one nicely!
b) When I flipped the axes it ignored my pie-chart option.  That may be ok, but we should do something about this in the dialogue - perhaps only have the pie chart control visible when the data are not flipped.

2022-11-21 07:02 UTC, N-thony commented
@Fidel365 they are open comments above, can you resolve them?

2023-01-11 17:28 UTC, rdstern commented
@lloyddewit is this ok to be merged?

2023-02-13 17:16 UTC, rdstern commented
@N-thony can someone take this over and resolve the conflicts?  
I think there will be more to do on this dialogue, but it would be good to get these changes merged first.

2023-02-14 07:23 UTC, N-thony commented
> @N-thony can someone take this over and resolve the conflicts? I think there will be more to do on this dialogue, but it would be good to get these changes merged first.

yes @derekagorhom is working on it.

2023-02-15 08:43 UTC, lloyddewit commented
replaced by PR #8139

2023-02-15 08:44 UTC, closed without merging