Modifying the plot option control in Line plot dialog. >Describe>Specific Tables/Graphs>Line/Smooth/Dumbbell/Slope
africanmathsinitiative/R-Instat pull request #7814
Opened 2022-08-25 14:26 UTC by Fidel365

Fixes (partially) #7556 
@N-thony , @lloyddewit , this PR is ready for review

2022-08-26 06:56 UTC, lloyddewit commented
@N-thony Please could you review?
@rdstern Please could you test?
Thanks

2022-08-28 10:32 UTC, rdstern commented
@Fidel365 this is a good start.  But there is quite a lot to add.  When I pressed on point then that should be added to the list.  Similarly for peaks and valleys.  Perhaps for valleys the control could be better lined up at the same time.
When on smooth, and then ask for the line, then that should be added.
By the way, at least initially, I am quite relaxed about whether an option is enabled - as you are trying to do.  If initially they are there, that's the important part.

2022-10-24 11:25 UTC, N-thony requested changes
@Fidel365 can you resolve my first comments above? Thanks

2022-10-24 11:25 UTC, N-thony commented on instat/dlgLinePlot.vb
> +    End Sub
Can you remove the empty sub?

2022-10-24 11:25 UTC, N-thony commented on instat/dlgLinePlot.vb
>      End Sub
we can get rid of this since it called on line 569

2022-10-24 11:25 UTC, N-thony commented on instat/dlgLinePlot.vb
>          TempOptionsDisabledInMultipleVariablesCase()
then we replace this by
cmdLinePathStepSmoothOptions.Enabled = ucrVariablesAsFactorForLinePlot.bSingleVariable

2022-10-24 11:25 UTC, N-thony commented on instat/dlgLinePlot.vb
> +        'cmdLinePathStepSmoothOptions.Visible = True
We can remove this if not needed?

2022-10-24 11:25 UTC, N-thony commented on instat/dlgLinePlot.vb
> +            'cmdLinePathStepSmoothOptions.Visible = False
here too

2022-11-20 10:57 UTC, rdstern commented
@N-thony this still has conflicts.  I wonder who should take this over from @Fidel365 who I assume is no longer doing this now?

2022-11-21 05:24 UTC, Fidel365 commented
I will be working on this and it will be ready before the end of tomorrow

On Sun, Nov 20, 2022, 13:57 rdstern ***@***.***> wrote:

> @N-thony <https://github.com/N-thony> this still has conflicts. I wonder
> who should take this over from @Fidel365 <https://github.com/Fidel365>
> who I assume is no longer doing this now?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/africanmathsinitiative/R-Instat/pull/7814#issuecomment-1321100184>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZU67SAFVNKVKC3BFEJXQQ3WJH72FANCNFSM57TKV76Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-14 09:14 UTC, derekagorhom commented
@africanmathsinitiative/developers i taking over this PR

2023-02-09 17:32 UTC, lloyddewit commented
Replaced by PR #8056

2023-02-09 17:32 UTC, closed without merging