Extended the Calculator Integer keyboard
africanmathsinitiative/R-Instat pull request #7826
Opened 2022-08-31 09:45 UTC by anastasia-mbithe

Fixes #7818
This is still in progress. The last part of the issue is yet to be addressed (adding length to the position control).

2022-09-05 08:50 UTC, rdstern commented
@anastasia-mbithe this all looks great.
a) Could you add the rep addition to the new prime, e.g. twin keys where needed - as explained in the issue.  You already added a similar feature in the prime key, to include the length of the data frame.
b) Add an s to the prime key, so it becomes `primes`.
c) Move the 5 prime keys from the main set to the top of the new set.  Have primes first, then n-th prime and next prime.  Then also is prime and coprime.

Many thanks

2022-09-05 16:48 UTC, anastasia-mbithe commented
@rdstern , having the rep function for the primes only works for twin and triplets functions though on very limited occasions; when the length of the output is 1.
Its functionality depends on the length of the dataset and the length of the resulting output, so it mostly bugs because the length of the dataset is not divisible by the length of the resulting output from the function.
 
Even having: rep(primes::third_cousin_primes(0,10000),len=1000) in a dataset of 1000 rows still bugs because the length of the result is 101 which does not divide 1000.

2022-09-06 07:08 UTC, rdstern commented
@anastasia-mbithe that's very odd, because it is just what the rep is supposed to do.

I tried with the rep in front of your functions.  I used the usual survey, so had 36 and it works fine for all your keys.  So, I am not sure what is going on?

For example - from my log file:

`calc6 <- rep(primes::sexy_prime_triplets(2 ,10000 ),len=36)
`
and:
`calc7 <- rep(primes::k_tuple( 2,10000 ,c(0,8)),len=36)`

![image](https://user-images.githubusercontent.com/11226469/188568581-219d4797-f426-41eb-9b91-abcf4ac9011f.png)

2022-09-06 09:53 UTC, anastasia-mbithe commented
@rdstern , I just added the rep function (am not sure why it was bugging yesterday, today the function works smoothly). I have also set the default to (0,100) for min and max since there has to be a default while implementing the function in this way. Also, am not sure if you want the parameters shown as well; for min, max or tuple.

2022-09-06 11:59 UTC, rdstern reviewed
@anastasia-mbithe the changes are very interesting.  Can you show them to @lilyclements .  You have included the specific values 0 and 100 for each of these special prime keys.  That's different to the other keys.  On the other hand it makes it very easy to adapt those values - so I rather like it.    It makes those keys easier to use, and I can't see it is doing any harm.  So I am inclined to suggest I should approve as it stands.  I'd just like Lily to give a second opinion.

2022-09-06 17:30 UTC, lilyclements approved these changes
Looks good to me!

2022-09-06 18:58 UTC, rdstern approved these changes

2022-09-07 07:50 UTC, lloyddewit requested changes

2022-09-07 07:50 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        clsGetDataframeFunction.AddParameter("data_name", ucrSelectorForCalculations.ucrAvailableDataFrames.cboAvailableDataFrames.SelectedItem, bIncludeArgumentName:=False)
This function does not have a package name or R command. Is that correct?
(this comment also applies to the other functions below)

2022-09-07 07:50 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub cmdTwin_Click(sender As Object, e As EventArgs) Handles cmdTwin.Click
This sub seems to have the same structure as the 4 subs below it. The only thing that seems to vary is the name of the R command (e.g. "twin_primes").
Could we remove the duplication (e.g. add a private function that takes the name of the R command as a parameter)?

2022-09-22 08:10 UTC, anastasia-mbithe commented
@lloyddewit, Kindly have a look at the changes made.

2022-09-23 10:18 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub cmdTwin_Click(sender As Object, e As EventArgs) Handles cmdTwin.Click
Thank you for moving some of the duplicated code into the `CalculatorFunctions()` function.
Is there even more duplicated code we could move? For example:
```
    Private Sub CalculatorFunctions(strRCommand As String)
        Dim clsPrimesFunction As New RFunction

        clsPrimesFunction.SetPackageName("primes")
        clsPrimesFunction.SetRCommand(strRCommand)
        clsPrimesFunction.AddParameter("min", "0", iPosition:=0)
        clsPrimesFunction.AddParameter("max", "100", iPosition:=1)

        clsRepFunction.AddParameter("x", clsRFunctionParameter:=clsPrimesFunction, iPosition:=0, bIncludeArgumentName:=False)

        clsDataFunction.SetRCommand("nrow")
        clsDataFunction.AddParameter("x", ucrSelectorForCalculations.ucrAvailableDataFrames.cboAvailableDataFrames.SelectedItem, bIncludeArgumentName:=False)

        clsRepFunction.SetRCommand("rep")
        clsRepFunction.AddParameter("len", clsRFunctionParameter:=clsDataFunction, iPosition:=1)

        ucrReceiverForCalculation.AddToReceiverAtCursorPosition(clsRepFunction.ToScript, 0)
    End Sub

    Private Sub cmdTwin_Click(sender As Object, e As EventArgs) Handles cmdTwin.Click
        CalculatorFunctions("twin_primes")
    End Sub
```

2022-09-23 10:19 UTC, lloyddewit commented
@anastasia-mbithe Thank you for the changes, if you can resolve the final open comment above, then I'm happy to approve

2022-09-28 11:16 UTC, N-thony commented
> @lloyddewit, I resolved the pending issue. Kindly have a look at it.

@lloyddewit please have look

2022-09-29 09:08 UTC, N-thony requested changes
Great, just some minor comments

2022-09-29 09:08 UTC, N-thony commented on instat/ucrCalculator.vb
> +
one line space?

2022-10-03 06:58 UTC, anastasia-mbithe commented
This is also complete as well. The changes requested are already resolved.

2022-10-03 08:41 UTC, lloyddewit approved these changes

2022-10-03 08:46 UTC, lloyddewit commented
@anastasia-mbithe thank you for the changes. I'm happy to approve.

@N-thony thank you for the peer review comments. I checked and they all look resolved. If not, then please let us know.

@rdstern there have been non-functional changes since your last review. Please could you restest/approve? thanks

2022-10-03 08:51 UTC, N-thony commented
> @anastasia-mbithe thank you for the changes. I'm happy to approve.
> 
> @N-thony thank you for the peer review comments. I checked and they all look resolved. If not, then please let us know.
> 
> @rdstern there have been non-functional changes since your last review. Please could you restest/approve? thanks

@lloyddewit looks good to me.

2022-10-04 06:51 UTC, rdstern approved these changes
Looks good.

2022-10-04 08:13 UTC, merged