Changed the Maximum factor default value to 12 in One Variable Summary dialog
africanmathsinitiative/R-Instat pull request #7827
Opened 2022-08-31 10:22 UTC by Vitalis95

Fixes #7825 
@rdstern @N-thony @lloyddewit , I changed default to 12 in Maximum Factor control

2022-09-02 09:35 UTC, lloyddewit requested changes

2022-09-02 09:35 UTC, lloyddewit commented on instat/dlgOneVariableSummarise.vb
> +        ucrNudMaxSum.SetMinMax(12, Integer.MaxValue)
We're hardcoding '12' several times in this dialog. If we want to change this number later, then we'll need to change it in multiple places.
Would it be better to declare a constant (e.g. `Private Const iMaxSum = 12` and use this instead?
```suggestion
        ucrNudMaxSum.SetMinMax(iMaxSum, Integer.MaxValue)
```

2022-09-02 09:35 UTC, lloyddewit commented on instat/dlgOneVariableSummarise.vb
> +                                            bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=12)
```suggestion
                                            bNewLinkedChangeToDefaultState:=True, objNewDefaultState:=iMaxSum)
```

2022-09-02 09:35 UTC, lloyddewit commented on instat/dlgOneVariableSummarise.vb
> +        clsSummaryFunction.AddParameter("maxsum", 12)
```suggestion
        clsSummaryFunction.AddParameter("maxsum", iMaxSum)
```

2022-09-02 10:25 UTC, Vitalis95 commented
@lloyddewit , I have made changes

2022-09-02 10:33 UTC, lloyddewit approved these changes

2022-09-02 10:33 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-09-04 09:56 UTC, rdstern approved these changes

2022-09-05 07:19 UTC, merged