Add New Apsimx Examples  Dialog
africanmathsinitiative/R-Instat pull request #7851
Opened 2022-09-07 12:42 UTC by MeSophie

Adding the Apsim Examples Dialog From #7532.

@rdstern and @lilyclements Please have a look.
Thank you.

2022-09-07 12:46 UTC, N-thony commented
@MeSophie this branch has conflicts, please resolve them.

2022-09-07 16:59 UTC, lilyclements submitted a review, later dismissed
Looks great! Nice job. @rdstern what do you think?

2022-09-08 08:21 UTC, rdstern commented
@MeSophie this is a good start.  These first comments are so you can complete this dialogue and it can be merged.
So please check each option and correct any aspects that are needed, so each example works.
I found Controlled Environment and Eucalyptus Rotation don't work and give the same error.  Then Rotation didn't work and gave a different error - I think it might be trying to write multiple data frames.

I stopped checking there.  Please check all the rest.  Once those are all working we should be able to merge the dialogue.  I didn't check what happens with Silent.

2022-09-08 08:30 UTC, rdstern commented
I wonder what your next thought was, when you saw the resulting data frames.  My immediate thought was - what's the corresponding climatic data for each example.  I think it is interesting that the assumption is that the analysis will just involve the yield data.  I would like to also be able to relate the variability in yields to those in the climatic data.  So I'd like both!

And, of course it would be good to know of the siol and management data too.  It is so useful that R-Instat makes it easy to look at multiple data frames.

So, I started by looking at the commands in the package - but couldn't see how to do this.  I did find that there is a link with Chirps and that there is a chirps package.  You could discuss this with @johnargentino as I wonder if that could become our easy way of importing chirps data in general?

Then I saw that the main vignette does seem to discuss the example data in much more detail.  I assume your current dialogue may work without installing Apsimx, but the other data need the package to be installed.  Good to investigate.

I imagine the dialogue will then be extended, so you could sort of import either just the yield data ar also the other data.  Let's see.

2022-09-13 07:25 UTC, MeSophie commented
@rdstern  The packages available are limited and all independent of each other. The ones I found interesting are **apsim** and **apsimx** which allow to read **.apsim and .apsimx files**, **apsimx_soil_profile** (which allows to create a soil profile), **as_apsimx_met** which transforms the climate data tables into **.met files**, **get_chirps_apsim_met/get_power_apsim_met**.  In order to link all these parameters, we need to understand the mathematical link between them and perhaps only then will one be able to simulate the model directly in R-Instat without using the APSIMX GUI. 

What we can do for the moment is to see to what extent we can use the **apsimx , inspect_apsimx and edit_apsimx** functions in a diaog. The user will be able to  import an .apsimx/.apsim file, inspect and edit it.

Also the majority of these packages require the installation of APSIMX software, this is also the case for the apsimx_examples and apsim_examples packages.

2022-09-23 10:14 UTC, MeSophie commented
@rdstern  I fixes  the bug generated by Controlled Environment, Eucalyptus Rotation and  Rotation models. Please, can you review the dialogue again? Thank you.

2022-09-29 09:24 UTC, N-thony commented on instat/dlgApsimx.vb
> +
can you remove this line?

2022-10-09 17:43 UTC, rdstern reviewed
For me it worked fine down to Wheat.  From then on it said as follows:
![image](https://user-images.githubusercontent.com/11226469/194771342-e2bcc0b0-965b-494d-9267-1f46cf56b354.png)

Now I had installed Apsim, but not Apsim classic.  I assume I needed to install the new Apsim or I would not have got any of the examples?  I am not sure I particularly need to install ApSim Classic, so I might have to do without those examples.  If that is the case, then perhaps the dialogue might make this all clear?

2022-10-24 11:17 UTC, N-thony commented
> Thanks @rdstern, I hadn't notice that because I had both apsim installed on my pc. To run all the examples below wheat you have to install Apsim classic because they are the examples of Apsim classic. The dialog uses two functions apsimx_example for the Apsimx Next Gen examples and apsim_example for the Apsim classic examples. If you don't need Apsim Classic I can just modify the code to stay with Apsim Next Gen examples only.

@rdstern what do you think?

2022-11-18 11:57 UTC, rdstern commented
@MeSophie we have spent so long on this dialogue, that is useful, but is a detail as it doesn't actually run ApSim, etc.  So we need to finish it quickly - I suggest for now either disabling or deleting those examples.  I am assuming a new user may not need to have classic as well as nextgen on their machine.

2022-11-20 22:57 UTC, MeSophie commented
> @MeSophie we have spent so long on this dialogue, that is useful, but is a detail as it doesn't actually run ApSim, etc. So we need to finish it quickly - I suggest for now either disabling or deleting those examples. I am assuming a new user may not need to have classic as well as nextgen on their machine.

@rdstern I already deleted apims_example on this dialog.

2022-11-21 17:00 UTC, rdstern submitted a review, later dismissed
@lloyddewit and @MeSophie it will be good to merge this, to show we have started work in this area.

2022-11-25 11:02 UTC, lloyddewit requested changes
@MeSophie Thank you for this.
Just a few questions/suggestions

2022-11-25 11:02 UTC, lloyddewit commented on instat/dlgApsimx.vb
> +            ucrBase.clsRsyntax.RemoveFromAfterCodes(clsReportOperator)
I assume that we only need to remove this operator object if it is added elsewhere.
Where is `clsReportOperator` added to the `AfterCodes`?

2022-11-25 16:55 UTC, MeSophie commented on instat/dlgApsimx.vb
> +        If ucrInputComboList.GetText = "Wheat" OrElse ucrInputComboList.GetText = "Barley" OrElse ucrInputComboList.GetText = "Controlled Environment" OrElse ucrInputComboList.GetText = "Sugarcane" O
@lloyddewit no we don't need to check all this. I just forgot to remove it. At the beginning there were two functions on this code since I have removed one we don't need this condition anymore.

2022-11-25 16:59 UTC, MeSophie commented on instat/dlgApsimx.vb
> +            ucrBase.clsRsyntax.RemoveFromAfterCodes(clsReportOperator)
@lloyddewit the operator is just useful for **Rotation mode** because  the result of this model is a list of two data frame and we just need one of them the **Report** so the operator help to select the report.

2022-11-28 08:34 UTC, lloyddewit requested changes
@MeSophie Thank you for the changes, just one open question

2022-11-28 08:34 UTC, lloyddewit commented on instat/dlgApsimx.vb
> +            clsDataListFunction.AddParameter(ucrInputSaveData.GetText, clsRFunctionParameter:=clsApsimxExampleFunction, iPosition:=0)
On lines 117 and 118, we add `clsApsimxExampleFunction` and `clsReportOperator` to the 'before codes'.
So should we remove `clsApsimxExampleFunction` and `clsReportOperator` from the 'before codes' in this `Else` block? or doesn't it matter?
(I don't completely understand how we should use RSyntax so my question may be naive)

2022-11-28 08:56 UTC, MeSophie commented on instat/dlgApsimx.vb
> +            clsDataListFunction.AddParameter(ucrInputSaveData.GetText, clsRFunctionParameter:=clsApsimxExampleFunction, iPosition:=0)
@lloyddewit Removing them in the else block doesn't matter too much because the results of the other models are already the **report**. So Removing or not will not change the results at all reason why I have deleted the two lines which removing them.

2022-11-29 08:22 UTC, lloyddewit approved these changes

2022-11-29 08:23 UTC, lloyddewit commented
@rdstern there have been some small changes since your last approval. If you can retest/approve, then we can merge, thanks!

2022-11-29 13:32 UTC, rdstern approved these changes
@MeSophie I have just noticed there is no help on the details of the examples.  I looked in the apsimx package and couldn't find them there.  It would be good to have those details - I assume they are somewhere?  But that doesn't affect approving the dialogue.

2022-12-01 08:13 UTC, merged