Go to specific Row page
africanmathsinitiative/R-Instat pull request #7858
Opened 2022-09-08 12:21 UTC by N-thony

@rdstern I'm not sure the issue number this PR attempts to fix. 
I have added a tooltip showing where to click for getting the box where you can enter the row page number. Please have a look.
![image](https://user-images.githubusercontent.com/68591383/189120215-8ff38365-783b-431d-a356-74d37f9dab90.png)

2022-09-08 15:12 UTC, rdstern commented
I could take that method.  I think the phrase could be Click to go to a specific window.  I am thinking that we have just a window onto the data.
Then once in the dialogue it could mention Window number:  Maybe it could even be an up-down with limits 1 to (say) 59 if there are over 59000 rows.  If you change the window size to (say) 2000, then it would adjust - or do we now not allow changes?
 
This could be the same for Columns.

It is only available when needed.  There have to be more than 2 clicks on the > or >> for this option to be worthwhile.  If there are 5 pages, or less, you can get to each page in (at most) 2 clicks.  So there need to be 6 or more windows (either down or across) before the corresponding option is visible.

2022-09-09 08:10 UTC, N-thony commented
> I could take that method. I think the phrase could be Click to go to a specific window. I am thinking that we have just a window onto the data. Then once in the dialogue it could mention Window number: Maybe it could even be an up-down with limits 1 to (say) 59 if there are over 59000 rows. If you change the window size to (say) 2000, then it would adjust - or do we now not allow changes?
> 
> This could be the same for Columns.
> 
> It is only available when needed. There have to be more than 2 clicks on the > or >> for this option to be worthwhile. If there are 5 pages, or less, you can get to each page in (at most) 2 clicks. So there need to be 6 or more windows (either down or across) before the corresponding option is visible.

@rdstern please take a look.  We keep this for now and further improvement as discussed will be done later.

2022-09-10 10:32 UTC, rdstern commented
I tried with the Pakistan hh data, which has 53400 rows.

a) The value isn't remembered.  It should be.
b) It did 25 well.
c) Then I typed 60.  It said the rows were 59000 to 60000 - which they were not.  And it moved back to page 1.  Either don't allow a number higher than 54 (for these data).  Or, if you type anything higher, then go to the last page, i.e. take the number mod 54.  You can keep the number typed - so it is possible to type a high number and go to the last page.
d) I tried -10 and it gave a funny message, saying I couldn't have 0.
e) I tried typing abc and it crashed.

You may feel that adding all these checks may make it easier to have your own simple dialogue, with an up-down control.  If so, then here it would be from 1 to 54 and the initial default would be halfway, i.e. 54/2 = 27.

2022-09-10 10:46 UTC, N-thony commented
> @N-thony I tried with the Pakistan hh data, which has 53400 rows.
> 
> a) The value isn't remembered. It should be. b) It did 25 well. c) Then I typed 60. It said the rows were 59000 to 60000 - which they were not. And it moved back to page 1. Either don't allow a number higher than 54 (for these data). Or, if you type anything higher, then go to the last page, i.e. take the number mod 54. You can keep the number typed - so it is possible to type a high number and go to the last page. d) I tried -10 and it gave a funny message, saying I couldn't have 0. e) I tried typing abc and it crashed.
> 
> You may feel that adding all these checks may make it easier to have your own simple dialogue, with an up-down control. If so, then here it would be from 1 to 54 and the initial default would be halfway, i.e. 54/2 = 27.

@rdstern thanks, I will just customized a sub dialogue for this.

2022-09-21 14:15 UTC, N-thony commented
@rdstern please test

2022-09-21 15:12 UTC, rdstern requested changes
It is better with this control.
a) At the start I accidentally pressed right-click.  This gave me a developer error, but then was ok.  That was just the first time.  I didn't get it again.
b) It started at 1, which is where I was.  It knew that 10 pages was the maximum.  I would like the default to be (say) 5 if that is easy.  Not important though.
c) I added another data frame which had 50 pages.  It was still stuck with a maximum of 10.  It should have known that the data frame is different?  As in b) ideally it would then change to its new default for the new data frame - so 25.  But I have no problem if that is difficult, so it remains on the previous setting anyway.  (Though remember that I could start with a larger one. )
d) I loaded a small data frame, and it still gave the popup message - though it didn't go to the dialogue.
e) Will you be adding the same control to go wider, or do you want this merged and then do another pull request for moving sideways?
e) Finally - and trivially, the spacing of the 3 buttons isn't quite right.

2022-09-30 08:35 UTC, N-thony commented
@rdstern I have made some changes regarding your comments above, it will still start by 1 and also will remember the pages according the data frame you are, also the buttons in the sub dialogue is a bit general.
For item e) I would prefer this to be merge then I will do it together with item f)

2022-09-30 12:51 UTC, N-thony commented
@rdstern this is ready for your re-test.

2022-10-01 06:23 UTC, rdstern submitted a review, later dismissed
This is nice.  I am approving, so it can be merged as soon as possible.
Then there is a second pull request to be able also to choose the "page" in terms of the columns shown, as well as the rows.  When this new pull is done perhaps consideration can be given to the following minor points:
a) At the top it says choose window number.  Then the text says page number.  Should it be window?
b) It starts at 1.  I wonder about starting roughly halfway down the list.  I was trying up to 53400, so it could start perhaps at about 27.
c) I wonder if it could give me the choice in the phrase?  In another set I have 157899 rows.  It is not immediately obvious to me that the limits are currently 1 and 158.  Perhaps this could be included.  It could perhaps become `Enter page number (1-158): `  Perhaps that information could also be included in the tooltip?  `Click to go to a specific window (1-158)`;
d) Should this feature also be added to the right-click menu at the bottom.  And perhaps there could also be an entry in the Edit menu that leads to the ability to go to any window - down or across?
e) I have now checked what happens when the number of rows is changed in the Tools > Options menu.  Fun - see below.  Is 1000 hard-wired into your code currently?  But before changing let's proceed with the horizontal paging so we make progress.  I also suggest Chris may with to disable that option anyway?
![image](https://user-images.githubusercontent.com/11226469/193395839-60e37938-72da-45fb-b9d8-47107b7de9bd.png)

2022-10-03 08:12 UTC, N-thony commented
@rdstern I have solved here items a) b) c), have a look. Thanks.

2022-10-09 17:03 UTC, rdstern reviewed
This is looking good now - and I note you have also done the columns as well as the rows - great.
a) If there are less than 1000 rows it still asks you to right-click and says you can choose between 1 and 0.  Similarly, if there are less than 100 columns it asks you to right-click but nothing happens.  I assume the simplest is just not to have the popup unless there are more than 1000 rows (or 100 columns).
b) It still gets messed up when I change (in Tools > Options) to show 2000 rows (say) rather than 1000.  But I am wondering whether - now the default is (I think) 1000 by 100, that - instead of you changing that code, we (at least temporarily) don't allow those defaults to be changed.

2022-10-11 07:37 UTC, N-thony commented
> This is looking good now - and I note you have also done the columns as well as the rows - great. a) If there are less than 1000 rows it still asks you to right-click and says you can choose between 1 and 0. Similarly, if there are less than 100 columns it asks you to right-click but nothing happens. I assume the simplest is just not to have the popup unless there are more than 1000 rows (or 100 columns). b) It still gets messed up when I change (in Tools > Options) to show 2000 rows (say) rather than 1000. But I am wondering whether - now the default is (I think) 1000 by 100, that - instead of you changing that code, we (at least temporarily) don't allow those defaults to be changed. Perhaps @ChrisMarsh82 would like to advise on this?

@rdstern how about now?

2022-10-11 07:46 UTC, N-thony commented
> 

@rdstern wait a bit

2022-10-12 07:03 UTC, rdstern requested changes
It still doesn't change the columns, see below for the example I am using:
![image](https://user-images.githubusercontent.com/11226469/195272796-c98094f8-8387-4b6a-9cb7-3d9bfc569adf.png)

2022-10-12 07:35 UTC, N-thony commented
@rdstern could you re-test? I also notice that when you change (in Tools > Options) to show 2000 rows rather than 1000 it doesn't apply directly to the `data view` unless you click one of the next button.
If you agree with me, we can consider it as a bug and fix it?

2022-10-12 09:06 UTC, rdstern submitted a review, later dismissed
@N-thony great - that all seems to work now, so I am approving and hope the code is such that @lloyddewit can approve soon and merge.
One tiny detail - if you want more work is the position of the cursor when you first use the popup.    It is at the start of the field, where I suggest it would be better at the end.  But that is not enough to stop the merge

2022-10-12 09:59 UTC, N-thony commented
> @N-thony great - that all seems to work now, so I am approving and hope the code is such that @lloyddewit can approve soon and merge. One tiny detail - if you want more work is the position of the cursor when you first use the popup. It is at the start of the field, where I suggest it would be better at the end. But that is not enough to stop the merge

@lloyddewit I can make this small change in the next PR concerning the paging.

2022-10-17 08:32 UTC, lloyddewit requested changes
@N-thony Thank you for the clean and readable code.
The Scintilla pacakages should also be removed from this PR.

2022-10-17 08:32 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +    Public enumWINNUMBERMode As String = WINNUMBERMode.Row
Is there a special reason for using `String`?
I understood that enum variables were normally declared like
```suggestion
    Public enumWINNUMBERMode As WINNUMBERMode = WINNUMBERMode.Row
```

2022-10-17 08:32 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +        If Not Integer.TryParse(iMax, iOutput) Then
`iMax` is not a string. What's happening on this line?

2022-10-17 08:32 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +                iDefault = Math.Round(iEnd / iMaxCols)
The rest of this sub seems to assume that we are in `Row` mode. Is that correct?

2022-10-17 08:32 UTC, lloyddewit commented on instat/ucrDataView.vb
> +            iPageNum = sdgWindowNumber.iPage
combine into single line?

2022-10-17 08:32 UTC, lloyddewit commented on instat/ucrDataView.vb
> +            iPageNum = sdgWindowNumber.iPage
combine into single line?

2022-10-17 08:32 UTC, lloyddewit commented on instat/ucrDataView.vb
> +            Dim iTotalPage As Double = GetCurrentDataFrameFocus().iTotalRowCount / frmMain.clsInstatOptions.iMaxRows
```suggestion
            Dim dTotalPage As Double = GetCurrentDataFrameFocus().iTotalRowCount / frmMain.clsInstatOptions.iMaxRows
```

2022-10-17 08:32 UTC, lloyddewit commented on instat/ucrDataView.vb
> +            If Not Integer.TryParse(iTotalPage, iOutput) Then
what's the purpose of this `If` statement?

2022-10-17 08:32 UTC, lloyddewit commented on instat/ucrDataView.vb
> +            Dim iTotalPage As Double = GetCurrentDataFrameFocus().iTotalColumnCount / frmMain.clsInstatOptions.iMaxCols
```suggestion
            Dim dTotalPage As Double = GetCurrentDataFrameFocus().iTotalColumnCount / frmMain.clsInstatOptions.iMaxCols
```

2022-10-17 08:32 UTC, lloyddewit commented on instat/ucrDataView.vb
> +            If Not Integer.TryParse(iTotalPage, iOutput) Then
please see comment above

2022-10-17 08:44 UTC, N-thony commented on instat/ucrDataView.vb
> +            If Not Integer.TryParse(iTotalPage, iOutput) Then
So, for this case, I'm using the if statement to check if the value returned from the division has decimal or not, if it has decimal then I have 1 to reach the limit of the page. Perhaps we can have a call and demonstrate that?

2022-10-17 09:30 UTC, N-thony commented
@lloyddewit I resolved your comments, please have a look. Thanks.

2022-10-17 10:24 UTC, lloyddewit requested changes
@N-thony Thanks for the updates.
I didn't finish my comments yet, I'll continue tomorrow.
Don't forget about removing the Scintilla packages.

2022-10-17 10:24 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +                iDefault = Math.Round(iEnd / iMaxRows)
I understand that 
- `iDefault` is the default number displayed in the Nud
- `iEnd` is the last row in the current window

In that case, I don't understand this calculation. Would it be better if the default was the current window + 10 for example? Or something similar?

2022-10-17 10:24 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +        If iNumPage = iEnd Then
are we comparing a window number to a row/col number? is that correct?

2022-10-17 10:24 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +        End If
Can we calculate `iDefault` in a single line without these special checks?

2022-10-17 11:16 UTC, N-thony commented on instat/sdgWindowNumber.vb
> +                iDefault = Math.Round(iEnd / iMaxRows)
Could you make it more clear?

2022-10-18 09:05 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +    Public iTotalRowOrColum, iStartRowOrColumn, iEndRowOrColumn As Integer
It is hard to upderstand what these data members are.
Please add an XML header for each one.

2022-10-18 09:16 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +        End If
would something like this work instead?
```suggestion
        ' the maximum number of rows/columns to display
        Dim iMaxRowsCols = If(enumWINNUMBERMode = WINNUMBERMode.Row,
                frmMain.clsInstatOptions.iMaxRows, frmMain.clsInstatOptions.iMaxCols)

        ' the current page number displayed
        Dim iDefaultPage As Integer = Math.Ceiling(CDbl(iEndRowOrColumn / iMaxRowsCols))

        ' the maximum number of row/col pages 
        Dim iRowOrColMaxPages As Integer = Math.Ceiling(CDbl(iTotalRowOrColum / iMaxRowsCols))
```

2022-10-18 09:17 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +        End If
I still don't understand what's happening here, please could you explain?

2022-10-18 10:10 UTC, N-thony commented on instat/sdgWindowNumber.vb
> +    Public iTotalRowOrColum, iStartRowOrColumn, iEndRowOrColumn As Integer
Thanks, resolved too

2022-10-18 10:10 UTC, N-thony commented on instat/ucrDataView.vb
> +            ttGoToRowOrColPage.SetToolTip(lblColDisplay, "Click to go to a specific window 1-" & iCols)
Done

2022-10-18 10:18 UTC, lloyddewit commented
@rdstern On 01 Oct, you commented:

> It starts at 1. I wonder about starting roughly halfway down the list. I was trying up to 53400, so it could start perhaps at about 27.

The current implementation shows the current page number in the control. The only exception is when the user is on the first page it shows the number of the half way page (27 in your example above).

This is inconsistent. Is there a risk that this looks like a bug or confuses the user? 
Should we be more consistent (e.g. always display the current page; or always display the page number half way between the current page and the last page)?

2022-10-18 10:26 UTC, rdstern commented
Humph - @lloyddewit you are right, we should be consistent.  Sorry @N-thony please could you always show the current page number - so it will be 1 (as you had before) at the start.

2022-10-18 10:29 UTC, N-thony commented
> Humph - @lloyddewit you are right, we should be consistent. Sorry @N-thony please could you always show the current page number - so it will be 1 (as you had before) at the start.

@rdstern good, could you re-test?

2022-10-18 10:34 UTC, N-thony commented
> @N-thony Thank you for the clean and readable code. The Scintilla pacakages should also be removed from this PR.

@lloyddewit could you help by removing the Scintilla pacakages? Thanks

2022-10-18 10:39 UTC, lloyddewit commented
> > Humph - @lloyddewit you are right, we should be consistent. Sorry @N-thony please could you always show the current page number - so it will be 1 (as you had before) at the start.
> 
> @rdstern good, could you re-test?

@rdstern I suggest you wait before testing. We will probably need to make a new PR to get rid of some extra packages that crept in. It's better if you test the new PR.

2022-10-20 08:55 UTC, lloyddewit commented on instat/sdgWindowNumber.vb
> +    Public iTotalRowOrColum, iStartRowOrColumn, iEndRowOrColumn As Integer
If we have a shared XML comment, then when the developer hovers over one of the variables, then it gives a confusing message.
Would it be better to have a separate XML header for each variable?

Do we need `iStartRowOrColumn`? Could we delete it?

![image](https://user-images.githubusercontent.com/57253949/196903737-88530c1c-d89b-40cf-ab5a-43545deb0ebb.png)

2022-10-20 09:01 UTC, lloyddewit requested changes
@N-thony This is looking good. There is just one open comment (see above).
If you can resolve this, then I will make a new PR, without the Scintilla packages, for @rdstern to test.
Thanks

2022-10-20 09:28 UTC, N-thony commented on instat/sdgWindowNumber.vb
> +    Public iTotalRowOrColum, iStartRowOrColumn, iEndRowOrColumn As Integer
Done, thanks

2022-10-20 10:18 UTC, lloyddewit commented
Replaced by PR #7924

2022-10-20 10:18 UTC, closed without merging