Implemented toggling from "Select All" To "Deselect All" for filter from factors subdialog
africanmathsinitiative/R-Instat pull request #7859
Opened 2022-09-08 12:38 UTC by Patowhiz

Fixes #7545
Replaces PR ##7563
@derekagorhom @africanmathsinitiative/developers this is ready for your review.
Thanks.

2022-09-09 10:18 UTC, lloyddewit requested changes

2022-09-09 10:18 UTC, lloyddewit commented on instat/sdgFiltersFromFactor.vb
> +        'autoTranslate(Me)
I agree that this line should not be needed any more. Delete the line rather than comment it?
```suggestion
```

2022-09-11 17:18 UTC, Patowhiz commented
@lloyddewit I've accepted you commit. Thanks.

2022-09-12 07:23 UTC, lloyddewit approved these changes

2022-09-12 07:23 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-09-12 10:11 UTC, rdstern approved these changes

2022-09-13 09:14 UTC, merged