Adding new packages to the Fit Model Keyboard. (Model>Fit Model> Fit Model Keyboard)
africanmathsinitiative/R-Instat pull request #7863
Opened 2022-09-09 08:26 UTC by Tula1

In this PR, @EstherNjeriLiberatta and I have added the `bayesglm` and `bayespolr` functions from the `arm` package, and the `bayes_inference` and `inference` packages from the `statsr` package into the fit model keyboard. 
@rdstern, this is ready for review.

2022-09-09 08:56 UTC, N-thony commented
@Tula1 which issue this PR attempts to fix?

2022-09-09 09:14 UTC, Tula1 commented
@N-thony , We are not fixing any issue, just adding Bayesian functions to the Fit Model Keyboard.

2022-09-10 07:20 UTC, rdstern commented
@Tula1 I have added an issue #7870 that corresponds to your work.  Possibly with @EstherNjeriLiberatta you could link this pull request to Fix, or partially fix this issue.
When you are ready for the pull request to be tested, could you mention how you have done initial tests, so we know where to start.  In particular you could suggest appropriate data and then roughly what you did for your testing.
You added 2 keyboards, one for arm and the other for statsr.
a) The arm keyboard seems to work fine.  The link to the help also works.  This is great.
b) But I couldn't get the statsr keyboard functions to work.  If you decide to keep that keyboard, then I suggest it is wrongly placed anyway.  There is also a Hypothesis testing keyboard and I suggest it goes better there.

But you have to help the user more in those keys.  When you press a key it should provide sufficient that the user can fit the model by just adding a column or two, etc.  Here I had first to type the name of the data frame, which is compulsory.  That could be provided automatically.  I also had to complete various other arguments - in fact so many - and some not so obvious that I never got it to work.  Where there are many **necessary** options I suggest the pressing of the key automatically gives one of them.  So it will easily run for at least one example.

c) But as you are now into adding keyboards - and seem to do it well, could you look to swap (at least initially) the statsr keyboard for one on rstanarm?

2022-10-27 11:36 UTC, N-thony commented
@Tula1 can you update about this?

2022-11-04 05:24 UTC, N-thony commented
@anastasia-mbithe can you peer review this?

2022-11-04 09:33 UTC, anastasia-mbithe commented on instat/dlgExtremesClimatic.vb
Delete line 54, we don't need the empty line there.

2022-11-04 09:34 UTC, anastasia-mbithe commented on instat/dlgExtremesClimatic.vb
> +
Also here

2022-11-04 09:35 UTC, anastasia-mbithe commented on instat/dlgHypothesisTestsCalculator.vb
> +
delete also line 1083 and 1085

2022-11-04 09:36 UTC, anastasia-mbithe commented on instat/dlgModelling.vb
> +
A single-line space will do

2022-11-04 09:41 UTC, anastasia-mbithe requested changes
@Tula1, change also the cursor position of both the inference function and bayes_inf function when we have Include arguments checked.

@N-thony, I have not testing how it works. It bugs on my side (I think its because of the dataset). I dont have the tapwater dataset. Maybe @rdstern could test that.

2023-03-26 18:31 UTC, rdstern commented
@derekagorhom could you please have a look at this pull request, which currently has build errors.  It adds more keyboards to the Fit Model dialogue and I am sure your new R-Help stuff will also be needed there.

2023-08-02 08:36 UTC, closed without merging