Created Import From RapidPro Dialog
africanmathsinitiative/R-Instat pull request #7867
Opened 2022-09-09 12:27 UTC by anastasia-mbithe

Fixes #7829 
This is ready @lilyclements , Please test using some real-time data / a valid key.

2022-09-09 12:59 UTC, lilyclements reviewed
Looks great! Two comments:

1. Can you set up the dialogs so that they cannot be Maximised/Minimised, the FixedToolOption and it opens CentreScreen? This can be done in the dialog properties.
2. The token does not read in correctly - you lose the file directory when it is read in and just read in the name of the file

2022-09-09 13:32 UTC, lilyclements commented
@anastasia-mbithe I made the changes that I commented about. Can you check you are okay with these? If so, this can then be reviewed.

2022-09-09 13:41 UTC, lilyclements commented
Quick problem I just noticed - 

```
# Code generated by the dialog, Import from RapidPro
rapidpror::set_rapidpro_key(key="C:/Users/lclem/OneDrive/Documents/GitHub/ParentText-data-analysis/R Code/tokens/PT_malaysia_key.txt", file=TRUE)

rapidpror::set_rapidpro_site(site="https://app.rapidpro.io/api/v2/")

rapidpror::get_user_data(rapidpro_site=rapidpror::get_rapidpro_site(), token=rapidpror::get_rapidpro_key())

```

We get the data, but do not actually import it into R-Instat. So we need a "New Data Frame Name:" button with an import. @anastasia-mbithe is this something you can sort?

2022-09-10 12:17 UTC, lilyclements commented
@anastasia-mbithe I made the changes that I commented about. Can you check you are okay with these? If so, this can then be reviewed. It would be great to have this in for Monday's GPI meeting

2022-09-11 12:17 UTC, anastasia-mbithe commented
@lilyclements I think everything is okay now. Just made very few changes.

2022-09-11 13:23 UTC, lilyclements reviewed
@anastasia-mbithe looks good! 

@africanmathsinitiative/developers this is ready for review

2022-09-11 13:23 UTC, lilyclements commented
https://github.com/orgs/africanmathsinitiative/teams/developers this is ready for review

2022-09-12 08:08 UTC, lloyddewit commented
@N-thony please could you (or your delegate) peer review?
thanks

2022-09-29 08:58 UTC, N-thony requested changes
@lloyddewit I have also work on it with @anastasia-mbithe perhaps you can peer review? Thanks

2022-09-29 08:58 UTC, N-thony commented on instat/dlgImportFromRapidPro.vb
> +        'ucrChkFlattenData.SetRDefault("FALSE")
can you remove this?

2022-09-30 08:42 UTC, lloyddewit requested changes
@anastasia-mbithe Thank you, this looks good. Just a couple of small suggestions

2022-09-30 08:42 UTC, lloyddewit commented on instat/sdgImportFromRapidPro.vb
> +
```suggestion
```

2022-09-30 09:04 UTC, anastasia-mbithe commented on instat/dlgImportFromRapidPro.vb
> +        dctTimezone.Add("GMT", Chr(34) & "GMT" & Chr(34))
I think it's totally okay to have all time zones included.

2022-09-30 10:51 UTC, anastasia-mbithe commented on instat/dlgImportFromRapidPro.vb
> +        dctTimezone.Add("GMT", Chr(34) & "GMT" & Chr(34))
Generally, time zones are many, so I have just added a few others. Maybe @lilyclements could help us identify the time zones needed.

2022-10-03 08:04 UTC, lloyddewit requested changes
@anastasia-mbithe just one more small suggestion, then I'm happy to approve.
Thanks

2022-10-03 09:56 UTC, lloyddewit approved these changes

2022-10-03 09:56 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-10-04 08:32 UTC, rdstern approved these changes
This all looks fine to me - at least just by clicking.  I don't have a database to check with.  So I guess @lilyclements should also approve.

2022-10-04 08:51 UTC, lloyddewit commented
> This all looks fine to me - at least just by clicking. I don't have a database to check with. So I guess @lilyclements should also approve.

@lilyclements approved on 11 Sep and there are no functional changes since then. So I'll go ahead and merge. I hope that's OK.

2022-10-04 08:52 UTC, merged