Improvements to Define New Filter dialog
africanmathsinitiative/R-Instat pull request #7893
Opened 2022-09-22 13:21 UTC by Vitalis95

Fixes #7860 
@rdstern @N-thony @Patowhiz , this PR shows the number of levels selected in factors.

2022-09-27 13:22 UTC, N-thony requested changes

2022-09-27 13:22 UTC, N-thony commented on instat/ucrFactor.vb
> +                'pnlSelectOptions.Anchor = (AnchorStyles.Left Or AnchorStyles.Right Or AnchorStyles.Bottom )
remove?

2022-09-27 13:22 UTC, N-thony commented on instat/ucrFilter.vb
>                  'ucrFactorLevels.SetSelectionAllLevels(False) 'by default don't select any factors
remove?

2022-10-05 07:57 UTC, N-thony commented
@Patowhiz can you review this? Thanks.

2022-10-06 02:54 UTC, Patowhiz reviewed
@Vitalis95 thanks for this.
I have added my code reviews and suggestions.

2022-10-06 02:54 UTC, Patowhiz commented on instat/ucrFactor.vb
> +        lblSelected.ForeColor = Color.Red
`lblSelected.ForeColor = Color.Red`
This can be set once in the designer, instead of here.

2022-10-06 02:54 UTC, Patowhiz commented on instat/ucrFactor.vb
> +    Public Sub SetColumnsSelected()
I think this subroutine should be private. The dialogs using this control do not need to call this subroutine externally.
The control is the one supposed to.

2022-10-06 02:54 UTC, Patowhiz commented on instat/ucrFilter.vb
> +    Private Sub cmdToggleSelectAll_Click(sender As Object, e As EventArgs)
Remove this subroutine entirely? I think it's no longer used.

2022-10-06 02:54 UTC, Patowhiz commented on instat/ucrFilter.vb
> +        ucrFactorLevels.SetColumnsSelected()
Once you refactor  `ucrFactorLevels.SetColumnsSelected()` to be internally called by  `ucrFactorLevels` control, this line can be removed.

2022-10-06 02:54 UTC, Patowhiz commented on instat/ucrFactor.vb
> +        lblSelected.ForeColor = Color.Red
You are calling `CountRowSelected()` twice. I think you can call it once and store it's result in a variable, then use the variable?

2022-10-06 02:54 UTC, Patowhiz commented on instat/ucrFactor.vb
> +        If _grdSheet IsNot Nothing Then
I think `_grdSheet IsNot Nothing`  should be done before getting the column index. And an additional check of whether the control is being used as a `ControlStates.NormalGrid` should be added. Have a look at line 716 for an example.
Also note this functionality is only used when the control is used as the selector.

2022-10-06 02:54 UTC, Patowhiz commented on instat/ucrFactor.vb
> +    Public Property SelectionControlsVisible As Boolean
I think this can be private. The control should determine the visibility based on how it is set up. For instance, if set up as normal grid, then the selection controls should be invisible. And that can be done internally by the control.

2022-10-06 12:20 UTC, Vitalis95 commented on instat/ucrFactor.vb
> +    Public Property SelectionControlsVisible As Boolean
@Patowhiz ,When changed it to private, I got the following error;

![image](https://user-images.githubusercontent.com/89011415/194310439-c7483ded-2d4c-4512-88cb-24358c6b2c14.png)

2022-10-06 12:39 UTC, Vitalis95 commented
> @Vitalis95 thanks for this. Have a look at the following dialogs. You may have to refactor them to be consistent with your new changes.
> 
> In this dialog, the button on it is now no longer needed. It should use the internal button that comes with the control. <img alt="1" width="422" src="https://user-images.githubusercontent.com/21179007/194199937-cf6bd6d3-6c2a-4435-ad79-9c033cce249c.png">
> 
> This dialog should now use the new label that comes internally built in the control. That means the top label can be removed. <img alt="2" width="463" src="https://user-images.githubusercontent.com/21179007/194199944-7e12dc59-d03d-43af-8cf4-5e020bc96dd1.png">
> 
> Thanks.

@Patowhiz , unlike other dialogs which shows levels selected in factors but for the dlgLabels/levels there are no levels to select, it just shows the number of levels. We can have a call or you can help me on this
Thanks.

2022-10-24 09:15 UTC, Patowhiz commented on instat/ucrFactor.vb
> +    Public Property SelectionControlsVisible As Boolean
@Vitalis95 you may have to remove the function call from other files too.

2022-11-03 06:54 UTC, N-thony commented
@Vitalis95 is this ready for @Patowhiz to check again?

2022-11-14 07:24 UTC, N-thony commented
> @Vitalis95 is this ready for @Patowhiz to check again?

@Vitalis95 any update?

2022-11-14 07:26 UTC, Vitalis95 commented
@N-thony , @Patowhiz , could you test it now?

2022-11-18 06:04 UTC, N-thony commented
> @N-thony , @Patowhiz , could you test it now?

@Patowhiz can you test/review again? Thanks

2022-11-18 11:46 UTC, rdstern commented
@Vitalis95 this is nice and I am happy to approve.
![image](https://user-images.githubusercontent.com/11226469/202697554-e9740394-bcfe-47e4-918e-50a8f769717b.png)
But I am reminded of another limitation here that might be a "quick fix"?  How do I select multiple levels?  I would like <shift> <click> to work, or perhaps dragging down.  (I can easily drag across in the reogrid.  Perhaps there is something that works already, but I haven't found it.  
Just to be clear I would like to select Jan to April without having to do 4 clicks?  Actually 4 isn't a problem, but sometimes I have had to select 40 levels - and then it is annoying!

2022-11-21 08:53 UTC, Vitalis95 commented
@rdstern , for the above I am investigating and I will do it as separate issue

> @Vitalis95 this is nice and I am happy to approve. ![image](https://user-images.githubusercontent.com/11226469/202697554-e9740394-bcfe-47e4-918e-50a8f769717b.png) But I am reminded of another limitation here that might be a "quick fix"? How do I select multiple levels? I would like to work, or perhaps dragging down. (I can easily drag across in the reogrid. Perhaps there is something that works already, but I haven't found it. Just to be clear I would like to select Jan to April without having to do 4 clicks? Actually 4 isn't a problem, but sometimes I have had to select 40 levels - and then it is annoying!

@rdstern, I am investigating on this and I will do as separate issue - this after discussing it with @N-thony

2022-11-21 12:53 UTC, N-thony commented
@rdstern @lloyddewit this can be merged at this step and the remaining as suggested above will be done probably in another PR

2022-11-21 12:57 UTC, rdstern submitted a review, later dismissed
Now happy to approve.  My other point can come later

2022-11-25 14:10 UTC, lloyddewit requested changes
@Vitalis95 Looks good, just one small question

2022-11-25 14:10 UTC, lloyddewit commented on instat/ucrFactor.vb
> +        If _grdSheet IsNot Nothing Then
should we check `_grdSheet` or `grdSheet`?

2022-11-26 11:11 UTC, Vitalis95 commented
@lloyddewit , have made the change. Thanks

2022-11-26 16:40 UTC, rdstern approved these changes

2022-11-28 08:49 UTC, lloyddewit approved these changes

2022-11-28 08:51 UTC, merged