More Improvements to the Integer Keyboard.
africanmathsinitiative/R-Instat pull request #7907
Opened 2022-10-11 09:51 UTC by anastasia-mbithe

Fixes #7876 

@rdstern, This is ready for testing.

2022-10-13 15:11 UTC, rdstern requested changes
@anastasia-mbithe these improvements are exciting and impressive.  Very well done indeed.
I only have a few very minor points.
a) for fibonacci2 and padovan please omit the gmp=FALSE.  Check they work fine without that, i.e.  just `Zseq::Fibonacci(n=nrow(x=data1))`, and `Zseq::Padovan(n=nrow(x=data1))` , because I think TRUE is the default.
b) For ugly please check the command you give.  it is currently 
`rep(x=Zseq::Regular(n=100), length=nrow(x=data1), gmp=FALSE)`
that looks to me as though the gmp is part of the rep and not the Regular command.  Should it be `rep(x=Zseq::Regular(n=100,gmp=FALSE), length=nrow(x=data1))`
If so, then the same change is needed for Perfect.

These are minor changes and perhaps @lloyddewit could check the code, in parallel, so it can be merged quickly.

2022-10-14 07:37 UTC, anastasia-mbithe commented
@rdstern, I have made the changes. For, Perfect and ugly I noticed the default is gmp=TRUE, so I omitted the gmp=FALSE.

2022-10-14 08:55 UTC, rdstern requested changes
@anastasia-mbithe just one tiny change - in ugly they remain quite small so we do want to keep the gmp=FALSE there.

2022-10-24 07:56 UTC, N-thony commented
@Vitalis95 can you peer review this?

2022-10-24 15:22 UTC, Vitalis95 approved these changes

2022-10-26 09:59 UTC, lloyddewit requested changes
@anastasia-mbithe thanks, just some very small comments

2022-10-26 09:59 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdFactorize2, "Compute the prime factorization(s) of integer(s) n. For example, Factorize(21)=c(3, 7, 1, 1)")
make consistent with other tool tip messages?
```suggestion
        ttCalculator.SetToolTip(cmdFactorize2, "computes the prime factorization(s) of integer(s) n. For example, Factorize(21)=c(3, 7, 1, 1)")
```

2022-10-26 09:59 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdOctal, "converts an integer into octal number. For example, intToOct(c(2,5,12,17))= 02,05,14,21")
```suggestion
        ttCalculator.SetToolTip(cmdOctal, "converts an integer into an octal number. For example, intToOct(c(2,5,12,17))= 02,05,14,21")
```

2022-10-26 09:59 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdHex, "converts an integer into hexadecimal number. For example, intToHex(c(2,7,10,15)))= 2,7,a,f")
```suggestion
        ttCalculator.SetToolTip(cmdHex, "converts an integer into a hexadecimal number. For example, intToHex(c(2,7,10,15)))= 2,7,a,f")
```

2022-10-26 09:59 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdOctmode, "converts an integer into a octal number. For example, as.octmode(intToOct(c(2,5,12,17)))= 02,05,14,21")
```suggestion
        ttCalculator.SetToolTip(cmdOctmode, "converts an integer into an octal number. For example, as.octmode(intToOct(c(2,5,12,17)))= 02,05,14,21")
```

2022-10-26 09:59 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdRoman, "converts a small(upto 3899) positive integer to Roman numbers. For example as.roman(14)=XIV")
```suggestion
        ttCalculator.SetToolTip(cmdRoman, "converts a small (up to 3899) positive integer to Roman numbers. For example as.roman(14)=XIV")
```

2022-10-26 09:59 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdPalindrome, "Generate palindromes to the length of the dataframe. For example the 100th palindromic number is 909")
```suggestion
        ttCalculator.SetToolTip(cmdPalindrome, "Generates palindromes to the length of the dataframe. For example the 100th palindromic number is 909")
```

2022-10-26 09:59 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdTriangle, " Number of objects in a triangle, so 0, 1, 3, 6, 10...")
```suggestion
        ttCalculator.SetToolTip(cmdTriangle, "Number of objects in a triangle, so 0, 1, 3, 6, 10...")
```

2022-10-26 09:59 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub cmdPalindrome_Click(sender As Object, e As EventArgs) Handles cmdPalindrome.Click
```suggestion
    End Sub
    
    Private Sub cmdPalindrome_Click(sender As Object, e As EventArgs) Handles cmdPalindrome.Click
```

2022-11-02 11:47 UTC, rdstern approved these changes
@lloyddewit this is already a big improvement on the existing Integer keyboard.
I have changed the text at the top to add (partially), so the issue is not closed.  I would like to merge this as it is and then make further progress.  Is the code ok for that?

2022-11-06 09:10 UTC, lloyddewit approved these changes
@anastasia-mbithe Thanks, code looks good

2022-11-06 09:11 UTC, merged