Summary functions code - adding summary statistics for date variables
africanmathsinitiative/R-Instat pull request #7925
Opened 2022-10-20 14:40 UTC by lilyclements

Adds in changes from #7465 that were lost in replacement. Fixes #7910 

@africanmathsinitiative/developers this is ready to review

2022-10-24 07:47 UTC, lloyddewit approved these changes

2022-10-24 07:47 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-11-18 08:37 UTC, rdstern commented
@lilyclements I added comments into #7910.  Here they are:
I still don't see a difference in the One Variable summarise - maybe they haven't been added in there yet. 
 For ordered factors with one variable I still get:
![image](https://user-images.githubusercontent.com/11226469/202525092-9c71958f-5bef-4de6-81ab-8960907168f5.png)

or for dates:
![image](https://user-images.githubusercontent.com/11226469/202525350-61504cee-ee9e-43ca-875e-79310dc96d51.png)

So I wondered if perhaps the changes were added to the general dialogue.  So I tried this:

![image](https://user-images.githubusercontent.com/11226469/202525641-edeceb8a-1fda-42c6-8f0c-95077c926d00.png)
And it gave me this error:

![image](https://user-images.githubusercontent.com/11226469/202525846-09fd4765-0a58-422b-b2f9-b961311267ed.png)
The commands that gave the error were:
```
summary_table <- data_book$summary_table(data_name="dodoma", columns_to_summarise="date", treat_columns_as_factor=FALSE, j=1, summaries=c("summary_mean", "summary_min", "summary_max", "p25", "p75", "summary_median"))


last_table <- (mmtable2::mmtable(data=summary_table, cells=value) + mmtable2::header_top_left(variable='summary-variable'))
data_book$add_table(table_name="last_table", table=last_table, data_name="dodoma")
data_book$get_tables(data_name="dodoma", table_name="last_table")

rm(list=c("last_table", "summary_table"))

```

2022-12-04 22:10 UTC, rdstern submitted a review, later dismissed
@lloyddewit this seems to work fine, so I am approving.
I found a different problem that the option in the dialogue to order the summaries seems to be ignored in the output.  But that is for another issue

2022-12-05 08:39 UTC, lloyddewit requested changes

2022-12-05 08:39 UTC, lloyddewit commented on instat/static/InstatObject/R/Backend_Components/summary_functions.R
> +          summary_function_exp <- paste0(summary_type, "(x = ", column_names, function_exp)
```suggestion
        summary_function_exp <- paste0(summary_type, "(x = ", column_names, function_exp)
```

2022-12-05 08:39 UTC, lloyddewit approved these changes

2022-12-05 23:41 UTC, rdstern reviewed
@lilyclements and @lloyddewit I wonder what has happened.  I thought it worked before.  Now when I try with the Dodoma data.  I first got:

![image](https://user-images.githubusercontent.com/11226469/205767339-c2b11c58-1d79-4d07-b763-2850b32b54ff.png)

Oddly it did give me the sd!  When I asked for more I got an error:
Here is the dialogue:
![image](https://user-images.githubusercontent.com/11226469/205767527-44f40644-0fae-4469-a5f2-5c06d4c3fc17.png)
And it gave me:

![image](https://user-images.githubusercontent.com/11226469/205767714-381bac53-5caa-454d-8271-16cbf47e8c8c.png)

I wondered if that was caused, because there was no factor - but that had worked before.  I got the same error when I added the factor.

I tried the script and noticed that the key line was repeated twice, though I think this might now be caused by other changes?

```
# Code généré par la boîte de dialogue, Frequency/Summary Tables

summary_table <- data_book$summary_table(data_name="dodoma", columns_to_summarise="date", treat_columns_as_factor=FALSE, j=1, summaries=c("summary_mean", "summary_max", "summary_min", "summary_count_non_missing", "p25", "p75", "summary_median"))

summary_table <- data_book$summary_table(data_name="dodoma", columns_to_summarise="date", treat_columns_as_factor=FALSE, j=1, summaries=c("summary_mean", "summary_max", "summary_min", "summary_count_non_missing", "p25", "p75", "summary_median"))
last_table <- (mmtable2::mmtable(data=summary_table, cells=value) + mmtable2::header_left_top(variable='summary-variable') + mmtable2::header_top_left(variable=month_abbr))
data_book$add_object(data_name="dodoma", object_name="last_table", object_type_label="table", object_format="html", object=last_table)
data_book$get_object(data_name="dodoma", object_name="last_table")
rm(list=c("last_table", "summary_table"))

```

2022-12-07 12:17 UTC, lilyclements commented
@rdstern the issue is because of the missing values. If you check "Omit missing values" does this still occur?

@rdstern looking at the code you posted, we have `month_abbr` in the `mmtable2` part of the code but not in the `data_book$summary_table` bit of the code. I think therefore the issue is in the visual studio code not reading in the arguments in the factors receiver?

2022-12-07 13:12 UTC, rdstern commented
@lilyclements aaah I forgot about the missing possibility - I'll check that again.  Sorry.

2022-12-12 06:21 UTC, rdstern approved these changes

2022-12-12 08:22 UTC, lloyddewit approved these changes

2022-12-12 08:28 UTC, lloyddewit commented
> @lilyclements Thank you for this PR. The PR title is automatically included in the release notes, so it should be meaningful for the user, rather than a technical description of the change. Can you think of a PR title that makes clear to the user which bug(s) have been fixed? Thanks

I changed the PR title to reflect what I think has improved for the user. If I misunderstood, then please let me know, thanks

2022-12-12 08:28 UTC, merged

2022-12-13 18:07 UTC, lilyclements commented
> I changed the PR title to reflect what I think has improved for the user. If I misunderstood, then please let me know, thanks

Apologies I missed this comment. Thank you for the title improvement