Added some modifications on the Bar and Pie Chart dialog.
africanmathsinitiative/R-Instat pull request #7928
Opened 2022-10-21 10:20 UTC by MeSophie

Fixes issue #6726.
 I noticed that Part a) and b) was already done. 

![image](https://user-images.githubusercontent.com/106779233/197173497-ed840ebb-ecde-446c-a756-5a608d2b17be.png)

![image](https://user-images.githubusercontent.com/106779233/197173587-4a2d3705-773a-4aaf-9341-0aad68038dac.png)
 @

2022-10-24 07:41 UTC, N-thony commented
@anastasia-mbithe can you peer review this?

2022-10-25 06:03 UTC, anastasia-mbithe commented on instat/dlgBarAndPieChart.vb
> +    End Sub
@MeSophie, remove these empty subs

2022-10-25 06:04 UTC, anastasia-mbithe commented on instat/dlgBarAndPieChart.vb
> +                'ucrInputReorderX.Visible = False
Remove this line too

2022-10-25 06:05 UTC, anastasia-mbithe commented on instat/dlgBarAndPieChart.vb
> +                'ucrInputReorderX.Visible = True
Remove this line since its not used

2022-10-27 11:34 UTC, N-thony commented
@anastasia-mbithe are you done reviewing this?

2022-10-31 06:56 UTC, anastasia-mbithe approved these changes

2022-11-08 13:53 UTC, anastasia-mbithe approved these changes

2022-11-18 08:27 UTC, rdstern approved these changes
Seems ok now

2022-11-21 11:31 UTC, lloyddewit requested changes
@MeSophie Thank you for the changes. I just have one small suggested change. I would have made it myself but I wanted to double-check with you that it's OK.
Thanks

2022-11-21 11:31 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +        ucrChkReorderFrequency.SetText("Rorder Frequency")
Should this be:
```suggestion
        ucrChkReorderFrequency.SetText("Reorder Frequency")
```

2022-11-21 15:03 UTC, MeSophie commented
> @MeSophie Thank you for the changes. I just have one small suggested change. I would have made it myself but I wanted to double-check with you that it's OK. Thanks

Thanks @lloyddewit . It's done.

2022-11-22 09:44 UTC, lloyddewit approved these changes

2022-11-22 09:44 UTC, merged