Fixed bug on displaying big number in data view
africanmathsinitiative/R-Instat pull request #7937
Opened 2022-10-27 08:18 UTC by N-thony

Fixes (partially) #7812 
@rdstern have a look of what we have now, when I use your example by creating a big number with `2^x1-1` in the corresponding issue I get this in the grid, with `Scientific = FALSE`
![image](https://user-images.githubusercontent.com/68591383/198229842-5c453303-ce00-4c43-807b-44eee5f569fa.png)

So, here when we set `Scientific = TRUE` we get the `e-notation` where the character are more than 9, you can see from row 30
![image](https://user-images.githubusercontent.com/68591383/198230148-e0858d5c-594a-4fd4-a998-11420b6a5646.png)

2022-10-27 08:36 UTC, N-thony commented
@lilyclements could we have a quick chat on this?

2022-10-27 08:36 UTC, rdstern commented
@N-thony that's good that it is so easy, but I also did like the option where the whole variable was in scientific.  For teaching I suggest it is useful to have the "all numbers scientific" option we had before.  I also like the FALSE option - where we can display very large numbers in non-scientific - and that's what Excel doesn't have!

So I suggest we need 3 options.  Is it possible for there to be FALSE and TRUE as before and NA as well!  If so, then NA would be your solution.  The message would also have to change when you make a mistake.  Perha[ps there could be a tooltip on the heading `Type T or TRUE for scientific, F or FALSE for numeric and N or NA for a mixture`.

2022-10-27 08:44 UTC, N-thony commented
> @N-thony that's good that it is so easy, but I also did like the option where the whole variable was in scientific. For teaching I suggest it is useful to have the "all numbers scientific" option we had before. I also like the FALSE option - where we can display very large numbers in non-scientific - and that's what Excel doesn't have!
> 
> So I suggest we need 3 options. Is it possible for there to be FALSE and TRUE as before and NA as well! If so, then NA would be your solution. The message would also have to change when you make a mistake. Perha[ps there could be a tooltip on the heading `Type T or TRUE for scientific, F or FALSE for numeric and N or NA for a mixture`.

@rdstern sounds good

2022-10-27 10:41 UTC, lilyclements commented
@N-thony did you want a chat about this or has it been cleared up?

2022-10-27 10:56 UTC, N-thony commented
> @N-thony did you want a chat about this or has it been cleared up?

@lilyclements let me try it again what @rdstern suggested now before your review.

2022-11-04 07:56 UTC, N-thony commented
> and N or NA for a mixture

@rdstern could you re-test?
@lilyclements can you review?

2022-11-05 11:00 UTC, rdstern submitted a review, later dismissed
@N-thony looks really good

2022-11-06 09:43 UTC, lloyddewit requested changes

2022-11-06 09:43 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +        #  format(data[[i]], digits = decimal_places[i], scientific = is_scientific[i])
```suggestion
```

2022-11-06 09:43 UTC, lloyddewit commented on instat/static/InstatObject/R/stand_alone_functions.R
> +              temp_data <- append(temp_data, format(val, digits = decimal_places[i], scientific = is_scientific[i]))
what's the difference between lines 31 and 33?

2022-11-06 09:43 UTC, lloyddewit commented on instat/ucrColumnMetadata.vb
>                  End If
replace this if-else structure with a select-case ?

2022-11-16 17:48 UTC, rdstern approved these changes
Still seems fine.  Must remember to include this property in the help.

2022-11-21 11:19 UTC, lloyddewit approved these changes

2022-11-21 11:21 UTC, merged