Minor improvement in New Dataframe dialogue
africanmathsinitiative/R-Instat pull request #7964
Opened 2022-11-15 05:35 UTC by N-thony

Fixes #7957 
@berylwaswa can you test this? Thanks.

2022-11-16 17:02 UTC, rdstern submitted a review, later dismissed
@N-thony I am approving, because it does solve the problem that we found.  So it could be merged.
But there are also problems with the defaults of letters(1,10) and LETTERS(1,10) that you may want to resolve at the same time.
There are 2 problems with those options:
a) when they are used they currently only work if the length of the data frame is a multiple of 10.  It usually will be, but if you put the usual `rep` round it, then it would always work. 
b) They won't work, when the variable is numeric or integer.  So check if they are set.  I suggest if they are set and the type is numeric or integer, you make that variable into character instead.  
c) Also they won't work if the type is set to be a factor and you have set the levels.  So, again, check that and make it a character variable instead.

2022-11-21 10:50 UTC, lloyddewit requested changes
@N-thony Thanks, just 1 samll comment. Will you also make the changes requested by @rdstern?

2022-11-21 10:50 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +            Dim iRowDefaultIndex As Integer = dataTypeGridView.CurrentRow.Cells("colDefault").RowIndex
these are only used on line 608.
Move these lines into the line 606 `If` block.

2022-11-21 11:01 UTC, N-thony commented
> @N-thony Thanks, just 1 small comment. Will you also make the changes requested by @rdstern?

@lloyddewit I will make them later.

2022-11-21 15:35 UTC, rdstern approved these changes
Fine

2022-11-22 11:01 UTC, lloyddewit approved these changes

2022-11-22 11:02 UTC, merged