Added Expand button to the Stack dialogue
africanmathsinitiative/R-Instat pull request #7967
Opened 2022-11-18 09:17 UTC by Vitalis95

Fixes #7941 
@rdstern , @N-thony @lloyddewit , the button converts a frequency table to a data frame representing individual observations in the table. I have convert the dataframe generated from characters to factors .

2022-11-18 10:24 UTC, rdstern commented
@Vitalis95 this is looking promising.
a) Could you change Factor to Factor(s)

b) I don't see the frequencies, f. to put into the dialogue.  Notice they are numeric columns here.  I think they have to be a factor to see them.  I am happy for the factor to be a factor, but the frequencies is usually numeric.
![image](https://user-images.githubusercontent.com/11226469/202678070-465c6ac4-2df8-44f0-b347-ad9069a88667.png)

c) So I made the frequencies into a factor.  Then I could use it and got this error:

![image](https://user-images.githubusercontent.com/11226469/202678432-182b5b73-eade-4fb2-b065-34a27aa3188f.png)

I tried making the variable name freq and it still gave me the same error.

Finally I tried (stupidly) with x instead of f (or freq) twice and the dialogue worked, but with odd answers, of course!  So I wonder if you need to tell the vcdExtra the frequencies in the data frame you make?

2022-11-18 10:47 UTC, Vitalis95 commented
@rdstern ,the frequencies is also included first in the multiple receiver `Factor(s):`, before adding it to single receiver, this is because the columns are made into a data frame and then handed to the function as you had indicated in the issue.

2022-11-18 11:01 UTC, rdstern commented
@Vitalis95 that now works fine.

Except I don't want users to have to put the frequencies into the factor(s) receiver.  That's very confusing.
Why can't I just put it into the frequencies receiver and you then add it into the data frame, before giving it to the vcdExtra function?

2022-11-18 11:18 UTC, Vitalis95 commented
I am including @N-thony in the conversation, after we discussed he suggested we implement that way- like in Transpose dialog where the variable in single receiver is included first in multiple receiver. @N-thony, is there a way we can implement above suggestion? here is that function; 
 `expand.dft(x, frq="Freq")`  where `x`  is a table object, or a data frame in frequency form containing factors and one numeric variable i.e `frq` - the variable in frequencies receiver

2022-11-21 08:33 UTC, Vitalis95 commented
@rdstern , have a look at now. Thanks

2022-11-21 15:26 UTC, rdstern approved these changes
@Vitalis95 and @N-thony it seems to work fine now.
I tried with @berylwaswa school data from 40 children - and fine.
Then I tried with abortion data, from vcdExtra which had 3 factors, plus the frequencies.  It works with all 3 factors, as well as when I put only a single factor.
Great!  I hope it can be merged soon.  
Does a new facility like this imply the translation should also be added.  If so, then that could come later?

2022-11-25 11:36 UTC, lloyddewit requested changes

2022-11-25 11:36 UTC, lloyddewit commented on instat/dlgStack.vb
> +            End If
Lines should not go past column 100.
Is this more readable?
```suggestion
            ucrBase.OKEnabled(Not ucrReceiverExpand.IsEmpty _
                              AndAlso Not ucrReceiverFrequency.IsEmpty _
                              AndAlso ucrSaveNewDataName.IsComplete)
```

2022-11-25 11:36 UTC, lloyddewit commented on instat/dlgStack.vb
> +        If ucrReceiverExpand.lstSelectedVariables.Items.Count > 0 Then
Follow 'happy path stays left' principle?
```
        If ucrReceiverExpand.lstSelectedVariables.Items.Count <= 0 Then
            Exit Sub
        End If
```

2022-11-25 11:36 UTC, lloyddewit commented on instat/dlgStack.vb
> +        Dim lstVariables As New List(Of String)
declare on line 247?
```suggestion
```

2022-11-25 11:36 UTC, lloyddewit commented on instat/dlgStack.vb
> +            lstVariables = ucrReceiverExpand.GetVariableNamesAsList()
```suggestion
            Dim lstVariables As List(Of String) = ucrReceiverExpand.GetVariableNamesAsList()
```

2022-11-26 10:59 UTC, Vitalis95 commented
@lloyddewit , have a look at it. Thanks

2022-11-26 16:33 UTC, rdstern requested changes
@Vitalis95 still looks good.  Except that when you change dataframe it correctly clears the receivers, but it should also go back to the first control - the one for the factors.  Currently it stays on the Frequencies.

2022-11-28 09:07 UTC, Vitalis95 commented
@rdstern , have look at it. Thanks

2022-11-30 16:31 UTC, rdstern commented
@Vitalis95 it would be good to merge this one, if you have time for the small change above.

2022-12-01 06:29 UTC, Vitalis95 commented
@rdstern , I did made the above change- when dataframe is changed, it correctly clears the receivers and  goes back to the first control and it works fine from my side. Thanks

2022-12-01 06:43 UTC, rdstern commented
@Vitalis95 thanks.  Let me check

2022-12-01 06:47 UTC, rdstern approved these changes
@Vitalis95 great.  Hope this passes the @lloyddewit tests, so it can be merged for the current release

2022-12-01 10:44 UTC, lloyddewit approved these changes

2022-12-01 10:45 UTC, merged