Adding summaries to frequency data.
africanmathsinitiative/R-Instat pull request #7970
Opened 2022-11-21 09:31 UTC by anastasia-mbithe

Fixes #7945 and also fixes #7929

@rdstern, this is ready for testing.

2022-11-21 12:36 UTC, rdstern requested changes
@anastasia-mbithe this looks great already.
a) In the frequencies the only one that seems not to work is the mode1.  Could you use the same function as in the  in the ordinary summary, where it is statip::mfv1( )
b) The quantile could (I think) be made simpler in the frequencies part by quantile(x=rep( x, f ), probs=0.2, na.rm=TRUE) - so leaving the additional bit out.
c) Could you add the arguments in the frequencies if the corresponding checkbox is ticked.  Then they could become, for example  sum(x=rep(x= ,times=   ), na.rm=TRUE)
d) In the ordinary summaries they have the na.rm=TRUE when you ask for the arguments, but not otherwise.  Could you add it in - as you have for the frequencies andway.
e) I thought we might not need tooltips for the frequencies.  But have `complete the command by rep(d ,f) for data in variable called d and frequencies in f`.  That's for all except the propn and the quantile.  For propn `Complete as rep(d > 50, f)) to give the proportion of values in variable d more than 50`.  For quantile give `Complete as rep(d ,f), prop=0.2), for example, for the 20% point.`

2022-11-22 12:15 UTC, anastasia-mbithe commented
@rdstern, the issues/changes are fixed. Kindly have a look.

2022-11-24 16:26 UTC, rdstern commented
@anastasia-mbithe almost there:
a) the new mode1 in the frequencies needs the rep also  included.  `statip::mfv1(rep(x,f) , na.rm=TRUE)`
b) You have missed the na.rm=TRUE from the ordinary `mode1` and `kurtosis`.
c) Could you add the equivalent - which is `use="na"` for the cor and cov keys

2022-11-25 07:11 UTC, anastasia-mbithe commented
@rdstern, should we also change the value of the parameter "use", in cor and cov keys when we have the show parameters checkbox checked? currently, we have use= "everything"

2022-11-25 07:21 UTC, rdstern commented
@anastasia-mbithe good spot - we should be consistent.  Or should we change the Use to everything above?  I would just like it to cope with missing better than always giving NA.  I chose that option, because it said it copes with no data - rather than giving an error.

But now I tried "everything" and "na" with lots missing and I think I prefer being consistent with "na".

2022-11-25 14:31 UTC, rdstern approved these changes
Great

2022-11-25 14:53 UTC, lloyddewit approved these changes
@anastasia-mbithe Thank you, this looks good to me.
I just had one small comment but it's so small I suggest we ignore it, and I'll go ahead and merge.

2022-11-25 14:53 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdFreqMode1, "complete the command by rep(d ,f) for data in variable called d and frequencies in f")
Can we remove the duplication by using a constant?
```
Const strCmdToolTip As String = ""complete the command by rep(d ,f) for data in variable called d and frequencies in f"
ttCalculator.SetToolTip(cmdFreqDistinct, strCmdToolTip)
ttCalculator.SetToolTip(cmdFreqIQR, strCmdToolTip)
'etc.
```

2022-11-25 14:53 UTC, merged