Added apsimx package
africanmathsinitiative/R-Instat pull request #7976
Opened 2022-11-23 09:44 UTC by MeSophie

Fixes #7974.
@N-thony and @lloyddewit please can you have a look? Thank you.

2022-11-23 09:46 UTC, N-thony approved these changes
@MeSophie great, @lloyddewit over to you

2022-11-23 09:47 UTC, N-thony commented
@MeSophie can you resolve the conflicts?

2022-11-23 10:46 UTC, MeSophie commented
> @MeSophie can you resolve the conflicts?

@N-thony  it is okay now.

2022-11-23 12:19 UTC, MeSophie commented
> @rdstern I think the package need in #7963 can be included in this PR. @MeSophie we can have a quick chat on how to add it.

@N-thony okay

2022-11-23 13:26 UTC, MeSophie commented
> @rdstern I think the package need in #7963 can be included in this PR. @MeSophie we can have a quick chat on how to add it.

@N-thony I'm done

2022-12-29 16:50 UTC, rdstern submitted a review, later dismissed
@MeSophie I am not sure what I can test here?  I am approving, because the examples still work for me - but I installed apsimx ages ago anyway.

2022-12-30 08:37 UTC, lloyddewit requested changes
@MeSophie Thanks for adding this pacakage. One open question.

2022-12-30 08:37 UTC, lloyddewit commented on instat/static/InstatObject/R/install_packages.R
> -    "vcdExtra"
Issue #7974 does not mention these pacakages. What's the reason for removing them?

2023-01-09 08:25 UTC, MeSophie commented on instat/static/InstatObject/R/install_packages.R
> -    "vcdExtra"
> Issue #7974 does not mention these pacakages. What's the reason for removing them?

@lloyddewit I didn't notice it. I did it by mistake.

2023-01-09 09:47 UTC, lloyddewit requested changes

2023-01-09 09:47 UTC, lloyddewit commented on instat/static/InstatObject/R/install_packages.R
> +     "coin",
```suggestion
    "coin",
```

2023-01-09 09:48 UTC, lloyddewit approved these changes

2023-01-09 09:53 UTC, merged