Maintaining the selected sheet in the Data View after reordering
africanmathsinitiative/R-Instat pull request #8007
Opened 2022-12-06 05:34 UTC by N-thony

Fixes #7550
@rdstern as discussed I have improved the code and also fixed the small bug in the `Data View` to maintain the selected sheet even though reordering is applied. Please, take a look. Thanks.

2022-12-06 05:58 UTC, rdstern approved these changes
@N-thony I am really pleased you have returned to this issue, because sorting out the reordering of the data frames was one of the last of these operations that seems now to be working.
It seems to be fine, so if @lloyddewit is ok, then I would be happy to merge it.  
I am not sure the title of the pull request is totally appropriate though?  When I tried, the sheets were reordered as I had wished, and the last sheet always became the active sheet.  That's fine by me, but it isn't what I think of as "maintaining the selected sheet".

2022-12-06 06:16 UTC, N-thony commented
> @N-thony I am really pleased you have returned to this issue, because sorting out the reordering of the data frames was one of the last of these operations that seems now to be working. It seems to be fine, so if @lloyddewit is ok, then I would be happy to merge it. I am not sure the title of the pull request is totally appropriate though? When I tried, the sheets were reordered as I had wished, and the last sheet always became the active sheet. That's fine by me, but it isn't what I think of as "maintaining the selected sheet".

@rdstern sounds good, it works fine on my side, I have sent some screenshots on Skype

2022-12-06 10:18 UTC, lloyddewit requested changes
@N-thony Thanks, looks good, just a few open questions.

2022-12-06 10:18 UTC, lloyddewit commented on instat/ucrColumnMetadata.vb
> +        Dim strCurrWorksheet As String = If(_grid.CurrentWorksheet Is Nothing, Nothing, _grid.CurrentWorksheet.Name)
move to just above line 77?

2022-12-06 10:18 UTC, lloyddewit commented on instat/ucrColumnMetadata.vb
> +        _grid.ReOrderWorksheets(strCurrWorksheet)
if `strCurrWorksheet` is `Nothing`, then should we still call this sub?
Unfortunately, `ReOrderWorksheets()` has no summary comment so it's hard to understand what will happen.
Please could you investigate and comment if needed?

2022-12-06 10:18 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    Private Sub ReOrderWorksheets(strCurrWorksheet As String) Implements IGrid.ReOrderWorksheets
Please could you add a summary header (see comment below)?

2022-12-06 10:33 UTC, N-thony commented on instat/ucrColumnMetadata.vb
> +        Dim strCurrWorksheet As String = If(_grid.CurrentWorksheet Is Nothing, Nothing, _grid.CurrentWorksheet.Name)
anytime there is a change in the data frame we load it back from R to the Data View, in `AddAndUpdateWorksheets()` there is a sub on line 75 we always load the data from R and set it as a selected/current dataframe in the Data View, so to the keep the selected dataframe active before reordering, I'm using this temp variable `strCurrWorksheet ` on line 66

2022-12-06 10:48 UTC, N-thony commented
@lloyddewit I have made the changes, please take a look. Thanks.

2022-12-07 22:35 UTC, rdstern submitted a review, later dismissed
@N-thony seems to work fine now!

2022-12-11 10:34 UTC, lloyddewit commented
@N-thony Thank you for the changes. There is just one open comment above. If you can add the summary header, then we can merge, thanks

2022-12-11 10:45 UTC, N-thony commented on instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
> +    Private Sub ReOrderWorksheets(strCurrWorksheet As String) Implements IGrid.ReOrderWorksheets
@lloyddewit this is done

2022-12-11 14:11 UTC, lloyddewit approved these changes
@N-thony Thank you for the final changes.
The new header is the same as the sub name, so it doesn't add any value.
I was hoping that the header would explain more about the what the sub does. However, I looked through the subs again and with the new code comments you added, it's easier for a developer to understand what's happening. So I'm happy to approve/merge.

2022-12-11 14:13 UTC, merged