Improved the displays of the lists and column type header
africanmathsinitiative/R-Instat pull request #8015
Opened 2022-12-13 05:58 UTC by N-thony

Fixes (partially) #8013 
@rdstern I have added the column type (S) for the list and also improved the display of lists in the grid. Take a look.

2022-12-14 11:06 UTC, N-thony commented
@rdstern I understand, I didn't check this example of sapply, let me look at it. Thanks

2022-12-14 16:15 UTC, N-thony commented
@rdstern this is seems to work fine. please have a look.
@ChrisMarsh82 please could you review this?

2022-12-15 10:58 UTC, ChrisMarsh82 commented
@N-thony Looks good. I like the way you have done this. Very neat.

2022-12-19 17:42 UTC, rdstern commented
@N-thony here is the error I get when editing.
I produced the list in the same way as usual (calculate > Integer > Divisors)
Then duplicated the variable.  That worked fine.
Then edited row 6 from 1, 2, 3  - I changed the 3 to 4.

It then complains that there is a string variable:

![image](https://user-images.githubusercontent.com/11226469/208486611-f64b7e0a-0ac8-4dde-8637-c2b11625430e.png)

As I mentioned somewhere, I am no longer worried if the display in reogrid is different to the R-viewer,  So you may wish to display it in reogrid as c(1, 2, 3) - if that makes the editing and subsequent translation for R easier?

2022-12-23 06:44 UTC, N-thony commented
> @N-thony here is the error I get when editing. I produced the list in the same way as usual (calculate > Integer > Divisors) Then duplicated the variable. That worked fine. Then edited row 6 from 1, 2, 3 - I changed the 3 to 4.
> 
> It then complains that there is a string variable:
> 
> ![image](https://user-images.githubusercontent.com/11226469/208486611-f64b7e0a-0ac8-4dde-8637-c2b11625430e.png)
> 
> As I mentioned somewhere, I am no longer worried if the display in reogrid is different to the R-viewer, So you may wish to display it in reogrid as c(1, 2, 3) - if that makes the editing and subsequent translation for R easier?

@rdstern this seems to work fine now? Please have a look. Thanks

2022-12-23 08:02 UTC, rdstern submitted a review, later dismissed
@N-thony that is great, so I am approving.  
1. I found I could replace a list by NA, but it complains if I make an element in the list into NA.  If quick, perhaps you could check this?  But otherwise let's stop for now.
2. We now need other dialogues to be able to produce lists.
3. I would also like lists be strings and possibly also matrices in the future.

But let's get this merged, and also the keyboard first.
It is really nice to be able to discuss lists, with this special case, and also to be able to use sapply in this way.

2022-12-23 08:23 UTC, N-thony commented
> @N-thony that is great, so I am approving.
> 
> 1. I found I could replace a list by NA, but it complains if I make an element in the list into NA.  If quick, perhaps you could check this?  But otherwise let's stop for now.
> 2. We now need other dialogues to be able to produce lists.
> 3. I would also like lists be strings and possibly also matrices in the future.
> 
> But let's get this merged, and also the keyboard first. It is really nice to be able to discuss lists, with this special case, and also to be able to use sapply in this way.

@rdstern I have fixed 1. and I agree for 2. and 3. which will help on improving this.

2022-12-23 08:36 UTC, rdstern approved these changes
Great

2022-12-23 08:46 UTC, lloyddewit requested changes
@N-thony Thank you, looks great. Just a couple of open questions

2022-12-23 08:46 UTC, lloyddewit commented on instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
>          If bWithQuotes Then
will a list of vectors ever be surrounded by quotes?
If not, then should we change to `ElseIf`?
```suggestion
        ElseIf bWithQuotes Then
```

2022-12-23 08:46 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +                End If
I understand that this code is setting `strData` to the text inside the brackets for strings with a format like `<txt>(<txt>)`.
Does it need to cope with strings in different formats, e.g. nested brackets? or no chars perceding the first '('?
Please could you add a comment with examples to help other developers understand the intention of this code?

2022-12-23 08:56 UTC, rdstern submitted a review, later dismissed
@N-thony great.  I approve again.  I just note that the R viewer displays the first element as an empty list, while you display it as 0?  Should it be 0?
If it is empty I would also be happy if it was made into NA. 
Should it be 0?  I tried deleting it, and it complained.  Could it make NA when deleted?

2022-12-23 09:08 UTC, N-thony commented on instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
>          If bWithQuotes Then
@lloyddewit if I commit this it means we will never pass the parameter value on line 333 or 335 if bListOfVector is True.
bListOfVector is helping only is just helping to change the parameter value i.e strNewValue to the format needed to replace a value if vector in the dataframe list column.

2022-12-23 09:23 UTC, lloyddewit commented on instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
>          If bWithQuotes Then
yes, I agree, thanks for checking

2022-12-23 09:24 UTC, N-thony commented
@rdstern I tried to delete and it works fine.
![image](https://user-images.githubusercontent.com/68591383/209307131-645ed77f-f69c-4b55-91e7-1ff06faacbaa.png)

When I display the data with the grid in RStudio, the first value is numeric(0) so for the nicer display as suggested in the issue, I found that numeric(0) returns a numeric vector of `length 0, `so when you add anything
to it you get the same result (it's basically a numeric NULL). I think it will be good to display as NA

2022-12-23 09:27 UTC, rdstern commented
Great - I agree

2022-12-23 09:34 UTC, N-thony commented
@rdstern I have made the changes as suggested replacing numeric(0) by NA.
@lloyddewit I resolved your comment above.
Please have look. Thanks

2022-12-23 10:27 UTC, lloyddewit commented
> @lloyddewit I resolved your comment above.

@N-thony I think there's still one unresolved comment above

2022-12-23 10:32 UTC, N-thony commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +                End If
@lloyddewit I'm just checking the first bracket because I think if that exist then there is a closing one.
I have also added some comments for the intention of these codes

2022-12-23 10:57 UTC, lloyddewit approved these changes

2022-12-23 10:58 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge, thanks

2022-12-23 23:08 UTC, rdstern approved these changes

2022-12-26 07:25 UTC, rdstern reviewed
@N-thony I have now found a new minor oddity in the solution, so far.
If an operation on a list produces another list, then the NA is not carried forward.
Here is an example (that I have fixed):
![image](https://user-images.githubusercontent.com/11226469/209516823-4a60b467-a162-4189-b0e2-2160f8b9268b.png)

It is as follows:
a) Usual new data frame, with 100 rows and x1 1 to 100.
b) x2 = Calculations > Integer > divisors put in x2.
c) calc is sapply (x2, with the key digitsum in the same keyboard).  

This gives the variable `calc`, but with the NA value as blank.
d) Then `sapply(calc,sum)` doesn't work - and says it can't, because calc is a list.
e) When I delete cell 1 in calc, then it replaces the blank in calc by NA, and then it works.

So a small tweak is needed in your code, when a LT variable produces another LT variable.

I would also like to be able to to do both steps together, i.e. 

`sapply(sapply(x2,DescTools::DigitSum),sum)`

and this currently doesn't work.  (by the way if sum is replaced by mean, then it does work!)

2022-12-26 07:27 UTC, rdstern requested changes
@so I have withdrawn my approval for now!

2022-12-28 10:00 UTC, rdstern commented
@N-thony I have also found another interesting "feature" with your code.
Try the usual new data frame, length 100, with x1 as 1 to 100.  Then use calc > integer > factorize.  The result is shown in x2 below:

![image](https://user-images.githubusercontent.com/11226469/209793666-a3975337-7721-486e-a448-a7105fbc9829.png)

You see for 2 , 8 and 9 the separator is a colon (:) rather than a comma.  Don't spend too long on this, because it doesn't seem to cause any problems. It is still recognised as a list of 2 numbers.

2022-12-29 12:34 UTC, N-thony commented
> sapply(x2,DescTools::DigitSum)

@rdstern there is an oddity in the data produced by example with calc = `sapply(x2,DescTools::DigitSum)` i.e item c) the value in the first cell is `list()` and I think this needs also to be displayed as `NA` since there is no value but the difference wuth `numeric(0)` here we need to edit the data replace `list()` by `NA`, what do you think? 
`calc <- data_book$get_columns_from_data(data_name="data", col_names="calc")`
`calc[1]`, from this observation you cannot directly run `sapply(sapply(x2,DescTools::DigitSum),sum)` you will get the error in item d)
![image](https://user-images.githubusercontent.com/68591383/209951114-6a5a61bf-8e98-4b15-a204-1711d103e0f3.png)

2022-12-29 12:38 UTC, N-thony commented
> > sapply(x2,DescTools::DigitSum)
> 
> @rdstern there is an oddity in the data produced by example with calc = `sapply(x2,DescTools::DigitSum)` i.e item c) the value in the first cell is `list()` and I think this needs also to be displayed as `NA` since there is no value but the difference wuth `numeric(0)` here we need to edit the data replace `list()` by `NA`, what do you think? `calc <- data_book$get_columns_from_data(data_name="data", col_names="calc")` `calc[1]`, from this observation you cannot directly run `sapply(sapply(x2,DescTools::DigitSum),sum)` you will get the error in item d) ![image](https://user-images.githubusercontent.com/68591383/209951114-6a5a61bf-8e98-4b15-a204-1711d103e0f3.png)

also, if try to change the first cell of `x2` to `NA` in the data by deleting the cell you get the following error. So I'm not sure if we should edit the data when we `numeric(0)` or `list()`?
![image](https://user-images.githubusercontent.com/68591383/209951911-515dcc0b-a7fe-46ec-a8a2-888aaa5ccffe.png)

2023-01-05 16:14 UTC, rdstern submitted a review, later dismissed
@lloyddewit I am approving as it seems sort of ok now & we need to move on. 
I still notice that the R viewer gives a blank, where R-Instat gives NA for a list of length zero.  If the code is ok, then let's accept.

2023-01-06 12:22 UTC, rdstern commented
@N-thony that's an improvement, but there is still a problem.  If I edit any entry in the list then that row doesn't work anymore.  Even if I just go into a row to edit, but don't change anything then it doesn't work.

I therefore asked Danny and David, if we are slightly opening a can of worms and should give up on all this.  They feel the opposite - so we continue.

The LT column is a list column and each element of the list is a numeric vector.  I think when sent to R these elements have a c(  ) round them, i.e. they look more like the way we used to display them in the grid.  
The R viewer distinguishes between that and the way the contents of the list are displayed to the user.

So, I am now more relaxed about having the display in reogrid different from the R-viewer than before - if that would also become simpler for you to code and clearer for the user.

But if we do display as you have now - that is still not quite the same as the R viewer - so the top element in reogrid is now 0, while it is blank in the R-viewer.   Anyway we should be able to change a value in reogrid, and it still works.  (Once we can do that I am particularly keen to see what happens if one of the elements is a missing value.)

I am happy that you are asking @ChrisMarsh82 to review the final code.  If you are not sure on the change to make now, and Chris is also unsure, then perhaps he could check with Danny or David.

In our statistical ideas, this is going to help us explain and discuss multiple response questions.

We will stop for now with these numeric vectors, but later will then include character vectors as the elements.  But that will be in another pull request.

And as a general idea, we are not taking a small step towards tibbles

2023-01-11 06:19 UTC, N-thony commented
@ChrisMarsh82 I have now made the changes I thought regarding Roger's comments above. Could you have a look?
@rdstern we can have a quick call about  what you have reported above?

2023-01-11 09:16 UTC, rdstern requested changes
The display seemingly looks fine now - except it is giving the wrong answers!  I compare your display with the R-viewer here and you see that you are now just keeping the first digit of each number.

![image](https://user-images.githubusercontent.com/11226469/211765632-c9b2d8d8-3fa0-4e03-8277-58f0816a5353.png)

I guess this is a tricky task and keep thinking that @ChrisMarsh82 or @volloholic may need to add explanation.  It is important, but I am concerned at the time it is taking you.

I am delighted though that you must now have your new machine working.  That was quick!

2023-01-11 16:34 UTC, N-thony commented
@ChrisMarsh82 I used the Regex expressions with this pattern `.Regex.Matches(strData, "\d+|\bN\S*A\b")`. I think this is much more easier or better

2023-01-12 08:24 UTC, rdstern submitted a review, later dismissed
Great - that (almost?) seems to work.  I tried with a column of length 100 and with the pascal function - that will become a key.

`lapply( x1, function(x) {lapply(x, function(i) {choose(i, 0:i)})})`

I have approved - unless you want to try a last tweak to your code?  So, first, here is the good news:

![image](https://user-images.githubusercontent.com/11226469/212013641-5a1ab11a-8213-4379-bb14-1d03968ab718.png)

It looks fine, doesn't it?  Very nice.  And it doesn't go into scientific notation either - which the R-viewer does.  

But later in the sequence there is a puzzle for me.  I am in the middle where the numbers are very large.  I assume there is an oddity here with the E notation?  Maybe if you recognised e and + in the regex it would become clear?  By the way I am having more trouble in the R-viewer now, than in your reogrid!

![image](https://user-images.githubusercontent.com/11226469/212015376-1b91d56d-f55b-4753-a07a-2ffbf47141c6.png)

2023-01-12 09:56 UTC, ChrisMarsh82 reviewed
@N-thony

2023-01-12 09:56 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +    Private Function GetVector(strData As String) As String
I would like to change how this works. Currently, you loop through all the values within the string. This could be inefficient if there are lots of values in the string. Also, GetVector does not really describe what the procedure is doing.
This is a proposed procedure that could be used instead:
`Private Function GetInnerBracketedString(strData As String) As String`
`    Dim strOutput As String = Strings.Left(strData, InStr(strData, ")") - 1) 'Get the first right bracket`
`    strOutput = Mid(strOutput, InStrRev(strOutput, "(") + 1) 'Get the last left braket`
`    Return strOutput`
` End Function`

2023-01-12 10:04 UTC, N-thony commented
@ChrisMarsh82 I just notice a small issue that the grid get bigger as the number do
![image](https://user-images.githubusercontent.com/68591383/212037530-2615fe3e-2c63-4a35-8de9-6b63dc74af37.png)

2023-01-12 10:14 UTC, ChrisMarsh82 commented
> @ChrisMarsh82 I just notice a small issue that the grid get bigger as the number do 
The issue if it doesn't do this it could be more misleading. It looks like only a certain amount of data can fit on a row in the ReoGrid and it always shows the last row. therefore if it doesn't grow you would see something like this.
![image](https://user-images.githubusercontent.com/84872334/212039295-c293fe3a-075d-4d0f-b6e6-5249c11e11e2.png)
Row 44 now looks like it only contains '44, 1' when actually that's just the last 2 values.

If this is a problem for users we could add a text box at the top of the screen to show the value in the current cell?

2023-01-12 10:15 UTC, ChrisMarsh82 approved these changes

2023-01-12 13:21 UTC, merged

2023-01-13 08:09 UTC, rdstern commented
@N-thony and @ChrisMarsh82 sorry I was too quick in approving and now seem to have a bug in the merged version.  I only tested with the new pascal code and that works fine.

So I had a new data frame of length 100 with x1 1 to 100 and then the code:

`lapply( x1, function(x) {lapply(x, function(i) {choose(i, 0:i)})})`

This (in the merged version) still correctly, (and impressively) gives as follows:

![image](https://user-images.githubusercontent.com/11226469/212269697-f4dbd93a-66c9-4d92-84fd-24259b9aab3e.png)


But then the command shown above, i.e. DescTools::Divisors(x1) - which was working before - gives an error and stops R-Instat.

![image](https://user-images.githubusercontent.com/11226469/212270015-66363508-092f-4334-b479-9afe54a4b3e2.png)

2023-01-13 09:34 UTC, ChrisMarsh82 commented
@rdstern - I have a fix but I want to check. The code is designed to get anything for the inner brackets (if they exist). Therefore c(1,2) will become 1,2 and numeric(0) will become 0. Is this correct or is there an example where we need to display the whole return string including the brackets?

2023-01-16 08:36 UTC, lloyddewit commented
@rdstern Thank you for the comment above. This PR is merged so there's a risk that this comment will be overlooked.

Does this comment apply to one of the issues linked with this PR?
Or is the comment related to the new PR @ChrisMarsh82 made (#8050 )?

Should we move the comment?