Included the new R Help button on all calculator keyboards
africanmathsinitiative/R-Instat pull request #8032
Opened 2022-12-23 13:57 UTC by derekagorhom

fixes #8031 
this PR is ready for review
![Screenshot (515)](https://user-images.githubusercontent.com/76208189/209347010-0e8fd858-a8a8-4aff-9417-f4ee4a474bcc.png)

I also added the `ContextMenuStrip` for the `List keyboard` (see above) so that it can be added when the keyboard is ready

2022-12-23 23:27 UTC, rdstern commented
@derekagorhom this looks great.  It all seems to work fine.  I am just being picky here, with the changes in the logical keyboard.  

![image](https://user-images.githubusercontent.com/11226469/209412969-92fce8a3-09e0-44aa-a281-e6333def48bf.png)

It already looks much better:
a) could you add a space in div (%/%)
b) could you line up the first 3 rows even more.  So the 3rd row lines with the first two.
c) And the first 3 rows (where there are 6 keys) line with the lower rows - so the end of the 3rd key in the top lines is the same as the end of the 2nd key in the bottom lines.

Then it can be merged.

2022-12-24 00:38 UTC, rdstern submitted a review, later dismissed
Excellent

2022-12-29 09:50 UTC, lloyddewit requested changes
@derekagorhom Thanks, looks good, just one comment

2022-12-29 09:50 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub WakefieldToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles WakefieldToolStripMenuItem.Click
This sub looks the same as the sub above. Could the sub above also handle the `WakefieldToolStripMenuItem.Click` event?

This comment also applies to most of the new subs below. Could some of the subs below be combined?

2022-12-29 10:49 UTC, derekagorhom commented on instat/ucrCalculator.vb
> +    Private Sub WakefieldToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles WakefieldToolStripMenuItem.Click
@lloyddewit i have made the changes, can you review it again

2022-12-29 11:40 UTC, lloyddewit requested changes

2022-12-29 11:40 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub cmdHelp_Click(sender As Object, e As EventArgs)
This sub doesn't seem to handle any events. Is it still needed or could it be deleted?

2022-12-29 11:40 UTC, lloyddewit commented on instat/ucrCalculator.vb
>      Private Sub GmpToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles GmpToolStripMenuItem.Click
If we add this event to the `cmdIntegerRHelp()` sub, then could we delete this sub?
```
    Private Sub cmdIntegerRHelp_Click(sender As Object, e As EventArgs) Handles cmdIntegerRHelp.Click, GmpToolStripMenuItem.Click
```

2022-12-29 11:40 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub WakefieldToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles WakefieldToolStripMenuItem.Click
Sorry if I wasn't clear. I was suggesting to add the `WakefieldToolStripMenuItem.Click` event to the sub above (see suggested change above).

2022-12-29 11:40 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub cmdWakefieldHelp_Click(sender As Object, e As EventArgs) Handles cmdWakefieldHelp.Click
Would this work?
```suggestion
    Private Sub cmdWakefieldHelp_Click(sender As Object, e As EventArgs) Handles cmdWakefieldHelp.Click, WakefieldToolStripMenuItem.Click
```

2022-12-29 16:08 UTC, derekagorhom commented
@lloyddewit i have made the changes

2022-12-30 09:17 UTC, lloyddewit requested changes
@derekagorhom Thanks, just one open question and then I think we can merge

2022-12-30 09:17 UTC, lloyddewit commented on instat/ucrCalculator.vb
>      Private Sub BaseToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles BaseToolStripMenuItem1.Click
can we delete this?

2022-12-30 09:42 UTC, derekagorhom commented on instat/ucrCalculator.vb
>      Private Sub BaseToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles BaseToolStripMenuItem1.Click
Sorry i missed that, it has been removed

2022-12-30 09:57 UTC, lloyddewit approved these changes

2022-12-30 09:58 UTC, lloyddewit commented
@rdstern If you can retest/approve, then we can merge, thanks

2023-01-05 13:46 UTC, rdstern approved these changes

2023-01-09 09:55 UTC, merged