Added a Pascal key to the Probability keyboard.
africanmathsinitiative/R-Instat pull request #8044
Opened 2023-01-10 06:46 UTC by anastasia-mbithe

Fixes #8036

2023-01-11 06:03 UTC, N-thony commented
@derekagorhom can you peer review this?

2023-01-11 08:59 UTC, rdstern requested changes
@anastasia-mbithe this works fine.  Just for uniformity, could you have pascal with a small P.  Then this can be merged - at least as far as I am concerned.  

I note the code here, because I would like to use it to check @N-thony changes in the display of lists.

`lapply( x1, function(x) {lapply(x, function(i) {choose(i, 0:i)})})`

I note that your display of the results for 1 to 100 has the c(  ) round it, but otherwise displays fine and only goes to scientific much later than the R-viewer.  I am happy to "delay" the change to scientific.

2023-01-11 15:46 UTC, rdstern approved these changes
Great

2023-01-11 18:26 UTC, derekagorhom approved these changes

2023-01-13 08:36 UTC, lloyddewit approved these changes

2023-01-13 08:37 UTC, merged