Implementing Plot Option for Line Plot
africanmathsinitiative/R-Instat pull request #8056
Opened 2023-01-16 13:24 UTC by derekagorhom

fixes (partly) #7556
replaces PR #7814

@rdstern  this PR is ready for review

2023-02-07 12:03 UTC, berylwaswa commented
The Plot options for the line plot are all enabled. And all the aesthetics and geom parameters are in place. 
The first option is the Plot Options and this is followed by each of the remaining options for that dialogue, but they are not in alphabetical order. @derekagorhom I think if you arrange them in alphabetical order it'll be okay.

2023-02-07 12:14 UTC, berylwaswa commented
The options are now well arranged in alphabetical order. @lloyddewit this looks fine now.

2023-02-07 13:03 UTC, lloyddewit commented on instat/dlgLinePlot.vb
> +    Private Sub PeakOptionsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles PeakOptionsToolStripMenuItem.Click
```suggestion
    End Sub
    
    Private Sub PeakOptionsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles PeakOptionsToolStripMenuItem.Click

```

2023-02-07 14:23 UTC, derekagorhom commented
@lloyddewit i have made the requested changes

2023-02-08 10:59 UTC, lloyddewit requested changes

2023-02-08 10:59 UTC, lloyddewit commented on instat/dlgLinePlot.vb
> +    Private Sub DumbbellOptionsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DumbbellOptionsToolStripMenuItem.Click
```suggestion
    End Sub
    
    Private Sub DumbbellOptionsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles DumbbellOptionsToolStripMenuItem.Click
```

2023-02-08 10:59 UTC, lloyddewit commented on instat/dlgLinePlot.vb
> +    Private Sub SmoothOptionsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles SmoothOptionsToolStripMenuItem.Click
```suggestion
    End Sub
    
    Private Sub SmoothOptionsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles SmoothOptionsToolStripMenuItem.Click
```

2023-02-08 10:59 UTC, lloyddewit commented on instat/dlgLinePlot.vb
> +    Private Sub StepOptionsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles StepOptionsToolStripMenuItem.Click
```suggestion
    End Sub
    
    Private Sub StepOptionsToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles StepOptionsToolStripMenuItem.Click
```

2023-02-08 11:00 UTC, lloyddewit approved these changes

2023-02-08 11:01 UTC, lloyddewit commented
@berylwaswa We made a few changes since your last approval. If you can retest/approve, then we can merge, thanks

2023-02-08 11:30 UTC, berylwaswa commented
@derekagorhom @lloyddewit this looks okay.

2023-02-08 11:31 UTC, berylwaswa approved these changes
Looks good.

2023-02-08 11:34 UTC, merged