Minor bug fixes
africanmathsinitiative/R-Instat pull request #8057
Opened 2023-01-16 13:55 UTC by N-thony

Fixes #8051
@rdstern @berylwaswa please take a look.

2023-01-16 14:50 UTC, rdstern commented
@N-thony this fixes the problem, but seems to have returned us to the earlier problem, namely that it appears to freeze when there is a long data frame.
I tried with the survey - length 36 and it seems to work fine.
Then with a new data frame of length 1 million and it still tries to give the preview - so it looks as though it is frozen for a time.  This is partly linked to the problem that changing the data frame and also reset don't seem to do much.
I suggest:
a) Changing the data frame should always untick the preview.  And it should review the default, so it is appropriate for that data frame.
b) Reset should also untick the preview, and should set the controls to the default for the data frame.
c) There should still be a preview not available if the data frame is long.  We could check different values, but I suggest perhaps 10,000 could be the limit - if longer, then no preview.

2023-01-17 09:10 UTC, N-thony commented
@rdstern I also notice the to input control by default in the code is the length of the dataframe but when you change the dataframe it still remain with the previous dataframe length.

2023-01-20 08:42 UTC, rdstern commented
This is much better, especially on the reset.  But there are still some oddities on the preview.
It still tries to give a preview when there are very long columns - and I think that is part of the problem.
When the column is long - say more than 10,000 then I wonder if the preview can quickly compare the length of the generated variable with the data frame - so give that information.  But not the data in the preview.

One big problem I found currently was when I moved from the Numeric > Regular Sequence to the Date > Generate.  Then it had remembered all the settings from the numeric use of the dialogue and took ages to come.  I was only asking for a data frame of length 100, but the preview was stuck because the other data frame is of length 1 million,

2023-01-20 08:46 UTC, rdstern commented
Maybe a separate problem is that I can't get a preview of dates?

![image](https://user-images.githubusercontent.com/11226469/213653242-060982f6-276c-46e7-8e3b-e8a6b9cd705c.png)

It used to exist.  Here it is as the default in version 7.3

![image](https://user-images.githubusercontent.com/11226469/213653587-53638dbf-fd47-4706-b9dc-212cda833daf.png)

2023-01-20 10:53 UTC, N-thony commented
@rdstern following item c) I did set the limit to 10000, I think this solve the problem in your last comment?

> @N-thony this fixes the problem, but seems to have returned us to the earlier problem, namely that it appears to freeze when there is a long data frame. I tried with the survey - length 36 and it seems to work fine. Then with a new data frame of length 1 million and it still tries to give the preview - so it looks as though it is frozen for a time. This is partly linked to the problem that changing the data frame and also reset don't seem to do much. I suggest: a) Changing the data frame should always untick the preview. And it should review the default, so it is appropriate for that data frame. b) Reset should also untick the preview, and should set the controls to the default for the data frame. c) There should still be a preview not available if the data frame is long. We could check different values, but I suggest perhaps 10,000 could be the limit - if longer, then no preview.

2023-01-20 20:42 UTC, rdstern approved these changes
@N-thony great.  @lloyddewit I hope the code is ok to merge?

2023-01-23 09:31 UTC, lloyddewit requested changes
@N-thony Thanks, just one small question

2023-01-23 09:31 UTC, lloyddewit commented on instat/dlgRegularSequence.vb
> +        ucrChkPreview.SetParameter(New RParameter("Checked", iNewPosition:=0))
R parameter names are case-sensitive. Does that matter in this context?
```suggestion
        ucrChkPreview.SetParameter(New RParameter("checked", iNewPosition:=0))
```

2023-01-23 09:38 UTC, N-thony commented on instat/dlgRegularSequence.vb
> +        ucrChkPreview.SetParameter(New RParameter("Checked", iNewPosition:=0))
yes, typo. Thanks

2023-01-23 11:02 UTC, lloyddewit approved these changes

2023-01-23 11:05 UTC, merged