Added factorize2 and primorial keys to the integer keyboard
africanmathsinitiative/R-Instat pull request #8059
Opened 2023-01-17 09:55 UTC by derekagorhom

fixes #8052 

This PR is review

2023-01-18 08:39 UTC, rdstern commented
The primorial key is fine.
Label the factorize2 key with a small f.
Then the reason you are adding the conf.design package is to use the factorize function from that package.  So please use that function, rather than the one from primes.

Also check with @N-thony on how to specify that the package is to be added.

2023-01-18 10:10 UTC, lloyddewit commented
@derekagorhom Thank you for this PR.
The last commit deletes `install_packages.R`. This is not correct. I assume that you wanted to delete the changes you made rather than the file itself. This now needs to be fixed. The easiest way to resolve is to copy `install_packages.R` from the master branch back into your PR branch.
If you're unsure what to do, then @N-thony should be able to help.

2023-01-19 08:46 UTC, rdstern commented
@derekagorhom now I understand why you gave the command that way.  You were using the conf.design package, but should have known more about how to use a command from a package.  And you could have seen this from the code from many of the other keys.  I didn't realise I needed to specify the code as completely as that!

The command should be given as
`conf.design::factorize( )
`
I was confused by your addition of the primes argument.  And that doesn't work as you gave it either.  If you had wanted to give that, then you needed to add the con.design:: there too.

So you could have programmed it as:

conf.design::factorize(  ,conf.design::primes(  )).

But you don't need this extra argument, because (as shown in the conf.design manual) that is the default.

I deduce from this that you are still not trying the code you provide.  You should always test it yourself on examples of data.  Then usually you should also mention the examples you used for testing.

There is a second item to add - that I forgot.  Could you also add the conf.design package into the help menu.

Now also a big problem you need to discuss with @N-thony and either he or @ChrisMarsh82 need to fix.  Can you start by checking my problem below and then making an issue from this. 

When I try the correct code it gives an error.  It also (now) seems to give an error on any key that generates a list.  So now the divisors key doesn't work, and neither does factorize, etc.  I also get the same error in the master, so it isn't just your branch.  Try with a data set of 1 to 100 say and divisors.  Do you also get this?

![image](https://user-images.githubusercontent.com/11226469/213395872-7ac1a1a4-f215-4cc8-8708-203067994793.png)

2023-01-19 08:53 UTC, N-thony commented
> @derekagorhom now I understand why you gave the command that way. You were using the conf.design package, but should have known more about how to use a command from a package. And you could have seen this from the code from many of the other keys. I didn't realise I needed to specify the code for you as completely as that!
> 
> The command should be given as `conf.design::factorize( ) ` Most of the time you need to give the name of the package. I was confused by your addition of the primes argument. And that doesn't work as you gave it either. If you had wanted to give that, then you needed to add the con.design:: there too.
> 
> So you could have programmed it as:
> 
> conf.design::factorize( ,conf.design::primes( )).
> 
> But you don't need this extra argument, because (as shown in the conf.design manual) that is the default.
> 
> I deduce from this that you are still not trying the code you provide. You should always test it yourself on examples of data. Then usually you should also mention the examples you used for testing.
> 
> There is a second item to add - that I forgot. Could you also add the conf.design package into the help menu.
> 
> Now also a big problem you need to discuss with @N-thony and either he or @ChrisMarsh82 need to fix. Can you start by checking my problem below and then making an issue from this.
> 
> When I try the correct code it gives an error. It also (now) seems to give an error on any key that generates a list. So now the divisors key doesn't work, and neither does factorize, etc. I also get the same error in the master, so it isn't just your branch. Try with a data set of 1 to 100 say and divisors. Do you also get this?
> 
> ![image](https://user-images.githubusercontent.com/11226469/213395872-7ac1a1a4-f215-4cc8-8708-203067994793.png)

@rdstern this bug is fixed in PR #8049, once merged this will be solved.

2023-01-19 09:44 UTC, derekagorhom commented
@rdstern thanks for the correction,  i have made the changes.
can you please have a look and approve. 
thanks

2023-01-19 18:16 UTC, rdstern submitted a review, later dismissed
@derekagorhom great - that looks fine now.  Thanks
It now awaits @lloyddewit for the second check.

2023-01-20 09:05 UTC, lloyddewit requested changes
@derekagorhom Thanks for the changes, just some small questions

2023-01-20 09:05 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ucrReceiverForCalculation.AddToReceiverAtCursorPosition("sapply(  ,primes::primorial_n)", 22)
Other subs in this class have the option to show the parameters.
Should we have this option in this sub also? You may want to ask @rdstern 's opinion.
For example:
```
    Private Sub cmdCeiling_Click(sender As Object, e As EventArgs) Handles cmdCeiling.Click
        If chkShowParameters.Checked Then
            ucrReceiverForCalculation.AddToReceiverAtCursorPosition("ceiling(x= )", 1)
        Else
            ucrReceiverForCalculation.AddToReceiverAtCursorPosition("ceiling( )", 1)
        End If
    End Sub
```

2023-01-20 09:35 UTC, derekagorhom commented on instat/ucrCalculator.vb
> +        ucrReceiverForCalculation.AddToReceiverAtCursorPosition("sapply(  ,primes::primorial_n)", 22)
@lloyddewit i dont think so in this case since `sapply` takes list as input and gives output in vector or matrix.
but @rdstern can confirm

2023-01-20 09:54 UTC, rdstern commented
@derekagorhom I think that's right.  In this case the real function isn't sapply, which is just handling the looping.  So, for now I'm happy without it.  We may add later.

2023-01-20 10:10 UTC, lloyddewit commented
> @derekagorhom I think that's right. In this case the real function isn't sapply, which is just handling the looping. So, for now I'm happy without it. We may add later.

@rdstern @derekagorhom 
OK thanks, understood.
How about the new sub added just below (I assume that `factorize` is the real function)? Should this have the option to add parameters?
```
    Private Sub cmdFactorize2_Click(sender As Object, e As EventArgs) Handles cmdFactorize2.Click
        ucrReceiverForCalculation.AddToReceiverAtCursorPosition("conf.design::factorize( )", 3)
    End Sub
```

2023-01-20 10:21 UTC, rdstern commented
@lloyddewit usually yes, but this time the only argument is very confusing, so I am happy without it for now.

2023-01-20 10:41 UTC, lloyddewit submitted a review, later dismissed
Thanks @derekagorhom

2023-01-20 10:43 UTC, lloyddewit commented
@rdstern The code changes should not have affected the functionality, but still good to test. If you can reapprove, then we can merge, thanks

2023-01-20 16:34 UTC, rdstern requested changes
@derekagorhom just a small correction, which I suggest is being caused by you still being optimistic and not trying your improvements yourself?

The factorize2 key needs to change the position of the cursor, so it is inside the bracket.

While you are doing that, I make a cheeky request.  You programmed the pascal key recently and it seems to work ok, but it works better if you could make a small change, namely to change the first letter to s from l.  So you are using sapply there, rather than lapply.  Thanks

2023-01-20 17:39 UTC, rdstern approved these changes
Looks fine now.  Back to you @lloyddewit

2023-01-23 08:40 UTC, lloyddewit approved these changes

2023-01-23 08:41 UTC, merged