Adding Export data for climsoft dialog
africanmathsinitiative/R-Instat pull request #8060
Opened 2023-01-17 13:43 UTC by Vitalis95

Partially fixes #6377
It is still in progress.  
@rdstern ,@N-thony , @lloyddewit, it fixes the first part of the issue of writing a new dataframe. 
 The dialog is in **Climatic > File > Export to Climsoft**
@rdstern , have a look at the progress so far.

2023-01-20 08:11 UTC, rdstern requested changes
@Vitalis95 that seems to work ok.  I tried with Dodoma, which doesn't have a station - so I had to add that variable.  I think that is ok, but you might consider, if easy, that you use the data frame name as the station information if it isn't provided.  I am not sure though.
1) Before merging I had the data defined as climatic.  So you should be able, then to include the variables automatically - as we do with many of the climatic dialogues.
2) And a question - perhaps also for @Patowhiz .  What happens on the importing if there are duplicate days?  Is that a problem?  Because you could easily add the control to check that - from the define climatic data.  And then possibly don't proceed if there are duplicates.

Then I would be happy to merge while you then add the proper exporting to the dialogue as another pull request.

And another 2 questions for @Patowhiz .  First what should we do about trace rainfalls?  In R-Instat we have the convention of making them 0.03mm, so we could detect and do something, e.g. even make it a text variable with tr, if that can be imported.  And second, what about flag variables?  We can export them, so they can be in R-Instat.  Can they be imported into Climsoft?

2023-01-23 10:53 UTC, Patowhiz commented
@rdstern 
Climsoft overwrites duplicate data. And by duplicate I mean duplicated dates.
Yes, Climsoft can import recognized flags. For trace values, 0 is what is expected not 0.03. The Climsoft team opinion is 0.03 could compound to observations that are not accurate.
Thanks.

2023-01-23 12:33 UTC, rdstern commented
Thanks for the clarification.
a) What do you think we should do as Climsoft overwrites duplicate values?  There seem to me to be 2 situations:
    1) The first value is in the database and the duplicate date is imported from R-Instat.  That will usually be a correction, so that's possibly ok.   
   2) There are duplicate rows in the data that is exported from R-Instat.  I suggest that is usually an error and should not happen.  Would it be good if that were checked in the Export dialogue, or are we getting too perfectionist.  It should be easy to add, because the code is there in the define climatic data dialogue.  
  3)  I suggest adding it to the dialogue would be sensible, because it would alert users to the general issue of duplicates.

Now the flags.

1) Pleased that Climsoft can import data with flags.  We need to make that an option in the dialogue.  So, there should be an Add Flag variables checkbox that would presumably open another multiple receiver for the flag variables (Text or factor variables).  Then it would check that there are as many flag variables as ordinary variables, and also possibly that the codes are acceptable?
 2) Rainfall would be a special case.  We could transform the rainfall data, on the fly as we export, i.e. change 0.03 into 0 and add T into a new flag variable.  For simplicity I suggest instead that we add a button at the top of the export dialogue, for that transformation.  It would produce the two new columns and (at least initially) be just for rainfall.  It could be labelled `Flag-precip`.

2023-01-23 13:28 UTC, Patowhiz commented
@rdstern I recommend adding the duplicate checks as suggested in item 2 above.
Also note, Climsoft expects the flag to be part of the value column not as a separate column. For examples; 0T or 23E. Then during importing it will detect the character and separate it out as the flag.

2023-01-24 10:25 UTC, Vitalis95 commented
@rdstern ,it is now taking data frame name if the station information isn't provided, have a look at it

2023-01-31 16:28 UTC, rdstern approved these changes
@Patowhiz and @Vitalis95, I exported the data for climsoft into a csv and it looks like this:
![image](https://user-images.githubusercontent.com/11226469/215819962-3de01616-133f-49e4-8efe-9769fc7682ea.png)

I assume it can be imported like this into Climsoft, i.e. with the variable names as in R-Instat?  Can you confirm.  I am approving, because (if so) it would be good to include soon.

The next improvement, Vitalis is to complete the dialogue more automatically, when the data has been defined as climatic.  The date can be filled.  And I assume the Station is also filled automatically as a variable when the data are defined as climatic.  And I suggest all the climatic elements can be assumed for export too.  

But this is all cosmetic, so I am approving.  @Patowhiz can you give the second approval?

2023-02-08 19:54 UTC, rdstern commented
@Vitalis95 and @Patowhiz this will be useful in Zambia, and I hope we can have something in the February release.  Other features can be added later, and it doesn't even need trace if that is holding things up?

2023-02-09 09:52 UTC, lloyddewit requested changes
@Vitalis95 thanks, this is looking good, just a couple of small suggestions

2023-02-09 09:52 UTC, lloyddewit commented on instat/dlgExportToClimsoft.vb
> +    Private Sub GetStationName()
a `Get` function normally returns something.
Rename this sub?

2023-02-09 09:52 UTC, lloyddewit commented on instat/dlgExportToClimsoft.vb
> +        Dim strVar As String = ucrReceiverStation.GetVariableNames
remove?

2023-02-10 10:28 UTC, Vitalis95 commented
@Patowhiz , could you test it?

2023-02-13 16:54 UTC, rdstern requested changes
@Vitalis95 the one item I notice is that the initial focus is on the date, even though all fields are completed except the multiple receiver.  
I am not sure what is needed next?  If it will take long to implement the direct csv output then we could merge this version once @lloyddewit is ok with the code.

2023-02-13 17:02 UTC, Vitalis95 commented
@rdstern , I am doing export part on separate PR,

2023-02-14 08:36 UTC, lloyddewit approved these changes

2023-02-14 08:36 UTC, lloyddewit commented
> the one item I notice is that the initial focus is on the date, even though all fields are completed except the multiple receiver.

@Vitalis95 if you can resolve this, then we can merge, thanks

2023-02-14 09:03 UTC, Vitalis95 commented
@rdstern , the focus now is on the multiple receiver. Have look at it

2023-02-14 09:03 UTC, rdstern approved these changes

2023-02-15 08:22 UTC, lloyddewit approved these changes

2023-02-15 08:25 UTC, merged