Improvement of the code quality of receiver logic that checks that when a dialog is reopened, only columns that still exist are shown in the list of selected columns
africanmathsinitiative/R-Instat pull request #8076
Opened 2023-01-23 10:20 UTC by N-thony

Fixes #8073
@lloyddewit @Patowhiz I have the changes suggested in PR #7581. Please take a look. Thanks

2023-01-23 11:01 UTC, lloyddewit commented
@N-thony It all looks good to me. Is the comment below also addressed?

![image](https://user-images.githubusercontent.com/57253949/214023836-cf9b91fb-4450-4d01-aa47-c3916fbae197.png)

2023-01-23 11:05 UTC, N-thony commented
> @N-thony It all looks good to me. Is the comment below also addressed?
> 
> ![image](https://user-images.githubusercontent.com/57253949/214023836-cf9b91fb-4450-4d01-aa47-c3916fbae197.png)

@lloyddewit yes, the single receiver already clear the variable

2023-01-23 11:17 UTC, lloyddewit approved these changes

2023-01-23 11:19 UTC, lloyddewit commented
@Patowhiz Thank you for these helpful comments. If you have time, would you also like to review?

@rdstern Please could you test?

thanks

2023-01-23 13:22 UTC, Patowhiz commented
@lloyddewit @N-thony thank you for addressing my comments
@N-thony I'm interested in knowing why the single receivers automatically removed the variables yet the multiple receivers don't, until this addition. The 2 receivers somehow relate thus this functionality should relate explicitly in regards to the 2.
I was expecting to see the single receivers calling the same function that you have added, or do they internally call a function that does the same thing?

2023-01-23 13:24 UTC, Patowhiz commented on instat/ucrReceiver.vb
> +    Public Overridable Sub RemoveAnyVariablesNotInList()
@N-thony thanks for this.
Could we have a comment here as well. Something that makes it clear that the list referred here is actually the selector.

2023-01-23 13:55 UTC, N-thony commented on instat/ucrReceiver.vb
> +    Public Overridable Sub RemoveAnyVariablesNotInList()
> @lloyddewit @N-thony thank you for addressing my comments @N-thony I'm interested in knowing why the single receivers automatically removed the variables yet the multiple receivers don't, until this addition. The 2 receivers somehow relate thus this functionality should relate explicitly in regards to the 2. I was expecting to see the single receivers calling the same function that you have added, or do they internally call a function that does the same thing?

The implementation of the single receiver has itself already the possibility the clear it when the variable no longer exist in the selector list, we can do the same if we do refactor the code, we can discuss more about it in our next meeting in Kakamega next week.

2023-01-23 16:56 UTC, rdstern requested changes
Good one to include.  However look below

![image](https://user-images.githubusercontent.com/11226469/214100743-e3d978d5-fda3-4537-9162-1ce88e27e1c2.png)

I deleted 2 variables from the data frame.  They deleted from the selector - which is great.  But only 1 of them was deleted from the receiver.

2023-01-23 17:58 UTC, N-thony commented
@rdstern I have tried also by deleting two variables and it seems to work fine
![image](https://user-images.githubusercontent.com/68591383/214113922-6a558b7a-c6fa-4100-b8d3-791eb46979cd.png)
 and again but with a different dialogue i.e `Convert columns`, this time I have deleted 4 columns and it seems fine too
![image](https://user-images.githubusercontent.com/68591383/214114325-5f1b7b3d-dd09-4202-aadd-7446731692d2.png)

2023-01-24 10:53 UTC, Patowhiz commented on instat/ucrReceiver.vb
> +    Public Overridable Sub RemoveAnyVariablesNotInList()
If the single receiver has a way of removing the deleted variable from itself. Then we should look into how it does that, at what event and whether we should use the same approach for the multiple receiver. What we have here seems to suggest explicitly that both the single and multiple receiver need to have this functionality implemented in this subroutine block, currently that is not the case.
It would be helpful if you could look into how the single receiver does it, check if the multiple receiver could have similar implementation then generalize it in a way that is consistent for both of them. I can make suggestions if you could outline how the single receiver does it.

PS what about `RemoveVariablesNotInSelector()`  as the name?
 
I'm happy we discuss more on the same.

2023-01-24 10:58 UTC, N-thony commented on instat/ucrReceiver.vb
> +    Public Overridable Sub RemoveAnyVariablesNotInList()
That is what I'm planning to do next after this PR which attends on resolving your comments and Stephen. But I will not consider it as higher priority for now. This was just an alternative instead of using the previous the R Function.

2023-01-24 11:02 UTC, Patowhiz commented
@N-thony @rdstern it would be good to also test this implementation with wide data sets (around 3000 variables). Especially for dialogs that have multiple receivers(multiple).

2023-01-24 11:13 UTC, Patowhiz commented on instat/ucrReceiver.vb
> +    Public Overridable Sub RemoveAnyVariablesNotInList()
So the single receiver uses an R Function to remove variables that are not in the selector?

2023-01-25 08:28 UTC, rdstern approved these changes
@N-thony it now seems to work well.  I tried with the survey data and summarise and it was fine now.  Then with rockart, from DAAG, which has 641 variables and deleted the first 100 - and that was ok.
Then back to another copy of the usual survey and single receivers in 3 variable regression, deleting two of them.  All ok.  
Nice

2023-01-25 12:08 UTC, lloyddewit approved these changes

2023-01-26 06:38 UTC, N-thony commented
> @Patowhiz @N-thony I'm personally happy with the changes so I approved. I understand that there are still some additional and related code-quality improvements that you're considering. I understand that you'll discuss these together when you're both in Kakmega. This PR is a code quality change rather than a functionality change, so it's not essential for the end January R-Instat release. When the changes are complete and you're both happy with this PR, then I'll merge. Thanks

@lloyddewit I'm also happy with this and think this can be merged. I will consider further suggestions in another PR.

2023-01-26 12:11 UTC, merged