Added Text in Json file and Minor Modification on Some Dialog Design on Prepare Menu.
africanmathsinitiative/R-Instat pull request #8078
Opened 2023-01-23 12:58 UTC by MeSophie

I added text on Json file and Adjusted the size of  Labels and controls on some Dialogs in Prepare Menu.
@N-thony and @lloyddewit please can you check it?

2023-01-24 09:37 UTC, lloyddewit approved these changes

2023-01-24 09:38 UTC, lloyddewit commented
@MeSophie Thank you, may I merge or do you expect to make further changes?

2023-01-24 10:26 UTC, MeSophie commented
> 

@lloyddewit you can merge so that I can proceed in Crowdin.

2023-01-25 11:59 UTC, lloyddewit requested changes

2023-01-25 11:59 UTC, lloyddewit commented on instat/translations/en/r_instat_not_menus.json
> +  "Occurren"
is this valid?

2023-01-25 12:13 UTC, lloyddewit approved these changes

2023-01-25 12:14 UTC, merged

2023-01-25 12:30 UTC, MeSophie commented on instat/translations/en/r_instat_not_menus.json
> +  "Occurren"
> is this valid?

@lloyddewit No sorry it was a mistake I corrected it.