Updated Help Menu
africanmathsinitiative/R-Instat pull request #8084
Opened 2023-01-26 12:01 UTC by Vitalis95

Fixes #8070 
@rdstern @lloyddewit @N-thony ,  I changed the help menu as requested, The  **Glossary** and **R-Packages** doesn't have the **help file**. Once Roger provides them I will add. Thanks

2023-01-26 13:02 UTC, rdstern commented
@Vitalis95 the help context for Glossary is 92
For R packages it is 26

2023-01-26 16:57 UTC, rdstern submitted a review, later dismissed
@Vitalis95 this seems to work fine

2023-01-27 08:41 UTC, lloyddewit requested changes

2023-01-27 08:41 UTC, lloyddewit commented on instat/frmMain.vb
> +        'mnuHelpAboutRInstat.Visible = False
```suggestion
```

2023-01-27 08:41 UTC, lloyddewit commented on instat/frmMain.vb
> +    Private Sub mnuHelpGuidesCaseStudy_Click(sender As Object, e As EventArgs)
Is this sub used anywhere? can we delete it?

2023-01-27 08:41 UTC, lloyddewit commented on instat/frmMain.vb
> +    Private Sub mnuHelpGuideGlosary_Click(sender As Object, e As EventArgs)
Is this sub used anywhere? can we delete it?

2023-01-27 08:41 UTC, lloyddewit commented on instat/frmMain.vb
> +    Private Sub mnuHelpAcknowledgments_Click(sender As Object, e As EventArgs)
Is this sub used anywhere? can we delete it?

2023-01-27 08:41 UTC, lloyddewit commented on instat/frmMain.vb
> +    End Sub
separate subs with empty line
```suggestion
    End Sub
    
```

2023-01-27 08:41 UTC, lloyddewit commented on instat/frmMain.vb
> +    Private Sub mnuHelpDataViewSpreadsheet_Click(sender As Object, e As EventArgs)
Is this sub used anywhere? can we delete it?

2023-01-27 09:17 UTC, Vitalis95 commented
@lloyddewit , have a look at it

2023-01-27 09:43 UTC, lloyddewit approved these changes

2023-01-27 09:44 UTC, lloyddewit commented
@rdstern there are some small changes since your last approval. If you can retest/approve, then we can merge, thanks

2023-01-27 09:51 UTC, rdstern approved these changes

2023-01-27 10:00 UTC, merged