Fixes Minor Bug on Column Rename
africanmathsinitiative/R-Instat pull request #8093
Opened 2023-01-30 13:10 UTC by derekagorhom

Fixes #7938 

This PR is fixes the bug on Prepare > Data Frame > Rename Column  

This PR  is ready for Review.

2023-01-30 13:29 UTC, N-thony commented
@rdstern if you test and you are happy with this, I suggest we do the same changes everywhere we use the Grid?

2023-01-30 17:43 UTC, rdstern requested changes
@derekagorhom I wonder how carefully you have tested this change.  It is what I keep asking you to do more of, before asking others.
Please try with the survey dataset and change the 7 names to a, b, c, d, e, f, g.  You will find - as before it doesn't like having f as the name.

Ok, now explain to me how to add any name now that starts with either f or t?  Now, with your change I think it is checking for the acceptable name letter by letter, and that's a disaster!

2023-01-31 07:31 UTC, derekagorhom commented
@rdstern sorry for the new issue found with the PR but i think instat recognizes t and f as boolean so it stops a user from having then as column names, see below
![image](https://user-images.githubusercontent.com/76208189/215694509-032cf308-138f-4143-a68a-eb130795db8d.png)
apart from that when you click ok and add more letters to the t or f it accepts them and the user can successfully rename the column.

2023-01-31 07:46 UTC, N-thony commented
> 

@derekagorhom we need the warning message to avoid the user to enter `Boolean` as column name, we can just check the string before passing it to the function if it is not a `Boolean`.

2023-01-31 08:43 UTC, derekagorhom commented
@rdstern this new commit ensures the user does not get hit with the `instat` warning when they are renaming the columns with starting words `t or f` but the warning message will pop up if they leave it as such (leaving it as `t or f `and moving to a new column).
this message will be repeated till the user makes that correction.

2023-01-31 09:02 UTC, rdstern approved these changes
@derekagorhom great - this now works fine.
As mentioned by @N-thony there are other places where this could be a good change.  Particularly entering data into the grid.  If agreed then maybe this pull request can be merged, but the issue could be extended and this pull request adjusted to only partially resolve the issue.

2023-01-31 09:31 UTC, lloyddewit requested changes

2023-01-31 09:31 UTC, lloyddewit commented on instat/dlgName.vb
> +    Private Sub grdCurrentWorkSheet_CellMouseLeave(sender As Object, e As CellEditTextChangingEventArgs) Handles grdCurrentWorkSheet.CellEditTextChanging
- The sub name should be consistent with the handled event. I would expect a name like `grdCurrentWorkSheet_CellEditTextChanging`.
- Normally we should change events in the designer so that `dlgName.designer.vb` stays consistent with `dlgName.vb`. Should we add this new event handler using the VS Designer?

2023-01-31 09:50 UTC, derekagorhom commented on instat/dlgName.vb
> +    Private Sub grdCurrentWorkSheet_CellMouseLeave(sender As Object, e As CellEditTextChangingEventArgs) Handles grdCurrentWorkSheet.CellEditTextChanging
@lloyddewit i have made the changes

2023-01-31 10:47 UTC, lloyddewit approved these changes

2023-01-31 10:51 UTC, merged