Added list keyboard
africanmathsinitiative/R-Instat pull request #8102
Opened 2023-02-07 08:36 UTC by derekagorhom

Fixes #7886 

This PR is ready for review. 

@rdstern with the exception of the `missing` and `nth` keys, all other keys seems to work fine, also for the maths bloc for the keyboard, i already added the `+,-,*,/ and ^` keys.

2023-02-07 09:31 UTC, lloyddewit submitted a review, later dismissed

2023-02-07 09:32 UTC, lloyddewit commented
@berylwaswa Do you feel comfortable testing/approving this? 
(please also test all the new tooltips)
thanks

2023-02-07 12:16 UTC, berylwaswa commented
@lloyddewit yes I can take a look.

2023-02-07 13:19 UTC, lloyddewit commented
> @rdstern @lloyddewit the sumd, missing and nth keys are the only ones not working all other keys seem to work fine.

@berylwaswa Thank you for testing. According to the code changes, it looks like there was an attempt to implement sumd. Should @derekagorhom implement this before we merge?
Should @derekagorhom also implement the `missing` and `nth` keys before we merge or can these be implemented in a separate PR?
thanks

2023-02-07 13:28 UTC, berylwaswa commented
@lloyddewit if @derekagorhom is able to implement without the help of @rdstern then he can do that before we merge, if not they can be implemented in a separate PR. 
Thanks.

2023-02-07 14:54 UTC, derekagorhom commented
@lloyddewit , @berylwaswa, i will try and solve the issue with the three keys not working so this PR can be left open for now.

2023-02-09 09:01 UTC, derekagorhom commented
For the last three commits, i was able to fix the issue with `missing` and `nth keys` not working. The `missing key` should work fine now, for the` nth key` i made sure to add space within the function to enable the user type with number they wanted to display eg.  **sapply( `V1`  , function(x) {dplyr::nth(x, `2` )});** 
Here V1 represents the list and 2 represent the second value in that list (`V1`), (this i hope makes more sense). 
![nth key](https://user-images.githubusercontent.com/76208189/217764991-2029fa54-46be-4eee-88ab-4e8aaba561a7.png)
For the `sumd key` i want to believe roger intended for it to be used on list that have only one value in them but i maybe wrong. 
I also added a new set of keys to the Math bloc of this keyboard, they can be reviewed also. 
thanks

2023-02-09 09:49 UTC, derekagorhom commented
@berylwaswa i have made the changes to the code, could you review this

2023-02-09 10:00 UTC, berylwaswa commented
@lloyddewit @derekagorhom The missing key and the nth key work fine now.
For the sumd key works only when the list has one value.
The keys added to the math bloc all work fine too.

2023-02-09 10:01 UTC, berylwaswa submitted a review, later dismissed
These work fine.

2023-02-09 10:36 UTC, lloyddewit commented
> For the sumd key works only when the list has one value.

Is this acceptable? or should this still be fixed (in this PR or another PR)?
thanks

2023-02-09 11:58 UTC, lloyddewit commented
@berylwaswa @rdstern I just had a quick interaction with @derekagorhom . We agreed that this PR can wait for @rdstern 's testing and feedback.

2023-02-09 12:47 UTC, rdstern commented
Looking forward to seeing that.  I am having trouble testing branches on my machine just now.  I can see the current merged version.  So the test will have to wait till I am back on Saturday.

2023-02-13 08:02 UTC, rdstern requested changes
@derekagorhom and also @berylwaswa this is looking exciting.  But I am not sure you have made enough effort to understand the different use of sapply and lapply, nor when a function is needed, or not?
So please check the code you have provided, in the keys carefully as follows:
1. lapply produces a list variable, while sapply does not.  So you need lapply for the range (it gives 2 numbers - min and max) and also for the mode(s) , because the mode may not be unique.  You don't need it for those that give a single summary, e.g. mean.
2. You need the function only when it has not been done for you.  So I could not find an ssq function in R - so ssq uses a function.  But there is var and sd, etc, so they can just be given in the same way as you gave min and max on the top row.

So @derekagorhom please examine all the keys now and see what you should do to change them.  Possibly discuss with @berylwaswa too.  This is not so easy, but rewarding when you understand.

As an example I used the factorize2 key on the numbers 1 to 100 in a new dataframe, but getting the factors of x1+100, so for 101, etc.  The example below also shows how I simplified the var key code.

![image](https://user-images.githubusercontent.com/11226469/218402455-a98843ad-ca9e-4703-b7fc-c3124be2a8fc.png)

2023-02-13 10:09 UTC, rdstern commented
The maths section is looking good.
a) Change the round2 code into the round1 key and call it `round`. tooltip "round the numbers in each list. Default is to 3 decimals)
b) Move the code behind round1 to the round2 key and call the key percent2.  Change the 3 to 2 in the code so it rounds percentages to 2 decimals.  Tooltip `percent of each value in the list, rounded to a default of 2 decimals.`  
c) Add the tooltip to the divide key:  `divide each value in the list by a given value (default 10)`
d) Change the square key to say `power (^)`  change the default to raise each number in the list to a given power (default 2, to square the numbers)
d)  Add the symbol to the other keys on the top row sum (+), subtract (-), times (*) divide (/).
e) Change the sqrt function to the simpler lapply(   ,sqrt) tooltip square root each number in the list.  (Change sqrt to abs, log, exp, sin, etc for other functions)
f) Change the word List (above to first key to Summary and move it closer to the first block.  Move it all upwards a bit and put the Help key at the top, moving the Maths block up a bit too.  This to make space for a third block of keys later, called Transform - though we will merge these first.

2023-02-13 12:08 UTC, derekagorhom commented
@rdstern i have made the changes but i am still a bit confused on the use of functions for r  for `missing` and `nth`
I have tried to make them simpler like the other r functions but it always returns an error for me.
Below are the links i looked on to make the missing and nth expressions 
[for sum of missing values](https://discuss.analyticsvidhya.com/t/how-to-count-the-missing-value-in-r/2949/5). 
[for the nth value](https://rdrr.io/cran/dplyr/man/nth.html)

2023-02-13 14:18 UTC, rdstern requested changes
@derekagorhom it is looking even better now
a) the round doesn't need to be a function, because it is itself!.  So change it to sapply(  ,round,3)
b) the sqrt can be sapply, rather than lapply.
c) for nth, have sapply(  ,dplyr::nth, 2).
d) For first make the tooltip simply `the first value in each list`, for last it is `the last value in each list`, and for nth it is `the nth value in each list, (default = 2, the second value)`
e) In the miss key the code is simply` ,na.rm=TRUE`  Include the comma at the start.  This is not used on its own.  It is to be added to other functions, such as the sum.  The tooltip is `add the option to omit missing values in the summaries`

2023-02-14 10:05 UTC, derekagorhom commented
@rdstern i have made the code changes to the `nth, round, miss` and `sqrt` keys and i also added the Transform bloc on the list keyboard.

2023-02-14 17:03 UTC, rdstern reviewed
@derekagorhom this has been excellent work.  I have tested lots and all the new keys seem to work fine.

I just suggest a few minor improvements to the tooltips and then it would be great to merge.

a) For the anydup key change row to observation
b) for the quantile key change it to `default is 20%, 50% (median) and 80% of each list`
c) for the fivenum add `gives the same summaries as the boxplot, so minimum, lower and upper hinges (roughly the quartiles), median, and maximum`.  
d) for sumd add gives the sum of the digit sums (e.g. for 34, 27 = 7 + 9 = 16)
e) for round replace by round the numbers in each list, with default of 3 decimals (change round to signif for significant figures)

2023-02-15 07:12 UTC, derekagorhom commented
@rdstern I have added the tooltips for the keys on the keyboard.

2023-02-15 08:13 UTC, rdstern submitted a review, later dismissed
@derekagorhom many thanks for working so well on this new keyboard.  Over to you @lloyddewit

2023-02-15 10:35 UTC, lloyddewit reviewed
@derekagorhom thanks, looks good, just a few small comments

2023-02-15 10:35 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListLength, "number of observations: For example length(c(1,2,3,4,NA)) = 5 ")
These tooltips seem to be duplicates of the tooltips starting on line 269.
Declare a constant string for each message and then assign the constant string to the tool tips?

2023-02-15 10:35 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListMode, "the most popular value. So mode(c(10,2,2,3,3) = 2 and 3")
```suggestion
        ttCalculator.SetToolTip(cmdListMode, "the most popular value(s). So mode(c(10,2,2,3,3) = 2 and 3")
```

2023-02-15 10:35 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListRound, "replace by round the numbers in each list, with default of 3 decimals (change round to signif for significant figures).")
this message doesn't make sense to me, rephrase?

2023-02-15 10:35 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListPercent2, "percent of each value in the list, rounded to a default of 2 decimals.")
```suggestion
        ttCalculator.SetToolTip(cmdListPercent2, "percent of each value in the list, rounded to a default of 2 decimals places.")
```

2023-02-15 10:35 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListSumd, "gives the sum of the digit sums (e.g. for 34, 27 = 7 + 9 = 16).")
what does 'for 34' mean?

2023-02-15 12:13 UTC, derekagorhom commented
@lloyddewit i made changes to the code for the keyboard tooltip and they work fine

2023-02-15 16:14 UTC, rdstern requested changes
Just a minor change in the sumd tooltip.  In the brackets it is (e.g. for 34, 27 = 7 + 9 = 16)

2023-02-16 09:01 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +    Private Sub cmdListLength_Click(sender As Object, e As EventArgs) Handles cmdListLength.Click
is this resolved?

2023-02-16 09:12 UTC, lloyddewit commented
> @lloyddewit i made changes to the code for the keyboard tooltip and they work fine

Thank you for adding the constant strings.
I made some other comments above also. They were marked as resolved but I checked an they still need resolving.
If you can make the requested changes, then I can approve.
thanks

2023-02-16 09:22 UTC, derekagorhom commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListSumd, "gives the sum of the digit sums (e.g. for 34, 27 = 7 + 9 = 16).")
https://github.com/africanmathsinitiative/R-Instat/pull/8102#pullrequestreview-1299824192

this is how the tooltip for that key was made, you can see from the above comment

2023-02-16 09:26 UTC, derekagorhom commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListRound, "replace by round the numbers in each list, with default of 3 decimals (change round to signif for significant figures).")
I changed it to 
"replaces by round, the numbers in each list, with default of 3 decimals (change round to signif for significant figures"
yesterday

2023-02-16 09:43 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListRound, "replace by round the numbers in each list, with default of 3 decimals (change round to signif for significant figures).")
I still find the message a bit confusing. Is something like thic clearer?

"applies the round function to each value in each list, with a default of 3 decimal places (change round to signif for significant figures)."

2023-02-16 09:45 UTC, lloyddewit commented
> Just a minor change in the sumd tooltip. In the brackets it is (e.g. for 34, 27 = 7 + 9 = 16)

@rdstern I'm still a bit confused about 'for 34', what does this mean?

2023-02-16 09:48 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListSumd, "gives the sum of the digit sums (e.g. for 34, 27 = 7 + 9 = 16).")
now I understand, my mistake, sorry

2023-02-16 09:54 UTC, lloyddewit requested changes
@derekagorhom I think there are 3 comments that still need your action. Please do not set these comments to 'resolved'. Please let me know when you're done and I'll review.
Thanks

2023-02-16 09:54 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListPercent2, "percent of each value in the list, rounded to a default of 2 decimals places.")
```suggestion
        ttCalculator.SetToolTip(cmdListPercent2, "percent of each value in the list, rounded to a default of 2 decimal places.")
```

2023-02-16 11:05 UTC, rdstern commented
@lloyddewit in "Just a minor change in the sumd tooltip. In the brackets it is (e.g. for 34, 27 = 7 + 9 = 16)"
You write 

" I'm still a bit confused about 'for 34', what does this mean?"

If so, then it must need rewording.  I mean if the list contains the 2 numbers 34 and 27, then the sum of the digits (individually) is 3 + 4 = 7 and 2 + 7 = 9, so sumd will give 7 + 9 = 16.

2023-02-16 11:09 UTC, derekagorhom commented
so roger can i reword it to 
` if the list contains the 2 numbers 34 and 27, then the sum of the digits (individually) is 3 + 4 = 7 and 2 + 7 = 9, so sumd will give 7 + 9 = 16.`

2023-02-16 11:11 UTC, lloyddewit commented
> so roger can i reword it to ` if the list contains the 2 numbers 34 and 27, then the sum of the digits (individually) is 3 + 4 = 7 and 2 + 7 = 9, so sumd will give 7 + 9 = 16.`

@rdstern for me that's perfect. Actually I was being a bit thick. After I wrote the comment, I suddenly understood what it meant and deleted my comment - but you were too fast and had already responded!

2023-02-16 11:19 UTC, rdstern commented
@lloyddewit I wondered why I couldn't find your comment in the pull request - but I still had the evidence in the e-mail.
@derekagorhom it is your choice.  I am keen that you understand the use of each key - and the tooltip is designed to help.  So I would like the most concise version that is really clear to you.

2023-02-16 11:31 UTC, lloyddewit requested changes

2023-02-16 11:31 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListPercent2, "percent of each value in the list, rounded to a default of 2 decimals.")
```suggestion
        ttCalculator.SetToolTip(cmdListPercent2, "percent of each value in the list, rounded to a default of 2 decimal places.")
```

2023-02-16 11:31 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        ttCalculator.SetToolTip(cmdListSumd, " if the list contains the 2 numbers 34 and 27, then the sum of the digits (individually) is 3 + 4 = 7 and 2 + 7 = 9, so sumd will give 7 + 9 = 16.")
```suggestion
        ttCalculator.SetToolTip(cmdListSumd, "if the list contains the 2 numbers 34 and 27, then the sum of the digits (individually) is 3 + 4 = 7 and 2 + 7 = 9, so sumd will give 7 + 9 = 16.")
```

2023-02-16 11:32 UTC, lloyddewit approved these changes

2023-02-16 11:33 UTC, lloyddewit commented
@rdstern there are some small changes since your last approval. If you can retest/approve, then we can merge, thanks

2023-02-16 11:54 UTC, rdstern approved these changes
@derekagorhom and @lloyddewit this looks very good.  Many thanks

2023-02-18 10:47 UTC, merged