Fixed bug to the variable of type List when setting the Signif value
africanmathsinitiative/R-Instat pull request #8106
Opened 2023-02-07 11:57 UTC by N-thony

Fixes #8067 
@ChrisMarsh82 I have made the change as discussed few minutes ago that to disable the cell in the `Signif_Figures` where the `class` is list in the Column Metadata grid. Please have a look.

2023-02-08 11:58 UTC, ChrisMarsh82 approved these changes

2023-02-08 12:10 UTC, N-thony commented
@lloyddewit overt to you

2023-02-09 09:09 UTC, lloyddewit requested changes
@N-thony thanks, just one question

2023-02-09 09:09 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
> +                    grdData.CurrentWorksheet.GetCell(row:=i, col:=GetColumnIndex("Signif_Figures")).IsReadOnly = True
The `GetColumnIndex()` function will potentially be called multiple times.
If we call the function outside the `For` loops (i.e. above line 43), then we only need to call the function once.
Should we move this function call?
Should we also check for the function returning `-1`?

2023-02-09 10:30 UTC, lloyddewit requested changes

2023-02-09 10:30 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
> +                If grdData.CurrentWorksheet.Item(row:=i, col:=j) = "list" Then
if `iColumnIndex` is -1, then the line below will trigger an exception.
Add a check like `AndAlso iColumnInex >= 0`?

2023-02-09 10:30 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
> +        Dim iCoumnIndex As Integer = GetColumnIndex("Signif_Figures")
fix typo?
```suggestion
        Dim iColumnIndex As Integer = GetColumnIndex("Signif_Figures")
```

2023-02-09 12:03 UTC, N-thony commented on instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
> +                If grdData.CurrentWorksheet.Item(row:=i, col:=j) = "list" Then
this seems fixed now.

2023-02-10 08:46 UTC, lloyddewit approved these changes

2023-02-10 08:50 UTC, lloyddewit approved these changes

2023-02-10 08:52 UTC, lloyddewit commented
@berylwaswa if you can test, then we can merge, thanks

2023-02-10 08:54 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
> +                If grdData.CurrentWorksheet.Item(row:=i, col:=j) = "list" Then
@N-thony I may have started commenting before you were done with your changes ... sorry

2023-02-10 09:28 UTC, berylwaswa commented
@ChrisMarsh82 @lloyddewit @N-thony I have checked this and the cell where the class is list in the Column Metadata grid the Signif_Figures is disabled. It works fine.

2023-02-10 09:52 UTC, merged