Added Save Control System for Rating Data dialogue
africanmathsinitiative/R-Instat pull request #8108
Opened 2023-02-07 12:45 UTC by derekagorhom

fixes partly #8105 

@Patowhiz , @lloyddewit , @N-thony 
This PR is ready for review

2023-02-07 13:26 UTC, lloyddewit requested changes

2023-02-07 13:26 UTC, lloyddewit commented on instat/dlgRatingScales.vb
> +        'ucrPnlGraphType.AddToLinkedControls(ucrSaveGraph, {rdoStacked, rdoLikert}, bNewLinkedHideIfParameterMissing:=True)
better to delete rather than comment?
```suggestion
```

2023-02-07 14:29 UTC, derekagorhom commented
@lloyddewit i have made the changes, thank you

2023-02-08 08:44 UTC, lloyddewit approved these changes
@derekagorhom Thanks for the tidy/readable code, looks good to me

2023-02-08 10:23 UTC, berylwaswa approved these changes
Looks good.

2023-02-08 11:30 UTC, lloyddewit approved these changes

2023-02-08 11:31 UTC, merged