Ensured output from correlation dialog is correct
africanmathsinitiative/R-Instat pull request #8117
Opened 2023-02-09 11:32 UTC by Vitalis95

Fixes partially #8104 
@lloyddewit , @Patowhiz ,  @rdstern . 
- In `multiple receiver` , I have added the following for the  new output system
`Save Table` 
When `Display Options` is checked, it has 
![image](https://user-images.githubusercontent.com/89011415/217799541-488e6d3d-c82e-4c27-815d-3372d28a97c5.png)

For `Save Table` and `Save data frame` when the buttons are checked respectively
- In `Two columns ` it has `Save Model` control for saving the model
- The sdg changes is because of setting R-code bug

2023-02-10 08:43 UTC, lloyddewit commented
@berylwaswa please could you test? thanks

2023-02-10 10:24 UTC, berylwaswa commented
@Vitalis95 @lloyddewit this seems to work fine.

2023-02-10 11:08 UTC, lloyddewit requested changes

2023-02-10 11:08 UTC, lloyddewit commented on instat/sdgCorrPlot.vb
> +        ucrPnlGraphType.AddToLinkedControls(ucrReceiverFactor, {rdoScatterPlotMatrix},, bNewLinkedHideIfParameterMissing:=True)
```suggestion
        ucrPnlGraphType.AddToLinkedControls(ucrReceiverFactor, {rdoScatterPlotMatrix}, bNewLinkedHideIfParameterMissing:=True)
```

2023-02-10 11:08 UTC, lloyddewit commented on instat/sdgCorrPlot.vb
> +        'ucrInputComboGeom.SetRDefault("tile")
delete?

2023-02-10 11:08 UTC, lloyddewit commented on instat/sdgCorrPlot.vb
> +        '    End If
delete?

2023-02-10 11:29 UTC, berylwaswa submitted a review, later dismissed

2023-02-10 12:02 UTC, Vitalis95 commented on instat/dlgCorrelation.vb
>                          ucrBase.clsRsyntax.iCallType = 0
@lloyddewit , yes it's only here

2023-02-10 12:14 UTC, berylwaswa reviewed
This looks fine.

2023-02-10 12:15 UTC, berylwaswa approved these changes

2023-02-13 11:39 UTC, lloyddewit approved these changes

2023-02-13 11:40 UTC, merged