Added Plot Options For Boxplot
africanmathsinitiative/R-Instat pull request #8122
Opened 2023-02-09 13:32 UTC by derekagorhom

partly fixes #7556 
Replaces #7570 

This PR is ready for review.

2023-02-10 09:29 UTC, lloyddewit requested changes
@derekagorhom looks good, just a couple of questions

2023-02-10 09:29 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +    Private Sub openSdgLayerOptions(clsNewGeomFunc As RFunction)
```suggestion

    Private Sub openSdgLayerOptions(clsNewGeomFunc As RFunction)
```

2023-02-10 09:29 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +            Me.ucrBase.Location = New Point(10, 413)
These statements look the same as lines 444 to 446.
Could we remove the `ElseIf` and replace with an `OrElse` on line 443?

2023-02-10 09:29 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +        ToolStripMenuItemSummaryOptions.Enabled = rdoBoxplotTufte.Checked OrElse ((rdoJitter.Checked _
rename to `toolStripMenuItemSummaryOptions` to make consistent?

2023-02-10 09:49 UTC, derekagorhom commented
thanks @lloyddewit, i have made the changes

2023-02-10 09:56 UTC, lloyddewit approved these changes

2023-02-10 09:57 UTC, lloyddewit commented
@berylwaswa if you can test, then we can merge, thanks

2023-02-10 13:39 UTC, berylwaswa approved these changes
@derekagorhom @lloyddewit the options are all working fine.

2023-02-13 16:43 UTC, rdstern approved these changes
Looks good

2023-02-14 08:32 UTC, merged