Created an empty windows form for dlgUseTable.
africanmathsinitiative/R-Instat pull request #8130
Opened 2023-02-10 10:14 UTC by anastasia-mbithe

@N-thony and @lloyddewit 

I have added an empty windows form for dlgUseTable, in line with #8081.

2023-02-10 10:20 UTC, lloyddewit requested changes
Thanks, just a couple of questions.
Note: @MeSophie is also changing `frmMain.Designer.vb'. Whoever merges first will cause a merge conflict for the other. You may want to coordinate with her.

2023-02-10 10:20 UTC, lloyddewit commented on instat/frmMain.Designer.vb
> +        Me.mnuDescribeUseTable.Enabled = False
please could you make visible also false?

2023-02-10 10:20 UTC, lloyddewit commented on instat/frmMain.vb
> +    Private Sub ucrDataFrameMeta_Enter(sender As Object, e As EventArgs)
was it the intention to remove these events?
if so, then should we also delete these subs?

2023-02-10 10:27 UTC, anastasia-mbithe commented on instat/frmMain.vb
> +    Private Sub ucrDataFrameMeta_Enter(sender As Object, e As EventArgs)
Nop, Its just something weird I've noticed. I didnt delete the events, it did so after pushing the branch. But I've fixed that now.

2023-02-10 10:31 UTC, anastasia-mbithe commented on instat/frmMain.Designer.vb
> +        Me.mnuDescribeUseTable.Enabled = False
done now

2023-02-10 11:34 UTC, lloyddewit requested changes

2023-02-10 11:34 UTC, lloyddewit commented on instat/frmMain.Designer.vb
> +        Me.Text = "R-Instat  .."
I think that this change is a side effect of opening frmMain in the designer.
Please could you manually reverse this change?
thanks

2023-02-10 12:29 UTC, anastasia-mbithe commented
@lloyddewit I made the changes

2023-02-10 12:32 UTC, N-thony approved these changes

2023-02-14 05:42 UTC, anastasia-mbithe commented
> Thanks, just a couple of questions. Note: @MeSophie is also changing `frmMain.Designer.vb'. Whoever merges first will cause a merge conflict for the other. You may want to coordinate with her.

@lloyddewit you can merge hers first, I can redo my PR if I won't be able to solve the conflicts.

2023-02-14 08:46 UTC, lloyddewit approved these changes

2023-02-14 08:47 UTC, merged