Added Plot Options for Bar and Pie Chart
africanmathsinitiative/R-Instat pull request #8139
Opened 2023-02-14 11:55 UTC by derekagorhom

fixes partly #7556 
Replace #7810 

@N-thony , @rdstern this PR is ready for review

2023-02-14 21:51 UTC, rdstern submitted a review, later dismissed
@derekagorhom this looks fine.  I assume the old one will also be closed?  Now over to @lloyddewit

2023-02-15 08:41 UTC, lloyddewit requested changes

2023-02-15 08:41 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +        'ChangeButtonsText()
```suggestion
```

2023-02-15 08:41 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +    Private Sub toolStripMenuItemBarchartOptions_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemBarchartOptions.Click
```suggestion

    Private Sub toolStripMenuItemBarchartOptions_Click(sender As Object, e As EventArgs) Handles toolStripMenuItemBarchartOptions.Click
```

2023-02-15 08:41 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +    End Sub
```suggestion
    End Sub
    
```

2023-02-15 08:47 UTC, merged