Ensure the R help html file to display in the Maximise window
africanmathsinitiative/R-Instat pull request #8144
Opened 2023-02-15 10:35 UTC by N-thony

@lloyddewit I have made the change as requested. Could you have a look?
@rdstern I can help you to test this. There is a small thing to do before as I discussed with @lloyddewit 
@Patowhiz you can also have a look.

2023-02-15 11:05 UTC, lloyddewit requested changes

2023-02-15 11:05 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +        Dim strTempPath As String = "C:\Program Files\R-Instat\0.7.8\static"
This variable is only used in the commented testing line below. Remove?
```suggestion
```

2023-02-15 11:05 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +        'strHelpPath = String.Concat(strTempPath, strRLibrary, strTempFile)
```suggestion
        'if you wish to test this in the development environment, then uncomment line below
        '(you may need to change the path or version number)
        'strHelpPath = String.Concat("C:\Program Files\R-Instat\0.7.8\static", strRLibrary, strTempFile)
```

2023-02-15 11:05 UTC, lloyddewit commented on instat/dlgModelling.vb
> +        Dim strPackageName As String = ucrInputComboRPackage.GetText
this code seems very similar to the code starting on line 232.
Make a new sub and call this sub from 3 places?

2023-02-15 11:05 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        Dim strTempFile As String = "\html\00Index.html"
this code seems very similar to the code starting on line 232.
Make a new sub and call this sub from 3 places?

2023-02-15 16:03 UTC, rdstern reviewed
@N-thony I tried the R Help from the File > Open from library and it still displays in a browser.  And the calculator, and the package help.  I didn't see anything in the maximized window.  Am I doing something wrong?

2023-02-16 06:35 UTC, N-thony commented
> @N-thony I tried the R Help from the File > Open from library and it still displays in a browser. And the calculator, and the package help. I didn't see anything in the maximized window. Am I doing something wrong?

@rdstern yes, I can help on how to test it.

2023-02-16 11:24 UTC, lloyddewit submitted a review, later dismissed
@N-thony Thank you for the changes and discussions, happy to approve

2023-02-16 11:28 UTC, lloyddewit commented
@rdstern if you can test/approve, then we can merge.
Note: to test this PR in your development environment, you'll need to uncomment 3 lines (1 line in dlgModeling, ucrCalculator and dlgFromLibrary respectively). If you look at the code changes in this PR, then it should be obvious which lines need uncommenting.
thanks

2023-02-18 11:20 UTC, lloyddewit requested changes
Just one suggestion. When this is resolved (and the testing lines are recommented), then I'm happy to approve.

2023-02-18 11:20 UTC, lloyddewit commented on instat/ucrCalculator.vb
> +        Dim clsList As New RFunction
use normal naming?
```suggestion
        Dim clsStartServerFunction As New RFunction
        Dim clsGetPortfunction As New RFunction
        Dim clsListFunction As New RFunction
```

2023-02-19 15:12 UTC, rdstern commented
@N-thony after our discussion I now understand that it can't work visibly in the development version, or even in the merged version.  So, as soon as @lloyddewit is ok, then I am happy for it to be merged.  I note the places we currently have the calls to the R-help:

a) The File > Open from Library
b) Each halfway dialogue - currently 4, namely Prepare > Calculator, Model > Fit > Fit Model Keyboard, and Hypothesis Testing keyboard, and Use Model > Use Model Keyboard.
I expect more in the future.
c) Help > Packages Documentation.  (When frm_main is next edited, then this could change to R Packages Documentation.

There are also many calls to the packages from the help.  I am thinking this may remain as an online call as I call the CRAN page where possible.

2023-02-20 06:30 UTC, N-thony commented
> @N-thony after our discussion I now understand that it can't work visibly in the development version, or even in the merged version. So, as soon as @lloyddewit is ok, then I am happy for it to be merged. I note the places we currently have the calls to the R-help:
> 
> a) The File > Open from Library b) Each halfway dialogue - currently 4, namely Prepare > Calculator, Model > Fit > Fit Model Keyboard, and Hypothesis Testing keyboard, and Use Model > Use Model Keyboard. I expect more in the future. c) Help > Packages Documentation. (When frm_main is next edited, then this could change to R Packages Documentation.
> 
> There are also many calls to the packages from the help. I am thinking this may remain as an online call as I call the CRAN page where possible.

@rdstern this first solution is not really efficient, I found a solution that will works well anyways but the code runs well in the script. I'm investigating on it and will also check with @lloyddewit

2023-02-21 12:22 UTC, closed without merging