Added a Use Table dialog.
africanmathsinitiative/R-Instat pull request #8145
Opened 2023-02-16 10:30 UTC by anastasia-mbithe

Fixes #8081 

This is almost ready. 
However, @Patowhiz the objects produced as either raw html, latex, word, or rtf are not supported in the output window. Is there a way we could save them as files (maybe)?

@rdstern, I have linked the dialog with the Format Options sub dialog, more edits will have to be done later when we adopt the new Format Options sub dialog, implemented in #8027

2023-02-22 15:28 UTC, rdstern commented
@anastasia-mbithe I couldn't get it to work.
I first got a table.  Then opened this dialogue and tried to just then say ok to get thge table again.  It didn't give an error, but it didn't give the table either.
Then I added a title and now it gives an error and says that data is not provided.

Incidentally I tried changing the order of the summaries on a summary table.  It first didn't work.  Then when I changed them again, it gave an error.  Perhaps that isn't sorted in this pull request.

2023-02-23 08:48 UTC, anastasia-mbithe commented
@rdstern, I have been using the script window to test this. And we dont have a table output at the moment since we changing / saving the gt tables as either rtf, word, latex or raw html formats, which are not supported by the save control right now. Thats what @Patowhiz had to look at. Sending the code to the script window and assigning the last line to a variable name i.e use_last_table i get this:
![image](https://user-images.githubusercontent.com/89011047/220858018-8844c516-791a-421b-a982-82991176d781.png)
![image](https://user-images.githubusercontent.com/89011047/220858240-1adbd024-fe7d-4ff4-8e7b-47d338cdbf96.png)

Alternatively, we can have a checkbox so that the table(s) are not saved in a certain format by default. When unchecked, we just use the table and add, maybe the formats. if checked, we save it in a certain format rtf,word,latex or raw html.

2023-02-23 08:56 UTC, N-thony commented
@rdstern @anastasia-mbithe I think for some function which is producing the output in the format not supported yet, we can customized those function in the way to return the result in a temporary file in the format required and save it? I think this can be used as an alternative. 
We just need to sink the output to the temp file with the format requested. I can discuss more about this approach with @Patowhiz and see if it is usefull?

2023-02-23 09:29 UTC, rdstern commented
@anastasia-mbithe and @N-thony I am happy if the different format options are disabled for now.
What I would like to be able to do is get the object back, and then change or add some of the format table options.
Later a few - perhaps some default themes, and addition of a title may be also on the main page.

2023-02-24 09:20 UTC, anastasia-mbithe commented
@rdstern, which default themes do you suggest to go to the main page? And should we also add a title to the main page when we have it in the Format options sub dialog as well?

2023-02-28 19:55 UTC, rdstern reviewed
@anastasia-mbithe I have the same problems as when I looked before.
I used the survey data and did a minimal frequency table.  Then, in Use Table I added a title and got this error:
![image](https://user-images.githubusercontent.com/11226469/221964185-72285e25-a2eb-47c6-8bd1-79554c810f76.png)


I have a zero success record.  I have not been able to change anything in a table so far, without getting this sort of error.

2023-03-01 06:40 UTC, anastasia-mbithe commented
@rdstern , the table object to be used has to be specifically a **gt table**, that is  only created from the Tables > Frequency/Summary Tables dialog

2023-03-01 06:56 UTC, rdstern commented
@anastasia-mbithe thanks.  I did save it from the Describe > Tables... dialogue.  So it should have been a gt table.  It was a simple 2-way frequerncy table from our little survey data of village by variety.

2023-03-01 10:09 UTC, rdstern commented
@anastasia-mbithe my mistake as usual.  I keep forgetting to synch the master.  Now I am getting your improvements and they are exciting - but see below - again.  It is the same error as before:

![image](https://user-images.githubusercontent.com/11226469/222108019-28ccb63c-7633-428d-a150-c291c9c92a69.png)

I did multiple saving and it started well.  Very well.

Then, as you see on the bottom right, above I saved the saved one (which had a title and a footnote) and then changed the footnote.  Now it gave me 1,1 and 2,2 after the titles.  And when I deleted the footnotes, the 1 and 2 at the titles were still there.  Then I added the fottnote again and got the error shown.

2023-03-01 13:00 UTC, anastasia-mbithe commented
@rdstern , I hope that bug is fixed now

2023-03-21 10:26 UTC, lilyclements commented
@anastasia-mbithe this is looking really nice, and making some great headway on it. After our conversation on the "undo"-ing of changes to the table, I have some suggestions.

We want to set bits to be `NULL` if the user **removes text from a text input box**:

```
# Creating table and mmtable2
summary_table <- data_book$summary_table(data_name="Sheet1", columns_to_summarise=c("size","fert"),
                                         treat_columns_as_factor=TRUE, summaries=c("summary_mean"))
last_table <- (mmtable2::mmtable(data=summary_table, cells=value) +
                 mmtable2::header_top_left(variable='variable') + mmtable2::header_top_left(variable='summary'))

# Our table
last_table

# Then we add a title
last_table_title <- last_table %>% gt::tab_header(title="hi") %>% gt::tab_style(style=gt::cell_text(font="NULL", size=gt::px(18)), location=gt::cells_title(groups="title"))
last_table_title

# Then if we remove the title we just want to say `title = NULL`.
last_table_no_title <- last_table_title %>% gt::tab_header(title=NULL) %>% gt::tab_style(style=gt::cell_text(font="NULL", size=gt::px(18)), location=gt::cells_title(groups="title"))
# or this also works, whichever is easier:
last_table_no_title <- last_table_title %>% gt::tab_header(title=NULL)

# then we can see our last_table is the same as our table with the title removed
last_table
last_table_no_title
last_table_title
```

2023-05-03 09:22 UTC, rdstern commented
@anastasia-mbithe and @lilyclements I assume this may now also change with the dropping of mmtable2.  Or does it only make use of gt?  Is it ready for testing again yet?

2023-05-17 13:05 UTC, anastasia-mbithe commented
@lilyclements and @rdstern, this is ready for review.
Since, we moved from mmtable2 to gt, the functions in the sub dialog are now compatible, after making some changes, and the issues we had of repetition and not undoing are fixed now.

2023-05-18 16:48 UTC, rdstern approved these changes
I am approving, so we implement this dialogue (without mmtable2) as soon as possible.  @lloyddewit I hope it is ok?

Then could @anastasia-mbithe and @lilyclements also consider the items below and - if feasible - then make a new issue, or have this pull request only partially completing the existing issue?

I would like us also to reflect on what else might be possible when we use a table.
a) Could the Table to Use label be just Table.
b) Could we have a table witout margins and add, or change the margins here?  If so, then we could include the margins stuff from the main tables dialogue.
c) Could we change the layout?  If so, then we could add the layout controls from the main dialogue.  
d) If b) and c) then maybe each would start with the existing settings in the existing table?

2023-05-19 07:27 UTC, lilyclements commented
@rdstern I have added your commented and replied to them in issue #8339

2023-05-19 10:24 UTC, lloyddewit requested changes

2023-05-19 10:24 UTC, lloyddewit commented on instat/dlgUseTable.vb
> +    Private Sub ucrCoreControls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrTablesReceiver.ControlContentsChanged, ucrSaveTable.ControlContentsChanged
```suggestion

    Private Sub ucrCoreControls_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrTablesReceiver.ControlContentsChanged, ucrSaveTable.ControlContentsChanged
```

2023-05-19 10:24 UTC, lloyddewit approved these changes
@anastasia-mbithe clean, readable code - thank you

2023-05-19 10:24 UTC, merged