Ensured Output system for One Way frequencies worked correctly
africanmathsinitiative/R-Instat pull request #8146
Opened 2023-02-16 12:18 UTC by derekagorhom

fixes partly #8094 
@rdstern , @N-thony 
I was able to fix the output system for the `Table` and `graph` options of the dialogue and also i fixed the issue of the `stem and leaf` not producing any results

2023-02-21 16:16 UTC, rdstern requested changes
@derekagorhom that is much better now.  Could you change the code generated for the Table option, so it separates getting the variables from the sj function.  It now seems ok for the graph and I am happy we have the stem and leaf plot again.

2023-02-22 10:15 UTC, derekagorhom commented
@rdstern 
i did the code for the output to display

`columns <- data_book$get_columns_from_data(data_name="survey", col_names=c("village","field"), remove_labels=TRUE, drop_unused_filter_levels=TRUE)`

`one_way_freq <- as.data.frame(x=sjmisc::frq(x=columns, show.strings=TRUE, show.na=TRUE, grp.strings=NULL))
data_book$import_data(data_tables=list(one_way_freq=one_way_freq))`

`data_book$get_data_frame(data_name="one_way_freq")`

`rm(list=c("one_way_freq", "columns"))` 

on the script widow.

2023-02-22 12:04 UTC, rdstern commented
@derekagorhom thanks, this now seems to work fine.
However I am afraid I have stumbled on another small problem.  The earleir version permitted text or html output, with the html going to a browser.  Now we have html in the output window, but seem to have lost that option.  In the sjmisc::frq command it should come from adding out="viewer" to the function, and then the html option to the data_book_add_object function.  
This adds a third option to the dialogue.  @Patowhiz alternatively we now just have html as the output format in the output window?  What do you think?  I quite like the options of text or html, but don't feel strongly?

2023-02-23 11:41 UTC, derekagorhom commented
@rdstern i managed to add the maximise to the output for the dataframe button.

2023-02-27 09:18 UTC, N-thony requested changes

2023-02-27 09:18 UTC, N-thony commented on instat/dlgOneWayFrequencies.vb
> +    Private clsGetColumnsFunction As New RFunction
Can you move this on before line 330 i.e Dim clsGetColumnsFunction As New RFunction?

2023-02-27 09:18 UTC, N-thony commented on instat/dlgOneWayFrequencies.vb
> +        clsGetColumnsFunction = New RFunction
then you remove this

2023-02-27 09:18 UTC, N-thony commented on instat/dlgOneWayFrequencies.vb
> +        'ucrReceiverOneWayFreq.SetRCode(clsSjMiscFrq, bReset)
remove?

2023-02-27 09:18 UTC, N-thony commented on instat/dlgOneWayFrequencies.vb
> +        clsSjMiscFrq.AddParameter("grp.strings", "NULL")
Can you add the positions?

2023-02-28 13:07 UTC, derekagorhom commented
@N-thony I have made the changes requested.

2023-02-28 18:08 UTC, rdstern requested changes
@derekagorhom perhaps I didn't make myself clear last time.  Here is the dialogue in Version 0.7.8

![image](https://user-images.githubusercontent.com/11226469/221940793-6a35304b-d769-4ea0-a275-91713242fc9e.png)

You see that html output in the browser was then possible.  So now we no longer have html - and just when this is now an option in the output window.

You could add it, so the first option is txt, the second is the html - this time in the output window.  (That was supposed to be the main change with the new output window.)

I don't have a problem with the addition of the new option as dataframe, so that can stay if you wish.

2023-03-02 06:40 UTC, Patowhiz commented
@derekagorhom I think we discussed with @anastasia-mbithe and @Vitalis95 about similar options. Check with them.

2023-03-06 13:30 UTC, derekagorhom commented
@rdstern I was able to implement the HTML option to this dialogue, but the problem is that it is not able to produce any results in the output window so i made the result display in the browser. 
I have had conversations with both Anastasia and Vitalis and we still don't know why it does not produce the HTML result in the output.

2023-04-18 06:55 UTC, Patowhiz commented
@derekagorhom I'll now work on this.

2023-06-07 07:57 UTC, rdstern commented
@Patowhiz will you still be doing this?  I am keen to "finish" all these options for the Describe > One Variable and 2/3 Variable as soon as possible.

2023-07-07 09:28 UTC, N-thony commented
> @Patowhiz will you still be doing this? I am keen to "finish" all these options for the Describe > One Variable and 2/3 Variable as soon as possible.

@derekagorhom is this fixed/replaced by another PR already? If so, can you close this PR?

2023-07-07 11:04 UTC, closed without merging