Added Longitude, Latitude, Altitude on Define Climatic Dialog
africanmathsinitiative/R-Instat pull request #8147
Opened 2023-02-17 08:06 UTC by MeSophie

Fixes Partially #8137

@rdstern I done the first step of this issue.

@lloyddewit, @N-thony  Please can you have a look ?

2023-02-18 10:52 UTC, lloyddewit requested changes

2023-02-18 10:52 UTC, lloyddewit commented on instat/DlgDefineClimaticData.vb
> +        Dim kvpLongitude As KeyValuePair(Of String, List(Of String)) = New KeyValuePair(Of String, List(Of String))("latitude", {"latitude", "lat"}.ToList())
swap names?
```suggestion
        Dim kvpLongitude As KeyValuePair(Of String, List(Of String)) = New KeyValuePair(Of String, List(Of String))("longitude", {"longitude", "lon"}.ToList())
        Dim kvpLatitude As KeyValuePair(Of String, List(Of String)) = New KeyValuePair(Of String, List(Of String))("latitude", {"latitude", "lat"}.ToList())

```

2023-02-21 08:56 UTC, rdstern reviewed
@MeSophie this is looking very promising.  Can you try with the file from the library with the 4 stations linked data.  This will need some correction, but that is not an issue for this dialogue.
a) The linking variable is the station name, so that should be detected.  I assume you use the data file first.  Then go to the

2023-02-21 09:56 UTC, MeSophie commented
> @MeSophie this is looking very promising. Can you try with the file from the library with the 4 stations linked data. This will need some correction, but that is not an issue for this dialogue. a) The linking variable is the station name, so that should be detected. I assume you use the data file first. Then go to the

@rdstern Sorry it look like you didn't finished your instructions.

2023-02-27 09:22 UTC, N-thony commented
> @MeSophie this is looking very promising. Can you try with the file from the library with the 4 stations linked data. This will need some correction, but that is not an issue for this dialogue. a) The linking variable is the station name, so that should be detected. I assume you use the data file first. Then go to the

@rdstern could you complete your reviews/comments?

2023-03-09 08:45 UTC, MeSophie commented
@N-thony  I resolved the bug with check duplicate. This PR is ready for review.

2023-03-23 05:22 UTC, N-thony commented
> @N-thony I resolved the bug with check duplicate. This PR is ready for review.

@MeSophie looks good, @rdstern can you test?

2023-07-04 12:20 UTC, closed without merging