Fixed a bug in ucrSelector
africanmathsinitiative/R-Instat pull request #8157
Opened 2023-02-21 07:46 UTC by Vitalis95

Fixes #8155 
@rdstern @lloyddewit @N-thony , fixes a bug when variables added to the receiver are excluded from the selector

2023-02-21 08:20 UTC, rdstern requested changes
@Vitalis95 great - that's much better.  

But it didn't "remember" the variables.  So, when I returned to the dialogue, the receiver was cleared.

2023-02-22 10:08 UTC, Vitalis95 commented
@rdstern , have a look at it.

2023-02-22 11:28 UTC, rdstern approved these changes
Excellent.  @lloyddewit this was a nasty bug in the climatic, so good if we can get the corrections into the forthcoming release

2023-02-23 08:39 UTC, lloyddewit approved these changes

2023-02-23 08:41 UTC, merged