Ensured R help package html file to display to the maximize dialogue rather than the browser
africanmathsinitiative/R-Instat pull request #8159
Opened 2023-02-21 12:10 UTC by N-thony

@rdstern this is ready for you to test. I made the changes in the FromLibrary, HelpVignettes, HypothesisTestsCalculator, Modelling, UseModel, and Calculator Dialogues.
@lloyddewit could you have a look of the code?
Thanks

2023-02-21 12:33 UTC, rdstern reviewed
@N-thony this is excellent.  The only one that doesn't work is in the R Documentation the Vignettes option works in 0.7.8 see below and doesn't do anything in the new version.

![image](https://user-images.githubusercontent.com/11226469/220345763-a0ec569e-b70b-4935-9bee-61f7094e6c78.png)

There is a simple addition needed to the dialogues, on making it R-help, but that's a separate issue.  I'll write it.

2023-02-21 14:08 UTC, N-thony commented
> @N-thony this is excellent. The only one that doesn't work is in the R Documentation the Vignettes option works in 0.7.8 see below and doesn't do anything in the new version.
> 
> ![image](https://user-images.githubusercontent.com/11226469/220345763-a0ec569e-b70b-4935-9bee-61f7094e6c78.png)
> 
> There is a simple addition needed to the dialogues, on making it R-help, but that's a separate issue. I'll write it.

@rdstern @lloyddewit I found that for the vignette, it autogenerates the html file. I need to investigate more about and it might delay this PR, if you happy we can merge this and fix the remaining in another PR?

2023-02-21 14:19 UTC, rdstern approved these changes
@lloyddewit then let's merge as is, and give many points to anyone who notices this vignette option is missing - even in the next month!.

2023-02-22 10:11 UTC, rdstern approved these changes

2023-02-22 10:22 UTC, N-thony commented
> > @lloyddewit then let's merge as is, and give many points to anyone who notices this vignette option is missing - even in the next month!.
> 
> Currently the vignette is still going to the browser,

@lloyddewit I think this can wait a bit, I found a way to display the vignette in the maximize window

2023-02-23 08:13 UTC, N-thony commented
> > > @lloyddewit then let's merge as is, and give many points to anyone who notices this vignette option is missing - even in the next month!.
> > 
> > 
> > Currently the vignette is still going to the browser,
> 
> @lloyddewit I think this can wait a bit, I found a way to display the vignette in the maximize window

@rdstern I have added the display of the vignette in the maximize window. Have a look.

2023-02-23 11:54 UTC, rdstern submitted a review, later dismissed
Great.  Good if this can be included in the February release.

2023-02-24 09:33 UTC, lloyddewit requested changes

2023-02-24 09:33 UTC, lloyddewit commented on instat/UserControls/Webview/Windows/ucrWebViewer.vb
> +            bReplace = "file:///" + strFileName.Replace("\", "/")
we are assigning a string to a boolean, is that correct?
should we assign to `strUrl` instead?

2023-02-24 09:33 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +        End If
This code is duplicated 4-5 times below.
Move this code into a public function that can be called by the different dialog boxes?

2023-02-24 09:33 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +        strURL = Path.Combine(String.Concat("http://", strLocalHost), strPort, strFilePath)
combine into single line?

2023-02-24 09:33 UTC, lloyddewit commented on instat/dlgHelpVignettes.vb
> +    Private clsGetPortFunction As New RFunction
should this be a class member? make this a local variable in `OpenHelpFile()`?

2023-02-24 09:33 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +        Dim strPackageName As String = ucrInputPackages.cboInput.SelectedItem
the remaining code in this sub, also seems to be duplicated 4-5 times in the dialogs below.
Is it possible to reduce some of this duplication?

2023-02-24 11:35 UTC, N-thony commented on instat/dlgHelpVignettes.vb
> +    Private clsGetPortFunction As New RFunction
This seems fixed now

2023-02-24 11:35 UTC, N-thony commented on instat/dlgFromLibrary.vb
> +        strURL = Path.Combine(String.Concat("http://", strLocalHost), strPort, strFilePath)
This seems fixed now

2023-02-24 11:35 UTC, N-thony commented on instat/dlgFromLibrary.vb
> +        End If
This seems fixed now

2023-02-24 11:35 UTC, N-thony commented on instat/UserControls/Webview/Windows/ucrWebViewer.vb
> +            bReplace = "file:///" + strFileName.Replace("\", "/")
This seems fixed now

2023-02-26 08:25 UTC, lloyddewit requested changes
@N-thony thank you, this looks good. Just one comment. If this can be resolved, then we can merge.

2023-02-26 08:25 UTC, lloyddewit commented on instat/dlgFromLibrary.vb
> +    Public Function GetFileURL(strPackageName As String, Optional strTopic As String = "", Optional bVignette As Boolean = False) As String
Great that you created this function.
Dialogs should be independent from each other. Putting the function in `dlgFromLibrary` means that other dialogs become dependent on `dlgFromLibrary`. 
Could we put the function somewhere else? I'm not aware of any utility class in R-Instat where we could put this type of function, can you think of any?
If not, then we could make a new class (e.g. `clsFileUrlUtilities.vb`) and use the `shared` key word for the function definition.
What's your view?

2023-02-26 08:29 UTC, lloyddewit commented
@lilyclements Please could you review the R code?

@ChrisMarsh82 I think that @rdstern would like this included in the Feb release. If @lilyclements is not able to review before you want to make the build, and I've already approved this PR, then please go ahead and merge this PR, thanks

(please note, I'm unavailable on Tuesday 28 Feb)

2023-02-26 08:56 UTC, N-thony commented on instat/dlgFromLibrary.vb
> +    Public Function GetFileURL(strPackageName As String, Optional strTopic As String = "", Optional bVignette As Boolean = False) As String
@lloyddewit this sounds good to me, I have the function to `clsFileUrlUtilities.vb`

2023-02-27 08:13 UTC, lloyddewit approved these changes

2023-02-27 11:03 UTC, rdstern approved these changes
looks fine now

2023-03-01 08:39 UTC, merged