changed grid to only update one cell if replace value is done
africanmathsinitiative/R-Instat pull request #8166
Opened 2023-02-23 14:53 UTC by ChrisMarsh82

Updated ReplaceValueInCell to only update the changed cell.

At the moment we still bring back the entire dataframe from R so there is still a delay. This would be a much bigger change and could run into errors. This change should at least half the time taken to refresh

2023-02-23 22:26 UTC, rdstern submitted a review, later dismissed
@ChrisMarsh82 I tried on a large dataset, where I had noticed the problem before.  It had 875,000 rows.
I needed to change temperaures measured such as 305 degrees to 30.5.  There were about 11 rows like this.  I first tried with a filter, so just the 11 rows were visible.  A cell change took about 4 seconds.  I bit long, but not impossible.
When I noted the row number and tried on the unfiltered data it took only 2 seconds.

I tried with your stated change and also (for comparison) with the released version.  There seemed no change in those times, between the 2 versions.

I had no problem with your new version, so am approving.

2023-02-24 08:58 UTC, lloyddewit requested changes
@ChrisMarsh82 Thank you for the changes, just some small comments.
Also, I understand that the purpose of this PR is to increase performance. During his testing, @rdstern found the speed similar to the previous version. Before we increase the code complexity, I think we should demonstrate a speed improvement. Do you have a test case that could show this?

2023-02-24 08:58 UTC, lloyddewit commented on instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
> +    Public Sub RefreshSingleCell(iColumn As Integer, iRow As Integer)
- should this sub be private?
- or could we copy these lines to line 104 and remove this sub?

2023-02-24 08:58 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +    Public Sub RefreshSingleCell(iColumn As Integer, iRow As Integer)
- should this sub be private?
- or could we copy this line to line 175 and remove this sub?

2023-02-24 08:58 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +
```suggestion
```

2023-02-24 08:58 UTC, lloyddewit commented on instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
> +        RefreshSingleCell(dataGrid.CurrentCell.ColumnIndex, dataGrid.CurrentCell.RowIndex)
This is an extra call. How does this increase performance?

2023-02-24 08:58 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +        RefreshSingleCell(e.Cell.Column, e.Cell.Row)
This is an extra call. How does this increase performance?

2023-02-24 08:58 UTC, lloyddewit commented on instat/ucrDataView.vb
> +    Private OnlyUpdateOneCell As Boolean = False
```suggestion
    Private bOnlyUpdateOneCell As Boolean = False
```

2023-02-24 11:04 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
> +    Public Sub RefreshSingleCell(iColumn As Integer, iRow As Integer)
made private

2023-02-24 11:04 UTC, ChrisMarsh82 commented on instat/ucrDataView.vb
> +    Private OnlyUpdateOneCell As Boolean = False
updated naming

2023-02-24 11:05 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +    Public Sub RefreshSingleCell(iColumn As Integer, iRow As Integer)
made private

2023-02-24 11:12 UTC, ChrisMarsh82 commented
@rdstern @lloyddewit  The changes I have made only stop the grid being fully loaded from the dataframe. The dataframe is fully refreshed so in some cases it won't appear any quicker. 

Where the benefit will come in if you have a large dataset with a lot of rows and where those rows contain lists with lots of values.
For example: 
create a dataset with one column with numbers 1 to 1000 (note: create a new dataset is broken at the minute so it will need to contain 3 columns)
add a couple more columns using the calculator "lapply( x1, function(x) {lapply(x, function(i) {choose(i, 0:i)})})"
Now when a value is changed although it still goes back to R to refresh the dataframe it doesn't need to repopulate the list in the grid which was taking a very long time

2023-02-24 11:13 UTC, ChrisMarsh82 commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +        RefreshSingleCell(e.Cell.Column, e.Cell.Row)
Although it is an extra call here ReplaceValueInData now doesn't repopulate the list

2023-02-26 08:33 UTC, lloyddewit approved these changes

2023-02-26 08:35 UTC, merged