Fixed Bugs on the NewDataFrame Dialogue
africanmathsinitiative/R-Instat pull request #8169
Opened 2023-02-24 09:38 UTC by derekagorhom

Fixes #8167 

This fixes the recent bug found when the dialogue fails to create a dataframe with less than 3 columns. 

@ChrisMarsh82 , @rdstern, this PR is ready for review.

2023-02-24 09:59 UTC, rdstern requested changes
@derekagorhom that's a releif that I think the main bug is fixed.  I couldn't get an error.  But there are still some more bits to correct.
a) As mentioned previously, when I untick the Variable Name checkbox it also works.  But when I return to the dialogue the Variable Name is ticked for me again.  The rule, in R-Instat is that the controls "remember" how they were left.  So please keep that control unticked if that was done the last time Ok was pressed.
b) I am also happy that changing a name in the variables now seems ok.  But changing the type to numeric, or factor doesn't work yet.  Please can those be fixed too.

2023-02-24 11:16 UTC, rdstern commented
@derekagorhom I hope this is still work in progress - but you need to comment more when you make changes, so I know when I should look again.  I am very keen that this is fixed in time for the February release this weekend.
So I now see the change has simply unticked the Variable Name (as it was originally).  That's not what I asked for.
I am happy that it starts by being ticked, as the initial default.
But when I then choose to untick it and press OK, it should then remember that setting for when I re-open the dialogue.

And the other problems - only character variables despite what I change - still remain.  Please also discuss with @N-thony because he did the original code and it worked fine then.

2023-02-24 11:32 UTC, derekagorhom commented
@rdstern i was not done yet... i am still making the changes

2023-02-27 08:07 UTC, derekagorhom commented
@rdstern i fixed the issue with the variable type and also made code changes to check variable name so that it is default and it can be ticked and unticked with no issues.

2023-02-27 10:53 UTC, rdstern approved these changes
@derekagorhom, well done it all seems to work fine now.
@lloyddewit it would be good to merge this, once you are happy with the code.  @ChrisMarsh82 found serious problems with the Version 0.7.8 version.

2023-02-27 15:17 UTC, lloyddewit requested changes

2023-02-27 15:17 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +        'ucrChkVariable.SetValuesCheckedAndUnchecked("TRUE", "FALSE")
```suggestion
```

2023-02-27 15:17 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +
```suggestion
        clsDummyVarFunction.AddParameter("checked", "defaults", iPosition:=1)
```

2023-02-27 15:17 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +
```suggestion
```

2023-02-27 15:17 UTC, lloyddewit commented on instat/dlgNewDataFrame.vb
> +                    .Item(i).Cells(1).Value = "x" & (iRowHeader)
```suggestion
                    .Item(i).Cells(1).Value = "x" & iRowHeader
```

2023-02-27 15:18 UTC, lloyddewit approved these changes

2023-02-27 15:20 UTC, lloyddewit commented
@rdstern I noticed that this PR reversed some of the changes made in PR #8148 . Please could you test that the problem solved by PR #8148 is still fixed?
If you're happy, then we can merge, thanks

2023-02-27 16:40 UTC, rdstern approved these changes

2023-03-01 08:49 UTC, merged