Rhelp for Model Menus
africanmathsinitiative/R-Instat pull request #8181
Opened 2023-03-01 11:39 UTC by derekagorhom

fixes #8160 
replaces #8165 

I have updated this branch with the changes done on PR  #8159  added the `Rhelp dropdown` to the Use `Model keyboard`, `Hypothesis Tests`, `Fit Mode`l and `Prepare > Column: Numeric > Enter dialogue.`

@N-thony , @rdstern this PR is ready for review.

2023-03-01 19:17 UTC, rdstern submitted a review, later dismissed
@derekagorhom well done.  This works really nicely now.
@lloyddewit I hope the code is ok, and if so it could be merged soon?
@ChrisMarsh82 if it is merged, and you are doing another build, then it would be good to include this.  It fixes a couple of small errors in the Model Keyboard dialogue.  But it isn't worth making a special effort for this.  I'd be delighted if anyone used this dialogue sufficiently to find these problems.  Maybe worth a small prize.  So no harm if it waits for the March release.

2023-03-03 08:56 UTC, lloyddewit requested changes
@derekagorhom Thanks for the PR, looks good, just a few comments

2023-03-03 08:56 UTC, lloyddewit commented on instat/dlgEnter.vb
> +        clsHelp.AddParameter("package", Chr(34) & strPackageName & Chr(34))
what is the purpose of `clsHelp`? is it used anywhere?

2023-03-03 08:56 UTC, lloyddewit commented on instat/dlgEnter.vb
> +        If strPackageName <> "" Then
It's normally cleaner and safer to check this way
```suggestion
        If Not String.IsNullOrEmpty(strPackageName) Then
```

2023-03-03 08:56 UTC, lloyddewit commented on instat/dlgHypothesisTestsCalculator.vb
> +        End If
combine into a single `If` statement using `OrElse`?

2023-03-03 08:56 UTC, lloyddewit commented on instat/dlgUseModel.vb
> +    Private Sub OpenHelpPage()
```suggestion

        Private Sub OpenHelpPage()
```

2023-03-03 08:56 UTC, lloyddewit commented on instat/dlgUseModel.vb
> +        If strPackageName <> "" Then
use `String.IsNullOrEmpty()`?

2023-03-03 08:56 UTC, lloyddewit commented on instat/dlgUseModel.vb
> +    Private Sub cmdHelp_Click(sender As Object, e As EventArgs)
is this function still used? could we delete it?

2023-03-03 09:13 UTC, derekagorhom commented on instat/dlgEnter.vb
> +        clsHelp.AddParameter("package", Chr(34) & strPackageName & Chr(34))
It is used as a function to call 
       ```
        clsHelp.SetPackageName("utils")
        clsHelp.SetRCommand("help")
        clsHelp.AddParameter("package", Chr(34) & strPackageName & Chr(34))

This  seem much easier to do than call it as `Private clsHelp as RFunction` at the beginning and again at the `Private sub SetDefaults `

2023-03-03 09:59 UTC, lloyddewit commented on instat/dlgEnter.vb
> +        clsHelp.AddParameter("package", Chr(34) & strPackageName & Chr(34))
@derekagorhom `clsHelp` is local to this `Sub` (i.e. it can only be called in this sub, nowhere else).
I agree that lines 381 to 385 initialise `clsHelp`, but then it is not used anywhere.
Should we delete lines 381 to 385?

2023-03-03 09:59 UTC, lloyddewit commented
> @lloyddewit i have made all the changes except the one related the `clsHelp function` on `dlgEnter`. can you have a look. Thanks

@derekagorhom thanks, just open comment above.

2023-03-03 10:07 UTC, derekagorhom commented on instat/dlgEnter.vb
> +        clsHelp.AddParameter("package", Chr(34) & strPackageName & Chr(34))
I understand now, I made the changes and the R help produces results too. 
Thanks for your explanation

2023-03-03 13:20 UTC, lloyddewit approved these changes

2023-03-03 13:27 UTC, lloyddewit commented
@derekagorhom thank you, looks good, happy to approve.

@rdstern there are some small changes since your last approval. If you can test/approve, then we can merge, thanks

2023-03-26 11:17 UTC, rdstern approved these changes
Looks fine

2023-03-27 09:39 UTC, merged