Added Selected Items label to multiple receivers to dialogues in Prepare > Databook sub menu
africanmathsinitiative/R-Instat pull request #8205
Opened 2023-03-08 10:05 UTC by derekagorhom

fixes partly #8203 

I have added the Selected item label to `dlgdeletedataframe`, `dlgHideUnhidedataframe` and `dlgReorderdataframe`.
This PR is ready for review
@Patowhiz , @N-thony can you review the PR.

Thanks

2023-03-09 07:12 UTC, anastasia-mbithe commented
@derekagorhom 
The feature works well. 
Though, do we really need it in the Reorder Data frame dialog? We ain't doing any selection there.
Additionally, the top, of the Hide and Unhide dialog as well as the Delete Data Frame dialog, looks so wordy and inconsistent in the (data frame & dataframe) labeling.
I would prefer having the number only( i.e Selected Data Frames: 2) it would look neater.
![image](https://user-images.githubusercontent.com/89011047/223946307-64ce9c0b-a7fc-457c-a48e-a2545875d178.png)

2023-03-09 09:51 UTC, derekagorhom commented
I removed the selected item label from the reorder dialogue and also made minor changes to the other dialogues which should make them more consistent and less wordy now. 
@anastasia-mbithe can you have a look at it again. 

Thanks

2023-03-23 05:50 UTC, N-thony requested changes

2023-03-23 05:50 UTC, N-thony commented on instat/dlgHideDataframes.vb
> +        Dim LsControl As New List(Of Control)
can you rename this variable correctly?

2023-03-23 16:26 UTC, rdstern approved these changes
Seems ok in the 2 dialogues for hide and delete.  So I am approving.
@Patowhiz did you also want it added to multiple receivers (like One Variable Summarise) where there are multiple variables?  Or were you thinking of it mainly for the delete data frames?

2023-03-24 09:28 UTC, lloyddewit commented on instat/dlgHideDataframes.vb
> +        Dim LstControl As New List(Of Control)
Does not follow naming conventions. Rename to `lstControlsUnhidden` or similar?

2023-03-24 13:36 UTC, derekagorhom commented on instat/dlgHideDataframes.vb
> +        Dim LstControl As New List(Of Control)
@lloyddewit i have made the corrections.

2023-03-27 09:13 UTC, lloyddewit approved these changes

2023-03-27 09:16 UTC, merged

2023-04-18 06:31 UTC, Patowhiz commented
@rdstern @derekagorhom I was thinking of this to be added everywhere there is multiple variables selection. So this functionality to be inside the multiple receivers.
This is particularly important when users are working with many variables. Confirming the number of selected variables eases the use of the software.

2023-04-18 06:45 UTC, Patowhiz commented
@derekagorhom if fixed as expected in the issue, changes made on the dialogs in this PR will have to be reverted.

2023-04-19 07:23 UTC, rdstern commented
@derekagorhom I agree with the minor proviso that a few dialogues already have this feature - the Climatic > Tidy Daily Data is an example.  If the soltion applies generally then we should also check the code on these dialogues.