Fixed the bug in Describe> Multivariate> Canonical Correlation Analysis dialog
africanmathsinitiative/R-Instat pull request #8206
Opened 2023-03-08 13:32 UTC by anastasia-mbithe

Fixes partially #8104 

This fixes the bug that was initially produced from the code.
Also, after a discussion with @Patowhiz during the Maseno sprint, we noticed that the options initially in the sub dialog were few and could be accommodated in the main dialog. And since the sub-dialog was not used in any other dialog, we settled on having the options in the main dialog. That has also been implemented in the branch.

@rdstern, @Patowhiz, and @N-thony this is ready for review.

2023-03-23 15:46 UTC, rdstern submitted a review, later dismissed
Now seems to work fine.

2023-03-24 09:50 UTC, lloyddewit requested changes

2023-03-31 10:37 UTC, anastasia-mbithe commented
@lloyddewit, I made the changes

2023-04-03 09:15 UTC, lloyddewit approved these changes

2023-04-03 09:16 UTC, merged