Added agriTutorial package
africanmathsinitiative/R-Instat pull request #8235
Opened 2023-03-23 09:58 UTC by derekagorhom

fixes #8234 
I have added the agriTutorial package. 

@lloyddewit this PR is ready for review. 

Thanks

2023-03-23 13:51 UTC, N-thony approved these changes

2023-03-23 14:18 UTC, rdstern submitted a review, later dismissed
@lloyddewit I approve just for the form, so it can be merged.

2023-03-24 08:16 UTC, lloyddewit requested changes

2023-03-24 08:16 UTC, lloyddewit commented on instat/static/InstatObject/R/install_packages.R
> +    "agriTutorial"
```suggestion
    "prediction",
    # Tutorial Analysis of Some Agricultural Experiments. 
    "agriTutorial"
```

2023-03-24 08:16 UTC, lloyddewit approved these changes

2023-03-24 08:23 UTC, merged