Ensured that 'tmin' & 'rain' fill automatically in Climatic Boxplot dialog
africanmathsinitiative/R-Instat pull request #8243
Opened 2023-03-28 07:58 UTC by Vitalis95

Fixes partially #8213 
Fixes part h) of the issue
@rdstern , @lloyddewit , Made `tmin `variable be completed automatically and if `tmin` is missing, then `rain `be filled automatically

2023-03-28 08:17 UTC, lloyddewit requested changes
@Vitalis95 thanks, looks good, just one small suggestion

2023-04-23 15:16 UTC, rdstern approved these changes
Looks fine.  Thanks

2023-04-24 10:18 UTC, lloyddewit approved these changes

2023-04-24 10:19 UTC, merged

2023-04-30 05:56 UTC, rdstern commented
@Vitalis95 There is a serious problem here, that I hadn't noticed before:

![image](https://user-images.githubusercontent.com/11226469/235337970-df87346d-97b6-4ba0-aadc-4293298d1918.png)

It currently does just "what you say on the tin", so now includes tmin by default when loaded.

But the problem is that it remains most insistent that tmin be analysed.  So, if you change it to tmax, then it immediately changes the variable back to tmin!  That's not what is needed of course.  You should be able to analyse any element.