Simplifying the use of comments when a data frame does not have key variables in Add comment dialog
africanmathsinitiative/R-Instat pull request #8257
Opened 2023-04-04 10:40 UTC by Vitalis95

Fixes #8216 
@rdstern @lloyddewit ,added a control  `Make a column a key for the data frame` to simplify the use of comments when a data frame does not have key variables.

2023-04-12 09:38 UTC, rdstern requested changes
@Vitalis95 well done - it is fine, but working too well!

Change the label to `Make Row a Key for the Data Frame`
Don't have the saving option control.  It is just (always) called Row.  

Now the important bit.  It is only visible if there is no existing key.  I tried with a climatic dataset - which has Station and date as the key.  If there is a key, then we don't want this option.

And, of course, when you add a second comment to any data frame, then there must already be a key, so you don't have that option.


I hope that's clear?

2023-04-18 13:05 UTC, Vitalis95 commented
@rdstern , have a look at it. Thanks

2023-04-23 14:25 UTC, rdstern submitted a review, later dismissed
Looks good now.  Can merge if @lloyddewit agrees

2023-04-25 10:49 UTC, lloyddewit commented
@rdstern In issue #8216 you wrote:

> I am changing 8257 to only Partially Fix this issue

Please note that if you write 'partially fixes #8216' then GitHub just sees the 'fixes #8216' and thinks that the whole of the issue is fixed. We need to write 'fixes partially' instead. I fixed it above.

![image](https://user-images.githubusercontent.com/57253949/234254843-17272b55-8f2f-4a6b-a300-92f8b0309edc.png)

2023-04-25 10:58 UTC, lloyddewit requested changes

2023-04-25 10:58 UTC, lloyddewit commented on instat/dlgAddComment.vb
> +    Private Sub AddRemoveKeyFromAfterCodes()
```suggestion

    Private Sub AddRemoveKeyFromAfterCodes()
```

2023-04-25 10:58 UTC, lloyddewit commented on instat/dlgAddComment.vb
> +    Private Sub ucrChkMakeColumnIntoKey_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrChkMakeColumnIntoKey.ControlValueChanged
```suggestion

    Private Sub ucrChkMakeColumnIntoKey_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrChkMakeColumnIntoKey.ControlValueChanged
```

2023-04-25 10:59 UTC, lloyddewit approved these changes

2023-04-25 11:08 UTC, merged