Changing mmtable2() to gt() for Describe <Tables dialog
africanmathsinitiative/R-Instat pull request #8259
Opened 2023-04-05 08:19 UTC by anastasia-mbithe

This fixes #8248 
@lilyclements and @rdstern This is ready for testing.

2023-04-12 08:16 UTC, lilyclements commented
Great! To update, @anastasia-mbithe I will have a good review of this tomorrow and get back to you then. Do you have something to work on in the meantime?

@rdstern I suggest you hold off looking at this PR until after I've reviewed?

2023-04-13 12:21 UTC, lilyclements requested changes
Really nice job @anastasia-mbithe! Looks great, and works really nicely.

A few minor comments below. And in addition to these:
- [ ] The receiver(s) clear on reopen (this occurs for factors and summaries)
- [ ] If I check the "Treat Summaries as Further Factor" checkbox, then select the "Variable" rdo, then uncheck the "Treat Summaries as Further Factor" checkbox, there is nothing selected for the rdo buttons. I suggest that if "Variable" or "Summary" is ever checked (and "Treat Summaries as Further Factor" is not checked), then "Summary-Variable" should be checked? (Otherwise, clicking and unclicking the checkbox shouldn't affect the rdo). What do you think?

2023-04-13 12:21 UTC, lilyclements commented on instat/dlgSummaryTables.vb
>      Private clsMmtableOperator, clsSummaryOperator, clsFrequencyOperator, clsColumnOperator,
`clsMmtableOperator` can be removed (and any instances where you mention it)

2023-04-13 12:21 UTC, lilyclements commented on instat/dlgSummaryTables.vb
> +        clsSummariesList.AddParameter("summary_count", Chr(34) & "summary_count" & Chr(34), bIncludeArgumentName:=False) ' TODO decide which default(s) to use?
Out of interest, why is this changed?

2023-04-25 14:46 UTC, anastasia-mbithe commented on instat/dlgSummaryTables.vb
> +        clsSummariesList.AddParameter("summary_count", Chr(34) & "summary_count" & Chr(34), bIncludeArgumentName:=False) ' TODO decide which default(s) to use?
I guess it was some errors I was experiencing while coding, and count was working. but I have tested it and am not getting the error anymore, so I have changed it back to "summary_mean"

2023-04-25 15:42 UTC, anastasia-mbithe commented
@lilyclements, the first comment was fixed in #8027, but I have fixed it here again to avoid the repetitive bug in case the other pull request takes time before being merged.
I have fixed the other comments as well. Please have a look.

2023-04-26 07:22 UTC, lloyddewit commented
> the first comment was fixed in https://github.com/africanmathsinitiative/R-Instat/pull/8027, but I have fixed it here again to avoid the repetitive bug in case the other pull request takes time before being merged.

@rdstern I'm concerned that fixing the same issue in 2 different PRs may trigger a merge conflict. PR #8027 hopefully only needs a small regression test from you before we merge. It's been waiting for this test since 31 March so may have slipped under the radar. It would be great if we can merge PR #8027 fairly soon, thanks

2023-05-02 07:08 UTC, rdstern reviewed
@anastasia-mbithe and @lilyclements this seems to be working ok.  Great.  I can think of many improvements I would like, but would like to merge this version, (without (mmtable2) as soon as you feel it can be a replacement.  Then it become our new baseline.  The next priority will be the simpler job of replacing mmtable2 in the one-variable and 2/3 variable cases.  Then we return to this dialogue.

2023-05-02 11:11 UTC, lilyclements approved these changes
@anastasia-mbithe this is working great. A really nice job - well done. Happy for this to be merged 🥇 

@lloyddewit over to you!

2023-05-03 09:06 UTC, rdstern approved these changes

2023-05-04 13:47 UTC, lloyddewit approved these changes
@anastasia-mbithe clean, readable code as always - thanks

2023-05-04 13:48 UTC, merged