Ensured variables fills automatically in Make date dialog
africanmathsinitiative/R-Instat pull request #8260
Opened 2023-04-05 13:02 UTC by Vitalis95

Fixes partially #8213
Fixes partially part c) of the issue
@rdstern , @lloyddewit , Ensured variables fills automatically in all the buttons, swapped `single column` and `Year Month Day` and  in the 3 variable case, ensured  it goes nicely from year to month to day

2023-04-23 08:59 UTC, rdstern submitted a review, later dismissed
@Vitalis95 this looks a really good simplification for the users.  If @lloyddewit is ok I would like to merge this, before waiting for anything else.

2023-04-24 10:31 UTC, lloyddewit requested changes
@Vitalis95 Thank you for the changes.
I didn't review the code changes yet but I noticed that this PR includes 3 extra packages. These seem to be older versions of packages already included in the R-Instat repo. Please could you remove these packages from this PR?
(let me know if you have any questions).
Thanks

P.S. These are the packages I have:

![image](https://user-images.githubusercontent.com/57253949/233971516-adc69dfb-3bd6-4623-b426-f409ec799e7d.png)

2023-04-24 10:58 UTC, Vitalis95 commented
@lloyddewit , check it now

2023-04-25 09:51 UTC, lloyddewit requested changes

2023-04-25 09:51 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +    Dim lstRecognisedTypes As New List(Of KeyValuePair(Of String, List(Of String)))
better to use a dictionary type?
```suggestion
   Dim dctRecognisedTypes As New Dictionary(Of String, List(Of String))
```

2023-04-25 09:51 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +
delete this function? (see suggestion above)
```suggestion
```

2023-04-25 09:51 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +            If lstRecognisedValues.Count > 0 Then
Use dictionary and follow 'happy path keeps left' principle (to minimize indents)?
```suggestion
            Dim lstRecognisedValues As List(Of String) = dctRecognisedTypes.Item(ucrTempReceiver.Tag)
            If IsNothing(lstRecognisedValues) Then
                Continue For
            End If
```

2023-04-25 09:51 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +                    End If
more readable to write on one line?
```suggestion
                If bFound Then Exit For
```

2023-04-25 09:51 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +
In the rest of the code, we normally only leave one blank line between sections. We should be consistent.
```suggestion
```

2023-04-25 09:51 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +
```suggestion

```

2023-04-25 09:51 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +
```suggestion
```

2023-04-25 09:51 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +
```suggestion
```

2023-04-26 09:29 UTC, Vitalis95 commented
@lloyddewit , have a look at it

2023-04-26 10:07 UTC, lloyddewit requested changes
looks good, just one suggestion

2023-04-26 10:07 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +            If IsNothing(lstRecognisedValues) Then
would something like this work?
(we could then delete the function below)
```suggestion
        Dim lstRecognisedValues As List(Of String) = New List(Of String)

        For Each ucrTempReceiver As ucrReceiver In lstReceivers
            Dim bFound As Boolean = False
            ucrTempReceiver.SetMeAsReceiver()
            If Not dctRecognisedTypes.TryGetValue(ucrTempReceiver.Tag, lstRecognisedValues) Then
```

2023-04-26 10:07 UTC, lloyddewit commented on instat/dlgMakeDate.vb
> +    Private Function GetRecognisedValues(strVariable As String) As List(Of String)
delete this function?

2023-04-26 10:20 UTC, Vitalis95 commented
@lloyddewit , it is fine now

2023-04-26 10:30 UTC, lloyddewit approved these changes

2023-05-03 09:04 UTC, rdstern requested changes
@Vitalis95 I am getting an error in some cases:

![image](https://user-images.githubusercontent.com/11226469/235872401-156ee61b-d685-44e9-9b3d-9421a71984b7.png)

I got this with the dodoma.rds data from the library.  

When I run simply, it fills the dialogue nicely and runs with no problem.  It gives me date1, because date is already there.

I now changed the names, so it didn't recognise them - so year into a, month into b and day into c.  Now I have to fill the year, month and day manually.  I now get this error:

![image](https://user-images.githubusercontent.com/11226469/235873099-ec03dea7-2a37-4e6e-880a-94c96800d764.png)

I notice it generated an odd command namely:

```
# Code generated by the dialog
date2 <- data_book$make_date_yearmonthday(data_name="dodoma", year_format="%Y", month_format="%m")
data_book$add_columns_to_data(data_name="dodoma", col_name="date2", col_data=date2, before=FALSE, adjacent_column="a")
```
When I return to the dialogue, make no changes, then it runs fine and generates the correct code as follows:

```
# Code generated by the dialog
date2 <- data_book$make_date_yearmonthday(data_name="dodoma", month="b", year="a", day="c", year_format="%Y", month_format="%m")
data_book$add_columns_to_data(data_name="dodoma", col_name="date2", col_data=date2, before=TRUE, adjacent_column="a")

```

2023-05-04 09:44 UTC, Vitalis95 commented
@rdstern , can you have look at it

2023-05-04 13:40 UTC, rdstern requested changes
@Vitalis95 it now seems to work almost fine.  I tried again starting with 3 variables it doesn't recognise.  It now works in that there is no error.  It gives this code:


```
# Code generated by the dialog
date <- data_book$make_date_yearmonthday(data_name="Uzgen", day="D.D.D.", month="D.D.N.N.N.", year="D3D.D.", year_format="%Y", month_format="%m")
data_book$add_columns_to_data(data_name="Uzgen", col_name="date", col_data=date, before=FALSE, adjacent_column="D3D.D.")
```
When I run again it has before=TRUE, which I prefer!

2023-05-18 06:52 UTC, rdstern reviewed
@Vitalis95 I am keen to get these changes merged.  Can you make the fix, so that Before - TRUE each time?
Here are my 2 runs with the Dodoma data (after changing the name to `a` for the year:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/1b2b40f2-34fe-438d-a343-6b007f024dc8)

2023-05-23 08:19 UTC, rdstern commented
@Vitalis95 will you soon be able to make this (small?) change, or are you stuck?  I am keen for this improvement to be merged as soon as possible.

2023-05-23 08:40 UTC, Vitalis95 commented
> @Vitalis95 will you soon be able to make this (small?) change, or are you stuck? I am keen for this improvement to be merged as soon as possible.

@rdstern , I am stuck on that, the code is Ok but it is not working,  We discussed with @N-thony and he promised to look into it,  I suspect it might be the changes done by Patrick on the Save controls

2023-05-23 08:50 UTC, N-thony commented
> > @Vitalis95 will you soon be able to make this (small?) change, or are you stuck? I am keen for this improvement to be merged as soon as possible.
> 
> @rdstern , I am stuck on that, the code is Ok but it is not working, We discussed with @N-thony and he promised to look into it, I suspect it might be the changes done by Patrick on the Save controls

I will look into it meanwhile this can be merged.

2023-05-23 09:15 UTC, lloyddewit commented
@rdstern Shall we merge this PR for this week's release or would you prefer to keep this PR open for other changes?
thanks

2023-05-23 10:11 UTC, lloyddewit approved these changes

2023-05-23 10:11 UTC, merged