Implementing Edit Dialogue
africanmathsinitiative/R-Instat pull request #8264
Opened 2023-04-06 09:21 UTC by derekagorhom

fixes #8239 
This PR is not ready for review.
@lloyddewit as we discussed on zoom i have made the draft pull request 
the only problem with the dialogue not working is that it can not populate the columns and rows part of the rcode.

2023-04-06 10:04 UTC, lloyddewit commented
@derekagorhom Thanks, I'll try and look at this next week, and see if I can find the problem.

2023-05-05 08:23 UTC, rdstern commented
@derekagorhom I get build errors on this.
I note your message above where you say: "the only problem with the dialogue not working is that it can not populate the columns and rows part of the rcode."

I just note that this is a "partner" to the delete option - and that is doing well and populating the columns and rows with NA.  In your case, if there are multiple rows (and possibly columns" you want to populate them all with the contents.  Of course, one difference is that NA is allowed everywhere, while your result may not be permitted.  I am hoping that will already be catered for, automatically, when you type a problem text.

2023-05-05 09:10 UTC, lloyddewit commented
@derekagorhom In April, I offered to help with this PR but didn't do so yet - sorry for that.
I see that you are updating the PR again. Would you still like my help or are you OK for now?
thanks

2023-05-05 09:15 UTC, derekagorhom commented
@rdstern and @lloyddewit this PR is ready for review/Testing.
As at now the dialogue can only edit for characters, I still have to make some few minor changes.

2023-05-05 09:19 UTC, derekagorhom commented
@lloyddewit please are you on mattermost i would like to have a discussion on the dialogue

2023-05-05 09:36 UTC, lloyddewit commented
> @lloyddewit please are you on mattermost i would like to have a discussion on the dialogue

@derekagorhom Thank you for the quick chat. Great that you found a solution without needing my help. I understand that there is still one problem that needs to be fixed (the user need to press reset to update the selected cell). I suggest that @rdstern and I do the the test/review after this is resolved. Please let us know when this is done.
Thanks

2023-05-05 10:01 UTC, derekagorhom commented
> > @lloyddewit please are you on mattermost i would like to have a discussion on the dialogue
> 
> @derekagorhom Thank you for the quick chat. Great that you found a solution without needing my help. I understand that there is still one problem that needs to be fixed (the user need to press reset to update the selected cell). I suggest that @rdstern and I do the the test/review after this is resolved. Please let us know when this is done. Thanks

Sounds good to me, thanks

2023-05-05 10:05 UTC, rdstern commented
@derekagorhom this is very promising.  I thought I'd check early to see where you have got to.
a) The menu should say Edit Cell(s) to parallel the Delete Cell(s) just above.  However, there are more changes needed to the right-click menu so that can wait.
b) It seems to check the entry against a valid variable name.  That's not needed and is at least one reason I can't enter a number.
c) It seems one behind in what it remembers.  So when I moved from the Variety column ( a factor) to the Fert column, it was still checking against the allowed values in the variety column.  OK after reset - perhaps that's what you mentioned earlier.
d) When I marked multiple rows it only edited the first of them.
e) Like the Rename Column dialogue (also on right click) it could have a field with Current Value.  Then you edit the field you have, called New Value: which initially has the same contents as the Current value.

2023-05-12 09:52 UTC, derekagorhom commented
@rdstern when making the new changes we discussed yesterday. I realized that the reogrid recognizes rows according to their position i.e row ="1", so this makes it difficult to pick the value from the cell since it only pick its position rather (this is the same for the delete cells too)

2023-05-12 10:41 UTC, rdstern commented
@derekagorhom I assume that's because you are avoiding using R.  I assume if you use R it can easily give you the value and will also be able to inform you of the type of variable, 

My R isn't good enough, but when I use the survey data from the library and do:

survey <- data_book$get_data_frame(data_name="survey")
as.numeric(survey[4,6])

I get the value 33.6, which is the yield in the 4th row of the yield column.


You could start by asking @fran2or because my R isn't good enough to take you further.  If that doesn't work, then we'll try Lily.

2023-05-16 13:32 UTC, derekagorhom commented
@N-thony I have made the changes and now the elements in the cell can be viewed in the dialogue and edited

2023-05-17 07:31 UTC, N-thony requested changes

2023-05-17 07:31 UTC, N-thony commented on instat/dlgEdit.vb
> +        strNewValue = strNewValue.Trim()
remove? it seems to not be needed

2023-05-17 07:31 UTC, N-thony commented on instat/dlgEdit.vb
> +        clsReplaceValue.AddParameter("rows", Chr(34) & StrRowIndex & Chr(34))
can you add the positions?

2023-05-17 07:31 UTC, N-thony commented on instat/dlgEdit.vb
> +
remove?

2023-05-17 07:31 UTC, N-thony commented on instat/dlgEdit.vb
> +
remove?

2023-05-17 07:31 UTC, N-thony commented on instat/dlgEdit.vb
> +
remove?

2023-05-18 15:49 UTC, rdstern requested changes
@derekagorhom this is looking promising.
a) It worked for a Factor variable, but I got this odd error when changing a numeric value.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/7583d9bf-be7c-452f-9763-f867521cbfee)

b) Please could the old Variable and the new Variable controls be the same width.

c) Could the new variable start with the same contents as the okd Variable ( as it would in Excel or Open Office)

d) Now a bigger challenge!  If the variable is a factor, then could there be a pull-down with the levels of the factor in the New Variable.  One in which you could perhaps type, and with the default being the current value.

I hope you could adapt the code from an existing dialogue.  Therre are probably more, but the Climatic > Tidy > Enter Data dialogue > Select station control.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/ed617bbd-199a-4bec-bf7a-dea7e9d73a2b)

e) Can you add the code from the main data selector which gives the column type - see below:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/6c30125f-a3da-41fa-8f2f-2faac54fb15e)

2023-05-19 10:28 UTC, derekagorhom commented
I have fixed items B -E . 
I am still working on fixing the issue of a)

2023-05-19 10:54 UTC, rdstern reviewed
@derekagorhom that's good progress.

But, when a factor is selected we don't need an extra control for the levels.  It is the New Value control that becomes a pull-down..  Then it is easy to change the value there, without typing.

2023-05-19 15:05 UTC, rdstern commented
@derekagorhom I am not sure I meant to have the usual data selector and so have an "ordinary" dialogue here? 
Here is your current dialogue:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/b7991f0e-ff26-45cc-9da6-0946eaabc3e6)

You will notice I changed the Vareiable, because ytour dialogue permits this!  But you did not change the cell contents.  If you wish to continue with the structure, then please change Column Name to Column:

Then also change your current `Select Factor :` to `Row:`

And I thought this would be very difficult, but I have just realised that this is now very similar the the idea and the code in the Add Comment dialogue!  This gas just been enhanced by @Vitalis95 so you could share with him if you wish.

In particular the Add Comment needs the data frame to have Key fields.  And Vitalis ahs just added the code for this in (I think) a pretty clever way.  So, you can add the same control here.  When there are key fields the row is shown in the Comments data frame, and will want it displayed here - so don't display anything if there are no key fields, but next time (when there are) you can display it.

This is looking very exciting now!

2023-05-22 16:00 UTC, rdstern reviewed
@derekagorhom this now all seems to work.  Well done.

But it looks very odd with the extra control when there is a factor.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/ed77a49c-f6d7-45d8-9466-be699ff38d6d)
 So you are changing the value in the drop down, but the old value is still visible in the disabled control called New Value.

When you change a numeric variable that odd extra control is still visible, but disabled.

I'd really like just the one control for the New Value.  Which is as you have it for numeric and the drop down for a factor.

My ideal would be a control for the factor that you could alternatively type into.  But I am happy with the list if that is tricky.

One other small change.  Could you make the Column and Row controls back the the same "ordinary" size for them  So they remain left-aligned as now, but are not so wide.  I like the width of the old and new controls as they are.

(Finally, as you are getting so much better as a programmer now, we will merge this one once you have made these small changes.  But can you think of anything else I might be asking for later?  Still just in editing a single cell.)

2023-05-24 16:03 UTC, rdstern commented
@derekagorhom can you check please - I get build errors

2023-05-25 07:35 UTC, lloyddewit commented
Replaced by #8354

2023-05-25 07:35 UTC, closed without merging