Added a layer parameter for density ridges
africanmathsinitiative/R-Instat pull request #8289
Opened 2023-04-26 11:33 UTC by anastasia-mbithe

Fixes #8283 
@rdstern This is ready for testing.

2023-05-02 11:52 UTC, N-thony approved these changes

2023-05-03 06:15 UTC, rdstern requested changes
@anastasia-mbithe very nice except the command should have a rel_ in front.  It is:
`geom_density_ridges(rel_min_height=0.01)`

2023-05-03 14:50 UTC, rdstern approved these changes
@anastasia-mbithe that now looks fine.  Great.

2023-05-04 13:32 UTC, lloyddewit approved these changes

2023-05-04 13:33 UTC, merged