Design changes bar chart
africanmathsinitiative/R-Instat pull request #8294
Opened 2023-04-28 10:27 UTC by derekagorhom

Fixes partly #8288 

This Fixes the Item c on the list. 
Item b is being fixed in PR #8293 by @lloyddewit 
Item a will be fixed after PR #8293 is merged

This  PR is ready for review 

@COLIEWO can you test this. 
Thanks

2023-04-30 06:43 UTC, rdstern submitted a review, later dismissed
@derekagorhom this looks fine and I also like your summary of which part of the issue it is fixing.  I also looked in Russian and the layout looks fine there.
I hope @COLIEWO will soon be involved, but would be happy for this to be merged as a start.  And I have, of course, now found an item d) to add to the list!

2023-05-01 07:39 UTC, lloyddewit requested changes

2023-05-01 07:39 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +    End Sub
these changes were probably added automatically while you were working in the designer tool. remove them?
```suggestion
```

2023-05-01 08:08 UTC, COLIEWO commented
@derekagorhom sorry for the delayed response, the positioning of the labels looks okay.

2023-05-01 09:18 UTC, lloyddewit approved these changes

2023-05-01 09:19 UTC, merged