Fixed Bugs  in the Bar chart dialogue
africanmathsinitiative/R-Instat pull request #8316
Opened 2023-05-09 10:52 UTC by derekagorhom

Fixes partly #8288 
This PR is ready for review
@rdstern i was able to fix items d, e, and g.
Item f will be fixed along with the new ones @COLIEWO found recently

2023-05-10 11:07 UTC, derekagorhom commented
@COLIEWO ,  @rdstern the new changes solved the issues of item f and also the latest correction by celestine on` vjust` being changed from "5" to "1.5"

2023-05-15 08:28 UTC, rdstern requested changes
@derekagorhom this is looking good.  However, while you are there I looked at the translation into French.  Adding better width of labels would be good at the same time.
And @MeSophie could you please edit the database to improve the translation of a Pie chart - which is Tart and should be Camembert and also Donut seems to be Anneau.  @derekagorhom  please make sure the labels have enough space for these.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/b644db4b-e29b-46ea-a57a-7c0422433d60)

1. @derekagorhom you see the Reorgansier la - that (In English) is `Reorder Frequencies`  I suggest you get rif of the Frequencies here (Like the simple Reorder lower down.  Then the French will automatically be complete/
2. Towards the bottom make the label wider for the Save control label - there is plenty of space.
3. For the Pie (Tart) just make sure that the label is wide enough for when Sophie has added the correct Camembert translation.

2023-05-15 11:09 UTC, derekagorhom commented
@rdstern I have made layout changes you requested, but Item a) will @lloyddewit to make database change in the `Id_text` for it to be complete.
I have also increased the length of the `pie` and `donut` checkboxes

2023-05-15 20:18 UTC, rdstern requested changes
@derekagorhom Here is a small problem, with the add.factor addition, so it can handle numeric data better.

```
# Code generated by the dialog, Bar Chart
diamonds <- data_book$get_data_frame(data_name="diamonds")
last_graph <- ggplot2::ggplot(diamonds, mapping=ggplot2::aes(x=forcats::fct_infreq(f=as.factor("carat")), fill="")) + ggplot2::geom_bar(stat="count") + theme_grey()
data_book$add_object(data_name="diamonds", object_name="last_graph", object_type_label="graph", object_format="image", object=check_graph(graph_object=last_graph))
data_book$get_object_data(data_name="diamonds", object_name="last_graph", as_file=TRUE)
```
In the code where you added as.factor, the variable is in quotes, here "carat".  Please delete the quotes.

2023-05-16 07:13 UTC, N-thony requested changes

2023-05-16 07:19 UTC, N-thony commented
> @derekagorhom this is looking good. However, while you are there I looked at the translation into French. Adding better width of labels would be good at the same time. And @MeSophie could you please edit the database to improve the translation of a Pie chart - which is Tart and should be Camembert and also Donut seems to be Anneau. @derekagorhom please make sure the labels have enough space for these.
> 
> ![image](https://user-images.githubusercontent.com/11226469/238288239-b644db4b-e29b-46ea-a57a-7c0422433d60.png)
> 
> 1. @derekagorhom you see the Reorgansier la - that (In English) is `Reorder Frequencies`  I suggest you get rif of the Frequencies here (Like the simple Reorder lower down.  Then the French will automatically be complete/
> 2. Towards the bottom make the label wider for the Save control label - there is plenty of space.
> 3. For the Pie (Tart) just make sure that the label is wide enough for when Sophie has added the correct Camembert translation.

@derekagorhom can you make the checkbox `Réorganiser la` wider so that it can fit the french text.

2023-05-16 08:06 UTC, derekagorhom commented
@N-thony , @rdstern I have fixed problem with the quotes occurring in the script.
Thanks

2023-05-16 08:46 UTC, N-thony commented
> @N-thony , @rdstern I have fixed problem with the quotes occurring in the script and also increased the width of the checkbox for reorder frequency Thanks
@derekagorhom looks good now.

2023-05-17 07:12 UTC, N-thony commented
> @N-thony I corrected the translation of `Pie` and `Donut` in Crowdin. And also corrected the translation of `Experiments` , I also wanted to change the translation of `File` to `Fichier` and not `déposer` (R-Instat Menu Items) but i received this notification. please can you have a look and approve the new translation? Thank you.
> 
> ![image](https://user-images.githubusercontent.com/106779233/238668745-ac40b81c-8b55-4b8a-ac6e-1df49d2bf243.png)

@MeSophie everything is approved already, I think @lloyddewit need to merge the new PRs created to update the database with new translations.

2023-05-18 08:32 UTC, rdstern submitted a review, later dismissed
@derekagorhom well done - these now all seem to work.  It would be good to merge.  There will continue to be improvements, I am sure!  Over to you @lloyddewit

2023-05-18 10:11 UTC, lloyddewit commented
@MeSophie Thank you for the CrowdIn changes. I accepted/approved them all. I also changed `File` to `Fichier`. You should see your updated translations later today when I merge the updated Json files into the database.

2023-05-18 10:14 UTC, lloyddewit requested changes

2023-05-18 10:14 UTC, lloyddewit commented on instat/sdgPlots.vb
> +        'dctLegendPosition.Add("None", Chr(34) & "none" & Chr(34))
```suggestion
```

2023-05-18 10:14 UTC, lloyddewit approved these changes

2023-05-18 10:14 UTC, merged