Improving the Titles tab on the graphs sub-dialogue
africanmathsinitiative/R-Instat pull request #8337
Opened 2023-05-18 09:59 UTC by Vitalis95

Fixes #8299 
@rdstern @lloyddewit , this PR improves the titles tabs in Plot sub-dialog

2023-05-18 16:28 UTC, rdstern requested changes
@Vitalis95 this is looking very promising.  Just what I was hoping for.

a) Could you also tempt the Caption to be multi-line as we do in the PICSA climatic sub-dialogue.
b) Could you also add the tooltip from there that explains that \n can be used to provide a multiline caption.

c) A sutprise!
![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/2caf5242-d0d0-4558-996d-5020d1c18c8a)

Here is an example, that gave me a small surprise.  The x and y axis sizes seemed to be affected by the changes in the font size for the title, or subtitle.  (I would like also to be able to choose their size, but perhaps not there!

d) There is something odd with your code and the defaults.  I get a very different size for the plot title and sub-title when I have the defaults of 20 and 15, compared with 20.1 and 15.1.  Could thise defaults be the actual ones as well as not linking to the x axis and y axis sizes.

e) Could the Tag and New Legend Title have checkboxes, default unchecked,  The text is only visible when checked.  Maybe the tag and also perhaps the Legend needs the Size too, and I am not sure the Legend title works yet?

2023-05-22 12:25 UTC, Vitalis95 commented
@rdstern have a look at it

2023-05-22 15:37 UTC, rdstern reviewed
@Vitalis95 this is looking good now.
a) When I first unchecked the tag it was as follows:
![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/1d174780-eb02-463b-b327-e321ea4ffe97)

But when I returned to the sub-dialog the size of the tag had changed to 8?
b) In the resulting ggplot I am not sure all the components are the size givewn - sometimes it is given, and sometimes not, so it presumably uses the default.  I suggest anytime a component is used (i.e. not null) then you explicitely put the size into the R command.
c) I am not sure what the Fill is doing for the new legend?  Doesn't that provide a colour?  If so, then the type of control is not correct.

2023-05-24 10:09 UTC, rdstern requested changes
@Vitalis95 here is the graph after input of a title and sub-title and caption.
I think it is probably a single error, but it looks as though the y-axis and x-axis and legends title are the same size as the main title?

2023-05-24 12:28 UTC, Vitalis95 commented
@rdstern , have a look at it

2023-05-24 17:39 UTC, rdstern reviewed
@Vitalis95 this all seems to work well now.

My only problem is the funny 2 parameters for the legend.  This entry seems to indicate I am not the only one to be [confused](https://stackoverflow.com/questions/14622421/how-to-change-legend-title-in-ggplot).

I suggest you just have the Legend title control there  - and still use the fill parameter in the R code that you generate.
 Then we can merge.

2023-05-25 09:07 UTC, Vitalis95 commented
@rdstern , check it now

2023-05-25 10:46 UTC, rdstern submitted a review, later dismissed
@Vitalis95 great.  @lloyddewit over to you

2023-05-29 09:51 UTC, lloyddewit requested changes

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +    Private clsPlotLegendTitle As New RFunction
Please follow naming conventions and rename these 5 variables to `clsPlotElementTitleFunction` etc.

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +        'ucrNudLegendSize.SetRDefault(18)
what's the reason for commenting out some of these lines? Delete these lines?

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 09:51 UTC, lloyddewit commented on instat/sdgPlots.vb
> +
```suggestion
```

2023-05-29 10:09 UTC, lloyddewit commented on instat/sdgPlots.vb
> +    Private clsPlotLegendTitle As New RFunction
You marked this as resolved but I don't see any related changes.
Please could you let me know the status? thanks

2023-05-29 10:09 UTC, lloyddewit commented on instat/sdgPlots.vb
> +        'ucrNudLegendSize.SetRDefault(18)
You marked this as resolved but I don't see any related changes.
Please could you let me know the status? thanks

2023-05-29 10:10 UTC, lloyddewit commented
@Vitalis95 Thank you for the changes, I think there are still 2 unresolved comments above, please could you check?
thanks

2023-05-29 10:11 UTC, Vitalis95 commented on instat/sdgPlots.vb
> +        'ucrNudLegendSize.SetRDefault(18)
> You marked this as resolved but I don't see any related changes. Please could you let me know the status? thanks

@lloyddewit hold on, I am resolving a conflict I have then push it. I will notify you

2023-05-29 10:26 UTC, Vitalis95 commented
@lloyddewit , it is fine now.

2023-05-29 10:40 UTC, lloyddewit approved these changes

2023-05-29 10:41 UTC, lloyddewit commented
@rdstern There are some small changes since your last approval. If you can test/approve again, then we can merge, thanks

2023-05-30 04:41 UTC, rdstern approved these changes
Great.  Thanks

2023-06-02 13:32 UTC, merged