Improved the column right-click menu and the Edit Cell dialog
africanmathsinitiative/R-Instat pull request #8367
Opened 2023-06-05 08:05 UTC by derekagorhom

fixes #8366 
fixes #8239 
This fixes the issues of some of the properties missed when creating the Edit dialog

@N-thony this PR is ready for review

2023-06-06 07:38 UTC, N-thony commented
> fixes #8366 This fixes the issues of some of the properties missed when creating the Edit dialog
> 
> @N-thony this PR is ready for review

can you reduce the space as shown in red mark and also in the Property, `StartPosition` = `CenterScreen`
<img width="383" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/68591383/22b8d692-9dc2-4e90-9320-f61108862d90">

2023-06-06 12:00 UTC, rdstern submitted a review, later dismissed
@derekagorhom and @N-thony seems as good as before to merge, so I am approving.  In the additions later, I note that you can (in the dialog) change the variable or the row, but neither work.  So they should be disabled.  They are for information and viewing in this dialog and not for editing.

2023-06-06 17:38 UTC, rdstern commented
@derekagorhom I note that the focus (in turquise) is on the column.  Could you not have that?  You can't change an item in a receiver unless it has the focus.

2023-06-12 16:10 UTC, rdstern reviewed
@derekagorhom I like the spacing and particularly that the column and row remain visible, but are disabled.  Great.
But the Factor columns have taken a backward step.  They have lost the drop-down that gives the choice between the different levels?

2023-06-15 13:28 UTC, derekagorhom commented
@rdstern i brought back the old selector because the new one was the reason the factor dropdown was not working and i also had a discussion with @N-thony and i realised that The receiver will always be highlighted since it is linked to the selector because that is how it has been done internally, we are still looking for ways to solve this. 
In the meanwhile i have already added the date control for the dialog and it work well now. 
Can this PR be kept open while i work on the logical option so that this can also close #8239

2023-06-15 15:40 UTC, rdstern reviewed
@derekagorhom seems good except I get an error on the date.  It seems to be pointing to a different variable, from the error message:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/83fdb0e1-4743-47c8-8891-22a97f47a6db)

I look forward to the pull-down for the factor variable being re-instated as well as the logical variable.  In each of those cases I hope NA will also be possible.

I agree we want all these to be working before merging.

2023-06-16 16:21 UTC, rdstern reviewed
@derekagorhom this is coming on now, but still step-by-step.  
a) With the date the default new date should start as the same as the original date.
b) You have added the NA as an option in the Logical variable.  Well done.  Can you do the same for a factor.
c) When I use it repeatedly it seems to remember more than it should from the previous use of the dialog.  For example I checked and edited a logical column, and then tried a date.  It wanted me to change into another logical setting, and not a date.  I pressed reset and it looked very odd.  I suggest reset should just set it correctly for the current cell?

2023-06-19 11:23 UTC, N-thony commented
> @rdstern i brought back the old selector because the new one was the reason the factor dropdown was not working and i also had a discussion with @N-thony and i realised that The receiver will always be highlighted since it is linked to the selector because that is how it has been done internally, we are still looking for ways to solve this. In the meanwhile i have already added the date control for the dialog and it work well now. Can this PR be kept open while i work on the logical option so that this can also close #8239

@derekagorhom we can have a quick call on this, I think I have a solution for the highlight of the receiver

2023-06-20 12:05 UTC, derekagorhom commented
@rdstern After some discussions with @N-thony we decided to disable the reset button since it was not needed any more
we also managed to fix the remaining issues
can you review this again. 

Thanks

2023-06-21 06:06 UTC, rdstern reviewed
@derekagorhom I am afraid I found a problem below, when using R-Instat in a language other than English.  But apart from that - you seem to have "nailed" it.  I tried with numeric and factor and date.  Oh, but now I found a new different problem in the English version - see below

@derekagorhom and @lloyddewit by chance I started with R-Instat in Portuguese.  Here is the dialog when editing the variable fert, etc.  

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/1d39340d-ecb3-4d44-b8cf-aed54699e974)

It was cell 3 and the value was 3.  The items are just a bit too far left in each control.  

Here it is in English:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/3686f109-015e-4577-9efd-ba6a8778ffb4)

And here in Russian?  It isn't usable now:
![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/8becfef6-0e3c-4b2f-8d8e-9fdb42430031)

I suspect that there is a left, rather than a right-limit on the controls you are using - or vice-versa?

Now the new problem I found:  Here is a picture:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/76792f3c-7bbd-41b2-9694-5975f5d18089)

I moved data frame and - unusually in our dialogs this dialog should always "follow me".  It should always relate to the current data frame, because that is the one I am editing.  I don't know if that is simple for you, or you will need a bit of help to make this change efficiently.

But, apart from that I am very happy wiuth this feature now.

2023-06-21 18:50 UTC, rdstern approved these changes
@derekagorhom this is looking great now.  Many thanks.  I am approving.  Later we may want to be able to call it alternatively from the Edit menu.  For now, I am happy where it is!
@lloyddewit over to you.

2023-06-22 10:05 UTC, lloyddewit requested changes
@derekagorhom thanks, looks good, just a few questions

2023-06-22 10:05 UTC, lloyddewit commented on instat/dlgEdit.vb
> +    Private Sub VariableTypeProperties()
would a name like `SetControlProperties()` be more meaningful?
(function names should normally start with a verb)

2023-06-22 10:26 UTC, derekagorhom commented on instat/dlgEdit.vb
> +        ucrReceiverName.bAsReceiver = False
@lloyddewit  this was a Roger requirement see here https://github.com/africanmathsinitiative/R-Instat/pull/8367#issuecomment-1579192493

2023-06-22 10:27 UTC, derekagorhom commented on instat/ucrReceiver.vb
> +    Public bAsReceiver As Boolean = True
Its was not really a color change per say but rather to remove the focus from the receiver which led to the removal of the color.

2023-06-22 10:31 UTC, derekagorhom commented on instat/dlgEdit.vb
> +        ucrInputogical.bAllowNonConditionValues = True
I don't think so since there are for only logical values and NA. See here https://github.com/africanmathsinitiative/R-Instat/issues/8239#issuecomment-1562630841

2023-06-22 10:43 UTC, derekagorhom commented
@lloyddewit I have made the changes and answer your comments, can you review this PR again 
thanks

2023-06-22 11:04 UTC, lloyddewit commented on instat/dlgEdit.vb
> +        ucrInputogical.bAllowNonConditionValues = True
then should this be set to false?

2023-06-22 11:24 UTC, derekagorhom commented on instat/dlgEdit.vb
> +        ucrInputogical.bAllowNonConditionValues = True
@lloyddewit I have made the change
thanks for the correction

2023-06-23 06:44 UTC, lloyddewit commented on instat/dlgEdit.vb
> +        ucrReceiverName.bAsReceiver = False
@derekagorhom Thank you for the discussion this morning. I understand that the receiver is read-only but still displayed in turquoise. And we don't want the receiver to be turquoise because it will confuse the user. 
I looked at the `ucrReceiver` code and couldn't see an obviously better way to achieve what you described. So I will resolve this comment and approve.

2023-06-23 06:45 UTC, lloyddewit commented on instat/ucrReceiver.vb
> +    Public bAsReceiver As Boolean = True
Please see my comment above

2023-06-23 06:46 UTC, lloyddewit submitted a review, later dismissed

2023-06-23 06:49 UTC, lloyddewit commented
@rdstern There have been some changes since you last tested. Please could you retest? Please could you pay special attention to the column receiver (to ensure that it is read-only when required and has the correct colour?
Thanks

2023-06-23 07:29 UTC, rdstern requested changes
@derekagorhom this is still looking good.  But @lloyddewit asked me particularly to look at the variable receiver.  Here it is the first time I use Edit Cell:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/b98adfd0-944a-41d0-9844-5ae3203627f4)

But whenever I return to Edit Cell after the first time, it appears enabled - as so.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/703cefb7-ffb6-4df5-a8ee-b17ea41a5210)

It isn't a major thing, because I don't think anything can be done - though I can delete it and then I can't make the change - see below:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/db79d567-4cf9-482a-a432-92f653da28fc)

And I can't reset, because that is disabled.  So I think this needs to be fixed.  I do hope we can include it in the next release.

2023-06-23 10:13 UTC, N-thony commented
@rdstern @derekagorhom what if we simplify this by changing the `Receiver` to an `InputControl` and set it to `ReadOnly`?

2023-06-23 14:56 UTC, rdstern commented
@N-thony I don't understand the implications of your suggestion.  But it was greyed out, so disabled, the first time it is used, see above.  It is my lack of programming skills, but why can't it stay like that thereafter?

2023-06-23 15:01 UTC, N-thony commented
> @N-thony I don't understand the implications of your suggestion. But it was greyed out, so disabled, the first time it is used, see above. It is my lack of programming skills, but why can't it stay like that thereafter?

@rdstern yes, I forgot to update my comment. This is the issue with control, the code is correct with `ReadOnly` applied to it but it is not, you can still delete a text on it. I'm looking at it.

2023-06-23 15:02 UTC, rdstern commented
This has become a really nice feature to show how useful the grid can be.  So I am keen to see this finished.  Then I have lost touch with the state of the other improvements.  Did anything happen on the wrap?  And was there resurrection on the paste.  Then I would like still to proceed on the Find rows (using filter) and find columns (using select)!  There is quite a lot, still to do.

What I really like about the new Edit Cell, is that it links nicely now to helping users when there is data of different types - and (so far) numeric, character, factor, data and logical.

2023-06-27 06:15 UTC, N-thony commented
> This has become a really nice feature to show how useful the grid can be. So I am keen to see this finished. Then I have lost touch with the state of the other improvements. Did anything happen on the wrap? And was there resurrection on the paste. Then I would like still to proceed on the Find rows (using filter) and find columns (using select)! There is quite a lot, still to do.
> 
> What I really like about the new Edit Cell, is that it links nicely now to helping users when there is data of different types - and (so far) numeric, character, factor, data and logical.

@rdstern what I think it will be good for this PR to not be held up too long, is if you are okay with changes made, we cane merge it as it is for now. The issue with the receiver seems to be general because the code for it being enabled is well implemented but it is not working, I'm investigating on it and so far this can be an issue with the `.Net framework` version we are using. I will suggest that @derekagorhom might open an issue about.

2023-07-05 13:03 UTC, derekagorhom commented
@rdstern  the new changes solves all the issues raised in https://github.com/africanmathsinitiative/R-Instat/issues/8366#issuecomment-1616625051

can you review this. 
Thanks

2023-07-06 13:57 UTC, lloyddewit submitted a review, later dismissed

2023-07-06 13:58 UTC, merged