Improvements to Climatic >Inventory dlg
africanmathsinitiative/R-Instat pull request #8369
Opened 2023-06-06 10:29 UTC by Vitalis95

Fixes Partially #8342 
@rdstern , @lloyddewit @N-thony , Fixes Part **a**, **b** and **c** of the issue. Part **d** will be fixed during the sprint with help of @lilyclements

2023-06-07 05:18 UTC, rdstern commented
@Vitalis95 a) seems to be working fine.
b) Has now the correct settings in the dialog, - of month and Date order, but the code was still the same code as before - so not consistewnt with the new dialog.  See below that it is still the code by Day.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/ea2e7bb7-f59c-464a-9870-7c1e4d3a3f1d)

c) When I tried to save - to check the new key - I got the following error:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/f86a4e4e-7138-476e-a8b0-8b71c946b04b)

2023-06-07 10:02 UTC, Vitalis95 commented
@rdstern , have a look at it

2023-06-07 10:17 UTC, rdstern commented
@Vitalis95 good progress.  
a) seems ok
b) Seems ok
c) Still gives error message, but produces data frame.  
c) Does not produce the key.  If it did, then it could also provide the message about the key in the output window.  Maybe the error message concerns the key?

2023-06-07 11:38 UTC, Vitalis95 commented
@rdstern , have a look at it

2023-06-07 16:13 UTC, rdstern submitted a review, later dismissed
@Vitalis95 full marks for persistence.  Thanks.  @lloyddewit over to you.

2023-06-08 07:41 UTC, lloyddewit requested changes
@Vitalis95 Thank you, looks good, just a few very small comments

2023-06-08 07:41 UTC, lloyddewit commented on instat/dlgInventoryPlot.vb
> +
```suggestion
```

2023-06-09 07:27 UTC, rdstern requested changes
@Vitalis95 looks fine to me, but I have a very small cosmetic change I am afraid.  In the Key, could you make the `From` the first element.  So it goes From, Station, Element, Level.

Thanks

2023-06-09 08:14 UTC, Vitalis95 commented
@rdstern , its fine

2023-06-14 06:01 UTC, lloyddewit approved these changes

2023-06-14 06:02 UTC, merged