Split the Climatic > Tidy and Examine menu
africanmathsinitiative/R-Instat pull request #8385
Opened 2023-06-16 09:48 UTC by MeSophie

Fixes #8348
Fixes Partially #8346
@rdstern and @N-thony this new PR is because the PR #8377 has conflict. 
For issue #8346 we are still investigate on how to autofill multiple receiver.
The name of `Tidy Data` is still `Tidy and Examine` because the text need to be change in the data base. So @lloyddewit please can you do it for me oe let me know when you merge the PR that has data base modification.

2023-06-17 13:38 UTC, rdstern reviewed
@MeSophie this is coming on well.  
a) Could you start with the Numeri9c Variable checked.
b) In the Climatic > Check Data > Inventory the multiple receiver is filled.  I wonder if the code there might help.  Of course, that is with climatic variables and you want others in this dialog.

2023-06-19 07:27 UTC, N-thony commented
> @MeSophie this is coming on well. a) Could you start with the Numeri9c Variable checked. b) In the Climatic > Check Data > Inventory the multiple receiver is filled. I wonder if the code there might help. Of course, that is with climatic variables and you want others in this dialog.

@MeSophie I'm ready to help you with this.

2023-06-19 08:07 UTC, MeSophie commented
@rdstern Please can you check if this is the change that you want? 
I went to check Inventory plot dialog. The multiple receiver is empty but the selector shows just numeric variables.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/106779233/4a14324f-d409-45a8-a13b-6f7ba42a9055)

2023-06-19 08:46 UTC, rdstern commented
@MeSophie I got it wrong in #8346 !  Just trying to make life more difficult for you - I hope you understand!

The columns should be the months and the day variable should be in the multiple receiver.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/c0137e02-72b5-44a3-9355-191b0b198893)

Sorry about that!

2023-06-19 10:13 UTC, MeSophie commented
> 

@rdstern Please can you check the dialog again?

2023-06-19 10:43 UTC, rdstern commented
@MeSophie that's better.  Can you start with the Numeric Variable checked please.

Then, ideally you would include the year and day in the multiple receiver as well.  But if that remains tricky let's merge with the progress so far.  That can be considered later.

2023-06-19 10:47 UTC, MeSophie commented
> @MeSophie that's better. Can you start with the Numeric Variable checked please.
> 
> Then, ideally you would include the year and day in the multiple receiver as well. But if that remains tricky let's merge with the progress so far. That can be considered later.

@rdstern Please can you explain what do you means by Numeric Variables Checked?

2023-06-19 11:00 UTC, rdstern commented
@MeSophie in the dialog there is a checkbox called `Numeric Variable (Optional).`  

When it is checked, then you can see the single receiver and you have correctly added rain there by default.  But you need to  add the tick to see it.  

I hope that's clear now?

2023-06-19 11:02 UTC, MeSophie commented
> @MeSophie in the dialog there is a checkbox called `Numeric Variable (Optional).`
> 
> When it is checked, then you can see the single receiver and you have correctly added rain there by default. But you need to add the tick to see it.
> 
> I hope that's clear now?

Yes @rdstern  Thank you.

2023-06-19 11:26 UTC, MeSophie commented
@rdstern please can you check once more?

2023-06-19 12:09 UTC, rdstern commented
This seems to have become quite hard work for you.  Here is the dialog now:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/d7eee7b5-0c05-4985-b350-857ae5b8076c)

The checkbox is correctly checked.  But I would like the focus to still be on the multiple receiver, even if it remains empty.

And we now seem to have lost the statistics for the summary.  Those controls were full, but they are not now.

2023-06-19 14:10 UTC, MeSophie commented
@rdstern Please can you check the changes

2023-06-19 14:54 UTC, rdstern commented
@MeSophie that looks much better.  I was ready to suggest merging and we leave the filling of the multiple receiver for later.  But when you get the pivot table it is slightly different:

Here is the dialog:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/bb513584-8c3d-44f4-a661-cb13b483fbdc)

Looks fine, but here is the pivot table:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/f6e9a0af-479c-49d3-af7f-5856c4f558f9)


I assume, because the focus is back on the multiple receiver, it has not recognised the rain as the numeric variable?

2023-06-19 17:45 UTC, MeSophie commented
@rdstern please can you check the new change?

2023-06-19 18:22 UTC, rdstern approved these changes
@MeSophie well done.  I am approving.  Please make an issue of the small remaining addition, but this is a big change and important to get into the next version.  @lloyddewit I hope it passes your tests soon?

2023-06-20 09:51 UTC, lloyddewit requested changes
@MeSophie thank you for the clean implementation. I only had very small comments.

2023-06-20 09:51 UTC, lloyddewit commented on instat/dlgThreeVariablePivotTable.vb
> +                If strMonthCol <> "" Then
Safer to use `String.IsNullOrEmpty()` function?

2023-06-20 20:10 UTC, rdstern reviewed
@MeSophie The dialog is now completed - seemingly correctly (except for the multiple receiver of course), but the display seems to have reverted to givning the counts and not the averages of Precip?

2023-06-20 20:38 UTC, MeSophie commented
> The dialog is now completed - seemingly correctly (except for the multiple receiver of course), but the display seems to have reverted to givning the counts and not the averages of Precip?

@rdstern this is what I have from my side. For the multiple receiver problem I will check it tomorrow with Vitalis I try it alone and is still not working.
![image](https://github.com/africanmathsinitiative/R-Instat/assets/106779233/454b3bc3-40c8-4991-9373-c5eb2b9276d4)

2023-06-21 06:36 UTC, rdstern reviewed
@MeSophie I think that is because you are being too conscientious when you are testing!
a) I tried with dodoma - as you are - and put the year and day myself into the multiple reciever.  And it worked perfectly.
b) Then I tried again, but forgetting to put the year and day into the receiver.  (You can always add them later, once in the pivot table.  And it now gave me the count.
c) Then I went back to the dialog and pressed Reset and then did it all perfectly again, and it now still gives me the Counts!

Can you try going back repeatedly and also not always being sensible with the multiple receiver - perhaps just putting the year, or the day in, etc.

2023-06-21 15:32 UTC, MeSophie commented
@rdstern I couldn't solve the autofill multiple receiver problem. What Vitalis explain to me is that in inventory plot. The multiple receiver is fill automaticaly according to the variable define as `element`  in metadata. So we still need to investigate on how to autofill multiple variable with specific climatic parameters.

2023-06-22 08:37 UTC, lloyddewit approved these changes

2023-06-22 08:40 UTC, merged