Added Discrete Scale to Plot Sub-Dialog
africanmathsinitiative/R-Instat pull request #8395
Opened 2023-06-20 13:55 UTC by Vitalis95

Replaces PR #8374 
Fixes #1789 
@rdstern , @N-thony , @lloyddewit , have a look at the progress made  so far on adding the discrete scale to plots sub-dialog,

2023-06-21 11:33 UTC, rdstern requested changes
@Vitalis95 well done.  This is already partly working ok.  The title part is fine.
The label part needs a different control.  I don't know whether we have this anywhere yet.  You can use it, as it stands, by giving strings, separated by commas.  But what we need is the Prepare > Recode > Recode Factor control:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/0d96bbd0-c2d2-4a78-9bbf-5125efc5a0c5)

Maybe check with Patrick, but I suggest having the frequencies does no harm and we could perhaps use this control.  Then it delivers the new names to R separated by commas.

It should not be used unless we ask for it.  So keep the checkbox and perhaps call it `New Labels`.

Then I wasn't sure how to use the Scales?  I will have a more detailed look and mayv=be you have ideas.

I liked the Position Top and Bottom and tried it.  It didn't remember for the next time.
I liked the Drop Unised levels and that seems to work fine.

2023-06-22 06:47 UTC, rdstern commented
@Vitalis95 could you please discuss the next steps on this tab with @Patowhiz and @lilyclements.  It mostly already seems to be working, which is great, i.e.
![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/a759756b-93a6-4252-b359-7e71f3380bdd)

This is our usual survey with village (4 levels) and I am just displaying 2 of them, and I have also changed their labels.  But this is not a practical way of giving the commands, when there are a lot of levels.

Exciting that this is really getting somewhere and showing how to manipulate factors within a graph!

Above I suggested that the new labels could use an adaptation of the Recode Factor control.  But the Limits could use an adaptation of the control in the Filter (sub) dialog.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/eb4140ed-5787-4f62-927f-bb414dfc90ae)

So, I wonder if we could combine the two, so add a rename column here just before the ticks?  Here of course the default should be all the levels ticked?  

And just to add to your complications, here is the main (bar chart) dialog.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/1bd5d924-5ee8-4fab-8b09-a8f963854a0b)

This gives the bar chart in Descending order and ideally that order would be reflected in the order of the factor levels in the sub-dialog.

I suggest adapting the filter control might be better, because that control loads much more efficiently than the others.  But just choose the simplest to adapt.  I guess that's a @Patowhiz discussion?

Now the breaks possibilities.  Here is a good stackoverflow site, called ["Display every nth value on a discrete scale." ](https://stackoverflow.com/questions/52919899/ggplot2-display-every-nth-value-on-discrete-axis)

This is something I have wanted for a long time.  For example in climatic I may have the year as a factor, but I just want to label every other year.  The solution uses a function and I hope we can too?  I guess that's a @lilyclements question.  We could still call it breaks and it is a checkbox with an up-down control, with default 1 and perhaps going up to 12.

There is also this neat trick for what it calls guide, but perhaps we call it Rows (the rows for the labels)

`scale_x_discrete(guide = guide_axis(n.dodge = 2)), `

That's also considered in the same stackoverflow.  Here is the result:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/aab5904b-a59e-45a0-a5c1-02274dfe6691)


Finally - (so far), could there be a checkbox for this nice feature:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/f8e9f593-e4a5-4baa-bade-9ac186ab0c2b)

2023-06-23 09:38 UTC, Patowhiz commented
@N-thony after looking into this issue with @Vitalis95, it's best we adopt the feature  by first having a custom control for editing the labels. This will simplify the task here.

2023-06-23 11:56 UTC, N-thony commented
> @N-thony after looking into this issue with @Vitalis95, it's best we adopt the feature by first having a custom control for editing the labels. This will simplify the task here.

@Patowhiz that sounds good. We can have further discussion about it next week.

2023-06-24 19:27 UTC, rdstern commented
@Vitalis95 and @N-thony I very much agree with the custom control.

However, that will take some time.  And I suggest it would be good to have a quick fix, possibly as follows:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/af2b5531-8f93-4cf9-b3af-c7450da998f7)

In the figure above, the new custom control will take the place of the current labels and limits control.
In the stop-gap, could the Labels, be as now, perhaps wider.
And could the Limits move to the right, and becomer a similar checkbox, opening the Limits field.

They are usable, for now.  So could enable a version of this tab to be merged.

Then ask whether we could have the Breaks option on the left - which needs a function to run, see above.
And the Rows possibility as described above.  Each of these would be checkboxes I assume, so the radio buttons inside the Scales box are possibly no longer needed?  Perhaps the box is called Options instead?

2023-06-26 11:54 UTC, Vitalis95 commented
[https://stackoverflow.com/questions/35583844/keep-grid-lines-and-optional-tick-marks-when-using-breaks-ggplot](url)
The `labels` must be of the same length as` breaks`

2023-06-26 12:21 UTC, rdstern commented
@Vitalis95 that's correct.  But I think we will usually just use 1 of them at a time.

When we use both now, then we will (for now) just give them as strings with a comma between each element.  Not worth checking on the size for now, because later it will come from the user control.

2023-06-26 14:58 UTC, Vitalis95 commented
> @Vitalis95 that's correct. But I think we will usually just use 1 of them at a time.
> 
> When we use both now, then we will (for now) just give them as strings with a comma between each element. Not worth checking on the size for now, because later it will come from the user control.

Great,  test it now

2023-06-29 10:46 UTC, rdstern commented
@Vitalis95 I need to play with this now, before making the next suggestions.  I suggest this is a really important addition to R-Instat, both in its own right and because of the message it gives of R-Instat and also R.  Coping with factors in graphs is difficult, as is shown in the documentation.  So, making it easy is also difficult, but could be very worthwhile.

So no work for you yet, though I am keen to know how we might make progress on the new custom control?  But I refer here to 2 documents.  First is a "solution to one of the problems that there is sometimes.  That is long labels for the factors - what are the [options](https://www.andrewheiss.com/blog/2022/06/23/long-labels-ggplot/)?  

This is his best option:
![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/a91700a6-7e0e-4c11-8276-07db68b5a921)

Second is the standard reference for ggplot on the [position scales for discrete data](https://ggplot2.tidyverse.org/reference/scale_discrete.html).  

I really like their example, partly because it is easy in R-Instat, but I think it is the first one that is monly easy in our general dialog, and not in the special cases.  I am thinking that this case itself may be a good reason to move that dialog and give it more importance?

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/d15ae82a-1202-454c-b0e5-0139626d3784)

And here is the graph, in R-Instat - just as in the tidyverse documentation:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/f91bbc99-fc5a-4786-82f7-4e2d7f609709)


So, both the x-axis and y-axis are discrete.  How can we deal with the labels in lots of different ways.  I need to explore what options we could have on the left-hand side, to complement the new control.  Meantime I can consider what is possible with the new control, using the way you have made it.  Back with more suggestions early next week.

2023-07-01 12:57 UTC, rdstern commented
I think I now have the scales I would like for this tab.
So, in the Scales box, at thew top of it add in 3 more checkboxes, in a single row.  default is unchecked.  They are labelled  `From`:, `To:` and `By`:  If checked they show an up-down control from 1 upwards, in steps of 1.  Initially no top limit.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/a7ae9424-68e9-4692-ab83-2e2dc6bbf97c)


a) If a factor is there (on the maoin dialog, then the top limit could become the number of levels of the factor.  And the default then could be 1 for From, and the number of levels for To and 1 for the By.

I have no idea yet of the code behind.  But here is an example:

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/079e57b0-ce2e-4f46-a568-14ed8630e08d)

The x-factor has 79 levels (from 1935 to 2013, and the new control coming on the right of the dialog will let you do similar things more visually.  (but more tediously if there are loads and loads of levels.)  Here, From = 27 To: = 56 By = 2, would give the graph from the 27th level so 1961 to  1990 with labels every second year.  
I am not sure of the code yet.  I'll have a look.

b) Then above Expand, add anoither checkbox with Label Wrap Labels:  Default unchecked.  If checked it opens an up-down control with default 10 (as in the example above) and in steps of 1, Lowere limit maybe 1 for now, but see what happens, and no upper limit.  We show an example above of this really nice feature.

2023-07-06 08:51 UTC, N-thony commented
@Vitalis95 any progress?

2023-07-09 08:01 UTC, rdstern commented
@Vitalis95 I would really like to have an improved version of this dialog in the next release - which is Wednesday.  Any chance of the improvements mentioned above or should we try to merge the current version?

2023-07-10 11:14 UTC, Vitalis95 commented
@rdstern , I am still in discussion with @N-thony  about this.

2023-07-21 04:38 UTC, rdstern approved these changes
@Vitalis95 thst seems promising, so far.  I tried with the survey data and the numeric use of factors seems to work.
When I tried with the diamonds data - getting a bar chart for carat - which has many levels - then I couldn't get it to work - it just didn't seem to include the code.  

I look forward to further work on this tab.  It is important.

2023-07-21 07:57 UTC, Vitalis95 commented
@rdstern . @lloyddewit  I will make more changes on separate pull request
If this can be merged first to avoid merge conflicts since it involves multiple dialogues, and other developers are also working on it

2023-07-21 08:30 UTC, rdstern submitted a review, later dismissed
@Vitalis95 would like this to be merged.  @lloyddewit when the code is ok with you I am happy with that.  It is an important addition.  Though incomplete it is much better than nothing.

2023-07-21 08:47 UTC, lloyddewit requested changes
@Vitalis95 Thank you for this PR. 
If we set `sdgPlots.SetRCode()` to have default parameters, then it may not be necessary to change so many files.
Please could you check this? I'll then continue with my review (hopefully with fewer changed files).
thanks

2023-07-21 08:47 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +        clsOperator = New ROperator
more meaningful names?
```suggestion
        clsLeftBracketOperator= New ROperator
        clsRightBracketOperator= New ROperator
        clsSequenceOperator = New ROperator
```

2023-07-21 08:47 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +
```suggestion
```

2023-07-21 08:47 UTC, lloyddewit commented on instat/ucrAxes.vb
> +    Public Sub SetRCodeForControl(bIsXAxis As Boolean, Optional strNewAxisType As String = "continuous", Optional clsNewXYScaleContinuousFunction As RFunction = Nothing, Optional clsNewXYScaleDiscret
What's the purpose of `clsNewOperator1` and `clsNewOperator2`?
Should we give them more meaningful names?

2023-07-21 08:47 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +        'clsXScaleDiscreteFunction.AddParameter("limits", clsRFunctionParameter:=clsConcantenateFunction)
delete? (or add 'todo' comment explaining why line left in)
```suggestion
```

2023-07-21 08:47 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +
If we set `sdgPlots.SetRCode()` to have default parameters, then do we still need these variables?
```suggestion
```

2023-07-21 12:28 UTC, Vitalis95 commented
@rdstern , it works now with diamonds data(ordered factor). @lloyddewit have a look at it

2023-07-21 14:55 UTC, lloyddewit requested changes
@Vitalis95 Thank you for the changes. I don't think all my previous comments are resolved. I added some new comments to try and clarify. I'm happy to discuss if needed.

P.S. Please don't set my comments to 'resolved' otherwise I lose track of which ones I've already checked. I will set the comments to resolved when I review the changes. Thanks

2023-07-21 14:55 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +        clsRightBracketOperator= New ROperator
duplicate of above?

2023-07-21 14:55 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +    Private clsXScaleDiscreteFunction As New RFunction
In a comment below for `sdgPlots.SetRCode()`, I suggested to make the `clsNewYScaleDiscreteFunction` and `clsNewXScaleDiscreteFunction` parameters optional (with defaults of GgplotDefaults.clsYScaleDiscreteFunction.Clone() and GgplotDefaults.clsXScaleDiscreteFunction.Clone() respectively).

If we do that, then can we revert all the changes in this file (and many of the other files below)?

I'm happy to dicsuss if needed.
```suggestion
```

2023-07-21 14:55 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +        clsXScaleDiscreteFunction = GgplotDefaults.clsXScaleDiscreteFunction.Clone()
```suggestion
```

2023-07-21 14:55 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +                                clsNewYScaleDiscreteFunction:=clsYScaleDiscreteFunction, clsNewXScaleDiscreteFunction:=clsXScaleDiscreteFunction,
```suggestion
```

2023-07-24 07:48 UTC, lloyddewit commented on instat/dlgBarAndPieChart.vb
> +    Private clsConcantenateFunction As New RFunction
@vitalis this still needs resolving, thanks

2023-07-24 07:58 UTC, lloyddewit requested changes
@Vitalis95 thank you for the changes, this simplifies the code changes.
there are still many `dlg*.vb` files (13 or 14 I think) in this PR that should not be here. Please revert the changes in these files (I think mainly just blank lines) so that these files no longer appear in this PR. 
I will then complete my review, just focussing on the remaining files. 
Thanks
P.S. there is also an unresolved comment about `clsConcantenateFunction`

2023-07-24 13:39 UTC, lloyddewit requested changes
@Vitalis95 Thank you for the changes, this PR is now much simpler.
I think we can simplify the code changes further, please see suggestions.
Thanks

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +
```suggestion
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +
```suggestion
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +
```suggestion
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +        ElseIf Not bIsX Then
```suggestion
        Else
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +
```suggestion
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +            'TODO move to ggplot defaults
can we implement this 'todo' in this PR?

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +            'TODO move to ggplot defaults
can we implement this 'todo' in this PR?

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +                'TODO move to ggplot defaults
can we implement this 'todo' in this PR?

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +            clsMajorBreaksSeqDiscreteFunction.SetRCommand("seq")
duplicates line above?
```suggestion
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +
```suggestion
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +
```suggestion
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +
```suggestion
```

2023-07-24 13:39 UTC, lloyddewit commented on instat/ucrAxes.vb
> +    End Sub
combine these 2 functions?

2023-07-25 11:36 UTC, lloyddewit approved these changes

2023-07-25 11:37 UTC, lloyddewit commented
@rdstern There have been extensive changes since your last approval. In theory, the functionality should be unchanged but a good retest is probably wise, thanks

2023-07-27 17:13 UTC, rdstern reviewed
@Vitalis95 see this test example:

<img width="311" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/7c81107e-4d39-4e0d-8c2f-b6285afc26a4">

This uses the standard diamonds data from the library.  And I was keen to present just the first 20 levels - not all of them.

I notice from the code here, there is nothing wrong, but it just isn't including anything to limit the levels?  When I use the ordinary survey data for the villages it does that fine.  I wonder what is not happening?

```
diamonds <- data_book$get_data_frame(data_name="diamonds")
last_graph <- ggplot2::ggplot(diamonds, mapping=ggplot2::aes(x=forcats::fct_infreq(f=as.factor(carat)), fill="")) + ggplot2::geom_bar(stat="count") + theme_grey() + ggplot2::theme(plot.caption=ggplot2::element_text(), plot.title=ggplot2::element_text(size=20), plot.subtitle=ggplot2::element_text(), axis.text.x=ggplot2::element_text())
data_book$add_object(data_name="diamonds", object_name="last_graph", object_type_label="graph", object_format="image", object=check_graph(graph_object=last_graph))

```

2023-07-28 09:43 UTC, Vitalis95 commented
@rdstern , have a look at it

2023-08-02 16:50 UTC, rdstern requested changes
@Vitalis95 that's much better.  

a) However I noticed that the checkboxes are separate, but you need to set both of them for anything to work.  If you just set one of them then it seems to give the whole thing.  Maybe the best is to have a single checkbox that makes both visible?  Up to you.
b) I then tried clicking on the Plot Options > bar chart and found that it has both the x and y blank.  If you do that and then return, you get an error.  This (I think) may be nothing to do with your current work, so I am copying @N-thony on this message.  I think it applies to all the pull-downs on this dialog and is a regression, from 7.6, where it did not occur.  Maybe you could check this feature or it could be a new issue.

2023-08-04 06:17 UTC, Vitalis95 commented
@rdstern , part b) is fixed in @EstherNjeriLiberatta  PR

2023-08-04 08:14 UTC, rdstern commented
@Vitalis95 thanks - good spot and a great relief.  Must get that merged next week!

2023-08-05 16:38 UTC, rdstern requested changes
@Vitalis95 this now seems to work well for my examples of bar charts.
But before accepting I tried some more graphs and that seems to make it collapse.  I used the survey data for simplicity.
a) I did a line plot of yield by fert, so both continuous axes.  Then it crashes when getting plot options, because I think it is trying to get discrete all the time.  Now it should all be continuous.
b) Try also a line plot of yield by village which works - not nice plot, but that's not the point.  Then can I do anything with the xaxis (discrete) and yaxis (continuous)?

I am also not sure what to expect with the y-axis in a bar chart?

2023-08-07 16:16 UTC, rdstern commented
@Vitalis95 here is an example you could be including.  It needs the general grapics dialog.  It uses the diamonds data from the ggplot2 library and does geom_jitter with both y and x a factor. (It uses a filter to just have carat > 1 so there are less points.)
Here is the dialog, with the data and the graph:

<img width="926" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/0853af3b-4058-4f0e-a4e9-f382bb95d428">

Now, both x and y are factors.  So, when using the plot options it should go to discrete for both x and y!
I hope you agree that's pretty nice.
:

2023-08-11 16:40 UTC, rdstern commented
@Vitalis95 there are now build errors.  Perhaps this is a promising sign that you are in the midst of good changes?

2023-08-21 13:09 UTC, closed without merging