Restores Script Window Short Cut Keys
africanmathsinitiative/R-Instat pull request #8405
Opened 2023-06-22 11:29 UTC by Patowhiz

Partly fixes issue #8301.
@africanmathsinitiative/developers this is ready for review.

@lloyddewit as I understand it, the previous code replaced here, attempted to combine the top visible buttons with the context menu options.
My approach leans towards attempting to treat them differently in implementation. Unlike the top buttons, which are always visible, right click menu options are only visible when the user rights clicks. So I'm now disabling them during opening.
If a user attempts to use short cut keys, then the individual events call functions that give sensible feedback to the users.
This is what was previous there.

Thanks

2023-06-22 14:17 UTC, rdstern submitted a review, later dismissed
Another "first-time round".  Seems to work fine.  Maybe I am not critical enough.

2023-06-22 14:49 UTC, lloyddewit requested changes
@Patowhiz Thank you, this is a good approach.
Just 2 small suggestions

2023-06-22 14:49 UTC, lloyddewit commented on instat/ucrScript.vb
> +    Private Sub EnableRightClickMenuOptions(bEnable)
```suggestion
    Private Sub EnableRightClickMenuOptions(bEnable As Boolean)
```

2023-06-22 14:49 UTC, lloyddewit commented on instat/ucrScript.vb
>          Dim bScriptselected = clsScriptActive.SelectedText.Length > 0
```suggestion
```

2023-07-10 06:54 UTC, rdstern approved these changes
Nice!

2023-07-10 09:58 UTC, lloyddewit approved these changes

2023-07-10 09:59 UTC, merged