Deleting Columns to not return an error if there is no key
africanmathsinitiative/R-Instat pull request #8416
Opened 2023-07-03 07:53 UTC by lilyclements

Fixes #8413

@Vitalis95 can you review this, and then it can be ready for @rdstern to review

2023-07-03 09:51 UTC, rdstern approved these changes
@lilyclements many thanks - this seems to work fine now.  @lloyddewit over to you

2023-07-04 06:53 UTC, lloyddewit requested changes
@lilyclements Thanks looks good to me. If you can fix the indentation, then I can approve and merge

2023-07-04 06:53 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +      }
indents correct?

2023-07-04 15:04 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +      }
They should be! I just copied and pasted the file into R and then back into the VB document to autofix the indentations of everything in this file

2023-07-05 08:02 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +      }
@lilyclements I assume that you pasted the whole file into the RStudio editor, and then pasted back into the Visual Studio editor. Unfortunately the GitHub diff interprets this as all 4000+ lines changing (probably because of different white space characters and/or line breaks). This makes it impossible to see the real changes in the PR and has also triggered a merge conflict.

I suggest that you go back to the previous version of the file and fix just the indents mentioned above manually.

Note: you can get the previous version of the file by checking it out from commit `102436e`. If you're unsure how to do this, then just let me know.

I'm sorry my comment caused such trouble, I only intended some spaces to be added to the few lines above.
Thanks for your patience.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/57253949/410ce061-ea0d-4fbe-b019-cb8e4e3263e9)

2023-07-05 14:33 UTC, closed without merging