Added Tooltips to Selected Dialogues in the Describe Menu
africanmathsinitiative/R-Instat pull request #8425
Opened 2023-07-07 11:03 UTC by derekagorhom

Fixes Partly #8384 

I have added tooltips to the following dialogues 

    Bar Chart. 
    Boxplot. 
    Histogram
    Line
    HeatMap
    Cumulative Distribution
    Describe > One Variable > Frequencies. Tooltip: Table or Graph. Also Stem and Leaf Plots
    Describe > One Variable > Rating Data. Tooltip: Table, Stacked Graph or Likert Graph
    Describe > One Variable > Summarise
    Describe > Two/Three Variable > Summarise 
    Describe > Two/Three Variable > Two Way Frequencies 
    Describe > Two/Three Variable > Three Way Frequencies 
    Describe > Multivariate > Correlation 
    Describe > Two/Three Variable > Cluster Analysis

@rdstern please can you review this PR. 

Thanks

2023-07-09 18:17 UTC, rdstern approved these changes
They look fine.  Thanks

2023-07-10 07:45 UTC, lloyddewit requested changes

2023-07-10 07:45 UTC, lloyddewit commented on instat/frmMain.Designer.vb
> +        Me.mnuDescribeSpecificLineSmoothPlot.ToolTipText = " Line Plots, Smoothed Plots, Dumbbell and Slope Plots"
Strings that start or end in spaces can cause problems for the translation mechanism.
Can we remove the space?
```suggestion
        Me.mnuDescribeSpecificLineSmoothPlot.ToolTipText = "Line Plots, Smoothed Plots, Dumbbell and Slope Plots"
```

2023-07-10 07:45 UTC, lloyddewit commented on instat/frmMain.Designer.vb
> +        Me.mnuDescribeMultivariateClusterAnalysis.ToolTipText = "Partitioning or Hierarchical "
```suggestion
        Me.mnuDescribeMultivariateClusterAnalysis.ToolTipText = "Partitioning or Hierarchical"
```

2023-07-10 07:46 UTC, lloyddewit approved these changes

2023-07-10 07:47 UTC, merged