Implementing the Find In Variable and Filter Dialogue
africanmathsinitiative/R-Instat pull request #8426
Opened 2023-07-09 10:57 UTC by N-thony

replaces #8423
@rdstern please test.
I have also added CTRL + F to open the dialgoue.

2023-07-09 15:52 UTC, rdstern commented
@N-thony I checked also the Edit cell and that seems ok.

In your Find dialog it is a bit off that the find control has the TRUE/FALSE as the default options?  Was that always there?

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/789752a4-b7f0-4dc2-b8d4-f193881929d7)

2023-07-09 16:13 UTC, N-thony commented
> @N-thony I checked also the Edit cell and that seems ok.
> 
> In your Find dialog it is a bit off that the find control has the TRUE/FALSE as the default options? Was that always there?
> 
> ![image](https://user-images.githubusercontent.com/11226469/252155215-789752a4-b7f0-4dc2-b8d4-f193881929d7.png)

@rdstern you have requested this in PR #8152 
![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/417287dd-1ad7-4eee-a383-25aeed27120d)

2023-07-10 05:25 UTC, rdstern commented
@N-thony on the drop down, so I did!  The surpriuse is that TRUE is the default.  Could the default be blank instead?  Would it also be possible to include NA to get missing as another option?

2023-07-10 08:00 UTC, rdstern submitted a review, later dismissed
@N-thony nice now.  It is easy to think of improvements that could be added, but this is useful now.  So let's merge as soon as @lloyddewit is ok with the code.

2023-07-10 08:07 UTC, N-thony commented
> @N-thony nice now. It is easy to think of improvements that could be added, but this is useful now. So let's merge as soon as @lloyddewit is ok with the code.

@rdstern I was still making some changes in the R function to be able to find rows with NA.

2023-07-10 09:45 UTC, lloyddewit commented
@N-thony 
Does this PR also fix #7950? If so, should we add this to the top comment?

2023-07-10 09:51 UTC, N-thony commented
> @N-thony Does this PR also fix #7950? If so, should we add this to the top comment?

@lloyddewit that is correct

2023-07-11 11:08 UTC, lloyddewit requested changes
@N-thony This is nicely implemented and a significant piece of work - thank you.
If you're able to resolve the comments today, then we can include in release 0.7.16 tomorrow.

2023-07-11 11:08 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +                For i As Integer = 1 To lstRowNumbers.Count
I cannot easily understand what's happening in this `For` loop, add a comment?

2023-07-11 11:08 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +                        (CInt(lstRowNumbers(iFisrtRow - 1)) < iRowIndex) Then
Exceeds 100 columns, split over multiple lines?
Can the condition be simplified?
```suggestion
                    If iRowIndex >= iStartRowHeader \
                        AndAlso CInt(lstRowNumbers(iFisrtRow - 1)) < iRowIndex Then
```

2023-07-11 11:39 UTC, N-thony commented on instat/frmMain.vb
> -        dlgFind.Show()
Resolved already

2023-07-11 11:57 UTC, N-thony commented on instat/dlgFindInVariableOrFilter.vb
> +Imports RDotNet
needed on line 120 where we are executing internally the R code to get the row headers from the corresponfing dataframe.

2023-07-11 15:14 UTC, lloyddewit commented on instat/frmMain.vb
> -        dlgFind.Show()
@N-thony the `dlgFind.*` files are still in `master` branch and this PR does not remove these files. Please could you clarify 'resolved already'? thanks

2023-07-11 15:16 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +            If strPattern <> "" Then
@N-thony Thanks for making this change, please could you also fix the indentation for the rows below?

2023-07-11 15:20 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +Imports RDotNet
yes, you're correct, sorry for that

2023-07-11 15:22 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +            Dim iRowIndex = GetRowIndex(currSheet, iRow)
@N-thony Sorry, I think there's a typo in my suggested code, hopefully the meaning is still clear

2023-07-11 15:26 UTC, lloyddewit commented
@N-thony Thank you for making a start with this. I appreciate that you're not finished yet. I reviewed anyway and I think there are just 6 open comments left.
When you work on these comments, please don't set to 'resolved' (or I can't see which comments I still need to review). Just let me know when this PR is ready to review again. Thanks

2023-07-11 16:56 UTC, N-thony commented
@lloyddewit I think I resolved your comments.

2023-07-12 07:09 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +                For i As Integer = 1 To lstRowNumbers.Count
@N-thony Thank you for the comment. I still don't really understand what's going on. Please can we discuss? thanks

2023-07-12 07:47 UTC, N-thony commented
@lloyddewit I think I resolved all your comments, please have a look.

2023-07-12 08:13 UTC, N-thony commented
> @lloyddewit I think I resolved all your comments, please have a look.

@lloyddewit  I tried with the click counter as index and now I remember that the reason of the for loop was to avoid always starting at the top row. For example if the text is on page 1,2,5,9 and I'm on page 9, if I click ok it will always go back on page 1. @rdstern has suggested that it should start on the current page if the row or text exist. I'm thinking of putting the for loop back.

2023-07-12 10:21 UTC, rdstern approved these changes
@lloyddewit and @N-thony I am still ok with this as a useful feature for now - once the code is solid.

2023-07-12 13:24 UTC, lloyddewit requested changes

2023-07-12 13:26 UTC, lloyddewit approved these changes
@N-thony Thanks, looks good, happy to approve.
I just removed some comments that referred to the old variable names. Thank you for your patience

2023-07-12 14:26 UTC, rdstern approved these changes
@lloyddewit and @N-thony it is now better than I thought, as it automatically moves from page to page.  Excellent new feature to merge.

2023-07-12 14:42 UTC, merged