Correct Variable Factor order on Pivot Table Dialog in Climatic Menu
africanmathsinitiative/R-Instat pull request #8431
Opened 2023-07-11 11:10 UTC by MeSophie

Fixes #8420
@rdstern I corrected the order of factor in climatic menu. Please can you have a look?

2023-07-11 12:10 UTC, rdstern approved these changes
@MeSophie wow, that now seems perfect.  And you managed also to be able to fill the multiple receiver.
Brilliant and a great relief!  @lloyddewit I would really, really like this improvement to be in the new release.  I hope the code is ok.

2023-07-11 15:52 UTC, lloyddewit requested changes
@MeSophie Looks really good, just one comment

2023-07-12 05:59 UTC, MeSophie commented on instat/dlgThreeVariablePivotTable.vb
> +                Next
@lloyddewit I uses `Dim arrYearAndDay As String() = New String() {strYearCol, strDayCol} ` instead of  `Dim arrYearAndDay() As String = {strYearCol, strDayCol}`. By using 
```
Dim lstItems As New List(Of KeyValuePair(Of String, String)) From {
    New KeyValuePair(Of String, String)(strDataFrame, strYearCol),
    New KeyValuePair(Of String, String)(strDataFrame, strDayCol)
}
```
 I get error on   `ucrReceiverInitialRowFactors.AddMultiple(lstItems)` saying that we cannot convert the list of type List(Of `keyValuePair[of string, string])` to` keyValuePair[of string, string]()`.

2023-07-12 06:30 UTC, rdstern approved these changes
@lloyddewit this is still ok for me.  But I note @MeSophie reported an error for her this morning?  This is a feature I would really like for the forthcoming version.

2023-07-12 08:58 UTC, lloyddewit requested changes

2023-07-12 08:58 UTC, lloyddewit commented on instat/dlgThreeVariablePivotTable.vb
> +                End If
I still think it's possible to simplify this. Would something like this work?
```suggestion
                If ucrSelectorPivot.lstAvailableVariable.Items.Count > 0 Then
                    Dim lstItems(2) As KeyValuePair(Of String, String)
                    lstItems(0) = New KeyValuePair(Of String, String)(strDataFrame, strYearCol)
                    lstItems(1) = New KeyValuePair(Of String, String)(strDataFrame, strDayCol)
                    ucrReceiverInitialRowFactors.AddMultiple(lstItems)
                End If
```

2023-07-12 09:09 UTC, MeSophie commented on instat/dlgThreeVariablePivotTable.vb
> +                End If
@lloyddewit This is the error that I have
![image](https://github.com/africanmathsinitiative/R-Instat/assets/106779233/f6847e20-19ee-4934-8568-cb078eb30372)

2023-07-12 10:37 UTC, rdstern reviewed
@MeSophie I tried quickly, because this is a feature I would really like to see in the July release.  The dialog fills nicely as before, but I now get an error when Ok is pressed

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/33e0db7e-090a-4a07-ae13-45638af7ae13)


I then tried with dodoma (single station and worked before)  The dialog was not filled now, and I was unable to put the variables manually into the multiple receiver.

![image](https://github.com/africanmathsinitiative/R-Instat/assets/11226469/2c0b8c80-3439-4b1d-a53d-9e1f3338e25e)

Oh I see you have another change - I'll try again with your new version

2023-07-12 10:42 UTC, rdstern approved these changes
@MeSophie that's a relief - it all seems to work again.  @lloyddewit back to you.

2023-07-12 13:31 UTC, merged

2023-07-13 08:43 UTC, N-thony commented on instat/dlgThreeVariablePivotTable.vb
> +                If ucrSelectorPivot.lstAvailableVariable.Items.Count > 0 Then
@MeSophie can you reinforce the If condition like below? The selector is linked to the receiver, it gets stuck with the previous dataframe  which doesn't have any column we want to AutoFill in the receiver.
 ```
 If ucrSelectorPivot.lstAvailableVariable.Items.Count > 0 AndAlso
                    Not String.IsNullOrEmpty(strYearCol) AndAlso Not String.IsNullOrEmpty(strDayCol) Then
```
This should fix the bug