Implemented wrapping and unwrapping on the DataView Grid
africanmathsinitiative/R-Instat pull request #8447
Opened 2023-07-17 16:20 UTC by N-thony

Replaces #7922
Fixes #7812
Fixes partially #8443
@rdstern @derekagorhom please test the wrapping and unwrapping here.

2023-07-18 06:50 UTC, rdstern requested changes
@N-thony wow - well almost.  I will test a bit more, but it seems almost to be nailed!  Well done.  
The "almost" is a shape file.  When I originally import it is ok.

But when I try the workdwrap on the geometry variable in the shape file, then it gives a serious error and closes the file and tells me to restart.  Please could you check and see what is possible here.
If you can find where it is going wrong, then I see (at least) 3 options:
a) You may be able to fix it, so wordwrap is also possible on this type of variable.
b) It may be possible to fix under certain circumstances, e.g. the width must be more than a certain value.
c) You don't allow wordwrap on this type of variable.  (That would also be acceptable)

A second problem on the shape file is when I save it into a databook.  Then I open it again.  This is desirable, so I can make it easy for users to draw maps.  Then the data sheet comes wordwrapped - see below:
That's one of the reasons I was keen to have the wordwrap feature.  So that I could unwrap this variable!  This gives me an error as shown below:

<img width="619" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/a12911af-f7ab-4a4d-888d-7606c636c8c8">




However, after this error, it did unwrap, which is great.  So, just not doing that operation, when there are no \n, seems to work!
--------------------------------------------------------------------------------------------
That also made me try worwrap on a list variable, and that had a very surprising result - at least surprising (and attractive) for me.

I tried a new data frame of length 1000 and then the calculator divisors of x1 into x2.  Then wordwrap of x2.

This works, but it changes x2 into a character variable.  Now, if you look at my recent issue #8443 you will see that I am unable to make this transformation any other way.  (Making a list variable into a character variable makes it always NA!  So you may have a solution to part of that issue in your code!  I suggest you leave that point for now, till you see the solution for geometry-type variables.  Later we may choose to excluse list variables from those that can be wordwrapped.

2023-07-20 05:45 UTC, rdstern requested changes
@N-thony this is just great.  And almost there I think.  I first tried with list variables and that was excellent.  As you say, you have also corrected the bug, so I can get a new data frame when there are list variables.  That's so good!

It now does detect a geometry variable and labels it with a (G) that I really like.  And I am happy that you can't wordwrap it.  

a) Please correct the spelling!  It says varaible and not variable!
b) I get an error when trying to wordwrap a variable in a dataframe that has missing values in the data.  It was fine with this variable first and then I made one row missing and got an error.

<img width="634" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/b461fcc5-360e-4737-9d7c-f1d214a21b2b">

This is almost ready to merge!

2023-07-20 07:36 UTC, rdstern submitted a review, later dismissed
@N-thony this is exciting, both in its own right and in the implications for the use of the spreadsheets in R-Instat.  We need to keep testing it, but @lloyddewit it would be great to get this merged, as soon as you are happy with the code.

2023-07-21 07:24 UTC, lloyddewit requested changes
@N-thony Loooks very good, just a couple of small questions

2023-07-21 07:24 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +            Next
do we need this `For` loop?
```suggestion
            grdData.CurrentWorksheet.AutoFitColumnWidth(iColumnIndex)
```
If we did the above, then would we still need to check `iColumnIndex` for validity?

2023-07-21 07:24 UTC, lloyddewit commented on instat/dlgWordwrap.vb
> +        End If
shorten? (if you prefer to leave as is, then that's also fine)
```suggestion
        ucrBase.OKEnabled(Not ucrReceiverWrapText.IsEmpty)
```

2023-07-21 08:53 UTC, lloyddewit approved these changes

2023-07-21 08:54 UTC, lloyddewit commented
@rdstern there were a couple of small changes, please could you retest/approve? thanks

2023-07-21 10:11 UTC, rdstern approved these changes

2023-07-21 11:06 UTC, merged