Added Use as Numeric and Display as Factor checkboxes to Graphics dialog
africanmathsinitiative/R-Instat pull request #8448
Opened 2023-07-18 11:19 UTC by MeSophie

Fixes #8428 
@rdstern , @N-thony  I added `Use as Numeric` and `Display as Factor` checkbox on Graphics dialog. Please check it.

2023-09-05 16:50 UTC, rdstern commented
@MeSophie I think this change is easier than the code we started with.  I need to check with @lilyclements, but suggest you keep the first checkbox and call it Group (or Group X - I am not sure.  The second checkbox and code is deleted.  
Then I show the code you had, and my change, which I prefer - found it on stack overflow of course!
Adding the group parameter does all we need!

```
# Dialog: Graphics

survey <- data_book$get_data_frame(data_name="survey")
##last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=as.numeric(variety), y=yield)) + ggplot2::geom_line() + theme_grey()
last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=variety,group=1, y=yield)) + ggplot2::geom_line() + theme_grey()
data_book$add_object(data_name="survey", object_name="last_graph", object_type_label="graph", object_format="image", object=check_graph(graph_object=last_graph))
data_book$get_object_data(data_name="survey", object_name="last_graph", as_file=TRUE)
rm(list=c("last_graph", "survey"))
```
I have also made a new issue, on further possible improvements for this dialog, and suggest we now close this one, once this small change is merged.

2023-09-05 21:26 UTC, MeSophie commented
> I think this change is easier than the code we started with. I need to check with @lilyclements, but suggest you keep the first checkbox and call it Group (or Group X - I am not sure. The second checkbox and code is deleted.
> Then I show the code you had, and my change, which I prefer - found it on stack overflow of course!
> Adding the group parameter does all we need!

@rdstern I notice also that on your code you added `geom_line`. Will this geom_line function be added at the same time as the group parameter when the box is ticked?

2023-09-06 12:04 UTC, MeSophie commented
@rdstern Please can you check the new change.

2023-09-06 12:53 UTC, rdstern requested changes
@MeSophie this works, but the group=1 is added at the wrong time.  If I do group before chooseing the geom, then it doesn't add group=1 into the code.  If I untick, after getting the geom, and then tick again, it is fine.  The action of ticking should add the code group=1 whatevwer the geom.

2023-09-06 13:18 UTC, MeSophie commented
@rdstern I think it is okay now.

2023-09-06 13:35 UTC, rdstern submitted a review, later dismissed
@MeSophie this looks fine now.  @lloyddewit there is more to improve on this dialog, but I would be happy to see this merged first.  And the corresponding issue can then be closed.

2023-09-08 09:33 UTC, lloyddewit reviewed
@MeSophie looks good, just a couple of small suggestions

2023-09-08 09:33 UTC, lloyddewit commented on instat/dlgGeneralForGraphics.vb
> +
This seems to be a duplicate. Delete?

2023-09-08 09:33 UTC, lloyddewit commented on instat/dlgGeneralForGraphics.vb
> +            End If
simplify?
```suggestion
            ucrChkUseasNumeric.Visible = ucrReceiverX.strCurrDataType = "factor"
```

2023-09-19 08:02 UTC, lloyddewit approved these changes

2023-09-19 08:03 UTC, lloyddewit commented
@rdstern if you can retest/approve, then we can merge, thanks

2023-09-19 14:50 UTC, rdstern approved these changes
@lloyddewit this still looks fine

2023-09-21 07:53 UTC, merged