Added find feature to Select option in Find dialog
africanmathsinitiative/R-Instat pull request #8463
Opened 2023-07-27 09:49 UTC by N-thony

Fixes #8217
@rdstern I have now implemented the find feature in Select option, have a look. Thanks.

2023-07-27 10:36 UTC, rdstern reviewed
@N-thony this is great and almost seems to work already!
I tried with the hh.sav file I have sent you - in case you didn't have it.
I made a selection of about 7 variables (doesn't matter which, but I scattered them and then had some close together.: HH2, HH5, 33X.34, 33X.36, 33X.37, ST4N.1 and 2 and 3).

a) I don't think it found them all correctly - and I occasionally clicked multiple times and it seemed to stay where it was - maybe it had made later variables greeen, but they were not visible to me?
b) When I closed the dialog a green column remained.  I am happy they remain, but how should we reset them, when we don't want them green?
c) I am wondering whether you add the usual buttons at the bottom?  That's for all 3 cases.  If so, then Close is just the same as the usual close.  Could Reset them be used to get rid of the marked rows or columns as well as resetting within the dialog.  And Help will be useful anyway.  I need to get the number.  I presume Ok and script remain disabled - is there R-code for script?  
d) One item missing on the columns is which column you have found.  For the rows in your ordinary Find I note that you have a message when searching for someting that isn't there.  Could there also be the opposite - and possibly for all 3 options, but particularly useful for the select.  It would give the column number as well as the name.  (You know the number when looking at the metadata.  )
You have space either above or below the Find.  For columns It could be 
Found Variable: xxx  
Name: yyy
Label: zzz

2023-07-28 12:51 UTC, rdstern reviewed
@N-thony that is looking pretty good.
a) I was hoping that the Found Variable : 129, so would give the number.  Currently you get the name twice.
b) I am not so keen on the dialog expanding to the length of the longest label.  Could the size stay fixed.  If necessary I can scroll or have the label on multiple lines here?
c) I am not so sure about the green.  I missed it at the start.

2023-07-28 15:50 UTC, rdstern approved these changes
@N-thony this is great.  It is easy to think of improvements, but let's get this merged first - as soon as @lloyddewit is also happy.

2023-08-02 10:42 UTC, lloyddewit requested changes
@N-thony This was a significant piecw of work, it looks good. Just a few comments, thanks

2023-08-02 10:42 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +                TruncateLabelText(lblLabel, strLabel, 135)
See my comment above about making TruncateLabelText a 'pure' function.
```suggestion
                lblName.Text = TruncateLabelText(lblName, strName, 135)
                Dim strLabel = "Label: " & GetColLabel(strColumn)
                lblLabel.Text = TruncateLabelText(lblLabel, strLabel, 135)
```

2023-08-02 10:42 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +    Private Sub TruncateLabelText(label As Label, strName As String, maximumWidth As Integer)
Would it be cleaner to make this a 'pure' function (i.e. no side effects on the `label` parameter)?
```suggestion
    Private Function TruncateLabelText(label As Label, strName As String, maximumWidth As Integer) As String
```

2023-08-02 10:42 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +            label.Text = strName
```suggestion
            Return truncatedText & "..."
        Else
            Return strName
```

2023-08-02 10:42 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +
```suggestion
```

2023-08-02 10:42 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +        Dim originalText As String = strName
do we need this?

2023-08-02 10:42 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +                    MessageBox.Show(Me, "Developer error: retrieved column label should be one.", "Developer Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
make message more meaningful?
```suggestion
                    MessageBox.Show(Me, "Developer error: more than one column label found.", "Developer Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
```

2023-08-02 10:42 UTC, lloyddewit commented on instat/dlgFindInVariableOrFilter.vb
> +    Private iCountRowClick, iColumnClick As Integer
is it safer yo initialise these to `1` (either here or in `SetDefaults()` or `initialiseDialog()`?

2023-08-04 09:35 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +        If bApplyToRow Then
@N-thony I'm still a bit confused. Please could you clarify if this is correct?

2023-08-04 09:42 UTC, lloyddewit commented
@N-thony Thank you for the changes. There is one open comment above, please could you check it?

2023-08-04 09:47 UTC, lloyddewit commented on instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
> +        If bApplyToRow Then
OK, I think it makes sense, thanks

2023-08-04 09:48 UTC, lloyddewit approved these changes

2023-08-04 09:48 UTC, lloyddewit commented
@rdstern there have been some changes since your last approval. If you can retest/approve, then we can merge, thanks

2023-08-04 10:26 UTC, rdstern approved these changes
Great.  Many thanks to both of you - this is an important new feature!

2023-08-06 12:03 UTC, merged