Bug fix when wrapping or unwrapping a list column
africanmathsinitiative/R-Instat pull request #8482
Opened 2023-08-08 07:31 UTC by N-thony

Fixes partially #8443 
Fixes #8475
@rdstern this fixes the bug when wrapping/unwrapping a column to not lose the `meta data` and also correct the display of `2:1` to `2, 1`

2023-08-08 11:13 UTC, rdstern requested changes
@N-thony I am very releived you are making progress on this.  I am really keen on being able to handle lists properly in R-Instat and I think we are close.
a) The 2: 3 is improved, but it is now 2 ,3, while all the others would be 2, 3.
b) The wrapping, etc now all seems to work.  Great!
c) I just note that when calculating divisors the one difference now between your display and the R viewer is that you give 0 for the divisors of 1, while the R viewer gives NA.  (You may give 0, but the length is 0, so it isn't a real 0!)
d) But there is still a problem.  The filter to give a subset seems to work, but the metadata is still odd, see below:
<img width="450" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/692ce81c-0040-47aa-9d1b-e7dcc5234873">

2023-08-08 14:56 UTC, rdstern commented
@N-thony the fixes mean that now it seems exactly the same as the R viewer for the list variables.  That's great.
Is this a suitable pull request to check on the display in Roman - which remains different from R viewer?
And the subset still has to sort out the metadata.
I am very pleased with the progress though.

2023-08-08 16:19 UTC, rdstern approved these changes
@N-thony that's great.  I think the problem with displaying lists and also getting a subset, seems to have been solved.
I also tried everything with a dataframe where I am keen on wordwrapping, namely the statquotes and there then wrapping and everything seem to work perfectly.

There is an interesting "feature" about the wordwrapping for a list column and also for (say) factorial, where there are very long numbers - and no spaces.  In each case the wordwrap with 20, 0r 40, etc, does not wrap.  It just makes the field very wide.  But I don't care, because the unwrap works fine.  This is good enough.

@lloyddewit as soon as you are happy with the code, then I would like to have this merged.  I will then also inform @rachelkg  because she is working on items that can continue to test that this is ok.

2023-08-09 13:02 UTC, lloyddewit approved these changes

2023-08-09 13:04 UTC, merged