Toolbar additions
africanmathsinitiative/R-Instat pull request #8484
Opened 2023-08-08 13:34 UTC by derekagorhom

Fixes #8444 

I have added `Show R commands` and `include comments` to the output tab.

@rdstern , @N-thony can you review this

Thanks

2023-08-08 15:52 UTC, rdstern reviewed
@derekagorhom well done, I like this.

a) The settings seem to link perfectly with the Tools menu. 
b) I occasionally switched off commands and it seemed to switch off comments too?  But I couldn't get that to repeat consistently?
c) The message in the output window seems odd.  I think it is the same as when you use the tools menu.  I wonder if, instead, it could simply state what the current setting now is, or what has been done?  For example:  `Comments from dialogs displayed in the output window.  
`or `Comments from dialogs not displayed`
Similarly `R commands displayed in the output window`
or `R commands not displayed. (They continue to be copied into the log window.)`

Please @Patowhiz could you also check.  This is not quite what you requested, which was simply to open the Tools > Options dialog at the right place.  However, I find this to be simpler and nicely synchronised?

2023-08-08 19:24 UTC, Patowhiz commented on instat/dlgOptions.vb
>      End Sub
Can line 362 and 363 be moved to below line 843 of `frmMain`. All we need is to change the checked status after `dlgOptions` has been closed.

2023-08-08 19:26 UTC, Patowhiz commented on instat/frmMain.vb
> +        Me.clsInstatOptions.ExecuteRGlobalOptions()
I don't think we need to have line 657. I think the `dlgOptions` dialog always reads from `clsInstatOptions` object when it's launched.
The same applies to line 650.

2023-08-08 19:33 UTC, Patowhiz commented
@rdstern I agree it's not what I proposed. But if you are happy with having this feature done in this way, I have no strong objection.

@derekagorhom changing of the comments can be done at the `clsInstatOptions` level. I recommend doing it at that level to maintain the single responsibility principle.

2023-08-11 17:05 UTC, rdstern submitted a review, later dismissed
@derekagorhom I am now happy this.  Many thanks.
@lloyddewit over to you

2023-08-14 08:01 UTC, lloyddewit requested changes
@derekagorhom Thanks, looks good, just a few questions

2023-08-14 08:01 UTC, lloyddewit commented on instat/clsInstatOptions.vb
> +        strRComments = GetROption("Comments.from.dialogs.displayed.in.the.output.window")
needed?
```suggestion
```

2023-08-14 08:01 UTC, lloyddewit commented on instat/clsInstatOptions.vb
> +        Dim strRComments As String
Do these variable have any purpose? delete?
```suggestion
```

2023-08-14 09:27 UTC, derekagorhom commented
@lloyddewit , i have made the changes can you review them
thanks

2023-08-14 09:32 UTC, lloyddewit approved these changes

2023-08-14 09:34 UTC, lloyddewit commented
@rdstern Since your last review, the code has changed a little. In theory the functionality should be unchanged but it would be good to do a sanity check. If you can test/approve, then we can merge.
Thanks

2023-08-14 09:48 UTC, rdstern approved these changes
@lloyddewit and @derekagorhom looks fine.  I like it!

2023-08-14 10:05 UTC, merged

2023-08-23 18:24 UTC, Patowhiz commented
Hello @derekagorhom,

I appreciate the progress you've made in this pull request. The inclusion of shortcuts is undoubtedly a significant enhancement that will greatly enhance usability.

To @lloyddewit and @rdstern, I noticed an anomaly in the output window upon launching the application. It think some of the code modifications introduced in this PR may have contributed to this issue.

I'd like to highlight that the display of comments and commands within R-Instat is not intrinsically an R based feature, as indicated by the introduction of parameters to the options R command at lines 320 and 327. Rather, this implementation operates at the front-end level (VB.Net). The options R command typically does not accommodate such parameters. This discrepancy could potentially appear odd to R users.

@derekagorhom, I understand your intention to address @rdstern's suggestion, which pertains to including a comment in the output window indicating the status of comments and commands being turned on or off. @rdstern, please feel free to provide clarification if my interpretation deviates from your original intent.

@rdstern if you agree with my assessment of your suggestion, I would recommend rectifying this matter by either amending the implementation to align with the intended behavior or considering the removal of those parameters from the R command. 

@derekagorhom if you agree with my code assessment I've highlighted the specific lines that require modification in the attached code screenshot. 

Kindly note, this discrepancy is not a critical issue warranting immediate attention. I acknowledge any delay in my review and apologize for it.

Thank you for your valuable contributions.

Output window screenshot.
![delete](https://github.com/africanmathsinitiative/R-Instat/assets/21179007/a235c43e-41d1-47de-aaca-e8f1b9b78332)

Code screenshot
![delete2](https://github.com/africanmathsinitiative/R-Instat/assets/21179007/9adcc47e-6811-4a5a-8c89-8648b3bf3776)

2023-08-30 06:57 UTC, lloyddewit commented
@Patowhiz thank you for the comment. If we leave the comment in a merged PR, then there's a risk it will be forgotten. I moved your comment to issue #8517.