Added Discrete Scale to Plot Sub-Dialog
africanmathsinitiative/R-Instat pull request #8503
Opened 2023-08-21 13:08 UTC by Vitalis95

Replaces PR #8395 
Fixes #1789 
@rdstern , @N-thony , @lloyddewit ,the scale is now implemented  only in `Line Plot dialog` , once the PR for Esther on `Bar graphs` is merged then I will implement there. Once it is working well and the code is fine, then we can replicate it in all the graph dialogs

2023-08-22 06:29 UTC, rdstern requested changes
@Vitalis95 I tried with a simple example of 3 climatic stations and months as the starting point.

<img width="397" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/a45d7fd2-9b65-4453-a909-7802e83f7ce7">

a) It defaul;ts to the x-axis as continuous.  I thought it might notice that the x-axis was a factor and hence discrete?  I thought that's partly why you need some code in the line-plot dialog?  But I am happy to have to move to discrete myself, if that is not the case.
b) Then I used the option 3 to 9 in the limits on the left and that seems to work.  Good.
c) But it keeps coming back to Continuous when I return to the sub-dialog.  It should remember Discrete from the last time.
d) Then I tried Limits on the right, where I assume it must be given as `Mar, Sep`.  Nothing happened.  I can't get anything to happen with the 3 (temporary) controls on the right.  I thought this stop-gap was there to work quickly.  But nothing works there I think.
e) I had closed the limits on the left, but they suddenly returned.  There is something you can't be clearing in the code there.
f) Is there anytrhing else I should be checking?

Please continue, and keep asking @N-thony.  There still seems such a long way to go!

2023-08-24 12:21 UTC, lloyddewit commented
> @lloyddewit this is a really important change. It will affect many dialogs, and I wonder whether the code could usefully be examined now, when what is done so far seems to be working ok?

This is a large change but I think I already reviewed a lot of the code in PR #8395. I think it's best if I review when the code is stable an you have approved, otherwise there's a risk I'll miss something.

2023-09-04 14:03 UTC, Vitalis95 commented
@rdstern , have a look it , line graphs and general graphics dialogs. I will be making small change of just adding the discrete function in other graphs dialog where discrete applies

2023-09-05 05:54 UTC, rdstern requested changes
@Vitalis95 there are 3 types of point here:
a) Great that you have added the other discrete options.  Could you please be exact on the spacing and position of the new checkbox.  Also you have included the secondary axis.  I don't think that applies to the discrete option.  (Perhaps I am wrong, but if you thought I had suggested it, then please remove it.)
b) It does seem to work from the general dialog, but only once, because the sub-dialog doesn't keep any memory of having used those options.  So it returns immedaitely to the defaults.
c) I thought that discussions with @Patowhiz had confirmed that nothing was needed on each main dialog.  Did I get that impression wrongly?

2023-09-05 10:41 UTC, Vitalis95 commented on instat/ucrAxes.vb
> -        clsXYScaleContinuousFunction = clsNewXYScaleContinuousFunction
it was moved up

2023-09-05 10:47 UTC, Vitalis95 commented
@Patowhiz , are we suppose to add the discrete function in the main graphs dialog, in the sdgplots sub , like the way they  have added for continuous scale function and date function?

2023-09-05 11:36 UTC, rdstern reviewed
@Vitalis95 I am now ready to see this merged, as soon as it is available for more of the graphics dialogs.
@Patowhiz and @N-thony I didn't realise there is already a function in each main graph dialog for continuous and date?  If so, the clearly it could usefully be amended for discrete.  I am still unclear whether it is a different function in each main graph dialog, or a single function to adapt that is called by each main graph dialog?

2023-09-05 12:51 UTC, Patowhiz commented
@Vitalis95 I think we discussed about this feature in skype. I'm happy to expound on it in an online discussion. 

I noticed there are features that were added in main dialogs for this subdialog in a way that introduced more unnecessary parameters when setting up the subdialog. I think we should be keen on avoiding that trend.

Thanks.

2023-09-07 11:36 UTC, rdstern reviewed
@Vitalis95 and @N-thony well done both of you.  I tried with the bar charts and that seems to work, also with the scatterplots.  This is on the home run now.

Could you just check the Mosaic plot code, see below:

<img width="926" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/571ba4b5-be62-4dcc-ab46-011afa67ded1">

This is a good candidate, to label better but when I try it says the x-scale is continuous - which it isn't!

2023-09-08 08:13 UTC, Vitalis95 commented
@N-thony , the get  parameter value from clsRaesFunction works when the main dialog has a single receiver, for multiple receivers like for dlgMossaic plot  raised above or when you switch the receiver in dlgBargraph to multiple receiver, it  doesn't get x variables

2023-09-08 08:41 UTC, rdstern commented
@Vitalis95 that's a good bit of detective work.  I hope it is therefore an easy fix for @N-thony

2023-09-14 09:35 UTC, Vitalis95 commented
> > @N-thony , the get parameter value from clsRaesFunction works when the main dialog has a single receiver, for multiple receivers like for dlgMossaic plot raised above or when you switch the receiver in dlgBargraph to multiple receiver, it doesn't get x variables
> 
> @Vitalis95 what do you think? Have you tried to run on Script window or check the documentation if it is possible when `x` has more than one variable?

@lilyclements is looking on the R-code for this.

2023-09-14 10:34 UTC, rdstern commented
@Vitalis95 I just wondered if it was ready now, though perhaps you are still waiting for @lilyclements?  However, it has conflicts now, so doesn't build.

2023-09-14 11:31 UTC, lilyclements commented
@Vitalis95 I've sent you the code for this now :)

2023-09-18 09:48 UTC, Vitalis95 commented
@lilyclements , I get a bug when I run the code on  dlg mosaic plot, check your mattermost I have sent the code there.

2023-09-22 08:08 UTC, lilyclements commented
@Vitalis95 great observation - very indepth to be looking at how this affects other dialogs too. From a little google, it seems [this is a known bug in `ggmosaic`](https://github.com/haleyjeppson/ggmosaic/issues/58).
We should keep an eye on it, but, perhaps for now is it possible to disable that tab if you access the sub dialog from a mosaic plot? If not, then I'm sure we can catch it in another way.

2023-09-22 15:34 UTC, rdstern commented
@Vitalis95 I now get conflicts so can't check this pull request any more.  If you can resolve them, then I'd also like to test the pull request even before you do anything more.  From @lilyclements if this is a sort of bug in the mosaicplot package, then, for now, I would accept an error when using it in R-Instat.  The mosaic plot is not important enough to prevent adding this important new facility.  And we need to get on, with important new changes.

2023-09-22 18:19 UTC, lilyclements commented
@rdstern yes this is the case. In which instance, @Vitalis95 no need to worry about the mosaic bug.

2023-09-22 18:20 UTC, lilyclements commented
@rdstern @Vitalis95 the conflict should now be fixed

2023-09-22 19:09 UTC, rdstern commented
@lilyclements I still get build errors.  I have updated the master to the latest version and am not clear what else I should do?

2023-09-25 09:18 UTC, Vitalis95 commented
@rdstern @N-thony , the merge conflicts is because of Derrick's  PR #8455 , we also made a change on dlg bar graph. Once this is merged I will make another PR.

2023-09-26 09:23 UTC, Vitalis95 commented
merge conflicts

2023-09-26 09:23 UTC, closed without merging