Ensured that rows can be changed and comments added in the Climatic > Examine/Edit > Data entry Dialog
africanmathsinitiative/R-Instat pull request #8512
Opened 2023-08-28 07:57 UTC by N-thony

Fixes partially #8281
@Fidel365 @rdstern this partially fixes the bug reported in the corresponding issue when the comment is added or a row values has changed. Have a look.

2023-08-28 21:29 UTC, rdstern requested changes
@N-thony that's excellent, I think one of the problems is fixed.  It now doesn't make that funny extra column.  
However, one critical problem still remains.  And I think I have found it.  I am not sure of the solution though.

After I make the change, I made it to Xai-Xai, and just added a comment.
Then I returned to the dialog.
In the returned dialog I now change the Station name.
Now I find that Ok is enabled - though I have not changed any data.  So it should not be.

I pressed To Script to see what it has produced:

```
# Dialog: Daily Data Editing/Entry

new_data <- data.frame(Station_Name="CHIMOIO")
data_book$save_data_entry_data(data_name="Mozambique_3_stations", new_data=new_data, rows_changed="22951", comments_list=list())
rm(new_data)

```
It has most of this code from last time, when I just changed a comment.  BUT it has a new station, i.e. the one I have now selected.  

I closed the dialog and checked the 3 stations - the 3 factors are fine.

Now I ran the script - so like pressing Ok.  Then I checked the stations again and found one row less in Xai-Xai has changed and become Chimoyo!

(When I hit the problem, as I was working before, I had changed a whole month, and it had changed a month from one station into the other.

I checked back in the dialog and when I change the variables to view it also enables Ok.  So that is currently another risky thing to do.  

I don't actually mind Ok being enabled, when there is nothing to change, as long as it then doesn't change anything!  But I suggest it would be simpler to only enable Ok, when there is at least a comment to change, or data to change, or both.

Here are the data I have been using.

[Mozambique_3_stations_shifted_summaries.zip](https://github.com/africanmathsinitiative/R-Instat/files/12458358/Mozambique_3_stations_shifted_summaries.zip)

2023-08-29 08:19 UTC, rdstern approved these changes
Yippee!  At last this now seems fixed.  Many thanks @N-thony.  @lloyddewit please check and merge as soon as you can.  This is useful for the forthcoming Zambia workshop.

2023-08-29 08:52 UTC, lloyddewit requested changes
@N-thony thanks look good, just one small formatting suggestion

2023-08-29 08:52 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +  if (ncol(new_data) > 1) {
indent lines 4319 to 4345?

2023-08-29 09:18 UTC, rdstern submitted a review, later dismissed
Still looks fine to me

2023-08-29 10:03 UTC, lloyddewit requested changes

2023-08-29 10:03 UTC, lloyddewit commented on instat/static/InstatObject/R/data_object_R6.R
> +   }
```suggestion
  }
```

2023-08-29 10:03 UTC, lloyddewit approved these changes

2023-08-29 10:05 UTC, merged