Added Jitter Check Box on ScatterPlot Dialog.
africanmathsinitiative/R-Instat pull request #8526
Opened 2023-09-05 12:56 UTC by MeSophie

Fixes #8524
@rdstern, @N-thony I Added Jitter check box on ScatterPlot Dialog. Please have a look.

2023-09-05 13:38 UTC, rdstern submitted a review, later dismissed
@MeSophie that looks great.  @lloyddewit over to you.

2023-09-06 08:02 UTC, lloyddewit requested changes
@MeSophie Looks, good, just a couple of very small suggestions

2023-09-06 08:02 UTC, lloyddewit commented on instat/dlgScatterPlot.vb
> +        ucrNudWidth.Minimum = 0.00
```suggestion
        ucrNudHeigth.Minimum = 0
        ucrNudHeigth.Increment = 0.01
        ucrNudHeigth.DecimalPlaces = 2

        ucrNudWidth.SetParameter(New RParameter("width", 6))
        ucrNudWidth.Maximum = 0.5
        ucrNudWidth.Minimum = 0
```

2023-09-06 13:10 UTC, rdstern approved these changes
@lloyddewit this still looks fine to me

2023-09-08 09:25 UTC, lloyddewit approved these changes

2023-09-08 09:26 UTC, merged