Ensured the Identify Key checkbox worked correctly in dlgRownamesOrNumbers
africanmathsinitiative/R-Instat pull request #8529
Opened 2023-09-07 07:23 UTC by derekagorhom

fixes #8510
The changes are; 

a) Delete the second set of lines. 
b) To permit the key variable checkbox to be unchecked while still being checked by default.

@N-thony , @rdstern this PR is ready for review

Thank

2023-09-07 09:15 UTC, rdstern requested changes
@derekagorhom that new first line generates an error.  The one:
`all(sapply(rownames(survey), is.numeric))`
I don't think it is needed, so you can delete it.
I am a bit confused how you managed to test it without finding that error yourself.

Originally I think the extra code was introduced because often the row names are just numeric, and the code finishes with them as character.  I am now prepared to live with that, at least for now!

2023-09-07 13:28 UTC, derekagorhom commented
@rdstern apologies, I think i read the issue wrongly. I have made the changes your requested. but you second paragraph is a bit confusing, Please did you want the dialog to have the original four lines again?

2023-09-12 13:52 UTC, rdstern approved these changes
@derekagorhom that now looks fine - thanks.  @lloyddewit for the last week I am afraid (at least for now) - over to you!

2023-09-14 07:22 UTC, lloyddewit approved these changes

2023-09-14 07:27 UTC, merged