Added Discrete Scale to Plot Sub-Dialog
africanmathsinitiative/R-Instat pull request #8553
Opened 2023-09-26 09:31 UTC by Vitalis95

Fixes #1789 
Replaces PR #8503 
@rdstern @N-thony , this is the new pull request

2023-09-26 14:26 UTC, rdstern submitted a review, later dismissed
@vitalis, great.  Really important addition

2023-09-28 16:16 UTC, rdstern commented
@N-thony I am not sure if this is a pull request that you feel you should be checking the code and merging?  Or - as it is used in many dialogs - and you were involved in the development, perhaps it should be for @Patowhiz?.  I would like it to be merged as soon as possible as it is such a useful update.

2023-10-05 08:35 UTC, Vitalis95 commented
@Patowhiz , can you have a look this. Thanks

2023-10-16 17:33 UTC, rdstern requested changes
@Vitalis95 I had the following problem from the general graphics dialog:
<img width="677" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/5b121706-52cf-4158-9212-896c4db255fb">

Here was the dialog, with the diamonds data:

<img width="350" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/e42fa564-3424-414f-b91b-b37754d89482">

2023-10-17 07:43 UTC, Vitalis95 commented
@rdstern , have a look at it

2023-10-17 16:08 UTC, rdstern requested changes
@Vitalis95 that's a relief.  It now seems to work ok
The only problem so far is that the limits forgets the settings if you click on any of the sub-dialog options again.
I used diamonds and a jutter plot on the graph general, with x and y both factors.  If I set one say x limit from 2 to 4, it works fine.  I can run it again, no problem.  But if I now go into the Y-axis and set that from 3 to 5 it works, but the x-axis is unset.

It unsets even if I go elsewhere - say to Theme and have no legend.

I haven't checked if that is general with other options.  Hope you can fix it.  I would really like to get this merged.

2023-10-18 09:40 UTC, Vitalis95 commented
@rdstern , have a look at it.  the issue was on the new tabs added to general graphics dialog it was forgetting

2023-10-18 10:44 UTC, rdstern approved these changes
@Vitalisgreat, I am approving.  @N-thony will you check and merge, or is this @Patowhiz?  I'd reaslly like to get this merged as soon as possible

2023-10-25 09:59 UTC, Vitalis95 commented
@Patowhiz , can you review? @MeSophie is waiting for this PR to be matched so that she can make more improvements on the sub dialog

2023-10-26 15:32 UTC, Patowhiz requested changes
@Vitalis95 thanks for this, just a few questions, comments and suggestions.
Would be good to work on this so that @MeSophie can push her changes.

2023-10-26 15:32 UTC, Patowhiz commented on instat/ucrAxes.vb
>          If strAxisType.ToLower = "continuous" Then
Use the VB.net `Select...Case` statement to check `strAxisType`? It will omit the need to call `strAxisType.ToLower` in the different checks and enforce consistency in future implementation.

2023-10-26 15:32 UTC, Patowhiz commented on instat/ucrAxes.vb
> +        End If
```suggestion
 If strAxisType = "discrete" AndAlso ucrChkExpandDiscrete.Checked AndAlso Not ucrInputExpandDiscrete.IsEmpty Then
            clsXYScaleDiscreteFunction.AddParameter("expand", clsRFunctionParameter:=ucrInputExpandDiscrete.clsRList)
       Else
            clsXYScaleDiscreteFunction.RemoveParameterByName("expand")
  End If
```

2023-10-26 15:32 UTC, Patowhiz commented on instat/ucrAxes.vb
> +        If ucrChkLimitsFrom.Checked AndAlso Not (ucrNudFrom.IsEmpty AndAlso ucrNudTo.IsEmpty) Then
@Vitalis95 is the intention of this line 922 similar to what I have below? 
`If ucrChkLimitsFrom.Checked AndAlso Not ucrNudFrom.IsEmpty AndAlso Not  ucrNudTo.IsEmpty Then`

Are both from and to controls required to not be empty or just one of them?

2023-10-26 15:32 UTC, Patowhiz commented on instat/ucrAxes.vb
> +    Public Sub SetRCodeForControl(bIsXAxis As Boolean, Optional strNewAxisType As String = "continuous", Optional clsNewXYScaleContinuousFunction As RFunction = Nothing, Optional clsNewXYScaleDiscret
@Vitalis95 if it won't take much of your time, kindly write a comment of how this subroutine operates. I've noticed subtle differences from how this has been implemented in other custom controls.

2023-10-26 15:32 UTC, Patowhiz commented on instat/ucrAxes.vb
> +        If bReset Then
@Vitalis95 why is `bReset = True`  check necessary? Does the setting of R code behave unexpectedly when it's `bReset` is false?

2023-10-27 09:12 UTC, Vitalis95 commented on instat/ucrAxes.vb
> +        If bReset Then
@Patowhiz , when `False`, the controls forgets the settings when you go back to the sub dialog

2023-10-27 09:16 UTC, Vitalis95 commented on instat/ucrAxes.vb
> +    Public Sub SetRCodeForControl(bIsXAxis As Boolean, Optional strNewAxisType As String = "continuous", Optional clsNewXYScaleContinuousFunction As RFunction = Nothing, Optional clsNewXYScaleDiscret
@Patowhiz , I am investigating to know why it was implemented this way here, I will write a comment once I understand

2023-10-27 09:17 UTC, Vitalis95 commented
@Patowhiz  over to you

2023-10-28 11:08 UTC, Patowhiz approved these changes
@Vitalis95 thanks for addressing my comments.
@rdstern I've approved the code, if you could test and approve the new changes then we can merge.

2023-10-30 19:17 UTC, rdstern approved these changes
great

2023-10-31 06:25 UTC, merged