Made Column metadata consistent with Data View when selection is applied
africanmathsinitiative/R-Instat pull request #8561
Opened 2023-10-03 07:43 UTC by N-thony

@rdstern I'm not sure about the issue number this PR fixes, but I made the change as discussed on Skype so that the Metadata grid will reflect on the Data View when the selection is applied. Have a look.
![image](https://github.com/africanmathsinitiative/R-Instat/assets/68591383/3277807d-5816-4754-bc1e-9d71a1f8bb21)

2023-10-03 12:14 UTC, rdstern requested changes
@N-thony nice but needs a tweak,  I think it is just doing the first 3 columns, see below:

<img width="417" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/081080d0-b3aa-42a1-b160-83496bf8d3aa">

Good to check with wide data, when we may choose to not show the column metadata.

It is what I have wanted for a long time.  But before we merge I would like to check whether we could also have options on where to apply.

2023-10-03 15:20 UTC, rdstern reviewed
@N-thony this is great - it now seems to work.  Here it is even for the extremes data:

<img width="353" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/ca35cb20-660f-4c59-9597-e6e41c4ef215">

I checked with @lilyclements though who is also excited by the option of being able to apply the select (or not) to these 3 alternatives (dataframe, metadata, dialog).  So I hope that isn't too  demanding a task.  

I had not expected this for the November upgrade even, so am really delighted!

2023-10-26 11:07 UTC, rdstern approved these changes
@N-thony agreed.  @Patowhiz over to you to check and merge

2023-11-01 08:33 UTC, rdstern commented
@N-thony I thought it is unlikely to do any harm and you suggested including it for now and then adding flexibility in where the select is applied later.  So, I'd be happy to have it in the version this week.

If it needs a check by @lilyclements first, then let's wait to see if she has the time this week.  Otherwise it could wait till the December version.

2023-11-01 09:15 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +      col <- curr_data[[c]]
@N-thony out of interest, why did you remove `seq_along`?
It means our `out` is now named not numbered. Does this affect code elsewhere or is this ok?

2023-11-01 09:20 UTC, lilyclements reviewed
@N-thony just a couple of comments where I wanted to double check some code changes you've made. Apologies for double checking on them, I don't know this code as well as I'd like to so wanted to run by a couple of changes you made.

2023-11-01 09:20 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +      col <- curr_data[[c]]
@N-thony out of interest, why did you remove `seq_along`?
It means our `out` is now named not numbered. Does this affect code elsewhere or is this ok?

2023-11-01 09:20 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +      if(self$column_selection_applied()) cols <- self$current_column_selection
From what I can tell, `column_selection_applied()` is either `FALSE` or `!curr_sel[["is_everything"]]`.
Have I misunderstood this? I'm sure you've checked this, but I just wanted to confirm is `!curr_sel[["is_everything"]]` logical (i.e., `TRUE`/`FALSE`)?

2023-11-01 09:32 UTC, lilyclements commented on instat/static/InstatObject/R/data_object_R6.R
> +      if(self$column_selection_applied()) cols <- self$current_column_selection
Ok great. So, `column_selection_applied()` gives a logical output then? If so, this looks good! :)

2023-11-01 09:51 UTC, lilyclements approved these changes

2023-11-01 10:21 UTC, rdstern reviewed
@N-thony and @lilyclements it started ok, but then I got awkward and found this when I was trying to remove the selection:

<img width="411" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/08926961-370b-4385-9e17-7fbce39607e2">

I was a bit extreme, I know!  I made the selection and then did a summarise one variable and it worked fine.  Then I renamed variety to variety2 and noticed it is still there as variety in the selection.  

It is now a bit worse.  When I got rid of the error message, it took revenge and got rid of the data frame!

2023-11-01 10:30 UTC, rdstern approved these changes

2023-11-01 10:33 UTC, merged