Fixed small bug in Column summaries sub-dialog
africanmathsinitiative/R-Instat pull request #8591
Opened 2023-10-23 10:50 UTC by derekagorhom

Fixes #8588 
I have fixed the problem with the receiver not appearing when the sub-dialog is used for the first time 
@N-thony , @rdstern can you review this
Thanks

2023-10-24 18:59 UTC, rdstern commented
@derekagorhom I tried and it still seems the same:

<img width="625" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/a0de6d14-0ca3-4e33-9923-4ae43cd39a0b">

Note I import the data, use the summaries as shown, then first the summaries button, and then the probability one.

2023-10-25 12:27 UTC, Patowhiz requested changes
@derekagorhom I have suggested a comment addition. Check if you agree then we can merge this.

2023-10-25 12:27 UTC, Patowhiz commented on instat/sdgProportionsPercentages.vb
> +    End Sub
```suggestion
    Private Sub ucrChkProportionsPercentages_ControlContentsChanged(ucrChangedControl As ucrCore) Handles ucrChkProportionsPercentages.ControlContentsChanged
        'temporarily fixes issue #8588
        If ucrChkProportionsPercentages.Checked Then
            rdoByFactors.Checked = True
        End If
    End Sub

```

2023-10-25 12:45 UTC, rdstern submitted a review, later dismissed
@Patowhiz I tried again and am happy to approve again.  I didn't do anything that provioked the comment though.
You also asked on the same dialog about the `j 1   Help` which does look a bit odd.  It is 2 separate controls.  Ideally the Help button would say R Help.  There is a comment to say why we have j as 1 in the other control.  It is all to do with the md measure.

2023-10-25 13:46 UTC, Patowhiz approved these changes

2023-10-25 13:47 UTC, derekagorhom commented
@Patowhiz should i look into the bug you found in another pull request?

2023-10-25 13:49 UTC, Patowhiz commented
@derekagorhom thanks the changes made here are enough. Once @rdstern clicks on approve, I will merge.

2023-10-25 14:14 UTC, rdstern approved these changes

2023-10-26 06:22 UTC, merged