Insert script and renaming tab in script window
africanmathsinitiative/R-Instat pull request #8597
Opened 2023-10-25 07:35 UTC by N-thony

Fixes partially #8487
Fixes partially #8151
Fixes #8570

@rdstern @Patowhiz this PR replaces PR #8544 due to conflicts, have a look. There is still a lot of work going on the script window, it will be good to get this merge quickly.

2023-10-25 07:50 UTC, Patowhiz commented
@rdstern could you test this and approve while I'm reviewing?

2023-10-25 08:49 UTC, Patowhiz commented
@rdstern we have looked into multiple issues with @N-thony in regards to this PR.

The final option is the one we couldn't agree on what you wanted. My understanding is, it's meant to produce the `rm()` function for removing objects from R global "memory".

Also I conspicuously noticed the **ToScript** button having the same functionality to **Ok** button. Any reason as to why we can't hide one of them to emphasize that the dialog is unique and simply inserts scripts to the script window?

Once @N-thony fixes the issues that we have discussed I can review.

2023-10-25 09:22 UTC, rdstern reviewed
@N-thony this is looking really excellent.  @Patowhiz I note first what seems to me to be working well.
a) It fixes the issue that when you first click to open the script window it opened into the log window.
b) You can double-click on a tab and add a name.  It then suggests that name if you click save.
c) The big thing is that there is a new Insert button.  I have checked the first 2 elements of this, namely you can insert a library line.  And you can insert the line to add the data into an R-Instat data frame.  
d) We need to be able to do more, like getting data into a script and copying a graph, etc.  I have yet to check those - and they may become a new issue.  And they may need @Patowhiz 
e) The new big one is the copying of scripts from packages.  I am very happy to see this.  There is a bug, to be fixed that @N-thony is aware of.  Then it will be great to add.

2023-10-25 09:53 UTC, rdstern commented
@Patowhiz I know that the ToScript and Ok do the same in this dialog.  I am quite happy to still allow both for consistency with the other dialogs.  But I don't feel strongly about it.  If you disable one of them, will you keep the ToScript, or the Ok?  So I'm happy for you and Antoine to decide and implement whatever you agree on.

I am disappointed to lose e) because it is such a big deal.  And it seems to work for most scripts/packages.  But if you feel it will take time to sort out properly, then let's make it another PR.  I hope it will be in time for this new version though.

2023-10-25 15:06 UTC, rdstern requested changes
@N-thony it looks great.
Except it is only showing data examples.  It should also allow examples from any function.  For example agricolae package has many functions, like AMMI and they also have an examples section.

And there are some packages that have useful examples, and don't have any data sets.  For example checkmate has many functions, some with examples, but no data files.

2023-10-25 17:56 UTC, rdstern commented
@N-thony I had not thought you would try that way?  I would like you to list the functions, just as you list the datasets.  Then we choose and you look for the Examples bit.
I would be very happy if there could be the two separate lists, but you could just list everything in a single list - as ythere is when you just choose the package in the Help dialog.

2023-10-26 11:29 UTC, rdstern approved these changes
@N-thony that's fine - we don't need the description for the functions.

When I upload an example it currently gives me some extra lines, see below.  So it is starting somewhere earleir than the Examples.  This isn't a problem (because they have hashes in front.) but a bit of a surprise.

I am approving anyway,  I am happy with what we have now, and would really like this to be merged.  @Patowhiz over to you.

<img width="506" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/910fa629-e1c9-46da-9daa-f440ed02da07">

2023-11-03 10:31 UTC, ChrisMarsh82 approved these changes

2023-11-03 10:35 UTC, closed without merging

2023-11-07 04:47 UTC, Patowhiz reviewed
@N-thony, I recognize that this PR received expedited approval from @rdstern and was  merged by @ChrisMarsh82.

After discussions with @rdstern, I've undertaken an effort to modify and enhance the changes introduced here, in PR #8629.

In my review comments, I've posed a few questions to you. Your feedback will play a crucial role in enabling me to implement the "get examples" feature in PR #8629. 

Thanks.

2023-11-07 04:47 UTC, Patowhiz commented on instat/dlgScript.vb
> +                    Dim strResult = RemoveDoubleHashD(strExampe)
Why do we need to remove double hashed D, that is, **##D**?

2023-11-07 04:47 UTC, Patowhiz commented on instat/dlgScript.vb
> +                clsLibraryExpFunction.RemoveParameterByName("package")
Why do we need to remove the package parameter when the selected package is not **datasets**?

2023-11-07 05:33 UTC, Patowhiz commented on instat/dlgScript.vb
> +            If Not String.IsNullOrEmpty(strTopic) Then
Do we have a possibility of a null or empty topic? Any example?

2023-11-07 05:34 UTC, Patowhiz commented on instat/dlgScript.vb
> +                If clsLibraryExpFunction IsNot Nothing Then
When could `clsLibraryExpFunction ` be null?

2023-11-07 05:50 UTC, rdstern commented
@Patowhiz  I am contributing here, just to emphasise that I see this work by @N-thony and you to be a really important feaure in R-Instat, and so much the better if these questions result in you two working more closely together on the code generally. 
I'm not a programmer, but I view these questions as implying the importantance of including good explanatory comments in the code.  They explain why the code is there, and the code itself is just the "what".

That's the parallel of our underused comment feature in every dialog in R-Instat.  Anyway my purpose in this message is to suggest that Antoine could reply, where possible, by adding the relevant comments into the #8629?  @Patowhiz is this sensible?

2023-11-07 06:56 UTC, Patowhiz commented
Thanks for your input @rdstern. I agree that the collaboration between @N-thony, the broader team and myself is significant for enhancing R-Instat. Your perspective on the importance of explanatory comments in the code is spot on. Comments are indeed invaluable in helping developers understand the "why" behind the code, which is just as crucial as the "what." My hope is the broader team will take this into account as we continue our work on R-Instat.

2023-11-07 10:09 UTC, Patowhiz commented
@N-thony, I wasn't initially aware that this PR had been superseded by PR #8619. Nevertheless, I'd like to emphasize that my comments from this PR are still applicable and relevant to PR #8619.

2023-11-10 20:00 UTC, Patowhiz commented on instat/dlgScript.vb
> +                    Dim strResult = RemoveDoubleHashD(strExampe)
I've been answered by @rdstern [comment](https://github.com/africanmathsinitiative/R-Instat/pull/8629#issuecomment-1806332036) in PR #8629.