Improved column selection to apply or not to dataframe, metadata or dialogue
africanmathsinitiative/R-Instat pull request #8648
Opened 2023-11-13 05:49 UTC by N-thony

Fixes #8600 
Fixes #8650
@rdstern have a look.
The dialogue checkbox is disabled and I was thinking that it will be good if the selection is applied to a specific dialogue?

2023-11-15 16:24 UTC, rdstern reviewed
@N-thony here is the current dialog:
<img width="317" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/5f168cb7-6d59-44c8-8801-bc0627206c5b">

I suggest 3 radio buttons (rather than 2) on the left.

O Select
O Subset
O Save Select

Select is the default and is the only one that shows the right-hand group.  Theat has 3 checkboxes.  Perhaps a label Apply To:
Then Data, Metadata, Dialogs.

All are checked by default.  

Roger.

2023-11-16 08:22 UTC, rdstern reviewed
@N-thony this is starting to look very good.
a) I was able to save 2 selects and then use them later.  This seems to work fine.
b) But when I asked for it to apply to just the data (not to the metadata) it still applied to the metadata.
c) When I applied to the metadata and not to the data, I got a formatting curiosity, see below, for the many decimals in the size column.  When I remove the selection the display is back to normal.

<img width="469" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/c7ecd383-77e6-4e67-9987-70d2271ed192">

d) And a new request.  I hope it is easy, so you can do it here.  Otherwise can you make a new issue.  When I make a filter, I can see the function on the main dialog.  That's very useful.  Could you add that feature for the selects?

e) I note that the select is currently always applied to the dialogs.  That option is greyed out.  I suggest that's fine for now, but could you tick it, so it is clear it will be applied to the dialogs.  And I can't apply it to just the dialogs?  Is that option difficult to add, see below:  If so, then stick with what we have now.  I am really happy that you can define selects ready for later use.

<img width="320" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/66c58ee7-a29f-4261-b594-68e8b3da5dff">

2023-11-16 17:11 UTC, rdstern requested changes
@N-thony I'm not sure about this, but happy if you want to continue, then fine. I used the usual survey dataset:
However The only cases I would really like are:
a) To be able to save the select and apply later.  That's working.
b) To be able to not apply in the metadata - which we used to have.  So apply always in the data and the dialogs, and just have a checkbox whether you apply to the metadata.  Currently that seems not to be working, i.e. it always now applies in the metadata.  When not applied (as before) the red would indicate which were in the select.

I would be happy if you continue to offer the other options, but there seems an error with each.
c) When not applied to the data, the formatting of at least one column in the data is odd.
d) When not applied in the dialog it gives an error if you choose to use a variable that is not in the select.

2023-11-21 16:47 UTC, rdstern commented
@N-thony my first try was a selection now applying to the metadata.
a) Previously I thought it was able to mark them red, though you saw all of them.  Would that still be possible?
b) However then I did a one variable summary, and then the metadata columns were selected, i.e. only the selected variables were shown now.
c) I am still keen on being able to see the selection formula in the main dialog, just as you can in the filter.  Can you include that now, or would you prefer to add it to the issue?

2023-11-22 07:14 UTC, rdstern approved these changes
@N-thony my mistakes.  Thanks for the clarification.  It seems to work fine

2023-11-24 16:38 UTC, rdstern reviewed
I am just testing the variables that are lebelled here and used hh from MICS.  The idea seems ok.
But when I ask for labelled variables I get 257 and these are fully or partially labelled.  When I ask for just the partially labelled I get 279 variables!  There's something wrong here.  I should get less.
I checked also by adding the not.  There are just 50 not labelled and that is working.

So you may be close!

2023-11-25 08:25 UTC, rdstern commented
@N-thony that's close!  I get 72 partially labelled, but they seem to be (instead) the variables that are not labelled.  When I ask for labelled variables and add the Not I get 72 - so the same.

2023-11-28 23:40 UTC, rdstern submitted a review, later dismissed
@N-thony very well done.  @Patowhiz can you check and merge?

2023-11-29 09:36 UTC, Patowhiz reviewed
@N-thony thanks for this. Just a few comments and question.

I noticed that you have introduced checking of column selections in different areas in the front end. Not unless I have misunderstood, this seems to suggest that the feature will be managed at the front end. Is the column selection not supposed to be managed at the R level? I  expected individual controls to internally check with the R data book as to whether there is column selection or not or send commands with appropriate selection parameters.
In summary I expected any new column selection global functionalities to be managed at the R level not VB.Net. Then for components that wish to not use them, they simply call R functions with correct flag parameters or functions that ignore the selection internally.

2023-11-29 09:36 UTC, Patowhiz commented on instat/static/InstatObject/R/data_object_R6.R
>      }
@N-thony why do we need an extra `use_column_selection` parameter instead of using the global `column_selection_applied()` only function. Is there a scenario where we will have a column selection yet `column_selection_applied()` will return false?

2023-11-29 09:36 UTC, Patowhiz commented on instat/dlgSelect.vb
> +        ucrChkDataframe.SetText("DataFrame")
@N-thony did you intend to have this as "Data Frame" instead of "DataFrame" ? Same applies to "MetaData" instead of "Metadata".

2023-11-29 11:01 UTC, Patowhiz reviewed
@N-thony thanks for your response. Very useful. Just a few comments and suggestions then we can merged.

Could you add TODO comments in specific instances that you think could be improved in future in regards to managing the entire column selection at the R level. A reference to this PR in the specific instances will be helpful as well. I find this helpful when in future we gradually refactor code and delete bits that are no longer needed.

Thanks.

2023-11-29 17:23 UTC, rdstern approved these changes
@Patowhiz still seems fine to me!

2023-12-01 15:18 UTC, merged