Returning the focus to the original receiver
africanmathsinitiative/R-Instat pull request #8649
Opened 2023-11-13 05:51 UTC by N-thony

Fixes #8256
@rdstern I have tested this with some dialogues in the Describe menu, have a look

2023-11-15 15:06 UTC, rdstern reviewed
@N-thony it seems to work fine on some dialogs.  Others resturn and nothing is in turquoise.  Here is an example:

<img width="358" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/45c329a6-e92d-47c3-8657-7983d5fa1d5a">

The stem and leaf is another like that:

<img width="323" alt="image" src="https://github.com/africanmathsinitiative/R-Instat/assets/11226469/23d144c6-cd67-48f6-a9b1-fb23889e8294">

2023-11-15 15:50 UTC, rdstern approved these changes
Looks fine.  Perhaps @Patowhiz can confirm

2023-12-05 07:21 UTC, Patowhiz requested changes

2023-12-05 07:21 UTC, Patowhiz commented on instat/ucrSelector.vb
> +            Dim lstVisibleReceivers = lstOrderedReceivers.Where(Function(ctrl) ctrl.Visible).ToList()
@N-thony could you specify the type of `lstVisibleReceivers` explicitly. This has many merits relating to long term code maintenance.

2023-12-05 07:23 UTC, Patowhiz commented
@rdstern I hope you have tested this with dialogs that have multiple features. I'm particularly interested with dialogs that have **multiple features** yet use **different receivers**. The sequence of reload may cause regression in the changes introduced here.

2023-12-06 07:42 UTC, Patowhiz commented on instat/ucrSelector.vb
> +            Dim lstVisibleReceivers = lstOrderedReceivers.Where(Function(ctrl) ctrl.Visible).ToList()
@N-thony I understand what the predicate is doing in the where clause.
Could you then specify the type explicitly, for example `Dim lstVisibleReceivers As List(Of Control)`. I understand that VB.Net allows dynamic types, but to be consistent with the code base and also for self documenting code, I strongly recommend static typing in this case.

2023-12-07 07:48 UTC, rdstern submitted a review, later dismissed
@Patowhiz I have checked again.  I really like this improvement and did check with many dialogs.  I can't see any problems.  My nervousness is that you know of some problems and are really just trying to teach me the lesson that I'm not checking carefully enough?
If that's not the case, then please continue with your checks and then merge!

2023-12-07 11:05 UTC, rdstern approved these changes

2023-12-07 18:20 UTC, Patowhiz commented
@rdstern thanks for your response. I'm glad you were able to check again on the dialogs that I was concerned about. 
I'm still not sure whether this change may affect performance of dialog reloads or not when it comes to wide data sets. 
@N-thony thanks for the change, would be useful to test this with dialogs that have different receivers that are visible in different options/features when using wide data sets. Nevertheless, I'm merging this.
@rdstern keep testing this feature in other PR's as well, I'll do the same.

2023-12-07 18:20 UTC, Patowhiz approved these changes

2023-12-07 18:20 UTC, merged