Fixed Legend position option in the Line graph > slope option
africanmathsinitiative/R-Instat pull request #9202
Opened 2024-10-24 08:37 UTC by derekagorhom

Fixes #9196 
@rachelkg , @N-thony , @rdstern I have disabled the lower legend position checkbox when the user is in the Slope option of the line graph dialogue. I have added a drop down input position to the legend option at the top. 
Can you review this PR
Thanks

2024-10-24 09:22 UTC, rdstern commented
@derekagorhom I hope the solution is simpler, namely delete the top legend control.  

We added the lower control to many graph dialogs, and I assume we did not notice it has an inferior version there.  Can you try that anyway.

2024-10-24 14:01 UTC, derekagorhom commented
@rdstern I have made so that the lower legend option work for the slope option now and deleted the top option...can you have a look
Thanks

2024-10-24 15:52 UTC, rdstern requested changes
@derekagorhom can you also fix the single Legend control.  

By the way, the greenrice data is in the agritutorial package if you want to use the same data as in the issue. 
Start by making W and N into factors.  You could use the slope (as Rachel does) or start with the line plot - the graph is silly there, but that's not the point. 
Start with the dialog as so:

![image](https://github.com/user-attachments/assets/652dfc6d-030d-4bd5-a4e2-58c7b2074d8f)

Notice I haven't done anything to the legend, so it is unchecked.

Press Ok.  Then get the dialog back and the legend control is checked.  That shouldn't happen.  Note I checked with the latest version and the control is ok there.  So, this is an example where you have fixed one fault and now introduced a new problem in that dialog, that wasn't there before.  And this new problem affects all the 5 options at the top of the dialog.  Please fix, and maybe use this example of a "regression in the code" to check that you don't do this sort of thing too often.

2024-10-28 08:51 UTC, derekagorhom commented
> @derekagorhom can you also fix the single Legend control.
> 
> By the way, the greenrice data is in the agritutorial package if you want to use the same data as in the issue. Start by making W and N into factors. You could use the slope (as Rachel does) or start with the line plot - the graph is silly there, but that's not the point. Start with the dialog as so:
> 
> ![image](https://private-user-images.githubusercontent.com/11226469/379841998-652dfc6d-030d-4bd5-a4e2-58c7b2074d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDM2MDcsIm5iZiI6MTczMDEwMzMwNywicGF0aCI6Ii8xMTIyNjQ2OS8zNzk4NDE5OTgtNjUyZGZjNmQtMDMwZC00YmQ1LWE0ZTItNThjN2IyMDc0ZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA4MTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzY2ExYTQ4ZjQyYzhiODJiMzIyNDllNzk0Y2UwZGY0MTU3ZjI5ZWYxMGM0Y2JiYzBhMDJkY2RiYTczMDAwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dg3dfWtzz3evkU1LcBsxEGCaGiv26IQe41ckDOJ6418)
> 
> Notice I haven't done anything to the legend, so it is unchecked.
> 
> Press Ok. Then get the dialog back and the legend control is checked. That shouldn't happen. Note I checked with the latest version and the control is ok there. So, this is an example where you have fixed one fault and now introduced a new problem in that dialog, that wasn't there before. And this new problem affects all the 5 options at the top of the dialog. Please fix, and maybe use this example of a "regression in the code" to check that you don't do this sort of thing too often.

@rdstern I have fixed the problem you identified. 
can you have a look again 
Thanks

2024-10-28 11:42 UTC, rdstern approved these changes
Thanks @derekagorhom that looks fine now.  @N-thony over to you

2024-10-30 20:30 UTC, rdstern commented
@N-thony over to you

2024-10-31 08:21 UTC, derekagorhom commented on instat/dlgLinePlot.vb
> +        End If
I changed it from `AndAlso` to `OrElse`

2024-10-31 08:23 UTC, derekagorhom commented on instat/dlgLinePlot.vb
> +    End Sub
I have removed this sub, i think its from me making some changes in the designer

2024-10-31 08:26 UTC, derekagorhom commented on instat/dlgLinePlot.vb
> +        End If
No... these are the other options in the dialog

2024-11-01 07:08 UTC, derekagorhom commented
@rdstern can review this again

2024-11-01 12:16 UTC, rdstern approved these changes
@N-thony back to you

2024-11-05 09:33 UTC, merged